### ISSUE TITLE
[QUESTION] How to get sum of column values in footer. 

### ISSUE THREAD

**Issue by vinodkhandelwal** [tannerlinsley/react-table#101]
I need to sum the column values and show that in footer. Footer Demo seems to have missing the code.

**Comment by tannerlinsley** [comment]
If you can, do this outside of the footer function for performance reasons.  If you have a small dataset though, you could do it in the render function of the column footer:

Outside of column, more performant
```javascript
const data = [...]

let ageSum = 0
for (let i = 0; i <= data.length; i++) {
  ageSum += data[i].age
}

const columns = [{
  header: 'Age',
  footer: 'Total: ' + ageSum
}]
```

Inside column, less performant
```javascript
const data = [...]

const columns = [{
  header: 'Age',
  footer: () => {
    let ageSum = 0
    for (let i = 0; i <= data.length; i++) {
      ageSum += data[i].age
    }
    return 'Total: ' + ageSum
  }
}]
```

**Comment by vkkdw** [comment]
Thanks a lot for response. However, with this solution it is rendering value as 0. here is my code snippet.  


var marketValSum = 0;
var cashSum = 0;

const columns = [
    { accessor: 'name', header: 'Name',width: 205 },
    { accessor: 'marketValue', header: 'Market Value', footer: 'Total: ' + marketValSum},
    { accessor: 'cash', header: 'Cash', footer: 'Total: ' + marketValSum}
 ];

const AccountsGrid = (props) => {

    const accountData = props.accounts;
   if(accountData.length >0) {
        for (let i = 0; i < accountData.length; i++) {
          marketValSum += accountData[i].marketValue;
          cashSum += accountData[i].cash;
        }
    }

    return (
        <ReactTable
            columns={columns}
            data={props.accounts}
            className='-striped -highlight'
            defaultPageSize={10}
            />
    );
};

**Comment by tannerlinsley** [comment]
Try this:
```javascript
const AccountsGrid = (props) => {

    var marketValSum = 0;
    var cashSum = 0;
    
    const accountData = props.accounts;
    
    if(accountData.length >0) {
        for (let i = 0; i < accountData.length; i++) {
          marketValSum += accountData[i].marketValue;
          cashSum += accountData[i].cash;
        }
    }

    const columns = [
      { accessor: 'name', header: 'Name',width: 205 },
      { accessor: 'marketValue', header: 'Market Value', footer: 'Total: ' + marketValSum},
      { accessor: 'cash', header: 'Cash', footer: 'Total: ' + cashSum}
    ]

    return (
      <ReactTable
        columns={columns}
        data={props.accounts}
        className='-striped -highlight'
        defaultPageSize={10}
      />
    );
};
```

**Comment by vinodkhandelwal** [comment]
It works. thanks a lot.

**Comment by zarela** [comment]
You could also do this: 
`columns=[
   {
        Header: 'Total',
        accessor: 'total',
        id: 'total',
        Cell: props => <span>{props.value}</span>,
        Footer: <span>{_.sum(_.map(data, d => d.total))}</span>,
      }
]`

Assuming

**Comment by zarela** [comment]
You could also do this:

```columns = [
       {
         Header: 'Total',
         accessor: 'total',
         id: 'total',
         Cell: props => <span>{props.value}</span>,
         Footer: <span>{_.sum(_.map(data, d => d.total))}</span>,
       }
     ]
```

**Comment by Mike-SP** [comment]
I've been able to make the code above work, however, if my table is filterable, when the table displays a set of filtered rows, the footer sums do not change to match the rows. How can I make it recalculate the sum of the filtered rows only?

**Comment by gary-menzel** [comment]
@Mike-SP 
Instead of doing your aggregation on your raw data you need to add a `ref` to ReactTable and then call `getResolvedState()` on the `ref` to get the `sortedData` (which is also the `filtered` data) and aggregate over that.

https://github.com/react-tools/react-table/wiki/FAQ#how-do-i-get-at-the-internal-data-so-i-can-do-things-like-exporting-to-a-file

**Comment by RokHoang** [comment]
@gary-menzel How to change the value of footers? I can get filtered data but don't know how to change the footer. Can you give me an example?

**Comment by BigCheeze45** [comment]
@RokHoang and anyone that stumbles upon this in the future: [example on updating footer count with filtered data](https://codesandbox.io/s/1r6nyjk33j).

**Comment by phares** [comment]
> Footer: <span>{_.sum(_.map(data, d => d.total))}</span>

Hi @zarela am getting an error  '_' is not defined  no-undef

**Comment by thomasserio** [comment]
@phares Make sure you are importing lodash to use _

**Comment by ofrades** [comment]
If the data in the table was editable would this work to update the sum value accordingly?

**Comment by Ribosom** [comment]
For me the solution with _getResolvedState_ didn't work to get it working with filters. 

Howerver, I did find another solution. Here is my footer definition, for a the sum of a column with costs-data:

`{
    Header: "Costs",
    accessor: "costs",
    Footer: info => _.sum(info.filteredRows.map(row => row.values.costs))
}`

**Comment by nbrombal** [comment]
For anyone who stumbles on this like I did, here's a current method that worked for me. It uses the native JavaScript `Array.reduce` instead of Lodash's `sum` method, but either would work.
```js
{
  accessorKey: 'your_accessor_key',
  footer: ({ table }) => table.getFilteredRowModel().rows.reduce((total, row) => total + row.getValue('your_accessor_key'), 0),
}
```
Note that you may need to cast the return value of `row.getValue()` to a number to properly sum it.

**Comment by sandeepd4d** [comment]
> For anyone who stumbles on this like I did, here's a current method that worked for me. It uses the native JavaScript `Array.reduce` instead of Lodash's `sum` method, but either would work.
> 
> ```js
> {
>   accessorKey: 'your_accessor_key',
>   footer: ({ table }) => table.getFilteredRowModel().rows.reduce((total, row) => total + row.getValue('your_accessor_key'), 0),
> }
> ```
> 
> Note that you may need to cast the return value of `row.getValue()` to a number to properly sum it.

I am getting the total of age in my scenario.
Total of age's column is working fine but when I update any age with negative value, I get the total wrong. like my total is 200 and I update age from 20 to -20 then it will reduce 40 from 200 instead of 20. Can anyone explain why?

**Comment by RaGreen** [comment]
@sandeepd4d Difference between 20 and -40 is 40 :) It would be 20, if you change 20 to 0.

**Comment by NatalliaSh** [comment]
Hello, could you please help with rendering footer.
I calculated the sum and difined it like in example, but it doesn't appear in table
here is column definition
`data.columns.map((col) => ({
        accessorKey: col.id,
        cell: EditableCell,
        footer: ({table}: FooterProps) => {
          const sum = table
            .getFilteredRowModel()
            .rows.reduce((acc, row, index) => {
              if (index === 0) {
                return acc;
              }
              const value: number = parseInt(
                (row.getValue(col.id) as ValueType).value,
              );

              return isNaN(value) ? acc : acc + value;
            }, 0);

          return `${sum}`;
        },`
        
and I'm trying to render footer like:
`<tfoot>
          {table.getFooterGroups().map((footerEl) => (
            <tr key={footerEl.id}>
              {footerEl.headers.map((columnEl) => (
                <th key={columnEl.id} colSpan={columnEl.colSpan}>
                  {flexRender(
                    columnEl.column.columnDef.footer,
                    columnEl.getContext(),
                  )}
                </th>
              ))}
            </tr>
          ))}
        </tfoot>`

**Comment by 9mm** [comment]
how do we actually use 

            aggregationFn: "sum",

There is no documentation or examples anywhere that I can find, and I see no intuitive way to use this

**Comment by 9mm** [comment]
<tfoot v-if="table.getFooterGroups().length">
      <tr v-for="footerGroup in table.getFooterGroups()" :key="footerGroup.id">
        <td v-for="cell in footerGroup.headers" :key="cell.id" :colspan="cell.colSpan" :class="['select-none', { 'footer-group': cell.column.columnDef.columns?.length }]">
          <flex-render :render="cell.column.columnDef.footer" :props="cell.getContext()" />
        </td>
      </tr>
    </tfoot>


I tried `cell.column.columnDef.aggregatedCell` in my footer but it just returns an error

**Comment by database-migration** [comment]
> It works. thanks a lot.





https://openjs.space/questions/merge-arrays-in-map-function-based-on-label-and-aggregate-information

**Comment by giladv** [comment]
@tannerlinsley is the specified method still the preferred one in v8? 
aggregation methods can't be used for this?

**Comment by giladv** [comment]
OK so i fashioned a simple custom feature to help make column aggregations easy:
```ts
declare module "@tanstack/react-table" {

  interface Column<TData extends RowData, TValue>
    extends AggregatedColumnFeature {}
}

interface AggregatedColumnFeature {
  getValues: <TValue = number>() => TValue[];
}

export const AggregatedColumnFeature: TableFeature<any> = {
  createColumn: <TData extends RowData>(
    column: ColumnType<TData>,
    table: TableType<TData>,
  ): void => {
    column.getValues = () => {
      return table
        .getFilteredRowModel()
        .rows.map((row) => row.getValue(column.id));
    };
  },
};
```

to use it, in the column def:
```ts
col.accessor("price", {
  header: "Price",
  footer: ({ column }) =>sum(column.getValues())
}),
```

keep in mind this will be not really efficient for huge datasets. in that case as suggested a memo will help.

**Comment by sandeepd4d** [comment]
Thanks for reply [RaGreen](https://github.com/RaGreen), I understood your point and It worked for me.
> [@sandeepd4d](https://github.com/sandeepd4d) Difference between 20 and -40 is 40 :) It would be 20, if you change 20 to 0.
