### ISSUE TITLE
[QUESTION] Search form fields slow down when rendering many rows 

### ISSUE THREAD

**Issue by sshaginyan** [tannerlinsley/react-table#103]
First, I would love to see an example of this using redux.

I have a container component that has both a form and react-table. Every change on the form means a new render for react-table which is extremely slow. Here is a sample http://54.219.188.76/search. I've managed to put the form and react-table in two different containers so that the form will have its own render and react-table will has its own. But now it's extremely difficult managing my redux state between the two components especially `loading` for some reason. Can you give me some suggestions/advice/patterns on how to use react-table with redux? 

I'm using react-redux and everytime I change my redux state componentWillReceiveProps get called followed by a render. However the render doesn't happen unless I change the key on <ReactTabel key={xyz} />

**Comment by tannerlinsley** [comment]
You can manage the entire table using a fully controlled mode (see fully
controlled component in the docs) which should work really well with redux
