### ISSUE TITLE
[QUESTION] Browser support

### ISSUE THREAD

**Issue by fc** [tannerlinsley/react-table#105]
Is there a specific range of browsers you specifically support?  Most interested to know if you support IE11+.  Perhaps this information be added into your readme.

**Comment by tannerlinsley** [comment]
Not entirely sure. Off the top of my head I would say just modern browsers.
But it would only take a few polyfills to support more.

**Comment by fc** [comment]
Grabbed a laptop that had IE11 from QA - seemed to work without any issues.

**Comment by tannerlinsley** [comment]
Nice!

**Comment by kumarsunny0013** [comment]
In safari The react table is not working. Any idea HOW CAN WE FIX THAT?
