### ISSUE TITLE
Custom comparator for ordering data

### ISSUE THREAD

**Issue by cesalberca** [tannerlinsley/react-table#107]
Hi again!

I'm here this time with a more complex problem. So here it goes:

I have a data structure as follows: 

```
data : [
  {
    name: 'A cool name'
    phaseWithPriority: {
      priority: 'keyOfPriority',
      phase: 'keyOfThePhase'
    }
  }
];
```

I have a property with both, the phase and priority because I want to render both fields in the same column. This is done correctly with the following code:

```
this.columns = [
  {
    id: 'phaseWithPriority',
    accessor: d => d.phaseWithPriority,
    render: row => (
      <span style={Object.assign({
        backgroundColor: row.value.priority === 'priority0' ? '#000000'
          : row.value.priority === 'priority1' ? '#e22900'
          : row.value.priority === 'priority2' ? '#f9c118'
          : row.value.priority === 'priority3' ? '#48ab04'
          : '#48ab04'
        }, estilos)}>
        {row.value.phase || '0'}
      </span>
    )
  }
  ...rest of columns
];
```

This renders what I want. However, and this is where I don't know how to proceded, when I order the column, I want it to be ordered by priority and this orders by the phaseWithPriority object.

So how could I set __for which property of the object__ react table should order by?

For the moment I can order priorities alphabetically, which matches the expected results, however it would be very cool to pass custom ordering function to that column. This was also mentioned in [other issue](https://github.com/tannerlinsley/react-table/issues/88). So we could do something like this:

```
this.orderValues = [
  {
    name: 'priority0',
    value: 2
  },
  {
    name: 'priority1',
    value: 4
  },
  {
    name: 'priority2',
    value: 3
  },
  {
    name: 'priority3',
    value: 1
  }
];

function customComparator(a, b) {
  // We find by key in orderValues the object which contains the value for ordering
  const orderValueA = orderValues.find(item => item.name === a.priority);
  const orderValueB = orderValues.find(item => item.name === b.priority);
    
  // Order them
  return orderValueA.value > orderValueB.value ? -1 : 1;
}

this.columns = [
  {
    id: 'phaseWithPriority',
    accessor: d => d.phaseWithPriority,
    sortFunction: customComparator,
    render: row => (
      <span style={Object.assign({
        backgroundColor: row.value.priority === 'priority0' ? '#000000'
          : row.value.priority === 'priority1' ? '#e22900'
          : row.value.priority === 'priority2' ? '#f9c118'
          : row.value.priority === 'priority3' ? '#48ab04'
          : '#48ab04'
        }, extraStyles)}>
        {row.value.phase || '0'}
      </span>
    )
  }
  ...rest of columns
]
```

[Here is a working example](http://codepen.io/cesalberca/pen/KWzeEZ?editors=0011). Please keep in mind that this isn't exhaustively tested and it might not be fully optimized.

Thank you for your time!

**Comment by tannerlinsley** [comment]
So first. Make the accessor point to only the phase. This will give you the
sorting you want. Then in your render function, just use both phase and
priority. The accessor function isn't the only data you can utilize in your
renderer. You can reference any other value in that row object via
rowInfo.row.

**Comment by cesalberca** [comment]
It works! Thank you so much! I could add a section to the README if you'd like including how you can utilize the fields of several columns using the process you described.
