### ISSUE TITLE
Cannot read property 'className' of undefined

### ISSUE THREAD

**Issue by eyerean** [tannerlinsley/react-table#108]
I get this error and it's located in the utils.js file:
```
function splitProps(_ref2) {
  var className = _ref2.className, //<---here
      style = _ref2.style,
      rest = _objectWithoutProperties(_ref2, ['className', 'style']);

  return {
    className: className,
    style: style,
    rest: rest
  };
}
```
I understand that it has something to do with my column headers, so here is (sort of) my columns definition:

```
columns: [
      {
        header: 'Sections',
        columns: [{
          header: 'Section',
          accessor: 'sectionName',
          sortable: false
        }, {
          header: 'Sub-Section',
          accessor: 'subSectionName',
          sortable: false
        }]
      },
      {
        header: 'KPIs',
        columns: [{
          header: 'KPI',
          accessor: 'kpiName_1',
          minWidth: 200,
          sortable: false,
          render: props => <span>{props.row && props.row.kpiName_2 ? '' : props.value}</span>
        }, {
          header: 'Sub-KPI',
          accessor: 'kpiName_2',
          minWidth: 140,
          sortable: false,
          render: props => <span>{props.row && props.row.kpiName_3 ? '' : props.value}</span>
      //more columns like that
        }]
      },
      {
        header: 'Details',
        columns: [{
          // more columns here
          header: 'NO',
          accessor: 'kpiNumber',
          render: rowInfo => <span>{rowInfo.value}</span>,
          width: 50,         
          sort: 'asc' //i know, but that is still the only way sorting works for me, @5.3.4
        }]
      },
      {
        header: () => <span>{this.props.selectedYear}</span>,
        columns: [{
          header: 'Apr',
          id: 'april',
          accessor: data => data.months && data.months.length > 0 && data.months[3].value,
          width: 70,
          sortable: false,
          render: ({index, value, row, aggregated}) => this.handleMonthValuesRender(index, value, row, aggregated, 3)
        },{
         // more columns 
        }]
      }
    ]
```

I tried removing all grouped headers but didn't fix the issue.

Any help is much appreciated, maybe I have to check something different than the columns too, I don't know.

EDIT: To be more specific, probably the problem is with my code and not `react-table`, so I would like to know what causes this error.

**Comment by tannerlinsley** [comment]
Paste the code to your component

**Comment by eyerean** [comment]
I don't understand which code I should paste to my component.

**Comment by tannerlinsley** [comment]
Wherever you are using `<ReactTable />`

**Comment by eyerean** [comment]
I understood this, I don't understand _what_ code should be pasted. I pasted the splitProps function but don't really know what to do with, what does `_ref2` and `_objectWithoutProperties` represent?

I know the problem is the props I pass to the table, so if I know which properties are causing this error to appear it will probably help me fix my props.
Looks like the table is rendered before the moment I want it to and my componentDidUpdate [in the parent component] is not called and I cannot pass the correct props. But I would like to see what exactly is missing

**Comment by tannerlinsley** [comment]
Right.  This is likely not being caused by any of your column definitions, but instead a property being used directly on `<ReactTable />`.  We'll need to see all of those properties to determine the issue. This is what we need to see from your code:
```
<React Table
  prop={val}
  prop={val}
  prop={val}
  ...
/>
```

**Comment by eyerean** [comment]
Ah wow I didn't get this before, ok. So:

```
<ReactTable
          loading={loading} 
          className="-highlight"
          data={data}
          columns={columns}
          defaultPageSize={numOfSections}
          showPagination={false}
          showPageJump={false}
          showPageSizeOptions={false}
          pivotBy={['sectionName', 'subSectionName']}
          getTrProps={this.handleTrStyle}
          freezeWhenExpanded={true}
          //defaultSorting={[{ //should work this way and not with sort='asc' but...
            //id: 'kpiNumber',
            //desc: false
          //}]}
        />
```

`numOfSections` is always a number, never `undefined`.
`data` is the property that changes, it's an array of objects this way:
```
{
  kpiFreq: "string",
  kpiId: "string",
  kpiName_1: "string",
  kpiNumber: number,
  kpiType: "string",
  months: Array[12], //these objects are sometimes with empty strings, 
                //but i catch that case on the columns definitions
  sectionName:"string"
  sectionNumber: number,
  subSectionName: "string"
}
```

**Comment by tannerlinsley** [comment]
Could it be something in getTrProps?

**Comment by eyerean** [comment]
Sorry for the late response! Turns out it was some wrong data in the database :)

**Comment by MostafaEbrahimi** [comment]
May you explain what wrong with data ? I have same issue @eyerean

**Comment by eyerean** [comment]
I have no access anymore to the BE for that repository, but I believe the error was some mapping between the database and the BE. Checking now my code and it looks the same as I had pasted it here, with the difference that I passed also some booleans to the `show` property of the columns.
Can it be that a `render` of one of you columns is accessing a property named differently?

**Comment by nrai** [comment]
Were you able to fix this issue @MostafaEbrahimi I am getting the same issue

**Comment by MostafaEbrahimi** [comment]
No! problem not solved and I use another way to solve my problem. @nrai

**Comment by slightlyoffbeat** [comment]
I had this problem as well. Same error code, and I narrowed the issue down to gettrbyprops. Turns out I didn't have a return. I had a return in my if statement: if (rowInfo && rowInfo.row) 

...but if that if statement failed there was no return. I just returned an empty object and it works now, which makes sense. Hopefully this helps.

**Comment by boksasp** [comment]
I had this issue when testing a component which rendered a react-table.
I'm was just sending in the function `() => {}` to _getTrProps_ to then spy on the function to see if it had been called. I don't need it to do anything. 

Anyway, I got the error that OP got, and had to change the function to `() => ({})` for it to return something.

**Comment by AbhaysinghBhosale** [comment]
in my case if i added a the condition in getTdProps to check undefined then this issue get triggered. Can anyone let me know the solution for this.

**Comment by ddsr17** [comment]
I am facing this issue due to getTrProps, below is the props code passed into react table.
@tannerlinsley please help.
Also, I haven't used the return statement before onClick because of linter causes issue when I do that.

getTrProps={() => {
            onClick: (e, handleOriginal) => {
              if (handleOriginal) {
                handleOriginal();
              }
              this.props.onClick();
            };
          }}

**Comment by bstrihova** [comment]
I was getting: Cannot read property 'className' of undefined
I was trying to put a MUI Tooltip inside of MUI TableCell, all I had to do was to not pass child as a plain string, had to wrap it in a paragraph, this might help someone :) 

Before:
`<TableCell>
<Tooltip title="hello world">
text
</Tooltip>`

After:
`<TableCell>
<Tooltip title="hello world">
<p>text</p>
</Tooltip>`

**Comment by SabrinaDanielle** [comment]
> in my case if i added a the condition in getTdProps to check undefined then this issue get triggered. Can anyone let me know the solution for this.

Hello, did you resolve this?

**Comment by vtarelkin** [comment]
@SabrinaDanielle 
```
    const rowProps = useCallback((state, rowInfo) => {
        if (rowInfo && rowInfo.row) {
            const isRowHovered = rowInfo.index === hoveredRow;
            return {
                style: {
                    background: isRowHovered ? '#D1DDE1' : ''
                },
                onMouseEnter: () => {
                    setHoveredRow(rowInfo.index)
                },
                onMouseLeave: () => {
                    setHoveredRow(null)
                }
            }
        }
            **return {};**
    }, [hoveredRow]);
```
