### ISSUE TITLE
Cannot read property 'isReactComponent' of undefined

### ISSUE THREAD

**Issue by rpalermodrums** [tannerlinsley/react-table#109]
Our previously working table code breaks when upgrading from 5.1.0 to 5.1.1 assumedly as a result of this line: [38522](https://github.com/tannerlinsley/react-table/commit/3852227bddeba81b15a51b410cde5b49b2116b73#diff-1fdf421c05c1140f6d71444ea2b27638R749). We are using a reusable function that returns a single `div`. Was this an intended change?

for example:
```
function renderDateCell (item) {
  return <div>{formatDate(item.value)}</div>;
}
```
```
const columns = [
  {
     header: 'Date',
     accessor: 'date',
     minWidth: 150,
     render: renderDateCell,
  },
  ...
];
```
```
<ReactTable
  ...
  columns={columns}
/>
```

**Comment by tannerlinsley** [comment]
That should work fine. Render functions should be able to handle react
components, classes, stateless components, traditional functions or strings

**Comment by rpalermodrums** [comment]
Ah, You're right. The issue was not with any of the simple div cells, but rather with two of our more nested ones. I solved the problem by simplifying them a bit. Thanks for the reply!

**Comment by tannerlinsley** [comment]
You bet!  Glad it’s working :)

**Comment by tmsh** [comment]
Doesn't this break when using arrow functions? E.g., in the examples? If I change the Custom render example to:
`render: function(row) {`

it works for me. Otherwise it errors. I'm using node v7.5.0 for what it's worth.

Cheers, Tom

**Comment by tannerlinsley** [comment]
Interesting. So arrow functions don't work for you that return jsx?

**Comment by tmsh** [comment]
Right, yeah. Exactly.

**Comment by tannerlinsley** [comment]
Yeah we need to fix that. Any idea why it's not working? There is a
normalizer function in the source that is supposed to handle arrow
functions among other things

**Comment by rpalermodrums** [comment]
@tannerlinsley Looks like the issue is inside of the `normalizeComponent` method [L195-L196](https://github.com/tannerlinsley/react-table/blob/265a5c8753ff8d7e45bbcd8d026768310187f735/src/utils.js#L195-L196). Arrow functions don't have a `prototype` like regular ones do.

**Comment by mfonsen** [comment]
Also it appears that bound functions don't have a prototype so I'm hitting this same error.

Use case: let the render function know the id of the column and the name of the data source it's rendering

**Comment by tannerlinsley** [comment]
The `normalizeComponent` method just needs to account for this then.  Can
anyone think of a reliable way to detect an arrow function, etc.?

**Comment by rpalermodrums** [comment]
@tannerlinsley One solution that may work is to use `Object.getPrototypeOf(Comp).isReactComponent` instead of `Comp.prototype.isReactComponent`. Regular functions, arrow functions, and bound functions return the same "function" prototype in that case, which seems to be the intended behavior.
