### ISSUE TITLE
Is there a way to select rows from the table?

### ISSUE THREAD

**Issue by bartvde** [tannerlinsley/react-table#11]
So similar to onRowClick in fixed-data-table

**Comment by tannerlinsley** [comment]
Check this old issue out: https://github.com/tannerlinsley/react-table/issues/10 and let me know if that clears things up?

**Comment by tannerlinsley** [comment]
For now you can use the `render` and `header` callbacks on a column definition, or even decorate/replace the entire `tr`/`td` component if you wish and implement some custom click functionality.  @Vaevictus's solution in #10 seems to work great.

**Comment by bartvde** [comment]
thanks that works great, had missed that ticket

**Comment by tannerlinsley** [comment]
👍 Anytime :)
