### ISSUE TITLE
[QUESTION] How to toggle sorting with customize header UI?

### ISSUE THREAD

**Issue by lingchn** [tannerlinsley/react-table#112]
By default when the _sortable_ flag for a column is set to true, clicking the table header on that column will toggle sorting. I am customizing my headers to include some filter input boxes, if I set _sortable_ to true, as soon I click anywhere inside the header, sorting will trigger. Is there anyway to get access something like a toggleSort function, so I can add custom UI like a button to trigger sorting only when the button is clicked?

Thanks!

**Comment by spacedarcy** [comment]
My workaround for this has been to put the controls in header groups that correspond to their respective headers.

**Comment by tannerlinsley** [comment]
You should consider overriding the core component for the header. This way
you can control when the sort method is called.

**Comment by tannerlinsley** [comment]
https://github.com/tannerlinsley/react-table#component-overrides

**Comment by lingchn** [comment]
Thanks for the tips.

I found the toggleSort function in the props for ThComponent, but I couldn't figure out how to pass the function down to each child. I ended up following @spacedarcy's workaround, which is pretty straightforward.

**Comment by tannerlinsley** [comment]
Awesome.  If you think the docs could be more clear, or the api bettered, let me know and we can talk PR :)

**Comment by sleepyfoodie** [comment]
is there anyway override the core component for the header in version 7?
