### ISSUE TITLE
optionally remove column width

### ISSUE THREAD

**Issue by kchojhu** [tannerlinsley/react-table#113]
Thanks for the great plugin! I see that default value for min-width 100 but in my case I don't want to set the width of the column and just let the browser calculate the width to show the values.  I try to set the 'minWidth' or 'width' to null or undefined but didn't work.

**Comment by scottclayton** [comment]
You may want to check out a proposed solution in issue #94 

It is handled via looping over the data and setting some state

**Comment by kchojhu** [comment]
Thanks for fast reply! I'll try that out

**Comment by tannerlinsley** [comment]
I second @scottclayton's suggestion.  For now, there is no built-in way of auto-sizing columns, but his solution works fairly well for now.
