### ISSUE TITLE
JSX passed to footer property does not receive expected arguments

### ISSUE THREAD

**Issue by michaelbridge** [tannerlinsley/react-table#115]
`const columns = [{ accessor: 'keyA', header: "Title A", footer: (o) => { console.log(o) }]`

o is an empty object rather than {data, column} as indicated in the documentation.  This prevents desired actions such as summing all the rows in the table for the specified column.

I've created a workaround using refs to access the applicable row/column information, however this approach is not React-like and generally undesirable.

**Comment by tannerlinsley** [comment]
Would you like to locate the bug and PR a fix?

**Comment by michaelbridge** [comment]
PR is open.
