### ISSUE TITLE
Support ticket : question about Event onExpandSubComponent

### ISSUE THREAD

**Issue by yukund** [tannerlinsley/react-table#118]
Hi react table team
Thank you for providing such useful table component, it is very easy to integrate it with my project and saves me a lot of time to write table related code.

I have a question about onExpandSubComponent. I have defined a subComponent. see the sample code below.

I want to click the rt-expander in order to show the sub component and make a web service call in the same time. However, when I click the rt-expander,  the onExpandSubComponent event is not trigged. 

Any suggestions?  

Thanks
Yanbo

```
<ReactTable
          data={data}
          columns={columns}
          SubComponent={(row) => {
            return (
              <div>
                You can put any component you want here ... 
            </div>
            )
          }}
           onExpandSubComponent={(event)=>{
             //make a web service call 
             console.log("expanded");
          }}
         .  . .
```

**Comment by tannerlinsley** [comment]
Try onExpandRow. Looks like the on expand sub component prop wad deprecated but the docs were not updated. You could PR a fix for the docs if you wished :)
