### ISSUE TITLE
Max height without paging?

### ISSUE THREAD

**Issue by PetrSnobelt** [tannerlinsley/react-table#120]
Hello, first of all, thank you for wonderful component, it looks really great, documentation and storybook is also well done.

I would like to use it with lot of rows, but instead of paging I prefer render with specified max-height and scroll through rows (sometimes called table freeze headers) Is it possible without writing my own render?

Thank you

**Comment by tannerlinsley** [comment]
Should be. Just put a css max height on the table body and it will scroll
vertically as well :)

**Comment by PetrSnobelt** [comment]
I hope so, but when I add height:100px on rt-tbody, it stretch rows height to unusable low height

**Comment by tannerlinsley** [comment]
Ah. That's because the whole table layout is based on flex box. You will
probably need to change the table body to have justify-content: flex-start
and possibly give your tr rows a fixed height.

**Comment by PetrSnobelt** [comment]
Thanks, it needs some more css tweaks, If anyone is interested here is working css:
(based on https://codepen.io/anthonyLukes/pen/DLBeE)
```
.rt-tbody {
        height:100px;
        justify-content: flex-start;
        flex: 1 1 auto;
        position: relative; /* need this to position inner content */
        overflow-y: auto;
      }
      .rt-tr-group {
        min-height:25px
      }
      .rt-thead {
        flex: 0 0 auto;
      }
```
Improvements or suggestions welcomed
