### ISSUE TITLE
Is there a searchbox? (question)

### ISSUE THREAD

**Issue by aikonplus** [tannerlinsley/react-table#123]
Hey,

I just wonder if react-table has support for a search box? I can not find anything about it in the docs, is there one or will I need to implement the "search"/"filter" component myself?

regards

**Comment by mikedevita** [comment]
you need to implement your own that filters the array of the `data` prop.

**Comment by aikonplus** [comment]
ok thanks. Kind of missing this feature out of the box, since I saw it in all the other table implementations so far, and am actually wondering why it is missing in react-table. So if I am allowed to make a wish for the future versions...

**Comment by mikedevita** [comment]
yeah maybe @tannerlinsley will implement it or accept a PR. problem is there are so many ways to accomplish this it's hard to cover all the bases for everyone.

**Comment by tannerlinsley** [comment]
Mike nailed it. There are so many ways to implement this that it would be
near impossible to satisfy everyone without writing a lot of edge case
code. Instead I tried to provide a really nice API and a clear path to make
your own. I think the wiki would benefit from a solution for this.
