### ISSUE TITLE
Want to hide the first row values of the columns

### ISSUE THREAD

**Issue by prateek04** [tannerlinsley/react-table#1246]
# STOP

We do not track feature requests through Github. Please use the [Spectrum React Table Forum](https://spectrum.chat/react-table) to talk about new ideas and features.
[
![hide_first_row_value](https://user-images.githubusercontent.com/13849977/52193954-be462c80-2877-11e9-821d-037fad1be8b0.png)
](url)

**Comment by tannerlinsley** [comment]
https://spectrum.chat/react-table
