### ISSUE TITLE
Lazy Render pages

### ISSUE THREAD

**Issue by nikolayg** [tannerlinsley/react-table#1250]
Hey guys, I tried asking my question on spectrum.chat, but it kept giving an error and couldn't post :(

I have a pretty big table, which I'm rendering in pages. I feel that all the pages are rendered at once, although only 1 is displayed at a time, which is creating a performance issue.

Is it possible to lazy load pages when the user navigates to them?

**Comment by tannerlinsley** [comment]
Going to close this since it's not an issue, but we can continue to discuss here if you'd like.

How many columns and rows is your table?

**Comment by nikolayg** [comment]
Thanks @tannerlinsley , I've got about 2000 rows and 9 columns. One of the columns has a customer renderer (i.e. `Cell`) for which I've used a `React.memo`-ized component. The page size is 50.

The first table page actually shows quite quickly, but then I can't click anywhere else on the page for a while. I assume this is because `react-table` keeps rendering the rest of the pages. 

Is it possible to lazy render just the current page (including filters and sorting)? I've seen examples of fetching from the server dynamically, but I already have all the data on client.

**Comment by tannerlinsley** [comment]
So to be clear, the rest of the rows are not being rendered unless they are
on the current page. However, all rows are being sorted and filtered
incrementally as sorting and filters change. If you're familiar with it,
you could run Chrome's profiler while this happens, and then
Save and post the profile here. That would tell us more about why it's
being slow.

Another thing to check is if all of the props you're sending to react table
are immutable and only being created once, or changing only when the table
needs to update.

**Comment by mike391** [comment]
@nikolayg from my experience react-table will re-sort the whole dataset on initial load as well as on any datachanges. You can try to use an alternative sort method that is faster if you can find one to improve this.

**Comment by tannerlinsley** [comment]
In the next v7, you'll be able to opt out of auto-sorting. Thus you could do the sorting on your own and pass the data straight in. This is a very advanced thing to take on yourself IMO, but I guess everything should be possible... :)
