### ISSUE TITLE
Header Group column width calculated wrong in complex configuration on some screen sizes

### ISSUE THREAD

**Issue by rndm2** [tannerlinsley/react-table#1251]
**Describe the bug**
On complex table configurations header group column width calculated wrong in some cases 

**To Reproduce**
1. Go to https://codesandbox.io/s/oqqvz96v45
2. Resize table frame to width 1115px
3. Look on header group

**Expected behavior**
Header group column width calculated ok

**Codesandbox**
https://codesandbox.io/s/oqqvz96v45

**Screenshots**
<img width="1110" alt="screen shot 2019-02-06 at 15 17 15" src="https://user-images.githubusercontent.com/6842505/52328542-97782980-2a22-11e9-9799-4baf8444622b.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: 72

**Comment by tannerlinsley** [comment]
Looks good to me.

<img width="1627" alt="screen shot 2019-02-06 at 4 58 31 pm" src="https://user-images.githubusercontent.com/5580297/52381894-7d454800-2a30-11e9-832e-61de7e95d298.png">

**Comment by rndm2** [comment]
> Looks good to me.
> 
> <img alt="screen shot 2019-02-06 at 4 58 31 pm" width="1627" src="https://user-images.githubusercontent.com/5580297/52381894-7d454800-2a30-11e9-832e-61de7e95d298.png">

On your screenshot table size is 1645 px, please resize it to 1115px
I have attached video: https://youtu.be/XsgULf5VAB4

**Comment by tannerlinsley** [comment]
Ah, I see it now. Not sure how I missed that.

I'm not sure what is causing this, but I've never seen it in the wild, even with all of the enterprise companies who use RT, or in my own apps, until now. 

There's 2 paths we can take from here:
- You can diagnose it and issue a PR to fix it in the 6.x version
- You can wait until v7, which is headless, and assume control of the rendering yourself.

Either way, I personally have moved on to v7 development and don't intend to dive back into v6 very far.

Thoughts?

**Comment by rndm2** [comment]
Okay, I will try to fix it. 
By the way, current v6 branch is broken

**Comment by tannerlinsley** [comment]
Right. #1243

**Comment by rndm2** [comment]
It looks like flex issue, 
The only one way to fix this I know: to set width based on actual column width from DOM, not css width

**Comment by tannerlinsley** [comment]
v7 will be a headless hook and won't provide any UI, so this issue won't technically exist in the future. For now, there isn't too much we can do in v6 I guess.
