### ISSUE TITLE
Default Expander for SubComponent stopped working after upgrade to v6.9 from v6.8.6

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [tannerlinsley/react-table#1256]
# Using v6?
Yes v6.9

# Using v7?
No

**Describe the bug**
I have used the react table to show some logs in application. I was using the default expander which shows the subcomponant. just few days ago expander stopped working on prod after investigation i found the package version is different so i have updated the package on local machine and i am able to replicate the issue.

**Comment by bmashall** [comment]
@AbhaysinghBhosale I had the same problem. for me the solution was just to add `{expander: true}` into the columns array.

**Comment by Misza508** [comment]
I had the same problem with SubComponent.

**Comment by tannerlinsley** [comment]
This is being tracked in #1243
