### ISSUE TITLE
current v6 version does not compile

### ISSUE THREAD

**Issue by jbauerrfid** [tannerlinsley/react-table#1257]
# Using v6?
issue on v6, commit 410417d0677cdd79d19da3e37e2ddbb2df9b58a5

the current v6 branch does not compile, caused by https://github.com/tannerlinsley/react-table/pull/1249#discussion_r254681761

**Comment by tannerlinsley** [comment]
This is being tracked in #1243

**Comment by tannerlinsley** [comment]
We'll keep this open for your PR though

**Comment by tannerlinsley** [comment]
Fixed
