### ISSUE TITLE
v7 sandBox infinite scroll not working when using server-side data

### ISSUE THREAD

**Issue by Anton-4** [tannerlinsley/react-table#1259]
First of all, thank you for this useful framework!

**Describe the bug**
In the v7 sandbox example, infinite scroll does not seem to be working when using Server-Side data.
After the last row "Loading more..." is shown but the data never loads.

**To Reproduce**
1. Go to the [v7 sandbox](https://codesandbox.io/s/m5lxzzpz69)
2. Click on "Server-Side Data"
3. Click on "Toggle Infinite Scrolling"
3. Scroll down to the last row
4. "Loading more..." does not go away

**Expected behavior**
Additional rows should be loaded when scrolling down.

**Desktop:**
 - OS: Ubuntu 18.04
 - Browser: Firefox 65.0 
 - Version: 7.0.0-alpha.2

**Comment by tannerlinsley** [comment]
Infinite scrolling for server-side has not yet been implemented.

**Comment by tannerlinsley** [comment]
But it's more than possible ;)
