### ISSUE TITLE
Adding custom operator in individual column

### ISSUE THREAD

**Issue by kea0811** [tannerlinsley/react-table#1260]
I have been researching on react table, but i couldn't find any answer related to my question. Just wondering if react table offer the following function that we specify default filter operator in column. ie, contain, greater or equal and etc

**Comment by tannerlinsley** [comment]
Yes. Each column can take its own via `column.filterMethod`. Search `filterMethod: (filter, row || rows,` in the [v6 docs](https://github.com/tannerlinsley/react-table/tree/v6#columns) for more info.

**Comment by kea0811** [comment]
Does it support server side? I tried and it only work on client side filtering

**Comment by tannerlinsley** [comment]
Server side data is supported, but when using it, the client is not responsible for filtering.
