### ISSUE TITLE
Examples Page is Down

### ISSUE THREAD

**Issue by mlersch** [tannerlinsley/react-table#1261]
Hi,

Tried to access the examples page at https://react-table.js.org/#/story/simple-table
But only getting a Cloudflare Error 1101

Hope you get this back up again, because it was a great source for me to learn how to integrate react-tables into my project.

**Comment by tannerlinsley** [comment]
The examples for v6 have been archived into the v6 branch at this location: https://github.com/tannerlinsley/react-table/tree/master/archives/v6-examples.

Feel free to open any of them in a codesandbox or locally to see them in action!

The React-Table.js.org site will soon be redirecting to the github repo. The repo will then be used as the primary source of documentation.

**Comment by mlersch** [comment]
Thanks for the quick response. Works!.. not so handy as the old solution but I can work with it.
Thank you very much!

**Comment by frankhale** [comment]
I was disappointed to find out the example site was removed. Searching through the examples folder by folder is not nearly as easy as it was on the website =(

**Comment by tannerlinsley** [comment]
A new examples experience will be available soon.

**Comment by KillerAyce** [comment]
> The examples for v6 have been archived into the v6 branch at this location: https://github.com/tannerlinsley/react-table/tree/master/archives/v6-examples.
> 
> Feel free to open any of them in a codesandbox or locally to see them in action!
> 
> The React-Table.js.org site will soon be redirecting to the github repo. The repo will then be used as the primary source of documentation.

Hi I am not seeing Any HOC examples like Select Tree

**Comment by toddcoulson** [comment]
In the future maybe don't take down an old examples page before the new release of examples page is finished.
