### ISSUE TITLE
Column Header Groups broken in 6.9.1

### ISSUE THREAD

**Issue by Android3000** [tannerlinsley/react-table#1262]
I'm creating this to track a new bug that I'm seeing in 6.9.1.  I understand that there may not be fixes being added except from the community for 6.x, but wanted to track this for visibility for anyone else who encounters this.

I have a reproducible example, but will have to see if I can actually find the underlying cause in terms of trying to contribute a PR to fix this.

**Describe the bug**
When using [column header groups](https://github.com/tannerlinsley/react-table/tree/v6#column-header-groups), a reference error is thrown:
```
i is not defined
makeHeaderGroups
../src/index.js:266:10
```

**To Reproduce**
Here is a very simple failing example:
https://codesandbox.io/s/p9xo6wrj8m

The header column with the nested columns is what causes the failure to occur. This previously worked in 6.8.6 and 6.9.0 (you can see this by flipping the version number back in the package.json in the example above).

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version: 71

**Comment by Android3000** [comment]
@tannerlinsley I think I know what may be going on here. The [PR reverted here](https://github.com/tannerlinsley/react-table/pull/1249/commits/dd192759df1d9ca7a2ab147295519eef457733d7) rolled back the method signature to `makeHeaderGroups = ()` from `makeHeaderGroups = (row, i)`. However, other PRs that were not reverted added in code to take advantage of that -- namely, the addition of a Key property in the returned TheadComponent: ```key={`${i}-${row.id}`}```

I'm wondering if there are more PRs that need to be reverted to fully eliminate the recursive header groups changes that were impacting 6.9.0?

**Comment by tannerlinsley** [comment]
Possibly. I'm not aware which ones though.

**Comment by tgirgin23** [comment]
We have had the same issue on our side. This only happens on **6.9.1**.

**Comment by leovo2708** [comment]
Same issue after upgrading to 6.9.1

**Comment by mrTurkay** [comment]
same issue

I turned v-6.8.1 back

**Comment by mrTurkay** [comment]
it also broke resizer, 

when you try to resize, column lines are broken

**Comment by npomfret** [comment]
Anyone know what the last working version is in NPM that doesn't suffer from this issue?

**Comment by Android3000** [comment]
For the issue I mentioned, technically it works in 6.9.0, but that has some of its own other issues. 6.8.6 is probably what you want.

**Comment by tannerlinsley** [comment]
6.9.2 is out now. Hopefully it fixes this problem.

**Comment by Android3000** [comment]
Thanks! I can confirm that my CodeSandbox example is now working after updating to 6.9.2.
