### ISSUE TITLE
Page documentation

### ISSUE THREAD

**Issue by xaipo-mardis** [tannerlinsley/react-table#1267]
Hi what happen with the documentation page, i can't see the part of selections in the new documentation please XD

**Comment by tannerlinsley** [comment]
All documentation for v6 is here: https://github.com/tannerlinsley/react-table/tree/v6/ and all of the v6 examples are here: https://github.com/tannerlinsley/react-table/tree/master/archives/v6-examples

**Comment by xaipo-mardis** [comment]
ok thanks
