### ISSUE TITLE
Docs don't rendering react

### ISSUE THREAD

**Issue by luizverissimo** [tannerlinsley/react-table#1268]
I access the docs page, there is an error message saying this: 

Error 1101 Ray ID: 4a877182db75baf2 • 2019-02-13 12:54:24 UTC
Rendering error

PrintScreen
https://i.imgur.com/dO4t97Z.png

**Comment by tannerlinsley** [comment]
The old docs have been deprecated. If you're looking for the v6 readme, plase go here: https://github.com/tannerlinsley/react-table/tree/v6
