### ISSUE TITLE
Bug in column resize

### ISSUE THREAD

**Issue by andreaci** [tannerlinsley/react-table#1272]
Using v6.

**Describe the bug**
Resizing a column doesn't work 

**To Reproduce**
1. Go to 
2. Resize a column
3. Strange glitches in sizes

**Codesandbox!**
https://codesandbox.io/s/50m2okv80x

**Additional context**
Created a pull request with the solved BUG:
https://github.com/tannerlinsley/react-table/pull/1271

**Comment by albertoarraco** [comment]
I have the same problem

**Comment by andreaci** [comment]
> I have the same problem

as a temporary WORKAROUND; set minResizeWidth to ALL columns or recompile the package using my pull request

**Comment by albertoarraco** [comment]
Thanks! Now it’s works!

**Comment by andreaci** [comment]
closed; now merged in v6

**Comment by xcv58** [comment]
Thanks, do you have estimated time to release the fix?

**Comment by brandonburkett** [comment]
Same, I hit this issue today and we have quite a few tables I would need to update, any ETA?

**Comment by thomasmi** [comment]
Hi, I updated to 6.9.2 today and this still appears to be an issue. Please see take a look at this codesandbox:
[](https://codesandbox.io/s/vv7o2w86p0)

**Comment by saveriocaminitiktech** [comment]
Same problem here (with version 6.9.2).

**Comment by brymon68** [comment]
Agreed. Same problem. This was working for a while but somehow reverted.....

**Comment by saveriocaminitiktech** [comment]
Bug solved with 6.10.0.
No changes in my code required.

**Comment by lstickelhube** [comment]
same bug in 6.10.0

**Comment by lstickelhube** [comment]
fixed it by adding correctly the ids for every column
