### ISSUE TITLE
What happened to the site with all the examples?

### ISSUE THREAD

**Issue by netmajor** [tannerlinsley/react-table#1273]
Hi
I am only copy question from Spectrum asked by @chobo2
"I am using Version 6 and I am looking for the site that had lots of examples that linked to live code examples on sandbox.
What happened to it?"

When I am start with this library, this examples were very helped, could you make them work?

**Comment by tannerlinsley** [comment]
The v6 site is unavailable for the time being, but the documentation and examples are still available in this list here: https://github.com/tannerlinsley/react-table#version-6

**Comment by AndiRudi** [comment]
I can't find the documentation in the link provided or at least all demos are not running anymore. This is a huge problem now..

**Comment by tannerlinsley** [comment]
Here's the link to the examples directory. https://github.com/tannerlinsley/react-table/tree/master/archives/v6-examples

**Comment by AndiRudi** [comment]
Yes sure, but they can not be run without checkout which makes it very hard for the one writing tech specs. You basically have to checkout them out and run them to figure out what it is. Or do I miss something?

**Comment by tannerlinsley** [comment]
There is now a list of links that are a direct codesandbox import: 
https://github.com/tannerlinsley/react-table/tree/v6#codesandbox-examples

**Comment by AndiRudi** [comment]
Thank you. It's good!
