### ISSUE TITLE
minResizeWidth not working when using functional accessor and column id

### ISSUE THREAD

**Issue by mquinn-leverege** [tannerlinsley/react-table#1275]
## minResizeWidth broken when using column id and functional accessor

1. Create a new react table using functional accessors and column ids and specify minResizeWidth for only certain columns
2. Notice that minResizeWidth does not work

**Expected behavior**
minResizeWidth should be able to be specified for individual columns, not just as a table default. The check for column.accessor === currentlyResizingColumn.id does not work if you are using a function as an accessor.

**Codesandbox!**
https://codesandbox.io/s/3rk0mzv9q6

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser Chrome
 - Version 72.0.3626.96

**Comment by tannerlinsley** [comment]
Will get your PR released today. Thanks!
