### ISSUE TITLE
Unable to re-render the dynamic cell elements

### ISSUE THREAD

**Issue by drizzlyyy** [tannerlinsley/react-table#1277]
**Describe the bug**
Unable to re-render sorted data, update table row with new data and filter data and even pagination not working if we create the cell elements dynamically using _`React.createElement`_. Also, There is no waning or error being printed on console.

**To Reproduce**
1. Go to 'Codesandbox'
2. Click on 'next and previous buttons on pagination'
3. Observe the failure

**Expected behavior**
Table cell element should be updated after updating the state.

**Codesandbox!**
[Sample Dynamic React Table](https://codesandbox.io/s/202y74jq0j)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 72.0.3626.109 (Official Build) (64-bit)

**Additional context**
Tried creating new copies of object using  `newRows = {...oldRows}`, also tried creating objects using `JSON.parse(JSON.stringify({rows}))`

**Note**: I commented my implementation of filter and sort, to reproduce them please uncomment them.

**Comment by SourceCipher** [comment]
I was about to open an issue regarding the resizing of the headers as they no longer work in our project for some reason, but I could not replicate on codepan, but thanks to you, your codepan sample shows the issue I was having!

**Comment by drizzlyyy** [comment]
> I was about to open an issue regarding the resizing of the headers as they no longer work in our project for some reason, but I could not replicate on codepan, but thanks to you, your codepan sample shows the issue I was having!

Thanks for bringing it to attention, I was also not aware of it.

**Comment by dbertella** [comment]
@SourceCipher you might find the answer to your issue in #1281

**Comment by drizzlyyy** [comment]
@tannerlinsley #1281 is not a perfect solution to this bug because, the cells contains some predefined code, but in my case, cells needs to be complete dynamic and does not contains any predefined code or attribute.
