### ISSUE TITLE
Default sorting on a date?

### ISSUE THREAD

**Issue by arcade16** [tannerlinsley/react-table#1278]
Sorry for not posting this on the spectrum chat channel, it kept giving me an internal server  error when trying to post there.

I need  to default sort my table by date column, with the most recent being at the top. My date format does not have a day and looks like this: ```MM/YYYY``` or ```01/2019```.

How can I sort by default by the date?

This is what my table looks like:
              <Busy isBusy={this.state.tableIsBusy}>
                  <ReactTable
                    data={reportJSON}
                    filterable
                    defaultFilterMethod={(filter, row) =>
                    String(row[filter.accessor]) === filter.value}
                    columns={[
                      {
                        id: "checkbox",
                        accessor: "",
                        Cell: ({ original }) => {
                          return (
                            <input
                              type="checkbox"
                              className="checkbox"
                              checked={this.state.selected[original.linkRaw] === true}
                              onChange={() => this.toggleRow(original.linkRaw)}
                            />
                          );
                        },
                        Header: x => {
                          return (
                            <input
                              type="checkbox"
                              className="checkbox"
                              checked={this.state.selectAll === 1}
                              ref={input => {
                                if (input) {
                                  input.indeterminate = this.state.selectAll === 2;
                                }
                              }}
                              onChange={() => this.toggleSelectAll()}
                            />
                          );
                        },
                        sortable: false,
                        width: 45
                      },

                      {
                        Header: 'Date',
                        accessor: 'date',
                        id: 'date',
                        maxWidth: 120,
                        filterMethod: (filter, rows) =>
                          matchSorter(rows, filter.value, { keys: ["date"] }),
                        filterAll: true,
                        asc : true
                      },

                      { Header: 'Provider', 
                      accessor: 'provider', 
                      filterMethod: (filter, rows) =>
                      matchSorter(rows, filter.value, { keys: ["provider"] }),
                      filterAll: true},

                    { Header: 'Type', 
                      accessor: 'type',
                      maxWidth: 120,
                      filterMethod: (filter, rows) =>
                      matchSorter(rows, filter.value, { keys: ["type"] }),
                      filterAll: true},

                      { Header: 'Executive Report', accessor: 'executiveLink', maxWidth: 130},
                      { Header: 'Detailed Report', accessor: 'detailedLink', maxWidth: 130},
                      { Header: 'Provider Report', accessor: 'providerLink', maxWidth: 130}
                    ]}
                    loading={this.state.tableIsBusy}
                    defaultSorting={[
                      {
                       id: 'date',
                       desc: true
                      }
                    ]}
                  />

**Comment by tannerlinsley** [comment]
Yeah, this is question for the Spectrum community. Going to close this and repost it there.

**Comment by tannerlinsley** [comment]
https://spectrum.chat/react-table?thread=691b096e-aef0-4cc4-9f30-1893b4210a36
