### ISSUE TITLE
Date Time filter on react table

### ISSUE THREAD

**Issue by Sudhir89** [tannerlinsley/react-table#1280]
Hi, How can i add date time filter on react table column? currently, I am using Match sorter for Text fields columns but for date time field column match sorter is not working. Anyone can suggest how can I filter react table data for datetime using filter on column.

Here is my code that I written for Text field column: { Header: 'Library Path', accessor: 'testLibraryPath', minWidth: 80, filterMethod: (filter, rows) => matchSorter(rows, filter.value, { keys: ["testLibraryPath"] }), filterAll: true },

I tried similar way for date time column but it is not working. Here is code for datetime field column: { Header: 'Started Date', id: 'startedDate', accessor: c => { return moment(c.startedDate).format('YYYY/MM/DD HH:mm:ss') }, width: 190, filterMethod: (filter, rows) => matchSorter(rows, filter.value, { keys: [moment("startedDate").format('YYYY/MM/DD HH:mm:ss')] }), filterAll: true }

Regards, Sudhir

**Comment by tannerlinsley** [comment]
Please post this question to our Spectrum support forum located at https://spectrum.chat/react-table. Thanks!
