### ISSUE TITLE
Component override

### ISSUE THREAD

**Issue by andrejunges** [tannerlinsley/react-table#129]
I was trying to override the pagination component here in my project and it wasn't working properly. I passed an `PaginationComponent`, for example, and nothing happened..
So I went to the compiled code and saw that these properties were lowerCamelCase (paginationComponent). I'm not sure if that is expected, but if it is we should definitely update the docs (readme).

What do you think about it?

**Comment by tannerlinsley** [comment]
All of the component override props should be pascal cased (PaginationComponent).  If they are not this way in the docs, pleas submit a PR to fix them :)
