### ISSUE TITLE
Request to update README in V6 for advancedExpandTableHOC

### ISSUE THREAD

**Issue by uclaeagit** [tannerlinsley/react-table#1290]
# Using v6?
Yes

**Describe the bug**

The README says to follow the same import pattern for advancedExpandTableHOC as for treeTableHOC:
```
import treeTableHOC from "react-table/lib/hoc/treeTable";
```

However advancedExpandTableHOC lacks a default export. So the import for it should read:
```
import {advancedExpandTableHOC} from "react-table/lib/hoc/advancedExpandTable";
```

**Comment by tannerlinsley** [comment]
We welcome any and all PR's to fix documentation. Give it a try!

**Comment by uclaeagit** [comment]
Which branch should I submit the PR to?
