### ISSUE TITLE
On CodeSandbox Examples section first example won't render as expected.

### ISSUE THREAD

**Issue by paschalidi** [tannerlinsley/react-table#1293]
**Describe the bug**
When going to this [link](https://github.com/tannerlinsley/react-table/tree/v6#codesandbox-examples) and click the option '100k-rows-aggregation' of the list, the example on CodeSandbox wont render.

**To Reproduce**
1. Go to this [link](https://github.com/tannerlinsley/react-table/tree/v6#codesandbox-examples
)
2. Click on '100k-rows-aggregation' (first option)
```
src/Utils.js:7:32
   4 | 
   5 | const range = len => {
   6 |   const arr = [];
>  7 |   for (let i = 0; i < len; i++) {
     |                                ^
   8 |     arr.push(i);
   9 |   }
  10 |   return arr;
```

**Expected behavior**
Since its first example one might argue its crucial for the trust people have on the product/project itself. Even tho I can understand that the issue is unrelated to `react-table` itself.

**Codesandbox!**
[Reproduce](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/archives/v6-examples/react-table-100k-rows-aggregation)

**Screenshots**
![image](https://user-images.githubusercontent.com/4181674/54468512-b12d2f00-478d-11e9-8c61-948173b19fa1.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version 72

**Additional context**
Suggested solution would be to limit the amount of data that are being generated since react-table will throw an error when iterations exceed 10001 and in this case is 100k.
Another solution would be to solve the big that is causing `react-table` not throw this error.

**Comment by tannerlinsley** [comment]
Yeah, this is something that should be configured in a `sandbox.config.js` file for that example.

**Comment by tannerlinsley** [comment]
Fixed.
