### ISSUE TITLE
How can I pass particular row prop to sub component

### ISSUE THREAD

**Issue by dineshui1** [tannerlinsley/react-table#1294]
Hello,

How to pass single row data as props to subcomponent?

when I am accessing props it is passing all rows data to the child. I need only parent row data in the subcomponent 

Thanks,
Dinesh

**Comment by dineshui1** [comment]
Got it row.original have the list of parent row params

**Comment by tannerlinsley** [comment]
If you have questions about support or implementation, please use the [React Table Spectrum Community](https://spectrum.chat/react-table)
