### ISSUE TITLE
Keeping selected page number after callback

### ISSUE THREAD

**Issue by chetanbuddh** [tannerlinsley/react-table#1296]
# STOP

We do not use Github to track general support. Please use our public support forum at https://spectrum.chat/react-table.

NOTE: If a support/help/question issue is opened, it will be closed immediately and be redirected to the forum. Thanks for helping us keep our issues clean and productive!

**Comment by arkn98** [comment]
> We do not use Github to track general support. Please use our public support forum at https://spectrum.chat/react-table.

It has been 3 days since I posted on spectrum for help. I haven't got any help. Not meaning to sound rude. Link [here](https://spectrum.chat/react-table/general/links-inside-cell-are-not-clickable~616f4a61-912c-49c4-9676-7ed03f9c5fe9)

**Comment by tannerlinsley** [comment]
Please ask this question on our support forum: https://spectrum.chat/react-table. You will have more luck there while we actively work on the next major version of React Table. Thankyou!
