### ISSUE TITLE
bad example in docs

### ISSUE THREAD

**Issue by chancesmith** [tannerlinsley/react-table#1297]
**Describe the bug**
[In the docs](https://github.com/tannerlinsley/react-table/tree/v6#codesandbox-examples), there is a link to [a broken CodeSandbox](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/archives/v6-examples/react-table-100k-rows-aggregation).

**Screenshots**
!(error in codesandbox)[https://sh-drop.s3.us-east-1.amazonaws.com/cs/Screenshot%202019-03-20%2013.49.53.png)

**Comment by tannerlinsley** [comment]
The sandbox needs to have the loop protection removed. The example is fine, but codesandbox tries to detect that something will infinite loop if it exceeds like 10,000 loop iterations.

**Comment by tannerlinsley** [comment]
If you would like to, you could PR a `sandbox.config.js` file to that example folder located in the repo archives. Somewhere in there you can hard code that flag to turn off the infinite loop protection.
