### ISSUE TITLE
I'm trying to add a checkbox input to a cell

### ISSUE THREAD

**Issue by hegelstad** [tannerlinsley/react-table#13]
```
const data = [{
    name: 'Tanner Linsley',
    age: 26,
    friend: {
        name: 'Jason Maurer',
        age: 23
    }
},{
    name: 'Banner Dansley',
    age: 19,
    friend: {
        name: 'Jason Mraz',
        age: 30
    }
}]

const columns = [{
  header: 'Name',
  accessor: 'name' // String-based value accessors !
}, {
  header: 'Age',
  accessor: 'age',
  render: <input type="checkbox" checked="checked"/> // Custom cell components!
}, {
  header: 'Friend Name',
  accessor: 'friend.name' // Custom value accessors!
}, {
  header: 'Friend Age',
  //header: props => <span>Friend Age</span>, // Custom header components!
  accessor: 'friend.age'
}]

<ReactTable
     data={data}
     columns={columns}
     minRows={0}
/>
```

Result: 

```
<div class="-td-inner">
    <input type="checkbox" value="on">   <----- should be rendered as <input type="checkbox" checked="checked"/>
</div>

```

**Comment by tannerlinsley** [comment]
Try checked={true}

**Comment by tannerlinsley** [comment]
Then to respond to changes, use onChange={() => {doSomething()}}

**Comment by hegelstad** [comment]
checked={true} doesn't change anything.

What am I supposed to put within:
```
onChange={(state, instance) => {
                    
                }}
```

**Comment by tannerlinsley** [comment]
That is the callback for when the page and sorting changes. It is an
opportunity for you to fetch server side data. Use it with the 'manual'
prop.

**Comment by hegelstad** [comment]
Aha, I don't think i need to fetch server side data. I just want to be able to check checkboxes within the custom cell component, the checking doesn't have to be persisted across page reloads or component lifecycles, but i would like to be able to access them from the application across paging.

Maybe it is wise to save the state of the checkbox within the data object? Do i change the state with onChange? And would you send me in the right direction to extract custom cell value changes?

**Comment by tannerlinsley** [comment]
Yes. In each row of the data, keep a property to track the check box state.
To track changes to the check box, just use an on change on the check box
and update that row.

React Table doesn't track state for anything except paging and sorting. The
rest is up to you. You can use your own components in the header and render
column properties, so you have full control.

**Comment by hegelstad** [comment]
Thanks for taking your time!

**Comment by tannerlinsley** [comment]
You bet!
