### ISSUE TITLE
SortedData does not match shown data

### ISSUE THREAD

**Issue by FreddyFroehlich** [tannerlinsley/react-table#1305]
In our app we have a list of locations, each shown in a row in react table. Some of them are pivoted, some are not. 
Now, when we sort the data, we want to restore the expanded state afterwards, so that the user does not have to expand all rows again. As the expanded state relies on indices, we use a ref of our table to get the "new" indices after sorting.

This procedure breaks, if we have multiple rows, which have the same value (0) in the sorted column. Then the `sortedData` does not match the shown data anymore. The order of rows is different, which leads to expanding wrong (different) rows than before. 

- Version: 6.8.6

**Expected behavior**
I'd expect the `sortedData` array to always match the shown data.

**Desktop:**
 - OS: macOS
 - Browser Chrome & Safari (others not tested)

**Comment by tannerlinsley** [comment]
Please ask this question on our support forum: https://spectrum.chat/react-table. You will have more luck there while we actively work on the next major version of React Table. Thankyou!
