### ISSUE TITLE
react-table doesn't re-render correctly

### ISSUE THREAD

**Issue by riddleit** [tannerlinsley/react-table#1306]
React-table is not reacting to the change of the pageSize property neither to the filterable in conjunction with filtered properties.
Two examples are provided: one for the pageSize and another to the table inline filtering.

**Version**
6.8.6

#### pageSize:
Steps to reproduce:
1. Observe that total number of pages (which is 556)
2. Observe that the number of rows per page is 10
3. Click on the "Change Page Size" checkbox
4. Observe that the number of rows per page is 6 but the total number of pages was not updated. Additionally, 4 empty rows are displayed.
5. If we click on "Next" page, everything is re-rendered correctly
#### Filterable:
Steps to reproduce:
1. Observe that total number of pages (which is 556)
2. Observe that the number of rows per page is 10
3. Click on the "Show Inline Filter" checkbox
4. Provide a partial filter (e.g. for Age column give the value 2)
5. Table is updated correctly (including the number of pages)
6. Click on the "Show Inline Filter" checkbox (to uncheck it)
7. Table is updated correctly
8. Click again on the "Show Inline Filter" checkbox (to check it)
9. Filter is not applied and the total number of pages was not updated
10. If we click on "Next" page, everything is re-rendered correctly

### Expected behavior
Table should be re-rendered whenever these properties change.

### Codesandbox
[Page size example](https://codesandbox.io/s/m9q3v25ro8)
[Filterable example](https://codesandbox.io/s/y2n71qzj1)

### Additional context
This issue only happens when we reuse the columns object due to performance issues (huge amount of data). Since it doesn't change, there is no need to recreate it.

### Desktop:
 - OS: Windows10
 - Browser: Chrome
 - Version 73.0.3683.86 64-bit

**Comment by tannerlinsley** [comment]
We're aware of these bugs in v6 and unfortunately cannot fix them without breaking changes. Please be patient as we work on v7 where these issues will be resolved.

**Comment by riddleit** [comment]
Could you please give an estimate for the release date of v7?
