### ISSUE TITLE
Is there way to specify title on Column header

### ISSUE THREAD

**Issue by ckshekhar73** [tannerlinsley/react-table#131]
{
	header: <strong title="Performance code">Perf</strong>,
	accessor: 'performance',
	width: 45,
	style: {textAlign: 'center'},
	title: 'Performance'
}
In above example tool tip is displayed only when cursor is on text "Perf" not on whole column header.
Is there way to implement just pass title and it is applied to whole column header.
{
	header: <strong>Perf</strong>,
	accessor: 'performance',
	width: 45,
	style: {textAlign: 'center'},
	title: 'Performance Code' 
	}

**Comment by ckshekhar73** [comment]
You can close this issues as we can achieve that with below spinet but still title will be better options.

getHeaderProps: (state, rowInfo, column, instance) => ({
			title: 'Performance Code'
		})

**Comment by tannerlinsley** [comment]
👍
