### ISSUE TITLE
Sorting and filtering are not working properly on formatted accessor

### ISSUE THREAD

**Issue by SourceCipher** [tannerlinsley/react-table#1311]
In our project we have v6 table and we are not intending to switch to any other for now.

We are having the issue where sorting and filtering are not working on the same data. For example: I have a date column. In `accessor` I pass the date as unix timestamp (`moment(update_date).valueOf()`) When I sort the column, it sorts on the `accessor` value which is unix which is good. But then I format that date in Cell to be displayed as `MM-DD-YYYY` and want the filter to be accessing the Cells formatted data and not the unix timestamp.. 

How can I pass separate values to sorting and filtering methods without actually specifying for each column special filter or sorting methods??? 

In sorting I can access original data and row data. I dont want to modify the original data but if there is a way to modify the row data I could use that for separate methods

**Comment by incognos** [comment]
running into the same issue with numbers formatted with the `numeral` lib
![image](https://user-images.githubusercontent.com/1743697/55806593-da1cb780-5ae0-11e9-86c4-4bbf0e03e49d.png)

**Comment by SourceCipher** [comment]
@incognos Thats it. We are using numeral as well and displaying formatted in MB, GB etc. We need to filter on the displayed value but sort on a raw value which is in bytes.

**Comment by incognos** [comment]
had to go custom sort method to solve the issue - annoying but hey, it solves the problem.

`   sortMethod: (a, b) => {
          a = numeral(a).value();
          b = numeral(b).value();
          if (a === b) {
            return 0;
          }
          return a > b ? 1 : -1;
        }`

**Comment by incognos** [comment]
@SourceCipher I cannot find any reference to that in the docs whatsoever and it doe snot seem to work. must have been removed

**Comment by SourceCipher** [comment]
@incognos I think it never was. It was as a request to make this work and he included as a sample. I dont think its possible to make it work like we expect without actually handling each column with separate filter, sort methods which will make the project a pile of mess

**Comment by incognos** [comment]
@SourceCipher  I managed to make it work by pushing the value into the `accessor` and using the `Cell` for rendering. You can pass the value into the accessor and this will be used for sorting etc.

**Comment by SourceCipher** [comment]
@incognos Yes you can but then the sorting will not work on the raw data as it will take that formatted `accessor` value.  Unless you managed to do something totally different then you can add a sample code so people could see

**Comment by CWSites** [comment]
Ya'll may want to look into this here: https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/archives/v6-examples/react-table-custom-sorting

**Comment by tannerlinsley** [comment]
Honestly I think this is the way to go in v6 for now. We're looking into some automatic sort-detection in v7, but nothing solid yet.

**Comment by Bangerathanujas** [comment]
I want sort the column with one accessor and filter with another accessor
is it  possible
