### ISSUE TITLE
Bug: pagination style is off on Firefox

### ISSUE THREAD

**Issue by stellashen** [tannerlinsley/react-table#1315]
device: 
Mac

version:
"react-table": "6.9.2"

Browser: 
Firefox. 

Bug: 
In the pagination, the -pageSizeOptions select element has two problems:
1) the select button on the right side looks like browser default and has undesired white padding;
2) the scroll bar in its dropdown has undesired white padding.
So, when the background color is not white, the style looks off.

**Comment by tannerlinsley** [comment]
Feel free to submit a PR to fix this on the v6 branch, but v7 will eliminate the need for this fix. Thanks!
