### ISSUE TITLE
Infinite pagination

### ISSUE THREAD

**Issue by sm2017** [tannerlinsley/react-table#1316]
In the https://www.npmjs.com/package/react-table#server-side-data initially we have `  pages={this.state.pages} // should default to -1 (which means we don't know how many pages we have)
` and then set it from server response

It is not possible to keep it -1 , I have a use case (Similar to infinite scrolling but no scrolling just infinite paginating) that I want to keep next and previous button , and disable next button when the server returns empty response

**Comment by tannerlinsley** [comment]
Please ask this question on our support forum: https://spectrum.chat/react-table

**Comment by sm2017** [comment]
@tannerlinsley before opening issue , I asked but no body responses

**Comment by tannerlinsley** [comment]
I'll see if I can get to it on Spectrum, but no promises. I am actively working on v7. Regardless, I don't use Github for anything other than reproducible bugs, so stay tuned on Spectrum.

**Comment by chiefcll** [comment]
Can we reopen this? I see the updated example:

> Please take a look at this example: https://github.com/tannerlinsley/react-table/tree/master/examples/pagination-controlled
> 
> The usePagination hook handles a lot of pagination state and logic for you. When doing pagination manually, you merely tell the pagination hook that you'll be supplying your own rows and pageCount, then listen for the state of the pagination to change

However, this does not take into account infinite pages, where the server does not return a pageCount. I'd like to see usePagination be able to support infinite pages and then have a boolean that sets lastPage true when the server sends end of internet reached :-)

**Comment by sm2017** [comment]
@tannerlinsley Do you have plan to implement `lastPage` props ?

**Comment by tannerlinsley** [comment]
Yes.

Tanner Linsley
