### ISSUE TITLE
Trying to create reference of react-table, But throwing error “Property 'getResolvedState' does not exist on type 'RefObject<HTMLInputElement>' ”

### ISSUE THREAD

**Issue by velsonjr** [tannerlinsley/react-table#1319]
I am trying to implement the download feature for react table. I am using react-csv package for the same. When I am trying to maintain the reference for the table using createRef() It is throwing "Property 'getResolvedState' does not exist on type 'RefObject'" error. I am using React with Typescript

```````````
import {CSVLink} from "react-csv";
import * as React from 'react';
import ReactTable from 'react-table';

export default class Download extends React.Component<{},{}> {

  private reactTable: React.RefObject<HTMLInputElement>;
  constructor(props:any){
    super(props);
    this.state={} // some state object with data for table
    this.download = this.download.bind(this);
    this.reactTable = React.createRef();
  }

   download(event: any)
   {
    const records =this.reactTable.getResolvedState().sortedData; //ERROR saying getResolved state does not exist
     //Download logic
   }

    render()
    {
       return(
       <React.Fragment>
       <button onClick={this.download}>Download</button>
       <ReactTable 
           data={data} //data object
           columns={columns}  //column config object
           ref={this.reactTable}
       />
     </React.Fragment>
    }
}

**Comment by tannerlinsley** [comment]
I would first suggest trying a functional ref, eg. `ref={instance => { this.reactTable = instance} }`. Outside of that, I suggest asking this question in our support community at https://spectrum.chat/react-table.

**Comment by RajuTicvic** [comment]
Hi @tannerlinsley 
I used to like this but I got the error below.

let reactTable = React.createRef();
//let reactTable = React.useRef(); I tried this too 
...
<EnhancedTable ref={instance => { this.reactTable = instance}} columns={header} data={data} />

Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
