### ISSUE TITLE
Example in the docs yields error

### ISSUE THREAD

**Issue by agamdua** [tannerlinsley/react-table#132]
Hi! I am new to react, and just trying to poke my way through things.

I created a new app with `create-react-app`, modified it a bit to use your first example in the docs.

Here's the error:

![screen shot 2017-03-18 at 3 00 06 pm](https://cloud.githubusercontent.com/assets/899801/24075103/a3a519e0-0beb-11e7-8938-515ce5a1aa33.png)

This is _probably_ the code path: https://github.com/tannerlinsley/react-table/blob/6d28bb2c4d96a94ed8684bee14600fc7197c5f6b/src/methods.js#L73-L76

If you however remove this:

```
{
  header: 'Friend Name',
  accessor: d => d.friend.name // Custom value accessors!
},
```

it renders alright.

My file which bugs out (just a modified version of the create app starter kit):

https://gist.github.com/agamdua/180807cf15caf5fa24a1660b5559f780

**Comment by mikedevita** [comment]
when using accessor you also need to add in the `id: 'friend-name'` for example:

```javascript
{
  header: 'Friend Name',
  id: 'friend-name',
  accessor: d => d.friend.name
}
```

**Comment by agamdua** [comment]
@tannerlinsley FYI, anyone following the docs will still have this issue. I can issue a patch once I test that the change suggested above works unless someone else gets to it first.

Thanks @mikedevita for the quick response!
