### ISSUE TITLE
request for small doc improvement on CSS

### ISSUE THREAD

**Issue by MareoRaft** [tannerlinsley/react-table#1320]
The step about needing

    import "react-table/react-table.css";

in the documentation (README) (this might not apply to the new version 7 stuff) is under the `Installation` section.  However, this isn't really installation, but rather setup/configuration.  I would suggest making a separate heading for `Configuration` there, so people will be less likely to skip over it.

You might consider adding the `import "react-table/react-table.css";` statement to the first example block too, although that might not work for people using CSS the old school way.

Thanks kindly for this great library!

**Comment by tannerlinsley** [comment]
We welcome a PR to improve this! Thanks :)
