### ISSUE TITLE
After loading the data, paginator stays in last viewed page

### ISSUE THREAD

**Issue by dmarinlivevox** [tannerlinsley/react-table#1321]
V6-Paginator is not restarting after loading new data.

1. Load data
2. Go to 3 page
3. Load new data
4. Paginator statys in 3 page instead of restarting. 

Pagination should be restarted (if no server side pagination is being used) after loading new data

**Comment by tannerlinsley** [comment]
Please feel free to submit a PR to the v6 branch to improve this experience, or consult https://spectrum.chat/react-table to discuss this issue with the community. Thanks!
