### ISSUE TITLE
Next page button is inactive when user is on the second-to-last page

### ISSUE THREAD

**Issue by kamilbielawski** [tannerlinsley/react-table#1326]
# Using v6?

yes

**Describe the bug**
When the current page is second to last (i.e 9 out of 10), the 'next page' button is disabled even though there's still one more page to visit.

**Expected behavior**
The button should be active

**Screenshots**

![bug](https://user-images.githubusercontent.com/1784928/56926423-1cc72380-6ad2-11e9-8ef5-fc092f873592.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Browser [e.g. Chromium]
 - Version [e.g. 74.0.3729.108]

**Comment by tannerlinsley** [comment]
In v6, page is intended to be used as an index, not an `n + 1` value. This is changed in v7, but will remain this way in v6, since it would be a breaking change.

**Comment by kamilbielawski** [comment]
oh, ok. Thank you for clarification. I was confused by the discrepancy between v6 and b7, my bad :sweat_smile:
