### ISSUE TITLE
Failing ESLint react/prop-types in Filter of columns

### ISSUE THREAD

**Issue by pvaritta** [tannerlinsley/react-table#1331]
I use React-table v.6.10.0 and I try to custom filter to select drop down
but I got warning from react/prop-types told me missing in props validation
It's the same issue as https://github.com/tannerlinsley/react-table/issues/1207 but in Filter of columns 

```code
Filter: ({ filter, onChange }) => (
          <select onChange={event => onChange(event.target.value)} style={styles.filter} value={filter ? filter.value : ''}>
           <option value="all">ALL</option>
           <option value="yes">YES</option>
           <option value="no">NO</option>
            ))}
          </select>
        ),
```

**Comment by tannerlinsley** [comment]
Hi there! It looks as though you've submitted an issue or feature request for v6 of React Table, which I am no longer maintaining or supporting. I invite you to try the latest alpha release of v7 and help me push towards a v7 release soon. Thankyou!

If you still wish to discuss v6, please use https://spectrum.chat/react-table.
