### ISSUE TITLE
defaultSortDesc does not sort by desc.

### ISSUE THREAD

**Issue by ElijahPrince73** [tannerlinsley/react-table#1332]
**Describe the bug**
Adding defaultSortDesc to ReactTable doesn't sort from descending 

**To Reproduce**
Add defaultSortDesc={true} to ReactTable component

**Expected behavior**
To sort by descending

**Codesandbox!**
https://codepen.io/anon/pen/QRLONG?editors=0010#anon-login

**Comment by tannerlinsley** [comment]
Hi there! It looks as though you've submitted an issue or feature request for v6 of React Table, which I am no longer maintaining or supporting. I invite you to try the latest alpha release of v7 and help me push towards a v7 release soon. Thankyou!

If you still wish to discuss v6, please use https://spectrum.chat/react-table.
