### ISSUE TITLE
How add a button to each row to column ?

### ISSUE THREAD

**Issue by Elliriah** [tannerlinsley/react-table#1334]
Hi everyone,  i'm new to react and i will know ho add a button to each row to column ?
Here my code :
`  defaultProps({
        columns: [
                id: "members",
                title: "Members",
                padding: "none",
                sortable: true,
                tableId: true,
                linkTo: id => ``
            }`...])};
Thanks you for your answers (and sorry for my english...)

**Comment by rpanczer** [comment]
Hi @Elliriah,

You'll want to use `Cell`  for the column you want to add the buttons for.

> `      {
        Header: '',
        accessor: 'testData',
        Cell: row => <button onClick={() => this.handleButtonClick(row.value)}>Click Me</button>
      }`

**Comment by tannerlinsley** [comment]
Hi there! It looks as though you've submitted an issue, feature request, or question regarding v6 of React Table, which I am no longer maintaining or supporting. I invite you to try the latest alpha release of v7 and help me push towards a v7 release soon. Thankyou!

If you still wish to discuss v6, please use https://spectrum.chat/react-table.
