### ISSUE TITLE
react-table/src/hoc/ is mising v6

### ISSUE THREAD

**Issue by zhupingcmm** [tannerlinsley/react-table#1337]
# ST
hello ,
I have clone the react-table code in gitup. But after clone, I can not found react-table/src/hoc/ in my code.
In react-table/src/hoc/ have selectTable and selectTreeTable I want to check the source code.
![image](https://user-images.githubusercontent.com/30522912/57443322-56d9b780-7280-11e9-8202-7c7c16631b38.png)

**Comment by jasonk** [comment]
Sounds like you need to check out the `v6` branch.

**Comment by tannerlinsley** [comment]
Hi there! It looks as though you've submitted an issue, feature request, or question regarding v6 of React Table, which I am no longer maintaining or supporting. I invite you to try the latest alpha release of v7 and help me push towards a v7 release soon. Thankyou!

If you still wish to discuss v6, please use https://spectrum.chat/react-table.
