### ISSUE TITLE
selectTable/index.js have bad operation

### ISSUE THREAD

**Issue by zhupingcmm** [tannerlinsley/react-table#1338]
hello ,
In the selectTable why the id combine with 'select-'.
if use this combine , the key in toggleSelection function is 'select-xxxx'.
So we need additional work to splice the key and get the right key we want to get.

in selectTable/index.js
var inputProps = {
          checked: checked,
          onClick: toggleSelection,
          selectType: selectType,
          row: row,
          ### id: 'select-' + row[keyField]
        };

**Comment by dichiaro-nicholas** [comment]
This seems to have changed recently because we were using 6.8.6 but updated to 6.10.0 which broke all our selectTables. Our solution for the time being is to remain on 6.8.6.

**Comment by tannerlinsley** [comment]
Hi there! It looks as though you've submitted an issue, feature request, or question regarding v6 of React Table, which I am no longer maintaining or supporting. I invite you to try the latest alpha release of v7 and help me push towards a v7 release soon. Thankyou!

If you still wish to discuss v6, please use https://spectrum.chat/react-table.
