### ISSUE TITLE
viewIndex across all pages?

### ISSUE THREAD

**Issue by thedustyrover** [tannerlinsley/react-table#1339]
I was attempting to render a basic index for my table (0...N for N rows) that is consistent with the current sort. Index is always the originally-specified index from server-side, and it seems that the viewIndex is only relative to the current page. I can cobble together a few attributes to get the current sort index:

`cellData.page*cellData.pageSize + cellData.viewIndex`

Is the easiest way to derive this to use, or have I missed another handy attribute?

**Comment by tannerlinsley** [comment]
Is there not a `cellData.index`?

---

Hi there! It looks as though you've submitted an issue, feature request, or question regarding v6 of React Table, which I am no longer maintaining or supporting. I invite you to try the latest alpha release of v7 and help me push towards a v7 release soon. Thankyou!

If you still wish to discuss v6, please use https://spectrum.chat/react-table.

**Comment by willbee28** [comment]
The problem with the plain index, is that they all get jambled up upon filtering by clicking on a header. I too just use viewIndex and add the pageSize*page to it. Seems to be best way to do it currently.
