### ISSUE TITLE
Shouldn't the page number be 0 when there is no data present.

### ISSUE THREAD

**Issue by marudhupandiyang** [tannerlinsley/react-table#134]
Demo [here](https://react-table.js.org/?selectedKind=2.%20Demos&selectedStory=Custom%20%22No%20Data%22%20Text&full=0&down=0&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel)

My understanding is, When there is no data present in the table or when the data is being fetched for the first time from a remote url, the page number should be zero. 

Currently it is displayed as `Page 1 of 0`.
When you focus the input and then click elsewhere(on blur) the number restores correctly to zero.

**Comment by mikedevita** [comment]
I would think the page numbering would be hidden if there is no data... but that is just me.

**Comment by tannerlinsley** [comment]
I would accept a PR to either show 0 of 0 pages or temporarily hide pagination until data is present. I prefer the former
