### ISSUE TITLE
Shadow over React Table

### ISSUE THREAD

**Issue by zach446** [tannerlinsley/react-table#1340]
I will begin this by saying that this is by no means a breaking bug.  It is just an interesting bug.  When I have my table at the bottom of my web page, and I open up the inspect menu.  Upon closing the inspect menu a shadow will be seen on the table.  

Again, this is not breaking, nor really a problem.  I just thought it was interesting and wanted to point it out.  

**To Reproduce**
1. Load app with your table
2. bring up inspect menu
3. Reload the page
4. Close inspect menu
5. Watch as the shadow stays

This is most likely an issue with Google Chromes inspect menu, but I still thought it was kind of cool.

![shadow](https://user-images.githubusercontent.com/22154347/57705455-f2c54380-7631-11e9-9f2d-9266ae4a4650.gif)

**Comment by tannerlinsley** [comment]
Hi there! It looks as though you've submitted an issue, feature request, or question regarding v6 of React Table, which I am no longer maintaining or supporting. I invite you to try the latest alpha release of v7 and help me push towards a v7 release soon. Thankyou!

If you still wish to discuss v6, please use https://spectrum.chat/react-table.
