### ISSUE TITLE
rowspan & colspan

### ISSUE THREAD

**Issue by BarretL** [tannerlinsley/react-table#1342]
# STOP

We do not track feature requests through Github. Please use the [Spectrum React Table Forum](https://spectrum.chat/react-table) to talk about new ideas and features.

**Comment by tannerlinsley** [comment]
This will be possible in v7

---

Hi there! It looks as though you've submitted an issue, feature request, or question regarding v6 of React Table, which I am no longer maintaining or supporting. I invite you to try the latest alpha release of v7 and help me push towards a v7 release soon. Thankyou!

If you still wish to discuss v6, please use https://spectrum.chat/react-table.

**Comment by oknoorap** [comment]
Is colspan and rowspan already included in v7? what's the status?

**Comment by tannerlinsley** [comment]
`colspan` has been implemented as a render prop only for column headers. Support for `colspan` and `rowspan` in cells is coming soon.

**Comment by oknoorap** [comment]
is colspan / rowspan support merge cell as well?

**Comment by akdor1154** [comment]
hey, could this be re-opened to track implementing cell-level row/col-span?
Cheers

**Comment by tannerlinsley** [comment]
Please open a new issue and we’ll track it there.

Tanner Linsley

**Comment by dandv** [comment]
I'm evaluating React table components, looking for one with colspan support.

Can't quite tell from this feature what the status is.  If column spanning is supported, can someone knowledgeable with the library please update the [Featues](https://github.com/tannerlinsley/react-table#features) section of the README?
