### ISSUE TITLE
Is there a way to add a label to the top left part of the React-Table?

### ISSUE THREAD

**Issue by Trancedified** [tannerlinsley/react-table#1344]
I'm hoping to add the total record count in the label. Is this possible at the top left part of the React-Table near the pagination "Previous" button?

Thanks!

**Comment by tannerlinsley** [comment]
Hi there! It looks as though you've submitted an issue, feature request, or question regarding v6 of React Table, which I am no longer maintaining or supporting. I invite you to try the latest alpha release of v7 and help me push towards a v7 release soon. Thankyou!

If you still wish to discuss v6, please use https://spectrum.chat/react-table.
