### ISSUE TITLE
Bug: can't go to next page

### ISSUE THREAD

**Issue by AskAlexSharov** [tannerlinsley/react-table#1345]
Version: `v7.0.0-alpha.3` (in `7.0.0-alpha.2` all works well). 

After call `nextPage();` pageIndex increasing, but then decreasing (after few re-renders). 

Browser: Chrome 74

**Additional context**

**Comment by tannerlinsley** [comment]
I just released a new alpha version. Can you confirm that this is still an issue? Or paste a link to a codesandbox that I can debug.

**Comment by AskAlexSharov** [comment]
I see bug in `7.0.0-alpha.3` (rechecked now). Don't see any newer alpha version.

**Comment by Siemko** [comment]
Any update on that? Bug is present in `7.0.0-alpha.3`

**Comment by AskAlexSharov** [comment]
`7.0.0-alpha.5` - no bug in this version. Closing ticket then. Thank you.
