### ISSUE TITLE
Lose focus on input in a cell

### ISSUE THREAD

**Issue by claraonmars** [tannerlinsley/react-table#1346]
**Describe the bug**
In version 6.9, we lose focus on input fields in cell on keystroke. 

**To Reproduce**
Go to this sandbox link to reproduce the behavior
https://codesandbox.io/s/reacttable-cell-renderers-with-custom-props-lhmzm?fontsize=14

**Expected behavior**
Go to this sandbox link to view expected behavior
https://codesandbox.io/s/reacttable-cell-renderers-with-custom-props-2pomf?fontsize=14

**Additional context**
The difference between the two sandboxes is only the version of React-Table. (between 6.8.6 to 6.9)

**Comment by LuisPaGarcia** [comment]
Just find out how to add an editable input to react-table:
```jsx

state = {
  data: [ { id: 1 }, { id: 2 }, { id: 3 }  ]
}

handleInputChange = (cellInfo, event) => {
    let data = [...this.state.data];
    data[cellInfo.index][cellInfo.column.id] = event.target.value;

    this.setState({ data });
};

renderEditable = (cellInfo) => {
    const cellValue = this.state.data[cellInfo.index][cellInfo.column.id];

    return (
        <input
            placeholder="type here"
            name="input"
            type="text"
            onChange={this.handleInputChange.bind(null, cellInfo)}
            value={cellValue}
        />
    );
};

render(){
<ReactTable 
...
columns={[
    {
        Header: 'Id',
        accessor: 'id',
        Cell: this.renderEditable
    }
]}
/>
}
```

**Comment by tannerlinsley** [comment]
This is one of the issues we've seen repeatedly with the old v6 React Table API. I'm not sure what can be done at this point, other than getting v7 out as fast as possible.
---
Hi there! It looks as though you've submitted an issue, feature request, or question regarding v6 of React Table, which I am no longer maintaining or supporting. I invite you to try the latest alpha release of v7 and help me push towards a v7 release soon. Thankyou!

If you still wish to discuss v6, please use https://spectrum.chat/react-table.

**Comment by NeriedAU** [comment]
Hi, had this issue and dropped back to v6.8.2 and focus is retained now after input update. I chose this version to try as it was not occurring in another project of mine with this version of react-table.

**Comment by evenfrost** [comment]
LuisPaGarcia's solution worked for me. Essentially you just need to move your Cell render function to component method to retain function signature. So instead e.g.:

```jsx
Cell: () => <input type="text" />
```

you'll need to write it like this:

```jsx
// inside related React class component
this.renderInput = () => <input type="text" />
// ...
Cell: this.renderInput
```

This fixed the issue for me.

**Comment by safekeep-admin** [comment]
issue still perisists for me on 7.6.3

**Comment by zxdvd** [comment]
This works well. Any one can help to explain this?

**Comment by 35grain** [comment]
For anyone using React Hook Forms for submitting the table fields coming across this, the following works nicely:

Define a function component for rendering your input (textarea in my case) and handling the data retrieval + updating the form:
```
const TextareaCell = ({ form, field }: any) => {
  const [value, setValue] = useState(field.value);

  useEffect(() => {
    setValue(field.value);
  }, [field.value]);

  const onBlur = () => {
    form.setValue(field.name, value);
  };

  return (
    <Textarea
      {...field}
      onChange={(e) => setValue(e.target.value)}
      onBlur={onBlur}
      value={value}
    />
  );
};
```

Use it in place of your regular input within the cell:
```
cell: ({ row }) => (
        <FormField
          control={form.control}
          name="yourFieldName"
          render={({ field }) => (
            <FormItem>
              <FormControl>
                <TextareaCell form={form} field={field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
      ),
```
