### ISSUE TITLE
Is there Excel Functionality in the table ?

### ISSUE THREAD

**Issue by RichyNs** [tannerlinsley/react-table#1347]
Does the react table have a button where onPress it will download the data from the table into an excel file ?

**Comment by Paul6552** [comment]
Please ask questions at stackoverflow. This is a bug tracker.

No, react-table does not have this functionality. But you can use a ref on the react-table to get the resolved state: `let data = this.reactTable.getResolvedState();`

`<ReactTable
                            ref={(r) => this.reactTable = r}
                            data={this.props.tabledata}
                            columns={columnsTaenze}
.....
/>`

After that you can do anything what you want with the variable data.

**Comment by Paul6552** [comment]
This could probably help:

https://stackoverflow.com/questions/48120858/access-filtered-data-in-reacttable

RichyNs <notifications@github.com> schrieb am Do., 23. Mai 2019, 14:58:
