### ISSUE TITLE
columns Header component not rendering

### ISSUE THREAD

**Issue by lockykeaney** [tannerlinsley/react-table#1349]
I am trying to set a global component for the header (sorting arrows) but anything I pass in get ignored.

```
<ReactTable
            
            defaultPageSize={tableData.length}
            showPagination={showPagination}
            multiSort={multiselect}
            className="-striped" 
            data={tableData}
            columns={updatedColumns}
            column={
              {
                ...ReactTableDefaults.column,
                Header: row => {
                  return (
                    <div>row {row.value}</div>
                  )
                }
              }
            }
          />
```

I can only assume it is a syntax error, but it works fine with `Cell`. The props in devtools looks like it shows it as a property of column.Header.

I'm using v6.

**Comment by tannerlinsley** [comment]
Hi there! It looks as though you've submitted an issue, feature request, or question regarding v6 of React Table, which I am no longer maintaining or supporting. I invite you to try the latest alpha release of v7 and help me push towards a v7 release soon. Thankyou!

If you still wish to discuss v6, please use https://spectrum.chat/react-table.
