### ISSUE TITLE
Is it able to multi select rows with Ctrl button in keyboard?

### ISSUE THREAD

**Issue by oshiniG** [tannerlinsley/react-table#1352]
# STOP

We do not use Github to track general support. Please use our public support forum at https://spectrum.chat/react-table.

NOTE: If a support/help/question issue is opened, it will be closed immediately and be redirected to the forum. Thanks for helping us keep our issues clean and productive!

**Comment by tannerlinsley** [comment]
https://spectrum.chat/react-table
