### ISSUE TITLE
In React Table v7 Sandbox basic example after doing group by from top not able to expand row.

### ISSUE THREAD

**Issue by shwetatarate** [tannerlinsley/react-table#1354]
# Using v6?

v6 is now considered feature complete to its current abilities and limitations. We are not actively working to fix any issues for v6 any more. We will, however, merge any non-breaking pull requests submitted to fix anything in v6.

# Using v7?

Thanks for using the alpha version of React Table v7! We're very excited about it.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Codesandbox!**
Use a new [react-table codesandbox](https://codesandbox.io/s/m5lxzzpz69) to reproduce the issue.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lukaswelinder** [comment]
It looks like the hooks were not being applied to the row in `prepareRow`.

I made a fix [in this sandbox](https://codesandbox.io/s/react-table-v7-sandbox-xjlc9) if you check `src/react-table/hooks/useTable.js` line 150.

Digging deeper, it looks like this change is [already in master](https://github.com/tannerlinsley/react-table/blob/master/src/hooks/useTable.js#L157), so the sandbox you linked is outdated. This issue can probably be closed.

**Comment by shwetatarate** [comment]
No it is not fixed there.
For regenerating issue go with following step.
![react-table 1](https://user-images.githubusercontent.com/51238312/58864001-90f87680-86d1-11e9-91cc-158624d3c352.png)
![react-table 2](https://user-images.githubusercontent.com/51238312/58864009-93f36700-86d1-11e9-8337-e9d2705c7e0a.png)

**Comment by lukaswelinder** [comment]
@shwetatarate I think I forgot to save changes. If you just change the `react-table` import in the `Table` component, it works fine.

**Comment by shwetatarate** [comment]
It is working now.
Thank You
