### ISSUE TITLE
Color the selected row

### ISSUE THREAD

**Issue by RichyNs** [tannerlinsley/react-table#1357]
When i click on a row it should be colored as if it's selected ... how can I do that ? and is there a way to flag a row ? to put in on top of the table ?

**Comment by Reston** [comment]
You should ask those sort of questions at Stackoverflow

Use the custom prop `getTrProps` and check with your `isSelected` function then return and style or className

If you are using v6 take a look at the docs https://github.com/tannerlinsley/react-table/tree/v6
