### ISSUE TITLE
Updating pager parameters does not  update the pager markup.

### ISSUE THREAD

**Issue by B-Esmaili** [tannerlinsley/react-table#1358]
# Using v7? yes
 

**Describe the bug**
When i change the pager parameters manually the change does not reflect on UI.

**To Reproduce**
`this.setState({page:0})`

**Expected behavior**
the pager should render initial page.

**Codepen!**
i us CDN version
https://codepen.io/anon/pen/Gabdao

**Comment by tannerlinsley** [comment]
You are not passing the `page` prop to the table. Please re-ask this question on https://spectrum.chat/react-table for more help. Thanks!
