### ISSUE TITLE
Checkbox in SelectTable works ok until I introduce setState to toggleSelection function

### ISSUE THREAD

**Issue by zpandza** [tannerlinsley/react-table#1362]
I implemented react-table to my project and it's partly working.

When i click on checkbox on the left side of my row, it triggers toggleSelection function that has setState in it, but it doesn't mark checkbox as "checked"

If i comment out this.setState({...}) checkbox works perfectly.

I searched through issues but couldn't find this one.

**Comment by tannerlinsley** [comment]
I would ask on https://spectrum.chat/react-table
