### ISSUE TITLE
Not able to implement SubComponents with react table V7.

### ISSUE THREAD

**Issue by shwetatarate** [tannerlinsley/react-table#1364]
Can you please provide example for implementing SubComponents with react table V7. I tried to pass SubComponent as props but it is not creating tree structure in row.

**Comment by tannerlinsley** [comment]
This is no longer included by default in v7. You can simply just render your own subcomponent in your table template, since v7 is headless, it is now fully up to you.

**Comment by mustafawm** [comment]
Are there v7 docs/examples that could show how to use it? The v7 codesandbox is a bit overwhelming to start with

**Comment by tannerlinsley** [comment]
I'm currently writing the documentation. Stay tuned!
