### ISSUE TITLE
Super column footer does not appear [v6]

### ISSUE THREAD

**Issue by gajus** [tannerlinsley/react-table#1365]
This is a bug/feature request.

If you have a column with sub-columns and add `Footer` property to the super column, then this footer is not rendered, e.g.

https://codesandbox.io/s/react-table-footers-fzwsz

I expect there to be another footer below "Popular: cart" footer that says "Test".

This is important when a single column is needed in the footer for multiple columns, e.g. In this table I need a single column that says "Total" for both "Location" columns.

<img width="1265" alt="Screenshot 2019-06-13 at 17 17 36" src="https://user-images.githubusercontent.com/973543/59449555-3eb90300-8dff-11e9-911c-a901021fd6b6.png">

Alternatively, is there a way to merge two footer columns?

**Comment by tannerlinsley** [comment]
As v6 stands today, no. Since V6 is no longer maintained, the only thing I can suggest would be forking the v6 branch, implementing any changes you want to accomplish this, and using that branch until you can upgrade to v7.

**Comment by FrontCoder1** [comment]
How can you solve it later?

**Comment by tannerlinsley** [comment]
v7 is a set of custom React hooks that let you render your table however you want. In the very near future it will also support building nested footer columns.

**Comment by FrontCoder1** [comment]
> v7 is a set of custom React hooks that let you render your table however you want. In the very near future it will also support building nested footer columns.

Can you give a dome on the codesandbox about merge footer columns?

**Comment by FrontCoder1** [comment]
> v7 is a set of custom React hooks that let you render your table however you want. In the very near future it will also support building nested footer columns.

thanks very much
