### ISSUE TITLE
getRowProps hooks is not merging the props correctly

### ISSUE THREAD

**Issue by DDinenno** [tannerlinsley/react-table#1366]
I'm having an issue overriding `getRowProps` by pushing another fn to the list  of `getRowProps` hook, only the last fn is applied.  I did some digging and I think it's because it's invoking  `applyHooks` fn inside mergeProps instead of `applyPropsHooks`

Not entirely sure if this is a bug or intended  (I would assume it should act the same as all the other getProp fn's).   I can open up a quick pr and fix this if it is.

** Version
RT 7

**To Reproduce**
Try pushing multiple override fn's to the getRowProps hook.

**Comment by tannerlinsley** [comment]
This should be fixed now :) Huzzah!
