### ISSUE TITLE
pageSize propType missing [V6]

### ISSUE THREAD

**Issue by dgavara** [tannerlinsley/react-table#1368]
https://github.com/tannerlinsley/react-table/blob/v6/src/propTypes.js

@tannerlinsley I see pageSize propType missing in proptypes. Because of this I am getting this warning:

`checkPropTypes.js:23 Warning: Failed prop type: t: prop type `pageSize` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined``

Can this be fixed?

**Comment by tannerlinsley** [comment]
V6 is no longer maintained. I would suggest forking the v6 branch, implementing any changes you see fit, and using that branch until you can upgrade to v7.
