### ISSUE TITLE
Dynamically setting show property of react-table does not show or hide columns viceversa

### ISSUE THREAD

**Issue by velsonjr** [tannerlinsley/react-table#1376]
I am using react-table for the data-grid purpose. I am implementing a settings icon which shows the list of columns and based on the selection, the column gets shown or hidden. I am manipulating "show" property of columns object for this. While the property is getting set properly, there is no such change in the table.

Code Sandbox: https://codesandbox.io/s/blue-cherry-di3ub

**Comment by DDinenno** [comment]
I've gotten this to `semi-work` by returning a new object to the column prop inside a hook whenever a state variable changes.  By  `semi-work` I mean the columns inside the body are updating, but the headers are ignoring the `show` property in columns.
