### ISSUE TITLE
Next page 

### ISSUE THREAD

**Issue by lishine** [tannerlinsley/react-table#1378]
The bug  #1345 returns

Using 7.0.0-alpha.6

**Describe the bug**
When doing next-page, the state.pageIndex switches momentarily to 1 but then immediately returns being 0.

**To Reproduce**
Using the react-table in the manual mode.
The bug is while using the npm package
Switching to sandbox code, the bug dissappears

**Expected behavior**
Switch the pageIndex state to the next page index till 'further notice'

**Desktop (please complete the following information):**
 - OS: Windows 10 pro 1809
 - Chrome 75.0.3770.100

**Comment by ggascoigne** [comment]
I think that this might be the same bug as is addressed in https://github.com/tannerlinsley/react-table/pull/1369

**Comment by brycejacobs** [comment]
This is happening to me as well. It only briefly changes the pageIndex past 0, then flips right back.

I haven't had a chance to nail down the culprit, but more than likely the useLayoutEffect.

**Comment by lishine** [comment]
Maybe it is SSR related. Because me on Next.js, it gives warning that useLayout don't work on server

**Comment by jackpope** [comment]
@tannerlinsley could a new release be made available with the merged solution in #1369 ?

**Comment by jackpope** [comment]
I'm also having an issue where `goToPage()` doesn't change the state at all during manualPagination. When I explicitly update the table state with a `pageIndex`, I get the flash back to 0 issue described here.

**Comment by tannerlinsley** [comment]
The latest release addresses this issue.
