### ISSUE TITLE
Grouped rows should be expandable

### ISSUE THREAD

**Issue by AkshayRaut1321** [tannerlinsley/react-table#1382]
When we toggle Group By on columns, it shows a pointer for summary of records that are grouped but it doesn't let me see the grouped rows individually under each group. It should be collapsible.

**Comment by Codar97** [comment]
This is just an issue with the local version of react-table used in the demo being outdated. An updated version can be found in this https://github.com/tannerlinsley/react-table/issues/1252#issuecomment-505107866 which uses the "next" version of react-table found on [npm](https://www.npmjs.com/package/react-table)

**Comment by AkshayRaut1321** [comment]
Okay. Thank you.
