### ISSUE TITLE
How to change the default styles of an editable cells

### ISSUE THREAD

**Issue by mdsaon** [tannerlinsley/react-table#1389]
I have a react-table and the cells of the tables are editable. I am trying to change the default colors of the editable cell. Specifically, when the user clicks to a cell value the default border color should be removed and the entire text should be highlighted...

**Comment by tannerlinsley** [comment]
v6 is no longer in active maintenance, so we suggest that you ask this question in the community forum https://spectrum.chat/react-table. Thanks!
