### ISSUE TITLE
Filtered data list

### ISSUE THREAD

**Issue by stropitek** [tannerlinsley/react-table#139]
Let's say I have a page size of 5 in my table. My `data` prop contains an array of 20 elements, and I navigate to page 4. Now let's say I filter the list somehow  and now my `data` prop contains only 10 elements. Now I'm stuck on page 4 with no data and I have to navigate to load a safe page. (You can reproduce this behavior [here](https://neptunjs.github.io/experiments/parallel_coordinates/) )

 I'm not sure weather this is a bug in React-table or if I should use a controlled ReactTable in this case.

**Comment by tannerlinsley** [comment]
This should be fixed in the latest version :)  When changing pageSizes, the current page is translated to an equivalent page based on the ratio of the new pageSize.

**Comment by stropitek** [comment]
The problem I was having was not when updating pageSize, but when updating data with a new array. When it happens, the current page stays the same, but the data array could be smaller and contain no data at the index `page * pageSize`. Thus I would expect the page to be systematically set back to 1 when the data prop changes.

**Comment by tannerlinsley** [comment]
Interesting. I'll look into this
