### ISSUE TITLE
Default filter select option is not working

### ISSUE THREAD

**Issue by sebiglesias** [tannerlinsley/react-table#1391]
# Using v6?
No

# Using v7?
Yes

**Describe the bug**
By following the example of custom filtering, if I have a default option for the select filter, it won't work unless I force the onChange method by picking other option.

**To Reproduce**
1. Go to the cusotm-filtering example
2. In line 72, instead of 'all' pick a different default value, for example true
3. You will see that the table has now the Can Drink option (if you picked true), but the column is not filtered, you'll see both Yes and No answers, where you should only see Yes.

**Expected behavior**
To be filtered with the default value I chose, running the filtering once.
**Codesandbox!**
https://codesandbox.io/s/react-table-custom-filtering-rb97f
**Screenshots**
![image](https://user-images.githubusercontent.com/13668861/60742038-08742c80-9f42-11e9-8365-4a8b26cbf3f9.png)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome

**Smartphone (please complete the following information):**
Haven't tried
**Additional context**
None

**Comment by sebiglesias** [comment]
Awesome table by the way

**Comment by tannerlinsley** [comment]
Thanks Seb!

Unfortunately, the v6 branch and examples are not in active maintenance any longer. I'm actively working on v7 though. It's headless, brand new and doesn't suffer from this issue. I can only suggest you try out the alpha while I get it ready for release.
