### ISSUE TITLE
An expanded rows expanded state is only tied to the row index

### ISSUE THREAD

**Issue by Codar97** [tannerlinsley/react-table#1395]
V7
When using expanded rows and sorting together the state of the expanded row isn't tied to the exact row just the index.

An example and steps to replicate shown below:
Grouping by age and expanding the age equal to 0 as shown below
```
Age   | Name  
v 0   |
├─ 0  |  Peter
└─ 0  |  John
> 1   |
```
Then sorting by name causes the rows to reorder as expected however now the age group equal to 1 is expanded whereas the age group 0 is expected to be expanded.
Actual:
```
Age   |  Name
v 1   |
├─ 1  |  Alex
└─ 1  |  Bob
> 0   |
```
Expected:
```
Age   |  Name
> 1   |
v 0   |
├─ 0  |  Peter
└─ 0  |  John
```

This can be tested in the sandbox demo [here](https://codesandbox.io/embed/react-table-v7-sandbox-cr3eh) by following the steps mentioned above.

**Comment by tannerlinsley** [comment]
I'll take a look into this.

**Comment by tannerlinsley** [comment]
Indeed, `useExpanded` is using the materialized row index, and not the original index to track expanded state. This should be fixed in the next alpha release 👍.

**Comment by tannerlinsley** [comment]
This is fixed in the latest alpha release.
