### ISSUE TITLE
Drag the column of react-table to adjust the column width failed

### ISSUE THREAD

**Issue by RanOfXuan** [tannerlinsley/react-table#1396]
**Describe the bug**

I can't adjust the column width by dragging the column of the react-table, and the style of the table row will be removed whenever I do the drag, and each column will not be aligned.

Strangely, i have no problem dragging when my code in the environment of one of my colleagues, but in other environments I have the problem than described above

"react-table": "^6.9.2",

My column is defined like this, and gives each column a different id, I want to ask you have encountered this kind of question?

    const columns = [
      {Header:()=>(<div style={{ textAlign:"center" }}></div>),
        accessor:'blue point',
        width: 20,
        id:'bluePoint',
        Cell: (row)=><div className="universal_discovery_nowrap">{this.getIfBluePiont(row)}</div>
      },
      {
        Header:()=>(<div style={{ textAlign:"left" }}><FormattedMessage id={IntlConst.DISCOVERY_SCHEDULE_TABLE_NAME}/></div>),
        accessor:'jobDisplayName',
        id:'jobDisplayName',
        Cell: (row)=><div className="universal_discovery_nowrap" title={row.value}>{this.getRowByChecked(row)}</div>
      },
      {
        Header:()=>(<div style={{ textAlign:"left" }}><FormattedMessage id={IntlConst.DISCOVERY_SCHEDULE_TABLE_ADAPTER}/></div>),
        accessor:'adapterName',
        id:'adapterName'
      },
      {
        Header:()=>(<div style={{ textAlign:"left" }}><FormattedMessage id={IntlConst.DISCOVERY_SCHEDULE_TABLE_INPUT_CI_TYPE}/></div>),
        accessor: 'inputCi',
        id:'inputCi'
      },
      {
        Header:()=>(<div style={{ textAlign:"left" }}><FormattedMessage id={IntlConst.DISCOVERY_SCHEDULE_TABLE_DISCOVERED_CITS}/></div>),
        accessor: 'outputCis',
        id:'outputCis'
      },
      {
        Header:()=>(<div style={{ textAlign:"left" }}><FormattedMessage id={IntlConst.DISCOVERY_SCHEDULE_TABLE_PROTOCOL}/></div>),
        accessor: 'protocol',
        id:'protocol'
      },
    ];

**Comment by tannerlinsley** [comment]
I would suggest rolling back the version of your table until you do not experience the bug anymore in v6. Unfortunately, I'm not actively supporting v6 anymore. I can only suggest that you give v7 alpha a try in the meantime until it's released.
