### ISSUE TITLE
Horizontal scroll using touchpad

### ISSUE THREAD

**Issue by danilads** [tannerlinsley/react-table#1397]
When I use touchpad for horizontal scrolling, a have double scrolls.
It can fixed by adding class .rt-tbody{overflow-x: hidden;}.
![Screen Shot 2019-07-16 at 11 28 11](https://user-images.githubusercontent.com/37548942/61278615-2f8df200-a7bd-11e9-9140-de71f013b96f.png)

**Comment by danilads** [comment]
If I add to .rt-tbody{border:1px dashed black}. Double scroll become visible
<img width="446" alt="Screen Shot 2019-07-16 at 11 31 43" src="https://user-images.githubusercontent.com/37548942/61278750-6a902580-a7bd-11e9-914a-6b04bf7f858f.png">

**Comment by danilads** [comment]
For limiting width of React Table I use 
<ReactTable
					className={'ReactTable'}
					data={data}
					columns={columns}
					minRows={1}
					defaultPageSize={20}
					style={{
						width: "500px",
						height: "400px" 
					}}

**Comment by tannerlinsley** [comment]
This is a common problem with the old UI in v6. As you may already know though, we're working on a new version that is headless and therefore does not have this problem in the library. Please consider trying the alpha (documentation is coming soon).
