### ISSUE TITLE
minRows last page bug

### ISSUE THREAD

**Issue by danilads** [tannerlinsley/react-table#1398]
When I use minRows={1}, on last page if more than one items they will be stretched.
(one element)
<img width="414" alt="Screen Shot 2019-07-16 at 12 15 35" src="https://user-images.githubusercontent.com/37548942/61282137-77177c80-a7c3-11e9-8144-0e6e791263d2.png">
(more than one element)
<img width="413" alt="Screen Shot 2019-07-16 at 12 15 42" src="https://user-images.githubusercontent.com/37548942/61282142-7848a980-a7c3-11e9-8965-40dfe5c63ec0.png">

**Comment by danilads** [comment]
I can fix it using .rt-tr-group{ flex: 0 0 auto;}

**Comment by tannerlinsley** [comment]
This is in v6, which we are no longer actively working on. Please consider trying the alpha version of React Table.
