### ISSUE TITLE
The default css overwrites the checkbox appearance if included into a custom cell.

### ISSUE THREAD

**Issue by hegelstad** [tannerlinsley/react-table#14]
http://stackoverflow.com/questions/20057581/css-webkit-appearance-none-is-causing-checkbox-to-not-be-checked

**Comment by tannerlinsley** [comment]
I would accept a PR that fixes this @hegelstad

**Comment by tannerlinsley** [comment]
Closing for now, but will still accept a PR to fix this edge case. :)
