### ISSUE TITLE
Sorting on one property and displaying another feels hacky.

### ISSUE THREAD

**Issue by hally9k** [tannerlinsley/react-table#140]
If I want to sort on a person's name but show a composite output of their other attributes, am I forced to select the desired sort value with the accessor and dig the person out of the row object?

Example of my column config object:
```
accessor: 'person.name',
render: ({ row: { person: { age, gender, name } } }) => (
   <div>
      <h2>{name}</h2>
      <p>{age}</p>
      <p>{gender}</p>
   </div>
) 
```

This works just fine but feels a little hacky. If there is a cleaner way to do this I'm all ears, I have only just picked up this library this week.

Maybe a `sortValue` attribute would allow the differentiation between the accessor choosing the value for the cell to render and the value that is passed into the sorting algorithm.

It might look something like this and would possibly be more easily understood:
```
accessor: 'person',
sortValue: 'name',
render: ({ value: { age, gender, name } }) => (
   <div>
      <h2>{name}</h2>
      <p>{age}</p>
      <p>{gender}</p>
   </div>
) 
```

Many many thanks for all the awesome work here! 😄

**Comment by tannerlinsley** [comment]
First off, thanks for using React Table!
Great to see it help people.

The api decisions your referring to were carefully made when I initially built the component and actually help to solve the scenario you are describing.  It happens very frequently.

When using string accessors, it may feel like more work to get at your values, and it very well may be.

To alleviate this, you can use functions for just about anything (including accessors), so you could easily factor out any repetition of nested paths if you feel it gets too monotonous:

```javascript
const fromPerson = prop => row => row.person[prop]
// ...
const columnDef = {
  accessor: fromPerson('name')
  ...
}
```

The goal of the component api is make as little assumptions as necessary to allow for greater customization and a wide range of use. Although what your suggesting would absolutely be more a shorter path for your situation, it would limit others who rely on the more flexible api.
