### ISSUE TITLE
Detected an unknown table action!

### ISSUE THREAD

**Issue by toth-istvan-zoltan** [tannerlinsley/react-table#1405]
**Describe the bug**
"Sort by" example throws exception when clicking on header to sort.
The check

`if (!actions[type]) {`

is wrong because _type_ is the "long name" of the action, while _actions_ is keyed by "short names".

**To Reproduce**
1. Start the sort by example.
2. Click on a header to sort by that column.

**Screenshots**
<img width="597" alt="Screenshot 2019-07-24 at 9 02 13 (2)" src="https://user-images.githubusercontent.com/16266294/61772643-10154b80-adf3-11e9-962f-13e4dc555b7b.png">
<img width="599" alt="Screenshot 2019-07-24 at 9 02 02 (2)" src="https://user-images.githubusercontent.com/16266294/61772650-13a8d280-adf3-11e9-9051-bc6ebfd116cd.png">

**Comment by tannerlinsley** [comment]
This is a known bug. I've got a fix queued up. I'll push it in the Morning

**Comment by tannerlinsley** [comment]
Fixed in the latest push to master. Update the codesandbox and it should work just fine now :)

**Comment by toth-istvan-zoltan** [comment]
Thanks, that was super fast!

**Comment by brycejacobs** [comment]
Any plans on rolling a new alpha release for this fix?

**Comment by tannerlinsley** [comment]
The latest alpha release should work :)
