### ISSUE TITLE
Unnecessary scroll on last page when it contains less number of rows than previous page.

### ISSUE THREAD

**Issue by digholesnehal** [tannerlinsley/react-table#1407]
If I change the page and go to the last page and the number of rows present on last page is less than that of others then it shows the empty white space. Then I need to pull the scroll upward till I find the React Table's body.
I tried Adding reference to one of header and in onPageChange method I was forcefully scrolling it to that reference. It was working well for other pages but last page is still the same.

Example:
If I have an array of 406 elements. And my page size is 100 then on 5th page it has only 4 rows to show as minimum row value is 1. when I jump to or goto last page initially it takes the screen height same as it took for other previous pages but here only white screen is visible. And if I pull the scroll upward then the page size get reduced automatically and page size become fit for those 4 rows only.

**Comment by tannerlinsley** [comment]
`minRows={0}`

**Comment by digholesnehal** [comment]
Sorry but I couldn't explain an issue properly I guess, I am attaching a video which will explain 
issue.

[New folder.zip](https://github.com/tannerlinsley/react-table/files/3435141/New.folder.zip)

**Comment by tannerlinsley** [comment]
There are 2 ways to fix this:
1. Use `minRows={currentPageSize}` to force the table to have the same height regardless of page
2. Implement your own scroll logic to watch for circumstances like that and scroll to the last row in the table.

Outside of those two solutions, this is not the direct responsibility of React Table :/
