### ISSUE TITLE
prop 'loading' doesn't work

### ISSUE THREAD

**Issue by jchenjc** [tannerlinsley/react-table#141]
Hi, 

I have the following structure

```
class CustomTable extends Component {
  state: {loading: false}
  handleOnClickOfSomeButton: <set the loading in state to be true, wait, and then reset it later>

  <ReactTable loading={this.state.loading} ... />
}
```

I was expecting the "loading"-styles to show up when I clicked on the button, but that's not the case, changing state didn't do anything to the styles of the table. I'm positive that the state got updated correctly. I rowPivot some columns in my data, right after clicking on the button (before the reset happened), the loading-styles showed up when I expanded a row pivot group, and the styles would stay there even after the rest. 

Is this a bug or did I do something wrong? 

Thanks!

**Comment by jchenjc** [comment]
Thanks for the quick response @tannerlinsley.

I was looking for a simpler workaround for the issue without defining my custom components for the table. As you mentioned, the loader should be shown and hidden automatically based on the "loading" property. But since that's not working for me, I'll try what you suggested to "control" the components myself. Thanks!

**Comment by tannerlinsley** [comment]
If you post your code, we may be able to see why it's not working. Make sure you're using the latest version too :) Let me know how it works out.

**Comment by jchenjc** [comment]
I'm on "react-table": "^5.0.4". 

My case is straightforward, I wrapped <ReactTable /> into another component. The initial state of 'loading' is false
```
const ReactTableWrapper = props => {
  return (
    <div>
      <div onClick={props.OnClickOfSomeButton}>Refresh</div>
      <ReactTable {...props} />
    </div>
  )
}
class CustomTable extends Component {
  state: {isLoading: false, data: []}
  handleOnClickOfSomeButton: <set the loading in state to be true, make a rest call to fetch data, and then reset the isLoading boolean after receiving the data>

  <ReactTableWrapper 
      ...otherProps
      loading={this.state.isLoading} 
      data={this.state.data}
      OnClickOfSomeButton={this.handleOnClickOfSomeButton}
  />
}
```
If the data is changed, then the "loading" UI works automatically; however if data stays the same (i was testing by hardcoding an array of data values), then the "loading" UI layer does not work. 

Another property that gave me the same trouble is "defaultPageSize". I want to control the defaultPageSize based on the length of the data array: `defaultPageSize = data.length >= 100 ? 100 : data.length;`. Initially, when the data is an empty array, it's fine; but after I click my "Refresh" button to update the data (more than 100 rows), <ReactTable> is showing 10 rows per page for some reasons, my defaultPageSize property is being ignored.

Let me poke around more to see how I can semi-control the table if default behavior doesn't work for me.

**Comment by tannerlinsley** [comment]
Loading is only applicable when using server side manual mode. Otherwise
you cannot manually set the loading overlay. Are you doing server side data?

**Comment by jchenjc** [comment]
Good point @tannerlinsley! I am doing server side data, but I thought the 'manual' property is only for sorting and pagination
> manual // informs React Table that you'll be handling sorting and pagination server-side

I still want the client to control the sorting and pagination, that's why I didn't set it to true.

**Comment by tannerlinsley** [comment]
Ah! If that's the case, you can treat it as client-side and ignore all of the server-side configuration props.  As for `loading`, you should still be able to override it.

1. Make sure you upgrade to version 5.4.0
2. Try the `loading` prop again doing everything client side
3. If it still doesn't work, let's try to get a codepen up and running to try and replicate the issue.

**Comment by jchenjc** [comment]
Upgrading seems to work, thanks @tannerlinsley!

**Comment by tannerlinsley** [comment]
You bet
