### ISSUE TITLE
Infinity render with usePaginaton

### ISSUE THREAD

**Issue by toastyboost** [tannerlinsley/react-table#1411]
Hi, when i use  usePaginaton i got infinity render on my func component

My test component:

```
import React from 'react';
import { useTable, useColumns, useRows, usePagination } from 'react-table';

export default function Table({ data, columns }) {
  const instance = useTable(
    {
      data,
      columns,
    },
    useColumns,
    useRows,
    usePagination
  );

  console.log('render', instance);
  return <div />;
```

Place where i am use component: 

```
const columns = [
  {
    Header: '#',
    accessor: 'RANK',
  },
];

const data = [
  {
    RANK: 1,
  },
  {
    RANK: 2,
  },
]

<Table
       columns={columns}
       data={data}
/>
```
What i get - infinity render every 1ms
https://gyazo.com/18d8e2662f1cd79ebfccb7e02d236bd0

Can someone help me? What's it may be? 

"react-table": "^7.0.0-alpha.12",
 "react": "^16.8.6",

**Comment by toastyboost** [comment]
I made it
https://codesandbox.io/s/react-table-v7-sandbox-z6cvl

just uncomment console.log and watch console.panel

**Comment by mgpsp** [comment]
I'm having the same problem.

**Comment by tannerlinsley** [comment]
I'll be writing examples and tests for usePagination in the next few days. I'll likely uncover the bug then. Stay tuned.

**Comment by tannerlinsley** [comment]
Just tested with the latest alpha and this looks to be fixed on my end.
