### ISSUE TITLE
Infinity render using useSortBy with usePagination v7

### ISSUE THREAD

**Issue by JordanW7** [tannerlinsley/react-table#1422]
When using `useSortBy` with` usePagination`, it will cause an infinite rerender if there are multiple tables on the page and you click the 'sort' on one table, and then click 'sort' on another table.

**Comment by tannerlinsley** [comment]
Can you please make a code sandbox with this bug please?

**Comment by JordanW7** [comment]
Code sandbox currently only has up to alpha 12, which has the separately recently closed issue of infinity render using `usePagination`, so I cannot create with this.

**Comment by JordanW7** [comment]
https://codesandbox.io/embed/great-cdn-mwtxq Here's an example that causes the bug locally on `alpha16`. It doesn't seem to cause any problems on the sandbox running `alpha12`, but `alpha12` locally causes infinite rerender with `usePagination`.

**Comment by JordanW7** [comment]
Appears to be only related to using `react-styleguidist` with `react-table v7`. The same code works fine with a clean `create-react-app`

**Comment by tannerlinsley** [comment]
That's really strange. I'll let you close this then, unless you have any more information you'd like to put here about `react-styleguidist`?

**Comment by JordanW7** [comment]
Closing for now while it seems contained to interaction with `react-styleguidist`.
