### ISSUE TITLE
useSortby must be listed prior to usePagination in useTable v7

### ISSUE THREAD

**Issue by JordanW7** [tannerlinsley/react-table#1423]
Example:
```  
const instance = useTable(
    {
      columns,
      data: currentData
    },
    usePagination,
    useSortBy, // This must be listed before usePagination to behave correctly
  );
```

This will cause the sorting of the data not to occur, although the sort props such as `column.sorted` and `column.sortedDesc` will still return as expected.

**Comment by tannerlinsley** [comment]
You are correct. We need to add an order warning for that.
