### ISSUE TITLE
 Do I need data after the filter can be done?

### ISSUE THREAD

**Issue by sarunopassawas** [tannerlinsley/react-table#1424]
<ReactTable
                    columns={columns}
                    data={this.state.posts}
                    filterable
                    defaultPageSize={10}
                    noDataText={"Please Wait..."}
                > </ReactTable>

 Do I need data after the filter can be done?

**Comment by tannerlinsley** [comment]
I'm not sure what you're asking, but you could try to ask this question on https://spectrum.chat/react-table. Be sure to label your question with the [v6] tag, too. Thanks!
