### ISSUE TITLE
V7 - Setting `disableSort` on a column does not work.

### ISSUE THREAD

**Issue by bbigard** [tannerlinsley/react-table#1425]
V7

**Describe the bug**
Setting `disableSort` on a column does not work.

In https://github.com/tannerlinsley/react-table/blob/master/src/plugin-hooks/useSortBy.js#L167

```
    const canSort = accessor
      ? getFirstDefined(
          columnDisableSorting,
          disableSorting === true ? false : undefined,
          true
        )
      : false
```

If `columnDisableSorting` is true, `canSort` gets set to true. `canSort` should be set to false if `columnDisableSorting` is true.

I think that should be enough information. However, if you need reproduction steps or a codesandbox let me know.

Thanks for the great work on this project!

**Comment by tannerlinsley** [comment]
A fix for this has been merged to master. Thanks!
