### ISSUE TITLE
'useTable' is not exported from 'react-table'

### ISSUE THREAD

**Issue by cuongw** [tannerlinsley/react-table#1426]
- react: 16.8.6
- react-table: 6.10.0

![111](https://user-images.githubusercontent.com/34389409/62344195-42bbf400-b517-11e9-8e8e-9af424e0a095.png)

**Comment by cuongw** [comment]
Sorry, I close issue because mistake versions.
Thanks for awsome package.

**Comment by CallumHemsley** [comment]
Mistake versions? What do you mean? Having same issue.

**Comment by cuongw** [comment]
Hey @CallumHemsley, document on GitHub is version 7 but I install react-table version 6.

**Comment by CallumHemsley** [comment]
@cuongw so you just did 'npm install react-grid@7.0.0' ?

**Comment by cuongw** [comment]
@CallumHemsley, `npm install react-table@next`

**Comment by cuongw** [comment]
@CallumHemsley, I need a stable package, so I choose version 6.

**Comment by nabeelnazirvf** [comment]
@cuongw I am having same issue.
I have following in my `package.json` file:
```
"react": "^16.2.0",
"react-table": "^6.10.0"
```
Can I use `useTable` with these above versions? If not can I use it by updating the react table to latest version only with the same mentioned react version which is `16.2.0`?
Please confirm.

Thank you.

**Comment by Lekha30** [comment]
I also have the same issue. My react version is 18.0.0 and I am using react-table version 7.8.0. Any input is much appreciated.
