### ISSUE TITLE
useFlexLayout plugin hook error

### ISSUE THREAD

**Issue by Codar97** [tannerlinsley/react-table#1428]
V7
I'm not sure if I am doing something wrong with the configuration of the useFlexLayout plugin but using it gives the following error: `Cannot read property 'columns' of undefined`

I am using the plugin as shown below.
```javascript
  const { getTableProps, headerGroups, rows, prepareRow } = useTable({
    columns,
    data,
  },
  useFlexLayout
  )
```
This error occurs in version 7.0.0-alpha.13 and above

**Comment by tannerlinsley** [comment]
The flex layout hook is currently out of date. I'll be updating or deprecating the plug-in in the next few alpha releases.

**Comment by paolostyle** [comment]
If you urgently need it here's my updated version, works pretty much the same as the old one and is compatible with alpha.19. Since @tannerlinsley mentioned potential deprecation I guess it can be useful in the future.

```
import PropTypes from 'prop-types';

function sum(arr) {
  return arr.reduce((prev, curr) => prev + curr, 0);
}

function getFirstDefined(...args) {
  for (let i = 0; i < args.length; i += 1) {
    if (typeof args[i] !== 'undefined') {
      return args[i];
    }
  }
  return undefined;
}

function getSizesForColumn(
  { columns, id, width, minWidth, maxWidth },
  columnMeasurements,
  defaultFlex
) {
  if (columns) {
    columns = columns
      .filter(col => col.show || col.visible)
      .map(column => getSizesForColumn(column, columnMeasurements, defaultFlex))
      .filter(Boolean);

    if (!columns.length) {
      return false;
    }

    const flex = sum(columns.map(col => col.flex));
    const width = sum(columns.map(col => col.width));
    const maxWidth = sum(columns.map(col => col.maxWidth));

    return {
      flex,
      width,
      maxWidth
    };
  }

  return {
    flex: width ? 0 : defaultFlex,
    width:
      width === 'auto'
        ? columnMeasurements[id] || defaultFlex
        : getFirstDefined(width, minWidth, defaultFlex),
    maxWidth
  };
}

function getStylesForColumn(column, columnMeasurements, defaultFlex) {
  const { flex, width, maxWidth } = getSizesForColumn(column, columnMeasurements, defaultFlex);

  return {
    flex: `${flex} 0 auto`,
    width: `${width}px`,
    maxWidth: `${maxWidth}px`
  };
}

const propTypes = {
  defaultFlex: PropTypes.number
};

const useMain = props => {
  PropTypes.checkPropTypes(propTypes, props, 'property', 'useFlexLayout');

  const {
    defaultFlex = 1,
    columns,
    hooks: { getRowProps, getHeaderGroupProps, getHeaderProps, getCellProps }
  } = props;

  const visibleColumns = columns.filter(column => column.visible);
  const columnMeasurements = {};

  let sumWidth = 0;
  visibleColumns.forEach(column => {
    const { width, minWidth } = getSizesForColumn(column, defaultFlex);
    if (width) {
      sumWidth += width;
    } else if (minWidth) {
      sumWidth += minWidth;
    } else {
      sumWidth += defaultFlex;
    }
  });

  const rowStyles = {
    style: {
      display: 'flex',
      minWidth: `${sumWidth}px`
    }
  };

  getRowProps.push(() => rowStyles);
  getHeaderGroupProps.push(() => rowStyles);

  getHeaderProps.push(column => ({
    style: {
      boxSizing: 'border-box',
      ...getStylesForColumn(column, columnMeasurements, defaultFlex)
    }
  }));

  getCellProps.push(cell => {
    return {
      style: {
        ...getStylesForColumn(cell.column, columnMeasurements, defaultFlex, undefined, {
          rowStyles
        })
      }
    };
  });

  return props;
};

const useFlexLayout = hooks => {
  hooks.useMain.push(useMain);
};

export default useFlexLayout;
```

**Comment by tannerlinsley** [comment]
This is extremely helpful. And, extremely impressive that it fits into a single code block like that :). Can you imagine how this would even be feasible in v6?! 💯

**Comment by paolostyle** [comment]
Oh yeah, definitely, I really love the extensibility that v7 provides, I never actually used v6 but so far I only had rather unpleasant experiences with premade table components for React. With v7 I have to put a bit more work initially but I have absolute control over almost everything, which is just amazing, especially when the project I'm working at has very dynamically changing requirements.

**Comment by tannerlinsley** [comment]
This should be fixed in master now.

**Comment by ggascoigne** [comment]
I don't think that this is actually fixed on master.

useFlexLayout still references hooks.columns, and no such value exists, there's certainly no such hook value defined in useTable where the set of hooks are defined.

**Comment by tannerlinsley** [comment]
Oh yeah... Sorry, the code for useFlexLayout is supposed to be deprecated for now. If you would like to know how to make the existing hook work, I could give you some direction, but I don't think I'm going to support it as a first-class citizen in this release.

**Comment by ggascoigne** [comment]
that's fine, the version that paolostyle posted works fine, this was more a comment in response you yours saying that it should be fixed.

Do you think that you should just delete it from the repo if you're not going to fix it?

**Comment by tannerlinsley** [comment]
Yes. That's a good idea.

**Comment by arianitu** [comment]
@tannerlinsley is useFlexLayout still deprecated?

**Comment by pmorgan3** [comment]
> 
> 
> @tannerlinsley is useFlexLayout still deprecated?

It's usable in the latest version.

**Comment by ggascoigne** [comment]
Tanner added a new version a little while ago, I can't speak for him, but I think that it's fair to say that it's no longer deprecated.  I'm using the new version quite successfully.

**Comment by arianitu** [comment]
So I tried using `useFlexlayout`, it seems to work okay but I am confused on how to make the table shrink as the container gets smaller?

The examples show scrollbars, but I actually want the table columns/cells to resize as I make the browser window smaller. Usually you use flex-basis with flex-shrink to make this happen, is this possible with useFlexlayout?

**Comment by arianitu** [comment]
I've decided to just implement my own useFlexLayout which utilizes flex-grow, flex-shrink and flex-basis that are defined on the columns, like so:

```
  const getColumns = () => [
    {
      ...
      id: 'firstName',
      accessor: 'firstName',
      flexBasis: '10rem',
      flexShrink: 2,
      flexGrow: 1,
      ....
    },
    {
      ...
      id: 'Info',
      accessor: 'info',
      flexBasis: '20rem',
      flexShrink: 1,
      flexGrow: 1
      ...
    },
```


```
export default function useFlexLayout(hooks) {
    hooks.getTableProps.push(getTableProps)
    hooks.getTableBodyProps.push(getTableBodyProps)
    hooks.getRowProps.push(getRowStyles)
    hooks.getHeaderGroupProps.push(getRowStyles)
    hooks.getHeaderProps.push(getHeaderProps)
    hooks.getCellProps.push(getCellProps)
  }
  
  useFlexLayout.pluginName = 'useFlexLayout'
  
  const getTableProps = (props, { instance }) => [
    props,
    {
      style: {        
        display: 'flex',   
        flexDirection: 'column' 
      },
    },
  ]

  const getTableBodyProps = (props, { instance }) => [
    props,
    {
      style: {},
    },
  ]
  
  const getRowStyles = (props, { instance }) => [
    props,
    {
      style: {
        display: 'flex',        
      },
    },
  ]
  
  const getHeaderProps = (props, { column }) => [
    props,
    {
      style: {
        boxSizing: 'border-box',
        flex: `${column.flexGrow || 0 } ${column.flexShrink || 1 } ${column.flexBasis || '0px'}`,
      },
    },
  ]
  
  const getCellProps = (props, { cell }) => [
    props,
    {
      style: {
        boxSizing: 'border-box',
        flex: `${cell.column.flexGrow || 0 } ${cell.column.flexShrink || 1 } ${cell.column.flexBasis || '0px'}`,
      },
    },
  ]
  ```

**Comment by ggascoigne** [comment]
Hmm, I've had no problem getting the columns to resize.  That said, there are all sorts of constraints in the standard useFlexLayout plugin.  It works with useGroupBy and the useResizeColumns plugins, getting the columns layout to work with grouped columns presents a lot of challenges - if you don't use that feature, then it's certainly easier to come up with a different implementation.

**Comment by arianitu** [comment]
@ggascoigne are your columns automatically resizing based on the parent container, or are you manually dragging your columns to make them smaller?

In our case, we just want the table to be responsive based on how wide the user has their browser window, maybe we are doing something wrong with the default useFlexLayout?

**Comment by ggascoigne** [comment]
take a look at https://github.com/ggascoigne/react-table-example,  Note that this is using a build of react-table including at least one fix that's been merged to master and not released yet.
