### ISSUE TITLE
"useSortBy should be placed before useFilters" warning even though it already is that way

### ISSUE THREAD

**Issue by paolostyle** [tannerlinsley/react-table#1432]
**Describe the bug**
As in title. The warning: `useSortBy.js:75 React Table: useSortBy should be placed before useFilters in your plugin list for better performance!` appears even though my instance looks like this:
```
  const instance = useTable(
    {
      data,
      columns,
      // ...
    },
    useSortBy,
    useGroupBy,
    useFilters,
    useExpanded,
    usePagination
  );
```
If I swap them I'll get an error that useSortBy should be before useFilters, so I think something is not right. Also it seems like the code works the other way around (i.e. it warns when useFilters is after useSortBy), lines 65-79 in useSortBy.js. I'd make a PR but the comment there is very confusing so I don't really know how should it behave.

**To Reproduce**
Put useSortBy plugin before useFilters in useTable.

**Expected behavior**
No warning

**Desktop (please complete the following information):**
irrelevant, but Win 10, Chrome 77

**Additional context**
alpha.19

**Comment by tannerlinsley** [comment]
This will be fixed in the next version :)

**Comment by paolostyle** [comment]
Seems like it's solved.
