### ISSUE TITLE
How to make async while sorting?

### ISSUE THREAD

**Issue by toastyboost** [tannerlinsley/react-table#1435]
Hi, i got table with charts. When data for table has arrived i'm fetch async action to get data for charts. For some reason while sorting i'm getting a loop, here is a code: 

```
const instance = useTable(
    {
      data,
      columns,
      state,
    },
    useSortBy,
    usePagination
  );

  const { page, prepareRow, headers, gotoPage } = instance;

  useEffect(() => {
      const { getSymbolChart } = fetchData;
      const symbols = page.map(item => item.original.ID);

      dispatch(getSymbolChart(symbols, '7d'));

  }, [page]);
```

How properly fetch async data while sorting? Please help!

**Comment by tannerlinsley** [comment]
It sounds like the `getSymbolChart` action is changing either `data`, `columns`, or `state`. Make sure those are not being recreated with every call to that action.
