### ISSUE TITLE
Codesandbox links for each example all lead to basic example

### ISSUE THREAD

**Issue by mmlumba** [tannerlinsley/react-table#1436]
Hi,

I was taking a look at your package and noticed that all the README's in each example folder lead to the same code sandbox link: https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/basic 

Do you have a link to each specific sample on Codesandbox, or is it advised to look at the examples locally? Thanks!

**Comment by tannerlinsley** [comment]
The links are in the main readme

**Comment by mmlumba** [comment]
Thanks so much for the prompt response! I missed that the first time. This link for the Editable Data example doesn't work though (should be examples/editable-data): https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/editable-cells

Should I submit a PR?

**Comment by tannerlinsley** [comment]
Yes please 😀
