### ISSUE TITLE
Incorrect Zappi link in the readme

### ISSUE THREAD

**Issue by p-himik** [tannerlinsley/react-table#1438]
It links to https://zappi.com/web but it seems that now Zappi uses https://zappi.io/web/

**Comment by tannerlinsley** [comment]
Please submit a PR

**Comment by p-himik** [comment]
I don't think I will.
It's up to you, Zappi, and your mutual communication to make sure that the sponsored link is correct.

**Comment by tannerlinsley** [comment]
I understand. I'll fix it preemptively given that a good link is infinitely better than a broken one, regardless of the location.
