### ISSUE TITLE
Filters example not working correctly

### ISSUE THREAD

**Issue by sandrojohanides** [tannerlinsley/react-table#1439]
Using React Table v7

**Describe the bug**
Filters are not working correctly in your own example, not sure if the bug is in the library or just the example. After trying to filter the `Status` column, you are unable to filter it again, since it only shows the `All` option. After applying the filter, `preFilteredRows` argument in `SelectColumnFilter` function returns an empty array.

Also the slider component cannot be moved, but filters the value once.

UPDATE:  
I suspect the empty array from `preFilteredRows` going into `useMemo` is the problem and it triggers an infinite loop (at least on my end). Removing the variable from the 2nd `useMemo` argument makes the filter work correctly.

**To Reproduce**
1. Go to https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/filtering
2. Click on the `Status` filter, or try to move the `Age` slider
3. Try to change the `Status` again, or move the `Age` slider again

**Expected behavior**
Filter should still be populated with all `Status` options, including `All`. It should be possible to move `Age` slider left & right.

**Screenshots**
![all](https://user-images.githubusercontent.com/8327913/62831354-16425f00-bc1e-11e9-9a14-ae8eebf067f1.PNG)  
![rows](https://user-images.githubusercontent.com/8327913/62831407-eba4d600-bc1e-11e9-908c-e71c292eac84.PNG)

**Desktop (please complete the following information):**
 - Any

**Comment by tannerlinsley** [comment]
I'll investigate this next. Thanks for your help!

**Comment by tannerlinsley** [comment]
This should be fixed in d9a4b6b
