### ISSUE TITLE
Header groups colSpan doesn't adjust with hidden columns

### ISSUE THREAD

**Issue by mbrandau** [tannerlinsley/react-table#1446]
> Thanks for using the alpha version of React Table v7! We're very excited about it.

Yes, and I'm excited too! 🔥 

**Describe the bug**
When hiding columns, the colSpan of their respective headers doesn't change, resulting in columns being shifted to wrong headers.

**To Reproduce**
1. Go to https://codesandbox.io/s/tannerlinsleyreact-table-basic-b33h9
2. Play around with the checkboxes to hide the columns
3. Notice how the colSpan of the header groups doesn't change and columns get shifted to wrong headers

**Expected behavior**
The colSpan property of the header groups should be calculated with hidden columns in mind.

**Screenshots**
![All columns shown](https://user-images.githubusercontent.com/12972798/63026351-510cf700-beab-11e9-96b8-666c5c39221c.png)
All columns show in this one.

![Last name hidden](https://user-images.githubusercontent.com/12972798/63026350-510cf700-beab-11e9-9f79-7a409ed3cf32.png)
Last name is hidden, age gets shifted to the Name header group.

This bug seems to be easy to fix. I'm happy to follow up with a PR!

**Comment by mbrandau** [comment]
See [my commit](https://github.com/mbrandau/react-table/commit/47e2717d0675260eef4537b96264e908578dfca9#diff-58070e993396b86d9cd977598221d49eR249) for a possible fix.
I don't know why prettier changed that many lines though. 😕

**Comment by tannerlinsley** [comment]
I would love a PR!

**Comment by mbrandau** [comment]
The issue is occurring again. https://codesandbox.io/s/tannerlinsleyreact-table-basic-b33h9
I‘m gonna have a look at this again. A test for this case might be a good idea.
Please reopen this issue @tannerlinsley
