### ISSUE TITLE
Sorting on Fully Controlled Component

### ISSUE THREAD

**Issue by janvp** [tannerlinsley/react-table#145]
Hi,

I'm trying to use ReactTable with full control of the state (page, pageSize, sorting), as described in the documentation (chapter Fully Controlled Component). But when using the sorting, the actual sorting is always one sort-click behind. 

I can send an example to show the issue (I wanted to make a fiddle or codepen, but I don't know how to include the react-table library).

**Comment by tannerlinsley** [comment]
Can you paste your code here?

**Comment by tannerlinsley** [comment]
Try upgrading to version 5.3.5

**Comment by janvp** [comment]
ok, here is my code. I didn't support multiple sorting here. 
I'll try also to upgrade to the new version. 
```
class FullyControlledTable extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            sort: [],
            page: 0,
            pages: Math.ceil(this.props.data.length / 10),
            pageSize: 10
        };
        this.handleSort = this.handleSort.bind(this);
        this.handlePageChange = this.handlePageChange.bind(this);
        this.handlePageSizeChange = this.handlePageSizeChange.bind(this);
    }

    handleSort(column) {
        let sort = [];
        if (this.state.sort[0] && this.state.sort[0].id == column.id) {
            sort.push({
                id: column.id,
                desc: !this.state.sort[0].desc
            });
        } else {
            sort.push({
                id: column.id,
                desc: false
            });
        }
        this.setState({
            sort: sort
        });
    }

    handlePageChange(pageIndex) {
        this.setState({
            page: pageIndex
        });
    }

    handlePageSizeChange(pageSize, pageIndex) {
        this.setState({
            pageSize: pageSize,
            page: pageIndex,
            pages: Math.ceil(this.props.data.length / pageSize)
        });
    }

    render() {
        return (
            <ReactTable
                data={this.props.data}
                columns={this.props.columns}
                page={this.state.page}
                pages={this.state.pages}
                pageSize={this.state.pageSize}
                sorting={this.state.sort}
                onSortingChange={this.handleSort}
                onPageChange={this.handlePageChange}
                onPageSizeChange={this.handlePageSizeChange}
            />
        );
    }
}
```

**Comment by tannerlinsley** [comment]
You should be able to directly setState with the sorting that given to you in `onSortingChange`.

```javascript
 handleSort(newSortingModel) {
        this.setState({
            sort: newSortingModel
        });
    }
```

Does that work for you?

**Comment by janvp** [comment]
The first parameter of `onSortingChange` is the column object and not the sorting object. So the `desc` key is not available.
I updated react-table to 5.3.5, but there's no difference. In the React-plugin of my browser, I see all the variables in the props and the same variables in the state. The values of the variables in the state are always one render behind. The variables in the props are always up-to-date. But, the `sortedData` variable is not available in the props. I think the issue is there somewhere.

**Comment by tannerlinsley** [comment]
Still waiting on other related issues and PR's to see if this get's fixed.  Will check back after #166 is merged or otherwise resolved.

**Comment by alebrozzo** [comment]
> when using the sorting, the actual sorting is always one sort-click behind.
Usually when this happens to me on a React application it's because the state is being updated after the data is fetch. And for react-table I don't keep track of pages or sorting, I let the table deal with it. Perhaps if you follow that approach it will fix it for you, @janvp

**Comment by janvp** [comment]
Thanks for your reaction, @alebrozzo , but I need control of the state of sorting and paging for different reasons.
But #166 solved the issue. Thanks a lot, @abbotteric !!
