### ISSUE TITLE
[v7-alpha.22] - filtering example does not work.

### ISSUE THREAD

**Issue by yyuurreecc5** [tannerlinsley/react-table#1453]
**Describe the bug**
The example of the filtering on the codesandbox does not work.

**To Reproduce**
1. Go to https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/filtering
2. Try to sort by any column.
3. Sorting does not work ant there are errors in the console.

**Expected behavior**
Sorting works correctly.

**Screenshots**
![Снимок экрана от 2019-08-16 13-44-12](https://user-images.githubusercontent.com/18028302/63162844-45950980-c02c-11e9-9c62-cd4a7f662498.png)

**Comment by tannerlinsley** [comment]
It should work now. Thanks!

**Comment by yyuurreecc5** [comment]
> It should work now. Thanks!

Unfortunately still not working..

**Comment by tannerlinsley** [comment]
Looks like codesandbox hasn't resolved `next` to the latest release yet. Try again?

**Comment by yyuurreecc5** [comment]
Yes, you were right, now it works correctly. Thanks!

**Comment by 1986webdeveloper** [comment]
Alpha Table
Alpha Table
Alpha Table
Alpha Table
Alpha Table
Alpha Table
