### ISSUE TITLE
[v7-alpha.23] - Table option "disablePageResetOnDataChange" does not work.

### ISSUE THREAD

**Issue by yyuurreecc5** [tannerlinsley/react-table#1455]
**Describe the bug**
Option "disablePageResetOnDataChange"  does not affect anything.

**To Reproduce**
1. Go to https://codesandbox.io/s/tannerlinsleyreact-table-pagination-controlled-j6l8m
2. Type something in any of the filters.
3. PageIndex is reset to zero although the option "disablePageResetOnDataChange" is set to true.

**Expected behavior**
After changing the filter, the pageIndex value is not reset to 0 when the option value is set to true.

**Codesandbox!**
Use a new [react-table codesandbox](https://codesandbox.io/s/tannerlinsleyreact-table-pagination-controlled-j6l8m) to reproduce the issue.

**Comment by tannerlinsley** [comment]
Good find. I'll look into this.

**Comment by tannerlinsley** [comment]
This should be fixed in the next release. Thanks!

**Comment by kret13** [comment]
any update about this, seems it still doesn't work?
