### ISSUE TITLE
Uncaught TypeError: (0 , _reactTable.useTable) is not a function

### ISSUE THREAD

**Issue by scottc11** [tannerlinsley/react-table#1457]
just a heads up, the default installation using `npm install react-table` installs version 6.10.0, but the documentation is for version 7 I believe?

I had issues following the examples and ran into this [StackOverflow question](https://stackoverflow.com/questions/57508300/uncaught-typeerror-0-reacttable-usetable-is-not-a-function) which solved the problem.

**Comment by dkozma** [comment]
@scottc11 You should be able to run `npm install react-table@next` to install the latest v7 version.

**Comment by tannerlinsley** [comment]
Yeah. We should probably update the docs to have the `@next`. Just need a disclaimer too that it's alpha.

**Comment by dlipeles** [comment]
+1 to ^ , I was seeing import errors on useSortBy since it's not in the latest version, upgrading to `@next` fixed it

**Comment by tannerlinsley** [comment]
This will be updated when we release beta soon. Closing for now.
