### ISSUE TITLE
[v6.10.0] componentWillReceiveProps warnings

### ISSUE THREAD

**Issue by nbar1** [tannerlinsley/react-table#1458]
I know v7 is under active development, but since it's not out on stable release yet is there any chance you can fix this warning on react@16.9.0?

> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: ReactTable

**Comment by Finrod927** [comment]
Same warning with componentWillMount

**Comment by tannerlinsley** [comment]
If you would like to submit a PR to fix this warning in a backwards compatible way (a patch or minor semver update), then I will gladly merge it. Otherwise, I suggest you fork v6 and implement your own fix until you're able to upgrade to v7.

**Comment by nbar1** [comment]
I've created PR #1461 for this issue. Thanks!

**Comment by benflodge** [comment]
This fix has broken compatibility with Preact, as they are not supporting the UNSAFE* methods https://github.com/preactjs/preact/issues/1047. I have fixed my react-table version to 6.10.0 as this version still works with Preact.

**Comment by sbcreates** [comment]
Is there an update on this?
