### ISSUE TITLE
[7.0.0-alpha.21] Expansion of sub rows does not open when the aggregate value has a "."

### ISSUE THREAD

**Issue by kddial** [tannerlinsley/react-table#1459]
**Describe the bug**
I am using the table with the groupBy feature; when I aggregate on a column and the string value has a period `.` it breaks the functionality of expanding the subrows.

**To Reproduce**
1. Go to https://codesandbox.io/s/tannerlinsleyreact-table-grouping-dpug3  (it was forked by the grouping example and I modified the makeData file).
2. You should notice that all the first names include a "." at index 1. For example `s.poon, t.rucks`
3. Click on "👊" to the left of the "First Name" header
4. The table should now be grouped by first name and the first name column should be green.
5. Click on "👉" on any of the cells in the "First Name" column.
6. Notice that it does not expand to show the sub rows.

**Expected behavior**
It is expected to show the sub rows for the aggregates.

**Codesandbox!**
https://codesandbox.io/s/tannerlinsleyreact-table-grouping-dpug3

**Screenshots**
<img width="612" alt="Screen Shot 2019-08-17 at 4 32 33 PM" src="https://user-images.githubusercontent.com/2696834/63217016-b0b60d00-c10c-11e9-89c0-5af68182b2f0.png">
Clicking on "👉" does not expand the sub rows. 

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra, Version 10.13.16
 - Browser Chrome
 - Version  76.0.3809.100

**Additional context**
Thank you very much for React Table! The new version is very easy to use and learn :)

**Comment by tannerlinsley** [comment]
Looks like we'll need to find a better key serializer for subrow state...

**Comment by tannerlinsley** [comment]
This is fixed in the latest release

**Comment by tannerlinsley** [comment]
Keep in mind the API has changed a bit for cell/column/row states. Many of the boolean states are now prefixed with `is`: https://github.com/tannerlinsley/react-table/blob/master/docs/api.md#cell-properties-1
