### ISSUE TITLE
Using examples that require an Alpha version, without documenting this causes confusion

### ISSUE THREAD

**Issue by gnesher** [tannerlinsley/react-table#1462]
**Describe the bug**
The listed examples in the documentation (https://github.com/tannerlinsley/react-table/blob/master/docs/examples.md) are all based on V7. Trying to run them will fail as master points to V6.

I could not find any documentation explaining this and new developers will simply assume the library is broken.

**To Reproduce**
Try to implement any of the examples in the documentation locally while installing react-table using 'npm install react-table'

**Expected behavior**
Examples on master should point to code examples that work on master

**Codesandbox!**
Use a new [react-table codesandbox](https://codesandbox.io/s/m5lxzzpz69) to reproduce the issue.

**Comment by andreydro** [comment]
Have the same problem

**Comment by tannerlinsley** [comment]
The examples must be linked to use the local version of the library of that's what you are asking. Otherwise, the examples at the very least point to the @next version of react table, so they should be downloading the alpha release at the very least when built with yarn.

Tanner Linsley

**Comment by tannerlinsley** [comment]
I've also updated the README and installation instructions to document any further discrepancies. Thanks!
