### ISSUE TITLE
Subcomponent max-height set to 60px

### ISSUE THREAD

**Issue by corby** [tannerlinsley/react-table#1464]
# Using v6?

v6 is now considered feature complete to its current abilities and limitations. We are not actively working to fix any issues for v6 any more. We will, however, merge any non-breaking pull requests submitted to fix anything in v6.

# Using v7?

Thanks for using the alpha version of React Table v7! We're very excited about it.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Codesandbox!**
Use a new [react-table codesandbox](https://codesandbox.io/s/m5lxzzpz69) to reproduce the issue.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tannerlinsley** [comment]
I don't see any details for this issue, and my guess is that it is for v6, not the v7. I suggest that you ask this question in https://spectrum.chat/react-table. Thanks!

**Comment by corby** [comment]
I'm an idiot and I wanted the world to know it.
Had a hidden css file that was screwing up the table.
