### ISSUE TITLE
Feature Request: Multiple filter rows [v7]

### ISSUE THREAD

**Issue by mattgabor** [tannerlinsley/react-table#1465]
This is related to #981 - there's no way to filter multiple columns using a single input.

For example, if I wanted one search input to filter on all of the columns in a table - this isn't possible, and it seems like a useful feature to have.

**Comment by tannerlinsley** [comment]
Thanks to React Table being headless and the ease of hooks, this is easy to accomplish without any extra help from React Table: https://codesandbox.io/s/tannerlinsleyreact-table-basic-ml77r

**Comment by tannerlinsley** [comment]
There is another side to this question though, and it is that of being able to filter on a column using values outside of the accessed cell model. eg. If you wanted to filter using one value, but sort using another, we would need to add some more API to the sortType option to handle this use case.

But, if the above use case is enough, then I'd rather not go down this other route unless we have to.

**Comment by mattgabor** [comment]
@tannerlinsley thanks for that - the useMemo solution works perfectly for my needs!
