### ISSUE TITLE
What's changed in v7?

### ISSUE THREAD

**Issue by cristianocca** [tannerlinsley/react-table#1466]
I'm wondering what was changed?

Also, are you planning on supporting classes after version 7 or will hooks be the only way to use the library?

**Comment by tannerlinsley** [comment]
Hooks will be the only way to consume the library. Though to be fair, 99% of users will create their own "MyTable" component that utilizes the hooks, rather than use them directly. Even all of the examples do this.

**Comment by cristianocca** [comment]
Thanks, hopefully we can get a small migration guide. Looking at the docs it seems like the migration will be tough!

**Comment by tannerlinsley** [comment]
Yeah, honestly I'm not sure if the migration guide would be that big, other than a few high-level conceptual connections and links out to example/API. V7 is basically a brand new library.

**Comment by valentyna-refundit** [comment]
@tannerlinsley Great work with the table v7!
However, you can return the links to the old documentation to a ReadMe? While version 7 in alpha (not stable for prod) it would be nice to still see them

**Comment by wedi** [comment]
Hi @tannerlinsley, it would be cool, if you could add a note for new users.
What is the state of v7 apart from the version saying alpha? Should new users use v6? Are there any hints on how to use v6 to ease a later migration?

**Comment by tannerlinsley** [comment]
This is a great idea. Where would you expect that to live? In the Readme? Where in the Readme?

Tanner Linsley

**Comment by dalvallana** [comment]
Hi! One question: in version 6 it was possible to set a default sorting for a table, but I don't seem to be able to do that in version 7. Is this not yet implemented or I'm just missing something?

Thanks!

**Comment by tannerlinsley** [comment]
https://github.com/tannerlinsley/react-table/issues/1456

**Comment by valentyna-refundit** [comment]
@tannerlinsley Hi. What did you decide to do with this task? I see that the task is closed, but there is no documentation about version 6 ( and there is no information when there will be a stable v7)  in the Readme

Thanks

**Comment by tannerlinsley** [comment]
I've created a new small section to start guiding people in the right direction:

https://github.com/tannerlinsley/react-table/blob/master/README.md#news--qa

**Comment by wedi** [comment]
Thanks a lot for the update! 👍 Now it's clear what's going to happen and I am happy I asked!
You chose the exact same place I would have suggested.
