### ISSUE TITLE
semantic-release and conventional-changelog

### ISSUE THREAD

**Issue by larrybotha** [tannerlinsley/react-table#1467]
related to #1383 

There have been a number of changes to semantic release since I last added it to a project, and there seem to be some caveats when adding it to an existing project.

Some things to iron out:

- installing `conventional-changelog` separately doesn't seem to be necessary, as `semantic-release` uses [release-notes-generator](https://github.com/semantic-release/release-notes-generator#release-notes-generator) which in turn uses `conventional-changelog` to generate changelogs
- the most recent commit must be included in the last published release before adding `semantic-release`: https://github.com/semantic-release/semantic-release/blob/master/docs/01-usage/configuration.md#existing-version-tags-and-how-semantic-release-deals-with-them
- work on v7-alpha _may_ need to be moved to an alpha branch in order to separate semantic versioning for the alpha and v6
- can the generated changelog continue on from the current changelog?

I'll fiddle around locally to see what I can find in the next few days. The last thing I want to do is introduce some weird history by not having evaluated the impact properly!

Additionally, @tannerlinsley you may have to run the install of `semantic-release` yourself, as I recall it requesting npm credentials which external contributors don't have privileges to provide.

**Comment by tannerlinsley** [comment]
Still would love this, but seems a ways off still. Closing for now.
