### ISSUE TITLE
Kitchen-sink row select is broken

### ISSUE THREAD

**Issue by riongull** [tannerlinsley/react-table#1470]
**Describe the bug**
Selecting 1 row in kitchen-sink example incorrectly selects many rows

**To Reproduce**
1. Go to [`kitchen-sink` code sandbox](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/kitchen-sink)
2. Click on `<<` to go to page 1.
3. Select row 1 (not row 0, that works fine).
4. See how it selects multiple rows instead of 1 row.

**Expected behavior**
It should only select rows that you explicitly select.

**Comment by riongull** [comment]
Same issue exists in [`kitchen-sink-controlled`](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/kitchen-sink-controlled) example

**Comment by tannerlinsley** [comment]
I'll look into it asap

**Comment by tannerlinsley** [comment]
This if fixed in the latest version
