### ISSUE TITLE
Nested header doesn't work

### ISSUE THREAD

**Issue by berik** [tannerlinsley/react-table#1472]
# Using v7?
7.0.0-alpha.25

**Describe the bug**
I've tried to add extra nested header to [basic example](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/basic) but it still breaks.

**To Reproduce**
```
function App() {
  const columns = React.useMemo(
    () => [
      {
        Header: "Extra Top Header",
        columns: [
          {
            Header: "Name",
            columns: [
              {
                Header: "First Name",
                accessor: "firstName"
              },
              {
                Header: "Last Name",
                accessor: "lastName"
              }
            ]
          },
          {
            Header: "Info",
            columns: [
              {
                Header: "Age",
                accessor: "age"
              },
              {
                Header: "Visits",
                accessor: "visits"
              },
              {
                Header: "Status",
                accessor: "status"
              },
              {
                Header: "Profile Progress",
                accessor: "progress"
              }
            ]
          }
        ]
      }
    ],
    []
  );

  const data = React.useMemo(() => makeData(20), []);

  return (
    <Styles>
      <Table columns={columns} data={data} />
    </Styles>
  );
}

export default App;
```

**Expected behavior**
Extra Top Header should have `colspan=4` not `colspan=0`

**Codesandbox!**
Use a new [react-table codesandbox](https://codesandbox.io/s/tannerlinsleyreact-table-basic-vsp7f) to reproduce the issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/1040210/63474223-afddfc00-c4bb-11e9-99df-d2592ffdfd3f.png)

![image](https://user-images.githubusercontent.com/1040210/63474260-da2fb980-c4bb-11e9-973c-d7d23c10122d.png)

**Comment by tannerlinsley** [comment]
This is fixed in the latest version :)
