### ISSUE TITLE
the number of rows remains the same as selected if you press row in v-7 with pagination

### ISSUE THREAD

**Issue by saneq1** [tannerlinsley/react-table#1473]
the number of rows remains the same as selected if you press row in v-7, but should increase

https://codesandbox.io/s/tannerlinsleyreact-table-expanding-bs3bu
should be
![need](https://user-images.githubusercontent.com/20462876/63501335-1ec74f00-c4d4-11e9-9711-82ddcf680ab4.PNG)
in fact
![inFact](https://user-images.githubusercontent.com/20462876/63501395-33a3e280-c4d4-11e9-9843-bed3a4e0ae98.PNG)

**Comment by tannerlinsley** [comment]
Please see the `paginateExpandedRows: Bool` option here: https://github.com/tannerlinsley/react-table/blob/master/docs/api.md#table-options-5
