### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by ztorstri** [tannerlinsley/react-table#1484]
Import fails with the following error
114:30-40 "export 'default' (imported as 'ReactTable') was not found in 'react-table'

This is how I'm importing:
import ReactTable from 'react-table';

and to install I ran:
npm install --save react-table@next

**Comment by ztorstri** [comment]
Apparently everything is drastically different in this version and I was looking at old examples. Do I really have to do it all manually now?  Are you sure that's better?

**Comment by tannerlinsley** [comment]
The new headless API may not feel as friendly out of the box, but I can assure you that after the initial learning curve of setting up your own table markup is over, you will be better equipped to build a table that functions, looks and feels exactly the way you want it to, with little to no restriction whatsoever. I would suggest looking through some of the examples. Fork them in codesandbox and play around! I think you'll be surprised at questions like: "How do I do an onClick for this row?" or "What if I want to use this UI/Style library?" or even "How can I move pagination to the top of the table, or even outside of the table?!" and how with the new headless API, they are all not only possible, but 100% customizable.

**Comment by mhsunny** [comment]
Solved the problem!!!

You have to install

npm install react-table-6

and then import 
```
import React, {Component} from 'react';

import ReactTable from 'react-table-6';

import 'react-table-6/react-table.css';

```

its solved:)
Reference   https://www.npmjs.com/package/react-table-6
