### ISSUE TITLE
how to open everything expanded at the start of the page in v7?

### ISSUE THREAD

**Issue by saneq1** [tannerlinsley/react-table#1485]
https://codesandbox.io/s/tannerlinsleyreact-table-expanding-39kd7
now
![image](https://user-images.githubusercontent.com/20462876/63929576-572dd680-ca5a-11e9-945b-09e777cddac3.png)
need to at start
![image](https://user-images.githubusercontent.com/20462876/63929660-7f1d3a00-ca5a-11e9-8ed2-9819a36000e0.png)

I've tried  then the switches do not work 
Uncaught TypeError: setState is not a function
````
  let expanded = React.useMemo(() =>[{"0":false, "1": true}], [data]);



  const {getTableProps, headerGroups, rows, prepareRow} = useTable(
      {
        columns: userColumns,
        data,
        subRowsKey: "matchings",
      state: [{expanded}],
      },
      useExpanded
  );
````

**Comment by tannerlinsley** [comment]
https://codesandbox.io/s/tannerlinsleyreact-table-expanding-o3rkm
