### ISSUE TITLE
useSortBy not working for numbers between 0-1

### ISSUE THREAD

**Issue by brianqian** [tannerlinsley/react-table#1486]
# Using v7?
Currently using   "react-table": "^7.0.0-alpha.15",

**Describe the bug**
useSortBy not working correctly for values between 0 and 1.

**To Reproduce**

You can use the example codesandbox: https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/sorting

and remove one of the `Math.floor`s

``` Javascript
const newPerson = () => {
  const statusChance = Math.random()
  return {
    firstName: namor.generate({ words: 1, numbers: 0 }),
    lastName: namor.generate({ words: 1, numbers: 0 }),
    age: Math.random() * 1,
    visits: Math.floor(Math.random() * 100),
    progress: Math.floor(Math.random() * 100),
    status:
      statusChance > 0.66
        ? 'relationship'
        : statusChance > 0.33
        ? 'complicated'
        : 'single',
  }
}
```

**Screenshots**

![image](https://user-images.githubusercontent.com/28659460/63988274-84ee3c00-caa9-11e9-982d-ac66e4a7a5b0.png)

**Comment by brianqian** [comment]
It looks like this is only an issue with the 'alphanumeric' sorting. I didn't see in the docs that you have to label your column with either 'basic', 'datetime', or 'alphanumeric'. Can I make a change to the docs noting that?

**Comment by tannerlinsley** [comment]
Please do! In fact, there needs to be a lot of work done on the specific options available for each of these hook plugins. Write as much as you'd like to make things clearer!
