### ISSUE TITLE
Please rename componentWillMount and componentWillReceiveProps to remove console warnings.

### ISSUE THREAD

**Issue by constantinpojoga** [tannerlinsley/react-table#1487]
First of all, thanks for the great tool. I'm using it for the 2nd project now, an I really love it!
On my last project, build with create-react-app, I'm getting these console warnings, which are pretty annoying:

```
Warning: componentWillMount has been renamed, and is not recommended for use. 
See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. 
To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder
.....

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps.
 Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. 
To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: ReactTable, ReactTablePagination
```
Now it's just adding the noise, and it's still fine but as of 17.x, this could break our apps. 
Hope that you can fix that any time soon.

Thank you!

**Comment by zhangyuliangzyl** [comment]
same problem

**Comment by tannerlinsley** [comment]
v7 does not have these warnings and has been rewritten to use hooks, etc. Please start upgrading when you can. v6 will be considered deprecated very soon.

**Comment by constantinpojoga** [comment]
You close it, wow. The issue still persists! The last stable version on npm is 6.10.0. In order to fix it, you suggest to update it to 7.0.0-alpha.33?

**Comment by tannerlinsley** [comment]
Sorry to disappoint, but it has been publicly known for quite a while (and in previous issues) that I won't be maintaining v6 any more. Unfortunately, I don't have time to guarantee that v6 will work on all future versions of React.

The best recommendation I can give you is to fork or clone the project locally and maintain your own fixes/upgrades for future compatibility. (Many companies who use v6 still are doing this until they are ready to upgrade to v7)

As for v7, I realize it is still in alpha and that it's a big ask to upgrade now. It will be in beta very soon and hopefully by then you'll feel more comfortable about upgrading.

**Comment by tannerlinsley** [comment]
As for the changes to be made in a fork for v6 to work in the latest version of React, you could start here: https://github.com/tannerlinsley/react-table/pull/1461/files, though I can't promise that those are the only changes required to ensure it will continue to work beyond that version.

**Comment by constantinpojoga** [comment]
Thank you
