### ISSUE TITLE
No mention of release 6.10.0

### ISSUE THREAD

**Issue by croraf** [tannerlinsley/react-table#1488]
In the list of releases https://github.com/tannerlinsley/react-table/releases there is no 6.10.0 release.

Also in the list of tags there is no 6.10.0 tag (the latest one)

**Comment by tannerlinsley** [comment]
Tagged and released. Thanks!

**Comment by tnrich** [comment]
@tannerlinsley just a heads up that I didn't see a changelog for v6.10

**Comment by tannerlinsley** [comment]
I'll try and get it updated soon. It was nothing big, just a maintenance release.
