### ISSUE TITLE
Cell renderer does not default to render cell value function

### ISSUE THREAD

**Issue by AlpacaGoesCrazy** [tannerlinsley/react-table#1490]
**Describe the bug**
Cell function does not default to `({ cell: { value } }) => value` as it renders 'null' as a string when omitted and provided null value for said cell
From [docs](https://github.com/tannerlinsley/react-table/blob/master/docs/api.md#usetable):
> Cell: Function | React.Component => JSX
> Optional
> Defaults to ({ cell: { value } }) => value
> Receives the table instance and cell model as props
> Must return valid JSX
> This function (or component) is primarily used for formatting the column value, eg. If your column accessor returns a date object, you can use a Cell function to format that date to a readable format.

**To Reproduce** 
[code sandbox](https://codesandbox.io/s/fervent-hodgkin-koygv)

**Expected behavior**
Both cells on second row should render nothing

**Desktop (please complete the following information):**
 - Version [7.0.0-alpha.33]

**Comment by tannerlinsley** [comment]
Looks like the docs were out of date. The default `Cell` renderer is actually:
```js
Cell: ({ cell: { value } }) => String(value)
```

The docs have been updated to reflect this. Thanks!

**Comment by cjinfantino** [comment]
This produces null values in the fields when you use `useExpand`. What's the best way to avoid this and have it produce an empty string for the expanded fields? 

![CleanShot 2019-09-03 at 20 56 33](https://user-images.githubusercontent.com/3409857/64217914-55667780-ce8d-11e9-830d-d6a0fa7f3a2b.png)
