### ISSUE TITLE
Drag and drop in rows from a specific cell

### ISSUE THREAD

**Issue by CarlosOrozc** [tannerlinsley/react-table#1491]
https://codesandbox.io/s/react-table-simple-table-wj8of
there is a way to pass the dragHandleProps to a specific cell? 

<img width="1435" alt="Screen Shot 2019-09-02 at 10 36 22 AM" src="https://user-images.githubusercontent.com/8071575/64127306-45a44180-cd6e-11e9-9b68-ed55f39a01e3.png">

**Comment by tannerlinsley** [comment]
In v6, no. In v7 you will be able to control that 100%.

**Comment by richardhsueh** [comment]
@tannerlinsley can you explain a little bit more on how to do it ?
