### ISSUE TITLE
can use this lib for react native?

### ISSUE THREAD

**Issue by iamir4g** [tannerlinsley/react-table#1492]
hi 
can i use this lib for react native app?
and work fine in android and ios?

**Comment by tannerlinsley** [comment]
To the best of my knowledge, yes. You should be able to use React Table in React Native.

**Comment by netalex** [comment]
how to fix https://github.com/tannerlinsley/react-table/discussions/2144???

**Comment by cengit** [comment]
react-native table, I'm going to use this one: https://github.com/meliorence/react-native-render-html
