### ISSUE TITLE
Missing hook order error for `useSortBy` with `useExpanded`

### ISSUE THREAD

**Issue by AlpacaGoesCrazy** [tannerlinsley/react-table#1493]
When you place `useSortBy` after `useExpanded` in `useTable` hook sorting with expanded rows happens to detach nested rows from their parents.
This should have similar error as 

> The useSortBy plugin hook must be placed after the useFilters plugin hook!

[codesandbox](https://codesandbox.io/s/cranky-sunset-71mfg)

**Desktop (please complete the following information):**
 - Version [7.0.0-alpha.33]

**Comment by tannerlinsley** [comment]
Your example doesn't illustrate any issues I'm aware of. Let me know if I'm missing something? Did you hit save on your example?

**Comment by AlpacaGoesCrazy** [comment]
Try this:
1. group by `foo` column
2. expand both grouped rows
3. sort by `bar` column

Rows will be sorted without any grouping

**Comment by tannerlinsley** [comment]
I think I see now. I'll work up a fix for this soon.

**Comment by tannerlinsley** [comment]
This should be fixed in the latest version. You will now be warned to place `useGroupBy` before `useSortBy`
