### ISSUE TITLE
Add the ability to have grouped rows expanded by default

### ISSUE THREAD

**Issue by dtfraighter** [tannerlinsley/react-table#1494]

**Comment by sgehrig** [comment]
We also wanted to use a grouped table but without the expand/collapse behaviour of subrows. Instead we just want to display all subrows always without any UI to toggle the expanded state.

Perhaps there's an easy solution to this but I couldn't figure out how to do it.

**Comment by tannerlinsley** [comment]
I'm working up an idea to support an `expanded: true` state that will expand everything all the time. Stay tuned.

**Comment by tannerlinsley** [comment]
My suggestion at this point would be to place the `expanded: true` property on every row in your data set. This will force every row to be expanded.

**Comment by bmamouri** [comment]
Hey @tannerlinsley,

Thank you for the great work, and sorry for commenting on a closed issue.

Setting `expanded: true` works but it comes with the cost that the row can't be collapsed anymore. Do you know of a solution to allow the rows to be collapsed?

**Comment by sapristi** [comment]
Hello, 
I am struggling on a similar issue. 
It seems that we can use `initialState.expanded` to choose which rows are expanded at startup, but for some reason this does not seem to affect group rows.

For example, passing `expanded: {"grouped:myGroup": true}`, where `"grouped:myGroup"` is the Id of my grouping row, does not seem to work. Am i missing something here ?
