### ISSUE TITLE
Wrong results of sorting when used with multiple filtered columns

### ISSUE THREAD

**Issue by paolostyle** [tannerlinsley/react-table#1497]
**Describe the bug**
Sorting results are wrong when using it when multiple columns are filtered. It might be related to specific data structure, but I'm not sure.

**To Reproduce**
I tried reproducing it with automatically generated data like in CodeSandbox examples from this repo but I couldn't, so I prepared a sandbox with almost identical table logic-wise that I'm using in my app and with dataset on which this bug occurs. So please use the sandbox here: https://codesandbox.io/s/bug-wrong-sorting-with-filters-and-pagination-20012 and:

filter F3 0.8 to (empty)
filter F4 0.2 to (empty)
filter F5 (empty) to 0.3
sort by F2 (click on the column label)

Look at the results: it is sorted up to "aromatic", then the next row is "parfum" which has lower F2 value than "aromatic". Same thing occurs a bit later for "aroma" (0.53) and "saffron" (0.29). 

I thought it's related to pagination, but I commented out pagination-related code in the sandbox and the bug still occurs, so it seems like it's not related (though it kind of seems like it is). It might be related to the fact that last two columns are nested in the object (see makeData and accessors in the columns), but it's hard to tell.

**Expected behavior**
The rows should be sorted properly.

**Comment by tannerlinsley** [comment]
Bug found. Working on a fix now.

**Comment by tannerlinsley** [comment]
Just released a new version. You'll see in your codesandbox (after the cache is updated and you get the latest version... curse you @next) that `numeric` is actually not a valid `sortType`. It may have been at one time though...  I've added a check to error for invalid sortTypes. What you'll want to do is use `sortType: 'basic'`, which covers numeric sorting:
```js
// src/utils/sortTypes.js

export function basic(rowA, rowB, columnID) {
  let a = getRowValueByColumnID(rowA, columnID)
  let b = getRowValueByColumnID(rowB, columnID)

  return compareBasic(a, b)
}

function getRowValueByColumnID(row, columnID) {
  return row.values[columnID]
}

function compareBasic(a, b) {
  return a === b ? 0 : a > b ? 1 : -1
}
```

**Comment by paolostyle** [comment]
Ahh... alright. Yeah, `numeric` definitely was valid sortType at some point, I must've missed that change. It does work with `basic`, thanks a lot.
