### ISSUE TITLE
Show / hide columns dynamically

### ISSUE THREAD

**Issue by eyerean** [tannerlinsley/react-table#150]
I am trying to do this with checkboxes: a function in `ReactTable`'s parent component handles the booleans, and when these change, the component with ReactTable rerenders with the correct updated booleans. But the columns seem to keep their initial state, shown or hidden, no change despite the correctly sent booleans.

In my columns definition I have `show: this.props.columnName` . 

On the contrary, when I change some column's header in the same way [`header: () => <span>{this.props.selectedYear}</span>`], it is changed correctly. The only difference is that with this change there is also a change of the data. However, even when I change this header + data this way, shown columns are still not refreshed.

How can I do this?

**Comment by tannerlinsley** [comment]
It seems you may have discovered a bug...  I would suggest trying to use [the changes from this PR](https://github.com/tannerlinsley/react-table/pull/166) to see if it fixes the problem, or just wait until we can get that PR merged (or the issue it's linked to resolved).  Then we can have a better idea if it is in fact a bug or simply an implementation error.  Either way If you could, please, post your component code so we can get a better idea of how you are attempting to achieve this. :)

**Comment by tannerlinsley** [comment]
Please run `yarn/npm upgrade react-table`, verify you are using the latest version and let me know if you are still seeing this bug.  If so, please reopen issue :)

**Comment by eyerean** [comment]
Bug still there on `react-table@5.5.0`, but thanks a lot for your work on this!

**Comment by gnain** [comment]
Hi, I kind of run into the same issue.
Basically, I generate a list of checkboxes atop the table to allow users to show/hide columns.
For this, I store the columns setting in the state of my react component, and link <ReactTable columns={this.state.columns} .../>
One of the column has a function for a specific rendering (here a select/option list). On the first component.render() everything goes as planned (ReactTable is awesome by the way !). However, when they change the visibility of **any** column to 'hide', the select html component generated by the column.render function is transformed to a simple text content in the `<div rt-td>`.
I made a Gist to show the configuration [here](https://gist.github.com/gnain/1b330921cc8c7d1816dfd6c6906ac009).

It seems to me that when the columns configuration is updated, the table does not call the column.render(), but rather copies the values of the contents of the cells.

This is a clear bug I guess, and could be very worth solving!

**Comment by gnain** [comment]
OK, so, for information and records, the bug was on me. I used a very nasty way to update the columns description object, that used to remove the rendering methods ! Therefore, no bugs from my part. Very sorry for the disturbance ! Ans thank you again for this awesome table ! 💯

**Comment by tannerlinsley** [comment]
:) Great to hear! And thanks!

**Comment by jeghers** [comment]
Show hide is still not working for me.  I am simply changing the show flags in the columns array and re-rendering.  Am I missing something?

**Comment by tannerlinsley** [comment]
Please post your code

**Comment by Si1kIfY** [comment]
Yep i'm having the same issue in `"react-table": "6.4.0",`

I've got a checkbox show hide thing similar to the above comments, when a user clicks on one of the boxes an `action` is sent that changes the state, the new state includes the columns array with `show: false` and `width: 0` on the particular array object.

Seems to be passing ok, am logging the new state in `mapStateToProps` and in the `render()` method.

**Comment by Si1kIfY** [comment]
Just updated to `"react-table": "^6.5.1",` and still have the same issue

**Comment by lukashambsch** [comment]
I'm seeing this issue with react-table@6.5.3. The state is updating, but the table doesn't seem to be re-rendering. Previously I was using an object that I would transform into an array in mapStateToProps. I just changed that to be an array initially to try and improve performance on the toggling and that seems to have broken it.

**Comment by DhanaTontanahal** [comment]
Hi 

Here is the working example of hiding/showing the columns dynamically with react table imple..

https://github.com/DhanaTontanahal/TdsReactTable


Thank you.
