### ISSUE TITLE
Invalid Pagination prop warning- renders fine 

### ISSUE THREAD

**Issue by ankitkadali** [tannerlinsley/react-table#1501]
I am using version 6.8 and i recently upgraded my material-ui version to V4. I see this warning :
Failed prop type: Invalid prop PaginationComponent supplied to ReactTable.

However, it renders well. Any idea of how to get rid of this warning message.

**Comment by tannerlinsley** [comment]
You can edit the prop-types locally like so:
```js
import ReactTable from 'react-table'
React.Table.propTypes.PaginationComponent = PropTypes.whateverPropTypeYouWant
```

This should suffice for now. v6 is not being actively maintained (we are working on v7). So this is low priority for the time being.

**Comment by shawnpetros** [comment]
In case anyone finds this for the same reason I did, @tannerlinsley's comment DOES remove the message, HOWEVER, there's a typo, which may or may not be instantly apparent:

```
- React.Table.propTypes.PaginationComponent = PropTypes.whateverPropTypeYouWant
+ ReactTable.propTypes.PaginationComponent = PropTypes.whateverPropTypeYouWant
```
