### ISSUE TITLE
JSX cell is unexpected render to '[Object Object]' in v7.

### ISSUE THREAD

**Issue by elivoa** [tannerlinsley/react-table#1505]
JSX cell is render to '[Object Object]' 

Affected version: 7.0.0-alpha.32 - 7.0.0-alpha.34

![image](https://user-images.githubusercontent.com/958954/64486519-c4aee380-d260-11e9-97a5-080bd7cb3f03.png)

**Comment by Codar97** [comment]
You can achieve the same with
`
columns: [
{
Header: 'First Name',
Cell: ({cell}) => <div>cell.value.firstName</div>
accessor: 'firstName'
}]`

This **may** be its intentional functionality to combat cross site scripting.

**Comment by tannerlinsley** [comment]
This is fixed in the latest release. All renderers now support Function components, Class components, non-component functions, JSX elements, and primitives.

**Comment by tannerlinsley** [comment]
Also,@elivoa, Its important to note that `accessor` is meant to resolve a primitive data type (number, string, boolean, etc), so that it can be used to sort and filter the table. If you want to customize it's display, please do the following: 
```js
{
  accessor: row => row.firstName,
  Cell: ({ cell: { value }}) => <div>{value}<div>`
}
```
