### ISSUE TITLE
Version 6.10.1 backward compatible

### ISSUE THREAD

**Issue by 4xemme** [tannerlinsley/react-table#1507]
Anyone tried ver 6.10.1?

Having this silly colum definition
{
Header: "Pick",
accessor: "name",
Cell: (r: any) => "hello"
}

I'm getting

TypeError: Cannot read property 'isReactComponent' of undefined
isClassComponent
C:/tfs/repos/ecod/app/node_modules/react-table/es/utils.js:263
260 | }
261 |
262 | function isClassComponent(component) {
263 | return !!(typeof component === 'function' && !!component.prototype.isReactComponent);
264 | }
265 |
266 | function isFunctionComponent(component) {

Works fine with ver 6.10.0

**Comment by tannerlinsley** [comment]
This is fixed in the latest release. Please upgrade and sorry!
