### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ivan-kaminskyi** [tannerlinsley/react-table#1514]
**Describe the bug**
After the table gets destroyed from react tree and the DOM, JS engine still keeps references to destroyed dom elements. If the table gets destroyed very often memory usage of tab grows really quickly. 

**To Reproduce**
1. Create simple table
2. Mount / Unmount it many time
3. Observe increased memory usage

**Expected behavior**
No memory leaks. All references to elements are garbage collected

**Codesandbox!**
```
import React, { useState } from 'react';
import Table from "react-table"
const rows = [];

for(let i = 0; i<1000; i++) {
  rows.push({
    data: i
  });
}

const columns = [{
  resizable: false,
  sortable: false,
  accessor: 'data',
  Header: 'Data'
}];

export default function TestPage() {
  const [showTable, setShowTable] = useState(true);
  return <>
    <button onClick={()=> setShowTable(value=>!value)}>Show / Hide</button>
    
    {showTable && <Table columns={columns} data={rows} manual />}
  </>
}
```
**Screenshots**
After first render
![screen1](https://user-images.githubusercontent.com/43336354/64804472-8c2c4400-d597-11e9-86fc-657a733b2e21.png)

After pressing many time Show / Hide button
![screen2](https://user-images.githubusercontent.com/43336354/64804473-8c2c4400-d597-11e9-9072-f2f9d003a1a6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome Version 76.0.3809.132
 - Version react-table@^6.10.0
.

**Comment by tannerlinsley** [comment]
Closing this, since we are only actively tracking bugs and issues in Github for v7. If you find the issue and would like submit a PR to fix it, it will still be accepted and merged. Thanks!
