### ISSUE TITLE
paginateExpandedRows not working with deep rows

### ISSUE THREAD

**Issue by jeshio** [tannerlinsley/react-table#1516]
When I'm using `paginateExpandedRows` param and set it to `false' I've got this:
![image](https://user-images.githubusercontent.com/1515657/64840628-d8fa3400-d604-11e9-9760-8f1a98abde8c.png)

I'ts two levels grouping, but original is three levels:
![image](https://user-images.githubusercontent.com/1515657/64840669-f7f8c600-d604-11e9-907a-eb98a0a81f70.png)

So, the third level is gone

And this is CodeSandBox example:
https://codesandbox.io/s/tannerlinsleyreact-table-expanding-hz7in

**Comment by tannerlinsley** [comment]
Yeah, this looks like a bug. I'll look into it

**Comment by tannerlinsley** [comment]
This is fixed in the latest alpha release. Thanks for your help!
