### ISSUE TITLE
Strange background behavior while data loading

### ISSUE THREAD

**Issue by garkey** [tannerlinsley/react-table#1518]
Hi,

Could someone have a quick look at this video, and verify whether this is a bug or a missed setting, please? Basically, while data is loading and the loading component (anything during `onFetchData`) is running, the background table reverts to what seems like the data set that was loaded the first time. Can I just make the background show something else? Thanks for any tips.

![output](https://user-images.githubusercontent.com/46828616/64887191-e6231d00-d61c-11e9-9467-d8dc7c4cd432.gif)

# Using v6?

v6 is now considered feature complete to its current abilities and limitations. We are not actively working to fix any issues for v6 any more. We will, however, merge any non-breaking pull requests submitted to fix anything in v6.

# Using v7?

Thanks for using the beta version of React Table v7! We're very excited about it.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Codesandbox!**
Use a new [react-table codesandbox](https://codesandbox.io/s/m5lxzzpz69) to reproduce the issue.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tannerlinsley** [comment]
Hi there! Thanks for using React Table!

V6 is currently not being actively maintained and it is recommended you upgrade to v7. If you plan to keep using v6 and still need support, it's recommended that you ask this support question in the Spectrum chat/forum: https://spectrum.chat/react-table

Thanks!
