### ISSUE TITLE
I am pissed off #rant #twitter #unconstructive

### ISSUE THREAD

**Issue by wkrueger** [tannerlinsley/react-table#1519]
I've been looking for a decent datatable lib for some time and all of the just seemed to suck in some way.

Then I tried this one and at start it seemed okay.

Now I'm just pissed off because I already have considerable UIs running over this, and this library just throws me random javascript errors everytime when I add something a bit different...

Then when I inspect the code it is just littered with 300-liner functions. I look for tests and they are scarce or nonexistant. WTF was i thinking when I chose this?

Then in the main page says you are rewriting the whole thing with hooks and: guess what - commiting the same mistakes all over again. No tests, not even typescript. Giant functions everywhere.

Next time you write a pile of untested code, at least keep it for yourself. The world is a better place with less untested untyped code.

<proceeds to fork the library, puts in diving mask preparing to dive in the pile of ~sh~ 300-liners functions>

sorry for childness

**Comment by tannerlinsley** [comment]
Hi! Welcome to github where people like me write code to help people like you for free!

I'm not going to take too much of my time to respond to this blatantly disrespectful issue, but I will leave a few thoughts here for @wkrueger and other posterity who see this issue:

If anyone ever has an issue with any open source library whether it's a bug, feature request, etc, then let this issue be an example of what not to do. I would encourage anyone in this situation to lead with kindness, patience, and information on how to better the situation. Specifically, I would have loved to receive an issue with:

- A pasted link to a codesandbox demonstrating a reproducible bug with the library
- A discussion about a potential PR to add a feature or functionality
- A question to clarify if any of this users concerns had already been (or are planned to be) addressed elsewhere

On a more technical note:
- Typescript is planned for this library. Also remember, Typescript results in better code, but better code does not exclusively require Typescript.
- There is nothing wrong with giant functions. Every React application is effectively a giant function.
- Integration tests are also planned. For now, snapshot tests are sufficient as the library has rapidly changed and evolved.

I'm really sorry and also disappointed that you ultimately feel this way. React Table is and has been a great library that helps great developers and well-known companies all over the world every day. I hope you change your mind! I'll gladly welcome you back to the library with open arms if/when you're willing.

PS - @wkrueger, I spent at least 2 years in Florianopolis Brazil, living as a near-native, having fully adopted the lifestyle, language, and people into my heart. It makes me very sad to have received a comment like this from a place and people I hold very dear to my heart. I hope our future conversations (if applicable) are on better terms.
