### ISSUE TITLE
[QUESTION] Expand row by ID 

### ISSUE THREAD

**Issue by erzzo** [tannerlinsley/react-table#152]
Hello,
is there a simple way to expand a row (subComponent) by specific data ID (id from the database)?
My theoretical (but complex) solution now is to calculate the page number first, where the item should be and set the page number manually and then set `expandedRows` property with the item index.

A better way would be to check `dataItem.id == row.data.id` and pass a property `expanded = true`

Thanks for any help on this

**Comment by tannerlinsley** [comment]
You could simulate this via the controlled `expandedRows` prop.  You would need to search for the index or key of the row you want expanded, then pass it into that model.

**Comment by erzzo** [comment]
Yes, that is what I thought. But I need to first find the page number, set it with `page={number}` then find the `viewIndex` of the item and set it as `expandedRows={{<viewIndex>: true}}` right?

**what I tried to simplify the process**
I've tried to find the index of the row item, set it as `expandedRows={{<itemIndex>: true}}` and hard coded the page number `page={<pageNumberOfItem>}`, but it wasn't working. Expanded rows working only with `viewIndexes` or am I doing something wrong?

**Comment by tannerlinsley** [comment]
yes, expanded rows works with the `viewIndex`, (which is relative to the current page) and not with the original data model's index.  You're on the right track though.  You may need access to the internal sorted data model to accurately locate the item's page and `viewIndex`.  I would suggest utilizing a react `ref` or [Functional Rendering](https://github.com/tannerlinsley/react-table#functional-rendering) to get the internal data model.  Then you will have an accurate representation of the data model for your logic.  This is extremely advanced functionality, and though possible, is going to be difficult.  If you would like to discuss implementation further, you could seek help on the [react-table slack organization](https://react-chat-signup.herokuapp.com/) :)

**Comment by erzzo** [comment]
Yep, I've got it already working. Thanks for help.

**Comment by tannerlinsley** [comment]
👍

**Comment by dowi** [comment]
@erzzo  How?
How can I get the row index in "functional rendering"?

thanks a lot

**Comment by erzzo** [comment]
@dowi This is how I do it (it's written in coffee jsx):

You need to go through all pages and find the actual page with the item index on that page by comparing url ID with actual item ID.

I'm using it with this routes:
/localhost/users - do not expand 
/localhost/users/15 - expand row with item id 15 

My react table component:
``` cjsx
<ReactTable
  data={items.toList().toArray()}
  columns={columns}
  page={pageIndex}
  expandedRows={{"#{selectedIndex}": true}}
  getTableProps={(state) =>
    if @props.SubComponent and @getUrlId()
      page = 0

      state.resolvedData.map (row, index) =>
        # count pages by index
        if index isnt 0 and index % state.pageSize is 0
          page++

        # find page on which the item is
        if pageIndex is undefined and row.id is @getUrlId()
          @handlePageChange page
          @props.onSelect @props.items.get "#{@getUrlId()}"

    if selectedIndex? and selected is null
      @handleCloseRow() # setState {selectedIndex: null}

    # set last page, when filtering items
    if state.page isnt 0 and  state.page + 1 > state.pages
      page = if state.pages then state.pages-1 else 0
      @handlePageChange page

    return {}
  }
  getTrProps={(state, rowInfo) =>
    if rowInfo
      {viewIndex: index, row} = rowInfo

      # find index of item in actual table view
      if selected and pageIndex isnt undefined and row.id is selected.id and selectedIndex isnt index
        @handleSelect index, row

    return {}
  }
  getTdProps={(state, rowInfo, column) =>
    # disable click on empty row
    unless rowInfo then return {}

    onClick: (event) =>
      if event?.isDefaultPrevented?()
        return
      event.preventDefault?()
      {viewIndex: index, row} = rowInfo

      # show subcomponent
      if @props.SubComponent and not column.selectable
        @handleSelect index, row
  }
  onPageChange={(pageIndex) =>
    @handleCloseRow() # when item is not on actual page
    @handlePageChange pageIndex # setState {pageIndex}
  }
  SubComponent={@props.SubComponent}
/>
```

**Comment by erzzo** [comment]
@dowi yes. Just find the page and the item index on that page

**Comment by dowi** [comment]
@erzzo thanks

**Comment by hatim85f** [comment]
@tannerlinsley I am struggoling in that issue since couple of days, nothing at all is helping and the examples on Doc are not clear. May be because I am not familiar with react-table that's why... for example I don't know how to implement that and where shall I add the code for expansion 
I will be grateful if you can give me a hand on that https://stackoverflow.com/questions/71538116/implementing-react-table-expanded-rows
