### ISSUE TITLE
React development warning for componentWillMount 

### ISSUE THREAD

**Issue by alexandrudanpop** [tannerlinsley/react-table#1524]
# Using v6?
Yes 

**Describe the bug**
Using React table 6.10.3 with React 16.9.0, the following warning is shown:

Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: ReactTable

**Expected behavior**
No warning

**Comment by tannerlinsley** [comment]
Please feel free to submit a PR to fix this issue :)

**Comment by tannerlinsley** [comment]
Closing this issue since it is v6 related.
