### ISSUE TITLE
Add tool-tip feature or hover event on row

### ISSUE THREAD

**Issue by pankaj-webonise** [tannerlinsley/react-table#1525]
# Tool-tip or Hover.
Hi,
It would be nice to have a tool-tip configuration on a row or customize tool-tip on a row.
And hover event on the row.

This could be useful in many places.

**Comment by tannerlinsley** [comment]
Since React Table (v7) is headless, you can use whatever react tooltip library (or even just css) to show tooltips. Just integrate it into your table renderer.

**Comment by sagarCS** [comment]
@tannerlinsley  do we have this tool-tip or hover ability in react table now? or is it still to be added, I want to show a tooltip on hover over the row to show tooltip with some action to perform.
Thanks.

**Comment by gargroh** [comment]
DOM is in consumer's control, you need to add it by yourself.

**Comment by neeraj15022001** [comment]
When adding tooltip to render with cell, it is getting overlapped with other rows. For tooltip i am using tippyjs

<img width="325" alt="Screenshot 2024-03-27 at 11 07 48 PM" src="https://github.com/TanStack/table/assets/55191873/e77f03dc-fbed-4a24-b435-d31b007c6f6e">
