### ISSUE TITLE
Global filter

### ISSUE THREAD

**Issue by john-pc** [tannerlinsley/react-table#1527]
Please Consider adding the ability to setFilter with a column id that is not represented in the table.

Use Case:
Global filter input that can be used with setFilter function along with other filters in the table.
Right now i need to create a dummy column in order to use the setFilter function.
It can be nice if i could pass a flag to the function setFilter that indicates if the column is not represented in the table.

**Comment by adamsoffer** [comment]
A global filter option would be clutch. Here's what a common use case looks like.

![image](https://user-images.githubusercontent.com/555740/65380736-ad83e300-dcaf-11e9-8712-0710801210e7.png)

**Comment by tannerlinsley** [comment]
I think you're right. I'll start thinking on how this could fit into the API. Stay tuned.

**Comment by MoAqsam** [comment]
Whats the status update for this feature ?

**Comment by wpapper** [comment]
A global filter would be fantastic! Our use case is quite similar to the ones already requested. Being able to pair a global filter with something like Fuse.js (https://fusejs.io) for weighting and fuzzy matching would be fantastic for a lot of search use cases.

**Comment by anishpatelyaadada** [comment]
@wpapper i think so you can use material UI for react to add this feature https://material-ui.com/components/tables/

**Comment by xuzhanhh** [comment]
I also need such a plugin! Will this be released soon?😍

**Comment by tannerlinsley** [comment]
This is now available!

## 7.0.0-rc.15

- Added `useGlobalFilter` hook for performing table-wide filtering
- Filter function signature has changed to supply an array of column IDs (to support both the tranditional single column style and the new multi-column search style introduced with `useGlobalFilter`).
- Removed the `column` parameter from the filter function signature as it was unused and no longer made sense with the array of IDs change above.
- Updated the `filtering` example to use a global filter in addition to the column filters

**Comment by anishpatelyaadada** [comment]
@tannerlinsley thank you so much

**Comment by Matheus-Ribeiro95** [comment]
@tannerlinsley MAN, you are amazing! thx :D

**Comment by bartoszgolebiowski** [comment]
Fantastic, could you updated @types/react-table 
useTable function with missing 
```js
    const {
        getTableProps,
        getTableBodyProps,
        headerGroups,
        rows,
        prepareRow,
        state,
      ->   preGlobalFilteredRows,
      ->   setGlobalFilter,
    } = useTable(
        {
            columns,
            data,
            defaultColumn,
        },
        useFilters,
        useGlobalFilter
    );
```

Fantastic lib btw!!!

**Comment by tannerlinsley** [comment]
@bartoszgolebiowski Feel free to submit a PR to the types repo. Those types are 3rd party and not tracked or maintained here.

**Comment by vishalgohel30** [comment]
hello, global filter not proper working plz any suggestion?

**Comment by picolloo** [comment]
For anyone looking for types for the filtering properties from useTable, here is a link for a type definition file https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table

**Comment by kafiarifin** [comment]
Hi @tannerlinsley , 
Is it possible to use one global search box to filter two tables?

![image](https://user-images.githubusercontent.com/35906946/103800815-704b8c00-507f-11eb-9332-eae3c095c0e1.png)
