### ISSUE TITLE
pagination: auto fill the empty rows at the end with repeated data

### ISSUE THREAD

**Issue by pariharps** [tannerlinsley/react-table#1528]
whenever we use react table and do pagination, for example 5 records per page or 10 records per page, if last page have only two records remains empty rows get filled with previous records.

**Expected behavior**
remaining rows should be empty if there is no sufficient data in last page to fill all the rows

version used- 6.9.2

**Comment by tannerlinsley** [comment]
Use the `minRows={0}` prop.

**Comment by zachrnolan** [comment]
@tannerlinsley I'm not seeing the `minRows` prop anywhere in the codebase. Is there a new way to do this?
