### ISSUE TITLE
Duplicate key warning when reusing accessor.

### ISSUE THREAD

**Issue by antoniobologna** [tannerlinsley/react-table#1529]
# Using v7
**Version: 7.0.0-alpha.22**

**Describe the bug**
Getting duplicate key issue for individual cells, when using the same accessor in more than one column.

**To Reproduce**

Given the following example:

```js
columns = {
  Header: 'User',
  columns: [
    {
      Header: 'First Name',
      accessor: 'user',
      Cell: row => <SomeComponent data={row.cell.value.first} />,
    },
{
      Header: 'Last Name',
      accessor: 'user',
      Cell: row => <SomeComponent data={row.cell.value.last} />,
    },
  ],
}
```

This is only an example. I actually have more complex situations involving iterating over one of the accessors, in the example above would be the column user, but in my case, I have an array of objects and need to render each element in the array for different sub-columns. When I add the accessor, I need to have the same accessor for these 2 sub-columns, but I get the duplicate key warning.

**Expected behavior**
No duplicate key warning.

**Desktop (please complete the following information):**

- MacOS Mojave 10.14
- Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)

**Comment by antoniobologna** [comment]
Ok, after some more digging, I added an ID (overriding the default id for the column), which solved the problem. It might be a workaround, or maybe it could be added to the docs :)

**Comment by Borio991** [comment]
can u show your solution in code please ?
iam have the same issue

**Comment by FrazTheWizard** [comment]
> can u show your solution in code please ? iam have the same issue

According to the [docs](https://react-table-v7.tanstack.com/docs/api/useTable#column-options) for **id**
*If a string accessor is used, it defaults as the column ID, but can be overridden if necessary*

Here's how I got it working:

```javascript
const columns = useMemo(() => [
  {
    id: "eventdate", // add unique id here
    Header: "Event Date",
    accessor: "eventdate",
  },
  {
    id: "eventtime", // add unique id here
    Header: "Event Time",
    accessor: "eventdate",
  },
]);
```
