### ISSUE TITLE
[Question] How to call class level onClick handler from inside custom renderer

### ISSUE THREAD

**Issue by jolyonruss** [tannerlinsley/react-table#153]
I have a column called Actions that looks like this:

```
{
  header: 'Actions',
  accessor: 'actions',
  render: ({value, rowValues}) => {
    return <button onClick={(e) => this.handlePublish(e, rowValues._id, rowValues.status)}>PUBLISH</button>
  }
}
```

I have a handler defined in the class, but when I click the button I get the following error:
`Uncaught TypeError: Cannot read property 'handlePublish' of undefined`

Which implies that `this` and scope is not passed into the renderer.

Is there a way to call class level handlers from inside a custom renderer?

Hope that makes sense - let me know if you need more context

**Comment by tannerlinsley** [comment]
I'll look into this asap

**Comment by TacticalCoding** [comment]
Where are you defining the columns?

I do this in my own projects with the columns defined in the constructor and it works fine.

```javascript
render: ({row}) => {
    return (
        <div>
            {
                <Checkbox
                        onToggle={() => {
                            this._handleDescrambleToggle(row.iid)
                        }}
                        checked={row.configuration.descramble}/>
            }
        </div>
    );
}
```

**Comment by tannerlinsley** [comment]
Works fine for me too. Just be sure you are defining your column in your class with only arrow functions all the way to the root of the class

**Comment by jolyonruss** [comment]
Sorry for the delay in replying - I've been away.

Dropping the column definition in my constructor fixed this for me.

I'll create a PR to make this example https://github.com/tannerlinsley/react-table#example a little clearer, by wrapping the whole thing in the render function.
