### ISSUE TITLE
Question: Can I extract filter outside to another component & how would I group two collumns, how would they behave

### ISSUE THREAD

**Issue by MarioKrstevski** [tannerlinsley/react-table#1533]
1. I have a lot of screens that share the same logic, a Filter above a List. And the filter has almost all the selection logic, that directly reflects on the List (like name search), and some extra ones that filter by something else that we don't have data displayed/column for. (Ex: Gender filter) but we don't have a gender column.

How easy would it be to extract the filter logic outside of the Header's as it is currently? And can I see some examples of something like that? I want to use this library because the features pagination and sorting when we click on the table header are handy.

2. This one is concerning how would two columns behave if I combine them. Our table is wide and one way to fix that is to use a better UI pattern, something like this

so far we have the columns: | Name | Surname | City | State |   
which would look like this:
| John | Smith | London | UK | - and based on this, when we click the headers, the people would be sorted by the column clicked in ascending order per se.

With our design changes, the new look is something like this

| John Smith     |
| London - UK   |

We have somehow combined them in the same column and with some visuals, it looks nice. But how would the table behave then, when I click on the Header/ Column name or when I search with my filter, will this react-table library be flexible to enable searching through these items. As far as I know, we are not searching through the display items, but rather through the JSON objects, where the data is separate.

Here are some photos.

Current Version: 
![image](https://user-images.githubusercontent.com/29738062/65334481-bea2f600-dbc2-11e9-9d1d-87a1f12b28f5.png)

Intended Version:
![image](https://user-images.githubusercontent.com/29738062/65334520-d37f8980-dbc2-11e9-9cb0-c68211ce4a2a.png)

I am mostly asking a dumb question and would like some links of similar projects if there are some. It's either this or making a custom component myself.

**Comment by tannerlinsley** [comment]
All of these things are possible in React Table v7, however, we suggest you ask this question in the community forum: https://spectrum.chat/react-table for more help there. We use Github primarily for tracking bugs and feature requests.

If you are looking for consulting or more serious help on this implementation, please DM me on any of my channels and I would be glad to get you some help.

Thanks!
