### ISSUE TITLE
6.10.1 breaks compatibility with React 15

### ISSUE THREAD

**Issue by panlina** [tannerlinsley/react-table#1537]
**Describe the bug**
I see `6.10.1`, `6.10.2`, `6.10.3` is published to npm recently. After some testing I find it's breaking our code using React 15. It gives:

> Cannot read property 'slice' of undefined

for a simple `<ReactTable columns={[]} />`.

**To Reproduce**
I have a demo repo at https://github.com/panlina/react-table-6.10.1-issue.git. Use `npm start` to start it. Once started you can see above error message.
If you install React 16 and try again, it renders successfully.
Or, if you install `react-table@6.10.0`, it renders successfully also.
So seems 6.10.1 is breaking code using React 15.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: chrome 76

**Comment by benflodge** [comment]
This is because the React deprecated methods have been renamed with the UNSAFE prefix in react-table > v6.10.0 by this commit https://github.com/tannerlinsley/react-table/pull/1461. 

I fixed my react table version to be exactly 6.10.0 to avoid a similar issue, as it was causing CI builds to fail.

**Comment by panlina** [comment]
@benflodge Thanks for the info. I'm doing the same. I think it should be avoided to break semver rules.

**Comment by tannerlinsley** [comment]
Breaking Semver is generally avoided when possible. However, because v7 is already underway, we cannot do breaking changes to v6 within the same semver range. This was the only way forward for backwards compatibility.

Tanner Linsley

**Comment by panlina** [comment]
Then I think at least you should put a warning message after install, because users using React 15 will find their app broken after update, wasting time figuring out what's happening.

**Comment by tannerlinsley** [comment]
I've updated the peer dependencies for React and React DOM to `^16`. This should be sufficient.
