### ISSUE TITLE
Can't filter or sort if accessor is undefined

### ISSUE THREAD

**Issue by john-pc** [tannerlinsley/react-table#1538]
If using id instead of accessor automatically the properties canFilter and canSort are turned to false.

**Expected behavior**
If i'm using the backend and i want to concat first_name and last_name  to show it as full_name and i don't return full_name field and only first_name and last_name.

i can't filter it by id "full_name" because i'm not using  accessor.

This makes the columns much less flexible

https://github.com/tannerlinsley/react-table/blob/3b42c72e7c7f649ff8a348fd4877b3a1e53ec4c3/src/plugin-hooks/useFilters.js#L111

**Comment by tannerlinsley** [comment]
I would accept a PR to allow the `canFilter` option on a column to be supported, regardless of an `accessor` being present. This would allow you to set `id: 'full_name', canFilter: true`.

**Comment by plxel** [comment]
I'll work on this one

**Comment by tannerlinsley** [comment]
You can now set a `defaultCanFilter` and `defaultCanSort` at both the table and column levels. If either of these are set to `true`, then those column/columns will be able to filter regardless of an accessor being present or not. 

Note that `disableThing` options still take priority.
