### ISSUE TITLE
How to prevent padRows displaying on last page of multi-page table?

### ISSUE THREAD

**Issue by jacobleesinger** [tannerlinsley/react-table#154]
I have a multi-page table and don't want to display any empty padRows on the last page when my total number of rows is not evenly divisible by the pageSize. 

I tried setting minRows={0}, but that didn't work. Looking through the source code, it seems that setting minRows doesn't actually do anything if there's more than one page. 

Is this the intended behavior / is there some other way to prevent displaying padRows in this scenario?

**Comment by tannerlinsley** [comment]
I'll be cutting a release in the morning. 👍

**Comment by jacobleesinger** [comment]
Well that was quick. Thanks!
