### ISSUE TITLE
v6 Multiple selection issue

### ISSUE THREAD

**Issue by velthune** [tannerlinsley/react-table#1540]
I'm trying to apply a background color on selected rows: 

    getTrProps={(state, rowInfo, column, instance) => ...}

on `rowInfo` I can't find any information on like "selected" or similar (also using `selectTableHOC`)

**Comment by tannerlinsley** [comment]
v6 is not being actively maintained. We still invite you to ask this question in the community forum though! https://spectrum.chat/react-table
