### ISSUE TITLE
onClick that contains setState cancels default  behavior of handleOriginal in getTdProps

### ISSUE THREAD

**Issue by RichyNs** [tannerlinsley/react-table#1541]
What I'm trying to do is when i click on a row I want the background color has to change and i need to get the row's info plus I have the choice to expand the row to show sub component. My getTdProps looks like this : 

` getTdProps={(state, rowInfo) => {
        if (rowInfo && rowInfo.row) {
          return {
            onClick: (e, handleOriginal) => {
              if (handleOriginal) {
                handleOriginal();
                if (tab !== 'resolved')
                  handleRowClick(rowInfo.original, rowInfo.index);`

                handleSelectRow(rowInfo.index);
              }
            },
            style: {
              background: rowInfo.index === selected ? '#AEBFE0' : 'red',
            },
          };
        }
        return {};
      }}`

this code is in the component where as in the container the function handleSelectRow contains a setState ,  when this function contains a setState the row will no longer expand but the clicked row will be colored , if i comment out the setState i can expand the row but i wont get the row info nor the row will be colored.
Any idea on why this is happening ?

**Comment by tannerlinsley** [comment]
v6 is not being actively maintained. We still invite you to ask this question in the community forum though! https://spectrum.chat/react-table
