### ISSUE TITLE
Missing props in `TableOptions` definition

### ISSUE THREAD

**Issue by Sklpcc** [tannerlinsley/react-table#1542]
**Describe the bug**
Missing `defaultColumn`, `getSubRows`, `getRowID` in `TableOptions`.

**Screenshots**

![image](https://user-images.githubusercontent.com/7380924/65550871-23718f80-dee6-11e9-89b1-b8a07a94c154.png)

**Comment by stramel** [comment]
please see #1535

**Comment by Sklpcc** [comment]
I'm closing this then. I didn't check that issue because the title is not very clear. I suggest something like: `Update types with codebase`? Anyway, great job in that PR. :tada:
