### ISSUE TITLE
Custom sorting for column does not work

### ISSUE THREAD

**Issue by simPod** [tannerlinsley/react-table#1543]
I cannot set custom sorting function for column.

In types, there is defined `sortByFn`

```ts
  export interface HeaderColumn<D> {
    /**
     * This string/function is used to build the data model for your column.
     */
    accessor: IdType<D> | AccessorFn<D>
    Header?: ReactNode | ((props: TableInstance<D>) => ReactNode)
    Filter?: ReactNode | ((props: TableInstance<D>) => ReactNode)
    Cell?: ReactNode | ((cell: Cell<D>) => ReactNode)
    /**
     * This is the unique ID for the column. It is used by reference in things like sorting, grouping, filtering etc.
     */
    id?: IdType<D>
    minWidth?: string | number
    maxWidth?: string | number
    width?: string | number
    disableSorting?: boolean
    canSortBy?: boolean
    sortByFn?: SortByFn
    defaultSortDesc?: boolean
    isAggregated?: any
  }
```

However, it is not used anywhere by this library. The only way I found to implement custom sorting was adding a new `sortTypes` and then referencing it through `sortType` property on column. That is not defined on the `HeaderColumn` type though.

I'm not sure what's more updated, whether API docs or ts types.

**Comment by tannerlinsley** [comment]
The types are still not up to date with v7. The docs should say that you can pass a custom function as the `sortType` prop on a column to get the functionality you want. If the docs don't reflect this, please submit a PR to update them? Thanks!

**Comment by stramel** [comment]
Types for v7 are not yet published. Types for v6 are published on DefinitelyTyped. You can provide a declaration file for your project in the meantime. Otherwise, I'm looking for feedback on #1535

**Comment by simPod** [comment]
Will types be published on DefinitelyTyped? I noticed there's a trend to keep them with repository so they don't get out of sync so easily.

**Comment by stramel** [comment]
Types will be published in the package for v7.
