### ISSUE TITLE
Selected Rows not Unselected on data change/update

### ISSUE THREAD

**Issue by swrap** [tannerlinsley/react-table#1544]
### Using v7? *YEP!*

Thanks for using the beta version of React Table v7! We're very excited about it.

**Describe the bug**
Selected checkboxes are not reset after change of table data

**To Reproduce**

1. Go to https://codesandbox.io/s/tannerlinsleyreact-table-row-selection-oz1nc
2. Click on some of the check boxes
3. Click on the *Random Data* button at the top of the page
4. The selected checkboxes have not been unselected although the data has been changed.

**Expected behavior**
I thought that because there was a change in data that the selected checkboxes would be reset. 

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Version: 69.0.1

**Additional context**
I have scoured the internet and your forums for how to manually update the rows selected from outside of the functional Table component I am making, but I have yet to find the answer. I have tried to use `toggleRowSelectedAll`, however I could not figure out how to only call it once on a change of data.

**Comment by swrap** [comment]
Found a work around for now by tracking a change to the internal value. 

Below is a sample:
dataChangedVersion: a number that should be increment outside which will reset selected columns
```javascript
function Table({ columns, data, dataChangedVersion }) {
    React.useEffect(() => {
        toggleRowSelectedAll(false)
    }, [dataChangedVersion])

...//Render the table
}
```

**Comment by tannerlinsley** [comment]
I agree that this should probably be default functionality with a toggle to turn if off, but I LOVE that you were able to solve this with a single hook. So cool.

**Comment by tannerlinsley** [comment]
If you would be willing, I would love to see you try to submit a PR to update this functionality :) Let me know if you're interested.

**Comment by swrap** [comment]
> 
> 
> If you would be willing, I would love to see you try to submit a PR to update this functionality :) Let me know if you're interested.

Sure thing, I think I will be able to some time soon. I am still getting used to React Hooks and also the `react-table` library, so be gentle with my PR.

**Comment by tannerlinsley** [comment]
Always :)

Tanner Linsley

**Comment by swrap** [comment]
Was actually looking into this today, but it seems that is has been fixed. I think it was in this [commit](https://github.com/tannerlinsley/react-table/commit/4842bc061d3421f297c6ab30809d17ba6bd7c642). It now resets the selected rows on a data change. There was also a couple other commits in the blame like [bbfc6428b7ce530cd6e03938084068b97f3800c7](https://github.com/tannerlinsley/react-table/commit/bbfc6428b7ce530cd6e03938084068b97f3800c7) and [e43968c6849ee82d8e2ee7404ec82387435e1444](https://github.com/tannerlinsley/react-table/commit/e43968c6849ee82d8e2ee7404ec82387435e1444), but I think it might have been the earlier one... It is not configurable, however it solves my issue.
