### ISSUE TITLE
Jump to next page does not work

### ISSUE THREAD

**Issue by BoriskinaAnna** [tannerlinsley/react-table#1546]
# Using v6?

**Describe the bug**
Jump to next page does not open next page.

**To Reproduce**

1. Add ReactTable Component
2. Try to press "jump to next page button"

**Expected behavior**
The next page is visible

**Actual behavior**

The previous page is still open

**Comment by BoriskinaAnna** [comment]
**describe**

**Comment by BoriskinaAnna** [comment]
**describe**: Jump to next page does not open next page.

**Comment by tannerlinsley** [comment]
v6 is no longer being maintained here on Github. You might be able to get some community support if you ask this question in https://spectrum.chat/react-table. Thanks!
