### ISSUE TITLE
Can't create dynamic table

### ISSUE THREAD

**Issue by valentyna-refundit** [tannerlinsley/react-table#1547]
# Using v7?

Yes, v. 7.0.0-beta.0

**Describe the bug**
I want to create a dynamic table after a server response (for example, i will use keys from the first object), but I can't do it now.
Because `columns` with *Column* type required (can't pass empty object while making a request)
I also tried to do a conditional render inside TableHead/TableCell (but the hooks themselves don't allow this, added a screenshot)

**Expected behavior**
The user must be able to render an empty table. Otherwise there will be ugly page jumps when the table appeared. And we can't implement own **Loading** component for table (as it was in version 6).

**Screenshots**
![Screenshot from 2019-09-26 16-22-43](https://user-images.githubusercontent.com/45849756/65691739-0a99e300-e07a-11e9-91ea-b52fdc3643a3.png)

I will be grateful for any ideas/examples in resolving this issue.

**Comment by tannerlinsley** [comment]
If you don't know the column structure beforehand, then the only option you have is to pass `columns` as an empty array and `data` as an empty array. Once your server request resolves, you can update them.

If you want to fake a table, simply pass some fake columns and data to render a placeholder table until things resolve.

**Comment by tannerlinsley** [comment]
If you would like more help with this, I would suggest opening a discussion in spectrum.chat/react-table
