### ISSUE TITLE
passing table instance to pagination component causes infinite loop

### ISSUE THREAD

**Issue by keeganstothert** [tannerlinsley/react-table#1549]
# Using v7

I am using useSortBy and usePagination. I have a pagination component that receives the useTable instance as prop. The instance must be unstable because it is causing an infinite rerender in my pagination component

I traced the unstable props that are causing the update 

<img width="438" alt="Screen Shot 2019-09-26 at 1 11 08 PM" src="https://user-images.githubusercontent.com/3612936/65717741-45dae880-e05f-11e9-9fc1-5721a7326a53.png">

**Comment by keeganstothert** [comment]
@tannerlinsley did I not submit this correctly?

**Comment by tannerlinsley** [comment]
Nope, you did!

It's fixed in the latest release :)
