### ISSUE TITLE
[Feature Request] using table tag instead of div

### ISSUE THREAD

**Issue by andychinka** [tannerlinsley/react-table#155]
If you copy the table in the website and paste in excel,
all data will be paste inside a cell now,
if it is using <table>, the whole table can be copied perfectly.

**Comment by tannerlinsley** [comment]
The first few versions of react-table were written in html tables, but capabilities like dynamic widths, fluid layout, etc were quickly found to be impossible.  For this reason we switch to use flexbox and drop support for non-modern browsers.  If you're interested, you could always implement a custom clipboard HOC for what you are describing using something like [react-copy-to-clipboard](https://github.com/nkbt/react-copy-to-clipboard) :)
