### ISSUE TITLE
Column width

### ISSUE THREAD

**Issue by yurzo** [tannerlinsley/react-table#1553]
@tannerlinsley:
First of all... Fantastic work on V7!
Maybe I'm too burn out but could not find in the docs how to set column widths. Is it there and I just wasn't able to find it?

**Comment by ctoppel** [comment]
And is drag-to-set column widths removed? An example on how to implement this with the new table would be great in case this was removed...

**Comment by yurzo** [comment]
@tannerlinsley: Hey... I figured my problem out (newbie mistake) the "filter table" example includes <input>. Which was incompatible with Bootstrap.
As soon as I replaced that with <InputGroup> it all became reactive and the width was no longer an issue.

**Comment by vladkolodka** [comment]
@yurzo I can't find any examples of setting column width here https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/filtering
Where did you find it?

**Comment by tannerlinsley** [comment]
Please refer to these examples:
- https://github.com/tannerlinsley/react-table/tree/master/examples/
- https://github.com/tannerlinsley/react-table/tree/master/examples/block-layout
- https://github.com/tannerlinsley/react-table/tree/master/examples/column-resizing

**Comment by IanVS** [comment]
Is there no way to set a column width while keeping table elements?

**Comment by SevenZark** [comment]
Yes, please! This is really important to some of us who really like that react-table is headless, but forcing us to have black-box lib functions attach themselves to elements to change presentation aspects seems to me to step over the line of truly headless (though I realize others probably find the attached functions convenient). For me, this messes with how I have drag-and-drop column order working, and it's a simple matter for me to attach my own mouse events to a resize handle to deal with column sizes... except react-table will not allow me to set the widths programmatically, so I have to fall back on custom state management, a thing I'm trying to avoid by using react-table in the first place.
