### ISSUE TITLE
Header groups colSpan doesn't adjust with hidden columns on V7

### ISSUE THREAD

**Issue by anton-z-s** [tannerlinsley/react-table#1555]
**Describe the bug**
When hiding columns, the colSpan of their respective headers doesn't change, resulting in columns being shifted to wrong headers.

**To Reproduce**

1. Hide column that is not the last visible column in the header
2. The colum Header colSpan doesn't reflect visible columns count

**Expected behavior**
The colSpan property of the header groups should be calculated with hidden columns in mind.

**Codesandbox!**
https://codesandbox.io/s/tannerlinsleyreact-table-basic-2p9in
LastName column is hidden, but Name header takes 2 columns, instead of 1

**Screenshots**
![Screenshot from 2019-09-29 22-54-55](https://user-images.githubusercontent.com/3487683/65834370-c5411400-e30c-11e9-9571-16b9431c949f.png)

**Additional context**
The bug is exactly like https://github.com/tannerlinsley/react-table/issues/1446

The problem is there https://github.com/tannerlinsley/react-table/blob/master/src/utils.js#L154
totalHeaderCount doesn't take into account if column is visible or not. At the time of function execution we don't have isVisible property.
I can send a PR if you ok with me adding new property totalVisibleHeaderCount that will be calculated after https://github.com/tannerlinsley/react-table/blob/master/src/hooks/useTable.js#L209

**Comment by tannerlinsley** [comment]
Fixed!
