### ISSUE TITLE
TypeError: sortedData is undefined

### ISSUE THREAD

**Issue by frank-guo** [tannerlinsley/react-table#1556]
I am testing a simple example and get the error above at react-table/es/index.js:150. In addition, I tested some other simple examples given in Git home of this project and all got the same error. I am using react-table 6.10.3, the latest version. Has anyone seen this before? Thank you.

**Comment by tannerlinsley** [comment]
All of the docs, examples, etc on the master branch are for v7. v6 is no longer being tracked and maintained.

**Comment by jessicaNamora** [comment]
I had the same error and solved doing node upgrade from v8.10.0 to v10.16.3

**Comment by frank-guo** [comment]
Thank you guys. I solved also by upgrading react and relevant packages.
