### ISSUE TITLE
Documentation does not contain that columns array element can have sortMethod property

### ISSUE THREAD

**Issue by meetDeveloper** [tannerlinsley/react-table#1558]
In documentation it is not mentioned that element in columns array can also have sortMethod property.

**Comment by tannerlinsley** [comment]
Located @ https://github.com/tannerlinsley/react-table/blob/master/docs/api.md#table-options-1 under the `sortType` option.

**Comment by tannerlinsley** [comment]
You bet. If you would like to improve the v6 documentation, please submit a pull request to the v6 branch. Thanks for your support!

**Comment by meetDeveloper** [comment]
@tannerlinsley I will send, I wanted to confirm if I have not misread something.
