### ISSUE TITLE
Custom Header

### ISSUE THREAD

**Issue by chrys1110** [tannerlinsley/react-table#156]
I am restyling your table. But I couldn't add a sort icon in the header.

Like:

**| ___ Name ___ | ___ Age 🡱 ___ |**

I tried to tie into the header like so:
`<ReactTable columns={ [ { accessor: 'age', header: ( { column } ) => ??? } ] } />`

But maybe there is an even better solution to create a template for all the column-headers to add a font-awesome icon like `<i className="fa fa-arrow-down"></i>` in the end of the column (depending if it's sort ASC or DESC)

Any recommendations?

**Comment by mikedevita** [comment]
you need to add the `header: () => <span><i className='fa-tasks' /> Progress</span>,` as described in [this](https://github.com/tannerlinsley/react-table#custom-cell-header-and-footer-rendering) section of the readme.

**Comment by chrys1110** [comment]
Yeah, I was aware of this, but I don't know the information which column is sorted and if ASC or DESC

**Comment by eladbs** [comment]
Why don't you use CSS for that?
Here's what I use:
`div.-sort-asc::after {
  content: "\25BC";
  float: right;
}

div.-sort-desc::after {
  content: "\25B2";
  float: right;
}`

**Comment by tannerlinsley** [comment]
Both of those are perfectly fine examples.  To discuss implementation more, please [join the slack organization](https://react-chat-signup.herokuapp.com/)  :)
