### ISSUE TITLE
Highlight a row

### ISSUE THREAD

**Issue by JimmerSmith** [tannerlinsley/react-table#1560]
Hi,

I am really new to react. I'm sure this question has been asked before but how do you highlight a row using react-table.

I've found examples e.g. https://codesandbox.io/s/mml59oz86y which does exactly what I want using the older <ReactTable>. How would I go about this if using the newer hooks like in the basic sorting example. (https://codesandbox.io/s/tannerlinsleyreact-table-sorting-trying-to-add-highlight-l16uy). How would I go about doing this. 

Any help will be appreciated. Thanks

**Comment by thiennn2** [comment]
"Highlight a row" or "How would I go about this if using the newer hooks like in the basic sorting example."?

**Comment by tannerlinsley** [comment]
☝️ This is a great example on how to do that
