### ISSUE TITLE
IE11 window.print() not printing data after first page to last page v6.7.4

### ISSUE THREAD

**Issue by narechowdary** [tannerlinsley/react-table#1561]
# Using v6.7.4

**Describe the bug**
IE11 window.print(), Screen is not printing data in react table after first page. here i have selected 100 rows in table by using pagination.

**To Reproduce**

1. select 100 rows in table
2. right mouse click and click on print preview
3. table data is coming only first page of print preview remaining pages coming blank

**Expected behavior**
it should come all datain table

**Codesandbox!**
Use a new [react-table codesandbox](https://codesandbox.io/s/m5lxzzpz69) to reproduce the issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/17018025/65985387-47cdee80-e447-11e9-9d92-3833c3549ee1.png)
![image](https://user-images.githubusercontent.com/17018025/65985407-574d3780-e447-11e9-8b00-0d1d22fc3218.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser IE
- Version 11

**Smartphone (please complete the following information):**

**Additional context**
first page data coming in table remaining pages not coming , below table footer and remaining stuff printing in print preview.

**Comment by tannerlinsley** [comment]
Issues with v6 are not tracked in Github any more since v6 has been deprecated. We suggest you upgrade to v7 as soon as possible. If you would like to ask further questions about this issue, we suggest you do so in the community forum: https://spectrum.chat/react-table
