### ISSUE TITLE
HeaderColumn type declaration

### ISSUE THREAD

**Issue by dinony** [tannerlinsley/react-table#1563]
Using v7

**Describe the bug**

Type declaration of `HeaderColumn` does not seem to mirror implementation.
[accessor](https://github.com/tannerlinsley/react-table/blob/master/index.d.ts#L61) is required in `HeaderColumn` but the Row Selection [example](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/row-selection) just specifies `[id, Header, Cell]`. It looks like just `id` should be fine: https://github.com/tannerlinsley/react-table/blob/master/src/utils.js#L27

Thanks for your work!

**Comment by tannerlinsley** [comment]
Types are currently being upgraded. Thanks for the tip!

**Comment by dinony** [comment]
Ah ok. For folks testing the beta and also having issues with outdated type declarations:

```typescript
const {getTableProps} = (useTable as any)({columns, data)
```

Do not forget to remove the type assertion, once type declarations are in sync.
