### ISSUE TITLE
Horizontal scrollbar only appears after scroll to bottom of table

### ISSUE THREAD

**Issue by MidouDev** [tannerlinsley/react-table#1566]
I'm working on project in which I'm using react-table, the table contains many columns so you'll have to scroll right to see the rest of your data, the problem is that the horizontal scrollbar only shows when you reach the bottom of your table, so every time you want to see the rest of a row data you'll have to scroll to bottom and then scroll right and the scroll to top and look for your row.
Is there a way I can show the horizontal scrollbar without having to scroll to bottom ? I've tried 

.ReactTable .rt-tbody {
  overflow: initial !important;
}

and with overflow : overlay

it solves the problem but the rows come out of the table frame.

**Comment by tannerlinsley** [comment]
Since this is a question about React Table v6 (which has been deprecated and is no longer actively maintained), we suggest you ask this question on our community support forum instead: https://spectrum.chat/react-table.

Thanks!
