### ISSUE TITLE
defaultResized column issues...

### ISSUE THREAD

**Issue by timothydowd** [tannerlinsley/react-table#1569]
I have a browserState that updates using onResizedChange, as well as onFilteredChanged.  When i change the column size, change page then come back to the page with the react table, the resized array shows in my console, so its updated, yet the column size has not been remembered in the ui....

However, if I change the column size and I add a filter to any column, change pages then comeback to the react table, both filtered and resized show in the console.logs as expected and now the ui registers the column size from browserstate and is adjusted accordingly...  Is there a bug with defaultResized??

react-table v 6.10.3

- OS: windows10
- Browser chrome  77.0.3865.90

**Comment by timothydowd** [comment]
ok - i since made a codesandbox for my issue and whilst the problem is apparent in my local environment, there is no issue in the sandbox and the browserState works just fine with the defaultResize prop... Any ideas?

**Comment by tannerlinsley** [comment]
Without looking at your code I can’t really offer any suggestions. I think at this point we could close the issue and move your question to https://spectrum.chat/react-table to get more eyes on it.

**Comment by timothydowd** [comment]
here is the code sandbox - https://codesandbox.io/s/react-router-dom-testing-1kz2p

my issue is in spectrum chat already....

**Comment by timothydowd** [comment]
> Without looking at your code I can’t really offer any suggestions. I think at this point we could close the issue and move your question to https://spectrum.chat/react-table to get more eyes on it.

Here is the code sandbox...  https://codesandbox.io/s/react-router-dom-testing-1kz2p

My issue is already in spectrum chat..

**Comment by tannerlinsley** [comment]
Ahh I see. This is v6. As of today, v7 is almost stable and I don't plan on doing much for v6 from here on out except for security releases, etc. I'm sorry I can't help you out more, but I would still suggest that you ping some other people in Spectrum that use v6 and see if they have any other suggestions.
