### ISSUE TITLE
[v7] Reorder columns by dragging example

### ISSUE THREAD

**Issue by gargroh** [tannerlinsley/react-table#1570]
To re-order columns by dragging i have created an example by using `react-beautiful-dnd`

Link - https://codesandbox.io/s/gargroh-v7-drag-column-beautiful-react-dnd-encww

@tannerlinsley wanted to check, `whether` this is good to go example for everyone who uses v7 and want this feature OR using any other DnD/sortable library would be more compatible with `react-table` in terms complexity(of implementation)/ customization/better UX or anything else better....which you have thought while writing v7.

**Comment by tannerlinsley** [comment]
This is a perfectly fine example! Please make a PR to add it to the examples directory and examples.md.

**Comment by HassanAbbas198** [comment]
@tannerlinsley  hello, is it necessary to use 'useAbsoluteLayout'? I'm trying to implement it and it is breaking my styles

**Comment by peraltafederico** [comment]
> @tannerlinsley hello, is it necessary to use 'useAbsoluteLayout'? I'm trying to implement it and it is breaking my styles

@tannerlinsley @HassanAbbas198  I just added a pull request [here](https://github.com/tannerlinsley/react-table/pull/3369) that implements column dnd by using `react-dnd` and only table elements, so non layout plugin hook is required :)

**Comment by rogerfar** [comment]
@peraltafederico I'm trying to implement drag&drop columns, what is your preferred way? The Atlassian ones looks a bit more polished as it has dragging updates.

**Comment by peraltafederico** [comment]
> @peraltafederico I'm trying to implement drag&drop columns, what is your preferred way? The Atlassian ones looks a bit more polished as it has dragging updates.

Hey @rogerfar! Honestly I couldn´t make react-beautiful-dnd work with react-table without using its layout hooks (e.g useAbsoluteLayout). So I decided to give a try to react-dnd as it´s used in the [official example for drag and drop of rows](https://react-table.tanstack.com/docs/examples/row-dnd). I could fit my needs with it so I created an example due it isn´t in the documentation yet :).

Just in case, here it is a Codesandbox with the implementation https://codesandbox.io/s/react-table-column-dnd-hkj2y

**Comment by JWTappert** [comment]
> To re-order columns by dragging i have created an example by using `react-beautiful-dnd`
> 
> Link - https://codesandbox.io/s/gargroh-v7-drag-column-beautiful-react-dnd-encww
> 
> @tannerlinsley wanted to check, `whether` this is good to go example for everyone who uses v7 and want this feature OR using any other DnD/sortable library would be more compatible with `react-table` in terms complexity(of implementation)/ customization/better UX or anything else better....which you have thought while writing v7.

What was the reason for going with divs instead of using table elements?

**Comment by gargroh** [comment]
Generally the given table will be having too many features together like virtualization etc., so thought of starting with divs, if tr td works fine for you feel free to go ahead with that.

**Comment by AlfredBryan** [comment]
Hello i am getting this error when i try to drag and drop 
TypeError: currentColOrder.current is not iterable

**Comment by stepinfwd** [comment]
> here

use allColumns instead of flatColumns
