### ISSUE TITLE
Ability to add a sub-footer

### ISSUE THREAD

**Issue by johndmeyer** [tannerlinsley/react-table#1573]
You can currently add sub headers (e.g. headers that group other headers). It would be nice to be able to add footers at this level. Something like this: 
```
<ReactTable
  data={data}
  columns={[
    {
      Header: "Name",
      Footer: "Name Footer", 
      columns: [
        {
          Header: "First Name",
          accessor: "firstName",
          Footer: () =>
            <div style={{ textAlign: "center" }}>First Name</div>
          } . . .
```

**Comment by tannerlinsley** [comment]
I think this would be a welcome addition to the API. I’ll look into it’s implementation over the next few days.

**Comment by anrao91** [comment]
@tannerlinsley Can I work on this ?

**Comment by burtyish** [comment]
This sounds great! 
What is the current mechanism for adding a footer to a table now? Would you set it up as an expanded last row using `useExpanded`?
I'd love to see an example of this

**Comment by tannerlinsley** [comment]
I’m working on this right now. Stay tuned.

Tanner Linsley
