### ISSUE TITLE
Filter search term highlight

### ISSUE THREAD

**Issue by panfiva** [tannerlinsley/react-table#1575]
Please add ability to highlight text matched by filter similar to search result highlighting in data tables. datatables.net/blog/2014-10-22

**Comment by tannerlinsley** [comment]
This has already been requested in #1527. We'll track it there. Thanks!

**Comment by simkessy** [comment]
Hey, just implemented the global search but I'm not seeing anything regarding highlighting in issue #1527

**Comment by kizu** [comment]
It is possible to get the current filters state — both for the regular filters and for the global filter — inside the `Cell` method of the `columns` options.

They're available inside the `state`, so for the global filter we can get it like this (imagine this being inside the `columns` definition and having a `highlight` function that would do the work for you):

```js
Cell: ({ cell: { value }, state: { globalFilter } }) => highlight(value, globalFilter)
```

**Comment by latobibor** [comment]
If anyone looking for a highlighting implementation that _might work well_ with right-to-left languages like Arabic and respects case of highlighted item then here is what I did:

```typescript
import React from 'react';
import { CellProps } from 'react-table';

// if you use `dangerouslySetInnerHTML` you must sanitize your values most likely
import DOMPurify from 'dompurify';

export function HighlightableCell<T extends object>({
  cell: { value },
  state: { globalFilter: searchTerm },
}: CellProps<T, string>) {
  if (!searchTerm) {
    return <div>{value}</div>;
  }

  const searchRegex = new RegExp(`(${escapeRegExp(searchTerm)})`, 'ig');
  const highlightedText = value.replace(searchRegex, '<span class="cell-search-highlight">$1</span>');

  return <div dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(highlightedText) }} />;
}

// from this line below is from lodash.escapeRegExp
const reRegExpChar = /[\\^$.*+?()[\]{}|]/g;
const reHasRegExpChar = RegExp(reRegExpChar.source);

function escapeRegExp(string: string): string {
  return string && reHasRegExpChar.test(string) ? string.replace(reRegExpChar, '\\$&') : string || '';
}

```

And in your table definition:
```typescript
  const columns = React.useMemo(
    (): Column<YourMightyRowObject>[] => [
      {
        Header: 'Phone number',
        accessor: 'phoneNumber',
        Cell: HighlightableCell,
      },
      // ...
]);
```
