### ISSUE TITLE
useRowSelect does not work with multi-level grouping

### ISSUE THREAD

**Issue by jasonlaw-dev** [tannerlinsley/react-table#1589]
# Using v7? Yes

Thanks for using the beta version of React Table v7! We're very excited about it.

**Describe the bug**
useRowSelect does not work with multi-level grouping

**To Reproduce**
Go to kitchen sink
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/kitchen-sink

Toggle grouping for the first 2 columns
Select the topmost row -> the checkbox is not checked

**Comment by tannerlinsley** [comment]
Fixed in the latest version! Thanks!
