### ISSUE TITLE
When defining a column, header and accessor cannot be defined as functions at the same time

### ISSUE THREAD

**Issue by Kristoffer88** [tannerlinsley/react-table#1592]
Thanks for this great library.
Not sure this is the biggest issue but took me some time to find out, why an accessor did not work.

Version 7

When defining columns, there seems to be a bug, when both the accessor and the header is expressed as functions.

[Line 111, in App.js)
[](url)
A column with header as a function: https://codesandbox.io/s/tannerlinsleyreact-table-basic-039ub
A column with accessor as a function: https://codesandbox.io/s/tannerlinsleyreact-table-basic-zj0nv
Both as functions: https://codesandbox.io/s/tannerlinsleyreact-table-basic-fkoyc

**Comment by Kristoffer88** [comment]
If you give it an id, it works:

https://codesandbox.io/s/tannerlinsleyreact-table-basic-oesbv

**Comment by ggascoigne** [comment]
if accessor is a function, you must provide an id.

```
id: String
    Required if accessor is a function
```
