### ISSUE TITLE
v7 Sub Components: Expanded state doesn't reset when data changes

### ISSUE THREAD

**Issue by JordanW7** [tannerlinsley/react-table#1593]
**Describe the bug**
Once a sub-component for an item (i.e. item of index 0) has been opened, if the data for the table changes, item at index 0 will still have an open sub-component state, even if the item at index 0 is a different item.

**To Reproduce**
1. Expand an item
2. Update the data provided to the table

**Expected behavior**
1. Expanded items should close when data is updated, or subcomponent state should be based on something other than item index.

**Codesandbox!**
https://codesandbox.io/embed/tannerlinsleyreact-table-sub-components-25ecw

**Comment by tremby** [comment]
I'm hitting the same issue. Would a possible solution be to allow some way to specify a unique key for each table row? And then, as suggested in the post above, subcomponent state could be automatically based on that rather than index.

**Comment by tannerlinsley** [comment]
I'll look into this.

**Comment by tannerlinsley** [comment]
There is now a new `getResetExpandedDeps` table option. It defaults to this:
```js
useTable({
  getResetExpandedDeps: instance => [instance.data]
})
```

The items returned in this array are used to fire the effect that resets the `expanded` state. As is, you won't need to change anything for your use case, since it defaults to tracking `data`.

Will be available by the end of the day.

**Comment by tremby** [comment]
@tannerlinsley thanks, but can you go into a little more detail? I don't fully understand from your description how to use this.

**Comment by tannerlinsley** [comment]
For now, it “just work”. The expanded state will now reset when the data changes.

Tanner Linsley

**Comment by tremby** [comment]
Ah, I see! Thanks.

**Comment by talolard** [comment]
Hi,
We want the opposite of this behavior, e.g. user makes a change in an expanded row, which triggers a server call, which changes the data fed to the table. We know that the row still exists, and would like it to remain expanded. 
Any tips on how to make that happen ? 
Thanks!

**Comment by talolard** [comment]
I feel dumb for asking, sorry. simply
````es6
      getResetExpandedDeps: false

````
Works
> Hi,
> We want the opposite of this behavior, e.g. user makes a change in an expanded row, which triggers a server call, which changes the data fed to the table. We know that the row still exists, and would like it to remain expanded.
> Any tips on how to make that happen ?
> Thanks!

**Comment by michael-han-grab** [comment]
For those that are looking for the `getResetExpandedDeps: false` functionality, the option has now changed to 
```
useTable({
    autoResetExpanded: false
})
```
[via the documentation here](https://react-table.js.org/faq#how-do-i-stop-my-table-state-from-automatically-resetting-when-my-data-changes)

**Comment by sapiens-shahbaz-khan** [comment]
Hi, I am a case where I need to maintain the expanded state of the table tree when doing CRUD operations.
However, when we are deleting any item (say at 0.0 index, which is a child), I am expecting to get an expanded state which only has { 0 : true } and not the previous state { 0: true, 0.0: true }.
Or say if I delete the parent itself, the new expanded state should be an empty object {}.
Is it possible?
