### ISSUE TITLE
Rendering blank rows

### ISSUE THREAD

**Issue by alisman** [tannerlinsley/react-table#16]
I passed the table only two rows.  For some reason, it still renders a full page of rows, with the last 18 or so rows blank.

**Comment by alisman** [comment]
I see now these are -padrows, so probably hidden in css.  I'm hoping to use this with bootstrap styles so will have to think on this.

**Comment by tannerlinsley** [comment]
You can set minRows to 0.

**Comment by mikedevita** [comment]
👍

**Comment by pogran** [comment]
solution https://github.com/react-tools/react-table/issues/514
