### ISSUE TITLE
[v7] Column toggle visibility feature 

### ISSUE THREAD

**Issue by gargroh** [tannerlinsley/react-table#1600]
To add column show/hide functionality(via user actions), there seems to be following ways :- 

1. Add a new hook, which have default state, detach current `show` attribute from columns and derive it from plugin's default state and add needed column methods.

2. Keep the current data structure, add a new method to column for toggling visibility, but will require one more property apart from `isVisible` and `show`.

3. Manage the state outside of react-table, by updating the `columns` config itself.

@tannerlinsley , what are your thoughts on it and what would you prefer ?

**Comment by kbruskiewicz** [comment]
Has that implementation been tested?

**Comment by gargroh** [comment]
Nope, it works for `flatColumns` only, not for group headers..

**Comment by gargroh** [comment]
@tannerlinsley point 1 in https://github.com/tannerlinsley/react-table/issues/1600#issue-507231067 sounds good to me, what is your opinion on it ?

**Comment by gargroh** [comment]
https://github.com/tannerlinsley/react-table/pull/1634 for the same.

**Comment by papigers** [comment]
How about accepting a function to the `show` property that receives that table/columns data and returns true/false to indicate whether the column should be shown or not.

`show: Boolean` => `show: Boolean | TableData => Boolean`

**Comment by tannerlinsley** [comment]
That should already be implemented. No?

Tanner Linsley

**Comment by papigers** [comment]
@tannerlinsley It is, I misunderstood the issue, my bad.

**Comment by tannerlinsley** [comment]
At this point, considering a plugin like this somewhat defeats the purpose of having a `show` option in columns, am I right? Can you think of any reason why a dev would want the `show` option  and not just want to use a hypothetical column visibility plugin?

**Comment by gargroh** [comment]
> Can you think of any reason why a dev would want the show option and not just want to use a hypothetical column visibility plugin?
For features like providing toggling functionality at user level, something like given in snapshot on this link https://github.com/tannerlinsley/react-table/issues/1649#issue-525806262

**Comment by gargroh** [comment]
>At this point, considering a plugin like this somewhat defeats the purpose of having a show option in columns, am I right

Yes, chnages mentioned in https://github.com/tannerlinsley/react-table/pull/1634#issue-337900708 will apply for above feature.

**Comment by tannerlinsley** [comment]
Tracking all of this in #1700
