### ISSUE TITLE
Jest - Unexpected token export error running tests

### ISSUE THREAD

**Issue by dsoffiantini** [tannerlinsley/react-table#1602]
When running unit tests on a React Table v7 component, I get the following error:
```

export const alphanumeric = (rowA, rowB, columnID) => {
    ^^^^^^

    SyntaxError: Unexpected token export
```

With the current structure of my application, I cannot provide Jest with transpile options that could fix this issue.

**To Reproduce**
1. import and use alphanumeric sorter in a react table setup
2. write unit test and try to render component

**Expected behavior**
Unit tests run successfully when utilizing react table 7

**Comment by tannerlinsley** [comment]
Even after a clean yarn install, I cannot reproduce this error.
