### ISSUE TITLE
Any updates on when React table 7 is going to be released ? 

### ISSUE THREAD

**Issue by pkareti** [tannerlinsley/react-table#1603]
Any updates on when React table 7, stable version is going to be released ?

**Comment by sejensen** [comment]
We uses version 7 beta 0 and spent hours debugging selection issues, when we found out that the kitchenzink eksample uses the next version which includes features and changes which is as far as we know not released yet. We would really love to get a release of v7 soon since we are using it in af project with a deadline in the near future. Thanx for really great library!

**Comment by manobalas** [comment]
> We uses version 7 beta 0 and spent hours debugging selection issues, when we found out that the kitchenzink eksample uses the next version which includes features and changes which is as far as we know not released yet. We would really love to get a release of v7 soon since we are using it in af project with a deadline in the near future. Thanx for really great library!

Same here

**Comment by tannerlinsley** [comment]
I’ll be home from my holiday tomorrow with more info.

Tanner Linsley

**Comment by paul-mcgrath** [comment]
Sorry to bump this, but I'm trying to decide whether to build on v6 or v7 right now, and it looks like the early v7 releases may not be ready.

@tannerlinsley would you have any update on this? Also, thank you for such a great library, and giving so much of your time to this project :)

**Comment by tannerlinsley** [comment]
Trying to get it released as stable by the end of November.

**Comment by paul-mcgrath** [comment]
Great, thanks @tannerlinsley

**Comment by sejensen** [comment]
Thanks @tannerlinsley Is it possible to release a beta version or release candidate in the near future? We would like to lock our build to a version instead of next which may break the functionality tested by our client anytime.
