### ISSUE TITLE
React table is breaking when ran with npm run start and works fine when ran with yarn start

### ISSUE THREAD

**Issue by shibilyt** [tannerlinsley/react-table#1604]
I have been using react table 7.0.0.beta for a while.

It worked fine till a few days back.

Now, the app breaks on whatever page a table is placed in.

The issue only comes up when I am using npm run start and doesn't come when using yarn start

**Comment by seventy-to-eternity** [comment]
What does the error say?

**Comment by shibilyt** [comment]
Update: 
The problem was actually build pipeline updating the react-table to the latest beta release. It broke some of the code I have written. 

Once I have reverted it back to the 7.0.0.beta.0 it works fine.

BTW, the error was this:

TypeError: arr[Symbol.iterator] is not a function

**Comment by ggascoigne** [comment]
This is caused by trying to deconstruct an undefined variable. The api changed between beta 9 and beta 10, specifically, useTableState no longer exists. You need to update your code to reflect this.

**Comment by tannerlinsley** [comment]
Yes. Pull on master and try again. Also, we use yarn right now to build, so there's no guarantees around using npm for now.
