### ISSUE TITLE
[QUESTION] Is it possible to select rows in this table? If not, could you implement this feature 

### ISSUE THREAD

**Issue by mktitov** [tannerlinsley/react-table#161]

**Comment by TacticalCoding** [comment]
See section [Custom Props](https://react-table.js.org/?selectedKind=1.%20Docs&selectedStory=Readme&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel) in the documentation.

You should be able to add an onClick handler to `customTrProps` or `customTdProps` to handle the selection.

**Comment by mikedevita** [comment]
@tannerlinsley is there a method for tracking individual cell selection? I didn't see it in the doc's.

**Comment by tannerlinsley** [comment]
Not built in. Its a fairly opinionated process. Best way is to just roll
your own with custom renders and your own flavor of state management

**Comment by mikedevita** [comment]
so there's not even a `getCellProps()`?

**Comment by tannerlinsley** [comment]
No, the state in table acts much like traditional local component state does.  So something like this is perfectly acceptable:

```javascript
export default MyComponent extends React.Component {
  constructor () {
    super()
    this.state = {
      checked: {}
    }
  }
  render () {
    return (
      <ReactTable
        data={data}
        columns={[{
          id: 'checkbox',
          render: ({ index }) => (
            <div>
              <input
                type='checkbox'
                checked={checked[index]}
                onClick={e => this.setState(state => ({
                  checked: {
                    ...state.checked,
                    index: !state.checked[index]
                  }
                }))}
              />
            </div>
          )
        }]}
      />
    )
  }
}
```

**Comment by spacedarcy** [comment]
I create a column just for checkboxes with a custom renderer and unshift it to the existing array of columns.

**Comment by tannerlinsley** [comment]
That's perfect 👌

**Comment by tannerlinsley** [comment]
If you would like to discuss the implementation more, I suggest joining the slack organization (badge/link in readme) :)
