### ISSUE TITLE
Cannot set `cell.className` v7

### ISSUE THREAD

**Issue by tsujp** [tannerlinsley/react-table#1612]
**Describe the bug**

Cannot set `cell.className` in strict mode v7 in `Cell:`.

**To Reproduce**

```javascript
const columns = [
  {
    Header: 'test',
    id: 'testid',
    accessor: 'test_property',
    Cell: ({ cell }: any) => {
      cell.className = '123'
      return <>{cell.value}</>
    }
  }
]
```

**Expected behavior**

The rendered `td` now has className of `123`.

**Desktop (please complete the following information):**

- OS macOS Mojave
- Browser Firefox
- Version 70

-------------

## Edit:

I managed to force the className on the props but it still doesn't apply the class. I suppose for now I have to use extra DOM elements just to style the `td`s I need.

```javascript
const columns = [
  {
    Header: 'test',
    id: 'testid',
    accessor: 'test_property',
    Cell: ({ cell }: any) => {
      const test: {} = cell.getCellProps()
      cell.getCellProps = () => {
        return {
          ...test,
          className: '123'
        }
      }
      console.log(cell.getCellProps())
      return <>{cell.value}</>
    }
  }
]
```

The console log of `cell.getCellProps()`
```
Object { key: "cell_0_testid", style: {}, className: "123" }
```

The rendered DOM object, without `class="123"`
```
<td class="">whatever</td>
```

**Comment by tannerlinsley** [comment]
It's easy to forget with a hook that you control the rendering of your markup 100%. Here is a codesandbox that shows you how to build this into your renderer in a few lines:

https://codesandbox.io/s/tannerlinsleyreact-table-basic-evgp3

**Comment by cyberwombat** [comment]
@tannerlinsley Would love to see this stuff in the docs. Been at it for hours looking for what the docs say is called the `getCellProps hook`.   

_"You can use the getCellProps hook to extend its functionality."_... I read that as: use a hook called `getCellProps` to extend the functionality of the `getCellProps` function.

 The sandbox clarifies it all.

**Comment by taochu** [comment]
@tannerlinsley I'm getting a `Property 'className' does not exist on type 'ColumnInstance<any>'.` at `cell.column.className` when following the sandbox. Any idea on why that's happening?

**Comment by z1m1n** [comment]
> @tannerlinsley I'm getting a `Property 'className' does not exist on type 'ColumnInstance<any>'.` at `cell.column.className` when following the sandbox. Any idea on why that's happening?

`className: (cell.column as any).className `

**Comment by princeup62** [comment]
I had all above suggestion but still I am unable to apply class on specific column

**Comment by luffespresso** [comment]
I'm still getting this issue as well, the only fix has been @z1m1n's workaround but it required ESlint rules to be disabled for the line to get it through.

Anyone found an actual fix?

**Comment by exactchange** [comment]
I am able to get a `className` into children of either a `<th>` or `<td>` cell by wrapping the value in the raw HTML/CSS that I need:

```
  {
    Header: <span className="my-class-name">Column Heading 1</span>,
    accessor: "column-heading-1",
  }
```

And in the case that I need it on the outer `<th>` or `<td>` directly, I can add it to the `getCellProps` method in the render, like this:

```
  <td {...cell.getCellProps({ className: 'my-class-name' })} />
```

Hope this helps!

**Comment by Cdvalencia** [comment]
create a new simple component cell.js -> CellComponent <CellComponent cell={cell.render('Cell')}/ >... inside that componen you use the next variable to get your value cell. -> this.props.cell.props.value...... finally create simple condition className= {(this.props.cell.props.value==true)?"your-class-in-true":"your-class-in-false")}

**Comment by ncoughlin** [comment]
Here is a handy way to fine tune cell classes:

In your render section you have this:

```
{row.cells.map((cell) => {
  return (
    <td {...cell.getCellProps(combinedCellProps)}>
      {cell.render("Cell")}
    </td>
   );
})}
```

Which combinedCellProps there is referencing this:

```
  const combinedCellProps = (defaultCellProps, { cell }) => {
      defaultCellProps,
      generateCellClasses(cell),
    ]);
    return [defaultCellProps, generateCellClasses(cell)];
  };
```

which the generateCellClasses function can look like this

```
const generateCellClasses = (cell) => {
    // default classes go here
    let classes = ["truncate"];

    switch (cell.align) {
      case "right":
        classes.push("align-right");
        break;
      case "left":
        classes.push("align-left");
        break;
      case "center":
        classes.push("align-center");
        break;
      default:
        classes.push("align-right");
    }

    // color ACOS data
    if (cell.column.Header === "ACOS") {
      let color =
        cell.value <= 0.2
          ? "very-good"
          : cell.value <= 0.4
          ? "neutral"
          : cell.value <= 0.5
          ? "bad"
          : "very-bad";

      classes.push(color);
    }

    // color CR data
    if (cell.column.Header === "CR") {
      let color =
        cell.value <= 0.1
          ? "very-bad"
          : cell.value <= 0.15
          ? "bad"
          : cell.value <= 0.25
          ? "neutral"
          : "very-good";

      classes.push(color);
    }

    return { class: classes.join(" ") };
  };
```

In this way not only can you add custom cell names, you can dynamically change them depending on the values of the cell or column.
