### ISSUE TITLE
Column Doesn't Fill Width if Unset and Expander is True

### ISSUE THREAD

**Issue by paulnovacovici** [tannerlinsley/react-table#1614]
For the following situation the max-width of the column is 35px if width isn't set.
```
columns = [
 Header: 'Name',
 expander: true,
]
```
Although when there is no expander then the width of the column fills the rest of react-table.
```
columns = [
 Header: 'Name',
 expander: false
]
```

Is this a design decision or a bug? I don't understand why having an expander would have a different behavior.

**Comment by tannerlinsley** [comment]
Expander is a behavior from v6, which is no longer supported. Please ask this question in our support forum intead, please: https://spectrum.chat/react-table
