### ISSUE TITLE
How can i add labels to the filter fields

### ISSUE THREAD

**Issue by narechowdary** [tannerlinsley/react-table#1617]
# Using v6?

using V6 latest

**Describe the bug**
I want to add label to the filter field.

**To Reproduce**
filter boxes doesn't have any label to get react table accessible. 

**Screenshots**
![image](https://user-images.githubusercontent.com/17018025/67702002-fa2d9e80-f97e-11e9-825f-956814fd2930.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tannerlinsley** [comment]
Since this is a v6 question, please ask it in the support forum: https://spectrum.chat/react-table
