### ISSUE TITLE
minWidth/ maxWidth not working in 7.0.0-beta.12

### ISSUE THREAD

**Issue by PaulRBerg** [tannerlinsley/react-table#1620]
**Describe the bug**
Setting `minWidth` or `maxWidth` on columns doesn't work.

**To Reproduce**

1. Go to this [CodeSandbox](https://codesandbox.io/s/romantic-wildflower-v3cru)
2. Open the `Table.js` file to see the `maxWidth` property set
3. Open the browser inspector and see how cells in the `firstName` column don't have `max-width: 16px`

**Expected behavior**
The `max-width: 16px` property should be set on the cells in the `firstName` column. I made sure that I'm using non-table-element layouts (flexbox).

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Brave (powered by Chromium)
- Version: 0.70.121 Chromium: 78.0.3904.70

**Comment by PaulRBerg** [comment]
After a bit of investigation, I noticed that `maxWidth` is put in `cell.column.maxWidth`, but the `style` property of the object returned by `getCellProps()` does not include it. Could this be the cause of the bug?

**Comment by tannerlinsley** [comment]
You're not using a width-supported layout hook. Try using one of the following layout hooks:

- `useBlockLayout`
- `useAbsoluteLayout`

**Comment by tannerlinsley** [comment]
Please refer to this example for more on how to do this: https://codesandbox.io/s/tannerlinsleyreact-table-column-resizing-c8hxr

**Comment by PaulRBerg** [comment]
Thanks @tannerlinsley!

**Comment by coreybruyere** [comment]
@tannerlinsley @PaulRBerg 

Pulled in the `useBlockLayout` hook, how do I specify a `width` or `maxWidth` on headers?

https://codesandbox.io/s/tannerlinsleyreact-table-basic-ts09s

**Comment by bmcgary** [comment]
I also ran into this. Perhaps something in the docs under min/maxWidth stating the two layouts that this applies to would help posterity?
