### ISSUE TITLE
useRowSelect with reducer supplied causes infinite loops

### ISSUE THREAD

**Issue by eenagy** [tannerlinsley/react-table#1622]
Hello there!

I'm facing issues with the provided row selection example when I supply a reducer to it. 
I'm using the example https://github.com/tannerlinsley/react-table/tree/master/examples/row-selection with the following reducer
```
  const defaultReducer = (old, newState) => {
    return newState;
  }
```
Running this code and trying to check a checkbox will result in freezing, checkboxes are not updated. And the browser freezes. Removing the reducer will not result in a freeze.
As I hardly modified the code, this looks like a possible bug.
When adding some logging to the reducer the `pageChanged` action called indefinitely.

**Version**: "react-table": "next" <== latest upstream
**Environment**: Tested in firefox browser, 70.0 (64-bit)(latest version), Platform: Ubuntu
**Steps to reproduce** 
```
  const defaultReducer = (old, newState) => {
    return newState;
  }
  // Use the state and functions returned from useTable to build your UI
  const {
    getTableProps,
    getTableBodyProps,
    headerGroups,
    rows,
    prepareRow,
    selectedFlatRows,
    state: { selectedRowPaths },
  } = useTable(
    {
      columns,
      data,
      reducer: defaultReducer,
    },
    useRowSelect
  )
```
Or see in the [codesandbox](https://codesandbox.io/s/tannerlinsleyreact-table-row-selection-5o45b?fontsize=14) for full example forked from the provided example.

**Comment by tannerlinsley** [comment]
The `reducer` function must be stable or memoized. It doesn't say this in the docs, but it will in a minute ;)

Move the function to the root scope or memoize it and it should work just fine.

**Comment by ronaiza-cardoso** [comment]
There's some example sandbox that works with reducer?
