### ISSUE TITLE
In v7, when using filters, filteredRows and filteredFlatRows seem to becoming in non-memoized causing unnecessary rerenders

### ISSUE THREAD

**Issue by ctoppel** [tannerlinsley/react-table#1623]

**Comment by tannerlinsley** [comment]
As far as I can tell, they should be stable:

https://github.com/tannerlinsley/react-table/blob/4842bc061d3421f297c6ab30809d17ba6bd7c642/src/plugin-hooks/useFilters.js#L135

Any more info on this?

**Comment by ctoppel** [comment]
I am using whyDidYouRender to check if there are any unnecessary renders, and after making sure everything was optimized, filteredRow and filteredFlatRows were said to be actual object and not references to them causing unnecessary rerenders. I haven’t check in a few weeks, so it may be that you have done some fixes to make sure they were memoized, but I can check again when I get a chance.

**Comment by tannerlinsley** [comment]
Sounds good. Honestly I may have fixed them before I was out of town and have forgotten. Let’s refresh this issue lol

Tanner Linsley

**Comment by tannerlinsley** [comment]
Going to close this for now, as I have not been able to reproduce it.
