### ISSUE TITLE
[useSort] initial state sorting with accessor as function is not working

### ISSUE THREAD

**Issue by gargroh** [tannerlinsley/react-table#1624]
# V7

Thanks for the awesome `react-table v7`, it is very cool e.s. in terms of extensibility.

Coming to the issue - Sorting config provided through `initialState` does not work for column with `accessor` as function.

Replicated at - https://codesandbox.io/s/initial-sorting-with-accessor-not-working-5qhnl

If `accessor: 'firstName'` is used then 

```
sortBy: [
            {
              id: 'firstName',
              desc: false
            }
          ]
```

is honored, with `accessor: row => row.firstName` it is not honored. 

Let me know in case i am missing something.

**Comment by tannerlinsley** [comment]
Accessor functions columns require an ID property. Use that instead.

Tanner Linsley

**Comment by gargroh** [comment]
Yeah, read in documentation, that we need to provide `id` if `accessor` is fn, don't know how i missed :(

Thanks for the information.
