### ISSUE TITLE
Server controlled data pattern broken by merging useTableState and useTable

### ISSUE THREAD

**Issue by ggascoigne** [tannerlinsley/react-table#1625]
I have a case where the data is retrieved remotely, with the data paginated, filtered, and sorted as part of that api call.  Previously I could retrieve the sort order and the filter settings before retrieving the data and passing it on to the useTable call.

Now, the data is required before I can find out what parameters are required to retrieve it.

I'm really not sure how to address this.  Merging these two functions has made something that used to be rather trivial, and to my eye, made it impossible.  Sadly, the controlled examples are too trivial to really highlight the problem - try changing makeData to more closely mimic a real api and take page number, page size, sort order, and filter values, then you'll see what I mean.

I hate to suggest rolling back to separating these two functions again, but I'm a bit stumped.

How would you suggest addressing this issue?

**Comment by ggascoigne** [comment]
@tannerlinsley Any suggestions here?  I feel that I must be missing something pretty fundamental here.

**Comment by tannerlinsley** [comment]
Just got back from vacation. I'll take a peek at this.

**Comment by tannerlinsley** [comment]
I think I'm also missing something in your issue. Could you elaborate with an example that shows the issue you're having?

**Comment by ggascoigne** [comment]
OK, I take it back. It's not broken, it's just different.  Many things needed to be converted from simple state accessors to functions that get passed the instance later - functionally it's probably much the same, it's just somewhat more verbose code.

It was certainly convenient to be able to reference state before calling `useTable`, but in the end it does work like this.
