### ISSUE TITLE
Sonar scans mark prepareRow as a bug (Remove this use of the output from "prepareRow"; "prepareRow" doesn't return anything.)

### ISSUE THREAD

**Issue by Joshhw** [tannerlinsley/react-table#1626]
Version: 7.0.0-beta.12

**To Reproduce**

1. Scan basic example on Sonar
2. Click on report

**Screenshots**
![screen cap](https://user-images.githubusercontent.com/10734399/67985070-69fd8c80-fbfe-11e9-9b28-50e36fd2581b.png)

**Comment by ggascoigne** [comment]
I think that this was fixed as part of https://github.com/tannerlinsley/react-table/pull/1631

**Comment by tannerlinsley** [comment]
Indeed. The function does return void, but has side-effects on the row required to lazy prep it for rendering.
