### ISSUE TITLE
Odd behavior with sorted data state and `sorting` prop

### ISSUE THREAD

**Issue by mannieschumpert** [tannerlinsley/react-table#163]
## Problem Description
Modifying the `sorting` prop via a container state does not have the expected results. As others have noted (https://github.com/tannerlinsley/react-table/issues/145), the header class names update one click before the _data_ does.

In the following example, I have included a simple element to modify the container state, which gets passed to ReactTable. (Note that I am preventing multisort by only ever passing one sort object.) When this element is first clicked, the 'name' column header class is changed and highlights as expected, but the data does not sort. After an _additional_ click of the "Sort" element, the data then sorts. In a different experiment, if logic was built into an `onSortingChange` handler to toggle the sort direction, the header's sort direction class would become the _inverse_ of the data's actual sort direction.

```javascript
return (
    <div>
      <p onClick={()=>this.setState({sort:{id:'name'}})}>Sort</p>
      <ReactTable
        data={data}
        columns={columns}
        defaultPageSize={10}
        getTrProps={this.setRowProps}
        getTdProps={this.setCellProps}
        sorting={[this.state.sort]}
      />
    </div>
)
```

## Steps to Reproduce
1. Add `sorting` prop that is set via container state
2. Modify container state via some action
3. Header of target column changes class immediately, but data does not re-sort until an additional action

## System Information
**Chrome 56.0.2924.87**
**Node Version: v6.10.1**
**OS Version: Mac OS Sierra 10.12.3**
**NPM Version: 3.10.10**

**Comment by mannieschumpert** [comment]
I looked into the `sortColumn` method in the source code. If an `onSortingChange` prop is included, the function returns that passed function immediately. However, when that prop is not included, there are clearly some additional functions triggered by default, e.g. `setStateWithData`. So, there seem to be some critical methods not being triggered if a user passes the `onSortingChange` handler.

Of note: everything works as expected if no `sorting` or `onSortingChange` props are used.

**Comment by tannerlinsley** [comment]
Good observation. I'll investigate our options here. It may be as simple as
making shot that changes to sorting props are properly triggering a sorting
model update.

**Comment by abbotteric** [comment]
I believe this is an issue with the order the arguments are being passed in in "getResolvedState." The way it is currently, the existing props take precedence over the passed in new state. I submitted a PR #166 that fixes the issue for me.

**Comment by tjphopkins** [comment]
Unfortunately the issue still seems to exist when the onSortingChange prop is used.

**Comment by karanattriCaw** [comment]
Hi,
I was having the same issue as i am doing a fully controlled sorting, I was 1 sort behind, for that I just removed all the props having sorting. This thing helped me. 

**Error Code** 
import {Grid} from "@material-ui/core";
import React, {useState, useEffect} from "react";
import ReactTable from "react-table-6";
import "react-table-6/react-table.css";
const DataGrid = (props) => {
  // console.log("Data Grid Props", props);
  const [grid, setState] = useState({
    entities: [],
    columns: [],
    searchInput: null,
    pages: 0,
    pageSize: 10,
  });
  let data = [];

  if (props && props.entities && props.entities.length !== grid.entities.length) {
    setState({...grid, entities: [...props.entities], pages: props.pages});
  }
  const [columnId, setColumnId] = useState({});
  // prp for local props | props for component level props
  const onFetchDataChange = (prp) => {
    if (prp.pageSize && grid.entities.length !== 0) {
      let skip = 0;
      if (prp.page > 0) skip = parseInt(prp.pageSize * prp.page);
      props.onQueries({
        searchInput: grid.searchInput,
        pageSize: prp.pageSize,
        skip,
      });
      setState({...grid, pageSize: prp.pageSize});
    }
  };
  useEffect(() => {
    if (
      props.sortingColumn &&
      (props.sortingColumn.id !== columnId.id ||
        props.sortingColumn.desc !== columnId.desc)
    ) {
      setColumnId(props.sortingColumn);
      onSortHandler();
    }
  }, [props.sortingColumn]);

  const onSortHandler = () => {
    const {id, desc} = props.sortingColumn;
    let sortedData = grid.entities.sort((a, b) => {
      if (
        (a[id] !== null || a[id] !== undefined) &&
        typeof a[id] === "string" &&
        (b[id] !== null || b[id] !== undefined) &&
        typeof b[id] === "string"
      ) {
        if (a[id].toLowerCase() > b[id].toLowerCase() && desc === false) {
          return 1;
        } else {
          return -1;
        }
      } else if (
        (a[id] !== null || a[id] !== undefined) &&
        (b[id] !== null || b[id] !== undefined)
      ) {
        if (a[id] > b[id] && desc === false) {
          return 1;
        } else {
          return -1;
        }
      }
    });
    setState({...grid, entities: sortedData});
  };
  const {filterAndSort} = props;

  // const NullComponent = () => (props.noDataText ? props.noDataText : `No Data Found `);
  return (
    <Grid item xs={12} md={12} lg={12} className="DataGridMAIN">
      {grid.entities ? (
        <ReactTable
          minRows={1}
          sortable={filterAndSort ? filterAndSort : false}
          loading={props.loading}
          data={grid.entities}
          columns={props.DataGridColumns}
          showPaginationBottom={props.showPaginationBottom ?? true}
          defaultPageSize={10}
          manual
          onFetchData={(props) => onFetchDataChange(props)} // For Pagination
          onSortedChange={(props) => onSortHandler(props.sortingColumn)} // For Sorting
          pages={grid.pages} // Display the total number of pages
          getTdProps={(state, rowInfo, column, instance) => {
            return {
              onClick: (e, handleOriginal) => {
                if (rowInfo?.original)
                  props.rowClickHandler({original: rowInfo.original, column});
                if (handleOriginal) {
                  handleOriginal();
                }
              },
              // onDoubleClick:()=>{}
            };
          }}
        />
      ) : (
        // TODO PROPS HERE
        <h5>No Data Found</h5>
      )}
    </Grid>
  );
};
export default DataGrid;


**Working code**
import {Grid} from "@material-ui/core";
import React, {useState, useEffect} from "react";
import ReactTable from "react-table-6";
import "react-table-6/react-table.css";
const DataGrid = (props) => {
  // console.log("Data Grid Props", props);
  const [grid, setState] = useState({
    entities: [],
    columns: [],
    searchInput: null,
    pages: 0,
    pageSize: 10,
  });
  let data = [];

  if (props && props.entities && props.entities.length !== grid.entities.length) {
    setState({...grid, entities: [...props.entities], pages: props.pages});
  }
  const [columnId, setColumnId] = useState({});
  // prp for local props | props for component level props
  const onFetchDataChange = (prp) => {
    if (prp.pageSize && grid.entities.length !== 0) {
      let skip = 0;
      if (prp.page > 0) skip = parseInt(prp.pageSize * prp.page);
      props.onQueries({
        searchInput: grid.searchInput,
        pageSize: prp.pageSize,
        skip,
      });
      setState({...grid, pageSize: prp.pageSize});
    }
  };
  useEffect(() => {
    if (
      props.sortingColumn &&
      (props.sortingColumn.id !== columnId.id ||
        props.sortingColumn.desc !== columnId.desc)
    ) {
      setColumnId(props.sortingColumn);
      onSortHandler();
    }
  }, [props.sortingColumn]);

  const onSortHandler = () => {
    const {id, desc} = props.sortingColumn;
    let sortedData = grid.entities.sort((a, b) => {
      if (
        (a[id] !== null || a[id] !== undefined) &&
        typeof a[id] === "string" &&
        (b[id] !== null || b[id] !== undefined) &&
        typeof b[id] === "string"
      ) {
        if (a[id].toLowerCase() > b[id].toLowerCase() && desc === false) {
          return 1;
        } else {
          return -1;
        }
      } else if (
        (a[id] !== null || a[id] !== undefined) &&
        (b[id] !== null || b[id] !== undefined)
      ) {
        if (a[id] > b[id] && desc === false) {
          return 1;
        } else {
          return -1;
        }
      }
    });
    setState({...grid, entities: sortedData});
  };

  // const NullComponent = () => (props.noDataText ? props.noDataText : `No Data Found `);
  return (
    <Grid item xs={12} md={12} lg={12} className="DataGridMAIN">
      {grid.entities ? (
        <ReactTable
          minRows={1}
          loading={props.loading}
          data={grid.entities}
          columns={props.DataGridColumns}
          showPaginationBottom={props.showPaginationBottom ?? true}
          defaultPageSize={10}
          manual
          onFetchData={(props) => onFetchDataChange(props)} // For Pagination
          pages={grid.pages} // Display the total number of pages
          getTdProps={(state, rowInfo, column, instance) => {
            return {
              onClick: (e, handleOriginal) => {
                if (rowInfo?.original)
                  props.rowClickHandler({original: rowInfo.original, column});
                if (handleOriginal) {
                  handleOriginal();
                }
              },
              // onDoubleClick:()=>{}
            };
          }}
        />
      ) : (
        // TODO PROPS HERE
        <h5>No Data Found</h5>
      )}
    </Grid>
  );
};
export default DataGrid;
