### ISSUE TITLE
Don't use accessor as Keys.

### ISSUE THREAD

**Issue by antoniobologna** [tannerlinsley/react-table#1630]
**Describe the bug**
v.7.0.0-alpha.36

**Warning logs**

```
backend.js:6 Warning: Encountered two children with the same key, `cell_1_account`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in tr (created by Table)
    in tbody (created by Table)
    in table (created by Table)
    in Table (created by Users)
    in div (created by Users)
    ...
```

It's not really a bug but just something that we should have control or at least have a way to not have these duplicate warnings whenever I'm using columns with the same accessor.

My use case for this is that we use JSON fields returned for some columns, and even though this works fine, but because I need to span the column into more than one (i.e. account.first, account.last, ...), I get warning about duplicate keys.

A quick solution that I did was to expand these fields in the array, making them unique keys, which is totally fine, just that it would be better not to depend on accessor as unique key values.

**To Reproduce**

Add more than one column with the same accessor name, i.e. 
```js
      {
        Cell: row => (
          <EditingJSONCell
            row={row}
            updateFunc={updateUser}
          />
        ),
        Header: 'first',
        accessor: 'account',
      },
      {
        Cell: row => (
          <EditingJSONCell
            row={row}
            updateFunc={updateUser}
          />
        ),
        Header: 'last',
        accessor: 'account',
      },
```

**Expected behavior**
Not use accessor as key values.

**Desktop (please complete the following information):**
N/A

**Comment by kizu** [comment]
I think we can use `id` for the keys. Basically. If the `id` is not present on a column, then the `accessor` becomes an `id`, so adding unique ids by ourselves solves this (at least, I managed to solve this issue for myself this way).

**Comment by antoniobologna** [comment]
sounds good to me :) id is good. Thank you.

**Comment by binoyskumar92** [comment]
![image](https://user-images.githubusercontent.com/32806163/99819625-4eb93400-2b15-11eb-800f-1e9dbeaae75a.png)
Just add a new key called _**id**_ in your column definition.

**Comment by HuynhVanThuy** [comment]
> ![image](https://user-images.githubusercontent.com/32806163/99819779-81632c80-2b15-11eb-99a3-c30f1e8e23ac.png)
> 
> Just add a new key called _**id**_ in your column definition.

This is correct
