### ISSUE TITLE
Extra sorting action after resizing column.

### ISSUE THREAD

**Issue by cXiaof** [tannerlinsley/react-table#1638]
### Describe the bug
When using both **useResizeColumns** and **useSortBy** like Examples in Documentation, Drag 'resizer' will trigger Header click events and do sort every time. Bubbling?

### Expected behavior
Drag 'resizer' to resize column, NO SORT.

### Codesandbox!
[![Edit tannerlinsley/react-table: column-resizing](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tannerlinsleyreact-table-column-resizing-o8qlu?fontsize=14)

**Comment by gargroh** [comment]
You can solve this problem by taking different elements for `header content` on which you apply `sort props` and a sibling to it which applies `resize props`, something like https://codesandbox.io/s/tannerlinsleyreact-table-column-resizing-jel1b can help you.

**Comment by tannerlinsley** [comment]
☝️ Well said. Apply the props to different elements.

**Comment by thexpand** [comment]
@tannerlinsley Maybe this should be mentioned in the docs, but I'm not sure where exactly. I had to search the issues to find this information.

**Comment by tai101568** [comment]
I did not see resize working in this link: https://codesandbox.io/s/tannerlinsleyreact-table-column-resizing-jel1b

**Comment by tai101568** [comment]
but it is working on my component. Thanks @gargroh

**Comment by jl-rojas** [comment]
I just put the sort props inside a DIV tag (inside my TH tag), just like this:
```
<th {...column.getHeaderProps()}>
   <div
       {...column.getSortByToggleProps()}



 // My code and resizer div




   </div>
`</th>
```
and that worked for me
