### ISSUE TITLE
Embedding 'value' in a Link for a column render JSX function

### ISSUE THREAD

**Issue by aikidoshi** [tannerlinsley/react-table#164]
## Problem Description
For each ID value in my table I'm trying to construct a Link but am not sure of the correct syntax.
I've tried many variations using back ticks etc but the expression does not evaluate the {value} into the Link:

## Code Snippet(s)

const columns = [
  {
    header: 'Batch ID',
    accessor: 'ID',
    render: ({value}) => <span><Link to="/batch/{value}">{value}</Link></span>
  },
...
]

NB: Half of what I've typed is being hidden in this editor, not sure how to get around that :-)

## Steps to Reproduce
1. I have an array of data with the first column called ID. 
2. Setup a basic table with the column defined as shown above
3. The table works perfectly (great work BTW), the link LOOKS good but the ID is not evaluated properly

## System Information
**Chrome:**
**Node Version: 7.4.0**
**OS Version: Windows 8**
**NPM Version: 4.0.5**
**Yarn Version: 0.21.3**

**Comment by mannieschumpert** [comment]
With the `render` method, you get all the props of the item, not just the value. So you'd access something like this:
``render: props => <Link to={`/baseurl/${props.ID}`}>Link title</Link>``

**Comment by TacticalCoding** [comment]
What you're trying to do should work.
```
render: ({value}) => (<Link to=`/somewhere/${value}`/>)
```

If value is still not correct you can help debug by printing out what the render method is being passed:
```
render: (props) => {console.log(props); return props.value;}
```
Tip: Use the markdown code syntax for your code sections to prevent them from being hidden. Surround your code with three backticks (```) e.g.

\```
code here
\```

**Comment by aikidoshi** [comment]
Thanks all! The solution proposed does indeed work when expressed thusly:
```
const columns = [
    {
        header: 'Batch ID',
        accessor: 'ID',
        render: ({value}) => (<span><Link to={`/batch/${value}`}>{value}</Link></span>)
    },
    {
```
Change ANYTHING and it breaks horribly :-) Hope this helps others with a similar plight.
I really appreciated the rapid response, many thanks. Case closed.
