### ISSUE TITLE
Examples is not running. 

### ISSUE THREAD

**Issue by Kalinkin92** [tannerlinsley/react-table#1641]
I'm trying to run basic example from your repo 
![image](https://user-images.githubusercontent.com/9201061/68924586-34c27400-0792-11ea-9d30-f54269d8de1b.png)

It falls on the **useTable** call

**Comment by gargroh** [comment]
Provide a minimal replication of this error on codesandbox

**Comment by tannerlinsley** [comment]
Yes, please provide a reproducible example in a new issue. Thanks!
