### ISSUE TITLE
v7 Manual Sort

### ISSUE THREAD

**Issue by abominab** [tannerlinsley/react-table#1642]
v7

**Describe the bug**
When using the manual sort option, there doesn't appear to be a way to tie into sort events happening. I looked through the source  and examples and can't see anyway that tells me sort actions happened and that I need to handle them. 
I don't understand why an option for manual is even there if there is nothing to help aid it.

**Expected behavior**
I would imagine something like onSort or similar to be an option to pass into the table.

**Desktop (please complete the following information):**
- OS: macOS Mojave 10.14.6 (18G87)
- Browser: Chrome 77.0.3865.120 (Official Build) (64-bit)

**Comment by tannerlinsley** [comment]
Regardless if using manual mode, the internal state of the table is still updated and used. So, if you want to listen to changes in sorting, you can use a `useEffect`:

```js
const { state: { sortBy }} = useTable(...)

React.useEffect(() => {
  // `sortBy` changed
}, [sortBy])
```

**Comment by abominab** [comment]
I was trying that, but my effect was getting called twice every time I clicked on a column header. That made me think I wasn't using it correctly.
Thanks for the reply!
