### ISSUE TITLE
How to put a button and multiple attributes in accessors in columns? Please help ASAP

### ISSUE THREAD

**Issue by isubhkarm** [tannerlinsley/react-table#1643]
And a very big THANK YOU! to Tanner Linsley for such a great library. My heart goes to you man, you saved my ass.

Sorry for posting this here.

**Comment by gargroh** [comment]
You can use custom cell render for this case using `Cell` method on `column` config...for exact signature details check https://github.com/tannerlinsley/react-table/blob/master/docs/api.md#usetable at `Cell: Function | React.Component => JSX` section

**Comment by isubhkarm** [comment]
@gargroh Thank you brother
