### ISSUE TITLE
React table v7 plugin hooks options not working in Typescript 

### ISSUE THREAD

**Issue by baskar383** [tannerlinsley/react-table#1647]
# Using v7?
Currently, we are using  ```"react-table": "^7.0.0-beta.12"```

**Describe the bug**
When I trying to paginate the rows manually, Bypassing the UsePaginationOptions of ```manualPagination``` by true in the ```useTable``` options, It's thrown a below error  in Typescript(.tsx) 
```
'manualPagination' does not exist in type 'TableOptions<object>

```
Note: The above code is written in .tsx file. 

**Expected behavior**
All the Plugin Hooks options need to work in Typescript(.tsx) 

**Codesandbox!**
The above issues have been reproduced in the code sandbox (https://codesandbox.io/s/tannerlinsleyreact-table-pagination-controlled-mf98b).  Kindly check and update 
**Screenshots**
Kindly refer the below screenshots, 
![screenshot-codesandbox io-2019 11](https://user-images.githubusercontent.com/17172610/69209103-066edb00-0b7c-11ea-9556-a72efd4cad97.png)

**Desktop:**
- OS: Ubuntu (64 bit)
- Browser: chrome(78.0.3904.97)

**Comment by androsj** [comment]
@baskar383 Make sure you have done this: https://github.com/tannerlinsley/react-table/blob/master/TYPESCRIPT.md

Same thing happened to me at first.

**Comment by baskar383** [comment]
cc @androsj 
Thnx for help us,
