### ISSUE TITLE
[v7] Universal customizable table

### ISSUE THREAD

**Issue by ivanov-v** [tannerlinsley/react-table#1649]
I want to implement a universal component of a table in which there will be a settings button. When pressed, a popup should open, in which there will be a list of columns. Columns can be sorted (DnD) and show / hide. These settings must be written to local storage.

For sorting, I want to use setColumnOrder, but column visibility is configured outside the table in columns, judging by the current api V7.
How do I switch column visibility dynamically? Where to properly store all this configuration logic?

<img width="370" alt="Снимок экрана 2019-11-20 в 16 26 01" src="https://user-images.githubusercontent.com/13759065/69243031-338ab000-0bb3-11ea-8205-f0460c7f4f1e.png">

**Comment by tannerlinsley** [comment]
This appears to be an implementation question. Please use https://spectrum.chat/react-table, thanks!
