### ISSUE TITLE
CodeSandbox Examples does not open

### ISSUE THREAD

**Issue by andyahn91** [tannerlinsley/react-table#1653]
I cannot access to the examples sandbox that's on: https://github.com/tannerlinsley/react-table/tree/v6

For example, I tried to check this example ([custom-expander-position](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/archives/v6-examples/react-table-custom-expander-position)), and this is what I see.
![CodeSandbox](https://user-images.githubusercontent.com/38708867/69393768-f09e0a80-0c8e-11ea-97f2-4429a9a560a6.png)

This happens to all examples of version 6.

**Comment by tannerlinsley** [comment]
The v6 readme and example links have been updated. Try again!

**Comment by andyahn91** [comment]
Now it works! Thanks!
