### ISSUE TITLE
Codesandbox is down

### ISSUE THREAD

**Issue by benlieb** [tannerlinsley/react-table#1655]
![image](https://user-images.githubusercontent.com/634562/69466346-9f4a5580-0d38-11ea-9f9b-b3b09e23b40a.png)

**Comment by andyahn91** [comment]
It works now.
https://github.com/tannerlinsley/react-table/issues/1653

**Comment by SVVijay1205** [comment]
All sample links are still broken with same error

**Comment by tannerlinsley** [comment]
This was fixed in the new README for the v6 branch. v6 examples were removed from the master branch and placed on the v6 branch for safe keeping, thus the codesandbox links changed.
