### ISSUE TITLE
upgrading to react 16.12.0 breaks Group By

### ISSUE THREAD

**Issue by ggascoigne** [tannerlinsley/react-table#1657]
I upgraded the kitchen sink example to react-table beta.14 (that worked fine), then I upgraded react and react-dom to 16.12.0.

The app starts up just fine, but clicking on the groupBy icon (the fist) for First Name, causes the app to hang and this message to be displayed in the console.

```
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
    in Table (at App.js:622)
    in div (created by Context.Consumer)
    in StyledComponent (created by App__Styles)
    in App__Styles (at App.js:620)
    in App (at src/index.js:7)
```

The only changes to the app are these package.json changes:

```json
 "dependencies": {
    "match-sorter": "^4.0.1",
    "namor": "^1.1.2",
    "react": "^16.12.0", // <-
    "react-dom": "^16.12.0", // <-
    "react-scripts": "3.0.1",
    "react-table": "^7.0.0-beta.14", // <-
    "styled-components": "^4.3.2"
  },
```

and the associated yarn.lock file.

**Comment by AtomicSimon** [comment]
I'm hitting a similar issue with usePagination

**Comment by FredyC** [comment]
Yea, same here, a combination of pagination and grouping is wild. I tried reproduction in this example sandbox, but strangely enough, just by adding `useGroupBy` to the list, the whole thing crumbles.

https://codesandbox.io/s/tannerlinsleyreact-table-pagination-ezq8r

The only change from [the original](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/pagination) is adding `useGroupBy` on line 67 of App.js, no other change.

**Comment by androsj** [comment]
@ggascoigne I just checked the kitchen example and it's hanging just like you described. That's with beta.14.

I reverted to beta.13 and it starts working again.

**Comment by iamjon** [comment]
Any chance it's related to this?
https://github.com/tannerlinsley/react-table/pull/1610

**Comment by tannerlinsley** [comment]
Likely not. I'll debug this as soon as I can.

**Comment by ggascoigne** [comment]
I'd like to reopen this, the kitchen-sink example still shows the same behavior with beta.15.

**Comment by FredyC** [comment]
Yea, reproduction I posted above also applies to beta.15.

**Comment by iamjon** [comment]
I also noticed it's happening when  useGroupBy, useExpanded are used along with usePagination or useRowSelect

**Comment by androsj** [comment]
Yeah you are right guys. The kitchen sink sandbox still haves that issue... It is quite strange because I was having the same issue on my personal project and it's now gone with beta15. And I've basically replicated most of that example (I'm using all the plugins)

**Comment by androsj** [comment]
Fix is on the way my friends. Row select is also listening to rows.

**Comment by androsj** [comment]
It wasn't affecting me since I'm passing my own deps for rowSelect. New pull request should finally do the trick.

**Comment by FredyC** [comment]
@androsj Perhaps I am misunderstanding something, but how is the rowSelect related to issue with a combination of groupBy and pagination? :)

**Comment by androsj** [comment]
@FredyC The real issue was in both usePagination & useRowSelect.

They both have an effect to reset some state, and as you may know, effects run every time one of the deps changes. Well, they both had `rows` as a dep, and these rows are re-created on every render (unlike `data`), causing the effect to run infinitely (on every render).

**Comment by tannerlinsley** [comment]
I’ve got this fix staged locally along with a bunch of other things. Stay tuned

Tanner Linsley

**Comment by ggascoigne** [comment]
FYI I can confirm that this is fixed for me using beta.19.  Thank you.

**Comment by KatamariJr** [comment]
This fix seems to have been undone at some point, v7.0.0 has this error occur once again. Going back to v7.0.0-beta.19, as suggested in this thread, has proper functionality. In my testing, it seems that v7.0.0-rc.1 is the last tag that works as intended without a 'maximum update depth' error.

**Comment by keebeegee** [comment]
> This fix seems to have been undone at some point, v7.0.0 has this error occur once again.

v7.0.0 is throwing "Maximum update depth exceeded" using react@16.13.1

**Comment by keebeegee** [comment]
FYI: Still issues w/ 7.1.0: 
https://codesandbox.io/s/busy-merkle-58ii6?file=/src/react-table-component.js

**Comment by santamaria7** [comment]
This issue still exist in v7.1.0.
Since i'm using react@16.13.1, I had to rollback to v7.0.0-beta.19.
