### ISSUE TITLE
[v7] Custom aggregate gets wrong input on more than one groups

### ISSUE THREAD

**Issue by FredyC** [tannerlinsley/react-table#1659]
**Describe the bug**
When using custom aggregate and want to group by more than one column, the `aggregate` values are wrapped into another nested array and most importantly already transformed once.

**To Reproduce**

1. Go to https://codesandbox.io/s/tannerlinsleyreact-table-grouping-yhz30
2. Click on "Last Name" grouping icon
3. See output in the console

A relevant piece of code producing the behavior. I used try/catch for convenience only.

```js
aggregate: values => {
  try {
    const uniqueValues = Array.from(new Set(values)).map(v =>
      v.toUpperCase()
    )
    console.log('correct input', values)
    uniqueValues.sort()
    return uniqueValues
  } catch (err) {
    console.log('incorrect input', values)
  }
}
```

**Expected behavior**
The input into `aggregate` should be consistent no matter how much groups is used.

**Screenshots**

![image](https://user-images.githubusercontent.com/1096340/69576900-89a18e00-0fcd-11ea-85fd-987f0afa4565.png)

**Comment by tannerlinsley** [comment]
Please see this example to clear things up :)

https://codesandbox.io/s/tannerlinsleyreact-table-grouping-r0wtb

**Comment by FredyC** [comment]
@tannerlinsley Thanks, that's interesting. It should be probably documented that `aggregate` is getting other arguments.

Anyway, it works well in this contrived example of the upper casing, but what if the transformation is one-way, for example, the value is being localized? Then we need to pick up from `rows` + `original`? That's kinda ugly and would love to see a more consistent approach. It shifts a lot of the leg work to user code.

Would it be too bad to treat arrays differently? I mean do they serve some other purpose? If not it could be normalized on the library side if running into nested aggregations.

**Comment by tannerlinsley** [comment]
They technically could be treated special, though, I’m not fond of adding the additional api and restrictions to accomplish that. Is there something that the API doesn’t allow per se? I’ve added some documentation around the aggregate option. Mind taking a look?

https://github.com/tannerlinsley/react-table/blob/master/docs/api.md

Tanner Linsley
