### ISSUE TITLE
Manual Pagination results in overflow of rows

### ISSUE THREAD

**Issue by mitchhankins01** [tannerlinsley/react-table#1664]
**Describe the bug**
- Number of rows is set to 10
- First 10 rows are loaded server side
- "next" is clicked, which triggers useEffect since it depends on "pageIndex"
- apollo's fetchMore is triggered in useEffect and loads the second page
- the next 10 rows are displayed on the first page, showing an incorrect total of 20 rows

**Expected behavior**
The expectation is for the second page to load with only the second page's rows

**Screenshots**
<img width="1357" alt="Screen Shot 2019-11-26 at 9 47 59 AM" src="https://user-images.githubusercontent.com/25047564/69659247-a45a1e00-1032-11ea-8247-3b19d8adac94.png">
<img width="1358" alt="Screen Shot 2019-11-26 at 9 48 09 AM" src="https://user-images.githubusercontent.com/25047564/69659252-a6bc7800-1032-11ea-8b16-4de2a83b28b2.png">

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS
- Browser [e.g. chrome, safari] Chrome 
- Version [e.g. 22] 78.0.3904.97

**Code**

`
<Paper className={classes.root}>

            <MaterialTable className={classes.table} {...getTableProps()}>
                <TableHead>
                    {headerGroups.map(headerGroup => (
                        <TableRow {...headerGroup.getHeaderGroupProps()} key={headerGroup.id}>
                            {headerGroup.headers.map(column => (
                                // <th {...column.getHeaderProps(column.getSortByToggleProps())}>{column.render('Header')}
                                <TableCell {...column.getHeaderProps()} key={column.id}>{column.render('Header')}
                                    <div>{column.canFilter ? column.render('Filter') : null}</div>
                                </TableCell>
                            ))}
                        </TableRow>
                    ))}
                </TableHead>
                <TableBody {...getTableBodyProps()}>
                    {page.map(
                        (row, i) => {
                            prepareRow(row)
                            return (
                                <TableRow key={row.index} className={classes.tableRow} {...row.getRowProps()} >
                                    {row.cells.map(cell => {
                                        return <TableCell key={cell.value} {...cell.getCellProps()}>{cell.render('Cell')}</TableCell>
                                    })}
                                </TableRow>
                            )
                        }
                    )}
                    {emptyRows > 0 && (
                        <TableRow style={{ height: 53 * emptyRows }}>
                            <TableCell colSpan={6} />
                        </TableRow>
                    )}
                </TableBody>
            </MaterialTable>
            <Grid container
                justify="center"
                alignItems="center"
            >
                <ButtonGroup size='small' className={classes.buttonGroup}>
                    <Button onClick={() => gotoPage(0)} disabled={!canPreviousPage}>First Page</Button>
                    <Button onClick={() => previousPage()} disabled={!canPreviousPage}>Previous</Button>
                    <Button onClick={() => {
                        nextPage()
                    }} disabled={!canNextPage}>Next</Button>
                    <Button onClick={() => gotoPage(pageCount - 1)} disabled={!canNextPage}>Last Page</Button>
                </ButtonGroup>
                <FormControl className={classes.formControl}>
                    <Select
                        value={pageSize}
                        displayEmpty
                        onChange={e => {
                            setPageSize(Number(e.target.value))
                        }}
                    >
                        {[10, 20, 30, 40, 50].map(pageSize => (
                            <MenuItem key={pageSize} value={pageSize}>Show {pageSize}</MenuItem>
                        ))}
                    </Select>
                </FormControl>
            </Grid>
        </Paper>
`

Thanks!

**Comment by tannerlinsley** [comment]
As far as your setup is concerned, it is working "properly", that is, how I would expect it to work. When you "fetch more" in apollo, it appends more results onto the existing array, thus growing the size of the array. What you likely want to do is not "fetch more", but simply fetch a different page of results. If this is not possible with the apollo configuration you have, then I would suggest pruning the list to only the new results. A good example that might help you find your solution will be to imagine and code what will happen when they hit the "previous page" button. Your query will likely need to fetch the page for the previous index only.

I'm sorry I can't help you more without a codesandbox example (which you can absolutely create if you'd like and open a new issue 😄 )

**Comment by tannerlinsley** [comment]
I found more information here: 

https://www.apollographql.com/docs/react/data/pagination/#offset-based

You're likely going to want to use the "offset-based" approach. Let me know if there is anything else I can do.
