### ISSUE TITLE
defaultColumn Header stop working

### ISSUE THREAD

**Issue by gyto23** [tannerlinsley/react-table#1666]
**Bug**
After some updates from several beta version defaultColumn overwrite for the Header just stop working. I am running a `7.0.0-beta.13` version of the react table. Also, at a moment beta.15 has a memory leak that why I rollback to `13th`

**To Reproduce**
```
// THIS PART DOESNT WORK
const CustomHeader = props => {
  console.log(props);
  return <div>Testing Header</div>;
};

const CustomCell = props => {
  console.log(props);
  return <div>Testing Cell</div>;
};

function Table({ columns, data }) {
  // Use the state and functions returned from useTable to build your UI
  const {
    getTableProps,
    getTableBodyProps,
    headerGroups,
    rows,
    prepareRow
  } = useTable({
    columns,
    data,
    defaultColumn: {
      Header: CustomHeader,
      Cell: CustomCell
    }
  });
  return (...)
}

```

**Codesandbox!**
Use [codesandbox](https://codesandbox.io/s/tannerlinsleyreact-table-basic-e2shl?fontsize=14&hidenavigation=1&theme=dark) to reproduce the issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/54277098/69736550-590a4300-10f8-11ea-879b-521e8e84832c.png)

**Comment by tannerlinsley** [comment]
Please upgrade to beta.16. Thanks!

**Comment by gyto23** [comment]
@tannerlinsley looks like its still doesn't work, I am testing on the sandbox with latest `react-table@7.0.0-beta.20`

**Comment by tannerlinsley** [comment]
It's working for me. In your codesandbox, you need to comment out a column def's `Header` option to see the default kick in.
