### ISSUE TITLE
setFilter doesn't filter subRows

### ISSUE THREAD

**Issue by kenjoegolo** [tannerlinsley/react-table#1667]
I'm trying to add a filter functionality on my table that has expandable rows, then the filter is applied only on first level rows, not on subRows.

**Comment by tannerlinsley** [comment]
As far as I know, you should be getting filtered sub rows:

https://github.com/react-tools/react-table/blob/50f2e84929f38f257a198206ded3100f85ad9856/src/plugin-hooks/useFilters.js#L204-L216

Please open a new issue with a codesandbox example demonstrating this problem so we can better help you. Thanks!
