### ISSUE TITLE
Tooltip for Table

### ISSUE THREAD

**Issue by PavanKumarHRao** [tannerlinsley/react-table#1668]
Hello Everyone,I am using reactstrap,which has its ownTooltip.I used that tooltip and my problem is its position which is not near the cell,Instead it sits on top corner of the screen.Does anyone have solution to this?Please help.

**Comment by ivanov-v** [comment]
> Hello Everyone,I am using reactstrap,which has its ownTooltip.I used that tooltip and my problem is its position which is not near the cell,Instead it sits on top corner of the screen.Does anyone have solution to this?Please help.

Show an example. It’s not clear.

**Comment by PavanKumarHRao** [comment]
[Tooltip error.pdf](https://github.com/tannerlinsley/react-table/files/3901158/Tooltip.error.pdf)

**Comment by ivanov-v** [comment]
> [Tooltip error.pdf](https://github.com/tannerlinsley/react-table/files/3901158/Tooltip.error.pdf)
> @ivanov-v Please find this attachment

Are you targeting correctly?
P.S. You need to ask this question in the tooltip repository.

**Comment by PavanKumarHRao** [comment]
Did u see code in second page?

**Comment by ivanov-v** [comment]
> Did u see code in second page?

Better show code on codesandbox.

**Comment by tannerlinsley** [comment]
This is either a question for the tooltip repo, or the forum, but not an issue.

https://spectrum.chat/react-table
