### ISSUE TITLE
If a column has no Filter, column.canFilter is true

### ISSUE THREAD

**Issue by burtyish** [tannerlinsley/react-table#1669]
**Describe the bug**

If a column has no `Filter`, `column.canFilter` is true, even though I expect it to be false.

**To Reproduce**

Based off the filters demo, I disabled the `defaultColumn`. So there's a column that has no `Filter`.

1. Go to https://codesandbox.io/s/tannerlinsleyreact-table-filtering-q00vx
2. You will see an Error
3. In the Table component, replace `BrokenFilterRenderer` with `FixedFilterRenderer`.
4. You'll now see column is rendered without a filter, as expected.

**Expected behavior**
A column with no `Filter` defined should produce `column.canFilter === false`

**Codesandbox!**
https://codesandbox.io/s/tannerlinsleyreact-table-filtering-q00vx

**Screenshots**
N/A

**Additional context**
Using react-table: 7.0.0-beta.15

**Comment by tannerlinsley** [comment]
`canFilter` is not dependant on if a `Filter` renderer is available. It is derived from a few things:

https://github.com/tannerlinsley/react-table/blob/50f2e84929f38f257a198206ded3100f85ad9856/src/plugin-hooks/useFilters.js#L121-L128

**Comment by tannerlinsley** [comment]
`canFilter` is not dependant on if a `Filter` renderer is available. It is derived from a few things:

https://github.com/react-tools/react-table/blob/50f2e84929f38f257a198206ded3100f85ad9856/src/plugin-hooks/useFilters.js#L114-L128
