### ISSUE TITLE
[QUESTION] 'Freezing' columns

### ISSUE THREAD

**Issue by snirlugassy** [tannerlinsley/react-table#167]
I was wondering if there is any possible way to 'freeze' the left  column (or few).
i tried using 'fixed' position while rendering the column, but it didn't really worked.
Love this component!!!
Thank you!

**Comment by tannerlinsley** [comment]
Glad you like it! As for freezing or fixing any columns, it's not yet possible.  There are many architectural changes that would need to take place to achieve this.  It does seem that it would be possible in plain css, but unfortunately you will eventually run into needing separate containers for the fixed and scrollable columns, and also a scroll synchronizer to work between them both. This is what many other libraries do, and unfortunately is also the source of a lot of bugs and performance issues.  For now we chose to forgo that architectural decision until the library matures more.

**Comment by chyamuna** [comment]
hi @tannerlinsley I would like to work on this issue. could you please give some thoughts on the complexity of the issue and help me with solving it?
