### ISSUE TITLE
[v7] Fully Controlled Table with Server-side Data 

### ISSUE THREAD

**Issue by ivanov-v** [tannerlinsley/react-table#1670]
Can you create an example like [this](https://github.com/tannerlinsley/react-table/tree/v6#server-side-data)?

**Comment by tannerlinsley** [comment]
Does this example not cover what you'd like to see?

https://github.com/tannerlinsley/react-table/tree/master/examples/pagination-controlled

**Comment by ivanov-v** [comment]
> Does this example not cover what you'd like to see?
> 
> https://github.com/tannerlinsley/react-table/tree/master/examples/pagination-controlled

Thanks)

**Comment by slykar** [comment]
@tannerlinsley I think it would be great to add more examples. Personally I'm trying to load new data when expanding a row (lazy loaded tree). Right now there is no easy way to know which row has been expanded? You only get an object of all expanded rows. Not only you need to compare `expanded` object to get the new expended row, you also need to find related data model from the `data` tree if you need to parametrize your API call.

**Comment by ronnydawn** [comment]
i think that is not server-side processing,
cause..
we can see static restricted render to 10k data

> const serverData = makeData(10000)

cmiiw

**Comment by Reksraj** [comment]
Yes, Data's server side examples would be great
