### ISSUE TITLE
Accessor keys don't work with Dots

### ISSUE THREAD

**Issue by ajtran** [tannerlinsley/react-table#1671]
# Using v7?

Yawps!

**Describe the bug**

Table rows aren't able to access the columns in data when they have a `.` in the accessor key.

**To Reproduce**

With columns and data described below, the values for the `broken column` are undefined.
```
const columns = [
  {
    Header: 'broken column',
    accessor: 'first.column',
  },
  {
    Header: 'working column',
    accessor: 'first-column',
  },
]

const data = [
  {
     'first.column': 'hello world',
     'first-column': 'hello again',
  },
  {
    'first.column': 'fizz',
    'first-column': 'buzz',
  },
]

...
<Table columns={columns} data={data} />
...
```

**Expected behavior**

I expect the cell to still be able to access the data even with `dot` in the accessor key.

**Codesandbox!**

Use a new [react-table codesandbox](https://codesandbox.io/s/tannerlinsleyreact-table-basic-fjqp4) to reproduce the issue.

**Screenshots**

<img width="317" alt="Screen Shot 2019-11-29 at 3 25 09 PM" src="https://user-images.githubusercontent.com/10730200/69892641-7982fa80-12bc-11ea-88bc-da54e94732cc.png">

**Desktop (please complete the following information):**

- OS: iOS
- Browser: chrome
- Version: 79.0.3945.36 (Official Build) beta (64-bit)

**Additional context**

Not sure if this is by design or a limitation of my data model or a bug.

**Comment by burtyish** [comment]
A period in an accessor is used for accessing properties on a data object.

Your column definition 
```
const columns = [
  {
    Header: 'broken column',
    accessor: 'first.column',
  },
  {
    Header: 'working column',
    accessor: 'first-column',
  },
]
```

Would work well with data like this:
```
const data = [
    {
      first: { column: "hello world" },
      "first-column": "hello again"
    },
    {
      first: { column: "fizz" },
      "first-column": "buzz"
    }
  ];
```

Result:
![image](https://user-images.githubusercontent.com/4200728/69897179-87825b00-1350-11ea-9e5c-45b2c48673e6.png)


You can see it in this working codesandbox: https://codesandbox.io/s/tannerlinsleyreact-table-basic-vxlcg

**Comment by ajtran** [comment]
Oh! I see. Thank you for the clarification!

**Comment by kderbalah** [comment]
@tannerlinsley @burtyish is there any way to disable the deep inspection and treat the accessor as a normal string?

**Comment by burtyish** [comment]
@kderbalah idk about that. But you can get full control of the logic by supplying a function as the accessor

**Comment by kderbalah** [comment]
@burtyish thanks for the quick reply. Yea, I managed to fix it by using a custom accessor
```
{
    Header: 'First Column',
    accessor: (d) => d[key], // example key first.column
    id: key
}
```
Thnaks for the hint!

**Comment by kevinisaac** [comment]
In v8, the `accessor` property was renamed to `accessorFn`.

So, the same example by @kderbalah should be the following:

```
{
    Header: 'First Column',
    accessorFn: (d) => d[key], // example key first.column
    id: key
}
```

**Comment by WillemSleegers** [comment]
What would this solution look like with Typescript?

**Comment by rajagopalstalwart** [comment]
V7 for React-Table
-------------------------------
Header: "Start Date",
accessorkey: "startDate",
Cell: StartDate,

V8 for React-Table
--------------------------------
header: "Start Date",
accessorKey: "startDate",
cell: StartDate,

**Comment by khaukheng** [comment]
> What would this solution look like with Typescript?
For me it's like this:
`header: () => toSnakeCase(key).replace(/_/g, ' '),
// @ts-ignore
accessorFn: data => data[key],
cell: (info) => info.getValue(),`
