### ISSUE TITLE
"utils" is exported but not declared in the typescript declaration file 

### ISSUE THREAD

**Issue by superbull** [tannerlinsley/react-table#1674]
# Using v6?

no

# Using v7?

Yes - react-table@7.0.0-beta.19

**Describe the bug**
`utils` is not declared in the typescript declaration file.

**Comment by tannerlinsley** [comment]
Types are actually being moved over to the Definitely Typed repo, so you'll need to file the issue over there. I would also add that the types are still in flux and likely going to be mismatched on the real api until it comes out of beta and into an RC. Also worth noting, types are not native to this library, so I cannot make any guarantees around the types being up to date with the API at all times.

Thanks!
