### ISSUE TITLE
After v7s Release, v6 is looking for v7's css

### ISSUE THREAD

**Issue by hollygirouard** [tannerlinsley/react-table#1678]
# Using v6?

v6 is now considered feature complete to its current abilities and limitations. We are not actively working to fix any issues for v6 any more. We will, however, merge any non-breaking pull requests submitted to fix anything in v6.

# Using v7?

Thanks for using the beta version of React Table v7! We're very excited about it.

**Describe the bug**
Using `"react-table": "^6.10.3",` _I did try changing it to `"react-table": "6.10.3",` and no dice there either_
`GET https://unpkg.com/react-table@7.0.0-beta.21/react-table.css net::ERR_ABORTED 404`

**To Reproduce**

1. Go to '.https://www.doingthingsmedia.com/dashboard'
2. Click on 'Inspect Element'
3. Check out the console. 

**Expected behavior**
v6 should not be looking for v7's css

**Codesandbox!**
Use a new [react-table codesandbox](https://codesandbox.io/s/m5lxzzpz69) to reproduce the issue.

**Screenshots**
https://dtm-app-test.s3.us-east-2.amazonaws.com/Screen+Shot+2019-12-02+at+10.54.03+AM.png

**Desktop (please complete the following information):**

- OS: 10.15.1
- Browser Chrome
- Version Version 78.0.3904.108
**Smartphone (please complete the following information):**

**Additional context**

**Comment by cc9431** [comment]
Also having this problem. Error in console leads to a link displaying:
"Cannot find "/react-table.css" in react-table@7.0.0-beta.21"

**Comment by jacobselg** [comment]
Yeah, I'm seeing this issue as well in production code, returning `404` on `https://unpkg.com/react-table@7.0.0-beta.21/react-table.css`

**Comment by burhanbvk** [comment]
This is an issue with the css included in the index.html file. The latest version no longer has the css file, so you need to specify the version in the stylesheet url.

It is the public/index.html file

`<link rel="stylesheet" href="https://unpkg.com/react-table@latest/react-table.css">`

This is in there, pointing to the latest release, which no longer seems to have the css file
Change it to:
`<link rel="stylesheet" href="https://unpkg.com/react-table@6.10.3/react-table.css">`

**Comment by tannerlinsley** [comment]
Yep, v7 no longer comes with css (the examples have the bare minimum to get you to a working table with decent layout.

If you are still using v6, you should be locking your version to the `^6` tag at the very least and not the `@latest` tag.
