### ISSUE TITLE
cellState of undefined

### ISSUE THREAD

**Issue by gyto23** [tannerlinsley/react-table#1679]
**Describe the bug**
In plugin `useRowState` I tried to use a function `setCellState` by passing this properties: 

Example 1:
```
setCellState([7], "PartType", (cell) => {
      console.log(cell);
      return "test";
});
```
Example 2:
```    
setCellState([7], "PartType", "test");
```

Non of those are working because as a return to the component I got
![image](https://user-images.githubusercontent.com/54277098/69983147-9d804f00-14fb-11ea-9486-b174604bba16.png)

One of the potential fixes were setting a `old = {}` object, but as get more deeply to the functionality I figure out that initialState of the cell is always `undefined` which kind of odd for me.

Reference: https://spectrum.chat/react-table/general/userowstate-where-cannot-read-property-cellstate-of-undefined~6b738e00-978a-401f-a881-7ef2f2912d09

**Comment by tannerlinsley** [comment]
Version 7.0.0-beta.22 is now your friend :)

**Comment by gyto23** [comment]
@tannerlinsley it still going to be undefined by the `columnId`, its better to do a revert -OR- like this `(old || {}).cellState[columnId]` at `useRowState.js:84` even though `old` is undefined you will still get a `columnId` from initial state undefined. Unless we set initial state on it.

**Comment by tannerlinsley** [comment]
Would you like to PR that?

**Comment by gyto23** [comment]
@tannerlinsley I can try it laster today 😄
