### ISSUE TITLE
6.11.1 is broken

### ISSUE THREAD

**Issue by bsaphier** [tannerlinsley/react-table#1680]
# Using v6?
Yes

**Describe the bug**
in my `package.json` dependencies I had `"react-table": "^6.10.0",`. After building my app after 6.11.1 was released earlier today, react-table errored when trying to render. Removing the carrot causing the build to use version 6.10.0, everything rendered as expected.

When trying to render, it throws this error:
`Uncaught TypeError: Cannot read property 'length' of undefined`
 
**To Reproduce**
1. install latest of v6
2. render the ReactTable component

**Expected behavior**
It renders

**Desktop (please complete the following information):**

- OS: OSX 10.14
- Browser: chrome
- Version 78

**Comment by zaweb** [comment]
I'm experiencing the same issue after updating to 6.11.1.

**Comment by cnavarreteliz** [comment]
Same, I had to force the version of `react-table` using `npm i react-table@6.10.3`

**Comment by tannerlinsley** [comment]
Working on a fix, stay tuned.

Tanner Linsley

**Comment by tannerlinsley** [comment]
Looks like some of the LTS fixes that we merged did something bad. Just going to revert to 6.10.x and do rerelease. Sorry for the confusion! We'll have to look into what happened since then on the v6 branch.

**Comment by tannerlinsley** [comment]
6.11.2 is now available

**Comment by zaweb** [comment]
Works great now, thank you!

**Comment by tannerlinsley** [comment]
👍
