### ISSUE TITLE
[v7] updatable grid remembering expanded state 

### ISSUE THREAD

**Issue by wildcat-cs** [tannerlinsley/react-table#1683]
I've been trying to understand the API and I do not see a way to update the underlying data without having the previously expanded rows collapsed/reset.

I see where I can set an initial expanded state, but not how to keep a previously expanded node to stay expanded.  

This might be an issue with getSubRows not being memoized, but I did not see an example of how you memoize a callback function getting passed into the options of useTable.

**Comment by tannerlinsley** [comment]
I think what you’re looking for is the getResetExpandedDeps option 😊

Tanner Linsley

**Comment by wildcat-cs** [comment]
Thanks for the quick response.  Is there any examples using getResetExpandedDeps feature?

**Comment by tannerlinsley** [comment]
No, but it's pretty easy to use. It receives the table instance, and you return an array of items that when they change, the state will reset.

**Comment by tannerlinsley** [comment]
If you never want the expanded state to reset, you can pass `getResetExpandedDeps: false`

**Comment by wildcat-cs** [comment]
Thanks, think I have it working.  I did find I had to do a //@ts-ignore in order to include the option in useTable.

Thanks again.

**Comment by tannerlinsley** [comment]
Yeah. For the record, typescript types have been removed from this repo and the TS community is working on getting them back up on Definitely Typed. You might want to ts-ignore all of React-Table for now if you run into anything else.
