### ISSUE TITLE
css not loading for react-table@6.10.2 after latest publish

### ISSUE THREAD

**Issue by praty1610** [tannerlinsley/react-table#1684]
Hi, 
What I have observed is classes for ReactTable, rt-table, rt-thead, rt-tbody, rt-tr-group are not being applied.
Is this because of  dependency package(classnames)

**Comment by RyderKishan** [comment]
Try having a stable release version from CDN for now to keep your apps running

**Comment by astritspanca** [comment]
i got this error: **The resource from “https://unpkg.com/react-table@7.0.0-beta.23/react-table.css” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).**. My App is online and this happened, with all css lost. Unacceptable!!!

**Comment by hugo-marques-m3** [comment]
@astritspanca you need to change the import to be:
```
<link
  rel="stylesheet"
  href="https://unpkg.com/react-table-v6@latest/react-table.css"
/>
```
They've changed the name of the v6 package but didn't think about people that were already using the css import.

**Comment by tannerlinsley** [comment]
Indeed. You need to lock into a v6 version

**Comment by astritspanca** [comment]
@hugo-marques-m3 i imported it locally to avoid similar issues in the future. It is our fault for using cdn import but definitely it's theirs too. When you have 250k+ developers using your library, you definitely should be more careful when making changes.

**Comment by tannerlinsley** [comment]
Yeah Im working on beefing up the ci to not allow crazy stuff to happen in the future, but for the record, there is little I can do to prevent people from not implementing semver in their dependencies. I can only do my best to honor semver on my end.

**Comment by hugo-marques-m3** [comment]
I ended up doing the same thing @astritspanca, just to avoid future issues.
And I understand that @tannerlinsley, but the documentation of the version (6.x.x) that we were using says to use
```
<link
  rel="stylesheet"
  href="https://unpkg.com/react-table@latest/react-table.css"
/>
```

**Comment by tannerlinsley** [comment]
Yikes. Yay we should change that.

Tanner Linsley
