### ISSUE TITLE
Resize Columns doesn't work from v7.0.0-beta.20

### ISSUE THREAD

**Issue by enco3ap** [tannerlinsley/react-table#1688]
# Using v7?

Thanks for using the beta version of React Table v7! We're very excited about it.

**Describe the bug**
From version `v7.0.0-beta.20`, `useResizeColumns` hook doesn't work anymore. 

**To Reproduce**

1. Go to [https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/column-resizing](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/column-resizing)
2. See that resizing columns feature doesn't work
3. Change in `package.json` version to `"react-table": "7.0.0-beta.19",`
4. Resizing works as expected

**Expected behavior**
Resize of columns doesn't work

**Codesandbox!**
Use a new [react-table codesandbox](https://codesandbox.io/s/m5lxzzpz69) to reproduce the issue.
[SANDBOX](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/column-resizing)

**Desktop (please complete the following information):**

- OS: [MacOS]
- Browser [chrome]
- Version [78]

**Comment by gyto23** [comment]
@enco3ap you should update to `7.0.0-beta.23` it already fixed there

**Comment by tannerlinsley** [comment]
Yep, it's fixed in versions after beta.23. Make sure codesandbox isn't caching the old version.
