### ISSUE TITLE
Is there a way to add edit button to each row?

### ISSUE THREAD

**Issue by chozze** [tannerlinsley/react-table#1689]
Hello, using v7, so far so great!

I would like to achieve an editable table, when each row has an editing button, when clicked, then the row becomes available for editing.

So far I added an edit button, with onClick action, which returns row id but I am not sure how to change that row into editing cells

Is that possible?

thanks Ales

**Comment by prathmeshphuke** [comment]
You can include Actions as mentioned below in column data. You will be passing array of options to actions. 
```
class UserContainer extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            columns: [{
                            id:'Actions',
                            Header: <div style={{textAlign: "left"}}><b>Actions</b></div>,
                            accessor: d => d.actions,
                            Cell: props => this.displayActionItems(props),
                            sortable: false,
                        }];

componentDidMount() { 
let updateState ={...this.state};
updateState.actions = ['Edit', 'Delete'];
this.setState(updatedState); }

displayActionItems = props => {
        return (
            <div style={{ textAlign: "left" }}>
                   <a style={{cursor: "pointer"}}  onClick={(event) => this.updateUswe(event, props)}>{props.value[0]}</a>
                <a style={{cursor: "pointer", color:"red"}} onClick={(event) => this.openDeletePopup(event, props)}> {props.value[1]}</a>
            </div>
        );
    }
```
Please let me know if you are still not clear about above code.

**Comment by tannerlinsley** [comment]
Please take a look at the editable table example in the examples directory. 😁

Tanner Linsley

**Comment by chozze** [comment]
yeah I did, but it is not exactly what I wanted to achieve :)

**Comment by tannerlinsley** [comment]
I think a good way to get help here is to have a codesandbox that others can look at and tweak. What's not quite right about the existing example?

**Comment by mrjelveh** [comment]
I think you should add an accurate example for the editable row in documentation,
generally, React Table is great but really hard to use as you see [reviews on openbase](https://openbase.com/js/react-table/reviews)
@tannerlinsley
