### ISSUE TITLE
Data is being fetch on current page box blur

### ISSUE THREAD

**Issue by alebrozzo** [tannerlinsley/react-table#169]
## Problem Description
I have a table that handles paging and sorting on the server side. Everything seems to work fine, except that when I manually enter the page I want to go and hit enter, the page is refreshed but then on blur the page is refreshed again and the same data is being retrieved.

## Steps to Reproduce
1. On a multi-page table, navigate by manually entering the current page and hit enter
2. Leave the current page box

## System Information
**Chrome 57**
**Win10 Pro**

**Comment by tannerlinsley** [comment]
This is definitely a bug and needs to get fixed.  If you're interested in fixing it, I would be happy to help you through it.

**Comment by tannerlinsley** [comment]
Near [this line](https://github.com/tannerlinsley/react-table/blob/master/src/pagination.js#L29), there needs to be logic that checks if the desired page is already the current page.  If it is, then just return without changing the page.  If it not the same page, continue as normal and change the page.

**Comment by alebrozzoSP** [comment]
Hey @tannerlinsley , I just created a PR with a fix to this issue (I am the creator of the issue, but with a different account). Rather than applying the fix where you said (function applyPage), I applied it on changePage. I also added an extra fix to getSafePage for when the parameter date is NaN.

**Comment by tannerlinsley** [comment]
Merge :)
