### ISSUE TITLE
[useRowSelect] `Select All` operation can be optimized

### ISSUE THREAD

**Issue by gargroh** [tannerlinsley/react-table#1690]
Using `useRowSelect`, `Select All` feature, when used with good amount of rows(mine case is with ~119K rows), then takes a long time to apply action. Following are the major places which are time consuming :-

1. ![image](https://user-images.githubusercontent.com/42495927/70052314-08638000-15f9-11ea-9252-91fe4df3ac6f.png)
It is possible to optimize here by checking `flatRowPaths.length === selectedRowPaths.length` or in any other way ?

2 ![image](https://user-images.githubusercontent.com/42495927/70052329-11ece800-15f9-11ea-9692-1c34eec90a6d.png)

@tannerlinsley , let me know your thoughts on it, will open PR accordingly..

**Comment by tannerlinsley** [comment]
Yeah there is definitely room for improvement here.

Tanner Linsley

**Comment by tannerlinsley** [comment]
I think one good solution to this is changing `selectedRowPaths` to a `Set()`.  The hard part with sets is that they are not particularly intuitive for immutable operations, but we can mask that for the most part and just document that it's a set. Not hard to do `new Set(existingSet)` to get a new copy.

**Comment by tannerlinsley** [comment]
I'll push that change in a bit.

**Comment by tannerlinsley** [comment]
Just pushed a new beta version that uses `Set()`. It should be a lot faster.

**Comment by gargroh** [comment]
Thank you @tannerlinsley
