### ISSUE TITLE
What happened to 7.0.0-beta25

### ISSUE THREAD

**Issue by rchadwic** [tannerlinsley/react-table#1696]
We used to link to https://unpkg.com/react-table@7.0.0-beta.25/react-table.css, but that file seems to have been removed from the CDN. Stranger still, this tag seems to be missing from the repo? We have multiple copies of our software that rely on this file, so I'm not sure what to do.

**Comment by paolostyle** [comment]
react-table v7 never (or at least never should've) provided any CSS files. I remember they were there for a while in one of early alphas but they got removed since then. Use https://unpkg.com/react-table@6.11.2/react-table.css

**Comment by rchadwic** [comment]
I see. So, yeah this is a problem. We reference https://unpkg.com/react-table@latest/react-table.css, which now redirects to https://unpkg.com/react-table@7.0.0-beta.26/react-table.css, which does not exist. Hummmmmm. Any ideas?

**Comment by tannerlinsley** [comment]
Right, this was just a file artifact from moving between branches locally. It should never have been packaged by npm for distro. I've since removed it and added an ignore to it.

Anything use v6 should lock into that version. After that, css is no longer provided.
