### ISSUE TITLE
kitchen-sink-controlled example link to CodeSandbox leads to kitchen-sink repo

### ISSUE THREAD

**Issue by paolostyle** [tannerlinsley/react-table#1697]
https://github.com/tannerlinsley/react-table/tree/master/examples/kitchen-sink-controlled - the anchor in README.md links to https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/kitchen-sink instead of https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/kitchen-sink-controlled - which, by the way, seems to be broken for me. I'm not sure what's wrong there since I'm getting that infamous cross-origin error in Code Sandbox, but it's not working.

**Comment by tannerlinsley** [comment]
The link is now fixed.

**Comment by tannerlinsley** [comment]
And the controlled example is now fixed.
