### ISSUE TITLE
Use react-table with react-virtualized grid

### ISSUE THREAD

**Issue by vitpekarek** [tannerlinsley/react-table#1698]
Do you think it's possible? I saw virtualization with react-window in examples, but I need to virtualize columns and maybe some other features from react-virtualized grid.

I just wanted to ask before I start working on it.
Thank you for response

**Comment by tannerlinsley** [comment]
Yes. The approach is almost identical too. Start with the React window example and just try swapping it out for virtualized.

Tanner Linsley

**Comment by Sudhirkanu** [comment]
The new release has a bug.
while traversing the columns, it gives a bug in forEach
Kindly revert or solve the issue please, it gave a pre-prod bug for my application

Thanks
sudhir

**Comment by tannerlinsley** [comment]
@Sudhirkanu  please open a need issue with a codesandbox example of the bug.

**Comment by pavelspichonak** [comment]
@tannerlinsley for List component from react-window the prepareRow method is great. But how about Grid component from react-window? For example you can also have any number of columns(100000+ for example) but only 10 of them are visible. In this case prepareRow method is good but only for vertical direction.

Maybe I missed something and there is opportunity to lazy prepare cells as well? Thanks.
