### ISSUE TITLE
[v7] typings

### ISSUE THREAD

**Issue by ivanov-v** [tannerlinsley/react-table#1701]
Can I install typings for latest beta?

**Comment by ivanov-v** [comment]
UPD: I found PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40816
Please add this link to release notes.

**Comment by jakub-astrahit** [comment]
So how can we use react-table in typescript now in version 7? I'm getting this error:

```
Could not find a declaration file for module 'react-table'. 'node_modules/react-table/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-table` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-table';`  TS7016
  >  8 | import { useTable } from 'react-table'
```

What workaround did you use @ivanov-v ?

**Comment by ivanov-v** [comment]
> So how can we use react-table v7 in typescript now? I'm getting this error:
> 
> ```
> Could not find a declaration file for module 'react-table'. 'node_modules/react-table/dist/index.js' implicitly has an 'any' type.
>   Try `npm install @types/react-table` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-table';`  TS7016
>   >  8 | import { useTable } from 'react-table'
> ```
> 
> What workaround did you use @ivanov-v ?

I'm temporarily install **7.0.0-beta.23**

**Comment by tannerlinsley** [comment]
The link to Definitely Typed is in the TYPESCRIPT.md file. It is still being reviewed  so you’ll have to continue the conversation there.
