### ISSUE TITLE
getResetPageDeps not working

### ISSUE THREAD

**Issue by chozze** [tannerlinsley/react-table#1703]
Hello, I am trying to create editing table, but getResetPageDeps set to false seems not to be working for me, please check https://codesandbox.io/s/sharp-paper-iljn7-iljn7

Go to page 2, click edit button, change any data and click outside of input > page goes back to 1.

btw I know i should not set getResetPageDeps: false directly, but use some kind of state instead - but this is just for a simplification here.

thanks Ales

**Comment by chozze** [comment]
Closing, found myself I am reini table function on every component render...

**Comment by tannerlinsley** [comment]
This discussion happening right now is relevant to this issue: https://github.com/tannerlinsley/react-table/issues/1729
