### ISSUE TITLE
Intermittent error "cannot read property subrows of null"

### ISSUE THREAD

**Issue by Quinter** [tannerlinsley/react-table#1708]
v7. error occurs infrequently, hard to reproduce, at line 33 of useTable.js:
`const defaultGetSubRows = (row, index) => row.subRows || []
`

I seem to have fixed it for myself as following: 
`const defaultGetSubRows = (row, index) => {
  if (row !== null && row.subRows) {
    return row.subRows
  } else {
    return []
  }
}`

**Comment by tannerlinsley** [comment]
This happens if an item in your `data` array is `null`, eg:

```js
const data = [row, row, null, row]

useTable({
  data, // Error!
})
```
