### ISSUE TITLE
useRowSelect broken since beta.24

### ISSUE THREAD

**Issue by ggascoigne** [tannerlinsley/react-table#1709]
It looks like useRowSelect broke in beta.24.

state.selectedRowPaths is no longer getting updated.

Reproduces easily in https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/row-selection

**Comment by ggascoigne** [comment]
I take it back, `selectedRowPaths` isn't broken, it changed to a `Set` and since all of the examples then try and pass it to `JSON.stringify` which doesn't know what to do with Sets, it gets displayed as being empty.

I'll leave the bug open since the examples need changing.

**Comment by tannerlinsley** [comment]
Examples have been updated 👍
