### ISSUE TITLE
import error...

### ISSUE THREAD

**Issue by mrkchang** [tannerlinsley/react-table#1710]
V7:

Followed readme.md for npm i --save react-table@next

Getting this error - Attempted import error: 'react-table' does not contain a default export (imported as 'ReactTable').

from 'package'     "react-table": "^7.0.0-beta.20",

**Comment by mrkchang** [comment]
import {
    useTable
    
} from 'react-table'

**Comment by tannerlinsley** [comment]
Use just `react-table` now. @next is no longer required

**Comment by atulcodex** [comment]
i am getting this error

Attempted import error: 'react-table' does not contain a default export (imported as 'ReactTable').

Version : "react-table": "^7.0.0-rc.15",

**Comment by kodcuserkan** [comment]
I am getting "Attempted import error: 'react-table' does not contain a default export (imported as 'ReactTable')." error as well. I deleted all modules and lock file and installed react-table again but still error exist. Made me crazy

**Comment by mhsunny** [comment]
Solved the problem!!!
Go to there https://www.npmjs.com/package/react-table-6
You have to install 
npm install react-table-6

and then import  
import ReactTable from 'react-table-6'

its solved:)
