### ISSUE TITLE
"utils" is not exported in .beta27

### ISSUE THREAD

**Issue by paolostyle** [tannerlinsley/react-table#1711]
I figured out how to fix this in my code (there's no utils object anymore, just loose functions), but it's really confusing. This is a breaking change (which is fine), but it's undocumented and code on GitHub is not updated. That also breaks some examples, e.g. https://github.com/tannerlinsley/react-table/tree/master/examples/data-driven-classes-and-styles

**Comment by tannerlinsley** [comment]
The examples that I know of have been fixed in master and this has been added to the changelog. Thanks!
