### ISSUE TITLE
Using SubComponent with react-redux useDispatch hook

### ISSUE THREAD

**Issue by hellpirat** [tannerlinsley/react-table#1712]
# Using v7?

**Describe the bug**
I using react-table@^7.0.0-beta.26 with react-redux. When I using Sub Component with useDispatch from react-redux - my expandable component is closing

**To Reproduce**
Code: 
```
const renderRowSubComponent = React.useCallback(({ row }) => {
    dispatch({ type: "test " });
    return (
      <pre
        style={{
          fontSize: "10px"
        }}
      >
        <code>{JSON.stringify({ values: row.values }, null, 2)}</code>
      </pre>
    );
  }, []);
```

**Codesandbox!**
[codesandbox](https://codesandbox.io/s/affectionate-heyrovsky-rx0ul)

**Comment by GunnarSturla** [comment]
It's hard to debug or help when we can't really see what's happening in your code, could you give a more detailed code example, showing how you're using react-table and the subComponent?

The CodeSandbox isn't working, you'll have to initialize the store and wrap the app in react-redux's `<Provider>`.

**Comment by tannerlinsley** [comment]
Yeah, please open a new issue with more information, or you could also ask this question on https://spectrum.chat/react-table.  Thanks!
