### ISSUE TITLE
[v7] Accessor derivation slow with 100k+ rows

### ISSUE THREAD

**Issue by gargroh** [tannerlinsley/react-table#1713]
When i provide react-table v7 with good amount of rows(below case is with 100K rows and 15 columns, then `getBy`, `makePathArray` are taking long time to execute.

![image](https://user-images.githubusercontent.com/42495927/70232017-7b97fe00-1781-11ea-9ad5-14063f5d1dd2.png)

![image](https://user-images.githubusercontent.com/42495927/70232038-818ddf00-1781-11ea-8edc-e7d48b8573ef.png)

Is there anything we can do to optimize it ?
I can see before calling `getBy` we are splitting by `.`, then in `makePathArray` we are doing `map(d => String(d).replace('.', '_'))`, this thing seems to be redundant(or can be applicable at some other place also),  is this good to remove ?

**Comment by tannerlinsley** [comment]
I think that needs to stay, but we can definitely start by extracting out the regex expressions to variables so they aren’t created for every row.

Tanner Linsley

**Comment by Asuskf** [comment]
'react-table' does not contain a default export (imported as 'ReactTable').

**Comment by tannerlinsley** [comment]
@asuskf, please update to the latest version of react-table@latest and try again. If the issue persist, please open a new issue with more information, thanks.

**Comment by tannerlinsley** [comment]
I just pushed a new RC with the regex's pulled out into vars. Let's see if that speeds it up at all?

**Comment by gargroh** [comment]
Ok, will check and get on this.

**Comment by gargroh** [comment]
Following is the time taken (its weird) but for 100K records stats are - 

Before(using inline regex) - 
```getAccessedRows: 10793.928955078125ms
getAccessedRows: 10435.14306640625ms```

After(using stored regex) -
```getAccessedRows: 11396.470947265625ms
getAccessedRows: 11333.337890625ms```

Also we can see the same at https://jsperf.com/regexp-indexof-perf/24, it can be improve by ~10 to 15%.

How about using memoization, as accessor will be same throughout column, so instead of calculating for every cell, can it be calculated once for each column and use it for cells ?

**Comment by tannerlinsley** [comment]
In the latest version, the table now caches the pathObjects used in column accessors via the `getBy` function. I would love to see if and how this improves your speeds.

Another piece to note is that the debug and timing code was removed in the latest version. You will need to edit the source to get those exact timing logs back. Here's the location of those loggers for reference: https://github.com/tannerlinsley/react-table/blob/176986a07ad8b25907fff435e1246962dba18e47/src/hooks/useTable.js#L174-L231

**Comment by tannerlinsley** [comment]
Any updates here?

**Comment by gargroh** [comment]
Checking brb

**Comment by gargroh** [comment]
Woah, that improved performance of `getAccessedRows` by `~5x`, time taken for 100K rows :-

Before - 
getAccessedRows: 9396.649169921875ms
getAccessedRows: 10379.017333984375ms

After - 
getAccessedRows: 2384.264892578125ms
getAccessedRows: 2155.550048828125ms

PS. - I am using `7.0.0-rc.1` version and only replaced old `getBy` method with new one(present in master)

**Comment by tannerlinsley** [comment]
Wow that’s awesome!

Tanner Linsley

**Comment by tannerlinsley** [comment]
I would say this is a big win out of the gate. I would still like to see some more profiling to see what else we could optimize, but I'd like to close this issue for now. If you're still not satisfied with the speed, feel free to comment with more info and we can open it back up. :)

**Comment by gargroh** [comment]
Yes, this is a pretty good win, i will say ~3s for 100K rows with 30 Columns is fine, if this was happening only on grid init. 

These `getAccessedRows ` are also calculated whenever user re-orders column(i know this is done to form `cells` array),  due to this every column re-ordering takes a good amount of time and screen freezes for the time being. Is there a way to better this.

Also, for profiling earlier used console time utility was pretty helpful, it would be good if we can get back.

**Comment by gargroh** [comment]
Re-opening, in case https://github.com/tannerlinsley/react-table/issues/1713#issuecomment-565008053 was missed, can open a new issue.

**Comment by gargroh** [comment]
It seems this was missed, opening a new issue to track this https://github.com/tannerlinsley/react-table/issues/1773

**Comment by fyodore82** [comment]
I also experienced performance degradation on 25K+ rows.
My code to measure performance is
```
console.log(new Date().toISOString(), ' useTable started')
const {...} = useTable(...)
console.log(new Date().toISOString(), ' useTable finished')
```

With columns like below
```
column = {
  accessor: 'some string'
  // ...
}
```
It takes 100+ seconds to execute useTable
![image](https://user-images.githubusercontent.com/29746153/95159417-56c94880-07e1-11eb-8714-808be5ad4fdc.png)

When I've written my own accessor function
```
const accessor = (pathArr: string[], originalRow: GridRow) => {
  let cursor = originalRow
  for (const path of pathArr) {
    if (cursor == null) return cursor
    cursor = cursor[path]
  }
  return cursor
}

column = {
  id,
  accessor: accessor.bind(null, pathArr),
  //...
}
```
`useTable` completes in couple of seconds
![image](https://user-images.githubusercontent.com/29746153/95159548-a3ad1f00-07e1-11eb-8961-3f7f40f83384.png)

My code may not be universal, I've developed it only for my project. But it may help someone else...
