### ISSUE TITLE
latest react table ignores show property on column

### ISSUE THREAD

**Issue by jurisjansons** [tannerlinsley/react-table#1715]
**Describe the bug**
Updated from v7 beta.24 to beta.27 and it seems that `rows` and `headerGroups` ignores `show` property on column. They return all columns all the time. 

**To Reproduce**
Use basic example and set `show: false` to any column.

**Expected behavior**
Not to return in `rows` and `headerGroups` columns that has property `show` set to `false`.

**Codesandbox!**
[Edited basic example](https://codesandbox.io/s/dreamy-engelbart-9u0vd) to reproduce the issue.

**Desktop (please complete the following information):**
- OS: Widnows
- Browser Chrome
- Version 78.0.3904.108

**Comment by tannerlinsley** [comment]
We're currently reworking how column visibility works, hang tight for the next beta.

**Comment by tannerlinsley** [comment]
The `show` option has been deprecated.

Visibility of columns can now be controlled using the `hiddenColumns` state property. It's an array of column ID's to be hidden. There are also brand new methods on the instance and columns for controlling visibility, including an example of how to build a column hide/show UI :)

Cheers!
