### ISSUE TITLE
v7.0.0-beta.15 disable sorting doesn't work

### ISSUE THREAD

**Issue by favianca** [tannerlinsley/react-table#1719]
# Using v6?

No

# Using v7?

Yes

**Describe the bug**

Disable sorting still makes the header clickable but the value of column.isSorted is false

**To Reproduce**

1. Use 7.0.0-beta.15
2. Set column option disableSorting to true
3. Click on disabled column header
4. Column sorts

**Expected behavior**
Header shouldn't be clickable

**Screenshots**
![image](https://user-images.githubusercontent.com/50097936/70295076-3e327f80-1818-11ea-9203-603fbeedf559.png)
Props of the disabled header
![image](https://user-images.githubusercontent.com/50097936/70295086-4e4a5f00-1818-11ea-9d32-fc7595e0f79c.png)
Actual header (displaying arrow logic is tied to column.isSorted so it doesn't show)

**Comment by tannerlinsley** [comment]
Please upgrade to the latest beta please.

Tanner Linsley

**Comment by stahlmanDesign** [comment]
use `disableSortBy`. `disableSorting` was renamed
https://github.com/tannerlinsley/react-table/issues/1656#issuecomment-558302555
