### ISSUE TITLE
Adding default filters

### ISSUE THREAD

**Issue by snirlugassy** [tannerlinsley/react-table#172]
I didn't managed to add filters.
The docs says just to add `showFilters={true}` (or just showFilters) to the component.
But still  i cant see the filters.
Current Component:
```
          <ReactTable
          loadingText={this.state.loadingText} 
          data={this.state.data} 
          columns={this.state.columns} 
          showFilters={true}
          loading={this.state.loading} />
```

There is another setting needs to be done to acheive default filtering?

**Comment by TacticalCoding** [comment]
That should work. What version are you using?

**Comment by snirlugassy** [comment]
"react-table": "^5.3.5",

**Comment by snirlugassy** [comment]
Do i need to add anything besides that showFilters?

**Comment by tannerlinsley** [comment]
You need to upgrade to at least version 5.5.0 to use filters.

**Comment by snirlugassy** [comment]
Worked! Thank you!!!!

**Comment by tannerlinsley** [comment]
Awesome!
