### ISSUE TITLE
useFilter docs are in the useSortBy file

### ISSUE THREAD

**Issue by ggascoigne** [tannerlinsley/react-table#1722]
I just noticed that the docs for useFilter are at the end of https://github.com/tannerlinsley/react-table/blob/master/docs/api/useSortBy.md

**Comment by tannerlinsley** [comment]
Whoops! Coding on a plane... you know how it is... no shoulder room. 😂

Can you PR that to a new file?

**Comment by ggascoigne** [comment]
Sure

**Comment by ggascoigne** [comment]
https://github.com/tannerlinsley/react-table/pull/1723 :)
