### ISSUE TITLE
Columns displays null values

### ISSUE THREAD

**Issue by killerbytes** [tannerlinsley/react-table#1725]
**Describe the bug**
`accessor: String` displays `null` values 

**Expected behavior**
It should display as blank

**Comment by tannerlinsley** [comment]
Do you have an example of this issue we can look at?

**Comment by Ksoso** [comment]
Default Cell renderer looks like this:
`({cell: {value}}) => String(value)`

When **value = null**, you will see in column **"null"** string.

I don't think this is issue at all, however String(undefined) returns **"undefined"** string. 

Default column renderer can be simply changed by passing **defaultColumn** property to **useTable()** hook where **Cell** will be like:
`({cell: {value}}) => value && String(value)`

**Comment by tannerlinsley** [comment]
Yep, you can change the default renderer if you choose:

```js
useTable({
  defaultColumn: React.useMemo(() => ({
    Cell: ({ cell: { value } }) => typeof value !== 'undefined' && value !== null ? String(value) : null
  }), [])
})
```
