### ISSUE TITLE
Code example for useExpanded is broken

### ISSUE THREAD

**Issue by tremby** [tannerlinsley/react-table#1731]
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/expanding

Currently shows an error message. The stack trace isn't useful to me; I can't figure out exactly what's wrong.

```Error
A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.
▶ 12 stack frames were collapsed.
evaluate
/src/index.js:6:9

  3 | import './index.css'
  4 | import App from './App'
  5 | 
> 6 | ReactDOM.render(<App />, document.getElementById('root'))
    |         ^
  7 | 

View compiled
▶ 10 stack frames were collapsed.
```

**Comment by patwalls** [comment]
Also experiencing this on another codesandbox example.

**Comment by nbostrom** [comment]
@tremby @patwalls All (or most) examples are broken. They work if you change the dependency version of react-table from "latest" to "7.0.0.rc3" under "Dependencies" in the sidebar

**Comment by tannerlinsley** [comment]
Indeed. This issue should be fixed with the next release (in a few hours)
