### ISSUE TITLE
useAsyncDebounce not working and not exported properly 

### ISSUE THREAD

**Issue by john-pc** [tannerlinsley/react-table#1734]
Hey, 
useAsyncDebounce is not exported correctly, you cant do 
`import {useAsyncDebounce} from 'react-table'`

its because of useAsyncDebounce is exported by default so it's not included in the index.js exports

`export default function useAsyncDebounce(defaultFn, defaultWait = 0) `

You need to change that to 
`export function useAsyncDebounce(defaultFn, defaultWait = 0) `

also the function is not working for me
```
publicUtils.js:161 
Uncaught (in promise) TypeError: debounceRef.current.reject is not a function
```

**Comment by tannerlinsley** [comment]
Yeah that should definitely be a named export instead. And I’ll look into that error

**Comment by john-pc** [comment]
Thank you for your amazing work @tannerlinsley

**Comment by tannerlinsley** [comment]
This should be fixed in RC.5
