### ISSUE TITLE
CodeSandbox not correctly running code

### ISSUE THREAD

**Issue by rctbusk** [tannerlinsley/react-table#1737]
# Using v7?

Yes

**Describe the bug**
Opening any example in CodeSandBox, get this error ```A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.```

**To Reproduce**

Open any example in codeSandbox

**Comment by tannerlinsley** [comment]
This is a known issue and will be resolved with our next release. Stay tuned.

**Comment by tannerlinsley** [comment]
This should now be fixed. Thanks!
