### ISSUE TITLE
`selectedFlatRows` keeps changing, triggering effects dependent on it

### ISSUE THREAD

**Issue by burtyish** [tannerlinsley/react-table#1740]
**Describe the bug**
`selectedFlatRows` keeps changing, triggering effects dependent on it.

**To Reproduce**
Set up an effect dependent on `selectedFlatRows`. See codesandbox below.

**Expected behavior**
`selectedFlatRows` should only change when row selection changes.

**Codesandbox!**
In the codesandbox below, open the console and then switch the version of react-table from beta.16 to rc.5.
You will see endless logging and eventually reach maximum callstack.
https://codesandbox.io/s/zealous-moore-7zxyr

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
react-table version rc.5

**Additional context**

P.S.
Possibly related to #1739?

**Comment by tannerlinsley** [comment]
Make sure you're using the latest release candidate version of React Table. This issue was solved in a version after the one you are using. If you keep having issues, please comment to reopen.

**Comment by Luckygirlllll** [comment]
I have the same error in react-table` 7.2.0 `version, when I'm trying to use `selectedFlatRows` in `useEffec`t it creates infinite loop.

```
 useEffect(() => {
console.log("do something")
  }, [selectedFlatRows])
```
