### ISSUE TITLE
error in useGroupBy in ^7.0.0-rc.6 Version

### ISSUE THREAD

**Issue by anishpatelyaadada** [tannerlinsley/react-table#1753]
I am making the application which shows the data using useGroupBy and useExpanded and the data changes as user click the option to show result by month or year. After changing this option the table is not performing grouping and its shows all info in expanded. I think so there is a bug in this version ^7.0.0-rc.6 because it was working with ^7.0.0-rc.1

**Comment by YaadadaAnish** [comment]
https://github.com/tannerlinsley/react-table/commit/9de699bfd3a12bc8884ec467f72bf93e29e68ff6#commitcomment-36361269

**Comment by tannerlinsley** [comment]
I believe this should be fixed in the latest version. If not, please comment with more info and we'll reopen.

**Comment by anishpatelyaadada** [comment]
@tannerlinsley sure thank you so much I really appreciated for your help

**Comment by anishpatelyaadada** [comment]
@tannerlinsley still the issue is not fixed in the new version

**Comment by tannerlinsley** [comment]
Weird. Would you be able to make a new code sandbox that shows this issue? That will help me the debug better

**Comment by anishpatelyaadada** [comment]
@tannerlinsley sure I will try my best to make later this week. Thank you so much for your help I really appreciated it.
