### ISSUE TITLE
getResizerProps error in 7.0.0-rc.7

### ISSUE THREAD

**Issue by mjchang** [tannerlinsley/react-table#1755]
**Describe the bug**
column.getResizerProps() produces this error: `Invalid attempt to spread non-iterable instance`.

**To Reproduce**
See error in: https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/column-resizing

**Expected behavior**
It's not supposed to error. Downgrading react-table to 7.0.0-rc.6 fixes the issue.

**Comment by tannerlinsley** [comment]
I'm on it
