### ISSUE TITLE
Rethink how row selection is handled

### ISSUE THREAD

**Issue by androsj** [tannerlinsley/react-table#1756]
[Original discussion @ Spectrum](https://spectrum.chat/react-table/general/feature-add-selectedleafrows-to-table-instance-way-to-control-selected-leaf-rows~82770072-3dbb-41d3-8f33-ecebcd35fd99)

### What's wrong with the current implementation?
1. It's harder to control state, specially when using the GroupBy plugin.
2. As you group by different values, the row paths also change, resulting in old selections suddenly "vanishing".
3. What you actually want to select are the original (leaf/raw) rows.

### How should it work then?
* The most natural approach is to track selected rows with a list of row ids. The original rows' ids, that is. This piece of state should take the place of `selectedRowPaths`, possibly with a new name like `selectedRowIds`.
* In order to manage materialized (grouped) rows, `selectedRowPaths` is kept as internal state. Whenever `groupBy` or `selectedRowIds` are updated, `selectedRowPaths` is regenerated using the new row paths.

**Comment by tannerlinsley** [comment]
Yep, this is where I'm headed. I'll be back in a bit!

**Comment by tannerlinsley** [comment]
Alright, big changes here. Check it out! https://github.com/tannerlinsley/react-table/commit/ddfa0fa2274fd9ed011cd91d474a8296d8cc9eec

**Comment by androsj** [comment]
wow you are a beast!
This is honestly one of the best thought-out software I've seen. Thank you. I'm truly enjoying working with this tool.
