### ISSUE TITLE
Not sure that some of the hook deps are working as intended

### ISSUE THREAD

**Issue by ggascoigne** [tannerlinsley/react-table#1757]
Looking at https://github.com/tannerlinsley/react-table/blob/master/src/hooks/useTable.js#L200

Isn't a plugins `columnsDeps` or `flatColumnsDeps` a function that returns the dependencies? Given that, then `getFlatColumnsDeps(getInstance())` returns an array of functions, not the results of calling those functions.  As such those aren't the values that want to get passed to useMemo.

Or am I completely misunderstanding what's intended here?

**Comment by tannerlinsley** [comment]
You are correct. They need to be applied

**Comment by tannerlinsley** [comment]
Fixed in the latest release :)
