### ISSUE TITLE
[v7] API suggestion/request on controlling table state

### ISSUE THREAD

**Issue by akdor1154** [tannerlinsley/react-table#1758]
(copied from Spectrum chat)

Heya,
Looking at the `useControlledState` system, it seems very capable, but also seems complex for many small use cases.
Would it be straightforward to provide us with a `setState` function returned to us by `useTable`? Or alternatively, `setExpanded`, `setGroupBy`, etc depending on what hooks we supply?

This would make my current use-case a lot simpler, you probably have a better idea of whether it would be useful for other users!

E.G.

```js
const {
  state,
  setState,
  //or
  setExpanded,
  ...
} = useTable(...);

setState((oldState) => ({...oldState, expanded: [all]}));
```

My current use-case is actually the same as one of the most recent other Spectrum chats: I want to provide buttons to "expand all" or "collapse all" expandable rows. If I had access to `setState`, I could do something like
```js
function expandAll() {
  const allRows = data.map((row) => [row.id]);
  setState({expanded: allRows});
}

function collapseAll() {
  setState({expanded: []});
}
<button onClick={expandAll}>Expand All</button>
```

I expect (again you probably have a better idea here) that a lot of desire to modify table state come from event-driven scenarios like this. Having `setState()` for the table's state maps naturally to these cases, and additionally is a really natural way for devs to work, as it's the same way state is manipulated in a (non-table) hooks-based component anyway.

The current alternative to this that I see now is duplicating the (e.g.) `expanded` state into my own component, and using `useControlledState` to pass that into the table on each render. This seems a bit clunky compared to the above workflow, and additionally doesn't work well when the table wants to modify its own expanded state (e.g. events from `row.getExpandedToggleProps()`)

**Comment by tannerlinsley** [comment]
I'm still evaluating this, but in the meantime, you should get caught up on the latest changes:

https://github.com/tannerlinsley/react-table/commit/ddfa0fa2274fd9ed011cd91d474a8296d8cc9eec

**Comment by tannerlinsley** [comment]
I still think we're going to favor adding pre-defined actions to the table instead of exposing a non-action based setState. If you have any use-cases that the existing actions don't cover, raise the alarm :)

**Comment by ConneXNL** [comment]
@tannerlinsley if one would use react-router and use the sort/filter/pages from the location in a parent component, you would need to somehow keep the internals in sync whenever someone hits the "back" button in the browser.

But this is a problem because this would basically trigger a complete new state and there is currently no way to update the state by outside changes.

**Comment by Reksraj** [comment]
Is there any link for server side (manual pagination)? I was trying to get data from server, it shows just top 10, not other data's
as server side pagination set for 10row's of data foe each page. Any help on this please

{
    "count": 15,
    "next": "http://127.0.0.1:8000/api/v1/applicant/?page=2",
    "previous": null,
    "results": [
...
...
]
}
