### ISSUE TITLE
Is there any method for fixed table header for version 7? If there is please help.

### ISSUE THREAD

**Issue by meSubhoKarma** [tannerlinsley/react-table#1759]

**Comment by tannerlinsley** [comment]
Since v7 is headless, this is not out-of-the-box functionality. Though we are working on some examples around this. If you would like to spearhead this on your own, or sponsor it's development, let me know!

**Comment by gajus** [comment]
> Since v7 is headless, this is not out-of-the-box functionality. Though we are working on some examples around this. If you would like to spearhead this on your own, or sponsor it's development, let me know!

Are there any examples for this?
