### ISSUE TITLE
Page size greater than length of data

### ISSUE THREAD

**Issue by roginfarrer** [tannerlinsley/react-table#176]
![](http://i.imgur.com/WlNh2hL.png)

## Problem Description
If you pass in a small dataset (say an array of 10 items), the you can still change the length of the table to be greater than the dataset. As a result, it produces these rows with these strange characters.

It's possible to avoid this with `pageSizeOptions`, but it seems like this kind of thing should be built in.

## Hacky fix
    const getPageSizeOptions = (data) => {
      const isBigEnough = (value) => value <= data.length;
      const reducedPageSizes = this.props.pageSizeOptions.filter(isBigEnough);
      return reducedPageSizes;
    };

    <ReactTable 
       columns={columns}
       data={data}
       pageSizeOptions={getPageSizeOptions(data)}
    />

## Steps to Reproduce
NOTE: I'm using the source file found [here](https://unpkg.com/react-table@5.5.0/react-table.js).
1. Pass in a small data set
2. Load the page, and change the table page length to a number longer than the dataset.

## Suggestions
I think it would make sense that if the data set's length is under 100, the the page length options should be limited to under the data.length, and perhaps the final option should be `Show all`. This could still be overridden with the `pageSizeOptions` prop.

**Comment by roginfarrer** [comment]
To add onto this, I think it would be great if the number of rows to reflect the length of the data. For example, if there's 7 rows of data, and the page length is 10, only show the 7 rows, rather than showing 3 empty rows.

**Comment by tannerlinsley** [comment]
@roginfarrer, can you please try and reproduce your code in this codepen demo: http://codepen.io/tannerlinsley/pen/QpeZBa?editors=0010.

As for your second comment, this is true, some people may prefer that the padding rows are not present, though in user-research, we found that 99% of the time, the last page of data shown without padding rows would consequently change the height of the table and position of the bottom toolbar.  This was disorienting according to our users and also caused unneeded reflow and scrollbar changes below our table. We ultimately decided to default to include padding rows.

Great news though. By setting the `minRows` prop to `0`, you can rest assure that no padding rows will ever be shown. :)

**Comment by cwhenderson20** [comment]
@roginfarrer, if you add the following tag to your HTML, the strange characters will disappear (those are actually `&nbsp;` being rendered improperly):

```html
<meta charset="utf-8">
```

**Comment by tannerlinsley** [comment]
With that utf fix and the minRows set to 0 this should be fixed.

**Comment by afoliveira** [comment]
You can make

defaultPageSize {data.length}
