### ISSUE TITLE
[v7] Toggle SortBy title

### ISSUE THREAD

**Issue by ivanov-v** [tannerlinsley/react-table#1760]
How to change default title "Toggle SortBy" in useSortBy hook?

**Comment by gargroh** [comment]
Something like this `column.getSortByToggleProps({ title: 'xyz' })`

**Comment by ivanov-v** [comment]
> Something like this `column.getSortByToggleProps({ title: 'xyz' })`

This works for me. Thanks)

**Comment by manishkc104** [comment]
how do I set the title dynamically do we have some prop on the column that can decide ?
