### ISSUE TITLE
useResizeColumns and useAbsoluteLayout 'position' style

### ISSUE THREAD

**Issue by gargroh** [tannerlinsley/react-table#1761]
Both plugins have `getHeaderProps` style `position`, and `useResizeColumns` overwrites it with `relative` can cause `header` in `useAbsoluteLayout` not follow css, which they were supposed to.
```
  getHeaderProps.push({
    style: {
       position: 'relative',
    },
  })
```

```
const cellStyles = {
  position: 'absolute',
  top: 0,
}
```

**Comment by tannerlinsley** [comment]
Looks like they need to enforce their order

Tanner Linsley

**Comment by tannerlinsley** [comment]
Added an enforcement to keep these in the right order. Will ship today :)

**Comment by tannerlinsley** [comment]
Check out the latest in the changelog with RC.10

**Comment by torkelo** [comment]
They are enforced to be in the wrong order. If useResizeColumns is after useAbsoluteLayout (which is what the enforcement does) it makes header use position relative, breaking the layout
