### ISSUE TITLE
useTokenPagination

### ISSUE THREAD

**Issue by ggascoigne** [tannerlinsley/react-table#1762]
Looks like useTokenPagination hasn't been updated to match the new interface.

**Comment by tannerlinsley** [comment]
Indeed. It's also undocumented and pretty experimental. I've been visiting it with new ideas here and there, but I don't think it's ready for prime time yet.

**Comment by ggascoigne** [comment]
I had to fork an early version to get it doing what I needed - but the token style iteration seems very backend specific.

**Comment by tannerlinsley** [comment]
I would love any feedback or ideas you have for it. Yes I agree, it's pretty specific to something like apollo and graphql vs general token pagination.

**Comment by IanVS** [comment]
I'd really love an example of how to perform token pagination with something like graphql.  Is `useTokenPagination` intended to be used in conjunction with the standard `usePagination`?  It seems like it just exposes some utility helpers, and doesn't really hook into `react-table` at all...
