### ISSUE TITLE
hooks.getRowProps not work on last rc 

### ISSUE THREAD

**Issue by yotavm** [tannerlinsley/react-table#1763]
v7

**Describe the bug**
after moving to the last RC (rc-9) 
using the hooks.getRowProps to update row props not working anymore 

```
hooks.getRowProps.push(row => {
    console.log(row);
    return {
      style: { backgroundColor: "blue" }
    };
  });
```
the good works until rc-2

**To Reproduce**
use rc-2 and above and try use hooks.getRowProps

**Expected behavior**
use the hooks.getRowProps to update the row props

**Codesandbox!**
https://codesandbox.io/s/holy-surf-981q2?fontsize=14&hidenavigation=1&theme=dark

**Comment by gargroh** [comment]
Latest react table has changed internally much from the version for which you have written this thing, you need to return `array` with previous props and keep second argument as your new options, for details open a plugin-hook of react-table

**Comment by tannerlinsley** [comment]
Yep. The plugin api (which is undocumented other than tidbits here and there in the changelog, I know) did change signficantly for prop getters. As @gargroh says, please refer to an existing plugin on master to see how the new interface works. Or you can take a look at the `makePropGetter` function in the `publicUtils.js` file.

**Comment by tannerlinsley** [comment]
Check out the latest in the changelog with RC.10
