### ISSUE TITLE
How to hide columns by default? 

### ISSUE THREAD

**Issue by hellpirat** [tannerlinsley/react-table#1765]
Using v7?

How I can hide some columns by default? I have some logic and if I use toggleHideColumn in React.useEffect - there is some lag  with UI

**Comment by gargroh** [comment]
https://github.com/tannerlinsley/react-table/blob/master/docs/api/useTable.md#usetable

section - `initialState.hiddenColumns: Array<ColumnId: String>`

**Comment by OmarAl-Ayoubi** [comment]
> https://github.com/tannerlinsley/react-table/blob/master/docs/api/useTable.md#usetable
> 
> section - `initialState.hiddenColumns: Array<ColumnId: String>`

link not found

**Comment by dmitrylebedev** [comment]
@OmarAl-Ayoubi, JFYI https://github.com/tannerlinsley/react-table/blob/master/docs/src/pages/docs/api/useTable.md#usetable
