### ISSUE TITLE
[useResizeColumns] User action lags with increase in row and columns

### ISSUE THREAD

**Issue by gargroh** [tannerlinsley/react-table#1766]
When grid has good amount of cells displayed then on column resize - both user action and column re-sizing functionality starts lagging.

Can be reproduced at - 
https://codesandbox.io/s/resize-columns-lagging-9puen
In above example this occurs with 70 rows with ~30 columns, but real world applications will have more render costly `cell`, then this lag would be easily observed by lib users with less data also.

Is there anything we can do to improve this performance(assuming that `cell` renderer is fully optimized) ?

**Comment by tannerlinsley** [comment]
One thing to make sure of is that you're testing this in the production build of react. Drag events in dev mode are usually terrible IMO. Does that change the perf characteristics for you?

**Comment by tannerlinsley** [comment]
I just tested in prod. The reconciliation phase is much much faster, but rendering to v-dom phase is still slow, simply due to the amount of cells. The biggest offender here is `prepareRow`, then after that just the actual renderer. A few ideas from here:

- virtualizing the columns and rows would really speed things up without hurting a lot
- memoizing the actual output of these cells would also speed things up, but also would start to restrict the update-ability of the cells in the future.

**Comment by tannerlinsley** [comment]
Wow, react reconciliation in prod is so fast! :)

<img width="712" alt="Screen Shot 2019-12-12 at 8 49 02 AM" src="https://user-images.githubusercontent.com/5580297/70727067-4842fb00-1cbc-11ea-9669-d7e74d5a0bc9.png">

**Comment by tannerlinsley** [comment]
So, I've added a few micro optimizations here and there for the hot paths of prop getters, cell renders, etc that affect this operation and things are a smidge better. At the end of the day though, if you have a table with this many columns and rows being rendered all at once, it may be time to consider virtualization and/or memoization of renderers.

**Comment by tannerlinsley** [comment]
I think we've taken this as far as we can at the library level. Closing for now.

**Comment by tannerlinsley** [comment]
Check out the latest in the changelog with RC.10

**Comment by Lagily** [comment]
what's the difference with the resizing in react-table-v6? it seems considerably faster out of the box

**Comment by ViieeS** [comment]
> I just tested in prod. The reconciliation phase is much much faster, but rendering to v-dom phase is still slow, simply due to the amount of cells. The biggest offender here is `prepareRow`, then after that just the actual renderer. A few ideas from here:
> 
> * virtualizing the columns and rows would really speed things up without hurting a lot
> * memoizing the actual output of these cells would also speed things up, but also would start to restrict the update-ability of the cells in the future.

How about to not affect cells size until mouse button up? Just need to draw a vertical line and move it, just like in old Windows.

**Comment by xSynack** [comment]
I fixed this by adding react. memo to my table body. Then I passed a custom function to react. memo that would check if any column is resizing and not rerender my row cells until isResizing is false. Iv only tested with 1000 rows in development and performance now is 10/10 when resizing. Hope this helps anyone.

**Comment by zhGio** [comment]
@xSynack could you please share an example on codepen for us non-power users? pretty please?

**Comment by KevinVandy** [comment]
> I fixed this by adding react. memo to my table body. Then I passed a custom function to react. memo that would check if any column is resizing and not rerender my row cells until isResizing is false. Iv only tested with 1000 rows in development and performance now is 10/10 when resizing. Hope this helps anyone.

Do you have the code example for how you did this?

**Comment by Matangub** [comment]
@KevinVandy @xSynack I'm having the same issues and would appreciate a code example too.

**Comment by xSynack** [comment]
@KevinVandy @Matangub Just noticed this, do you guys still need the code example or did you figure it out? Let me know, I can create an example if you still need it.

**Comment by Matangub** [comment]
> @KevinVandy @Matangub Just noticed this, do you guys still need the code example or did you figure it out? Let me know, I can create an example if you still need it.

Yes I still need it I would love an example

**Comment by xSynack** [comment]
> > @KevinVandy @Matangub Just noticed this, do you guys still need the code example or did you figure it out? Let me know, I can create an example if you still need it.
> 
> Yes I still need it I would love an example

Here is a working example rendering 2000 rows with smooth resizing. 

https://codesandbox.io/s/react-table-column-resize-render-fix-lemg3h?file=/src/App.js

**Comment by andresgutgon** [comment]
@xSynack really appreciated for the example 🙏 . The issue I have with this is that column feedback is not reflected while resizing.

**Comment by slavivanov** [comment]
Thanks @xSynack, that's exactly what I needed.

**Comment by kr4chinin** [comment]
> One thing to make sure of is that you're testing this in the production build of react. Drag events in dev mode are usually terrible IMO. Does that change the perf characteristics for you?

That's so true. I was losing my mind for a few days why my table has such a slow resizing. But now I am checking production build and everything works just fine.

**Comment by lou-bi** [comment]
> > > @KevinVandy @Matangub Just noticed this, do you guys still need the code example or did you figure it out? Let me know, I can create an example if you still need it.
> > 
> > 
> > Yes I still need it I would love an example
> 
> Here is a working example rendering 1000 rows with smooth resizing.
> 
> https://codesandbox.io/s/react-table-column-resize-render-fix-lemg3h?file=/src/App.js

Is it still the recommended workaround for v8 ?

**Comment by srgampa** [comment]
Hi, I am using TanStack table to render a not so huge amount of data which has fixed columns and resizing. Now without the tableData inside the table body the sizing is quick but when the data is loaded into the table the sizing is lagging. Now I have some custom widths that are passed from the page. I have used memoization to render the table body with the custom widths. But when after the data is loaded into the table the sizing is lagging after drag and release.
below is table body in my GridLayout component,

    <TableRow key={row.id ?? rowIndex}>
            {row.getVisibleCells().map((cell) => {
              const col = cell.column;
              const stickyStyle = getStickyStyle(col, false);
              const defaultBgColor = rowIndex % 2 === 0 ? "white" : "#E6EEF2";
              return (
                <TableCell
                  key={cell.id}
                  style={{
                    ...stickyStyle,
                    // width: fixedColumns ? col.getSize() + "px" : `${100 / table.getAllLeafColumns().length}%`,
                    width: fixedColumns ? col.getSize() + "px" : col.columnDef.id == "_sno" ? "50px" : col.columnDef.size ? col.getSize() + "px" : `${100 / table.getAllLeafColumns().length}%`,
                    minWidth: fixedColumns ? col.getSize() + "px" : 80,
                    padding: 8,
                    ...(stickyStyle
                      ? {} // If pinned, skip border shorthand
                      : {
                        borderTop: "1px solid #D3D3D3",
                        borderBottom: "1px solid #D3D3D3",
                        borderRight: "1px solid #D3D3D3",
                        borderLeft: "1px solid #D3D3D3",
                      }),
                    // Apply sticky background if it exists, otherwise default color                    
                    backgroundColor: defaultBgColor,
                    // whiteSpace: "normal",
                    // wordBreak: "break-word",
                    whiteSpace: "nowrap",
overflow: "hidden",
textOverflow: "ellipsis",

                  }}
                >
                  {flexRender(cell.column.columnDef.cell, cell.getContext())}
                </TableCell>
              );
            })}
          </TableRow>


is there is a mistake I am doing or anything to be else added to accommodate smooth sizing.


Thanks.
