### ISSUE TITLE
[useFilters] Make filters state array ?

### ISSUE THREAD

**Issue by gargroh** [tannerlinsley/react-table#1767]
Tanner, wanted you to review this before making stable release(don't know whether you have considered or not), `filters` in table state is object `{}`, how about taking it as an `array` [], because filters order(which `object` keys don't guarantee) can matter for `cascading filters` specially when using `preFilteredRows` to show the filterable options on columns.

**Comment by tannerlinsley** [comment]
Yep. We should probably do that. I know that you can *sometimes* rely on key order in an object, but not across machines/interpreters/apis etc. So yes, let's turn it into an array.

**Comment by tannerlinsley** [comment]
This is rolling out shortly. 👍

**Comment by tannerlinsley** [comment]
Check out the latest in the changelog with RC.10
