### ISSUE TITLE
[7.0.0-rc.9] Infinite render loop with useEffect and empty sortBy

### ISSUE THREAD

**Issue by yarinb** [tannerlinsley/react-table#1768]
**Describe the bug**
Somewhere between 7.0.0-beta.12 to 7.0.0-rc.9 there's a change in behavior which causes our useEffect to constantly trigger, when `sortBy` is provided as a dep.

**To Reproduce**
This is our usage of react-table:

```javascript
const Table = ({ columns, data, fetchData, loading, pageCount: controlledPageCount, total }) => {
  const {
    getTableProps,
    getTableBodyProps,
    headerGroups,
    prepareRow,
    canPreviousPage,
    canNextPage,
    pageCount,
    gotoPage,
    nextPage,
    previousPage,
    rows,
    // Get the state from the instance
    state: { pageIndex, pageSize, sortBy }
  } = useTable(
    {
      columns,
      data,
      initialState: { pageIndex: 0, pageSize: 25 }, // Pass our hoisted table state
      manualSorting: true, // Use server side sorting
      manualPagination: true, // Tell the usePagination
      // hook that we'll handle our own data fetching
      // This means we'll also have to provide our own
      // pageCount.
      pageCount: controlledPageCount
    },
    useSortBy,
    usePagination
  );

  const offset = pageSize * pageIndex;

  React.useEffect(() => {
    fetchData(pageSize, offset, sortBy);
  }, [fetchData, pageSize, offset, sortBy]);
```
Initially, `sortBy` is an empty array and it constantly calls the effect function. When replaced with the following code, the effect function is being called once per sort change, as expected.

```javascript
let sortByDep = '';
  if (sortBy.length) {
    sortByDep = Object.values(sortBy[0]).join(",");
  }
  React.useEffect(() => {
    fetchData(pageSize, offset, sortBy);
  }, [fetchData, pageSize, offset, sortByDep]);
```
**Expected behavior**
I'd expect the effect function to accept even an empty `sortBy` as a dep

**Comment by tannerlinsley** [comment]
Looks like sortBy isn't stable for whatever reason. I'll look into this.

**Comment by yarinb** [comment]
So apparently there was an API change. `s/manualSorting/manualSortBy/g'
Making this change seems to solve the problem for me.

**Comment by tannerlinsley** [comment]
Ahhh yep. That'll do it :)

**Comment by Mani4723** [comment]
Hi, 
I have similar issue, I am calling a custom sorting function from useEffect, I am using latest version of react-table and manualSortBy: {true}. But table is getting re-rendered in a loop.
