### ISSUE TITLE
How do I get react-table.css file?  

### ISSUE THREAD

**Issue by mg629** [tannerlinsley/react-table#1769]
When I installed the react-table-7.0.0-rc.9, there was no react-table.css file under node_modules/react-table.

import "react-table/react-table.css" 
causes error "Module not found: Can't resolve 'react-table/react-table.css' in '/project/src'

**Comment by tannerlinsley** [comment]
You are likely looking for version 6, not version 7 (which is the new default install). You'll want to lock into a version in your dependencies eg. `"react-table": "^6.x.x"`

**Comment by tannerlinsley** [comment]
If you were indeed looking for v7, then it's important to note that v7 does not come with styles (or markup) any longer. It's just a collection of custom hooks that you wire up to your own markup and styles.
