### ISSUE TITLE
Issues with row.id in useGroupBy and useRowSelect

### ISSUE THREAD

**Issue by jasonlaw-dev** [tannerlinsley/react-table#1772]
See https://codesandbox.io/s/summer-darkness-v1kox

I have modified the data to only two rows, with repeated firstName
```js
  const [data, setData] = React.useState(() => {
    const data = makeData(2);
    data[0].firstName = "Jon";
    data[0].lastName = "Stark";
    data[1].firstName = "Jon";
    data[1].lastName = "Snow";
    return data;
  });
```
groupBy is set to ["lastName", "firstName"],

When you click the second row's checkbox, you will notice that 3 rows at the bottom are selected instead. useGroupBy is not setting a unique id/path (that includes parent's id in previous versions) for grouped rows, so useRowSelect cannot work out which row is selected

``` js
      groupedRows = Object.entries(groupedRows).map(
        ([groupByVal, subRows], index) => {
          const id = `${columnId}:${groupByVal}`

          subRows = groupRecursively(subRows, depth + 1)

          const values = aggregateRowsToValues(subRows, depth < groupBy.length)

          const row = {
            id,
            isAggregated: true,
            groupByID: columnId,
            groupByVal,
            values,
            subRows,
            depth,
            index,
          }

          groupedFlatRows.push(row)

          return row
        }
      )
```

**Comment by tannerlinsley** [comment]
I’ll roll out a fix for this asap.

Tanner Linsley

**Comment by tannerlinsley** [comment]
Check out the latest in the changelog with RC.10

**Comment by jasonlaw-dev** [comment]
Thanks! Just want to let you know that this library is awesome and it is really fast.

**Comment by tannerlinsley** [comment]
Thanks! Much appreciated. If you wish, consider [becoming a sponsor!](https://github.com/sponsors/tannerlinsley)
