### ISSUE TITLE
[useColumnOrder] Slowness with large number of rows

### ISSUE THREAD

**Issue by gargroh** [tannerlinsley/react-table#1773]
Coming from https://github.com/tannerlinsley/react-table/issues/1713#issuecomment-565008053

Yes, this is a pretty good win, i will say ~3s for 100K rows with 30 Columns is fine, if this was happening only on grid init.

getAccessedRows fn are also calculated whenever user re-orders column(i know this is done to form cells array), due to this every column re-ordering takes a good amount of time and screen freezes for the time being. Is there a way to better this.

Also, for profiling earlier used console time utility was pretty helpful, it would be good if we can get back.

One more thing to mention not having any data to back - it has become bit slow with the latest changes(the one with loophooks etc.). - if you need will do more detailing on it later.

**Comment by tannerlinsley** [comment]
This is fixed now. Will push shortly.

**Comment by tannerlinsley** [comment]
Check out the latest in the changelog with RC.10
