### ISSUE TITLE
Removing a column that is grouped causes an error

### ISSUE THREAD

**Issue by hanvyj** [tannerlinsley/react-table#1776]
**Describe the bug**

When the columns are updated and a column that is currently "grouped by", `useTable` crashes!

**To Reproduce**

1. Go to https://codesandbox.io/s/quirky-carson-i3x8x
2. Group the "First Name" column
3. Click on the "Remove First Name column" button to remove that.
4. See error:
> Uncaught TypeError: Cannot read property 'id' of undefined
>     at eval (index.js:1977)
>     at Array.forEach (<anonymous>)
>     at flatColumns (index.js:1976)
>     at eval (index.js:230)
>     at Array.reduce (<anonymous>)
>     at reduceHooks (index.js:229)
>     at eval (index.js:1193)
>     at updateMemo (react-dom.development.js:16854)
>     at Object.useMemo (react-dom.development.js:17334)
>     at Object.useMemo (react.development.js:1643)
>     at useTable (index.js:1192)
>     at Table (App.js? [sm]:44)

**Expected behavior**
I'd expect the column and grouping to be removed. It should be similar behavior to removing an ungrouped column (see the above example, but grouping "Last Name", or with no grouping at all.

**Codesandbox!**
https://codesandbox.io/s/quirky-carson-i3x8x

**Desktop (please complete the following information):**

- OS: Windows
- Browser chrome
- Version 78.0.3904.108

**Comment by hanvyj** [comment]
Looking at the code:

```
var groupByColumns = groupBy.map(function (g) {
  return flatColumns.find(function (col) {
    return col.id === g;
  });
});
var nonGroupByColumns = flatColumns.filter(function (col) {
  return !groupBy.includes(col.id);
});
```

If the `groupByColumns` contains a column that's not in `flatColumns`, `find` returns `undefined`. A quick patch could be to filter those out:

```
var groupByColumns = groupBy.map(function (g) {
  return flatColumns.find(function (col) {
    return col.id === g;
  }).filter(function (col) {
     return col !=== undefined
  });
});
```

**Comment by tannerlinsley** [comment]
Yep. Would you like to submit a PR for that?

Tanner Linsley

**Comment by hanvyj** [comment]
Sure. I notice you've only got one test per plugin. Would you want to test this scenario? (New test, or modify existing test)

**Comment by tannerlinsley** [comment]
Yes Either way. 😊

Tanner Linsley

**Comment by hanvyj** [comment]
Raised PR https://github.com/tannerlinsley/react-table/pull/1782

**Comment by tannerlinsley** [comment]
Merged!
