### ISSUE TITLE
Typescript broken on 7.0.0 RC, help with declaration

### ISSUE THREAD

**Issue by 4xemme** [tannerlinsley/react-table#1777]
Hi,

I upgraded react-table package in my TS project from 7.0.0-beta.12 to 7.0.0-rc.10
Suddenly it doesn't recognize the package any more

trying to import the hooks
import { useTable, useFilters } from "react-table";

I'm getting the following error
Could not find a declaration file for module 'react-table'
 Try `npm install @types/react-table` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-table'

Is there a TS declaration working for v7?

thanks
/mak

**Comment by JimmyMultani** [comment]
https://github.com/tannerlinsley/react-table/blob/master/TYPESCRIPT.md

We'll have to wait until it gets merged there though, last version that came with types was `7.0.0-beta.23`, so best stick with that until the new types get merged.

**Comment by tannerlinsley** [comment]
Yep. Types are no longer maintained here.
