### ISSUE TITLE
usePagination where pageIndex starts with 0

### ISSUE THREAD

**Issue by gyto23** [tannerlinsley/react-table#1778]
I started using a page pagination with react-table, and I am really confused with a way it written. In other words, `pageIndex` the initial value is 0 which kind of going against all times of the pagination that has numbers. I am not referring any examples of the pagination that react-table has. Some developers, like me, sometimes creating a pagination with numbers and it would be kind of helpful to have initial index of the page to be `1`. On the other hand, it make sense to have both examples of the pagination for the future.

**Comment by tannerlinsley** [comment]
When it comes to zero-index vs one-index approach, it's simple enough to just `pageIndex + 1` if you need to the one-index version, and visa-versa if you need to convert it the other way. I am pretty sure it's not worth maintaining two examples to show this difference.

**Comment by gyto23** [comment]
@tannerlinsley it doesnt make really a sense. I feel like you coming from tech side which is correct and it easy to do `+/- 1` on the `pageIndex`, but from other point of view, are you starting reading book from page `0`? 📚

**Comment by tannerlinsley** [comment]
I'm not disagreeing with you that the real world starts from 1. But you must understand that it's *extremely* commonplace, best practice, standard, and most times inescapable that in the world of programming, indexes start at 0. That's the way it's been for a very very long time and it will continue to be that way for a very very long time. 

But don't dismay! This doesn't mean that you can't *display* the page number in real world terms. This happens every day in almost every application you use. Even the pagination mechanisms on Github itself are zero-indexed when programmed, but formatted to starting at 1 when displayed. If you noticed, every example for React Table shows the page UI as starting at 1.

To punctuate this one last time, **zero-indexed list positions are native to approximately every single programming interface and API on the planet and that programming principle is presumably never going to change.** 

To display a zero-indexed number, simply increment it by one. To accept and use a real-world display number as input (like in a page picker), take the input number (eg. page 1) and decrement it by one (pageIndex: 0).
