### ISSUE TITLE
CodeSandbox Broken for RowSelection Example for v7

### ISSUE THREAD

**Issue by cevinlo23** [tannerlinsley/react-table#1779]
**Describe the bug**
CodeSandbox Broken for RowSelection Example for v7

**To Reproduce**

1. Go to https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/row-selection

**Expected behavior**
Renders Example without CORS error

**Comment by tannerlinsley** [comment]
Refresh the react-table dependency. It is likely resolving a cached version.

**Comment by cevinlo23** [comment]
Thanks so much for the reply. Im still getting used to v7 and have a question about passing the selectedRows state back into a parent component. Before the update you could just pass a callback from the parent into the child as a prop and then have a onClick event call your callback with the row data being sent back to the parent. It seems as though now you will have to use useEffect() or the useRowSelect hook. Do you have any docs or code snippits for best practices for handling this?

**Comment by tannerlinsley** [comment]
For now, there's a few things in the FAQ that might point you in the right direction: https://github.com/tannerlinsley/react-table/blob/master/docs/faq.md#how-can-i-manually-control-the-table-state
