### ISSUE TITLE
Console warning in "Simple->Sub-components" example: Missing unique "key" prop...

### ISSUE THREAD

**Issue by chrisnorwood** [tannerlinsley/react-table#1780]
## Issue:
The following example gets a warning from React, as it introduces a second child <tr> (the expanded row) in each iteration of the row mapping:
https://github.com/tannerlinsley/react-table/tree/master/examples/sub-components

The typical console warning can be seen showing in the CodeSandbox link included with the example, [here](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/sub-components)

### Notes:
I know that the getRowProps() function returns the key, but I'm not sure the best way to tackle updating this example, given the way it's currently written.

**Comment by tannerlinsley** [comment]
The fragment there needs to become an actual React.Fragment component. Then it needs the key prop that would normally be given to the row via getRowProps() or just row.id too would work fine.

Tanner Linsley
