### ISSUE TITLE
pageOptions undefined value array

### ISSUE THREAD

**Issue by gogones** [tannerlinsley/react-table#1785]
![image](https://user-images.githubusercontent.com/19695153/70919245-17afe800-2053-11ea-8176-b6be0fc342ca.png)
pageOptions value is undefined, This was working perfectly fine before. however, when I updated to react-table@7.0.0-rc.10 pageOptions give me undefined value array

**Comment by tannerlinsley** [comment]
As far as I can tell, this is working in the latest RC (and to my knowledge in RC.10, too, but not sure why)

**Comment by MatsJakobsson** [comment]
I am experiencing something similar.
![pageOptions](https://user-images.githubusercontent.com/12683386/71145974-b25f2100-2223-11ea-8b0f-cf6edb929f07.png)

**Comment by tannerlinsley** [comment]
Can you make a sandbox with this I can look at?

Tanner Linsley

**Comment by MatsJakobsson** [comment]
Thank you for your work and the quick response!

Not sure what to expect in you example, but mine does not differ too much and here `pageOptions` contains an array of undefineds:
![pageOptions](https://user-images.githubusercontent.com/12683386/71189098-8fb02500-2282-11ea-95d4-7361f61eb795.png)

**Comment by tannerlinsley** [comment]
Indeed, it's happening for me now. I'll have it fixed asap :)

**Comment by priley86** [comment]
is anyone else still seeing this in `7.0.0-rc.11` ? Just logging `pageOptions` in the Codesandbox pagination example still shows an empty array with the expected page option length. Just curious if that's expected (since it has changed from prior versions).

**Comment by priley86** [comment]
any thought if this should change back @tannerlinsley ? Otherwise, i will just convert it on my side I suppose...

```
const pageOptionsConverted = Array.from(Array(pageOptions.length).keys());
```
