### ISSUE TITLE
Select and display multiple tables on same page

### ISSUE THREAD

**Issue by mg629** [tannerlinsley/react-table#1786]
I want to provide the ability to select a table from a drop down menu or tree (preferably by tree) and have the table display in a specific area on the page.  
If the operator selects a different table from the drop down or tree menu, it will replace/display the newly selected table in this specific area on the page.
Could you point me to a good example to look at for providing this functionality?

**Comment by tannerlinsley** [comment]
This would be the perfect question to ask on our forum: https://spectrum.chat/react-table

Thanks!

**Comment by mg629** [comment]
Thank you.

**Comment by theskillwithin** [comment]
links to 404
