### ISSUE TITLE
Doc useTable API

### ISSUE THREAD

**Issue by xiaoyu-tamu** [tannerlinsley/react-table#1787]
V7.

`reducer: Function(newState, action, prevState) => newState`

should be 

`stateReducer`

DOC: https://github.com/tannerlinsley/react-table/blame/master/docs/api/useTable.md#L28

SRC: https://github.com/tannerlinsley/react-table/blob/d421cb52c550ba39bfa5c2698351967ed5f1e5cc/src/hooks/useTable.js#L35

**Comment by tannerlinsley** [comment]
Yep. Will you PR that change?

**Comment by xiaoyu-tamu** [comment]
Sure, will do it after dinner.
