### ISSUE TITLE
When setting the table to open a later page the Jump to page value doesn't update itself

### ISSUE THREAD

**Issue by lalit7788** [tannerlinsley/react-table#1789]
# Using v6?
Yes, v6.11.5

# Using v7?
No

**Describe the bug**
So my application has a table with `n` pages where `n > 1`. When user clicks on a row (s)he is taken to a details page. There is a custom back button that appends the selected item id in the URL so its row can be shown in bold. This helps the user to know which item was just viewed.

Now normally the list of items is available in the global state so going back isn't a problem. But let's say user reloads the details screen and then tries to go back, in this case the list has to be first re-fetched and then the corresponding row has to be highlighted.

In the latter case, I first find the matched `index` in the array of items and then I get the page number by doing `Math.floor(index / pageSize)` (`floor` because page is index-based). I then set this number to the local state that controls page number. React Table jumps to that page just fine and the row is highlighted without problems. However, the jump-to-page text input still shows page 1.

![image](https://user-images.githubusercontent.com/32096657/70981722-f6ccae80-20b5-11ea-9a82-0b74437ab695.png)

It's interesting to note that if I turn off the page jump feature (`showPageJump={false}`) then it shows the page number correctly.

![image](https://user-images.githubusercontent.com/32096657/70981867-47dca280-20b6-11ea-91ca-51d088bdf208.png)

**To Reproduce**
You could perhaps reproduce the issue with any kind of list and following what I have typed into the description.

**Expected behavior**
I expected the page-jump text input to show the correct page number.

**Codesandbox!**
Use a new [react-table codesandbox](https://codesandbox.io/s/m5lxzzpz69) to reproduce the issue.

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS Catalina
- Browser:  Chrome
- Version: 79.0.3945.79

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tannerlinsley** [comment]
Long-term support for v6 has been moved to the Spectrum Forum here: https://spectrum.chat/react-table. Please post your question/issue there! Thanks!
