### ISSUE TITLE
Sorting negative number doesn't work

### ISSUE THREAD

**Issue by blobinabottle** [tannerlinsley/react-table#1793]
# Using v7

**Describe the bug**
Trying to sort column with negative and positive number doesn't work. It will sort -1, -2, -3, 0, 1, 2, 3... 

**To Reproduce**
1. Go to https://codesandbox.io/s/epic-worker-re09x 
2. Sort column visit

**Expected behavior**
Order should be -3, -2, -1, 0, 1, 2, 3 ....

**Codesandbox!**
https://codesandbox.io/s/epic-worker-re09x

All devices & OS

**Comment by tannerlinsley** [comment]
I believe you will want to use the `sortType: 'basic'` option. `sortType` currrently defaults to `alphanumeric`. You can see more options here: https://github.com/tannerlinsley/react-table/blob/master/src/sortTypes.js

**Comment by blobinabottle** [comment]
Sorry my bad! I thought I tested with basic... but it's working, cool! And thanks!

**Comment by danieldanielecki** [comment]
Please take a look on it https://stackoverflow.com/a/68965542/11127383; that's the only working solution I've found so far.
I'll repost it here:

```
const columns = React.useMemo(
  () => [
    {
      Header: 'Column 1',
      accessor: 'col1', // accessor is the "key" in the data
    },
    {
      Header: 'Column 2',
      accessor: 'col2',
      sortType: compareNumericString // custom function
    },
  ],
  []
)

function compareNumericString(rowA, rowB, id, desc) {
    let a = Number.parseFloat(rowA.values[id]);
    let b = Number.parseFloat(rowB.values[id]);
    if (Number.isNaN(a)) {  // Blanks and non-numeric strings to bottom
        a = desc ? Number.NEGATIVE_INFINITY : Number.POSITIVE_INFINITY;
    }
    if (Number.isNaN(b)) {
        b = desc ? Number.NEGATIVE_INFINITY : Number.POSITIVE_INFINITY;
    }
    if (a > b) return 1; 
    if (a < b) return -1;
    return 0;
}
```

Make sure to use the `sortBy` in the `columns` settings, not in the `useTable`.
