### ISSUE TITLE
Table renders twice on each props change v6

### ISSUE THREAD

**Issue by SergiiTykhenkoNTS** [tannerlinsley/react-table#1798]
**Describe the bug**
As setStateWithData method, that is setting state for table, is called from componentDidUpdate after props are changed it leads to second component render that causes performance issues if table contains a lot of rows

**To Reproduce**

 Change some prop from list: data, columns, pivotBy, sorted, filtered.
See how table renders twice

**Expected behavior**
Table should render just one

**Desktop (please complete the following information):**

- All browsers and devices

**Additional context**
It can be fixed by replacing componentDidUpdate with shouldComponentUpdate or getDerivedStateFromProps.

**Comment by tannerlinsley** [comment]
V6 issues are no longer bringing tacked here on GitHub. Please use our support forum. Thanks!

https://spectrum.chat/react-table
