### ISSUE TITLE
Is full-text search being considered?

### ISSUE THREAD

**Issue by ConAntonakos** [tannerlinsley/react-table#18]

**Comment by tannerlinsley** [comment]
Technically you can already do this. Just add a a text box somewhere and
filter your data before you send it into react table

**Comment by tannerlinsley** [comment]
![screen shot 2016-11-17 at 3 33 46 pm](https://cloud.githubusercontent.com/assets/5580297/20410634/43721880-acdb-11e6-8c01-728e11e4ca9e.png)

**Comment by tannerlinsley** [comment]
I personally prefer https://github.com/kentcdodds/match-sorter from @kentcdodds

**Comment by ConAntonakos** [comment]
> Technically you can already do this. Just add a a text box somewhere and
filter your data before you send it into react table

@tannerlinsley That would have been exactly my approach, but was curious to ask. :) Thanks!

**Comment by tannerlinsley** [comment]
👍

**Comment by mikedevita** [comment]
I've personally used [fuzzy](https://www.npmjs.com/package/fuzzy) search

**Comment by automano** [comment]
@mikedevita What did you do if the array contains undefined elements?
