### ISSUE TITLE
Bug: meta is not properly applied in the loopHooks

### ISSUE THREAD

**Issue by kizu** [tannerlinsley/react-table#1805]
In 7.0.0-rc.14 the function signature of loopHooks should have been changed:

> Changed the function signature for all loopHooks accept a single object of named meta properties instead of a variable length of meta arguments. For example, hooks.prepareRow.push((row, instance) => void) is now written hooks.prepareRow.push((row { instance }) => void)

And in the code for the `prepareRow` hook there is a new signature used:

https://github.com/tannerlinsley/react-table/blob/63d54b1e876d5a04d67e1e8c9e5f1198697cd382/src/hooks/useTable.js#L503-L505

However, in the loopHooks definition the second meta argument is not applied:

https://github.com/tannerlinsley/react-table/blob/63d54b1e876d5a04d67e1e8c9e5f1198697cd382/src/publicUtils.js#L111-L113

So the meta won't be available in the hooks at the moment.

- - -

There is also a typo in the changelog entry: 

> is now written `hooks.prepareRow.push((row { instance }) => void)`

missing a coma, should be:

> is now written `hooks.prepareRow.push((row, { instance }) => void)`

**Comment by tannerlinsley** [comment]
Yeah, I ran into this bug developing the new usePivotColumns hook. I've the fix applied locally. I'll also fix the changelog. :)
