### ISSUE TITLE
Suffering useEffect deps bugs when using `setFilter` instance properties?

### ISSUE THREAD

**Issue by Chun-Lin** [tannerlinsley/react-table#1808]
# Using v7?

Yes.

**Describe the bug**
I built a searchbar outside the table to filter data in the table. I used `setFilter` instance properties to filter my data based-on column id and the keyword. The thing is that I don't really know how to put setFilter as a dependency when I use it inside `useEffect`. Below is the example code

```js
const TableContainer = () => {
   const [searchBarValue, setSearchBarValue] = useState('')

  return (
  <>
    <input
        value={searchBarValue}
        onChange={e => setSearchBarValue(e.target.value)}
     />
    <Table
        searchBarValue={searchBarValue}
     />
  </>)
}

function Table({serachBarValue}){
  const {setFilter} = useTable(
    {
      columns,
      data,
    },
    useFilters,
  )

  React.useEffect(() => {
      setFilter('name', searchValue)
  }, [searchBarValue, setFilter])

  return(/* JSX */)
}
```

If I write like the code above, I will suffer an infinite loop effects, and if I remove setFilter in deps array, it will show useEffect deps warning messages. For now, I just add linter disable comments to avoid that. Is there any better way to use setFilter inside useEffect?

**To Reproduce**

1. I send `searchBarValue` as a prop to `Table`
2. `setFilter` function is placed inside `useEffect`, and set `serachBarValue` and `setFilter` as deps
3. Once the `searchBarValue` changed, it will re-run the effect infinitely

**Expected behavior**
The effect shouldn't be triggered infinitely

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: chrome
- Version: 79

**Comment by reinrl** [comment]
I don't know that this is strictly related to useEffect(). I tried doing something similar by just using setFilter() directly (with a hard-coded value):

```js
function Table({searchBarValue}){
  const {setFilter} = useTable(
    {
      columns,
      data,
    },
    useFilters,
  )

  setFilter('name', 'myvalue');

  return(/* JSX */)
}
```

results in: "Too many re-renders. React limits the number of renders to prevent an infinite loop."

**Comment by Chun-Lin** [comment]
@reinrl , the later code example is what I'm doing right now, and I disabled eslint warning by placing disable comment right above the dep array, but i think `setFilter` should be placed inside deps array just like `dispatch` from `useReducer`.

**Comment by ggascoigne** [comment]
I'm seeing the same sort of thing but with `toggleAllRowsSelected`, looking at the code, some of these dispatchers aren't memoized and so their value changes with every new instance you get back.  Since a common pattern is to use these from within a `useEffect` like:

```ts
  useEffect(() => {
     toggleAllRowsSelected(false)
  }, [selectedCustomer, toggleAllRowsSelected])
``` 
then you quickly land in an infinite loop.

And I really don't want to disable the eslint rule to work around this.

**Comment by Ikos9** [comment]
I'm having the same problem, I pass down `setFilter` to a custom Select that goes on an infinite loop because of a `useEffect` dep.

A temporary fix is to wrap `setFilter` in a `useCallback` hook, even tho there will be a warning cause we are missing a dep.

```
const setFilterTemp = React.useCallback(args => setFilter(args), [])
```

**Comment by VanTanev** [comment]
Same problem with `column.setFilter()`

**Comment by tannerlinsley** [comment]
This is fixed in master and slated for release. Thanks for your help everyone!
