### ISSUE TITLE
Deprecation warnings in React v15.5.0 (React.createClass)

### ISSUE THREAD

**Issue by mkrause** [tannerlinsley/react-table#181]
See:

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

Since v15.5.0, using `React.createClass()` is deprecated in favor of extending `React.Component`.

**Comment by tannerlinsley** [comment]
We will work on moving to the es6 class syntax very soon.

**Comment by tannerlinsley** [comment]
This is fixed in the latest version :)
