### ISSUE TITLE
useGlobalFilter, filtered rows dont take care subRows

### ISSUE THREAD

**Issue by Gi972** [tannerlinsley/react-table#1814]
**Describe the bug**
When I filtered a row the subrows is empty and the subrows dont render.

**To Reproduce**
Go on the codesanbox [react-table codesandbox](https://codesandbox.io/s/react-table-sub-filtered-test-6e4uu)
Choose a statut , that represent a "age" in column age in a subrow. 
The parent has a summary of all age of children.

**Expected behavior**
 The filtered good row with the filtered subrow.

**Codesandbox!**
[react-table codesandbox](https://codesandbox.io/s/react-table-sub-filtered-test-6e4uu) to reproduce the issue.

**Screenshots**

- Browser [ chrome, safari]
- Version lastest

**Comment by tannerlinsley** [comment]
SubRows are filtered out as well. If you need a more custom approach to how global filtering works, then I would suggest extending or replacing the `useGlobalFilter` hook with your own version for now.
