### ISSUE TITLE
Is there a way to load this from a CDN via script tag?

### ISSUE THREAD

**Issue by rajaraodv** [tannerlinsley/react-table#182]
## Problem Description
This is a pretty cool project! I need to test this for an existing app. Is there a way to load this from a CDN via script tag? i.e.e umd or something?

**Comment by tannerlinsley** [comment]
I'll work on getting a UMD build that works for sites like codepen and jsbin.  It will most likely be available at https://unpkg.com/react-table@latest/

**Comment by rajaraodv** [comment]
Cool Thanks, will wait for it.

**Comment by tannerlinsley** [comment]
A UMD build is now available here:
- JS - https://unpkg.com/react-table@5.5.3/react-table.js
- CSS - https://unpkg.com/react-table@5.5.3/react-table.css

If you are using a script tag, it will be available via `window.ReactTable`, and the main component is located at `window.ReactTable.default`.

Here is a Codepen showing how to use it: http://codepen.io/tannerlinsley/pen/QpeZBa?editors=0010

Cheers!

**Comment by serviceform** [comment]
Do we have an UMD build of the v7?

**Comment by gargroh** [comment]
This can be helpful - 

https://unpkg.com/react-table@7.5.0/dist/react-table.production.min.js

**Comment by serviceform** [comment]
My solution was in the end to take the
https://unpkg.com/react-table@7.5.0/dist/react-table.development.js?module

distribution and trim the unneccessary code from top / bottom, ie.

(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('react')) :
  typeof define === 'function' && define.amd ? define(['exports', 'react'], factory) :
  (global = global || self, factory(global.ReactTable = {}, global.React));
}(this, (function (exports, React) { 

Seems to work.
