### ISSUE TITLE
useExpanded must follow useSortBy

### ISSUE THREAD

**Issue by ggascoigne** [tannerlinsley/react-table#1823]
If you load useExpanded before useSortBy and sort by some column other than the one that you are grouping by, then the group rows follow the expanded data in some cases.

**Comment by tannerlinsley** [comment]
Indeed. We'll need to add that as a constraint to one of those plugins.

**Comment by tannerlinsley** [comment]
Fixed in latest commits to master and slated for release. Thanks!
