### ISSUE TITLE
prepareRow hooks are missing the instance reference.

### ISSUE THREAD

**Issue by WreckedArrow** [tannerlinsley/react-table#1824]
**Describe the bug**
The `instance` meta argument isn't passed into the `prepareRow` hooks. With the change to `loopHooks` the third argument [here](https://github.com/tannerlinsley/react-table/blob/9baf3c275b0463f1345fd59403efb9ede4755eb5/src/hooks/useTable.js#L504) is ignored.

**Comment by tannerlinsley** [comment]
Indeed you are correct. This will be fixed in the next release.

**Comment by kizu** [comment]
(just linking a duplicate: #1805)

**Comment by tannerlinsley** [comment]
This is fixed in master and slated for release. Thanks for your help everyone!
