### ISSUE TITLE
Changing the data resets the filters

### ISSUE THREAD

**Issue by avshyz** [tannerlinsley/react-table#1825]
# Using v6?

No

# Using v7?

Yes

**Describe the bug**
Changing the data, for example - when a row is being edited, resets the filters

**To Reproduce**
1. open https://codesandbox.io/s/crazy-brown-qdj7p
This codepen was originally the filters' example codepen, with the following change:
```
const [size, setSize] = React.useState(100000);
  const data = React.useMemo(() => makeData(size), [size])

  useEffect(() => {
    setTimeout(() => {setSize(50); console.log('effect')}, 5000);
  }, [])
```
A small piece of code that changes the data 5 seconds after mount

2. fiddle with the filters (prior to the change in the data)
3. Notice how after the timeout function was triggered, the filters will reset

**Expected behavior**
Changing the data shouldn't reset the filters, as it makes using the filters while editing rows annoying

**Codesandbox!**
see `To Reproduce`

**Desktop (please complete the following information):**

- OS: ios 10.15.2
- Browser: firefox (latest), chrome(79)

**Comment by tannerlinsley** [comment]
I believe you are looking for the `autoResetFilters` option here: https://github.com/tannerlinsley/react-table/blob/master/docs/api/useFilters.md

**Comment by avshyz** [comment]
You're right! Thank you!

**Comment by iKrushYou** [comment]
> I believe you are looking for the `autoResetFilters` option here: https://github.com/tannerlinsley/react-table/blob/master/docs/api/useFilters.md

Link is dead, here's the new one
https://react-table.tanstack.com/docs/api/useFilters
