### ISSUE TITLE
Reconsider [useSort] Add sort order custom sortMethod 

### ISSUE THREAD

**Issue by gargroh** [tannerlinsley/react-table#1826]
@tannerlinsley pls re-consider https://github.com/tannerlinsley/react-table/pull/1615#issuecomment-550261421, just making sure it does not get missed.

Sort direction will be needed in sortMethods for advance cases like mentioned in the given link.

Let me know in case more details are to be provided.

**Comment by tannerlinsley** [comment]
We'll chat there :)
