### ISSUE TITLE
[help] redesign sorting icon

### ISSUE THREAD

**Issue by joesalloum** [tannerlinsley/react-table#1828]
i already did a tweak in css but looking for the proper way 

![image](https://user-images.githubusercontent.com/3799066/71717389-a167ff80-2e20-11ea-98da-b63c7cbbd268.png)

**Comment by gargroh** [comment]
This seems to be related to v6, which is currently not maintained.

**Comment by joesalloum** [comment]
ok thank you so i think i will stick with my css fix

**Comment by tannerlinsley** [comment]
Please use the forum: https://spectrum.chat/react-table
