### ISSUE TITLE
@types/react-table not working for 7.0.0-rc.15 and @types/react-table 7.0.2

### ISSUE THREAD

**Issue by phuzarski** [tannerlinsley/react-table#1834]
I am using typescript in my react project and using:

` "@types/react-table": "^7.0.2",`
`"react-table": "^7.0.0-rc.15",`

I've read the documentation about typing, so I've added in **/src** directory folder file **react-table-config.d.ts**

```import {} from 'react-table'

declare module 'react-table' {
    // take this file as-is, or comment out the sections that don't apply to your plugin configuration
}
```
I've checked the library for @types/react-table and it seems should fit, because in index.d.ts I found info:

>  reflects react-table@7.0.0-rc.15

But it seems still types are missing:

![image](https://i.ibb.co/Bwh08SD/Screenshot-2020-01-07-at-20-03-11.png)

**Comment by ggascoigne** [comment]
How are you importing ReactTable?

**Comment by phuzarski** [comment]
`import ReactTable from 'react-table'`

I also tried
`import * as ReactTable from 'react-table'`

both are not working

**Comment by ggascoigne** [comment]
ReactTable isn’t a component. You should look at some of the examples and see how it’s used.

**Comment by ggascoigne** [comment]
You write your own table component using useTable and then deal with the layout yourself.

**Comment by phuzarski** [comment]
Ok, what a fail. It's my bad, I copy it from some example from internet without checking that. Sorry and thanks!
