### ISSUE TITLE
Issue with Interaction between initialRowStateAccessor and setState

### ISSUE THREAD

**Issue by Akatsukac** [tannerlinsley/react-table#1835]
I'm working with react-table version 7.0.0.rc-15.

When I set initial row state with the initialRowStateAccessor function and then try to access said initial state as part of the row.setState( (prev) => {...}) pattern, prev !== row.state.  I would expect that prev should be equal to what is set in the initialRowStateAccessor.

**Comment by tannerlinsley** [comment]
Could you please spin up a codesandbox that illustrates this issue? That will help me debug much easier.

**Comment by tannerlinsley** [comment]
This is fixed in master and slated for release. Thanks for your help everyone!
