### ISSUE TITLE
Resizing columns with `minWidth` option set is not possible

### ISSUE THREAD

**Issue by Lukas742** [tannerlinsley/react-table#1838]
Version : **7.0.0-rc.15**

**Describe the bug**
When adding the `minWidth` option to table columns, it is not possible to resize the respective columns anymore.

**To Reproduce**

1. Create a table with resizable columns
2. Add `minWidth` and some value to one of the columns in the core columns array.
3. Now all columns except for the one with `minWidth` are resizable.

**Expected behavior**
Columns with `minWidth` enabled should be allowed to be resized to the set minimum.

**Codesandbox!**
https://codesandbox.io/s/jolly-shannon-mytzg
_First column has a `minWidth` of 500, the rest has either `maxWidth`, `width` or none of them set._

**Comment by tannerlinsley** [comment]
You are probably forgetting to take this little block of code into account:

```js
const defaultColumn = React.useMemo(
    () => ({
      minWidth: 30,
      width: 150,
      maxWidth: 400
    }),
    []
  );
```

**Comment by tannerlinsley** [comment]
Thus, if your minWidth is set to 500 and your maxWidth is set to 400, you will not be able to resize the column.
