### ISSUE TITLE
Sort only when sort icon is clicked, not when whole column header is clicked

### ISSUE THREAD

**Issue by JWess** [tannerlinsley/react-table#1839]
I would like to have a sort icon in my header, and I would like to activate the sort only when the icon is clicked, not the whole header. As far as I can tell, for sorting, there is no way to move a column header's `onClick()` handler from the entire `<th>` to a child element of the `<th>`.

**Comment by tannerlinsley** [comment]
You can move the `...getSortByToggleProps()` to whatever element you want to be able to use as the toggle.

**Comment by jantorestolsvik** [comment]
@tannerlinsley that does not work for me. When I move it to another element it reaches the place where it dispatches an action, but it never reaches the reducer. I can't figure out what is happening.

**Comment by aoloo** [comment]
@jantorestolsvik  did you figure this out?

**Comment by jantorestolsvik** [comment]
No, I ended up creating my own tablesetup.

**Comment by cchintada-chikkolu** [comment]
It is working for me as suggested.
` <thead className="bg-dark text-white">
            {headerGroups.map(headerGroup => (
            <tr {...headerGroup.getHeaderGroupProps()}>
                {headerGroup.headers.map(column => (
                <th {...column.getHeaderProps()} className="justify-content-top">
                   {column.canFilter?<span><FaFilter onClick={ () => {column.setFilter('');setFilters({...filters, [`${column.id}`]: !filters[`${column.id}`]})}}/></span>:null}
                   <span className="ms-5 me-5">{column.render('Header')}</span>
                   <span>
                   {column.isSorted
                        ? column.isSortedDesc
                            ? <FaSortUp {...column.getSortByToggleProps()} />
                            : <FaSortDown {...column.getSortByToggleProps()} />
                        : column.canSort?<FaSort {...column.getSortByToggleProps()} />:''}
                    </span>
                    <div>{column.canFilter && filters[`${column.id}`]? column.render("Filter") : null}</div>
                </th>
                ))}
            </tr>
            ))}
        </thead>`
