### ISSUE TITLE
useGlobalFilter custom filtering function doesn't work

### ISSUE THREAD

**Issue by dmitriigaidarji** [tannerlinsley/react-table#1845]
# Using v7?

Thanks for using the beta version of React Table v7! We're very excited about it.

**Describe the bug**
Can't set the custom filter function for the global sort

**To Reproduce**

In filter codesandbox example remove fuzzy filtering

**Expected behavior**
`filterTypes ... text` to be called on `globalFilter` value change

**Codesandbox!**
https://codesandbox.io/s/objective-https-0m4cr

**Comment by dmitriigaidarji** [comment]
Neither column filtering seems to call the `filterTypes` func

**Comment by gendronb** [comment]
In that same line of question, is it possible to disable global filter for specific columns?

**Comment by stevenhuyn** [comment]
I am also interested in how to implement a custom global filter

**Comment by tannerlinsley** [comment]
This is fixed in master and slated for release. Thanks for your help everyone!

@stevenhuyn please ask your question on our spectrum.chat/react-table forum. Thanks!
