### ISSUE TITLE
Cell renderer v6 -> v7 interface change

### ISSUE THREAD

**Issue by kizu** [tannerlinsley/react-table#1849]
Is there a reason the Cell renderer in `columns` needs this change in v7 compared to v6?

v6 | v7
-|-
`Cell: ({ value }) => value` | `Cell: ({ cell: { value } }) => value`

I think the `({ value })` was one of the most used cases, in v7 it becomes a bit more awkward.

What I propose: keep the new `cell` property there with the value inside, but also add back the `value` linked to the same value. This would make a lot of use cases more elegant and easier both to write and read.

**Comment by tannerlinsley** [comment]
I know this is awkward at first, but since you are technically dealing with an extended version of the table instance, but with cell, row, and column information this is more consistent.

**Comment by kuzdogan** [comment]
Is this change not reflected to documentation or am I misinterpreting it? I still see:

![Screenshot from 2020-04-08 14-50-13](https://user-images.githubusercontent.com/13069972/78786049-6d185800-79a8-11ea-9130-9057ee02e560.png)

**Comment by kizu** [comment]
Oops, I did forgot to mention this issue in my recent PR: https://github.com/tannerlinsley/react-table/pull/2073 — from 7.0.1 the `({ value })` is available again.
