### ISSUE TITLE
Clicking column headers selects their text

### ISSUE THREAD

**Issue by dandv** [tannerlinsley/react-table#1850]
**Describe the bug**
Clicking too fast on table headers to change the sort order, selects the column title.

**To Reproduce**
1. Go to https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/sorting
2. Click twice in quick succession on any table header.
3. Notice the selected text:
![image](https://user-images.githubusercontent.com/33569/72384961-3dd1b200-36fd-11ea-8cbd-786cb67b77f6.png)

**Additional context**
Column headings should probably have `user-select: none;`, like the [Material Design table component](https://material-ui.com/components/tables/#sorting-amp-selecting) or [material-table.com](https://material-table.com/#/docs/features/sorting). The interaction of clicking the header twice quickly is not uncommon at all, given that initially the column sort indicator is hidden, and the user doesn't know if after clicking the heading, the direction will be the one they want.

**Comment by MeisterTea** [comment]
The best way to use this libary is by using useTable.
This way, you can do whatever you want with the css.

**Comment by tannerlinsley** [comment]
You can put the toggle props on any component or element you want, not just the header. Please see the advanced examples to see this in action.
