### ISSUE TITLE
Changing sort order changes column width

### ISSUE THREAD

**Issue by dandv** [tannerlinsley/react-table#1851]
**Describe the bug**
Changing the sort order causes the column width to change, which is jarring. This is because the sort indicator toggles between being displayed and hidden.

**To Reproduce**
1. Go to https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/sorting
2. Change the `const data = React.useMemo(() => makeData(2000), [])` to make only 10 rows.
2. Click on any table header 3 times.

**Expected behavior**
Column width should never change when changing the sort order on a table that fits fully on the screen.

**Screenshots**
![react-table chancing sort order changes column width](https://user-images.githubusercontent.com/33569/72385752-e3395580-36fe-11ea-8b8e-f8b1aefc3a42.gif)

**Comment by kizu** [comment]
The `react-table` itself is headless, and this behaviour is just one of the possible implementations of this kind of control and a part of an example. I don't think the library itself should do anything there.

**Comment by tannerlinsley** [comment]
Yep ☝️

**Comment by deepankarmalhan** [comment]
So how do we implement the behavior where the sort doesn't reset the width, are there any docs I can take a look at?

**Comment by Flo0806** [comment]
Hey!

A simple way is to change the style of the span like this:
` <span
                    style={{ position: "absolute", right: "8px", top: "5px" }}
                  >
                    {column.isSorted
                      ? column.isSortedDesc
                        ? " 🔽"
                        : " 🔼"
                      : ""}
                  </span>`
