### ISSUE TITLE
 autoResetSelectedRows does not seem to be working correctly

### ISSUE THREAD

**Issue by ctoppel** [tannerlinsley/react-table#1852]
I am using v7 and have a table using useRowSelect and although autoResetSelectedRows defaults to true, I am changing data on a controlled table (e.g. filtering data and getting new data from the server), yet the checkboxes are not clearing/reseting. I would expect the checkboxes to clear in this instance.

**Comment by tonilxm** [comment]
I am having the same issue on v7.
I am deleting on the rows that are selected and then reload the data but the checkboxes are not being reset, instead checkboxes are selected to same index of previously deleted/selected rows. 
Behavior is correct only when there are only 2 rows and 1 of them is deleted.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4486196/72496857-738dac80-385d-11ea-8d40-81aee80f9bdf.gif)

**Comment by tannerlinsley** [comment]
This is fixed in master and slated for release. Thanks for your help everyone!

**Comment by damianobarbati** [comment]
@tannerlinsley do you have an example of your repo? when removing rows with the button outside the table component, how do you tell to the table to clear the selection?
