### ISSUE TITLE
Row selection works improperly in strict mode.

### ISSUE THREAD

**Issue by jacek-skwarna** [tannerlinsley/react-table#1853]
When user tries to select multiple rows (one by one) then checking one row cause that another rows become unchecked.
You can reproduce the issue by wrapping `<App />` component by `<React.StrictMode></React.StrictMode>`, like: `ReactDOM.render(<React.StrictMode><App /></React.StrictMode>, document.getElementById('root'))` in official sandbox (https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/row-selection) in index.js file.

**Comment by tannerlinsley** [comment]
This is fixed in master and slated for release. Thanks for your help everyone!

**Comment by camflan** [comment]
@tannerlinsley I don't think this is fixed. I vendored react-table and applied your changes (since the above hasn't been published yet), and it's still causing issues in Strict Mode


https://codesandbox.io/s/nervous-blackburn-1u63z?fontsize=14&hidenavigation=1&theme=dark

**Comment by Nuuou** [comment]
Chiming-in on this:
Indeed, I'm experiencing the same issue as noted above. This is on the 7.0.0 release.

Fork of the "Row Selection" demo with Strict Mode added, as per initial comment:

https://codesandbox.io/s/react-table-row-select-strict-mode-broken-0jfbt

I can open a new issue thread if that's preferred!

**Comment by Haimrik** [comment]
I do have the same issue, using this 7.0.0 release.
Removing "React.StrictMode" made the row selection work as expected.

Please, reopen this issue

**Comment by xiaoyu-tamu** [comment]
experiencing the same issue.  7.0.0

**Comment by Debananda** [comment]
@tannerlinsley experiencing the same issues in 7.0.4. https://stackblitz.com/edit/react-xjzb2d
