### ISSUE TITLE
In PaginationComponent (child of rect-table) page props is not updated

### ISSUE THREAD

**Issue by VincenzoCarlino** [tannerlinsley/react-table#1854]
Hi all, I'm using react-table v6.10.3 in server-side so with manual settet to true and a custom pagination component. The page property of react table is linked to a variable of the state. The problem is that when I update this index, the prop page in the child component (PaginationComponent) is not updated, all'others are updated except Page property.

Thanks.

**Comment by EswarNandam** [comment]
Hi @VincenzoCarlino this is happening because you don't have number of rows data required for the page to be rendered. For example, your rows per page are 5, when you are changing your page index the required no of rows data are 6.

**Comment by tannerlinsley** [comment]
Closing since v6 is now deprecated. Please use the forum to discuss older versions.
