### ISSUE TITLE
Keyboard presses not captured for sorting buttons?

### ISSUE THREAD

**Issue by vincerubinetti** [tannerlinsley/react-table#1855]
Possible duplicate of #842

**Describe the bug**
When you add a `tabIndex` to a header `<th>` cell, the user can tab to it with the keyboard. But pressing enter/space to "click" the header does not seem to trigger an `onClick` event like the mouse does to perform the source.

Perhaps I am adding the `tabIndex` in the wrong way? 

**Codesandbox!**
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/sorting

Add `tabIndex="0"` to this line
`<th {...column.getHeaderProps(column.getSortByToggleProps())} >`

It looks like it can be done using the method here: https://spectrum.chat/react-table/general/is-there-a-way-to-activate-sort-via-onkeypress~66656e87-7f5c-4767-8b23-ddf35d73f8af

But it seems like this should be something that's built in.

**Comment by vincerubinetti** [comment]
If anyone stumbles across this in the future, here's a simpler solution than the one linked above:

```javascript
<th
  {...column.getHeaderProps(column.getSortByToggleProps())}
  tabIndex='1'
  onKeyPress={(event) => {
    if (event.key === 'Enter' || event.key === ' ')
      column.toggleSortBy();
   }}
>
```

Still, I think accessibility, especially keyboard accessibility, should probably be built in. Anything that takes a mouse click to activate should probably also accept a keyboard "click" by default.

**Comment by tannerlinsley** [comment]
I would accept a PR to add this functionality by default. Thanks!
