### ISSUE TITLE
Table is not 're-rendered' after row is being dragged to different index.

### ISSUE THREAD

**Issue by tonilxm** [tannerlinsley/react-table#1856]
# Using v7? Yes
Back story: I am following Row Drag and Drop example provided.
Table is not 'updated' after row being dragged to differrent index even when data has changed.

**To Reproduce**
1. Drag row to different index
2. Remove one/many rows in data. 
3. Re-render component
4. Table not 'updated'

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/4486196/72597278-04d54f80-3940-11ea-8476-f1b7ccebb0ec.gif)

**Expected behavior**
After row drag and data changed (row is deleted). Table should be updated with new set of data provided during render. 

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/4486196/72597155-c0e24a80-393f-11ea-99fc-bdc9b1b2d545.gif)

**Screenshots**

**Desktop (please complete the following information):**
- OS: Mac OSX High Sierra 10.13
- Browser: Chrome Version 79.0.3945.117 (Official Build) (64-bit)

**Comment by tannerlinsley** [comment]
It looks like this may be an error with the example, not the library. We'll take a look into this, but since it's not a core library issue, we're going close this for the time being.
