### ISSUE TITLE
pageIndex is not reset on Fully Controlled Component

### ISSUE THREAD

**Issue by gogones** [tannerlinsley/react-table#1857]
**Describe the bug**
If user go to page index 1 or more and then user filter the data, page index isn't reset to 0 but it's still in the last page index user has visited

**Codesandbox!**
https://codesandbox.io/s/manualfiltersdoesntresetpageindex-bs4ud

**Comment by tannerlinsley** [comment]
Fixed in latest commits to master and slated for release. Thanks!
