### ISSUE TITLE
page and flatColumns not ordered based on columnOrder

### ISSUE THREAD

**Issue by BjoernRave** [tannerlinsley/react-table#1861]
I am running in some problems when trying to integrate the column ordering functionality.

When I change the columnOrder of my react-table instance only the header order is updated, but the body order and the flatColumns order stays the same.

For example I have a table with `["foo", "bar", "baz"]` as Columns and when I change the order to `["bar", "foo", "baz"]` the headers of my table change their order accordingly, but the order of the actual columns stays the same, so data of "foo" would have the header of "bar".

Also the flatColumns array doesn't change it's order, which makes my drag-n-drop list of available columns I use to order, be not in sync with the actual order

**Comment by tannerlinsley** [comment]
Fixed in latest commits to master and slated for release. Thanks!

**Comment by BjoernRave** [comment]
@tannerlinsley Thank you for your efforts, really appreciate your work on this library :)
