### ISSUE TITLE
Global search does not update pagination

### ISSUE THREAD

**Issue by r-s-sandbox** [tannerlinsley/react-table#1862]
# Using v7?

Thanks for using the beta version of React Table v7! We're very excited about it.

**Describe the bug**
Global search returns results but does not reset page leading to incorrect pagination behaviour

**To Reproduce**
1. Browse to https://codesandbox.io/s/frosty-sky-su2mk
2. Progress to page 4
3. Type conversation in global search input
4. Pagination says Page 4 of 2

**Expected behavior**
Page should reset to 1 and pagination should say Page 1 of 2

**Codesandbox!**
https://codesandbox.io/s/frosty-sky-su2mk

**Screenshots**

**Desktop**

- OS: OS 10.14
- Browser Latest Chrome
- Version 79

**Comment by tannerlinsley** [comment]
Fixed in latest commits to master and slated for release. Thanks!
