### ISSUE TITLE
Rename componentWillMount to UNSAFE_componentWillMount

### ISSUE THREAD

**Issue by sashasochka** [tannerlinsley/react-table#1867]
Getting this warning in the console. The fix is a very simple CTRL+F-level change, which would get rid of warnings in the browser console.
Same for componentWillReceiveProps.

```
react-dom.development.js:12357 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: ReactTable
```

**Comment by devrsw** [comment]
I'm pretty sure this is not a react-table issue, but an issue with your implementation of it. Try using react table in a functional component instead?

**Comment by sashasochka** [comment]
Nope, it's not. The whole project is written using functional components and it clearly links to ReactTable (see the last line). Actually there is one more similar warning that also points to ReactTablePagination.

```

**Comment by ggascoigne** [comment]
what version of react-table are you using?

**Comment by sashasochka** [comment]
`6.8.4`

**Comment by sashasochka** [comment]
Not seeing the issue anymore. Closing

**Comment by olee2002** [comment]
I set the version to 6.10.0 and I still see the Warning above and it is failing the pipeline.

**Comment by GlistenSTAR** [comment]
I think it's very serious problem.

**Comment by GlistenSTAR** [comment]
hello, I have also this problem. but my error occured on React-native-sliderimage.
can you fix it? pls give me solution.
thank you

**Comment by AbhaysinghBhosale** [comment]
Getting same warnings, i am using 6.8.6
