### ISSUE TITLE
Issue with css modules and styling

### ISSUE THREAD

**Issue by stphnlngdncoding** [tannerlinsley/react-table#187]
I am using webpack 2 with the '['style-loader', 'css-loader?modules']' value for the 'use' property for .css files.  When I remove the modules portion of the string, the table is styled.  When I add the modules string back in, the table is unstyled.  Can anyone explain what's going on?

**Comment by tannerlinsley** [comment]
It appears this is used in the inline require style: https://webpack.js.org/concepts/loaders/#via-require. I have not yet personally upgraded to Webpack 2, so I won't be much help here.  Do other css imports work fine without the `modules` portion?

**Comment by TacticalCoding** [comment]
I think this is less webpack related and more of a css-loader related problem. I'm not too familiar with the modules option but it appears to locally scope css includes.

https://github.com/css-modules/css-modules

When you include the react-table.css file in your project, the css-modules is probably mangling the css names to keep them locally scoped but react-table isn't using the locally scoped css names in it's code.

Are you taking advantage of CSS-Modules in your project?

Do you have any other third party packages that include a global css that are working correctly?

It looks like there have been some discussions around this: https://github.com/css-modules/css-modules/pull/65

You might have to test for the react-table.css file name and exclude it from the module css loader and have a separate css loader that is specifically for globally scoped css packages.

**Comment by stphnlngdncoding** [comment]
Thank you for your help.  To get it working I altered my webpack configuration file to match files with .global.css in them to use the css-loader without the modules param.  Then I copied the react-table.css file from the node_modules folder, renamed it to react-table.global.css, and imported it in to the file.  In case anyone else is interested in the same approach, my webpack rules look like this:
````
{
        test: /\.global.css$/,
        use: [{
          loader: 'style-loader',
        }, {
          loader: 'css-loader',
        }],
      },
      {
        test: /^((?!\.global).)*\.css/,
        use: [{
          loader: 'style-loader',
        }, {
          loader: 'css-loader?modules',
        }],
      },
      {
        test: /\.scss$/,
        use: [{
          loader: 'style-loader',
        }, {
          loader: 'css-loader?modules',
        }, {
          loader: 'sass-loader',
        }],
      },
````

**Comment by rwpetti** [comment]
@stphnlngdncoding's solution worked for me, except I just added his `/\.global.css$/` test block and subbed in `/^((?!\.global).)*\.css/` for my already existing `/\.css$/` regex. worked like a charm!

**Comment by flibustier7seas** [comment]
You can exclude "node_modules"
```js
            {
                test: /\.css$/,
                include: [/node_modules/],
                use: [
                    {
                        loader: "style-loader",
                    },
                    {
                        loader: "css-loader",
                        options: {
                            modules: false,
                        },
                    },
                ],
            },
            {
                test: /\.css$/,
                exclude: [/node_modules/],
                use: [
                    { loader: "style-loader" },
                    {
                        loader: "css-loader",
                        options: {
                            modules: true,
                            localIdentName: "[local]__[hash:base64:5]",
                            importLoaders: 1,
                        },
                    },
                ],
            },
```

**Comment by Johnpc123** [comment]
Including the oldschool style globally is what works when webpack, css modules and react have obfuscated things so much that nothing works.

<link rel="stylesheet" href="node_modules/react-table/react-table.css">

**Comment by escanzanocloudcath** [comment]
Hi, 

I am using Webpack 4.3.x. It looks like this below. Do you have an example of how to change this configuration to accommodate the above mentioned changes? 

Thanks


            {
              test: cssRegex,
              exclude: cssModuleRegex,
              use: getStyleLoaders({
                importLoaders: 1,
                modules: true,
                localIdentName: '[name]__[local]__[hash:base64:5]',
                sourceMap: isEnvProduction && shouldUseSourceMap,
              }),
              // Don't consider CSS imports dead code even if the
              // containing package claims to have no side effects.
              // Remove this when webpack adds a warning or an error for this.
              // See https://github.com/webpack/webpack/issues/6571
              sideEffects: true,
            },
            // Adds support for CSS Modules (https://github.com/css-modules/css-modules)
            // using the extension .module.css
            {
              test: cssModuleRegex,
              use: getStyleLoaders({
                importLoaders: 1,
                sourceMap: isEnvProduction && shouldUseSourceMap,
                modules: true,
                getLocalIdent: getCSSModuleLocalIdent,
              }),
            },
