### ISSUE TITLE
useFlexLayout works incorrectly at small table width

### ISSUE THREAD

**Issue by deser** [tannerlinsley/react-table#1875]
**Describe the bug**
Look at the video: https://recordit.co/KNkCVPFFuB
This is example from documentation: 
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/full-width-resizable-table

**Expected behavior**
Columns should be drawn correctly with small table widths.

**Codesandbox!**
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/full-width-resizable-table

**Comment by deser** [comment]
Oh, seems its already fixed in https://github.com/tannerlinsley/react-table/pull/1846

**Comment by tannerlinsley** [comment]
Fixed in latest commits to master and slated for release. Thanks!
