### ISSUE TITLE
Wrong headers structure with depth >=3.

### ISSUE THREAD

**Issue by cy6eria** [tannerlinsley/react-table#1877]
**Describe the bug**
If I have nesting depth more then two levels, the headers structure is very wired.

**To Reproduce**
Use structure like this:

```
[
      {
        Header: "Personal info",
        columns: [
          {
            Header: "Name",
            columns: [
              {
                Header: "First Name",
                accessor: "firstName"
              },
              {
                Header: "Last Name",
                accessor: "lastName"
              }
            ]
          },
          {
            Header: "Age",
            accessor: "age"
          }
        ]
      },
      {
        Header: "Info",
        columns: [
          {
            Header: "Visits",
            accessor: "visits"
          },
          {
            Header: "Status",
            accessor: "status"
          }
        ]
      },
      {
        Header: "Profile Progress",
        accessor: "progress"
      }
]
```

**Expected behavior**
Don't have a "Personal info" cell on the second level.

**Codesandbox**

[https://codesandbox.io/s/priceless-feather-071wp](https://codesandbox.io/s/priceless-feather-071wp)

**Comment by tannerlinsley** [comment]
Sandbox not found. :(

**Comment by cy6eria** [comment]
Hey @tannerlinsley ! My fault, I accidentally removed sandbox and couldn't restore it due to some codesandbox bug) Now they finally have fixed it and I've restored the example. Can u reopen this issue, coz bug is still there. 

This is how it looks like:

<img width="681" alt="Снимок экрана 2020-03-03 в 12 48 41" src="https://user-images.githubusercontent.com/2938040/75763482-5d747680-5d4d-11ea-902e-a331c32032a3.png">

**Comment by anguyen227** [comment]
I have created sandbox for this issue
@tannerlinsley plz take a look 
https://codesandbox.io/s/crazy-shadow-ui53t?fontsize=14&hidenavigation=1&theme=dark
