### ISSUE TITLE
Drag and Drop example sandbox does not work

### ISSUE THREAD

**Issue by nickshvets** [tannerlinsley/react-table#1881]
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/row-dnd

![image](https://user-images.githubusercontent.com/8167188/73647693-b5538b00-4684-11ea-99f0-b09389092d32.png)

**Comment by tannerlinsley** [comment]
The dependencies need to be updated is all. Fixed in latest commits to master and slated for release. Thanks!

**Comment by niravbhimani53** [comment]
Could you please share which dependencies required to updated or version number to be set for packages?
Also, I couldn't find any commit regarding the fix. Can you please also share that?

**Comment by Floriferous** [comment]
It appears to be broken again, dragging and dropping rows has no effect.
