### ISSUE TITLE
V7 Pagination Input

### ISSUE THREAD

**Issue by wesleywong** [tannerlinsley/react-table#1885]
How we can restrict the input number within the min and max range. Currently, official pagination example also allowed entering more than the maximum number. e.g. 1/100 but in the input field that I allowed entering 1001. Is there a way to be same as V6 to allowed only within the range number.

Official Pagination example - https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/pagination

**Comment by zebrahondje** [comment]
This input is not a part of React Table and I don't think this will ever be so. You're in control of its state and the `onChange` handler which allows you to customize it the way you want. 

Viewing this from a UX-perspective I would suggest to allow any kind of input. When an invalid value is entered, simply show it as an error message. Or use recognized colors like red or yellow.
