### ISSUE TITLE
Unable to get example running

### ISSUE THREAD

**Issue by hendrawidjaja** [tannerlinsley/react-table#1886]
# Using v7?
Yes

**Describe the bug**
Can"t run the example, especially the pagination. 

**To Reproduce**

1. Clone or Download the repo or zip file
2. Chdir to examples/pagination
3. Yarn and Yarn start

**Expected behavior**
A clear and functional working example

- OS: Ubuntu 19.04
- Browser Chrome v79

**Comment by zebrahondje** [comment]
What error?

**Comment by tannerlinsley** [comment]
Not enough to reproduce error. Please try again with more information! (a codesandbox would be great)
