### ISSUE TITLE
Infinite renders while using custom sort function

### ISSUE THREAD

**Issue by Mani4723** [tannerlinsley/react-table#1887]
# Using v7.0.0-rc.15

**Describe the bug**
Trying to implement sort with custom function, but Table is getting into infinite render loops.

**To Reproduce**
Please have a look at the sandbox code.

1. Go to : https://codesandbox.io/s/custom-sort-yfc9b
2. Try sorting one of the columns

- Browser [chrome]

**Comment by XanMK3** [comment]
In App component wrap your fetchData in useCallback hook.
Now it is recreating every render and passing as onChangeSort property here.
```
useEffect(() => {
    onChangeSort({ sortBy });
}, [sortBy, onChangeSort]);
```
So here you'he got an onChangeSort dependency that changes every render.

**Comment by Mani4723** [comment]
Thanks @XanMK3, It is rendering only once now. Can you give me some info about your solution. 

I want to know why infinite renders are happening and how useCallback is rectifying it.
