### ISSUE TITLE
Auto expandable rows and subrows react table using hooks

### ISSUE THREAD

**Issue by ProTipMAX** [tannerlinsley/react-table#1888]
Here we have a code of react table using hooks, and i have struggled on task where I need to set all rows and subrows expanded by default when i open the page, I have tried several solutions, but all of them didn't work.

Link to the code : https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/expanding

Could you suggest proper way to expand absolutely all rows and subrows. For example, parent -> child -> subChild -> subSubChild and so on.

**Comment by ashurathi7** [comment]
+1. 

> release notes say new action _ toggleAllExpanded_ is added but didn't find any handling in the reducer.

One way to do this is to maintain the expanded object by urself and update every time. 
I felt toggleAllExpanded would resolve this.

@tannerlinsley @gary-menzel

**Comment by tannerlinsley** [comment]
This is now supported in master and will be shipped in the next version with utilities like `toggleAllRowsSelected` and even a `getToggleAllRowsSelectedProps` prop getter for the expander header.

**Comment by Vscode-python** [comment]
I faced a related challenge and figured out how to overcome it https://explosive-lev54.github.io/b0Gn7COCAuhmDQ/
