### ISSUE TITLE
When disableMultiSort is true, sortBy still storing multiple sorts and column properties are reflecting the subsequent sorts

### ISSUE THREAD

**Issue by ctoppel** [tannerlinsley/react-table#1889]
This causes UI issues when using the column properties to display sorting icons. If feel that when disableMultiSort is true, that the sortBy array shouldn't grow past one item, and the column properties shouldn't be affected (e.g. column.isSorted or column.isSortedDesc)

**Comment by tannerlinsley** [comment]
I can't replicate this issue in master. `disableMultiSort` disallows there to be more than one sortBy object in the sortBy state and never grows beyond that. Can you replicate in a codesandbox and reopen please?
