### ISSUE TITLE
Change Height based on Click Action

### ISSUE THREAD

**Issue by stephyswe** [tannerlinsley/react-table#1890]
# Using v6?

v6 is now considered feature complete to its current abilities and limitations. We are not actively working to fix any issues for v6 any more. We will, however, merge any non-breaking pull requests submitted to fix anything in v6.

# Using v7?

Thanks for using the beta version of React Table v7! We're very excited about it.

**Describe the bug**

How to SetHeight on Table if clicking a column in React-Table? Using React-Table v7 Hooks from Codesandbox - https://codesandbox.io/s/empty-cherry-w7967x2wm7 ? 

Added a clickable column to open / show a container below Table. But haven't got setHeight working yet. Any ideas? 

**Extra**: Solved issues adding Table into redux App by putting LocationProvider between <Provider /> and < ConnectedRouter /> . Then in index.js I changed<Match />.. to become a component.  Couldn't get Basic to work but ServerByData worked fine. :) 
Also moved columns and data 

PREVIOUS
``` 
<Match
       path="server-side-data"
       component={ServerSideData}
       infinite={infinite}
/>
```
AFTER
```
<ServerSideData
        infinite={infinite}
      />
```
By adding two props ( columns and data)  to ServerSideData.js enables Table to be re-usable 

/examples/ServerSideData.js
BEFORE

```
const serverData = makeData(10000);

// Simulate a server
const getServerData = async ({ filters, sortBy, pageSize, pageIndex }) => {

// Call our server for the data
    const { rows, pageCount } = await getServerData({
      filters,
      sortBy,
      pageSize,
      pageIndex,
    });
```

AFTER
```
_const serverData = makeData(10000); <- remove line

// Simulate a server
const getServerData = async ({ filters, sortBy, pageSize, pageIndex, serverData }) => {

export default function({ infinite, serverData, columns }) { 

// Call our server for the data
    const { rows, pageCount } = await getServerData({
      filters,
      sortBy,
      pageSize,
      pageIndex,
      serverData,
    });
```

/index.js/
BEFORE
`<ServerSideData infinite={infinite}  />`

AFTER
` <ServerSideData serverData={dataToDisplay} columns={adminColumns} />`

**To Reproduce**

**Expected behavior**

**Codesandbox!**
Use a new [react-table codesandbox](https://codesandbox.io/s/m5lxzzpz69) to reproduce the issue.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tannerlinsley** [comment]
Looks good! Make sure you are using the most up to date codesandbox example when tinkering. That one you posted is pretty old. :)
