### ISSUE TITLE
How to know if rendered row is a subRow?

### ISSUE THREAD

**Issue by donperi** [tannerlinsley/react-table#1892]
I want to have a common background color when a row is expanded.
I can easily check if a row is expanded using the `row.isExpanded` prop

But how I can tell if a rendered row is a subrow?

**Comment by tannerlinsley** [comment]
`row.depth` 😄

**Comment by caiorios** [comment]
I am facing the same issue. In my case I want to create a visual tree. Using the depth prop solution made no difference for me, because all rows have value 0 for this prop.
