### ISSUE TITLE
Add rowspan and colspan to header

### ISSUE THREAD

**Issue by spvalencia** [tannerlinsley/react-table#1893]
# STOP

We do not track feature requests through Github. Please use the [Spectrum React Table Forum](https://spectrum.chat/react-table) to talk about new ideas and features.

**Comment by IanVS** [comment]
It seems that Spectrum is also now deprecated?  It would have been nice to see what this feature request at least _was_, so that I can know it isn't something already built into react-table (I'm still learning its capabilities).
