### ISSUE TITLE
Mistake in API documentation: wrong prop name "autoResetGlobalFilter"

### ISSUE THREAD

**Issue by itaizi** [tannerlinsley/react-table#1895]
![image](https://user-images.githubusercontent.com/4322857/74128058-f3046680-4be4-11ea-89cf-af9e323d487a.png)

In documentation prop name is : autoResetGlobalFilter
while in code it is "autoResetGlobalFilter**s**"

**Comment by tannerlinsley** [comment]
This is now fixed in master and will soon be released. Thanks!
