### ISSUE TITLE
Leading Zero doesn't show in the NumberRangeColumnFilter filter

### ISSUE THREAD

**Issue by hybmg57** [tannerlinsley/react-table#1896]
# Using v7?

Thanks for using the beta version of React Table v7! We're very excited about it.

**Describe the bug**
Leading Zero doesn't show in the NumberRangeColumnFilter filter
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/kitchen-sink

```
function NumberRangeColumnFilter({
    column: { filterValue = [], preFilteredRows, setFilter, id },
  }) {
    const [min, max] = React.useMemo(() => {
      let min = preFilteredRows.length ? preFilteredRows[0].values[id] : 0
      let max = preFilteredRows.length ? preFilteredRows[0].values[id] : 0
      preFilteredRows.forEach(row => {
        min = Math.min(row.values[id], min)
        max = Math.max(row.values[id], max)
      })
      return [min, max]
    }, [id, preFilteredRows])
  
    return (
      <div
        style={{
          display: 'flex',
        }}
      >
        <input
          value={filterValue[0] || ''}
          type="number"
          onChange={e => {
            const val = e.target.value
            setFilter((old = []) => [val ? parseFloat(val) : undefined, old[1]])
          }}
          placeholder={`Min (${min})`}
          style={{
            width: '70px',
            marginRight: '0.5rem',
          }}
        />
        to
        <input
          value={filterValue[1] || ''}
          type="number"
          onChange={e => {
            const val = e.target.value
            setFilter((old = []) => [old[0], val ? parseFloat(val) : undefined])
          }}
          placeholder={`Max (${max})`}
          style={{
            width: '70px',
            marginLeft: '0.5rem',
          }}
        />
      </div>
    )
  }
```

**To Reproduce**

1. Go to 'https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/kitchen-sink'
2. Click on Min (0) input box
3. Type 0
4. Cannot see 0

**Expected behavior**
Should see leading 0. This is especially useful if I want to use decimals for the range

**Codesandbox!**
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/kitchen-sink

**Desktop (please complete the following information):**

- OS: MacOS Catalina
- Browser Chrome
- Version 80.0.3987.87

**Comment by tannerlinsley** [comment]
Simply change the value for the rendered input to `value={typeof filterValue[0] === 'number' ? filterValue[0] : ''}` and `value={typeof filterValue[1] === 'number' ? filterValue[1] : ''}` respectively.
