### ISSUE TITLE
Error "Objects are not valid as a React child" on date data type, returning from another component (using browser's back button)

### ISSUE THREAD

**Issue by joseespinadote** [tannerlinsley/react-table#1898]
I had a very strange behavior returning back (through browser's back button) to a component which has ReactTable rendered on it

After clicking in a react-table row, with a react-router "Link" implemented on the accessor, and returning back through browser's back button, got the error: "Objects are not valid as a React child (found [a date here in extended format])"

After some digging, I discovered that a column with dates was generating the error. I solve it changing that date data type, from date to string (a string representing that date), at the backend

I'm using (between others):
- "react": "^16.11.0"
- "react-table": "^6.10.3"
- "react-dom": "^16.11.0"
- "react-redux": "^7.1.1"
- Django 2.2 + DRF  3.9.1 + psql 9.6, as backend
- Opera 65.0.3467.42 as browser

PS.: Sorry for the poor english
PS2.: Couldn't reproduce it at codesanbox or similar, sorry
PS3.: Honestly, thanks for react-table. It's a great component

EDIT: Small format things

**Comment by tannerlinsley** [comment]
You can use dates in react-table, but you must use a formatter in your column's Cell renderer to format the date. eg. if your accessor returned a date object, `Cell: ({ cell: { value }}) => value.toLocaleDateString()`

**Comment by joseespinadote** [comment]
Thanks!

Just comment that is very strange that the error appeared on getting back only

Setting "Cell" is an elegant solution. Thanks again, José.-
