### ISSUE TITLE
useExpanded docs are misleading

### ISSUE THREAD

**Issue by tamopovi** [tannerlinsley/react-table#1899]
The useExpanded docs should be updated.
# Using v7?
Yes.

**Describe the bug**

The function `toggleExpnaded` functionality is described incorrectly (or realization does not follow the description). 
"- `toggleExpanded: Function(?isExpanded: Bool) => void`
  - This function will toggle the expanded state of a row between `true` and `false` or, if an `isExpanded` boolean is passed to the function, it will be set as the new `isExpanded` value."

In reality, `toggleExpanded` toggles the rows expanded state from `true` to `undefined`.
**To Reproduce**
`row.isExpanded `returns `undefined` instead of expected `false`.

1. Open useExpanded CodeSandbox example.
2. In `rows.map(){}`, add `console.log(row.isExpanded);`.
3. Open console.
4. All of the row expanded states are undefined, if toggled, they change to `true` and if toggled again, they change back to `undefined`

**Expected behavior**
Expected the rows expanded state to be `false` if the row is unexpanded/collapsed. Or at least `undefined` at first (when the row wasn't interacted upon) and `false` if it was toggled on and off.

**Codesandbox!**
Adding CodeSandbox with reproduced steps:
https://codesandbox.io/s/useexpanded-toggleexpanded-3mhtn

**Additional context**
I wanted to have different behaviour if rows expanded state is `undefined` or `false` but it seems like the row expanded state can only be either `true` or `undefined`.
Additionally, the `useTable` hook link links to the same page `useExpanded`, not to the `useTable` hook page

**Comment by tannerlinsley** [comment]
Thanks for the heads up. If you'd like, pleas submit a PR to fix the docs how you see fit :)
