### ISSUE TITLE
quick way to get first column to be sticky?

### ISSUE THREAD

**Issue by aliyazdani** [tannerlinsley/react-table#190]
Wondering if currently there is a way to get the first column ( y-axis if you're doing 2 dimensional data) to be a sticky column so that if you have a large table with scroll you can see the categories?
I'm doing a time series as column headers and sometimes the table has a hundred columns so when the user scrolls they wouldn't see the first column that holds the list of metrics - forcing them to keep scrolling back to the first column.

Cheers

**Comment by tannerlinsley** [comment]
Sticky columns are not yet supported. But we will add your request to our
discussions on future features :)
