### ISSUE TITLE
v7 Row selection not working

### ISSUE THREAD

**Issue by evgeniylovejs** [tannerlinsley/react-table#1900]
Using v7

**Describe the bug**
Found bug in my project then checks on your kitchen sink example and there it is also reproduced.
When user apply some filters or globalFilter there is no way to select (or in some cases unselect) rows.

**Steps To Reproduce**

1. Apply any column filter
2. Press several times on row selection checkbox
3. Checkbox are locking

**Codesandbox!**
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/kitchen-sink

- OS: Windows
- Browser Chrome
- Version 7.0.0-rc.15

**Comment by boatcoder** [comment]
Checkbox are locking?  What does that mean?

Checkboxes aren't updating?  It is because you aren't triggering a re-render.  Click a couple of checkboxes and page down and back up.  When you do that, they are selected and it displays.  Need to make sure you trigger a re-render for them to show up.

**Comment by evgeniylovejs** [comment]
> Checkbox are locking? What does that mean?
> 
> Checkboxes aren't updating? It is because you aren't triggering a re-render. Click a couple of checkboxes and page down and back up. When you do that, they are selected and it displays. Need to make sure you trigger a re-render for them to show up.
> 
> Check this sandbox . https://codesandbox.io/s/table-with-checkbox-rb9mk

In yours example:
1. Put "legs" string in Alias column filter.
2. Select any row
3. Try to unselect this row

Actual result - unselect not working.

**Comment by boatcoder** [comment]
Interesting.  I see this happening in the sandbox.  I don't see it happening in my storybook though.

**Comment by boatcoder** [comment]
I'm seeing `isSelected` always set to false in the useRowSelect reducer
```
      if (action.type === actions.toggleRowSelected) {
        const { id, selected, } = action;
        const { flatGroupedRowsById, } = instance;

        // Join the ids of deep rows
        // to make a key, then manage all of the keys
        // in a flat object
        const row = flatGroupedRowsById[id];
        const isSelected = row.isSelected;
        const shouldExist = typeof selected !== 'undefined' ? selected : !isSelected;

        if (isSelected === shouldExist) {
          return state;
        }
```

row.isSelected never seems to be true which causes this failure.  In the debugger, I see the UI uncheck and recheck after the reducer.

**Comment by tannerlinsley** [comment]
Yep, looks like an inconsistency between the useFilters plugin and the useRowSelect plugin. Will dig in.
