### ISSUE TITLE
I think toggleAllRowsSelected is doing the wrong thing.

### ISSUE THREAD

**Issue by boatcoder** [tannerlinsley/react-table#1901]
# Using v7
## Selecting/Deselecting All that are filtered should not affect non-filtered rows
Currently the toggleAllRowsSelected always clears the selection and creates a new one.  That shouldn't happen, it should add to or remove from the selection, not completely reset it and restart with an empty selection.

## To Reproduce
Using this sandbox:  https://codesandbox.io/s/table-with-checkbox-rb9mk
* Sort by something and then select a few rows
* Filter by something that causes those rows to disappear and a small subset to display
* Use the header to select all
* Remove the filter and the first 2 rows are unchecked (may need to re-sort to see them, but that is another issue with the example)

## Expected behavior
I can add to and remove from the global selection while a filter is in place without affecting things that are not filtered

**Codesandbox!**
https://codesandbox.io/s/table-with-checkbox-rb9mk

React-Table Version 7.0.0-rc.15

Browser versions don't matter

*Additional context**
Here is a better reducer for useRowSelect and how I had to patch it in my code because replacing the reducer is almost impossible without this kind of hack:
```
  const useFixedRowSelect = (hooks) => {
    useRowSelect(hooks);
    hooks.stateReducers.pop();  // Remove the damaged reducer

    function reducer(state, action, previousState, instance) {
      if (action.type === actions.init) {
        return {
          selectedRowIds: {},
          ...state,
        };
      }

      if (action.type === actions.resetSelectedRows) {
        return {
          ...state,
          selectedRowIds: instance.initialState.selectedRowIds || {},
        };
      }

      if (action.type === actions.toggleAllRowsSelected) {
        const { selected, } = action;
        const { isAllRowsSelected, flatRowsById, } = instance;

        const selectAll =
      typeof selected !== 'undefined' ? selected : !isAllRowsSelected;

        // Only remove/add the rows that are visible on the screen
        //  Leave all the other rows that are selected alone.
        const selectedRowIds = Object.assign({}, state.selectedRowIds);

        if (selectAll) {
          Object.keys(flatRowsById).forEach((rowId) => {
            selectedRowIds[rowId] = true;
          });

        } else {
          Object.keys(flatRowsById).forEach((rowId) => {
            delete selectedRowIds[rowId];
          });
        }

        return {
          ...state,
          selectedRowIds,
        };
      }

      if (action.type === actions.toggleRowSelected) {
        const { id, selected, } = action;
        const { flatGroupedRowsById, } = instance;

        // Join the ids of deep rows
        // to make a key, then manage all of the keys
        // in a flat object
        const row = flatGroupedRowsById[id];
        const isSelected = row.isSelected;
        const shouldExist = typeof selected !== 'undefined' ? selected : !isSelected;

        if (isSelected === shouldExist) {
          return state;
        }

        const newSelectedRowIds = { ...state.selectedRowIds, };

        const handleRowById = (id) => {
          const row = flatGroupedRowsById[id];

          if (!row.isGrouped) {
            if (!isSelected && shouldExist) {
              newSelectedRowIds[id] = true;
            } else if (isSelected && !shouldExist) {
              delete newSelectedRowIds[id];
            }
          }

          if (row.subRows) {
            return row.subRows.forEach((row) => handleRowById(row.id));
          }
        };

        handleRowById(id);

        return {
          ...state,
          selectedRowIds: newSelectedRowIds,
        };
      }
    }
    hooks.stateReducers.push(reducer);
  };

  useFixedRowSelect.pluginName = useRowSelect.pluginName;
```

And this is how I'm using that
```
const tableObject = useTable(
    {
      columns,
      data,
      defaultColumn,
    },
    useBlockLayout,
    useResizeColumns,
    useFilters,
    useSortBy,
    useFixedRowSelect
  );
```

**Comment by tannerlinsley** [comment]
First off, the fact that you can remove a core reducer and replace it with your own is just freaking awesome. I love this plugin system lol. 

Yeah this looks like a bug. Would love for you to submit a PR with these changes to the reducer and improve the existing useRowSelect.test.js file to account for this.

**Comment by boatcoder** [comment]
Ok

**Comment by boatcoder** [comment]
I think to test this I'm going to need to build a combination scenario that includes filtering AND selecting which steps outsides the bounds of "unit" testing.  An alternative would be to fake a bunch of state and export the reducer for direct testing.

I did the former.

**Comment by tannerlinsley** [comment]
Tracking your PR. Thanks :)

**Comment by tannerlinsley** [comment]
Merged.
