### ISSUE TITLE
https://unpkg.com/react-table@latest/react-table.css is missing from CDN

### ISSUE THREAD

**Issue by akomakom** [tannerlinsley/react-table#1902]
# Using v6?

Yes

**Describe the bug**

CDN-hosted **react-table.css** that is referenced [from the documentation](https://www.npmjs.com/package/react-table/v/6.10.0#installation) is missing:

https://unpkg.com/react-table@latest/react-table.css

**To Reproduce**

1. Go to 'https://unpkg.com/react-table@latest/react-table.css'
2. see error:
```Cannot find "/react-table.css" in react-table@7.0.0-rc.15```
Note that it's redirecting to 7.0, not 6.0

**Expected behavior**

CDN should redirect to 6.0

**Comment by tannerlinsley** [comment]
Oooo this is awkward, but the latest version of React Table doesn't ship with CSS or any markup for that matter. Take a look at the examples for the latest version and you'll see why.

**Comment by akomakom** [comment]
@tannerlinsley has the latest version been released?  I see only **rc** tags and "npm install" gets me 6.0

**Comment by tannerlinsley** [comment]
@latest should give you react-table@7.0.0-rc.15 which, yes, is a release candidate.

**Comment by akomakom** [comment]
The part I was missing was that I could substitute "@latest" with a version, eg:

https://unpkg.com/react-table@6.0.0/react-table.css

(just guessed it)
