### ISSUE TITLE
Filtering doesn't work if rows are collapsed when grouping is enabled

### ISSUE THREAD

**Issue by tekrei** [tannerlinsley/react-table#1903]
# Using v6?

No

# Using v7?

Yes:  `"react-table": "7.0.0-rc.15"`

**Describe the bug**
With grouping enabled, filtering of columns doesn't work when rows are collapsed (their aggregation is empty). The filtering on non-grouped columns only works when rows are expanded.

**To Reproduce**
When rows are collapsed try filtering non-grouped columns (see the codesandbox)

**Expected behavior**
I expect column filter should work even rows are collapsed

**Codesandbox!**
https://codesandbox.io/s/serene-bouman-1td5k

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser Chrome
- Version 78

**Comment by tannerlinsley** [comment]
This is because of the plugin order (which is now warned against in the latest version in the master branch, release is on the way) Thanks!

**Comment by RohithMeganathan** [comment]
I am using version 8 of the Tanstack table, but the grouping filter in sub-rows is not working propery,  https://codesandbox.io/p/sandbox/github/tanstack/table/tree/main/examples/react/expanding?embed=1&file=%2Fsrc%2Fmain.tsx%3A293%2C22 
I cannot find any update regarding grouping filter in sub groups works or not in V8. Kindly update it
