### ISSUE TITLE
Reopen: Moving from beta 13 to RC15 caused infinite looping while onFetchData 

### ISSUE THREAD

**Issue by chozze** [tannerlinsley/react-table#1911]
Cannot reopen #1904 so I am creating new report.

'SortBy' or 'filters' are causing refresh of 'onFetchData' function - with or without a React.useCallback.

https://codesandbox.io/s/flamboyant-villani-7p0n3

**Comment by tannerlinsley** [comment]
Dats you update to the latest RC version?

**Comment by chozze** [comment]
yes, RC16 is used

**Comment by chriscerk** [comment]
Also getting infinite loop with 
- `React.useCallback` 
- Setting 
``` yaml
 manualSortBy: true,
 manualPagination: true,
 manualFilters: true,
```
- and following the below faq section:

**How do I stop my table state from automatically resetting when my data changes?**

https://github.com/tannerlinsley/react-table/blob/35d36db4c92c21fed4d15440f87ddfe043017640/docs/faq.md#how-do-i-stop-my-table-state-from-automatically-resetting-when-my-data-changes

It seems that either `pageIndex`, `pageSize`, `sortBy`, or `filters` on the state is changing (despite it not changing) when external data changes. Unless there is some other state triggering `onFetchData` to get called infinitely on external data changes.

Going to be using manual callbacks in my filter, sort, etc elements until this is resolved.

**Comment by chozze** [comment]
@chriscerk, did you temporarily resolve this using manual callbacks? Mind sharing your code?

thanks Ales

**Comment by tannerlinsley** [comment]
I'm still unable to replicate this, even with the sandbox provided. A really simply replicable use case would be great and fast. Looking to get v7 stable out the door asap.

**Comment by chozze** [comment]
Hello, just use the https://codesandbox.io/s/admiring-sammet-juz8r andchange the react-table component to rc16 to replicate the issue.

**Comment by zebrahondje** [comment]
> Hello, just use the https://codesandbox.io/s/admiring-sammet-juz8r andchange the react-table component to rc16 to replicate the issue.

I did exactly that, but you're I think you forgot to pass the `manualSorting` option here. That fixes it.

**Comment by tannerlinsley** [comment]
Indeed. If you are controlling the sortBy externally, then you must pass `manualSorting` which does fix the issue.
