### ISSUE TITLE
Data is not updating even if the data is mutated 

### ISSUE THREAD

**Issue by dhamodharan-baskar-e3171** [tannerlinsley/react-table#1912]
Need to perform sort action outside react table and just the pass the data to react table 
but i cant able to fine any props or function to trigger that update or to notify react-table to use the latest sorted data

**Comment by tannerlinsley** [comment]
You must immutably update the data object you are passing to react table or at the very least make a new copy of it

**Comment by Androsv96** [comment]
I'm using  onRowUpdate: (newData, oldData) =>
Then I'm cloning my react-table data this way: let data = {...myStore}.
then, I'm updating data with the newData argument, then I'm dispatching an action to update my store with the new updated data but the table does not re-render with the new data, it stays the same.

**Comment by tannerlinsley** [comment]
Correct. `data` must be a new object if you want the table to updated. `oldData` should not `===` your `newData`
