### ISSUE TITLE
Breaking changes should be published only in major versions (https://semver.org)

### ISSUE THREAD

**Issue by c-cal** [tannerlinsley/react-table#1913]
Renamed instance.flatColumns to instance.allColumns in v7.0.0-rc.16, cause legacy app crash after a yarn install... Is a RC considered to be a major release, in which case it should not be used in production?

**Comment by tannerlinsley** [comment]
RC is technically a beta so you should be locking to a specific version and expecting possible but Unlikely breaking changes with every release.
