### ISSUE TITLE
Example for 'Expanding' is not working on Code Sandbox

### ISSUE THREAD

**Issue by carlosrberto** [tannerlinsley/react-table#1914]
After the last release this example stopped working

https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/expanding

**Comment by tannerlinsley** [comment]
Works great for me! Make sure it’s cache busted

**Comment by carlosrberto** [comment]
You are right, It's some cache issue. I tried from another connection and it's working.
