### ISSUE TITLE
Resize: Finding or Adding Class to current Resizing column 

### ISSUE THREAD

**Issue by RaghulXander** [tannerlinsley/react-table#1916]
I have been using react-table just few days ago only and been stuck with this queries

Is there a way to know that current `column` in a table is being resized currently ?
Do we have any `props` to add a `className` to the column which is resized currently ?

The reason behind this is to highlight the column header which is getting resized.

Version: `6.11.5`

**Comment by tannerlinsley** [comment]
We can keep working on your PR (or the new one I asked if you'd open), but I don't plan on tracking v6 issues here any more, so closing this for triage. Keep going on that PR!

**Comment by RaghulXander** [comment]
@tannerlinsley I have re-worked added this an enhancement feature please have a look into it .
Just a minor change
