### ISSUE TITLE
useColumnVisibility - resetHiddenColumns is never called

### ISSUE THREAD

**Issue by ta-anders** [tannerlinsley/react-table#1919]
Using the latest react-table v7.

**Describe the bug**
The `resetHiddenColumns` action is not being dispatched when table data/columns change. You can see that it is not used anywhere in the implementation [here](https://github.com/tannerlinsley/react-table/blob/master/src/hooks/useColumnVisibility.js#L10).

So the `columns` prop can change but the `hiddenColumns` state will remain the same. In my use case, this is causing some unexpected behaviour when switching between two tables in the UI with different columns:

- When `columns` changes, often the `initialState.hiddenColumns` changes. But the internal `hiddenColumns` state is not being reset to the initial state, meaning the hidden columns for the new table are not applied correctly.
- If they happen to have overlapping column IDs. For example, the user might hide the "name" column in table 1 and then switch to table 2 to find it also hidden for this table.

**To Reproduce**
1. Create a `Table` instance with some `columns`.
2. Pass in a new value for `columns`.
3. The `hiddenColumns` state will not be reset.

**Expected behavior**
The `hiddenColumns` state should be reset to the initial state.

**Desktop:**

- OS: macOS Catalina
- Browser: chrome
- Version: 78.0.3904.108

**Potential solution**
I think the `useColumnVisibility` hook should dispatch the reset action using the `useMountedLayoutEffect`, as in the other hooks (e.g [useFilters](https://github.com/tannerlinsley/react-table/blob/master/src/plugin-hooks/useFilters.js#L286)). I'm not sure if the reset needs to be controllable with a parameter like `autoResetFilters`. Further I'm not sure what the correct dependency for that effect is - if it is `data`, `columns` or both. Just `columns` makes sense to me given that is what is relevant for the hidden column state.

Happy to make a PR for this if my explanation makes sense!

**Comment by tannerlinsley** [comment]
Would love a PR doing what you suggested: Fire the reset action using `useMountedLayoutEffect` when `columns` change. Make it configurable using an `autoResetHiddenColumns` option, similar to the other plugins. 😄
