### ISSUE TITLE
isAllRowsExpanded does not filter out non-expandable rows

### ISSUE THREAD

**Issue by lwhiteley** [tannerlinsley/react-table#1921]
# Using v7?

```js
 Header: ({ getToggleAllRowsExpandedProps, isAllRowsExpanded }) => (
          <span {...getToggleAllRowsExpandedProps()}>
            {isAllRowsExpanded ? '👇' : '👉'}
          </span>
        ),
```

**Describe the bug**
`isAllRowsExpanded` does not take into consideration rows that are not expandable

if i have 5 rows and only 4 are expandable then `isAllRowsExpanded` is still false

**Comment by lwhiteley** [comment]
to be more precise, im not sure if its something to support but when i manually exapand all expandable rows, the `isAllRowsExpanded` bit doesnt update.

**Comment by Tommoore96** [comment]
Did you find a solution to this?

**Comment by lwhiteley** [comment]
Decided not to support the behaviour and was no longer required by my app. Came to this conclusion after reviewing various similar solutions. 

The toggle all button for all that I reviewed doesn't actually update for most of these solutions.
