### ISSUE TITLE
[Documentation] Primitive not defined

### ISSUE THREAD

**Issue by gDelgado14** [tannerlinsley/react-table#1926]
**Describe the bug**

Documentation is unclear on what a *primitive* value is.

My assumption currently is that a primitive is:

- string
- number
- boolean

Is there anything else that react-table defines as primitive?

**Expected behavior**

Documentation should explicitly list out what react-table defines as a primitive.

**Comment by tannerlinsley** [comment]
Yes that is correct. See https://developer.mozilla.org/en-US/docs/Glossary/Primitive for more information.
