### ISSUE TITLE
[Documentation] useTable column options: `accessor` is not required

### ISSUE THREAD

**Issue by gDelgado14** [tannerlinsley/react-table#1927]
Version: 7.0.0-rc.16

**Describe the bug**
The `useTable` [docs](https://github.com/tannerlinsley/react-table/blob/master/docs/api/useTable.md#column-options) currently state that `accessor` is required. However, when looking at examples (such as [expanding rows](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/expanding) - look at the expander column object. It has no `accessor` field.), it is clear that it is indeed not required, and that the table works fine.

Perhaps the code sandbox example isn't using the API correctly? What are the consequences of not passing an accessor?

**Comment by tannerlinsley** [comment]
`accessor` is almost always required, but as long as you have a unique `id` for a column, it technically doesn't need one. This is used for things like expander or row selection columns. It's more required than not, so it makes sense to label it as such, then teach that it is in fact optional under few circumstances. Labeling it as optional would create mass hysteria :)

**Comment by gDelgado14** [comment]
> so it makes sense to label it as such, then teach that it is in fact optional under few circumstances. Labeling it as optional would create mass hysteria :)

Hey @tannerlinsley ... I don't quite agree that you should assume that react-table users aren't competent enough to make a judgment call on their own. 

You could still mark the field as required and add your comment above explaining that technically speaking it's not required if you pass in a unique `id` column. 

Would you be ok with me opening a PR to add this info to the `useTable` docs?

**Comment by tannerlinsley** [comment]
I never assumed anyone’s incompetence and pardon my exaggeration. I’m simply referring to the teaching and education process of learning react table’s API. If as a first time viewer of the docs, a user see that an accessor is optional, they would likely make their own assumption that as a beginner, an optional configuration would not be required to get started and be productive.

I would still like it to remain labeled as required and I think it’s perfectly acceptable to add a comment to the docs that covers the this edge case.
