### ISSUE TITLE
Render method doesn't log errors

### ISSUE THREAD

**Issue by daniloprates** [tannerlinsley/react-table#193]
## Problem Description
When using the `column.render` method, with an error inside, no error will be logged.

## Code Snippet(s)
```js
  columns[0].render = ({ row }) => (
    <div>
        {row.nonExisting.variable}
    </div>
  );

```

## Steps to Reproduce
1. Write a custom working method for a column using `.render` 
2. Make it break, using a non existent variable, for example.
3. The component won't render, but no error will be logged.

## System Information
* **Browser & Browser Version: Chrome 58.0.3029.54
* **Node Version: v6.9.5
* **OS Version: MacOS 10.11.3 
* **NPM Version: 5.3.3
* **Yarn Version:**

**Comment by tannerlinsley** [comment]
That's very interesting.  Any ideas?

**Comment by tannerlinsley** [comment]
Replicating your example into any storybook entry, the error is properly logged.

<img width="1232" alt="screen shot 2017-04-17 at 9 17 07 am" src="https://cloud.githubusercontent.com/assets/5580297/25093252/a7bbfb3c-234e-11e7-8b2c-a5622ea45a41.png">

This is most likely an issue with your local setup.  It's possible that your components are wrapped somewhere with a promise or try and any caught errors are being silently swallowed.

To be sure, you should follow the contributing setup in the readme and try changing one of the stories to see if it behaves correctly on your machine.

**Comment by daniloprates** [comment]
hey @tannerlinsley thanks for checking this out and the feedback. I'll have a look.

**Comment by tannerlinsley** [comment]
Closing for now, as it seems this is not an issue with an unmodified build of the library.  Please reopen if you find anything else that we may have missed :)

**Comment by daniloprates** [comment]
sure thing, thanks
