### ISSUE TITLE
GlobalFilter not filtering on data subrows

### ISSUE THREAD

**Issue by arnoBruynseels** [tannerlinsley/react-table#1930]
**Describe the bug**
The Global Filter does not filter on data subrows out-of-the-box.

**To Reproduce**

1. Implement Global Filtering (useGlobalFilter) with **manualGlobalFilter = false** (default)
2. Implement Row Expansion (useExpanded)

**Expected behavior**
The Global Filter, also filters on the subrows of data default out-of-the-box without any custom filtering needed.

**Codesandbox!**
[codesandbox](https://codesandbox.io/s/inspiring-breeze-cf1gm?fontsize=14&hidenavigation=1&theme=dark)

**Desktop:**

- OS: Windows 10
- Browser: Chrome
- Version: 80.0.3987.116

**Comment by tannerlinsley** [comment]
As far as I know this is working now in your codesandbox with the latest version. Thanks

**Comment by noahbenham** [comment]
@tannerlinsley Was this behavior recently corrected? I’m seeing sub-rows failing to global filter using rc16, agnostic of the useExpanded plugin.

**Comment by tannerlinsley** [comment]
To my knowledge yes. But it could be a regression we haven’t tested for.

**Comment by arnoBruynseels** [comment]
@tannerlinsley I'm not seeing this working in my codesandbox.

Steps to reproduce:

1. Expand a row
2. Type in the global filter the value of some column of the expanded row
3. No results are found

**Comment by uqix** [comment]
@arnoBruynseels `useFilters` and `useGlobalFilter` only filter subRows of rows which match the filter first, you can flatten rows to avoid this, [FYI](https://github.com/uqix/reactkit-table/blob/master/src/filter/flatten.js)

**Comment by arnoBruynseels** [comment]
@uqix Would you be so kind to provide a codesandbox example?

**Comment by lajerca** [comment]
@tannerlinsley  Any update on this?  Not working as far as I can see (with latest version) in the provided sandbox. @uqix is right, the filter works only if parent rows match too. If the solution is using flatRows with manual global filter, a CodeSandbox would be cool!

**Comment by shabeebcoder** [comment]
{
    Header: 'Client Name ',
    Footer: 'Last Name',
   
    accessor: (props) => (
      <>
        <div class="text-sm text-gray-900">{props.clientname}</div>
        <div class="text-sm text-gray-600">{props.country}</div>
        <div class="text-sm text-gray-400">{props.clientstatus}</div>
      </>
    ),
  },

With custom cell (like above) global filter is not working 

if i change code above to following(below) then global filter work with this cell
  {
    Header: 'Client Name ',
    Footer: 'Last Name',
   accessor: 'clinetname"
  },


is there any way to fix global filter with custom cell ?

**Comment by rajeshkannam** [comment]
Hi All, @arnoBruynseels has explained cleared with CodeSandbox. i am also struck with same problem. could you please share the solution with example (CodeSandbox would be better) if any one knows. Thanks

**Comment by amplicity** [comment]
This issue is resolved here https://github.com/TanStack/table/discussions/3828
