### ISSUE TITLE
Explicitly setting Cell to undefined in a column definition causes a render error 

### ISSUE THREAD

**Issue by mikegoatly** [tannerlinsley/react-table#1931]
**Describe the bug**
Using v7. When defining a column, if you specifying a `Cell` explicitly as `undefined` rather than omitting it, you get a renderer error.

**To Reproduce**

1. Go to the basic sample: https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/basic
2. Change:
```
...
columns: [
{
    Header: 'First Name',
    accessor: 'firstName',
},
...
```

to 
```
...
columns: [
{
    Header: 'First Name',
    accessor: 'firstName',
    Cell: undefined
},
...
```

3. Save the page, see error

**Expected behavior**
Setting `Cell` to `undefined` should have the same behavior as omitting it, i.e. no render error should occur and it should be as if `Cell` hasn't been specified.

**Codesandbox!**
https://codesandbox.io/s/friendly-blackwell-3o6q2

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Edge (chromium)
- Version 81.0.416.6

**Comment by tannerlinsley** [comment]
Omitting vs setting to undefined is not the same actually. This is shown when spreading properties across objects:

```js
const foo = { bar: 1 }
foo = { ...foo, bar: undefined }
// foo == { bar: undefined }
```

So in this case as it stands today, you should not explicitly Cell to `undefined`. If you really want to support that out of the box, then I would happily accept a PR to add that functionality :)
