### ISSUE TITLE
PageIndex does not update in controlled component

### ISSUE THREAD

**Issue by r-s-sandbox** [tannerlinsley/react-table#1935]
rc-v16

##Describe the bug
Not sure if this is a bug or whether I have to control page index manually since its a fully controlled component, but triggering a global search or column filter returns results but does not reset page index leading to incorrect pagination behaviour

##To Reproduce
Browse to https://codesandbox.io/s/elegant-cherry-fbrei
Progress to page 2
Type some text from page 2 in global search input or column filter
Pagination says Page 2 of 1

##Expected behavior
Page should reset to 1 and pagination should say Page 1 of 2

##Codesandbox!
https://codesandbox.io/s/elegant-cherry-fbrei

##Desktop
OS: OS 10.14
Browser Latest Chrome
Version 81

**Comment by zebrahondje** [comment]
See https://github.com/tannerlinsley/react-table/issues/1883

**Comment by arnoBruynseels** [comment]
Issue is still present in version **7.0.0-rc.16**

**Comment by tannerlinsley** [comment]
Fixed in bfcc08e7eb66d0bb86bbda0d3f40cf2319e304b3

**Comment by karnamanirudh** [comment]
I have a similar kind of issue, i have implemented redux to store the pageIndex value as i am using multiple instances of react table, as i want to maintain state for each react table. When i click on next page i dispatch an action to store the pageIndex value in reducer. When i navigate to second page and if i apply global filter then the pageCount shows 2 of 1. The pageIndex is set to 1, and doesn't update on filtering the values.

react-table version : 7.7.0
Thanks!

**Comment by 5no0p** [comment]
Issue is still present in version 7.7.0

**Comment by sergecheban** [comment]
Does not seem to help, but I think that might be the desired behavior when using `manualPagination` for most people.

**Comment by Sadeghbayan** [comment]
this is still an issue
