### ISSUE TITLE
makePropGetter always results in fresh properties causing render thrash

### ISSUE THREAD

**Issue by ggascoigne** [tannerlinsley/react-table#1936]
I'm not completely sure that this is a bug so much as a problem where the best fix might end out being in react-table.

Due to the nature of makePropGetter, you can guarantee that repeated calls to methods such as `getToggleRowSelectedProps` will generate new objects. Where the top level values are primitives then this tends to not cause problems since the results are often destructured and passed to a component, but when they are objects, such as `styles`, this fails simple equality checking and leads to a spam of re-renders.  Non-memoized callbacks have the same problem.

Not quite sure yet whether this is best handled in the table or by memoizing the UI components, but thought it was worth bringing up.

**Comment by tannerlinsley** [comment]
I'll look into this as part of the stable release 👍

**Comment by tannerlinsley** [comment]
After some deep thinking on this issue, I think I've come to the conclusion that this is going to be the best we can do for now. As of today, all if not most uses of `makePropGetter` are going to return fairly stable props other than inline callbacks created or composed style objects. In those cases that styles or callbacks are created, I think this is in line with the React docs and common practices as it is highly unusual that inline style objects and inline callbacks actually result in overrendering and when they do (as you pointed out), there are tools like `useMemo` or `React.memo` that let you break out of that. Alternative ways of constructing these props would not be simple or maybe not even possible, given that the nature of react hook memoization is tied to the instance of the parent component and not to something variable like the amount of rows. We would have to build our own memoization solution that could operate on a variable amount of items across the entire library. So while it is *technically* possible, I think the pros don't justify the cons here. I am totally open to discussing this as the library grows though and use cases arise. For now I don't think this is a blocker to get v7 out though. I really appreciate your attention to detail here though. It's helped me validate some of the core architecture of the library.
