### ISSUE TITLE
SubComponent lost selection when extended

### ISSUE THREAD

**Issue by Gi972** [tannerlinsley/react-table#1942]
Hello,

When I Use the table with option expandSubRows to false and a extended row, I lost the selection event.

If I put at true, I have the selection but expanded rows appears.

Before I could extend the row  and have the selection in a subrow with the preparedRow.

You can see a example here:

https://codesandbox.io/s/condescending-architecture-3sy9r

Extend the row and select and deselect the checkbox in the subcomponent. You can see the parent don't deselect.

But when I put expandSubRows option at  true it's working.

**Comment by tannerlinsley** [comment]
This codesandbox example is pretty contrived (I'm not sure what it's trying to achieve just yet) but as far as I can tell, the checkboxes are working and selecting just fine. Could you please reopen with a simpler example or more precise steps to replicate the issue?
