### ISSUE TITLE
Columns with the same ID are silently de-duped

### ISSUE THREAD

**Issue by tobz1000** [tannerlinsley/react-table#1944]
[**CodeSandbox**](https://codesandbox.io/s/shy-glade-0o4kb)

**To Reproduce**:
1. Specify multiple column descriptors for your table with the same ID.
2. Only the last column with this ID will be rendered.

**Expected behaviour**: It would be better to warn the user that this deduplication is being performed, or throw an error.

The sandbox is a trivial example, but in my case it was because I switched from string accessors to functions, without manually adding IDs to each column. A user might also be generating column descriptors programmatically, and not realise that they're reusing the same ID.

**Comment by tannerlinsley** [comment]
This will no longer happen with the next RC. Stay tuned.
