### ISSUE TITLE
[v7] Table state is lost when data is updated

### ISSUE THREAD

**Issue by gargroh** [tannerlinsley/react-table#1949]
When i am updating data, then table state is reset to initial, is this the expected behavior or i am missing something. 

Can be replicated at - https://codesandbox.io/s/trigger-change-in-data-causing-state-reset-mlxzt

Steps :-
1. Sort any Column, current state is rendered
2. Then use `update data` btn to update data
3. SortBy state of table is lost, ideally it should preserve user's state.

**Comment by gDelgado14** [comment]
This is expected behaviour.

See `autoResetRowState`:

https://github.com/tannerlinsley/react-table/blob/7dc9b8516543e72410e5dc5ed6ebc10c198df45b/docs/api/useRowState.md

**Comment by gargroh** [comment]
Cool, thanks for it...just cross checking without seeing docs...does this autoReset exists for all features/plugins..

**Comment by gargroh** [comment]
Cool, thanks a ton for that.
