### ISSUE TITLE
Table overflow option

### ISSUE THREAD

**Issue by karankumar89** [tannerlinsley/react-table#195]
Hey! This is a pretty cool table, i was wondering is there a way have overflow on the table while having the headers fixed?

**Comment by tannerlinsley** [comment]
Though it is not recommended for usability, this is possible with some extra CSS. Please post your question to the slack channel for more information.

**Comment by karankumar89** [comment]
Cool! Can i get an invite to the slack channel?

**Comment by tannerlinsley** [comment]
I'm on my phone traveling, but you could click the react chat badge on the
readme for now

**Comment by karankumar89** [comment]
That works! Thanks!

**Comment by bartvde** [comment]
@karankumar89 did you get this fixed? I'm looking for the same thing actually.

**Comment by bartvde** [comment]
Ah found it here: https://github.com/tannerlinsley/react-table/wiki/Fixed-headers-with-scrollable-table-body
