### ISSUE TITLE
Warning: Invalid prop `role` supplied to `React.Fragment` at a console

### ISSUE THREAD

**Issue by chuikoffru** [tannerlinsley/react-table#1951]
**Describe the bug**
Display at the console: Warning: Invalid prop `role` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.

**To Reproduce**

1. Go to https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/sub-components
2. Click on the Console button
3. See error

**Expected behavior**
Clear console logs

**Codesandbox!**
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/sub-components

**Desktop (please complete the following information):**

- OS: macOS
- Browser Chrome
- Version 80.0.3987.106 (Official Build) (64-bit)

**Additional context**
Everything works, but I think it needs to fix.

**Comment by gargroh** [comment]
You can use html element instead of fragment for removing this react warning.

OR

Get these props in object, delete role prop and then provide to Fragment.

**Comment by tannerlinsley** [comment]
Yep ☝️ This is all in userland. The only prop a fragment should really ever get is a `key` prop for iteration tracking. Other than that, it doesn't make much sense to put other props on a fragment.

**Comment by bbohling** [comment]
@tannerlinsley - while I agree that this is all in userland, I think it is lame to use a bad approach in examples. adding additional HTML elements would be another bad approach IMO as then it would be "bad" HTML semantics. If I come up with a "good" solution I will submit a PR for the documentation

**Comment by dipenparmar12** [comment]
We have this good solution(example) in official docs as well. If anybody interested. 
https://react-table.tanstack.com/docs/examples/sub-components-lazy

**Comment by PaulAtkins88** [comment]
> We have this good solution(example) in official docs as well. If anybody interested. https://react-table.tanstack.com/docs/examples/sub-components-lazy

This link just diverts to v8 home page
Issue is still current in v7?
