### ISSUE TITLE
multi-level columns

### ISSUE THREAD

**Issue by artico16** [tannerlinsley/react-table#1952]
imagine I need some sort of a master-detail views where each level - master and detail has their own set of columns, and their own set of headers. Also it would be nice to have unrestricted nesting of levels, so set of columns and headers on each level might be different. As I see currently grid supports only top level columns and headers. Can you suggest how to implement 'multi-level columns' currently ? Or it requires some core re-architecturing of current solution ?

**Comment by Michielnuyts** [comment]
I'm looking for something very similar, basically, parts of a row can recursively have another body. I'm pretty sure I'll have to do some custom implementation for that. Maybe the custom hooks can be of help here.

**Comment by artico16** [comment]
Currently headers go apart from rows. I think, could it be something like row can not just be only a data row, but a header row ?, So e.g. first row in subRows collection to be a 'header' row and cells be drawn accordingly ?

**Comment by tannerlinsley** [comment]
Don't make this harder than it should be :) You can easily implement the "sub component" pattern using this example: https://github.com/tannerlinsley/react-table/tree/master/examples/sub-components and in your sub component renderer, simply render another table.
