### ISSUE TITLE
sorting is not toggled properly when used with custom 'sortType' callback function 

### ISSUE THREAD

**Issue by malek-abbassi** [tannerlinsley/react-table#1953]
# Using v7

Hi there! First of all thanks for all your efforts in creating such a great library. 

**Bug Description**
I did encounter a rather strange problem with the latest version (v7.0.0-rc.16): when I use a custom function for sorting, the results are sorted for one direction only. 
P.S: same code works fine with v7.0.0-rc.15

**Additional context**
here is the code for the custom sorting function
```
const sortHelper = ({
	isAfter,
	isBefore,
	desc
}) => {
	let order

	if (isAfter) {
		order = 1
	} else if (isBefore) {
		order = -1
	} else {
		order = 0
	}

	if (desc) {
		return -order
	} else {
		return order
	}
}

const sortString = (rowA, rowB, columnId, desc) => {
	const stringA = rowA.values[columnId].trim().toLowerCase()
	const stringB = rowB.values[columnId].trim().toLowerCase()

	const isAfter = stringA > stringB
	const isBefore = stringA < stringB

	return sortHelper({
		isAfter,
		isBefore,
		desc
	})
}
```
here the code for the table component
```
const OverviewTable = (props) => {
	const columns = [
		{
			Header: <span>{translate({ text: 'FIRSTNAME' }).text}</span>,
			accessor: 'firstname',
			sortType: sortString
		},
		{
			Header: <span>{translate({ text: 'LASTNAME' }).text}</span>,
			accessor: 'lastname',
			sortType: sortString
		}
	]

	const data = props.data

	return (
		<Table columns={columns} data={data} />
	)
}
```

**Comment by arwandar** [comment]
Probably the same problem here: the ascending sort works well, but not the descending sort.
Here a [sandox ](https://codesandbox.io/s/sort-problem-42x42)where you can see the result for on the age column.

**Comment by XanMK3** [comment]
It looks like the api is changed. I'm not a maintainer but I'm watching the repo and I think there was some discussion about sorting and removing `desc` parameter from sort function.
I'm not sure if it is documented now.
Looks like it works if I change the sorting function this way:
```
  const customSort = React.useCallback((rowA, rowB, columnId) => {
    return rowB.values[columnId] - rowA.values[columnId];
  }, []);
```
Working example:
https://codesandbox.io/s/sort-problem-e17oq

**Comment by gargroh** [comment]
Sort Comparator function should return `-1 || 0 || 1`.

Boolean will not work.

```If the result is negative a is sorted before b.

If the result is positive b is sorted before a.

If the result is 0 no changes are done with the sort order of the two values.```

**Comment by mattstates** [comment]
Is there a good pattern for having a sort function only sort the items at depth === 0? I would like subRows to stay with (directly under) the "parentRow" when expanded.

**Comment by tannerlinsley** [comment]
@mattstates, please ask your question in https://spectrum.chat/react-table :) Thanks!
