### ISSUE TITLE
Reset filters no longer works

### ISSUE THREAD

**Issue by DaveSweeton** [tannerlinsley/react-table#1954]
I'm using v6, and running into a bug that was introduced recently. Upgrading to v7 isn't feasible at this time.

I'm controlling the filtered property externally so that I can implement a "Reset Filters" button. My setup matches this answers on SO: https://stackoverflow.com/a/48093712

This used to work in 6.10.3, but is broken in 6.11.1 through 6.11.5.

Setting the filtered property of the react-table no longer triggers a data fetch.

**Comment by tannerlinsley** [comment]
V6 is no longer maintained here, nor are we tracking issues for it here. You can ask your question in the forum though! https://spectrum.chat/react-table
