### ISSUE TITLE
useRowState cellState is calling cell column ID

### ISSUE THREAD

**Issue by gyto23** [tannerlinsley/react-table#1957]
From the last update I mention that state of the cellState have changed and now it depending on the `cell.column.id`, meaning that it will narrow down the object and put the value as is, when originally it was based on the object it self and then per cell I could select the option I wanted. Is there will be an option just narrow down to the object as it was before `row.state.cellState` but not `row.state.cellState[cell.column.id]`

Regarding to this line:
```
row.cells.forEach(cell => {
        cell.state = row.state.cellState || {}

        cell.setState = updater => {
          return setCellState(row.id, cell.column.id, updater)
        }
 })
```

that was changed to 
```
row.cells.forEach(cell => {
      if (!row.state.cellState) {
        row.state.cellState = {}
      }

      cell.state =
        typeof row.state.cellState[cell.column.id] !== 'undefined'
          ? row.state.cellState[cell.column.id]
          : initialCellStateAccessor(row.original)

      cell.setState = updater => {
        return instance.setCellState(row.id, cell.column.id, updater)
      }
    })
```

**Comment by tannerlinsley** [comment]
I'm not entirely sure what you're asking. The API changed to keep state located in a safe place whereas before it was easily clobbered and not very centrally located on the row. 

More info please?

**Comment by gyto23** [comment]
@tannerlinsley By default cell gets initial state of object which also expect to have a column ID as a cell state:
For example row state is `{cellState: { fooBar: "baz" }}` in this case it will give a cell a state of `"baz"`, as I remember originally cell state would get entire state of the given property of `{ fooBar: "baz" }`.

I am just wondering why it was changes, and if will be changed later to control your own state shape without calling a `row.state.cellState[cell.column.id]` as initial state of the cell

**Comment by tannerlinsley** [comment]
I believe it was changed to both give more control and to also be more in line with the cells having their own space in the row state:

```js
row.state = {
  ...customRowState,
  cellState: {
    [column.id]: ... 
  }
}
```

I guess if it helps, you can think of it more like `cellState(s)` plural, where each cell in the row is referenced by its corresponding column ID.

**Comment by tannerlinsley** [comment]
If this does end up being a bug, we can fix it post release. Thanks!
