### ISSUE TITLE
Missing indeterminate prop of getToggleHiddenProps in column

### ISSUE THREAD

**Issue by gyto23** [tannerlinsley/react-table#1958]
I mention that property like `getToggleRowSelectedProps` contain an `indeterminate` of false which is really convenient in the usage of `<IndeterminateCheckbox/>` component. However, `getToggleHiddenProps` is missing same property of `indeterminate`, but exist in `getToggleHideAllColumnsProps`.

**Comment by tannerlinsley** [comment]
It technically could exist on the individual column objects. You're the first person to ask for this, so I would gladly accept a PR to either implement this or discuss how it could be done :)

**Comment by gyto23** [comment]
@tannerlinsley sure I can add it, later, when I have time
For those who wondering how it was implemented in my code:
```
<IndeterminateCheckbox
      indeterminate={false}
      {...column.getToggleHiddenProps()}
/>
```
