### ISSUE TITLE
Download table options

### ISSUE THREAD

**Issue by Nitin123-4** [tannerlinsley/react-table#1959]
Is there any wat we can download the tables as csv, xlsx, or PDF etc?
I am using it in the R markdown HTML report.

# STOP

We do not track feature requests through Github. Please use the [Spectrum React Table Forum](https://spectrum.chat/react-table) to talk about new ideas and features.

**Comment by gargroh** [comment]
This may be useful to you...https://github.com/tannerlinsley/react-table/pull/1941

**Comment by tannerlinsley** [comment]
Yeah, for now this is not build in, but all of the information is readily available in the object that `useTable` returns.
