### ISSUE TITLE
Translate Options ?

### ISSUE THREAD

**Issue by JigsWeb** [tannerlinsley/react-table#196]
Hi, i'm french and my english is limited, so sorry.

I decide to use your component, great job ;)

I want to translate some word like "Previous", "rows" etc.. I know i can override their components but for just a translation, i think a translate option is a plus.

Thank you for your reading and your futur answers !

**Comment by JigsWeb** [comment]
My bad, RTFM sorry guys.

**Comment by dmr** [comment]
I have the same issue --> @JigsWeb where do I find this in the manual?

**Comment by JigsWeb** [comment]
Hi, in props part, you can found:

`{..., 
  previousText: 'Previous',
  nextText: 'Next',
  loadingText: 'Loading...',
  noDataText: 'No rows found',  
  pageText: 'Page',
  ofText: 'of',
  rowsText: 'rows'
}`

**Comment by dmr** [comment]
Cool, thank you!
