### ISSUE TITLE
Material-UI Enhanced Table example not working

### ISSUE THREAD

**Issue by pjshu** [tannerlinsley/react-table#1961]
# Using v7

**Describe the bug**
I clone Material-UI Enhanced Table and run yarn install && yarn start
![2020-03-06 22-03-59 的屏幕截图](https://user-images.githubusercontent.com/47631325/76090415-80758380-5ff6-11ea-9b4d-55f0b7cc61bc.png)

**Desktop (please complete the following information):**

- OS: [ubuntu 19.10]
- Browser [chrome]
- Version [latest]

## fixed:
just add like this
![2020-03-06 22-08-55 的屏幕截图](https://user-images.githubusercontent.com/47631325/76090771-1f01e480-5ff7-11ea-9e2a-73a1732db9ec.png)

```
if (hooks.allColumns && hooks.allColumns.push) {}
```

**Comment by riceboyler** [comment]
It probably needs to have the dependency updated to `7.0.0-rc.16`.

**Comment by riceboyler** [comment]
FWIW, it works fine on the Code Sandbox: https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/material-UI-enhanced-table.

Can you check what version of react-table is actually installed locally for you?

**Comment by riceboyler** [comment]
@pjshu I was able to reproduce what you're seeing. For some reason, yarn is resolving `react-table@latest` to version "7.0.0-rc.15" in this folder.

![CleanShot 2020-03-06 at 09 10 01](https://user-images.githubusercontent.com/2243596/76100660-45d60180-5f8a-11ea-938c-4a8fd37e7d07.png)

**Comment by pjshu** [comment]
> FWIW, it works fine on the Code Sandbox: https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/material-UI-enhanced-table.
> 
> Can you check what version of react-table is actually installed locally for you?

sorry,replay you after 11 hours ,
```
├─ react-table@7.0.0-rc.15
```

**Comment by pjshu** [comment]
> 7.0.0-rc.16

yes,when i update to `7.0.0-rc.16.` ,this problem is solved
