### ISSUE TITLE
Sort not working with float numbers

### ISSUE THREAD

**Issue by carlosrberto** [tannerlinsley/react-table#1967]
When one of the columns has float numbers and we sort by that column the result looks incorrect.

See this example, try to sort by the "Profile Progress" column:
https://codesandbox.io/s/wrong-sort-2n8fk

<img width="176" alt="Screen Shot 2020-03-09 at 23 08 12" src="https://user-images.githubusercontent.com/679481/76261715-e2362780-625a-11ea-9a6e-cda2de261c3b.png">

**Comment by tannerlinsley** [comment]
The default sorter is an alphanumeric one here: https://github.com/tannerlinsley/react-table/blob/127a7fca8754f6289b6bc019dbd1fc4bcdd13187/src/sortTypes.js#L6

You need to use the `sortType: 'basic'` for now if you want exact sorting for floats: https://codesandbox.io/s/wrong-sort-w60ff

**Comment by carlosrberto** [comment]
@tannerlinsley unfortunately this option doesn't solve my problem. It works if we have only positive float numbers. On my case I have a mix of positive, negative and null values, the `basic` doesn't work.

**Solved** using `sortType` with a custom sort function.

One note regarding the custom sort function, the [documentation](https://github.com/tannerlinsley/react-table/blob/master/docs/api/useSortBy.md#column-options)  says that there is a `desc` param:
```
sortType: String | Function(rowA: <Row>, rowB: <Row>, columnId: String, desc: Bool)
```
But this value is always `undefined`.

**Comment by ianstormtaylor** [comment]
Maybe it would be better to have the `alphanumeric` type be named `string` instead? 

I saw the current name and just assumed it handed floats, since floats are "numeric". Whereas if I saw that the default was `string` that might have helped me track down this bug way earlier.

**Comment by alexanderholmberg** [comment]
So I have a unfortunate problem. I have floats that I want to sort, and I want them to be sorted descending by default. The problem is that when I don't use sortType: 'basic', the floats aren't sorted correctly. If I however use sortType: 'basic', then the floats are sorted correctly but they are now no longer sorted by default... How do I solve this?

**Comment by mariam-ali-k** [comment]
// Added logic to fix sorting issues with decimal numbers, as DataTable treats all data as strings
      {
        targets: [1, 2, 3, 4],
        render: function (data, type, row, meta) {
          if (type == "display") {
            return data;
          }
          return parseFloat(data);
        },
      },
