### ISSUE TITLE
manualPagination with pageCount set to -1 does not work

### ISSUE THREAD

**Issue by vkbansal** [tannerlinsley/react-table#1972]
**Describe the bug (required)**
When using `manualPagination: true` along with `pageCount: -1`, pagination does not work.

**Provide an example via Codesandbox! (required)**
Reproducible in example
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/pagination-controlled

**Steps To Reproduce (required)**

1. In the example, change `pageCount` to `-1`
2. Try clicking on next/prev buttons

**Expected behavior (Recommended)**
Pagination should work according to [this line of code](https://github.com/tannerlinsley/react-table/blob/master/src/plugin-hooks/usePagination.js#L156)

**Comment by tannerlinsley** [comment]
Actually, this line is blocking it from working: https://github.com/tannerlinsley/react-table/blob/master/src/plugin-hooks/usePagination.js#L49

**Comment by tannerlinsley** [comment]
Would you like to submit a PR to fix this?

**Comment by vkbansal** [comment]
Sure. I'll try opening one in sometime.

**Comment by TimNZ** [comment]
@tannerlinsley 

Doing a quick pull request to update the usePagination docs to document this situation as I had to google and stumbled on this issue.

How's this look?

```
- `pageCount: Int`
  - **Required if `manualPagination` is set to `true`**
  - If `manualPagination` is `true`, then this value used to determine the amount of pages available. This amount is then used to materialize the `pageOptions` and also compute the `canNextPage` values on the table instance.
  - Set to `-1` if you do not know or want to present the number of pages available.  `canNextPage` will now return `false` if page data length is less than pageSize, otherwise `true`.
```

**Comment by tannerlinsley** [comment]
Looks good!
