### ISSUE TITLE
useRowSelect - checked rows on different pages

### ISSUE THREAD

**Issue by junste** [tannerlinsley/react-table#1979]
Hi,

React table v7.0.0-rc.16.
I use the useRowSelect hook and I’ve also implemented my own pagination, asking for new data from server when going to a new page.
If I check some rows on the first page, go to page 2, check some rows there as well and then return to the first page, my previously checked rows
are unchecked. Is that the expected behaviour? That selected rows only apply on the current page?

Regards,
Stefan

**Comment by j3ernhard** [comment]
I have the same issue, what is the expected bahaviour?

**Comment by tannerlinsley** [comment]
Please upgrade to the latest stable release, create a codesandbox that demonstrate the issue and reopen please :)

**Comment by zombiQWERTY** [comment]
+1
