### ISSUE TITLE
Support for headers on Expander columns

### ISSUE THREAD

**Issue by zachcoyle** [tannerlinsley/react-table#198]
There doesn't seem to be the option to have a header on an expander column. 
I was wondering if this would be a possibility? 

thanks

**Comment by tannerlinsley** [comment]
That's a good question. We will look into this.

**Comment by TacticalCoding** [comment]
This is now possible in version 5.6.0. See the [Custom Expander Story](http://localhost:8000/?selectedKind=2.%20Demos&selectedStory=Custom%20Expander%20Position&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel) for an example.

**Comment by zachcoyle** [comment]
Thank you!
