### ISSUE TITLE
tree-table selection doesn't work correctly if only single subRow is specified

### ISSUE THREAD

**Issue by Lukas742** [tannerlinsley/react-table#1980]
**Describe the bug (required)**

Codesandbox: https://codesandbox.io/s/lucid-wozniak-fsg0b

In a tree-table, parents of rows with single children (`subRows` has only one element) get selected when selecting a child row. This only occurs with single child rows, so if `subRows` contains more than one row, the tree-table selection is working as intended.

*To reproduce:*
In the Codesanbox expand to level 3 or deeper and select the table entry. The result is that not only the current row is selected, but all of its parents, too. This only happens for single `subRow` entries.
Expand to level 6 and check the entry, now only the current row is selected.

Also the `state` is updated correctly, so only the selected row and its children are selected.  The `checked` prop of the parent entries is set to true/false, though.

**Desktop (please complete the following information):**
- OS: iOS
- Browser: chrome
- Version: 80.0.3987.132 (Official Build) (64-bit)

**Comment by tannerlinsley** [comment]
AFAIK, this is intended behavior. If you check a selection for a parent, all sub-rows should also be checked to match. Likewise, in a reactionary event, if all sub-rows of a parent become checked, the parent should again, show the same state by having them all checked. I'm not sure why or how you would want this to function without breaking the majority use case of nested row selection. If you want each of these rows to be independently checkable, then I would suggest that you propose a simple use case and PR to accomplish it via a config or if you wish, you can write your own version of the `useRowSelect` hook that fits this use case.

**Comment by Lukas742** [comment]
Hi @tannerlinsley 

thanks for the reply. 
In our use-case it's more common that the user wants to select only a single node or leaf in the tree, that's why we need a single select option. 
For now I implemented the _single select behavior_ by leveraging the table's state and setting the selected rows accordingly.
If I find the time, I will look into creating a hook/option that implements this behavior and then open a PR.
