### ISSUE TITLE
Multi Select Bug in 'Kitchen Sink' example

### ISSUE THREAD

**Issue by ee0pdt** [tannerlinsley/react-table#1981]
**Describe the bug (required)**

I would expect the 'select all' checkbox to only select the rows included in the current filter... instead this behaviour appears to break if the checkbox is used _before_ filter is applied. 

**Provide an example via Codesandbox! (required)**

Exists in the official demo here: 

https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/kitchen-sink

**Steps To Reproduce (required)**

1. Go to the Kitchen Sink demo on CSB
2. Click on the 'select all' checkbox
3. Click on the filter for First Name column
4. Type "food"

`selectedRowIds` will still contain all the rows in table

**Expected behavior (Recommended)**

`selectedRowIds` to be filtered to match the table filter

**Screenshots**

![image](https://user-images.githubusercontent.com/6094917/76437304-4834c300-63b1-11ea-988f-de246ae9f6a9.png)

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Brave
- Version: 1.3.118 Chromium: 80.0.3987.116 (Official Build) (64-bit)

**Comment by tannerlinsley** [comment]
I can't reproduce this in either the codesandbox you posted or locally with master. Make sure you're all the way up to date, dependencies and all.

![Screen Shot 2020-04-01 at 11 29 48 AM](https://user-images.githubusercontent.com/5580297/78167730-28227d80-740c-11ea-8b3e-cb21f7b19f79.png)
