### ISSUE TITLE
'Expanding' example does not run locally

### ISSUE THREAD

**Issue by markwedding** [tannerlinsley/react-table#1982]
**Describe the bug (required)**
After running `yarn start` on the expanding example, I got an error that `row.getToggleRowExpandedProps` is not a function. After discovering that this function had been renamed in version `7.0.0-rc.16`, I figured that the example package was not using the latest version of react table. I manually changed the version from `latest` to `7.0.0`, and it started working. It turns out that `latest` was referring to `7.0.0-rc.15` for some reason (see git diff below).

I'm not sure if this is happening in all the example packages or not, and I'm also not sure what the cleanest way to reliably grab the latest version is either.

**Screenshots**
![image](https://user-images.githubusercontent.com/15792934/76451575-fdfa1480-63a5-11ea-9263-6f8d217bf5fd.png)

**Comment by tannerlinsley** [comment]
`yarn add react-table@latest` or `yarn add react-table@7` (or `npm install` if that's your jam)

I can't replicate this in the codesandbox or locally on master. Please upgrade and try again and if  needs be, submit another issue with a link to a codesandbox that consistently shows the error.
![Screen Shot 2020-04-01 at 11 33 13 AM](https://user-images.githubusercontent.com/5580297/78168022-95cea980-740c-11ea-9af5-cfb1957b9a59.png)

**Comment by fatsoflo** [comment]
use `toggleRowExpanded` function instead. documentation: https://react-table.tanstack.com/docs/api/useExpanded#row-properties
