### ISSUE TITLE
react table sorting inside group

### ISSUE THREAD

**Issue by remyasnair** [tannerlinsley/react-table#1983]
Unable to sort a table fields inside of a group without sorting the parent?
I am using react table v7 useSortBy hook.

Thanks

**Comment by tannerlinsley** [comment]
React table implements recursive sorting, meaning that parents are sorted first, then each row's subrows are also sorted. If you need alternative sorting strategies, please feel free to describe them in a new PR with the desired changes or if you wish, you can even write your own version of the `useSortBy` plugin hook to get the desired functionality.
