### ISSUE TITLE
Pagination increment/decrement arrow not displaying in "Windows 10 Edge"

### ISSUE THREAD

**Issue by jvarshaprdxn** [tannerlinsley/react-table#199]
I've used **react-table** .

Pagination increment/decrement arrow not getting display in a Windows 10 Edge .

This might be because edge not supporting <input type="number"> html5 feature which this plugin is using.

**Comment by tannerlinsley** [comment]
Could you please post a screenshot?

**Comment by tannerlinsley** [comment]
Please reopen with a screenshot or more information :)
