### ISSUE TITLE
"react-table": "^7.0.0-rc.12" Tag is missing

### ISSUE THREAD

**Issue by ktalgaonkar** [tannerlinsley/react-table#1991]
# STOP

We do not use Github to track general support. Please use our public support forum at https://github.com/tannerlinsley/react-table/discussions.

NOTE: If a support/help/question issue is opened, it will be closed immediately and be redirected to the forum. Thanks for helping us keep our issues clean and productive!

**Comment by tannerlinsley** [comment]
Since this is an RC tag, and the latest is stable, I don't see how this is an issue.
