### ISSUE TITLE
Cell does not render content in production builds

### ISSUE THREAD

**Issue by nikhilem** [tannerlinsley/react-table#1992]
**Describe the bug (required)**

In react-table v7.0.0, cells of the table are rendered empty only in production builds of the app, but works in the development server

**Provide an example via Codesandbox! (required)**
Example: [Virtualized-Rows](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/virtualized-rows) sandbox works fine when run in development mode. But, when run by building the project(`yarn build`), the cells are empty.

**Steps To Reproduce (required)**

Build the project and the run the built version, the cells of the table are empty

**Expected behavior (Recommended)**
The built version should works exactly as the development version, the cells of the table should be rendered correctly.

**Screenshots**

When run locally(development version)
![image](https://user-images.githubusercontent.com/8972095/76592955-e09a8700-651a-11ea-924a-8f3dcfaaa500.png)

When run after building(production version)
![image](https://user-images.githubusercontent.com/8972095/76592969-eb551c00-651a-11ea-9281-08a0ace04c2b.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 80

**Smartphone (please complete the following information):**
N/A

**Additional context**
React Table version: `v7.0.0`

Works fine on `v7.0.0-rc.10`

**Comment by teagueash** [comment]
I have similar issues on my development server, except headers aren't rendering either
<img width="1163" alt="Screen Shot 2020-03-13 at 10 42 47 PM" src="https://user-images.githubusercontent.com/29009775/76675948-16bc2300-657c-11ea-9cdd-7f117e77c79d.png">

**Comment by tprata** [comment]
Hello,
I had just the same problem, you need to check your yarn.lock
My resolved version was 7.0.0.rc-16 (even if it was not the one i put in my package.json, which i find strange)
After i did a "yarn add" to add a new library in my project, the yarn.lock was unexpectedly updated, the resolved package transformed to the latest stable release, 7.0.0 (not very stable tho)
I rolled back my yarn.lock to 7.0.0.rc-16, that fixed my issue

**Comment by samjbmason** [comment]
Im having this exact same issue with v7.0.0

**Comment by Toyobaru** [comment]
Same issue with v7.0.0 on MacOS, Chrome. Works fine when I use v7.0.0.rc-16

**Comment by jketcham** [comment]
I came across this same bug, downgrading to v7.0.0-rc.16 fixed the issue for me. Using this with gatsby 2.13.25.

**Comment by ac1997** [comment]
Same issue here with v7.0.0, works fine with v7.0.0.rc-15
Development server is fine. Production build is not rendering any content.

**Comment by suriyaprashath** [comment]
**Problem:**
I faced the same issue too in v7.0.0. To give more info on the issue I faced:
 - render method works if the derived value(column[type]) is a primitive
 - render method doesn't work if the derived value(column[type]) is a function

Observation:
As per my quick look, there is some problem due to the minification of the code in the production version. Below is the minified code of the flexRenderer method of the actual source code, in the production version, which is potentially causing the problem:
![image](https://user-images.githubusercontent.com/10843459/77385888-69cd7b80-6daf-11ea-90c4-ef60f53e3ffe.png)
When I keep breakpoint in the above method and execute using F11, the debugger is not going executing line 185 which handles the case when column[type] is a function.

Patch:
As a quick solution, I implemented a patch file by extracting the code necessary from the actual source which I have attached below.
[render.service.txt](https://github.com/tannerlinsley/react-table/files/4373074/render.service.txt)

How to use the patch:
Use the patchRenderer method exported instead of cell.render or column.render
Column render:
Before:
column.render('Header')
Now:
patchRenderer('column', tableInstance, column, null, 'Header', null)

Cell render:
Before:
cell.render('Cell')
Now:
patchRenderer('cell', tableInstance, column, {row, cell}, 'Cell', null)

Hope this helps :)

**Comment by alocke12992** [comment]
Thanks @suriyaprashath  - Though it looks like its not supporting the filter render. I can report downgrading to v7.0.0.0-rc.16 worked for me.

**Comment by suriyaprashath** [comment]
Hi @alocke12992, looks great.
Until this is fixed if someone needs to use the latest version along with cell and column render, kindly use the patch in the [above comment](https://github.com/tannerlinsley/react-table/issues/1992#issuecomment-603002248).

**Comment by tannerlinsley** [comment]
This bug is VERY VERY strange. Still working on this, but rest assured, the tiny little insect causing this will be hunted and killed as soon as humanly possible.

**Comment by tannerlinsley** [comment]
I still don't know *why* this was happening, but I managed to fix it by simply pre-inlining the function that terser was inlining in the end. 🤷‍♂

**Comment by tannerlinsley** [comment]
Released to 7.0.2

**Comment by nikhilem** [comment]
Thanks @tannerlinsley

**Comment by brandonparis** [comment]
I'm seeing this happen on release 7.2.0, but only with the Headers. Downgrading to 7.0.2 resolved it.

**Comment by RileyMShea** [comment]
@tannerlinsley I am also still seeing this issue with 7.2.1

**Comment by kyiii** [comment]
@tannerlinsley Still experiencing this with 7.3.0.

**Comment by kyiii** [comment]
@tannerlinsley Very strange, am still experiencing this with 7.3.0 but only with Netlify/Vercel builds.

**Comment by thiagozf** [comment]
I am also still seeing this issue with 7.5.0

**Comment by stefanmaretic** [comment]
> I am also still seeing this issue with 7.5.0

Same here, also experiencing this. This is kind of a big deal I think this should get reopened.

**Comment by Karl992** [comment]
Still seeing this issue with 7.5.1 in my developer server.

**Comment by pmilla1606** [comment]
Also seeing this with 7.5.1

**Comment by UcheSylvester** [comment]
Experiencing this same issue but this time the entire table is not rendered in production

**Comment by pmilla1606** [comment]
Removing react.strictmode fixed it for me. If you’re using CRA your app will be wrapped in it.

**Comment by UcheSylvester** [comment]
> Removing react.strictmode fixed it for me. If you’re using CRA your app will be wrapped in it.

@pmilla1606, the app is not wrapped in react.strictmode.

**Comment by pmilla1606** [comment]
Are you on the latest version? I haven’t had any issues since removing strict and updating.

**Comment by UcheSylvester** [comment]
currently, no. I had to downgrade to v7.0.0.0-rc.16 which didn't solve the problem either. But I'd removed the strictmode even before installing react table

**Comment by Kuzzmich** [comment]
I'm experiencing similar issue, but I can't see only table head. I tried to downgrade the version a few times, but without success. My current version is 7.6.0

**Comment by gustavo-pateti** [comment]
Similar issue here, building a CRA app, it doesn't render anything. Downgraded to 7.0.2, working now.

**Comment by Shauandsss** [comment]
Same here, i cant see the content of rows, but the number of rows are right, the header is right too, react-table@7.6.3

**Comment by AxelThomsonEk** [comment]
Same here, seeing this issue in production (but not locally) on version 7.6.3

**Comment by nuno-ferrao** [comment]
I am also seeing this issue, I was on the latest version, 7.6.3, and downgraded all the way back to 7.0.0, and it still didn't fix it. I would be great to have an update from @tannerlinsley on this issue, seems quite major.

**Comment by ajmeraaxesh** [comment]
@tannerlinsley  facing a similar issue in 7.6.3

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Cell`.

**Comment by mil0s2** [comment]
Again, same issue with version 7.7.0, downgrading does nothing

**Comment by kkrzr** [comment]
I've faced the same issue with version 7.7.0 in a next.js project. Downgrading the next version from 12.0.8 (latest) to 12.0.7 solved the issue.

**Comment by Zellerich** [comment]
I also had this issue with 7.7.0 in a next.js project with version 12.1.0.
Downgrading to 12.0.7 fixed this.
