### ISSUE TITLE
Loading: showing with property value is false

### ISSUE THREAD

**Issue by mhd999** [tannerlinsley/react-table#20]
Hi!

I have sat the property loading to false but loading over lay still showing.

**Comment by mhd999** [comment]
The reason of this issue is because i turned off the pagination and not set `pageSize` value that fit all the rows data from a server. Now after enabling pagination or set `pageSize` to proper value the issue gone.

**Comment by mikedevita** [comment]
are you including the stylesheet?

**Comment by mhd999** [comment]
No, adding it solve my issue.

**Comment by mikedevita** [comment]
Yeah. Initially @tannerlinsley talked about moving the styles to scss and inline them into the component not sure where he stands on that work.

Sent from my iPhone

On Dec 19, 2016, at 2:23 PM, mhd999 <notifications@github.com<mailto:notifications@github.com>> wrote:


No, adding it solve my issue.

-

**Comment by tannerlinsley** [comment]
Still contemplating how to handle the styles.  Closing this particular issue for now.
