### ISSUE TITLE
[QUESTION] Move to the first/last page

### ISSUE THREAD

**Issue by yupushnov** [tannerlinsley/react-table#200]
Hi!
I'm using **react-table** with custom `PaginationComponent`. And I need go to the last page on "adding new row" event.
Is possible to move dynamically to the first/last page without controlling state `page`, `pageSize` overrides and `onPageChange`, `onPageSizeChange` callbacks?

**Comment by tannerlinsley** [comment]
You could use a component ref and manually use the tables internal setState to do this. Since this falls under an implementation question, please join the slack channel for further discussion or help :)
