### ISSUE TITLE
UseSortBy Multisort description update

### ISSUE THREAD

**Issue by at-webdev** [tannerlinsley/react-table#2003]
On UseSortBy API Description (https://github.com/tannerlinsley/react-table/blob/master/docs/api/useSortBy.md) its mentioned as Multisort (Keyboard required) even though it can be overriden with out keyboard using ```isMultiSortEvent: Function``` 

This function works great but the  description of ```It also support multi-sort (keyboard required)``` seems to be misleading as it can be overriden with the function above. This issue is for a suggestion to modify the description. Thanks!

**Comment by tannerlinsley** [comment]
A PR is welcomed to make any clarifications you see fit :)
