### ISSUE TITLE
[QUESTION] Rendering table without 'columns' property?

### ISSUE THREAD

**Issue by ilyablbnv** [tannerlinsley/react-table#201]
Is there option to render table without 'columns' property? I mean my data is fetched from the server (JSON format) and do not have fixed structure. So my data is quite dynamic and I don't want to define columns in my template. Consider having this JSON:
`data = {
    name: 'Tanner Linsley',
    age: 26,
    friend: 'Jason Maurer'
}`
and all I want is just to pass 'data' into <ReactTable> without 'columns' and get this kind of table:
<img width="238" alt="screen shot 2017-04-15 at 19 41 49" src="https://cloud.githubusercontent.com/assets/17590024/25065661/9de593ca-2213-11e7-9e90-53060f4408e6.png">

Thanks in advance.

**Comment by tannerlinsley** [comment]
Currently no, but it would be easy to dynamically create columns on the
fly.  Just loop over your data and store a unique list of object keys for
all of the rows. Then you can use those keys to generate a very basic
column list.

**Comment by tannerlinsley** [comment]
Closing for now. If you need more details on implementing this, please join inquire on the slack channel
