### ISSUE TITLE
Expand/close all nested subRows

### ISSUE THREAD

**Issue by deugene** [tannerlinsley/react-table#2023]
Hi! How can I do this? If I don't want to expand the whole table, but only expand a single row and all of it's nested subRows recursively?

**Comment by tannerlinsley** [comment]
This is a good question. Right now it's not supported by the built-in API, but I would be open to a PR that implements this functionality.

**Comment by livwvil** [comment]
Hi all! Thanks devs for the awesome lib!
Has it not been implemented yet? I need this functionality too. My solution is too slow :( expand/collapse for the whole tree works extremely fast, why it cannot be implemented for the subtree?

```ts
const toggleSubRows = (subRows: Row<SettingsTreeNode>[], expanded: boolean) =>
  _.forEach(subRows, subRow => {
    if (subRow.getCanExpand() && subRow.getIsExpanded() === expanded) {
      subRow.toggleExpanded();
    }
    if (subRow.subRows.length) {
      toggleSubRows(subRow.subRows, expanded);
    }
  });
```
