### ISSUE TITLE
Working with immutable data

### ISSUE THREAD

**Issue by roginfarrer** [tannerlinsley/react-table#203]
The component throws an error when working with immutable data. When using `seamless-immutable`, we get the following error:

    Can't add property _viewIndex, object is not extensible

Is there a proper way to work with immutable data, or is just plain not supported? Do we need to be using a certain immutable data library in order to work with immutable data?

**Comment by tannerlinsley** [comment]
Please upgrade to 5.5.2 and try again :)

**Comment by roginfarrer** [comment]
Will give it a shot! Thanks! I'll let you know if we run into any problems.

**Comment by tannerlinsley** [comment]
If you find that it's fixed, please feel free to close this issue :)

**Comment by tannerlinsley** [comment]
Please reopen if the issue still exists :)

**Comment by roginfarrer** [comment]
Just got word from my team that this resolved our issue! Thanks for the prompt fix!

**Comment by tannerlinsley** [comment]
You bet!

**Comment by nicolechung** [comment]
I just started using react-table with seamless immutable, and when I tried to do some sorting I got this error message:

```
The sort method cannot be invoked on an Immutable data structure.
```

Seems to be happening at this line of code:
```
function orderBy(arr, funcs, dirs, indexKey) {
  return arr.sort(function (rowA, rowB) { ...
```

**Comment by nicolechung** [comment]
@tannerlinsley can I reopen this issue or should I provide a codebox sample?

**Comment by nicolechung** [comment]
Wait, I am going to try to make it mutable when I pass it in as props.
