### ISSUE TITLE
Memorized Components are not updating with changes in table data.

### ISSUE THREAD

**Issue by krashdifferent** [tannerlinsley/react-table#2032]
When using useTable in a parent component and passing the result down to a memorized child (React.memo(Child)), the child does not update on changes in the table state or data. Is the object being returned by useTable being mutated?

The following contrived CodeSandbox shows the same table component rendered twice, once memorized and once unmemorized. The data changes every 2 seconds but the memorized table does not reflect the data updates.

https://codesandbox.io/s/zen-brown-v01vb

**Expected behavior (Recommended)**
Unless there are other reasons to mutate the object that I am missing or my admittedly incomplete knowledge of React is failing me, I would expect useTable to generate a new object when it's state updates so it can be used with memorized objects safely.

**Comment by tannerlinsley** [comment]
React.memo only works with top-level props, and since the table instance itself that is returned from `useTable` never really changes (but it's properties do), then what you have won't really work. But this would:

```
function Table (tableProps) {
  ...
}

function App () {
  const table = useTable()

  return (
    <>
      <Table {...table} />
      <MemoTable {...table} />
    </>
  )
}
```
