### ISSUE TITLE
How to add custom pagination icons?

### ISSUE THREAD

**Issue by rehat101** [tannerlinsley/react-table#205]
Can I replace the current pagination buttons for Prev and Next to custom arrow icons?

**Comment by tannerlinsley** [comment]
Absolutely! Just use your own component for the NextComponent and
PreviousComponent props

**Comment by rehat101** [comment]
I'm trying to use my own component below here but I can't see the component render. Am I doing something wrong here? 

```
class NextIcon extends Component {
  render() {
    return <button><img src="../assets/scroll-arrow-right.svg"/></button>;
  }
}

class PrevIcon extends Component {
  render() {
    return <button><img src="../assets/scroll-arrow-left.svg"/></button>;
  }
}

Object.assign(ReactTableDefaults, {
  PreviousComponent: <PrevIcon/>,
  NextComponent: <NextIcon/>
});
```

**Comment by tannerlinsley** [comment]
Try PreviousComponent: PrevIcon

**Comment by rehat101** [comment]
Now it renders but doesn't paginate.

**Comment by tannerlinsley** [comment]
Include all props on the button like this: <button {...this.props}>. It
needs to use the onClick that is provided in the props at the very least.

**Comment by rehat101** [comment]
it works now. thanks.

**Comment by tannerlinsley** [comment]
You bet!

**Comment by perpetualgrimace** [comment]
In case anyone else gets stumped by this:

`PreviousComponent={props => <CustomButton {...props} />}`
