### ISSUE TITLE
Resizing column to minimum doesn't work correctly

### ISSUE THREAD

**Issue by monikanowak** [tannerlinsley/react-table#2052]
**Describe the bug (required)**
When resizing column header to minimum width, the text in the column is overlapping another column.

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/column-resizing

**Steps To Reproduce (required)**

1. Go to codesandbox
2. Resize the last name column to minimum

**Expected behavior (Recommended)**
When resizing column header to minimum width, the text in the column shouldn't overlap another column, the overflow should be hidden just like in excel.

**Screenshots**
https://imgur.com/eemjNNK

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS Catalina 10.15.3
- Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tannerlinsley** [comment]
Since this is using a non-table element layout (which is required for resizing columns), the min width is not defined by the text content. If you want the text content to not break out, you'll either need to set it to overflow: hidden, overflow: scroll, or make it so the text can wrap.
