### ISSUE TITLE
Delete row (register) server side

### ISSUE THREAD

**Issue by Keony1** [tannerlinsley/react-table#2059]
I am implementing a button that is received by the columns property that when it is clicked it triggers an event to delete the record in the database, so far so good, the problem is that the table does not update. I searched the documentation and found nothing. Could anyone set an example?

**Comment by tannerlinsley** [comment]
To update the table, you can give it a new reference to either the `data` or `columns` properties, or any other property for that matter. If you need more help, please consider asking in the Discussions tab or submitting a codesandbox example that has more or less what you want to happen.
