### ISSUE TITLE
Reference Links are not working

### ISSUE THREAD

**Issue by MitulGedeeya** [tannerlinsley/react-table#2061]
Links on the documentation has been broken

**Comment by mattstvartak** [comment]
I've also noticed that the example Code Sandbox links have been down for a while. Perhaps on the documentation site @tannerlinsley  could just provide the code with links to the Code Sandbox  examples of well that way if they are down it does not matter as much. 😊

**Comment by mattstvartak** [comment]
> Links on the documentation has been broken

Source links still work, just the CodeSanbox links seem to be down.

**Comment by sm-Fifteen** [comment]
There are a number of links besides the code examples that no longer work or references to information that are simply not present in the doc. On top of my head:

https://github.com/tannerlinsley/react-table/blob/d2acfc423593389f8f7b974c6f544ecf683f0724/docs/api/useFilters.md#L33
https://github.com/tannerlinsley/react-table/blob/d2acfc423593389f8f7b974c6f544ecf683f0724/docs/api/useSortBy.md#L52
https://github.com/tannerlinsley/react-table/blob/d2acfc423593389f8f7b974c6f544ecf683f0724/docs/api/useFilters.md#L39

**Comment by milesrichardson** [comment]
None of the codesandbox.io load for me unless I am logged into codesandbox via github. Without being logged in, I get a 403 error. 

To resolve, log into codesandbox via github

**Comment by tannerlinsley** [comment]
This is a codesandbox bug and nothing to do with React Table. We'll just have to wait for them to sort it out. Sorry! 🤷‍♂
