### ISSUE TITLE
Pagination not working correctly when used with the 'useSortBy' hook

### ISSUE THREAD

**Issue by williamolojede** [tannerlinsley/react-table#2063]
**Describe the bug (required)**
The `pageIndex` state property resets to 0 after loading the next page

**Provide an example via Codesandbox! (required)**
Use a new [react-table codesandbox](https://codesandbox.io/s/m5lxzzpz69) to reproduce the issue.
https://codesandbox.io/s/interesting-hertz-01fnh

**Steps To Reproduce (required)**

1. Go to the codesandbox
2. Click on the next button '>'
3. Notice how the `pageIndex ` resets back to 0

**Expected behavior (Recommended)**
The `pageIndex` should not change after the data for the new page has been loaded.

**Comment by lookaflyingdonkey** [comment]
I have been having this issue too, whenever using manualPagination and useSortBy it is resetting the pageIndex to 0 (or initialState.pageIndex) when new data comes from the server.

Managed to find a "solution" by setting the initialState.pageIndex to the page number returned by the server (or the last one queried by react-table)

I have applied a couple edits to your sandbox at https://codesandbox.io/s/agitated-chatelet-r8wsj, namely lines 48, 71, 251, 272

It does seem to work but haven't fully tested sorting yet.

**Comment by tannerlinsley** [comment]
☝️ 💯

**Comment by williamolojede** [comment]
thanks!
