### ISSUE TITLE
When we use `useExpanded` and `useFilters` subRows disappear when we perform a search

### ISSUE THREAD

**Issue by carlosrberto** [tannerlinsley/react-table#2064]
**Describe the bug (required)**
When using `useExpanded` and `useFilters` subRows disappear when we perform a search.

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/expander-filtering-gjer7

**Steps To Reproduce (required)**
This happens with all filters, bellow an example:

Search for the exact content of a row from "First Name":

**Issue 1:** The search doesn't looks for values on subRows
**Issue 2:** When you clear the search **the subRows disappear**

**Comment by timothymathison** [comment]
I was just about to open an issue for this same behavior as well.
After looking through the code, I believe this behavior was introduced by [this change](https://github.com/tannerlinsley/react-table/commit/6d4a733a88dd9c1b9d1e49e5dbc54edd6f2acad5). Before that change, each `row` was cloned before overwriting the `subRows` property. But now, each row is no longer cloned; which means that updating the `subRows` property actually persists a change the the [memoized `row` data](https://github.com/tannerlinsley/react-table/blob/d51aac11f3ddbbb3a82cbc3852e81aa7e609c51b/src/hooks/useTable.js#L186).

The workaround is to clone each `row` yourself inside your filter method(s). But I think this is definitely a bug. IMO, filtering should not be allowed to mutate the `subRows` like that.

**Comment by tannerlinsley** [comment]
Yeah, that change was necessary for some other things to work that were restricted by doing immutable ops on the sub rows. Welcome to suggestions, but you'll see many tests fail if you revert that change. Any ideas moving forward?

**Comment by noahbenham** [comment]
Out-of-the-box behavior seems broken here. I'm using the following to work around this bug.
```tsx
function globalFilter<Datum extends DatumType>(
  rows: Row<Datum>[],
  columnIds: Extract<keyof Datum, string>[],
  searchQuery: string
) {
  if (!searchQuery) return rows;

  const lowercaseQuery = searchQuery.toLowerCase();
  const rowMatches = (row: Row<Datum>): boolean =>
    Object.values(row.values).some(
      rowValue =>
        typeof rowValue === "string" &&
        rowValue.toLowerCase().includes(lowercaseQuery)
    ) || row.subRows.some(rowMatches);
 
  return rows.filter(rowMatches);
}


useTable<Datum>(
    {
      ...
      globalFilter,
    },
    useGlobalFilter,
    useFilters,
    useSortBy,
    usePagination,
    useRowSelect,
  );
```

This also works quite well with Fuzzy searching:
```tsx
import fuzzy from 'fuzzy';

function globalFilter<Datum extends DatumType>(
  rows: Row<Datum>[],
  columnIds: Extract<keyof Datum, string>[],
  searchQuery: string
) {
  if (!searchQuery) return rows;

  const rowMatches = (row: Row<Datum>): boolean =>
    Object.values(row.values).some(rowValue => {
      return typeof rowValue === "string" && fuzzy.test(searchQuery, rowValue);
    }) || row.subRows.some(rowMatches);

  return rows.filter(rowMatches).map(row => ({ ...row, subRows: row.subRows }));
}
```

@tannerlinsley You mention the changes in 6d4a733a88dd9c1b9d1e49e5dbc54edd6f2acad5 allowed a few other things to work. Could you share details? I'd like to ensure my cloning workaround isn't going to cause unreliable behavior/regressions. Thank you for all your hard work on this library and congrats on shipping v7.

**Comment by aaryn101** [comment]
For my use case I had to write my own `useGlobalFilter` plugin-hook anyway, so I decided to try to tackle this issue from a different angle.

Here's what I did, at a high level:
- added a property to each `row` object called `preGlobalFilteredSubRows`
  - this is set in the `useInstance` hook whenever rows or columns change (basically whenever `accessRowsForColumn` is called in `useTable`)
- `row.subRows` is reset to the value of `row.preGlobalFilteredSubRows` whenever `globalFilterValue` is undefined (basically whenever the filter is cleared)
- Instead of:
```javascript
row.subRows =
  row.subRows && row.subRows.length
    ? filterRows(row.subRows)
    : row.subRows
```
I do:
```javascript
row.subRows =
  row.preGlobalFilteredSubRows && row.preGlobalFilteredSubRows.length
    ? filterRows(row.preGlobalFilteredSubRows)
    : row.subRows
```

In my limited testing thus far, this has worked to ensure that sub-rows do not disappear whenever the `globalFilterValue` changes or is removed.

**Comment by timothymathison** [comment]
> @tannerlinsley You mention the changes in `6d4a733` allowed a few other things to work. Could you share details?

I would definitely be interested to learn about those issues as well!

Perhaps @aaryn101's solution could be generalized to solve the problem with both global and row filtering, by adding a `preFilteredSubRows` array to every `row`?

**Comment by govi74** [comment]
@aaryn101 Do you have a sample code for reference?  I am new to this and need this  feature :(

**Comment by govi74** [comment]
Well , when you explicitly define the subrows , at least the subrows are not getting removed.
But my problem now is, global filter is not searching the subrows.

**Comment by tannerlinsley** [comment]
In the next version of RT, this is going to be configurable. You'll be able to choose top-down or bottom-up filtering. For now, v7 is top-down.

**Comment by FOXY-FO** [comment]
@govi74 what are in hiddenColumns?

**Comment by govi74** [comment]
> @govi74 what are in hiddenColumns?

an array of column names

**Comment by matveychuk** [comment]
I solved it by adding custom filter function to filterTypes

```
  const filterTypes = React.useMemo(
    () => ({
      filterRowsWithSubrows: (rows, id, filterValue) => {
        return rows.filter((row) => {
          const rowValue = row.values[id];
          return rowValue !== undefined ? String(rowValue).toLowerCase() === String(filterValue).toLowerCase() : true;
        });
      },
    }),
    [],
  );
```
and then add filterTypes to useTable hook

```
const tableInstance = useTable(
    {	
      columns
      data,
      filterTypes,
    },
    useFilters
)
```
and then add this custom filter to column as a string name "filterRowsWithSubrows" for value "filter"

```
export const status = {
  Header: 'Status',
  accessor: 'status',
  filter: 'filterRowsWithSubrows',
  Filter: SelectColumnFilter,
};
```

**Comment by bosper131** [comment]
Has anyone found any other solution to that issue as all of the mentioned solutions don't work for me? :( 

I refer to the issue with filtering the subRows

**Comment by pea3nut** [comment]
> In the next version of RT, this is going to be configurable. You'll be able to choose top-down or bottom-up filtering. For now, v7 is top-down.

@tannerlinsley How is it going?

**Comment by tannerlinsley** [comment]
Still working on it. The Typescript conversion is going well

Tanner Linsley

**Comment by AleksanderIII** [comment]
@tannerlinsley  Could you tell me if you know some solution for the issue? All the suggested solutions did not help me

**Comment by qapla47** [comment]
I have it implemented for a table that renders a sub table with global filtering using the match-sorter package. 
When you create your filterFn (most of the filtering examples show the fuzzyTextFilterFn), you get access to rows. From there, you can add information from the rows.values and rows.original objects to the keys array for matchSorter (you can actually access deeply nested values in this keys array). 
Your keys array needs to provide a list that looks at the data from both the main table's pov and the sub table's pov. 
ie: 
 - values.name belongs to the main table, it looks directly at rows.values for the main table
 - original.sub_item.*.item_name looks from the main table to the sub table's data (it's an array of objects, from rows.original)
 - values.sub_item_name belongs to the sub table, and looks directly at rows.values for the sub table
 
Both tables also need to implement useGlobalFilter. Only the main table gets the actual input, but both tables need to know about the globalFilter.

I'm using: react-table 7.6.3 and match-sorter 6.1.0

**Comment by ColinLights** [comment]
Its funny how this small fixable issue made me change library

**Comment by zk-rbx** [comment]
Not sure why this is closed, this is still a bug in react-table@v7.7 as of July 2021. 

Feels like this library is just unmaintained until v8 comes out in year?

**Comment by tannerlinsley** [comment]
This is not an issue, but a feature request for leaf-node first filtering. It’s also non trivial to add without significant changes. Your choices are to either put in the time and effort yourself with a PR or patiently wait for v8. 

It’s moving along well, too!

**Comment by ThePr0grammer** [comment]
Took me a whole day to find some workaround. 

For example, you have table with columns: title, price, count.  
You have a parent rows and expandable sub-rows.

You want to filter by "Title" and you want to filter parent-rows + sub-row. 

1. Put this in your useTable hook options: getSubRows: (row: any) => row.subRows ( fixing issue with missing sub-rows, after filtering ),
2. Put all title's from sub-rows inside title of the parent row. 

Initial structure vs what you need to get: 
```[
  {
    "title": "Department 1 title",
    "cost": "",
    "count": "",
    "subrows": [
      { "title": "Department 1 service 1", "cost": "string", "count": "number" },
      { "title": "Department 1 service 2", "cost": "string", "count": "number" }
    ]
  }
]

[
  {
    "title": "Department 1 service 1 Department 1 service 2" + "Department 1 title",
    "department_title": "Department 1 title",
    "cost": "",
    "count": "",
    "subrows": [
      { "title": "Department 1 service 1", "cost": "string", "count": "number" },
      { "title": "Department 1 service 2", "cost": "string", "count": "number" }
    ]
  }
]
```

If you need to display somewhere initial parent row title, you can access it in formatter data though row.original.department_title.

**Comment by ZiedHf** [comment]
🟢  **A work-around for this issue [here](https://codesandbox.io/s/react-table-expanded-global-filter-1-kibuy?file=/src/App.js)**

**Comment by kasunnirmala** [comment]
> 🟢 **A work-around for this issue [here](https://codesandbox.io/s/react-table-expanded-global-filter-1-kibuy?file=/src/App.js)**

Not suitable for huge data set. It hangs the table when the dataset is more than 5000.

**Comment by ZiedHf** [comment]
> > 🟢 **A work-around for this issue [here](https://codesandbox.io/s/react-table-expanded-global-filter-1-kibuy?file=/src/App.js)**
> 
> Not suitable for huge data set. It hangs the table when the dataset is more than 5000.

Do not use v7 for this use case. Upgrade to v8. It will solve the issue without using any hack. And work fine with more than 5000 rows as well.

**Comment by kasunnirmala** [comment]
> > > 🟢 **A work-around for this issue [here](https://codesandbox.io/s/react-table-expanded-global-filter-1-kibuy?file=/src/App.js)**
> > 
> > Not suitable for huge data set. It hangs the table when the dataset is more than 5000.
> 
> Do not use v7 for this use case. Upgrade to v8. It will solve the issue without using any hack. And work fine with more than 5000 rows as well.

V8 with your workaround example? Or is there any inbuild configs to do that? Because I still couldn't find a way to support child search in the documentation.

**Comment by willot** [comment]
I am not sure it is working as intended in version 8. When using the global search functionality some rows lose the capability to expand. It is inconsistent. If I search for "c" some of the rows will be expandable and if I search for 'ch' then the rows lose their capacity to expand...

**Comment by sumitaney** [comment]
It does not works for huge data, it shows unnecessary rows also with two string

**Comment by obadakhalili** [comment]
The solution for me was to overwrite the `globalFilter` option and return any row that:
* Satisfies the global filter value.
* One of its `subRows` satisfies the filter.
* Has a parent that satisfies the filter. This was the trickiest to implement since you need to have access to all the rows to return the parent of the current row, and react-table calls the `globalFilter` function not on all rows at once, but does many calls to the function with each containing the rows of a certain depth. So you need to accumulate all the rows manually. You are welcome to tell me if there is a better way to get all the rows in react-table.

Solution:
```ts
useTable({
  globalFilter: getGlobalFilter()
})

function getGlobalFilter() {
  const allRows = []

  return (
    levelNRows,
    columnIds,
    filterValue,
  ) => {
    allRows.push(...levelNRows)

    if (!filterValue) {
      return levelNRows
    }

    const normalizedFilterValue = filterValue.trim().toLowerCase()

    return levelNRows.filter((row) => {
      function rowMatches(row, parentRow) {
        return (
          // row's string values satisfy the filter
          Object.values(row.values).some(
            (cellValue) =>
              typeof cellValue === "string" &&
              cellValue.toLowerCase().includes(normalizedFilterValue),
          ) ||
          // or the row has a subRow that satisfies the filter
          row.subRows.some((row) => rowMatches(row)) ||
          // or the row has a parent row that satisfies the filter
          (parentRow ? rowMatches(parentRow) : false)
        )
      }

      const parentRow = allRows.find(({ subRows }) => subRows.includes(row))

      return rowMatches(row, parentRow)
    })
  }
}
```

**Comment by sumitaney** [comment]
@obadakhalili Can you provide working sandbox for this piece of code

**Comment by garkusha-software** [comment]
> Well , when you explicitly define the subrows , at least the subrows are not getting removed. But my problem now is, global filter is not searching the subrows.
> 
> ```
> useTable(
>     {
>       columns,
>       data,
>       initialState: {
>         hiddenColumns: hiddenColumns,
>       },
>       getSubRows: (row: any) => row.subRows,
>     },
> ```

Yeah, this is one works, but if you don't wrap getSubRows in useCallback it may cause a huge performance issue, e.g if you using virtualization with the huge amount of items. 

What did work for me, inside globalFilter (which also should be wrapped in useCallback) I do clone(rows) like so:
`globalFilter: useCallback((rows) => clone(rows).filter(...), [])`
so subRows will always be populates after you clearing the filter because you don't overwrite the original rows.
