### ISSUE TITLE
How to create table with nested columns

### ISSUE THREAD

**Issue by cindy-li-qa** [tannerlinsley/react-table#2070]
I want to create a table with some nested columns like this

![image](https://user-images.githubusercontent.com/44219522/77893670-c85e9200-72a6-11ea-87d2-e93615d5502c.png)

But got this when set columns to 
  const columns = [
        {
            Header: 'Team',
            accessor: 'team',
            style: {
                textAlign: "center",
                whiteSpace: "unset",
            },
        },
		{
            Header: 'Q1',
            columns: [
				{
				  Header: 'Jan',
				  accessor: 'jan',
			      style: {
					textAlign: "center",
					whiteSpace: "unset",
				  },
				},
				{
				  Header: 'Feb',
				  accessor: 'feb',
			      style: {
					textAlign: "center",
					whiteSpace: "unset",
				  },
				},
				{
				  Header: 'Mar',
				  accessor: 'mar',
			      style: {
					textAlign: "center",
					whiteSpace: "unset",
				  },
				},
			]
        },
		...
	]

![image](https://user-images.githubusercontent.com/44219522/77893778-f3e17c80-72a6-11ea-969d-e2be5113e39a.png)

Can someone tell me how to fix this?

**Comment by tannerlinsley** [comment]
This is currently not supported in React Table as far as I know without a lot of custom work in userland. I imagine you would be better off asking this question in Discussions, so I'm going to convert it as such.
