### ISSUE TITLE
Error on useAsyncDebounce

### ISSUE THREAD

**Issue by Ajaay** [tannerlinsley/react-table#2071]
When attempting to debounce a serverside fetch using useAsyncDebounce, I get the following error in browser:

<img width="1275" alt="Screen Shot 2020-03-30 at 20 32 54" src="https://user-images.githubusercontent.com/6141375/77954066-fdc6a800-72c5-11ea-9f39-b0b7b9373bd2.png">

Is there a missing babel dependency perhaps?

Cheers

**Comment by tannerlinsley** [comment]
Looks like you'll need to be using Babel and `@babel/preset-env` to transpile React Table into your app. If you are excluding the regeneratorRuntime by accident, I would look for something related to your babel presets. Unfortunately, I don't have much more info on this other than to make sure your babel setup is up to date and solid.

**Comment by manojeeva** [comment]
Same here using NextJs Server-side rendering.
Simple table sample with controlled pagination with debounce causing this error.
How to fix this?
Is it okay to add preset-env at the server side?

**Comment by sebaranowski** [comment]
Configuring Babel is the right clean way, i guess. But for me this also works for now:

`App.tsx`:
```ts
import 'regenerator-runtime/runtime';
import React from 'react';
...
```

See https://flaviocopes.com/parcel-regeneratorruntime-not-defined/ and this for Webpack configuration hints: https://www.jhipster.tech/tips/028_tip_ie_support.html
