### ISSUE TITLE
Examples with colgroup and col HTML5 tags for controlling columns

### ISSUE THREAD

**Issue by clord** [tannerlinsley/react-table#2072]
These HTML5 tags allow much greater control over tables, for example they are the only way to set widths, and also can set styles along any span of columns, and they can help screen readers understand tables with multiple headers.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/colgroup

Also, the new tags help with accessibility: https://stackoverflow.com/questions/41913896/should-i-use-colgroup-and-col-and-if-so-why-and-how

Finally, these tags are a natural place to control the width of table columns, since min-width/max-width and width are all respected by most browsers now.

**Comment by tannerlinsley** [comment]
You are more than welcome to use these new tags to control the table layout, that's the beauty of headless components and hooks! :)

**Comment by JWess** [comment]
I think this ticket was requesting an example, not capability.
