### ISSUE TITLE
confused about server side filtering

### ISSUE THREAD

**Issue by theigor** [tannerlinsley/react-table#208]
## Problem Description
From the docs, it says 
> If you want to handle pagination, sorting, and filtering on the server, react-table makes it easy on you.

and I did find it very easy for everything but the filtering... Am I just thinking about it wrong? It seems to me that the filterMethod expects a boolean return value but that only works if all your data is client-side. What I actually want to do is have the filter method return a filter expression I can pass to the server - something like this for a "name" column (for mongoose):

```filterMethod: (filter:any, row:any) => { return { "$regex": filter.value, "$options": "i" } }```

that my service takes and maps to a mongoose `.find()` method

Am I missing something? I'm on `"react-table": "^5.5.1"`

Thanks!

**Comment by tannerlinsley** [comment]
Are you handling *pagination* and *sorting* server-side? If so, then you would not use the built-in column filter functions in the table at all. You would, however, definitely use the `filter` values that are sent to your `onChange` method.  Those filters would presumably be sent to your server so the filtering can be done server-side.  By the time the desired page of data comes back from the server, it should only be *one* page of *sorted* and *filtered* data.  Of course, how you implement that sorting and filtering in mongoose or any other database is up to you :).

The most concrete example we have is the storybook entry for server-side data located here: https://github.com/tannerlinsley/react-table/blob/master/stories/ServerSide.js#L22-L31.  I've highlighted the lines in that example that mock the server-side filtering. Again, you would need to utilize the filter values in your query if you are using mongoose.

**Comment by theigor** [comment]
I should have added this to the original description but the reason for this is the mockup seems to assume a filter method on the server - https://github.com/tannerlinsley/react-table/blob/master/stories/ServerSide.js#L27 (`include`) but I want the column to define the filter method it needs so some text columns will be `include` and some `startsWith`, etc.

**Comment by theigor** [comment]
Sorry - our comments got crossed. OK, that's what I kind of thought - so you're basically saying - don't use the filter UI but build my own filter UI that the onChange function collects filter info from?

**Comment by tannerlinsley** [comment]
Precisely.  You can build your mongo query however you want using the text the user has entered.  You could even use a map of columnID to query-filter-method, so you know how to build the query. eg. `{ firstName: '$in' }` or the mongo equivalent.

**Comment by tannerlinsley** [comment]
Also, you can actually use the filter UI as it is.  When using the `manual` prop, the `onChange` handler is sent the values from the built-in filter text boxes.  So you wouldn't even really need to build your own UI, you just need to integrate those values correctly into your mongo query.

**Comment by theigor** [comment]
Perfect - I did just that. Here's an example for future folks

```typescript
applyCustomFilters(gridFilters: FilterDefinition[]) {
	return gridFilters.map((f) => {
		switch (f.id) {
			case "name": return Object.assign({}, f, { value: { "$regex": f.value, "$options": "i" }})
			default: return f
		}
	})
}
```
where `FilterDefinition` is 
```typescript
export type FilterDefinition = { id: string, value: any, pivotId: any /* any for now, until i become familiar with it */ };
```

I'll have to make some helper function so it's more reusable but this'll do for now. Thanks!

**Comment by midnightcodr** [comment]
Hi @tannerlinsley this link https://github.com/tannerlinsley/react-table/blob/master/stories/ServerSide.js#L27 returns 404, any way you can make an update? Thanks.

**Comment by calebpsdinc** [comment]
For others googling, here's the [serverSide.js example](https://react-table.js.org/#/story/server-side-data).
