### ISSUE TITLE
`defaultCanSort` not setting canSort to false in columns

### ISSUE THREAD

**Issue by lmosele** [tannerlinsley/react-table#2080]
I set the `defaultCanSort` option as described in the [docs](https://github.com/tannerlinsley/react-table/blob/master/docs/api/useSortBy.md):

```
 const {
    getTableProps,
    getTableBodyProps,
    headerGroups,
    rows,
    prepareRow
  } = useTable(
    {
      columns,
      data,
      defaultCanSort: false
    },
    useSortBy
  );
```

Unfortunately when logging `columns`, they all still return `canSort: true`, which means some of my unsortable headers are all styled as sortable.

**Example**
As you can see below, the columns marked 'sortable' are receiving `canSort` as true, even though `defaultCanSort` is set to false and `names` is the only column with `canSort` set. 

https://codesandbox.io/s/flamboyant-chebyshev-ksdy3

**Expected behavior **
Setting `defaultCanSort` to `false` in the options object should mean all columns are marked as `canSort` false by default. 

- OS: OSX
- Browser: Firefox

**Comment by tannerlinsley** [comment]
The docs need to be more clear here maybe, but that default only applied to columns without accessors. If a column has an accessor, you will need to set `canSort` on the column or even extend the default column options so all columns have `canSort: false`

**Comment by datner** [comment]
Sorry to bring this back from the dead, the docs are mistaken! They declare theres a column option called `defaultCanSort` instead of `canSort`. Which is probably how people missed this. (it is also declared wrong in the `@types` declaration)
![image](https://user-images.githubusercontent.com/22598347/129254253-1eea8c5a-f5a4-477c-9893-3acad0011fa2.png)

**Comment by rkaufman13** [comment]
@datner can you elaborate on this? if you edit the type declaration in `react-table-config.d.ts` this works for you?

**Comment by datner** [comment]
@rkaufman13  yes. Like a charm!
there are 2 options that work in different situations
if the column is not obviously sortable (meaning, accessor function) you can pass `canSort: true` to enable the sorting behavior. **but**! if the column is sortable (meaning, accessor string), passing any `canSort` doesn't do anything. But passing `disableSort: true` does!
I of course didn't try try a dictionary attack on the interface to find this out, I concluded this from the source code 🤔 
```ts
const col1 = {
  id: 'foo'
  accessor: data => data.foo,
  canSort: true, // enables sorting
  disableSort: false, // does nothing
  defaultCanSort: true, // does nothing
  sortType: someSortFn
}

const col2 = {
  accessor: 'bar',
  canSort: false, // does nothing
  disableSort: true, // disables sorting
  defaultCanSort: false, // I think it disabled it? Not sure
}

**Comment by dpovey** [comment]
I have a similar issue, in my case I had to set `canSort: true` on the column but this is not covered by Typescript definitions so had to hack it in.  Be good if the documentation and types could be updated.
