### ISSUE TITLE
Examples are broken with latest (7.0.1 / 7.0.2)

### ISSUE THREAD

**Issue by skokenes** [tannerlinsley/react-table#2088]
None of the examples on the documentation site work anymore. Codesandbox produces an unable to resolve dependencies error with the latest version of react-table.

Try any of the Codesandbox examples. For example: https://codesandbox.io/embed/github/tannerlinsley/react-table/tree/master/examples/basic

**Comment by madbiker88** [comment]
It is working for me - see pasted picture below, though on other issus I have sometimes found codesandbox trips up - probably many waays to refresh, but I typically log off my computer to clear any background tasks then log back in.  Picture below:
![image](https://user-images.githubusercontent.com/40077141/78263431-6f208800-755e-11ea-9614-e6013d0183ff.png)

**Comment by tannerlinsley** [comment]
The actual issue is gone now that the release was made for the @latest tag. However, codesandbox still has hiccups for whatever reason. They know of the issue and they are working on it.
