### ISSUE TITLE
Documentation link for useTable is broken in V7 master docs

### ISSUE THREAD

**Issue by madbiker88** [tannerlinsley/react-table#2089]
In master version of documentation - get 404 error.  Easy to fix as it is a typo.
error is on page: https://github.com/tannerlinsley/react-table/tree/master/docs/api

Current link is to:
https://github.com/tannerlinsley/react-table/blob/master/docs/**api/api/**useTable

It should be changed to
https://github.com/tannerlinsley/react-table/blob/master/docs/api/useTable.md

**Comment by tannerlinsley** [comment]
Please submit a PR to fix this1
