### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by ggascoigne** [tannerlinsley/react-table#2095]
If I check out master (25f1fba), run `yarn && yarn test`, all of the non-lint tests fail with:

```
 FAIL  src/hooks/tests/useTable.test.js
  ● Test suite failed to run

    /Users/ggp/dev/git/rt2/configs/tests/setup.common.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import '@testing-library/jest-dom/extend-expect';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
          at Array.forEach (<anonymous>)
```

I've not spent that much time digging into this, but it's been broken for me like this for quite a long time.

**Comment by tannerlinsley** [comment]
Weird. It runs locally for me. I’ll wipe the repo and try again

**Comment by omridevk** [comment]
also runs locally for me, clean repo(tried on master and on the mentioned commit id), same results, all tests passes successfully.

**Comment by ggascoigne** [comment]
Hmm, my error was on a fresh clone of the repo too.

What version of node, yarn/npm were you using?  I’m happy to beleive that
it’s some difference in my environment, but so far I’ve not tracked it down.

**Comment by omridevk** [comment]
node: v12.16.1
yarn: 1.22.4
MacOS  Catalina.

**Comment by ggascoigne** [comment]
Worked it out.

I had NODE_ENV=development set globally, unset it or set it to test and the tests work.  Interestingly the same thing happens using jest with snowpack, looks like it's a jest issue.
