### ISSUE TITLE
README says filtering is supported, but I don't see where

### ISSUE THREAD

**Issue by rosensama** [tannerlinsley/react-table#21]
The `Data` section of README.md says "Client-side filtering and pagination is built in".   I see the pagination, but no signs of filters. Can you point me to how I might enable filtering?  Or perhaps more likely the README needs to be edited?

Thanks for the nice package.

**Comment by tannerlinsley** [comment]
Good point.  Filtering in the sense you are thinking of is not supported (meaning, there is no built-in UI to filter).  This is unfortunate, and I have thought about including a UI to do this, but at the moment I can't think of a way to do this without making some heavy assumptions.  

The way I currently achieve this is by creating my own UI, either inside the table with header or cell renders, or outside the table, that filters my raw data before passing it to the table.  In a nutshell, I simply use a text box that filters my data using https://github.com/kentcdodds/match-sorter as I type. Nothing crazy

If you're looking for a more out-of-the-box solution, maybe we can discuss it and come up with something simple that would work easily for everyone.

Regardless of what we do, I would accept a PR to remove `filtering and` from the README for now until we actually support it out of the box. :)

**Comment by tannerlinsley** [comment]
Fixed by replacing `filtering` with `sorting` :)
