### ISSUE TITLE
Dynamic Columns not compatible with filtering

### ISSUE THREAD

**Issue by theCmaker** [tannerlinsley/react-table#210]
## Problem Description
I am currently working on a project that needs columns to be shown/hidden dynamically. To toggle them, I use the `show` property on `columns`. Some of these columns can be filtered (using the default filter). But when I want to hide a column with an active filter, I get the following error:

```log
react-table.js:6 Uncaught TypeError: Cannot read property 'filterMethod' of undefined
    at https://unpkg.com/react-table@5.5.3/react-table.js:6:10800
    at Array.filter (native)
    at https://unpkg.com/react-table@5.5.3/react-table.js:6:10601
    at Array.reduce (native)
    at Object.filterData (https://unpkg.com/react-table@5.5.3/react-table.js:6:10571)
    at Object.getSortedData (https://unpkg.com/react-table@5.5.3/react-table.js:6:10218)
    at Object.setStateWithData (https://unpkg.com/react-table@5.5.3/react-table.js:6:6019)
    at Object.componentWillReceiveProps (https://unpkg.com/react-table@5.5.3/react-table.js:6:5356)
    at https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react-dom.js:5065:23
    at measureLifeCyclePerf (https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react-dom.js:4529:12)
```

In file `methods.js` near line 266 (in `filterData()`), data filtering is performed on visible columns, but the `filtering` list is kept aside. When a filter is active on a column that gets hidden, `filtering` still has a filterId referencing a column which is not accessible anymore in `visibleColumns` (the origin of the error I got).

Is there a trick to reset the filter before "removing" the column? (Except asking the user to do it :/)

## Example
```js
const ReactTable = window.ReactTable.default

let columns = [{
	header: 'First Name',
	accessor: 'firstName'
}, {
	header: 'Last Name',
	id: 'lastName',
	accessor: d => d.lastName,
	show : true,
}, {
	header: 'Age',
	accessor: 'age'
}]

class MyTable extends React.Component {
	constructor(props) {
		super(props)
		
		this.state = {
			cols: props.cols,
		}
	}
	
	onToggleCol() {
		let {cols} = this.state
		cols[1].show = ! cols[1].show
		this.setState({cols: cols})
	}
	
	render() {
		return (
			<div>
				<h1>React-Table - Example with dynamically shown column</h1>
				<button onClick={this.onToggleCol.bind(this)}>Show/Hide <strong>Last Name</strong></button>
				<ReactTable
					data={makeData()}
					columns={this.state.cols}
					showFilters={true}
				/>
				<br />
				<br />
				<h1>For more examples, <a href="https://react-table.js.org" target="_blank">see our react storybook</a></h1>
			</div>
		)
	}
}

ReactDOM.render(<MyTable cols={columns} />, document.getElementById('root'))


function makeData () { ... } // The same as the CodePen example
```

## Steps to Reproduce
1. Hide then show again the `lastName` column (the provided button),
2. Perform a filtering operation on the column,
3. Try to hide the column again. It ends up with an error (console).

## System Information
* **Browser & Browser Version:** Chrome 57.0.2987.133
* **Node Version:** 6.10.0
* **OS Version:** Windows 7 Pro
* **NPM Version:** 4.4.1

**Comment by TacticalCoding** [comment]
You found a use case I didn't think of when writing it. This is a bug. I think the right thing to do is ignore the filters on columns that are hidden. How does that sound?

**Comment by theCmaker** [comment]
Actually, I think it is the best (and easier) solution. I agree with you.

**Comment by theCmaker** [comment]
Hi,

The problem is still there in v6.0.0. 
I had a look at the code. It is something very simple (just a few lines of code).
I am writing a PR to fix that.

**Comment by sathya-exalogic** [comment]
thanku
