### ISSUE TITLE
v6 tag pointing at 6.11.4 instead of 6.11.5 at https://www.npmjs.com/package/react-table

### ISSUE THREAD

**Issue by dje1990** [tannerlinsley/react-table#2104]
At the npm site
https://www.npmjs.com/package/react-table

in the Versions tab, 
The v6 tag is pointing at 6.11.4 instead of 6.11.5
Is this a mistake?

**Comment by cristianocca** [comment]
Looks like v6 also points to an outdated v6 branch:

"react-table-v6": "6.8.6" is the current latest on npm, but 6.11.5 is supposed to be the latest version?  @tannerlinsley can you take a quick a look at it? Some people are stuck with v6 :(

**Comment by tannerlinsley** [comment]
- Are you using v6 and v7 in parallel? If not, then just use `react-table@6`, which should be fine.
