### ISSUE TITLE
React fragment should't include 

### ISSUE THREAD

**Issue by fedorenko-dmitriy** [tannerlinsley/react-table#2107]
Hi guys. I updated my app and catch error which didn't appear in the past.  

Updated from
"react-table": "^7.0.0-rc.15",
to
"react-table": "version": "7.0.0"

The table uses code from the table expanded example in your's page
```js
<tbody {...getTableBodyProps()}>
                {rows.map((row, i) => {
                  prepareRow(row)
                  return (
                    <React.Fragment {...row.getRowProps()}>
                      <tr className={row.isExpanded ? styles.selectedRow : null}>
                        {row.cells.map((cell, index) => {
                          return (
                            <td key={index} className={cell.column.className} {...cell.getCellProps()}>{cell.render('Cell')}</td>
                          )
                        })}
                      </tr>
                      {/*
                          If the row is in an expanded state, render a row with a
                          column that fills the entire length of the table.
                        */}
                      {row.isExpanded ? (
                        <tr {...row.getRowProps()}>
                          <td colSpan={visibleColumns.length}>
                            {renderRowSubComponent(row)}
                          </td>
                        </tr>
                      ) : null}
                    </React.Fragment>
                  )
                })}
              </tbody>
```

The error I catch is 
"Warning: Invalid prop `role` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props."
<img width="809" alt="Screen Shot 2020-04-06 at 1 11 18 PM" src="https://user-images.githubusercontent.com/13682979/78548757-f5142b80-7809-11ea-9386-ebcd9cb291a0.png">

**Comment by tannerlinsley** [comment]
You can only pass the `key` prop to a fragment, all of the other props must be spread onto the row elements.

**Comment by fedorenko-dmitriy** [comment]
Sorry, but it is your example 
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/expanding
And before it works properly!

**Comment by npomfret** [comment]
Whats the solution?  I followed the examples and am getting this error

**Comment by adrenalin8231** [comment]
Dear future me (and everyone struggling like me),

[Another example](https://react-table.tanstack.com/docs/examples/sub-components-lazy) already have dealt this issue:
```tsx
// L143-148
          prepareRow(row);
          const rowProps = row.getRowProps();
          return (
            // Use a React.Fragment here so the table markup is still valid
            <React.Fragment key={rowProps.key}>
              <tr {...rowProps}>
```
or you can just fix L77 of [our example](https://react-table.tanstack.com/docs/examples/sub-components) appropriately.
```tsx
// L77, as-is
              <React.Fragment {...row.getRowProps()}>

// L77, to-be
              <React.Fragment key={row.getRowProps().key}>
```

Stay safe!

**Comment by hungdev** [comment]
@adrenalin8231,thank you, it worked. But dont forget remove {...row.getRowProps()}
