### ISSUE TITLE
Can not use global filter with column filter in the same table which has checkbox selection !

### ISSUE THREAD

**Issue by hung1998pro** [tannerlinsley/react-table#2113]
This is my react table, it works fine when I use column filter
![image](https://user-images.githubusercontent.com/22428822/78655275-fa4ba600-78ef-11ea-89c8-40eb67ed6560.png)
But, when I type in global filter the key 'a', it turns to this error
![image](https://user-images.githubusercontent.com/22428822/78655573-69c19580-78f0-11ea-9a9f-32a588b0f7b5.png)
It took me a few hours to troubleshoot because there's no one have run into my problem. 
This is the code I defined for the checkbox selection
![image](https://user-images.githubusercontent.com/22428822/78656024-fd936180-78f0-11ea-854a-49f618867f76.png)
I already set the `disableFilters` property to true, but when I type in the global filter, the page rerender and the `disableFilters` property automatically turn to true
![image](https://user-images.githubusercontent.com/22428822/78656656-eb65f300-78f1-11ea-856b-b4283aeb9913.png)
This is the picture when the table just initializes, `disableFilters` property of the checkbox is false
![image](https://user-images.githubusercontent.com/22428822/78657267-b60dd500-78f2-11ea-84d1-391d9e15b421.png)

**Comment by tannerlinsley** [comment]
Please reopen with a codesandbox example as outlined in the issue template.
