### ISSUE TITLE
Need to have both row click and cell click. But on cell click, both the cell click and row clicks are getting triggered

### ISSUE THREAD

**Issue by IamDhana** [tannerlinsley/react-table#2114]
**Description**
Need to have both row click and cell click. 
If I click cell only cell click should be triggered. 
If I click row click only row click should be triggered.
But on cell click, the row click also getting triggered. 

**example via Codesandbox!**
https://codesandbox.io/s/wonderful-wozniak-sn3yt?file=/src/App.js

**Steps To Reproduce**
1. Click on Edit button
2. Edit click is triggering both edit button click and also row click.

![table](https://user-images.githubusercontent.com/24955135/78677871-dd21d200-7905-11ea-957b-5182b72c0c5a.png)

**Comment by kizu** [comment]
You can use the `stopPropagation()` method of the click event, it would prevent the event from bubbling to the row:

```jsx
            onClick={(e) => {
              onClickActionCB(row.original, "isEdit");
              e.stopPropagation();
            }}
```
