### ISSUE TITLE
Hashed class name does not match expected class name

### ISSUE THREAD

**Issue by byumark** [tannerlinsley/react-table#212]
I'm having an issue importing the react-table.css with webpack. My webpack configuration file adds a hash to the end of css class names and the ReactTable component does not refer to the classes with the hashes.

So the hashed class name looks something like `ReactTable-23I04` and the component is looking for a class name of `ReactTable`.

Any thoughts on a way to work around this? I've tried using two different css loaders with different tests but I haven't had much luck.

**Comment by tannerlinsley** [comment]
You will need to import the CSS file as a global CSS important. Though I
myself am not sure how exactly that is done

**Comment by TacticalCoding** [comment]
Does anything in this ticket help? https://github.com/tannerlinsley/react-table/issues/187

Normally the css loaders don't mangle class names. You might need to set up a custom test for this particular css file and tell it to not add a hash to the class names.

**Comment by byumark** [comment]
Yes, that does help! Thank you!
