### ISSUE TITLE
useRowSelect not work with React.StrictMode

### ISSUE THREAD

**Issue by ShcherbakovDV** [tannerlinsley/react-table#2120]
**Describe the bug (required)**

When using `React.StrictMode` in conjunction with `useRowSelect`, I cannot select more than one row. And in selectedRowIds I only get data from the first selection

**Provide an example via Codesandbox! (required)**
I fork base `useRowSelect` example and add `React.StrictMode`.
[Exsample](https://codesandbox.io/s/adoring-varahamihira-2f2wy?file=/src/index.js)

**Steps To Reproduce (required)**
0. State before:
```
"selectedRowIds": {},
```
1. Select first line. 
```
"selectedRowIds": {
    "0": true,
    "0.0": true,
    "0.1": true,
    "0.2": true
  } 
``` 
2. Select second line
```
"selectedRowIds": {
    "0": true,
    "0.0": true,
    "0.1": true,
    "0.2": true
  } 
``` 
3. Select third line
```
"selectedRowIds": {
    "0": true,
    "0.0": true,
    "0.1": true,
    "0.2": true
  } 
``` 

**Expected behavior (Recommended)**
0. State before:
```
"selectedRowIds": {},
```
1. Select first line. 
```
"selectedRowIds": {
    "0": true,
    "0.0": true,
    "0.1": true,
    "0.2": true
  } 
``` 
2. Select second line
```
"selectedRowIds": {
    "0": true,
    "1": true,
    "0.0": true,
    "0.1": true,
    "0.2": true,
    "1.0": true,
    "1.1": true,
    "1.2": true
  },
``` 
3. Select third line
```
{
  "selectedRowIds": {
    "0": true,
    "1": true,
    "2": true,
    "0.0": true,
    "0.1": true,
    "0.2": true,
    "1.0": true,
    "1.1": true,
    "1.2": true,
    "2.0": true,
    "2.1": true,
    "2.2": true
  },
``` 

**Desktop (please complete the following information):**

- OS: macOS 10.15.2
- Google Chrome
- Version 80.0.3987.149

**Comment by chmod77** [comment]
I am having the same issue. 
``` "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1",
    "react-table": "latest",
    "styled-components": "^4.3.2"
```

OS = Linux Mint 19.3
Brave Browser - Version 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)

**Comment by gargroh** [comment]
Try once in production mode with react strict mode on. Wanted to rule out
this behaviour https://github.com/facebook/react/issues/12856

**Comment by reisnobre** [comment]
Same problem here

**Comment by spectras** [comment]
Here is another sandbox that shows the problem:

https://codesandbox.io/s/hopeful-elion-9ueg9?file=/src/index.js

**To reproduce:**
- Simply tick the checkbox in order.
- As you tick the 3rd checkbox, the 2nd will untick itself.
- Also, the selection count does not get updated.

**Without strict mode:**
- Comment out the two strict mode lines on the left.
- Everything works as expected (checkboxes have consistent behavior, and selection count is updated).

**Ideas**
I believe this could come from either of two design issues (or the combination of both).

1) There are side effects in a `useMemo` hook:
```js
const selectedFlatRows = React.useMemo(() => {
    const selectedFlatRows = []

    rows.forEach(row => {
      const isSelected = selectSubRows
        ? getRowIsSelected(row, selectedRowIds)
        : !!selectedRowIds[row.id]
      row.isSelected = !!isSelected               // <====== SIDE EFFECT
      row.isSomeSelected = isSelected === null    // <====== SIDE EFFECT

      if (isSelected) {
        selectedFlatRows.push(row)
      }
    })

    return selectedFlatRows
  }, [rows, selectSubRows, selectedRowIds])
```

2) The state reducer [reads state](https://github.com/tannerlinsley/react-table/blob/master/src/plugin-hooks/useRowSelect.js#L126) outside of `previousState`, which may or may not be up to date (resolving this ambiguity is the whole point of the reducer pattern).

I know for sure it causes issues even without strict mode:
→ eg: calling `toggleAllRowsSelected(false) ; someRow.toggleRowSelected(true)` leaves `someRow` unselected *if it was selected*.
* AllRows reducer runs correctly.
* Then single row reducer reads `row.isSelected`, which has not yet been updated (so it's `true`).
* It concludes selection should not be updated.
* Then template is rendered, causing `isSelected` to account as per 1).

**Comment by iansilva6** [comment]
I have the same problem

**Comment by aethelz** [comment]
Same problem, was very hard and time-consuming to find the underlying issue, but finally narrowed it down to strict mode :(

**Comment by arielaco** [comment]
Same issue. Bumping it. Will this get a fix? Don't really want to stop using strict mode.

**Comment by tannerlinsley** [comment]
Going to track this in #2170
