### ISSUE TITLE
React-table v7 may be not incompatible with Terser

### ISSUE THREAD

**Issue by rufusnguyen** [tannerlinsley/react-table#2130]
In our application, I am using webpack 4 with Terser plugin for optimizing our bundles however while I set our webpack optimization config: 
`optimization: {
    minimize: true,
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          warnings: false,
          compress: {
            comparisons: false,
          },
          parse: {},
          mangle: true,
          output: {
            comments: false,
            ascii_only: true,
          },
        },
        parallel: true,
        cache: true,
        sourceMap: true,
      }),
    ],`
The react-table showed empty rows and no row data display in each of them. When I turned off our webpack optimization to false, the react-table showed data properly. Has someone dealt with this issue? Could you please help to take a look?

**Comment by tannerlinsley** [comment]
This was fixed in a recent release. Please make sure you are up to date.
