### ISSUE TITLE
Text strings must be rendered within a <Text> component

### ISSUE THREAD

**Issue by surajmdl** [tannerlinsley/react-table#2144]
I am getting some kind of error while using this component. Kindly see the screenshot for error detail. Below is the code which I'm using.

--------Installed Component-------------
npm install react-table-6
-------------------Below is the code-----------------------------------------------
`import React, {Component} from 'react';
import ReactTable from 'react-table-6';
<link
  rel="stylesheet"
  href="https://unpkg.com/react-table-6@latest/react-table.css"
/>;

export default class DataTable3 extends Component {
  render() {
    const data = [
      {
        name: 'Tanner Linsley',
        age: 26,
        friend: {
          name: 'Jason Maurer',
          age: 23,
        },
      },
      {
        name: 'Suraj Kumar',
        age: 28,
        friend: {
          name: 'Rohit K',
          age: 25,
        },
      },
    ];

    const columns = [
      {
        Header: 'Name',
        accessor: 'name', // String-based value accessors!
      },
      {
        Header: 'Age',
        accessor: 'age',
        Cell: props => <span className="number">{props.value}</span>, // Custom cell components!
      },
      {
        id: 'friendName', // Required because our accessor is not a string
        Header: 'Friend Name',
        accessor: d => d.friend.name, // Custom value accessors!
      },
      {
        Header: props => <span>Friend Age</span>, // Custom header components!
        accessor: 'friend.age',
      },
    ];

    return <ReactTable data={data} columns={columns} />;
  }
}
`

![ReactTable6 Error](https://user-images.githubusercontent.com/11940579/79079061-4a7c9b00-7d2a-11ea-8e00-7947304ffd4d.jpeg)

**Comment by tannerlinsley** [comment]
Looks like you're using react-native, in which case you will need to override the default Cell renderer for your tables to use the Text component wrapper.
