### ISSUE TITLE
Render() Can't mutate row props in custom component 

### ISSUE THREAD

**Issue by dcworldwide** [tannerlinsley/react-table#216]
## Problem Description
I have a cell renderer with a custom text field. I want the text field to mutate the row object that is passed into the text field by the render function.  Mutations are not working. 

Does react-table support mutations of cell values? 

In my case, the row objects are mobx observables. 

Thanks, great library btw!

**Comment by tannerlinsley** [comment]
Thanks for using React-Table!

You should be able to mutate the `properties` of the `rowInfo` object, but not the `rowInfo` object itself, and likewise, MobX, if configured correctly I am assuming, will detect these changes. Do remember though that React-Table was built with the same level of immutability that is recommended by React itself.  Just as `props` themselves are not meant to be mutated, React-Tables state has been architected to retain immutable integrity. 

If you keep having problems, please consider posting the question to our [slack org](https://react-chat-signup.herokuapp.com/)'s #react-table channel.  There may be someone there that uses MobX that could help.

Closing as this is more of an implementation question and has much to do with MobX.
