### ISSUE TITLE
My builds are failing due to one of newer dependancies scarfjs

### ISSUE THREAD

**Issue by thecodejack** [tannerlinsley/react-table#2169]
I have raised the request there https://github.com/scarf-sh/scarf-js/issues/13

but it would be great if you can disable scarfjs until fix is in place

**Comment by aviaviavi** [comment]
Fix is in place and released, so please let me know if you're still having issues. Very sorry for the trouble here, but thanks for reporting the issue. Scarf-js intends to _never_ bubble up errors like this, but there was a bug in our error handling of some non-promise based node api's.
