### ISSUE TITLE
Incosistent behaviour when using subRowsKey

### ISSUE THREAD

**Issue by aight8** [tannerlinsley/react-table#217]
## 1. Indent by level difficulties

I want to describe some problems I found when using the ```subRowsKey``` property (it's not really documented so I started to try it out myself).

I currently don't found a nice way how to indent sub items by level. see:
<img width="309" alt="bildschirmfoto 2017-04-21 um 11 43 00" src="https://cloud.githubusercontent.com/assets/1138623/25272389/e188136e-2687-11e7-9c3c-323eaf6e7ab0.png">

I solve it currently like this:
```
getTdProps={(state, row) => {
   //console.log('getTdProps', state, row)
   if (!row) {
      return {}
   }
   return {
      style: {
         marginLeft: row.level * 10
      },
   }
}}
```

**The problem is:**
- **My current solution isn't maintaining the shared column width across all rows.**
- ExpanderComponent config property is called but only with useless argument (```{isExpanded: undefined}, (empty object), (ReactElement)```)
- The column ```render``` method which is defined in the ```columns``` configuration is never called after apply the ```expander``` property to the column. Some other values doesn't work neither (it's unclear which properties it disables). The style however is applied:
```JS
{
   expander: true,
   style: {
      cursor: 'pointer',
      userSelect: 'none'
   },
   render: (r) => {
      return <div>test</div>
   },
},
```

So I wondering if there is a elegant way to do this today. However the above described problems are still the same.

## 2. Expander rendering

Here the screenshot again:
<img width="309" alt="bildschirmfoto 2017-04-21 um 11 43 00" src="https://cloud.githubusercontent.com/assets/1138623/25272812/91d1755c-2689-11e7-9aae-65679dfbd070.png">

I want to hide the expander if there are no sub items. This could be also accomplished if the expander render function would be called with all the row information (especially row.subRows is used here).

**Comment by aight8** [comment]
The last release some hours ago exactly implement this one. Incredible work!

**Comment by TacticalCoding** [comment]
Could you elaborate how the new release fixes your issue for others that might have the same issue? Are you taking advantage of the expander column's `render` option?

**Comment by aight8** [comment]
Yeps ;)!

**Comment by rajmiglani** [comment]
Hi,

I am facing an unwanted problem. The expander icon is not at all redering in the table. Its rendering in my local but not in production. Strange.

react table version: 6.7.6
