### ISSUE TITLE
version 7.0.4, filter: 'includes', not working as before

### ISSUE THREAD

**Issue by schoi8uber** [tannerlinsley/react-table#2174]
**Describe the bug (required)**
In version v7.0.4, I noticed that the select filter using below not working any more.
`filter: 'includes' `

This works fine in the previous version I had v7.0.0. I think it seems to perform AND operator instead of OR when there are multiple values selected from the dropdown.

**Provide an example via Codesandbox! (required)**
Use a new [react-table codesandbox](https://codesandbox.io/s/m5lxzzpz69) to reproduce the issue.

**Steps To Reproduce (required)**

**Expected behavior (Recommended)**
Select filter using filter: 'includes', should perform OR operator to filter out all rows including any of selected values.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS]: MacOS 10.15.3
- Browser [e.g. chrome, safari]: Chrome 
- Version [e.g. 22]: Version 81.0.4044.92 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ericberens** [comment]
Related: https://github.com/tannerlinsley/react-table/pull/2001
