### ISSUE TITLE
Feature request: Native support for column spaning

### ISSUE THREAD

**Issue by aight8** [tannerlinsley/react-table#218]
I have accomplished almost everything with lot of try-out and battle-testing what this awesome library can do.
Now I have one point which could be interesting.

If you use the ```pivot``` or ```sub items``` feature you have the **parent row** and it's **child rows**. I recognised that most time I want to span some columns (not all just some) to make some better summaries about the particular sub rows.

I tried out some ways but it results in chunky clunky hacks which is not really neat without text ellipse etc.
Native column spanning could be a very nice feature for parent rows.

What you think, how difficult this is to implement?

**Comment by tannerlinsley** [comment]
This will likely not enter the core of React-Table any time soon. But it would help us further down that path if you could help us with a few things:

- Post a screenshot/mockup of what you are wanting
- Implement spanning using Component Overrides. You can override the core functionality of any component very easily in React Table.  You may be able to do this on your own, and if it is simple enough to achieve, we may consider adding it to the core it's it works well and becomes a large use case for more people.

Going to close this issue for now, but I will remain active on it for questions on implementation and for tracking progress of this feature request :)
