### ISSUE TITLE
Adding an extra header disturbs the allignment of other headers

### ISSUE THREAD

**Issue by ashwanikumar415** [tannerlinsley/react-table#2187]
**Describe the bug (required)**
![image](https://user-images.githubusercontent.com/7288437/79564212-d3e5f180-80cb-11ea-9dc2-f892f1c964f6.png)

Sandbox link :
 https://codesandbox.io/s/confident-fermi-hlum3?file=/src/App.js 

Create columns as mentioned in sandbox
As you observe , column header : FirstName & LastName should be parallel to Info. But with react table they are parallel to : Age,Visits,Status, ProfileProgress.
Is there a way cells on top of FirstName and LastName be removed ?
**Expected behavior (Recommended)**

![image](https://user-images.githubusercontent.com/7288437/79567645-39d57780-80d2-11ea-94bf-38ff97e583ea.png)

**Comment by tannerlinsley** [comment]
You can fiddle with the rowSpan of these headers if you like, but this is currently beyond the scope of React-Table since it's a headless utility, not a component.
