### ISSUE TITLE
Question: Filter Textfiles

### ISSUE THREAD

**Issue by orangecoding** [tannerlinsley/react-table#219]
Hi,
not sure if this is the correct place to ask this question, probably not (sorry), but I'd like to know whether it is possible to display a search field above the table to filter the tabledata. The filter should work on all columns, not a specific one. So I would like to have kind of a full text search that searches over all columns.

**Comment by aaronschwartz** [comment]
This is definitely possible. But it has very little to do with react-table itself. You'll need to make your own text  field above the table which filters the `data` prop being passed to react-table. The table will re-render with the newly filtered data.

**Comment by orangecoding** [comment]
thanks!
