### ISSUE TITLE
Column property isSorted is set to false when we click on same column repeatedly

### ISSUE THREAD

**Issue by Sureddy08** [tannerlinsley/react-table#2197]
**Describe the bug (required)**
At first, all columns isSorted property is false. Let's say when we click on first column ("First Name") Three times 
1) On First time - isSorted should be true, isSortedDesc=false and sortedIndex =0.
2) On second time  - isSorted should be true, isSortedDesc=true and sortedIndex =0.
3) On third time  - isSorted should be false, isSortedDesc=undefined and sortedIndex =-1.

**Expected behavior (Recommended)**
On third time, It should be isSorted=true, isSortedDesc=false and sortedIndex =0.

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/kitchen-sink

**Comment by ivaskevych** [comment]
I think you are looking for `disableSortRemove: true` property

**Comment by Sureddy08** [comment]
> I think you are looking for `disableSortRemove: true` property

Thank you for the reply. I am not looking for disableSortRemove: true property. if you open the sandbox and try to click on first name column header repeatedly as you can see on third time the sort icon is missing(Inactivated). I am expecting it should sorted the rows by ascending order.

**Comment by ivaskevych** [comment]
> on third time the sort icon is missing(Inactivated)

That is because on third click column sorting state is set to default un-sorted state, that's why you need that option to disable this behavior.

- `disableSortRemove: Bool`
  - If true, the un-sorted state will not be available to columns once they have been sorted.

check this [sandbox](https://codesandbox.io/s/funny-shape-mhghd?file=/src/App.js:7605-7622)

**Comment by Sureddy08** [comment]
> > on third time the sort icon is missing(Inactivated)
> 
> That is because on third click column sorting state is set to default un-sorted state, that's why you need that option to disable this behavior.
> 
> * `disableSortRemove: Bool`
>   
>   * If true, the un-sorted state will not be available to columns once they have been sorted.
> 
> check this [sandbox](https://codesandbox.io/s/funny-shape-mhghd?file=/src/App.js:7605-7622)

Gotcha! Thank you

**Comment by rossthedevigner** [comment]
@ivaskevych Is there a way to capture the current sort state so that when that 3rd un-sorted state comes around you can trigger the original column you wanted to sort by? Or is there an option to do that currently?
