### ISSUE TITLE
On row click

### ISSUE THREAD

**Issue by DimitryDushkin** [tannerlinsley/react-table#22]
Is there is any way to subscribe on row click event?

If it's not I can try to contribute it.

**Comment by tannerlinsley** [comment]
Options to achieve this:
1. Place onClick handlers on your rendered elements in each cell (cumbersome, but works right now)
2. Override the `trComponent` to use a custom one that implements onClick functionality
3. Submit a PR that does the following:

- Add an `onTrClick` event after (this)[https://github.com/tannerlinsley/react-table/blob/master/src/index.js#L25] with a good default noop.  Probably something like:
```javascript
onTrClick: () => null
```
- Add an `onClick` handler [here](https://github.com/tannerlinsley/react-table/blob/master/src/index.js#L362) that will fire the `onTrClick` prop with all of the appropriate information about the row.  eg:
```javascript
onClick={(event) => this.props.onTrClick(rowInfo, event)}
```

I would also be okay with the prop being called `onRowClick` if that feels or sounds better.

Thoughts? :)

**Comment by DimitryDushkin** [comment]
Sounds good!) I'll send PR.

**Comment by DimitryDushkin** [comment]
https://github.com/tannerlinsley/react-table/pull/23
