### ISSUE TITLE
How to change TR style on TD Click

### ISSUE THREAD

**Issue by parmod-arora** [tannerlinsley/react-table#220]
How to change TR style on TD Click.

http://codepen.io/parmodkrarora/pen/wdWoBd/?editors=0010

```const columns = [{
  header: 'Name',
  columns: [{
    render: (rowInfo, column) => {
			const onClicked = () => {
				console.log('How i can change Tr style here');
			};
			return (
				<span onClick= {onClicked} className='number'>close</span>
			)
		}
  }```

**Comment by parmod-arora** [comment]
```columns: [{
    render: (rowInfo, column) => {
			const onClicked = () => {
				rowInfo.selected = true; // Not working
				rowInfo.row.selected = true; // Not working
				rowInfo.rowValues.selected = true; // Not working
				console.log('How i can change Tr style here');
			};
			return (
				<span onClick= {onClicked} className='number'>close</span>
			)
		}
  }
```

On Changing rowInfo object MyTRComponent is not rendering again.
Any Suggestion ??

**Comment by mikedevita** [comment]
its most likely because your click function is inside of the render, which will get reset next time it re-renders. you should either track this in another scope (like in the component calling ReactTable) or in state.

**Comment by tannerlinsley** [comment]
@mikedevita nailed it. This state must be tracked outside of the table in your parent component's state. Remember that `rowInfo` is not a mutable object and changing values on it is not only not recommended, but also will not trigger rerenders to any components that use that value.
