### ISSUE TITLE
Column options are not working

### ISSUE THREAD

**Issue by malsioufi** [tannerlinsley/react-table#2200]
**Describe the bug (required)**
When I set isVisible or canFilter on a column to false, both option are overridden

**Provide an example via Codesandbox! (required)**
I have started with the filtering example and modified it a little bit
https://codesandbox.io/s/divine-wood-b9331

**Steps To Reproduce (required)**
1. Set isVisible or canFilter on a column to false
Check: https://codesandbox.io/s/divine-wood-b9331?file=/src/App.js

**Expected behavior (Recommended)**
To have a hidden column or the column can not be filtered

**Comment by hybmg57** [comment]
were you able to fix the issue? I'm getting same results if I set `canFilter` to `false` it still gets overwritten to `true`

**Comment by malsioufi** [comment]
Not really, in fact I changed to another package after I felt that react-table v7 is over-complicating things for me. 
But there is another discussion related to the issue, you can find it here
https://github.com/tannerlinsley/react-table/issues/1804#issuecomment-622028808

**Comment by hybmg57** [comment]
I actually used `disableFilters` to `true` and it worked fine. See [useFilters documentation](https://github.com/tannerlinsley/react-table/blob/master/docs/api/useFilters.md#column-options)

**Comment by tannerlinsley** [comment]
> I actually used disableFilters to true and it worked fine. See useFilters documentation

Yep!
