### ISSUE TITLE
Not Supporting Insensitive case sorting

### ISSUE THREAD

**Issue by Kavimugilan17** [tannerlinsley/react-table#2202]
![image](https://user-images.githubusercontent.com/58725968/79713883-b348b200-82ec-11ea-922a-940d3090b87f.png)

After sorting Lower cases are went down.

Link: https://codesandbox.io/s/holy-voice-3zeqv?file=/src/App.js

**Comment by nomanalikhan** [comment]
I'm having the same problem. Is there a way we can override the default function?

**Comment by Kavimugilan17** [comment]
Insensitive case sorting supported in v6. In v7 why it's not supported?

Link: https://codesandbox.io/s/rt-various-external-filter-footer-component-r15sx?file=/index.js

**Comment by gargroh** [comment]
You can provide your own custom sorting for this, have a look at this https://github.com/tannerlinsley/react-table/blob/master/docs/api/useSortBy.md#column-options

**Comment by Kavimugilan17** [comment]
Great!!, Thank you so much. It's working fine.

Custom Sorting Code:
-----------------------------
const sortItems = (prev: Row<ITaskMetadata>, curr: Row<ITaskMetadata>, columnId: string) => {
  if (prev.original[columnId].toLowerCase() > curr.original[columnId].toLowerCase()) {
    return 1;
  } else if (prev.original[columnId].toLowerCase() < curr.original[columnId].toLowerCase()) {
    return -1;
  } else {
    return 0;
  }
};

Column:
-----------------
   {
    Header: 'Sample Header',
    accessor: 'sampleHeader',
    sortType: (prev, curr, columnId) => {
      return sortItems(prev, curr, columnId);
    }
  }

**Comment by Wgil** [comment]
It would be great if the library could allow insensitive case sorting by default, it is very common to do this kind of sorting in tables. Something like `ignoreCase: true`

**Comment by tannerlinsley** [comment]
Future releases will allow for this more easily. For now, you can override the `alphanumeric` sorter with your own implementation that does exactly what you want.

**Comment by Wgil** [comment]
@tannerlinsley using `sortTypes` key in table options?

**Comment by tannerlinsley** [comment]
Yep. You can override like this:

```js
{
  sortTypes: { alphanumeric: myCustomFn }
}
```

**Comment by tannerlinsley** [comment]
Or just add your own new one and reference it in `column.sortType`

**Comment by Wgil** [comment]
Thanks!
