### ISSUE TITLE
Filter/Edit Cell - the moment we edit the row value, the filter get reset and all the rows are visible

### ISSUE THREAD

**Issue by ankitsalu** [tannerlinsley/react-table#2206]
Steps to replicate :

1) Apply any filter on UI
2) Edit the row by clicking on cell and write anything

Expected Behavior:
1) Cell value should get updated (its working)
2) Existing Filter should stay and should continue to see filter rows (Its not working....the moment we update the cell, the filter get reset and we see all the rows)

example:
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/kitchen-sink

**Comment by ankitsalu** [comment]
same with sort - the moment we update the cell, the sort also reset to default. There should be a way to tell the table that we just need to refresh the data and filters/sort should persist.

Or is there a way to refresh the table without updating the original data which is upsetting the filter/sorting?

**Comment by gargroh** [comment]
Both filter and sort has flag that can help you retain their state on data
update...they are mentioned in their respective hook documentation.
