### ISSUE TITLE
How to add button in each row?

### ISSUE THREAD

**Issue by Abdul-Hameed001** [tannerlinsley/react-table#221]
give me some sample codes to add button in a row.

**Comment by mikedevita** [comment]
you do it via `render`... its in the docs on the front page.

```jsx

const columns = [{
  header: () => <span><i className='fa-tasks' /> Progress</span>,
  accessor: 'progress',
  render: ({ row }) => (<button onClick={(e) => this.handleButtonClick(e, row)}>Click Me</button>)
}];
```

https://github.com/tannerlinsley/react-table#custom-cell-header-and-footer-rendering

**Comment by mcasey8540** [comment]
Below is an updated way to do this via **Cell** property

https://react-table.js.org/#/story/cell-renderers-custom-components

**Comment by enKoding** [comment]
Hey guys, I want to add a Button to delete a record, How can I do this ? I need to pass the item Id to a function.
