### ISSUE TITLE
Table (with expandable rows) with fixed header and vertical scroll?

### ISSUE THREAD

**Issue by SanjaySankar** [tannerlinsley/react-table#2216]
I'm working on a project and I need a **table with** :  

**1. 2 fixed headers, 
2. expandable rows and
3. a vertical scroll on the body.**

I have done the expandable rows part but can't find a way to fix the header and height without breaking the component.

**This is the codesandbox link for what I have now : https://codesandbox.io/s/vibrant-napier-h58np**

**Comment by vijay-dadhich09** [comment]
Hi please let me know if you find any solution?
