### ISSUE TITLE
data looks like a single column

### ISSUE THREAD

**Issue by thisKeeWord** [tannerlinsley/react-table#222]
I'm glad I came across this today to incorporate into my project. I've come across an issue where my data is basically a single column. 

<img width="944" alt="screen shot 2017-04-22 at 8 12 33 pm" src="https://cloud.githubusercontent.com/assets/13548758/25310386/1b956168-2798-11e7-9181-c05fa718a598.png">

This is what I'm getting and I'm not sure if I'm doing something wrong.

My result props is an array of objects like the one you provided in the docs and the columns also like the one you provided.

Any help would be appreciated. :)

 ` <ReactTable data={this.props.result} columns={columns} />`

**Comment by tannerlinsley** [comment]
Have you included the CSS file that comes with react table?

**Comment by thisKeeWord** [comment]
Do I add the css from the node module? I used the one in the example provided 
 





On Sat, Apr 22, 2017 8:58 PM, Tanner Linsley notifications@github.com  wrote:
Have you included the CSS file that comes with react table?
On Sat, Apr 22, 2017 at 9:15 PM Leonard Kee <notifications@github.com>
wrote:

> I'm glad I came across this today to incorporate into my project. I've
> come across an issue where my data is basically a single column.
>
> [image: screen shot 2017-04-22 at 8 12 33 pm]
>
<https://cloud.githubusercontent.com/assets/13548758/25310386/1b956168-2798-11e7-9181-c05fa718a598.png>

**Comment by thisKeeWord** [comment]
I gotchu. Thank you!!!!!!

**Comment by tannerlinsley** [comment]
You're welcome!
