### ISSUE TITLE
Make a release with the last version of `react-table-6`.

### ISSUE THREAD

**Issue by VincentLanglet** [tannerlinsley/react-table#2223]
The `react-table-v6` version was made in order to help the migration between the `v6` and the `v7`.

But the only version available is `v6.8.6` when `react-table` provide `6.11.x` versions.

Could you make a `react-table-v6: 6.11.x` release in order to allow developers to use the last `v6` version during the migration ?

Thanks.

**Comment by Dakkers** [comment]
I was able to install `react-table-6: 6.11.0` today, fwiw

**Comment by VincentLanglet** [comment]
> I was able to install `react-table-6: 6.11.0` today, fwiw

Oh !
There is 
https://www.npmjs.com/package/react-table-v6
And 
https://www.npmjs.com/package/react-table-6

The second one should be used !

**Comment by VincentLanglet** [comment]
The version is still not up-to-date since the last available version is `react-table-6: 6.11.0`.

`react-table` has a `6.11.5` version. A last `react-table-6` release is still needed.

**Comment by Dakkers** [comment]
ah ok, I didn't know it was up to 6.11.5. I am gonna revert my package to 6.10.3 then if I can

**Comment by VincentLanglet** [comment]
@tannerlinsley Hi, do you think this last final release could be possible ? :)

We would like to start the v6-v7 migrations, but without downgroading our actual v6 version.

**Comment by VincentLanglet** [comment]
@tannerlinsley Friendly ping. Can you consider making the last v6 release in order to have an up-to-date alias ?

**Comment by tannerlinsley** [comment]
I do not control the `react-table-v6` npm module. https://www.npmjs.com/~gmfe

**Comment by Dakkers** [comment]
@tannerlinsley don't you own the `react-table-6` module though? https://www.npmjs.com/package/react-table-6

**Comment by tannerlinsley** [comment]
Ah yes, I do. I can do another release on that one. I need ya'll to verify that the v6 branch is good though. We had some trouble publishing a bad PR previously and it got into a funky state.

**Comment by VincentLanglet** [comment]
> Ah yes, I do. I can do another release on that one. I need ya'll to verify that the v6 branch is good though. We had some trouble publishing a bad PR previously and it got into a funky state.

Last commits are https://github.com/tannerlinsley/react-table/commits/v6
So the branch seems ok to me.

**Comment by VincentLanglet** [comment]
Hi @tannerlinsley, if you find any time, a last release would be great :)
