### ISSUE TITLE
Material-UI Enhanced Tabler: redundant horizontal scroll bar

### ISSUE THREAD

**Issue by AndreyMZ** [tannerlinsley/react-table#2225]
**Describe the bug (required)**
There is a redundant horizontal scroll bar (see the screenshot below).

**Provide an example via Codesandbox! (required)**
Use the [react-table codesandbox](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/material-UI-enhanced-table) to reproduce the issue.

**Steps To Reproduce (required)**

1. Go to https://react-table.js.org/examples/ui
2. Scroll down to *Material-UI Enhanced Table*
3. Click on *Open in CodeSandbox*
4. In the *Browser* tab scroll down 

**Expected behavior (Recommended)**
There is no this redundant horizontal scroll bar (see the screenshot below).

**Screenshots**
![actual](https://user-images.githubusercontent.com/9609370/80271544-44ec6100-86eb-11ea-880e-b01482dd47eb.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Vivaldi (chromium-based)
- Version: 3.0.1874.23

**Comment by tannerlinsley** [comment]
Please refer to #2226
