### ISSUE TITLE
Material-UI Enhanced Table: warnings in console

### ISSUE THREAD

**Issue by AndreyMZ** [tannerlinsley/react-table#2226]
**Describe the bug (required)**
There are warnings in browser console.

**Provide an example via Codesandbox! (required)**
Use the [react-table codesandbox](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/material-UI-enhanced-table) to reproduce the issue.

**Steps To Reproduce (required)**

1. Go to https://react-table.js.org/examples/ui
2. Scroll down to *Material-UI Enhanced Table*
3. Click on *Open in CodeSandbox*
4. Click *Console*

**Expected behavior (Recommended)**
No warnings.

**Screenshots**
![actual](https://user-images.githubusercontent.com/9609370/80271702-d3151700-86ec-11ea-90e0-f65c0431854e.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Vivaldi (chromium-based)
- Version: 3.0.1874.23

**Comment by tannerlinsley** [comment]
This is an issue for MUI, not react-table. If it's a problem with the example, then I will accept a PR to update the example. Thanks!
