### ISSUE TITLE
Add cells argument into filterRender

### ISSUE THREAD

**Issue by a-x-** [tannerlinsley/react-table#223]
## Problem Description
I need cells of the column for generating `<select>` elements or input-datalist elements as filters.

## Code Snippet(s)

I desire something like this:

```jsx
import tableDefaultProps from 'react-table/lib/defaultProps';
  const filterRender = ({filter, onFilterChange, cells}) => { // <=== cells added HERE ===
    return <select
      style={{width: '100%'}}
      value={filter ? filter.value : ''}
      onChange={event => onFilterChange(event.target.value)}
    >
      {uniq(cells).map(value => <option {...{value}}/>)}
    </select>;
  }
  const uniq = arr => arr.sort().reduce((uniq, cell) => uniq[uniq.length - 1] === cell ? uniq : uniq.concat(cell), [])

      <Table
        {...{data, columns}}
        column={{...tableDefaultProps.column, filterRender}}
      />
```

**Comment by tannerlinsley** [comment]
I believe you are referring to a uniq list of values in your columns.  This is not something React-Table provides out of the box.  We suggest building the unique list of column values on your own *before* your data enters the table and/or before the column definitions are built.  This way, the `uniq` function would not run on every single rerender of the table, but only when your data changes.

**Comment by a-x-** [comment]
You're right, guy, thank you I missed simple&true solution.
