### ISSUE TITLE
The provided starter codesandbox doesn't compile

### ISSUE THREAD

**Issue by bmcgary** [tannerlinsley/react-table#2240]
**Describe the bug (required)**
The provided codesandbox doesn't work

**Provide an example via Codesandbox! (required)**
Use a new [react-table codesandbox](https://codesandbox.io/s/m5lxzzpz69) to reproduce the issue.

**Steps To Reproduce (required)**

1. Open the starter codesandbox: https://codesandbox.io/s/m5lxzzpz69
There is some "asdf" text that first makes the compile fail. Remove that, and then there is an issue "instance.state is undefined"

**Expected behavior (Recommended)**
I fork the example to tweak it to illustrate my (original) issue

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win 10
- Browser: chrome (v81.0.4044.122 (Official Build) (64-bit)), FF (v75.0)

**Smartphone (please complete the following information):**
Didn't test it on phone

**Additional context**

**Comment by xehpuk** [comment]
I get:
> SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document. (at /src/index.js:32:4)

After replacing `useLocalStorage` with `useState`:
> TypeError: Cannot read property 'groupBy' of undefined (at /src/components/Table.js:85:19)

Probably a wrong link. Doesn't make sense to use `localStorage` für bug reports.

**Comment by tannerlinsley** [comment]
I'm not sure where you got that starter link. Is that in the issue template? If it is, then it should point to the basic example instead. I will accept a PR to fix that if it's the issue.

**Comment by bmcgary** [comment]
Yes it is. I click "New Issue" -> "Bug Report" and in the template that is the link to the code sandbox. When I tried it again just now it now gives me a 404. 🤷‍♂️
I'll try and get a working sandbox into a PR, but may take me a bit as I'm swamped at work.
