### ISSUE TITLE
Unexpected sorting of alphanumeric strings

### ISSUE THREAD

**Issue by nbermudezs** [tannerlinsley/react-table#2245]
**Describe the bug (required)**
There seems to be an issue with sorting alphanumeric strings -- I'd expect the order of the values to match that of `Array.sort` but it is not the case.

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/patient-water-rhi33?file=/src/App.js

**Steps To Reproduce (required)**

1. Go to the [CodeSandbox](https://codesandbox.io/s/patient-water-rhi33?file=/src/App.js)
2. Click on the "colName" header
3. See that the order of the rows is ```["bmlnbwj6bo5", "c9zh0gxho9rp", "c47jyh9le3v1"]```

**Expected behavior (Recommended)**
I'd expect the order of the values to match that of `Array.sort`. That is, 
```js
["bmlnbwj6bo5", "c47jyh9le3v1", "c9zh0gxho9rp"]
```

**Comment by tannerlinsley** [comment]
This will be the new default in the next major version.
