### ISSUE TITLE
defaultSorting: Table unexpectedly changes the sort on re-render

### ISSUE THREAD

**Issue by bgeihsgt** [tannerlinsley/react-table#225]
## Problem Description
Using react-table version 5.6.0

I'm using `defaultSorting` on my table like so:

```
<ReactTable
   defaultSorting={[{id: 'foo'}]}
/>
```

The component I'm using to render the table has its own state that changes. I've noticed if you change the sort order and then do an operation that causes a state change + re-render, the sort order will unexpectedly flip back to the default sort.

I've narrowed down the problem to this code: https://github.com/tannerlinsley/react-table/blob/42b5f5bb18fec5b72421441ef9514507ebcfca91/src/lifecycle.js#L15-L17

The `!==` check is insufficient here as in this case, the object references are different, but the contents of the objects are the same. This could should do a deep equality check instead of just a reference check. 

To confirm this theory, I defined my defaultSorting as a constant and it works perfectly.

## System Information
* **Browser & Browser Version:**
Chrome latest

* **Node Version:**

6.9.5

* **OS Version:**

OS X Sierra

* **NPM Version:**

NPM 3.10.10

* **Yarn Version:**

N/A

**Comment by tannerlinsley** [comment]
This is expected. We simply need to change the documentation to better reflect the need for an immutable array to be used

**Comment by bgeihsgt** [comment]
@tannerlinsley Seems odd to make this the expected behavior -- it creates a pit of failure for people using `defaultSorting`. Why not just do a deep equality check and eliminate the problem altogether?

**Comment by tannerlinsley** [comment]
I can get on board with that then. I'll put this on the docket for our next
release.

**Comment by bgeihsgt** [comment]
Great!
