### ISSUE TITLE
Warning: Cannot update a component while rendering a different component...

### ISSUE THREAD

**Issue by vsshaposhnikov** [tannerlinsley/react-table#2260]
Hi, I noticed a strange feature when I want to pass table state to the he parent component, I get the warning that is discussed here - https://github.com/facebook/react/issues/18178, may be you could update version of react that the table uses to 16.13.1 .

Structure to reproduce
- 2 children, one parent, one child
- Table is a child who passes state to parent

**Comment by tannerlinsley** [comment]
I can't reproduce this. Please reopen with a codesandbox example.
