### ISSUE TITLE
Documentation missing for overriding the Cell renderer

### ISSUE THREAD

**Issue by marvinthepa** [tannerlinsley/react-table#2269]
**Describe the bug (required)**

https://github.com/tannerlinsley/react-table/blob/master/docs/api/useTable.md#cell-properties

```
- `value: any`
  - The **resolved** value for this cell.
  - By default, this value is displayed on the table via the default `Cell` renderer. To override the way a cell displays
```

That sentence stops right in the middle, without explaining how to override the way the cell displays.
Opening as a bug instead of a feature request as it looks like the information was intended to be there.

**Comment by gargroh** [comment]
To override have a look at `Cell` in https://github.com/tannerlinsley/react-table/blob/master/docs/api/useTable.md#column-options

**Comment by marvinthepa** [comment]
@gargroh I was not looking for an answer here. I would have asked on Stackoverflow instead :rofl:.

It just seemed to me that the sentence

  "To override the way a cell displays" (sic!)

is not even a sentence - so it seemed to me the documentation was missing something.
Sorry if I got that wrong and/or did not make myself clear.

**Comment by tannerlinsley** [comment]
You're right, it's not complete. Please open a PR if you would like to fix it, otherwise, we'll get to it when we can.
