### ISSUE TITLE
Tall pagination section

### ISSUE THREAD

**Issue by byumark** [tannerlinsley/react-table#227]
For some reason the pagination section at the bottom of the table is really tall. I'm probably doing something wrong. 

This element has a style height of 100% but I can't figure out what's causing it to be so tall 

`<button type="button" disabled="" class="-btn" data-reactid="228">Previous</button>`

When I use it as a component in StoryBook it looks fine. Is some other css I have messing with it?

![react-table](https://cloud.githubusercontent.com/assets/5302809/25411068/ba59157e-29d7-11e7-8f9a-76461d911a89.png)

**Comment by tannerlinsley** [comment]
You are likely putting a height on the table element which is forcing it to stretch since its built with flex box. Remove any height related styles from the table and it should function properly.

**Comment by helsont** [comment]
I'm experiencing the same issue and I'm not tampering with any of the React Table css 
<img width="889" alt="screen shot 2017-05-11 at 1 21 39 pm" src="https://cloud.githubusercontent.com/assets/1709344/25970269/d7e5ea78-364c-11e7-9a1b-032d3821be53.png">

**Comment by tannerlinsley** [comment]
Is container-fluid a flex element? If this is still happening for whatever reason, you can put a `flex-grow: 10000` or some other very high number on the `rt-table` element.

**Comment by helsont** [comment]
Here's `container-fluid`. Nothing too crazy going on and no flex either.
<img width="900" alt="screen shot 2017-05-11 at 2 38 27 pm" src="https://cloud.githubusercontent.com/assets/1709344/25973094/8ae5807a-3657-11e7-9a6a-049eb16bda0a.png">

I tried your suggestion and it didn't work - nothing changed. Also, I tried making `container-fluid` a flex element with `flex-direction: column` and it didn't help either. 

What should I look out for in my CSS?

**Comment by helsont** [comment]
I found the "issue". 
<img width="347" alt="screen shot 2017-05-11 at 2 42 36 pm" src="https://cloud.githubusercontent.com/assets/1709344/25973240/1770a38a-3658-11e7-84c8-19cebcda43e6.png">

I removed the `height:100%` from the pagination button class and it worked perfectly. Is it something I should override in my CSS?

**Comment by byumark** [comment]
@helsont that did it for me as well.

**Comment by tannerlinsley** [comment]
Does that change affect any of the examples? If not, please submit a PR :)

**Comment by tannerlinsley** [comment]
Fixed now.

**Comment by roieki** [comment]
Still seeing this.

**Comment by stfnlzvn** [comment]
I "fixed" it by adding this CSS:

.ReactTable .-pagination .-center {
  flex-wrap: unset;
}

**Comment by alexkindel** [comment]
Still had this issue. The auto button height fix from @helsont worked.

**Comment by nathan-gilbert** [comment]
Thank you @alexkindel, I ran into this issue tonight and your solution worked best for me.

**Comment by SrikanthRayaprolu** [comment]
I found the issue not am not able to override the value to default how can I do this to override it to this .ReactTable .-pagination .-btn {
    height: auto;
}
