### ISSUE TITLE
Sorting in my data set doesn`t work

### ISSUE THREAD

**Issue by styfi** [tannerlinsley/react-table#2273]
**Describe the bug (required)**
I have a table with sorting turned on, sorting on string column doesn`t work with my data.

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/lucid-oskar-9l2s0?fontsize=14&hidenavigation=1&theme=dark

**Steps To Reproduce (required)**

1. Click on header to sort
2. [A33K450] is between [A5...] and [A6...], not between [A1...] and [A3G...]

**Expected behavior (Recommended)**
After sort, [A33K450] is between [A1...] and [A3G...]

**Screenshots**
![image](https://user-images.githubusercontent.com/13940947/81170186-86f28e00-8f9a-11ea-87ce-7eee0a51d323.png)

**Desktop (please complete the following information):**
OS - chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xehpuk** [comment]
Add `sortType: "basic"` to your column object. `alphanumeric` is the default.

- [`useSortBy`](https://github.com/tannerlinsley/react-table/blob/d2acfc423593389f8f7b974c6f544ecf683f0724/docs/api/useSortBy.md)
- [Example](https://github.com/tannerlinsley/react-table/tree/d2acfc423593389f8f7b974c6f544ecf683f0724/examples/sorting)
