### ISSUE TITLE
Column width cannot change from props if previously changed manually.

### ISSUE THREAD

**Issue by ofembe** [tannerlinsley/react-table#2285]
Thanks for the awesome library! I experienced this while trying to andjust column widths manually and programmatically.

**Describe the bug (required)**
Column width cannot change from props if previously changed manually. 

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/react-table-simple-table-ple00?file=/index.js

**Steps To Reproduce (required)**
Steps to reproduce the behavior

1. Click on"Toggle columns"
2. Adjust column sizes manually
3. Click on "Toggle columns again"

**Expected behavior (Recommended)**
Column width should always change when you click on toggle columns.

**Additional context**
Column widths don't change after you adjust manually and click "Toggle columns" again.

**Comment by tannerlinsley** [comment]
v6 has been deprecated for a while now. Feel free to fork and fix if you want, but I suggest you upgrade to the latest version of the library.
