### ISSUE TITLE
Adding `useFilters` breaks manualPagination

### ISSUE THREAD

**Issue by garrettmaring** [tannerlinsley/react-table#2286]
**Describe the bug (required)**

When using controlled pagination (`manualPagination: true`) in conjunction with filters, pagination does not behave as expected.

**Provide an example via Codesandbox! (required)**

This is the standard controlled pagination setup from the documentation with `useFilters` added on line 77.

https://codesandbox.io/s/throbbing-cdn-9epvw

**Steps To Reproduce (required)**

1. Click the "next page" button

**Expected behavior (Recommended)**

The table should navigate to the next page. Instead, you'll see it jump back to the first page.

**Additional context**

This is very possibly a configuration error. If so, how does one configure the interplay between filters (and possibly sorting) and manual pagination.

**Comment by garrettmaring** [comment]
Interestingly, setting `autoResetPage: false` helps to prevent the issue.

According to the [documentation](https://react-table.js.org/api/usePagination), that shouldn't be necessary.

**Comment by tannerlinsley** [comment]
Feel free to PR an update to the docs if you find time.
