### ISSUE TITLE
linking text to href (eg. website or address on maps)

### ISSUE THREAD

**Issue by thisKeeWord** [tannerlinsley/react-table#229]
It's not an issue but a question. 

If one of my column's is displaying a website or an address as text, is there a way to have that text as an href?

**Comment by tannerlinsley** [comment]
Wouldn't an ahref work just fine?

**Comment by thisKeeWord** [comment]
I could just pass that in right?  





On Tue, Apr 25, 2017 8:02 PM, Tanner Linsley notifications@github.com  wrote:
Wouldn't an ahref work just fine?

**Comment by thisKeeWord** [comment]
is there an option to include an ahref in 
`{
   header: 'Address',
   accessor: 'address'
}`

**Comment by thisKeeWord** [comment]
my goodness. I have to say that I love this module :)

💯 👍 :1st_place_medal: 
keep up the good work!

p.s: I found that the readme has `render: props => <a href={props.value}>{props.value}</span>` which is exactly what I need :D
