### ISSUE TITLE
Cannot overwrite default text filter type

### ISSUE THREAD

**Issue by CodingGreen** [tannerlinsley/react-table#2293]
**Describe the bug (required)**
Although it is possible to overwrite the text filter type that does not overwrite the default as well so the default text filter type cannot be overwritten.

**Provide an example via Codesandbox! (required)**
We can see in the [filtering example Codesandbox](https://codesandbox.io/embed/github/tannerlinsley/react-table/tree/master/examples/filtering) that the text filter type is overwritten (Lines 220-231) and we also see that the first name column is configured without a filter (Lines 343-346). However the custom text filter is not used.

**Steps To Reproduce (required)**
Steps to reproduce the behaviour:

1. Go to https://codesandbox.io/embed/github/tannerlinsley/react-table/tree/master/examples/filtering
2. Enter text into the First Name search box
3. Any results that include your text appear (Default behaviour rather than custom)

**Expected behaviour (Recommended)**
In my opinion the custom text filter should be used and, in this case, only results that start with search string should be displayed.

**Desktop (please complete the following information):**

- OS: MacOS 10.15.4
- Browser: Chrome
- Version: 81.0.4044.129

**Additional context**
The cause seems to be that in the utils file if no filter is specified (and therefore the `filter` variable is presumably `undefined` or `null`) the `getFilterMethod` function always returns the built in text function. See: https://github.com/tannerlinsley/react-table/blob/42b41d1260fab3c6635b071ca984dce253bf23ab/src/utils.js#L264-L271

**Comment by tannerlinsley** [comment]
Simply set the default `filter` property on `defaultColumn` to `filter: 'text'`. This is how things will work in the next version anyway.

**Comment by johnslemmer** [comment]
Just ran in to this too.  And when you say "this is how things will work in the next version anyway" does that mean you are going to change getFilterMethod to return user defined `text? Or just not have a default filter at all make users have to define a default column?

Just curious as we have implemented your work around, but wanted to know if any future changes would break anything.  Thanks!
