### ISSUE TITLE
Documentation site not available

### ISSUE THREAD

**Issue by LouOtway** [tannerlinsley/react-table#2298]
**Describe the bug (required)**
The documentation site isn't available

**Provide an example via Codesandbox! (required)**
Navigate to https://react-table.js.org/

**Steps To Reproduce (required)**

1. Open https://react-table.js.org/ with a web browser

**Expected behavior (Recommended)**
Documentation site should open

**Screenshots**
![image](https://user-images.githubusercontent.com/11749950/81667544-4fbd2a80-943b-11ea-8b10-3c8c94ec4651.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome, Edge

**Additional context**

**Comment by kuzdogan** [comment]
For those who need to react documentation until this gets fixed, the files are already in the repo: https://github.com/tannerlinsley/react-table/tree/master/docs 

Should be well human-readable as they are markdown formatted.

**Comment by tannerlinsley** [comment]
The github docs have returned temporarily while we figure out what to do with the docs.
