### ISSUE TITLE
Please implement ondblclick that let's us know which cell was dblclicked

### ISSUE THREAD

**Issue by rajaraodv** [tannerlinsley/react-table#230]
I know there is a onClick callback but I want ondblclick because onclick is for something else in my use-case.

**Comment by mikedevita** [comment]
since youre defining your columns, you can generate a custom render and handle the onDoubleClick yourself...


```jsx
const columns = [
{
  header: 'clickme',
  id: 'clickme',
  render: ({ row }) =>(<span onDoubleClick={(e) => this.handleDoubleClick(e, row)}>
    {row.name}
  </span>)
}
];

```

**Comment by rajaraodv** [comment]
I'll try out your solution! Thanks!
