### ISSUE TITLE
useResizeColumns - IE11 issue

### ISSUE THREAD

**Issue by kmaimn** [tannerlinsley/react-table#2302]
**Describe the bug (required)**
Initially opened as a discussion item, but further digging my end leads me to believe that this is an actual issue. `useResizeColumn`, specifically in IE does not work. It looks like mouse event listeners aren't being removed when a column is resized, causing the table to rerender based on mouse position. 

**Provide an example via Codesandbox! (required)**
Unable to replicate in codesandbox since this is an IE11 issue, but I implemented the `useResizeColumns` [example ](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/column-resizing) provided in the docs.

![react-table-v7-IE](https://user-images.githubusercontent.com/18150950/81715539-f60a2f80-943d-11ea-8dd8-33f871562956.gif)

**Steps To Reproduce (required)**
1. Resize any column in IE11
2. See column snap to max width (if you have the console open, and are logging state from `useTable`, you should see the width of the resized column size as you mouse around)

**Expected behavior (recommended)**
Columns resize as they do in other browsers

**Desktop**
- OS: Windows 10
- Browser: Internet Explorer 
- Version: 11.778.18362.0

**Comment by BrianMitchL** [comment]
IE doesn't support the `{ passive: false }` option on an event listener, which seems to break the ability to remove that listener once it's been created. We can can detect support for the feature (https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Improving_scrolling_performance_with_passive_listeners) and only use it if so. I'll work on submitting a PR to fix this tomorrow.
