### ISSUE TITLE
Nested SubRows Not Sorting

### ISSUE THREAD

**Issue by Chase-Dickerson** [tannerlinsley/react-table#2303]
**Describe the bug**
SubRows do not sort beyond a parent subRow of length 1.

**Provide an example via Codesandbox!**
https://codesandbox.io/s/nice-surf-hzprc

**Steps To Reproduce (required)**

1. Go to the sandbox
2. Click on any of the info columns to apply sorting
3. Notice that no sorting occurs

**Expected behavior**
SubRows should sort at any depth.

**Desktop / Smartphone:**

- OS: Any
- Browser: Any
- Version: Any

**Additional context**
The bug is caused by an early termination of subRow sorting, which occurs on this line:
https://github.com/tannerlinsley/react-table/blob/master/src/plugin-hooks/useSortBy.js#L324

**Proposed Solution**
Adjust the check for skipping subRow sorting so that it only skips subRows if the length of subRows is zero (i.e. change: `!row.SubRows || row.subRows.length <= 1` to `!row.SubRows || row.subRows.length === 0`).

**Comment by dbertella** [comment]
oh wow thanks for this I was going to open the same issue today

**Comment by Chase-Dickerson** [comment]
This issue is still not resolved on v7.3.4 or higher. See the provided sandbox, which references latest react-table (v7.5.1).

**Comment by aaryn101** [comment]
@Chase-Dickerson I just tried it out on the sandbox, and it seems to be working. What am I missing?

![Screen Shot 2020-09-22 at 2 02 54 PM](https://user-images.githubusercontent.com/4121710/93931724-66726880-fcdc-11ea-9a57-d858a185c741.png)

**Comment by Chase-Dickerson** [comment]
Sorry, I was referring to the sandbox I linked in the original issue above (https://codesandbox.io/s/nice-surf-hzprc) not the default sandbox. As illustrated below, child rows do not sort when there is a single sub-row. Sorting is terminating too early because it sees a sub-row of length 1, which by itself constitutes as "sorted," ignoring other sub-rows further down the chain.
![nested_sort](https://user-images.githubusercontent.com/31904663/94043872-ae4fc900-fd8a-11ea-9b30-ba20a289b9e7.JPG)

**Comment by aaryn101** [comment]
@Chase-Dickerson Ahh, I see. I'll try to find some time this week to look into a fix.

**Comment by leyinetwork** [comment]
@aaryn101 Look at #2633 
@tannerlinsley  Can you merge this PR
