### ISSUE TITLE
Filtering example is broken. useGlobalFilter is not exported fom react-table

### ISSUE THREAD

**Issue by MidnightJava** [tannerlinsley/react-table#2307]
**Describe the bug (required)**
The filtering example does not compile when you run the source code. It complains that useGlobalFilter is not exported from react-table. 

**Provide an example via Codesandbox! (required)**
There is an Existing filtering example ( https://codesandbox.io/embed/github/tannerlinsley/react-table/tree/master/examples/filtering), but it works. The problem only occurs when you run the example from source code.

**Steps To Reproduce (required)**
1. git clone git@github.com:tannerlinsley/react-table.git
2. cd react-table/examples/filtering
3. yarn
4. yarn start
5. Observe compile error on console and in browser

**Expected behavior (Recommended)**
The filter example should compile and run from source code just as it does in the code sandbox
**Screenshots**
![image](https://user-images.githubusercontent.com/904783/81757027-760ab680-948b-11ea-8bae-c14a6f9a7bc2.png)

**Desktop (please complete the following information):**
- OS: CentOS 7.8
- Browser: Firefox
- Version: 68.7.0esr

**Comment by MidnightJava** [comment]
The problem seems to be that it was installing react-table version 7.0.0-rc.14 in node_modules. I changed the react-table versions from "latest" to "7.0.5" in examples/filtering/package.json, and after running yarn the correct version of react-table was installed in node_modules, and the code compiled successfully.

I changed package.json back to "latest", and it installs version 7.0.5. Even after deleting node_modules and re-running yarn. But if I delete the git repo and re-clone it, and run yarn, it loads the rc.14 version of react-table initially again.

**Comment by MarkJiYuan** [comment]
Thanks bro, I meet the same problem

**Comment by tannerlinsley** [comment]
The dependency is now up to date.

**Comment by hkorsvoll** [comment]
The problem here is that the lock file is still pointing to version 7.0.0-rc.14. So if you only do `yarn` and `yarn start` in the project, you end up with not the latest version.
You should run `yarn upgrade` to get the latest version installed.
