### ISSUE TITLE
Document tree-shaking, or provide precise imports

### ISSUE THREAD

**Issue by Floriferous** [tannerlinsley/react-table#2311]
The docs say that this library weighs anywhere between 5 and 15kb, depending on if you use tree-shaking. It doesn't specify how to get tree-shaking to work, so I guess it assumes you have a tool that does this automatically.

Is there a way to import only the hooks that you need without automatic tree-shaking?

Like this, no surprises, configuration on guess-work:

```js
import useTable from 'react-table/useTable';
import useSortBy from 'react-table/useSortBy';
```

Maybe there already are import paths like these, but it doesn't look like it.

**Comment by ingro** [comment]
I think that this could be very useful.

I'm using rollup as bundler and it seems that the whole library is imported even if only few hooks are used.

**Comment by dpacmittal** [comment]
This is working well for me in a preact typescript project:

```typescript
import { useTable } from "react-table/src/hooks/useTable";
import { useSortBy } from "react-table/src/plugin-hooks/useSortBy";
```

**Comment by Floriferous** [comment]
@dpacmittal Not sure that's what you want in production though, I don't think that code is minified (maybe I'm wrong, or maybe your setup minifies it)?

**Comment by tannerlinsley** [comment]
Separate imports will be the default and preferred way in v8. For now, it is not v7's responsibility to implement tree shaking in your applicaitons, nor would it be possible to cover all of the scenarios and edge case around. Stay tuned for v8!
