### ISSUE TITLE
initialState.sortBy doesn't respect the sortInverted column property.

### ISSUE THREAD

**Issue by tmporterSGSI** [tannerlinsley/react-table#2313]
**Describe the bug (required)**
`initialState.sortBy` doesn't respect the `sortInverted` column property.

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/tannerlinsleyreact-table-sortinverted-not-respected-usx07

**Steps To Reproduce (required)**
1. Set the `sortInverted` property to `true` on the column definition for the column that will be initially sorted.
2. Set `initialState.sortBy` to the column configured in the previous step.
3. Load the table. Observe the specified column is sorted on load, but not inverted.
4. Click the column header to cycle through the sort directions. Observe that the column sort is inverted on subsequent clicks.

**Expected behavior (Recommended)**
The `sortInverted` property should be respected when the table loads.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Version: 76.0.1

**Comment by tmporterSGSI** [comment]
Strangely, if I explicitly set `desc: false` on the `initialState.sortBy` object the initial sort works as expected as seen in the sandbox below:

https://codesandbox.io/s/tannerlinsleyreact-table-sortinverted-not-respected-workaround-1mlx3?file=/src/App.js

I would expect setting `desc: false` to be have the same as excluding the option all together. In fact, the docs state that this property is optional, but doesn't specify what the default value is.

> An optional desc key may be set to true or false to indicated ascending or descending sorting for that column.

**Comment by tannerlinsley** [comment]
`sortInverted` only applies to interactions with the sorting toggle and associated API. If you are manipulating sorting state directly, you must use the `desc: true/false` to achieve your desired result. I've updated the docs you mentioned to be more clear on this.

**Comment by tannerlinsley** [comment]
c591ec102045f52317834040426dbc4ff30d2f57
