### ISSUE TITLE
Notifying when row is selected or sort conditions change

### ISSUE THREAD

**Issue by nanandn** [tannerlinsley/react-table#2316]
I am using react-table@7.0.4 to build a table component. I am using useRowSelect and useSortBy plugins.  Works great. But how do I notify code that is using the table when row selection or sort conditions change? 

For example, I see that useRowSelect adds a onChange prop to the check box element that I use and handles the change event. But how do I propagate that event to the app code that is using the table. I want the users of table to set "onRowSelectionChanged" prop and I want to call that function when the selection changes. 

I don't see anything like this in the examples. Is there a way to hook into this event and fire a onRowSelectionChanged or onSortChange callback?

Thanks

**Comment by matijagalina** [comment]
@nanandn 
You can use something like this inside your Table instance:

` useEffect(() => {
    onRowSelect(selectedFlatRows);
  }, [selectedFlatRows.length]);`

where `onRowSelect` is some prop function you pass to your table instance:

`
// table definition:

const Table = ({
  columns,
  data,
  onRowSelect,
}) => {
  const {
    getTableProps,
    getTableBodyProps,
    headerGroups,
    prepareRow,
    selectedFlatRows,
...
  } = useTable(
    {
      columns,
      data,
    },
    useSortBy,
  );

  useEffect(() => {
    onRowSelect(selectedFlatRows);
  }, [selectedFlatRows.length]);

return ( ..table UI here );

// pass onRowSelect to your table component:

 <ProductListTable
     columns={columns}
     data={data}
     onRowSelect={handleRowSelect}
 />
`

**Comment by tannerlinsley** [comment]
Please use discussions or discord for questions.

**Comment by rashad2985** [comment]
@nanandn sorry, but this does not solve the problem.

1. The event is triggered on initilizing the element, without selection or user interaction. Such a behaviour is not wished. onRowSelect can be a heavy function call and can make user wait for handling, without interacting with the element.
2. React.useEffect depends on selectedFlatRows, but dependency array contains part of it. It is a hack, but not a good solution.

I think, we need a callback mechanism here. A possibility to provide a callback function to useTable like columns and data. And react-table should call this method after row selection completed, like onRowSelectionCompleted with signature (selectedFlatRows => void). It would be nice to extend with onRowSelectionStart (callback before internal row selection starts).
Besides, adding such a callback support does not cost much effort. One can do it in several minutes and no need to wait several monthes for such thing, just calling the provided callback directly after changing selected rows.
