### ISSUE TITLE
immutable.js support

### ISSUE THREAD

**Issue by a-x-** [tannerlinsley/react-table#232]
Do you want support immutable.js List as data (may be with Record rows)?

Now I have to convert long immutable redux state List to JS array.

In the case of using Immutable.List as data, I got:

<img width="767" alt="screen shot 2017-04-26 at 23 42 26" src="https://cloud.githubusercontent.com/assets/6201068/25455980/3e883976-2ada-11e7-892f-d7080fc34cf1.png">

**Comment by tannerlinsley** [comment]
There are currently no plans to support immutable directly. This may change in the future

**Comment by williamboman** [comment]
Support for Immutable.js would be awesome! @tannerlinsley Do you reckon it would be difficult for an external developer (maybe me) to implement this in `react-table`? I have no previous history with this component before today.

**Comment by duro** [comment]
@tannerlinsley I too would love to see this work with immutable. With some cursory review this seems very doable, especially if those using immutable are expected to always use function based accessors. The main issue is that immutable objects to not expose a `length` property, instead they use `size`. I may take a crack at seeing if I can introduce basic support and send over a PR.

**Comment by gminor7** [comment]
+1 this would be great.

**Comment by midnightcodr** [comment]
+1 would love to see immutable.js supported as well.

**Comment by RSLi** [comment]
+1

**Comment by tommyalvarez** [comment]
+1

@a-x- you are converting your list to array using `toJS()` to make things work right?

**Comment by dnbr2002** [comment]
+1 for Immutable

**Comment by anthonychung14** [comment]
how would it be to fork/implement? :0 not sure how React-Table determines whether or not a ref has changed, but it would be a great addition

**Comment by kushalmahajan** [comment]
I'm from future. I've been using your library and after introducing immutable.js in full swing I came to know now that it doesn't support it. Just saddens me to the core. 

Two paths, either someone or I study and raise a PR. Second, I invest time to build my own table from scratch ( more time). 

Will be of great upgrade if you can do that. Thanks!

**Comment by a-x-** [comment]
> @tommyalvarez, you are converting your list to array using toJS() to make things work right?

yes, sure

Also, we adding immutable support to some our custom components. It does not even require any immutable-js dependencies. Basically, we:
- check the `get(i)` method and use it instead of `[i]`
- check the `size` property and use it instead of `length`

**Comment by theoarena** [comment]
Hi! I was experiencing the same problem ( except for the 'nan' at the bottom )

**React-table v 6.9.2**

My solution:

```
let noData = pagination.results_count > 0 ? () => <span></span> : (txt) => <span>{txt.children}</span>

//txt.children shows 'no data' text defined in noDataText props

<ReactTable
manual={true}
data={data} // <----- immutable object!
NoDataComponent={noData}
(...)
/>
```

This will give you control to show "no data" when you want. You'll have to style it manually, but that's not a big deal.

Hope it helps someone!

**Comment by jasekiw** [comment]
@tannerlinsley Would you be open to prs to add immutable.js support?
