### ISSUE TITLE
Error while using ReactTable in a functional component

### ISSUE THREAD

**Issue by itisguptak** [tannerlinsley/react-table#2323]
Hi,

I'm getting this error while using ReactTable. 
react-dom.development.js:23965 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

I looked at multiple posts on web for similar error, and they point to an issue with how a component is defined and imported. But I can confirm that it's defined and imported correctly. Any help with this will be much appreciated. Thanks. 

Functional component (PgTable.js)
import React from 'react';
import ReactTable from 'react-table';

//useTable
//import "react-table/react-table.css";

function PgTable(props) {

    const data = [{
    name: 'Roy Agasthyan',
    age: 26
  },{
    name: 'Sam Thomason',
    age: 22
  },{
    name: 'Michael Jackson',
    age: 36
  },{
    name: 'Samuel Roy',
    age: 56
  },{
    name: 'Rima Soy',
    age: 28
  },{
    name: 'Suzi Eliamma',
    age: 28
  }]

  const columns = [{
    Header: 'Name',
    accessor: 'name'
  },{
    Header: 'Age',
    accessor: 'age'
  }]

  return (
          <div>
              <ReactTable 
              data={data}
              columns={columns}
              defaultPageSize = {3}
              pageSizeOptions = {[3, 6]}
              />
          </div>      
    );
}

export default PgTable;

It's imported in PgTabs.js as:
import PgTable from '../components/PgTable';
It's consumed in PgTabs.js as below:

<TabPanel >
        {metricsR == null ? <div>Loading . . .</div> : <div><PgTable metrics={metricsInfo[props.env]}/></div>}
    </TabPanel>

**Comment by itisguptak** [comment]
<TabPanel >
        {metricsR == null ? <div>Loading . . .</div> : <div><PgTable metrics={metricsInfo[props.env]}/></div>}
    </TabPanel>

**Comment by tannerlinsley** [comment]
`ReactTable` is not exported in v7 any more. v7 is a collection of hooks like `useTable` that allow you build your own tables.

**Comment by Neirda24** [comment]
@tannerlinsley : Hi. I'm new to React but as far as I know it means I cannot use react-table within a class component right ? Or am I missing something ?

**Comment by Neirda24** [comment]
Just found https://github.com/tannerlinsley/react-table/issues/1807 and I think it may be missing a documentation or a link to a documentation if already exists somewhere.
