### ISSUE TITLE
Table width not set in Material-UI Enhanced Table - react-table

### ISSUE THREAD

**Issue by RajuTicvic** [tannerlinsley/react-table#2337]
Hi,
I used react-table with Material-UI Enhanced Table
I tried to set width but I could not set 
this is what I tried below
{
			Header: header.name,
			accessor: String(i),
			width:400, // Not working
                         //width:"400" // Not working
                        //width: 40% // Not working
                        //width: "400px" // Not working
}
None of these work
Please help me to fix it

**Comment by gargroh** [comment]
Can you share url where this can be reproducible..

**Comment by RajuTicvic** [comment]
@gargroh 
First of all, thank you for your swift response
Here my URL 
https://codesandbox.io/s/loving-hopper-xfik9?file=/src/App.js

**Comment by gargroh** [comment]
You need to use any of the layout plugin i.e. useAbsoluteLayou or, useBlockLayout

**Comment by RajuTicvic** [comment]
Useful answer.
But now stickyHeader not working vertically after use useBlockLayout.
https://codesandbox.io/s/loving-hopper-xfik9?file=/src/App.js

**Comment by RajuTicvic** [comment]
Hi,
Is there anyone to help?

**Comment by tannerlinsley** [comment]
This is an implementation question, so please use discussions or discord.
