### ISSUE TITLE
Infinite Scroll version. Network request iteration

### ISSUE THREAD

**Issue by stephyswe** [tannerlinsley/react-table#2348]
**Describe the bug (required)**
When scrolling in Infinite Scroll version of React-table v7* the client makes numberous network requests. In the long run iit could be up to ten thousands of request.

* = https://codesandbox.io/s/react-table-v7-sandbox-veigk?file=/src/examples/Basic.js

**Provide an example via Codesandbox! (required)**
Use forked infinite scroll [react-table codesandbox](https://codesandbox.io/s/react-table-v7-sandbox-veigk?file=/src/examples/Basic.js) to reproduce the issue.

**Steps To Reproduce (required)**

1. Go to Codesandbox
2. Click "Toggle Infinite Scroll" to enable it
3. in Chrome: Right-click choose "Inspect" to open devTools
4. In DevTools - Choose Network tab. 
5. Scroll down in table too see amount of network request increasing per scroll

**Troubleshooting**
I'm debugging this issue myself and found an interesting thing that might solve it. At another Codesanbox using infinite scroll (same react-table version) all images are fetched at start and no increase of network request occur. The other codesandbox have useMemo and other ways. I'm gonna look into this and solve it today :)

Issue happens for me ( Toggle infinite scroll / pagination ) - with network request issue
https://codesandbox.io/s/react-table-v7-sandbox-veigk?file=/src/examples/Basic.js

Issue doesnt happen for me ( only infinite scroll )  - without network request issue
https://codesandbox.io/s/icy-bird-ijiqf?file=/src/App.js

**Expected behavior (Recommended)**
It would be nice with optional ways to handle images in infinite scroll. Maybe an feature to fetch all images at once so no more network request are required. Or only fetch images isn't already requested. 

**Screenshots**
![ZGv6R3 (1)](https://user-images.githubusercontent.com/20955623/82451402-3dcc2f00-9aae-11ea-8e80-f8a28f74ff12.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gargroh** [comment]
You need to turn off `Disable Cache` in CDT

**Comment by stephyswe** [comment]
What is CDT?

**Comment by gargroh** [comment]
CDT - chrome dev tools

**Comment by stephyswe** [comment]
Did as mentioned inside the Codesandbox example provided here and enabled "disable cache". Sadly it still makes same sorts all requests . Any other reason causing it?

**Comment by gargroh** [comment]
You need to uncheck highlighted checkbox

![image](https://user-images.githubusercontent.com/42495927/82575007-87e40c00-9ba5-11ea-99fc-3e3be6cf772a.png)

**Comment by stephyswe** [comment]
I unchecked highlighted checkbox "Disable cache" and issue still happens. image shows result from scrolling up and down afew times in a list of 100 rows - networks requests are 762. Scrolling more increases that number. 
![1Drve6](https://user-images.githubusercontent.com/20955623/82639977-0b374900-9c0a-11ea-8cbe-21d75b741fec.png)

**Comment by stephyswe** [comment]
OK. My Solution was to just skip this code. And use Another way to render Infinite Scroll and Pagination. I might close this issue soon. Also I think the code used here is WAY
