### ISSUE TITLE
Cannot overwrite the default sorting method

### ISSUE THREAD

**Issue by ShrutikaSingh** [tannerlinsley/react-table#2349]
**Describe the bug (required)**
cannot overwrite the default sorting method
As of now, the useSortBy method is using sorting columns like normal-ascending-descending.
But I want to sort by just descending.

**Provide an example via Codesandbox! (required)**
Use a new [react-table codesandbox](https://codesandbox.io/s/m5lxzzpz69) to reproduce the issue.
https://codesandbox.io/s/jolly-dream-6ejz2?file=/src/App.js

**Expected behavior (Recommended)**
When I click on column header I want to sort by just descending order and then back to normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/42492660/82471760-c665c200-9ae4-11ea-949e-25910823ffbe.png)

**Desktop (please complete the following information):**
Mac os

**Comment by tannerlinsley** [comment]
This is a feature request, so please use the discussions tab to track it.

**Comment by ErikAGriffin** [comment]
@tannerlinsley just to be clear, there is a feature request to have react-table be able to load being sorted by a specific column by default? This isn't yet implemented?

Also could you link to the relevant discussion?  Thank you!

**Comment by jmilldotdev** [comment]
Can I bump this? Is it possible so the sort order goes: unsorted -> desc -> asc?
