### ISSUE TITLE
Add Array of Objects to Cell

### ISSUE THREAD

**Issue by shezankazi** [tannerlinsley/react-table#235]
Is it possible to add an array of objects to a cell?

```
Currently I have
columns = [
           {
               header: 'Tags',
               accessor: 'tag'
           }
]
```
where tag is an array of objects:

```
[
    {id: 1, tag: "JS"},
    {id: 2, tag: "React"}
]
```

I can display the first item from tags with:
`accessor: 'tag[0].tag'`

But how do I list all of them separated with commas?

**Comment by aaronschwartz** [comment]
You `accessor` will stay as `accessor: 'tag'`.
You will use the `render` method of the column to take your tag array and display it how you want.

http://codepen.io/anon/pen/MmJzrz?editors=0010

**Comment by shezankazi** [comment]
Thank you very much Aaron! I had not seen the render function. Sorry for that.

**Comment by shezankazi** [comment]
What I did not notice at first, is that this does not work with my custom filter:
`filterMethod: (filter, row) => (row[filter.id].toLowerCase().includes(filter.value.toLowerCase()))
`
Is there something I am missing?

**Comment by aaronschwartz** [comment]
You need to give some more information on what isn't working.
If you're trying to add that custom filter to a column that has an array as a value, `row[filter.id]` is going to be an array. You can't call `toLowerCase()` on an array.

**Comment by shezankazi** [comment]
Hi Aaron, thanks a lot. I was not aware, that is was an array. Since I am using `.join(',')` on my render function I thought I was creating a string. Also, my console log says it is a string.

**Comment by aaronschwartz** [comment]
`row` always contains the raw data value that you pass in since `render` could theoretically render whatever it wants including JSX tags.

Your filter method isn't returning anything. You need to return `true` if you find a match.

```
filterMethod: (filter, row) => {
    for (var i=0; i<row.business_sector.length; 
        if(row.business_sector[i].business_sector.toLowerCase().includes(filter.value)) {
          return true;
        }
    }
    return false;
}
```

**Comment by shezankazi** [comment]
Thanks again Aaron! I had tried the boolean but set it outside the loop. Now it works :-)

**Comment by Bagpuss-org** [comment]
> You will use the `render` method of the column to take your tag array and display it how you want.

It should be mentioned that the render method has now been deprecated and has been replaced with the Cell method. Maybe this will save someone else 5 minutes :)

**Comment by nemo0** [comment]
Here's a sample if anyone needs it. It's mainly for a simple array. But you get the idea.
```jsx
    columnHelper.accessor("roles", {
      cell: (info) => {
        const roles = info.getValue();

        return (
          <div>
            {roles.map((role) => (
              <div className="px-2 py-1 bg-green-500 rounded-full text-white text-center my-2 text-sm">
                {role.toUpperCase()}
              </div>
            ))}
          </div>
        );
      },
      id: "roles",
      header: "Roles",
    }),
    ```
