### ISSUE TITLE
Plugins do not guard against invalid values in initialState

### ISSUE THREAD

**Issue by nderscore** [tannerlinsley/react-table#2354]
Plugins do not guard against invalid values passed through `initialState` in the same manner they do from method calls. 

Because of interactions between different plugins, it might not be possible for the caller of `useTable` to know whether a given value is valid at the time `initialState` is defined either. For example, if there is an initial filter state, there's no easy way to validate a page index ahead of time.

**Codesandbox Example**

https://codesandbox.io/s/bold-wildflower-h0blz (kitchen sink example with initialState)

**Steps To Reproduce**

1. Pass invalid value(s) in `initialState`

**Expected behavior**

When consuming from `initialState`, the same validity checks and cleanup should occur as when state updates are triggered by method calls.

**Examples of existing guarded behavior**
* **usePagination**'s `gotoPage` will guard against a negative or out of bounds page from being set.
* **useFilter**'s `setFilter` and `setAllFilters` will automatically remove empty values based on `filter.autoRemove`

Not every plugin's method calls have such guards in place either (**useRowSelect** and **useSortBy** methods don't gracefully handle invalid column ids), but for ones that do, I think it might make sense for the same behavior to exist at the time of initialization or after a reset.

**Comment by tannerlinsley** [comment]
So if it’s invalid you would want a layoutEffect to happen and correct it with a new call to setState?

**Comment by nderscore** [comment]
Since the existing guards happen at the reducer-level already, I was thinking it should go in the "___Reset" action of each plugin (the one triggered on mount by a `useMountedLayoutEffect` in the `useInstance` hook or by a reset method call), as that's where `initialState` gets consumed.

Using `useFilters` as an example, I was thinking it would look like something like this:
```javascript
  if (action.type === actions.resetFilters) {
    return {
      ...state,
      filters: (instance.initialState.filters || []).filter(filter => {
        const column = allColumns.find(d => d.id === filter.id)
        const filterMethod = getFilterMethod(
          column.filter,
          userFilterTypes || {},
          filterTypes
        )

        if (
          shouldAutoRemoveFilter(filterMethod.autoRemove, filter.value, column)
        ) {
          return false
        }
        return true
      }),
    }
  }
```

But maybe without duplicating

**Comment by nderscore** [comment]
Thinking about it some more... Maybe a more comprehensive solution would be to run a validation check after every state update, given that invalid state values could come from other places besides `initialState`, such as `useControlledState` or even another plugin's `stateReducers` hook.

**Comment by tannerlinsley** [comment]
This will likely be more "possible" in v8 given the internal state architecture changes. So let's wait until we get closer and discuss it again then.
