### ISSUE TITLE
Resizing with useResizeColumns can trigger sorting when use with useSortBy

### ISSUE THREAD

**Issue by krashdifferent** [tannerlinsley/react-table#2359]
**Describe the bug (required)**
Mouse events on resize objects propagate upwards to the containing elements, meaning they can trigger sort events also attached to header cells.

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/amazing-dream-x4iyw

**Steps To Reproduce (required)**

1. Resize "First Name" column.
2. note the column sorting changes

**Expected behavior (Recommended)**
mouseDown events captured in the resize object props should call stopPropagation so the sorting (and other) props can be attached to the resize parent elements without triggered on resize.

**Comment by Mikoz93** [comment]
@krashdifferent The getResizerProps() prop getter only returns onMouseDown and onTouchStart. To fix this issue, an onClick would also have to stop the propagation (I know that that's what you probably meant by saying 'mousDown events', just wanted to clarify).

**Comment by barbara-lea** [comment]
Does anyone know a workaround for this? :)

**Comment by berkin** [comment]
i moved out the resizer out of the cell as a quick fix.  https://codesandbox.io/s/brave-sanne-6o1mg

**Comment by krashdifferent** [comment]
Another simple work around, add an onClick handler to the resizer that calls stopPropagation:

`<div className={classes.resizer} {...column.getResizerProps({onClick(ev){ev.stopPropagation()}})} />`

**Comment by tannerlinsley** [comment]
Or even: Place the sortBy props on the text, not the entire cell.

**Comment by syntacticsolutions** [comment]
I submitted a fix for this here. https://github.com/TanStack/table/pull/4494

**Comment by syntacticsolutions** [comment]
> Another simple work around, add an onClick handler to the resizer that calls stopPropagation:
> 
> `<div className={classes.resizer} {...column.getResizerProps({onClick(ev){ev.stopPropagation()}})} />`

I don't think this will work since the event is coming from the document when the resizer is released so it hits the `th` element before it reaches the resizer.
