### ISSUE TITLE
Save columns widths

### ISSUE THREAD

**Issue by shaleynikov** [tannerlinsley/react-table#236]
I want to be able to save columns widths for later use. In order to do that I need to have some sort of callback which is called after columns widths has been changed. Now I'm unable to find any kind of `onResizeChange` or anything like that. Proposed `onResize` method disables default resize handling leaving me an option to rewrite resizing code.

Is there any way to get columns widths?

**Comment by aaronschwartz** [comment]
I don't see an easy way to do this right now without using onResize and handling the resize logic yourself.

You can join the react-chat slack channel to discuss possible enhancements that would make this easier: https://react-chat-signup.herokuapp.com/
