### ISSUE TITLE
Docs is missing explanation what does omitted `desc` key mean in SortingRule

### ISSUE THREAD

**Issue by simPod** [tannerlinsley/react-table#2363]
**Describe the bug (required)**

Here https://github.com/tannerlinsley/react-table/blob/master/docs/api/useSortBy.md#table-options the member of `initialState.sortBy` array is defined as `{id: string, desc?: bool}`.

`desc` can be omitted as described:

> An optional desc key may be set to true or false to indicated ascending or descending sorting for that column

However, there's a missing description of what does it mean if `desc` key is not set.

**Comment by tannerlinsley** [comment]
The docs are more clear now.
