### ISSUE TITLE
Custom hooks & plugins

### ISSUE THREAD

**Issue by nanandn** [tannerlinsley/react-table#2365]
Where can I find documentation for writing custom plugins and hooks?

**Comment by 07harish** [comment]
I have built custom hooks by reading any of their plugin hooks implementation, in this way:

Take a look at any of the plugin hooks written for example usePagination etc..

React-table exposes all required plugin points (instance.hooks)

To get these plugin points, we pass our useCustomHook to useTable just like how we pass usePagination, useGroupby to useTable

In useCustomHook, select any of the plugin points (or push to an array) you want to add logic

```
function useInstanceFn(instance) {
  console.log(instance)
   // Implement logic
}

export function useCustomHook(hooks) {
    // plugin points (hooks)
    hooks.useInstance.push(useInstanceFn)
}
```

 useCustomHook gets table instance, table **instance** has everything you need to build your own logic.

**Comment by tannerlinsley** [comment]
I'm putting off a plugin guide until v8 where it will be a much better experience and make way more sense.
