### ISSUE TITLE
Setting isVisible: false does not work

### ISSUE THREAD

**Issue by relf** [tannerlinsley/react-table#2367]
**Describe the bug (required)**
When <code>isVisible</code> is initialized with <code>false</code>, the column is still visible.

**Provide an example via Codesandbox! (required)**
Cannot use : code on sandbox is erroneous?! 

**Steps To Reproduce (required)**
Modify Simpe basic example and set <code>isVisible: false</code> in the first column object
<pre>
...
  const columns = React.useMemo(
    () => [
      {
        Header: 'Name',
        columns: [
          {
            Header: 'First Name',
            accessor: 'firstName',
            isVisible: false,   
          },
...
</pre>

**Expected behavior (Recommended)**
Column <code>First Name</code> should not be visible?! Did I miss something?

**Desktop (please complete the following information):**
- OS: Windows
- Browser Firefox
- Version 76

**Additional context**
I've noticed the bug when I upgraded from 7.0.0-rc.10. With my code, it starts to fail with v7.0.0-rc.13.

**Comment by omarkhatibco** [comment]
Codesandbox here 
https://codesandbox.io/s/funny-archimedes-bvpqf?file=/src/App.js

**Comment by Mikoz93** [comment]
The docs don't mention 'isVisible' being a prop that you can pass to a column.

**Comment by relf** [comment]
@Mikoz93, thank you, you confirm the doubt I've just came up with. Indeed when I upgraded from 6 to 7.0.0-rc.10, I misread the documentation which mentions a <code>isVisible</code> [column property](https://github.com/tannerlinsley/react-table/blob/master/docs/api/useTable.md#column-properties), I infer erroneously I could just initialize the columns with and well... It happened to work at that time! I will try initialState, thanks.
