### ISSUE TITLE
Column info in rowInfo object

### ISSUE THREAD

**Issue by skyflyer** [tannerlinsley/react-table#237]
## Problem Description
Currently, custom renderer for cell includes a `rowInfo` object, which provides index, but not the column (field) information when rendering. Would it make sense to include it for dynamic rendering? I'm trying to have certain columns editable... and perhaps there is a better way to achieve this?

## Codepen
http://codepen.io/anon/pen/KmWxBj?editors=0010

Here you can see the custom cell renderer for `age` column. I used a workaround with `getTdProps` to add column info to rowInfo object, so I can use it there (but still need to figure out how to change the underlying data).

## Steps to Reproduce
1. add a custom cell render in a `columns` column definition
2. try to determine which column it is rendering inside the custom render function

## System Information
* 57.0.2987.133 (64-bit)
* **Node Version: Unknown (codepen) **
* **OS Version: Unknown (codepen) **
* **NPM Version: Unknown (codepen) **
* **Yarn Version: Unknown (codepen) **

**Comment by aaronschwartz** [comment]
You could enhance your renderInput function to take in the id like this:

http://codepen.io/anon/pen/XRMxpR?editors=0010

Or I'm sure if you make a PR which passes in the Column ID to the render function that it would be accepted.

**Comment by skyflyer** [comment]
Aaron, thanks for that! Unfortunately, it still requires an "id" to be passed in, but it is a very nice trick with a closure. Also, thanks for taking the time to bind renderInput correctly so that it updates state.

While thinking about PR, I wonder what to do when the accessor is not a string. Do you think it would make sense to pass `columnAccessor` through the `rowInfo` object whatever the value of it might be (`string`, `function`, `undefined`, ...)?

**Comment by aaronschwartz** [comment]
I would be hesitant to pass just the accessor. I think passing the id which is always a string through would be ok. If you really want the accessor, you might as well pass the whole column back to the render function so that you can use anything in the column.

**Comment by skyflyer** [comment]
Oh, I've been playing with it a bit more and found out that the `id` property is mandatory if using accessor as a function; you are completely right, `id` is always a string.

If you think it makes sense for others as well, I'll prepare a PR where I'll add `columnName` to the `rowInfo` object. Otherwise, I'll just fill it with the `getTdProps` for my use case.

**Comment by skyflyer** [comment]
I hope purely referencing this issue in a fork is sufficient as a pull request? If not, let me know I'll specifically create a pull request for this.

In the end, I decided `columnId` is the proper identifier given that it is `column.id` the property I'm looking for. I also added an example to the react storybook.

**Comment by tannerlinsley** [comment]
You will need to open a pull request for consideration
