### ISSUE TITLE
Any idea how to allow only table to expand one row at a time 

### ISSUE THREAD

**Issue by jomaint** [tannerlinsley/react-table#238]
Hi, 

Anyone has any success to expand only one subComponent at all time?

**Comment by aaronschwartz** [comment]
You will have to override `onExpandRow` and handle keeping track and setting `expandedRows` yourself. You can join the [react-table Slack Channel](https://react-chat-signup.herokuapp.com/) if you need help with the implementation.

**Comment by cherchezlafemme** [comment]
Being able to open only 1 row and collapse rest rows is useful feature. The link to slack channel is broken.
