### ISSUE TITLE
Small sorting performance degredation migrating to v7

### ISSUE THREAD

**Issue by OfficerHalf** [tannerlinsley/react-table#2381]
**Describe the bug (required)**
Sorting performance seems noticeably slower in v7, at least for my case. It isn't _slow_ by any measure, but I immediately noticed it and was surprised.

**Provide an example via Codesandbox! (required)**
I wish I could show my real example where it is maybe a little more pronounced, but I don't have anonymized data, so this will have to do:

v7 Example: https://codesandbox.io/s/github/OfficerHalf/react-table-7
v6 Example: https://codesandbox.io/s/github/OfficerHalf/react-table-6

**Steps To Reproduce (required)**
Try sorting by email on each one. It's not a huge difference and doesn't seem to increase with data size, but still thought it worth mentioning.

**Expected behavior (Recommended)**
Sorting performance should be comparable.

**Desktop (please complete the following information):**

- OS: Win10 1903
- Browser: chrome
- Version 83

**Additional context**
This is based on a real world data set. I have numerous sets of user data from an LDAP directory (which is why email, firstname, lastname are all arrays), most of which are under 1000 records. Still, some of my data sets spike up to as high as 20k rows right now and theoretically have no limit.

However, the difference in sorting speed doesn't really seem to grow with data size. Changing from the ~3100 records (chosen because that's the actual size of the data I was testing on) that I have in the codesandbox examples to 10001 doesn't make a noticeable difference. It just seems like there's some friction during sorting in v7 that isn't present in v6.

Or maybe it's just render speed? I'm not sure.

**Comment by israelidanny** [comment]
I'm also seeing this. Both sorting and grouping are kind of slow in v7 compared to v6.

**Comment by tannerlinsley** [comment]
The default sort for v7 is not "basic" like it was in v6. It has alphanumeric sorting and a bunch of cool stuff built in. Try doing this in v7:

```js
defaultColumn: React.useMemo(() => ({
        sorting: 'basic',
      }), [])
```
