### ISSUE TITLE
StrictMode

### ISSUE THREAD

**Issue by armin2200** [tannerlinsley/react-table#2387]
**Describe the bug (required)**
if Wrapping App with React.StrictMode , when you use useRowSelect , checkboxes doesn’t work correctly 
<React.StrictMode>
    <App />
  </React.StrictMode>

https://ndh6t.csb.app/

**Comment by maxime4000** [comment]
I did report the same issues with example. Each refresh of the table can allow one select/unselect and after it's done until a new refresh of the data. Kinda weird... The select all always work while select one is broken...
I made a duplicate of this issues here : https://github.com/tannerlinsley/react-table/issues/2566

**Comment by tannerlinsley** [comment]
Let's track there.
