### ISSUE TITLE
Multi Sort seems to be broken in the sorting demo

### ISSUE THREAD

**Issue by awarmfastbear** [tannerlinsley/react-table#2396]
**Describe the bug (required)**

Multi sort functionality not working when shift clicking columns in the sorting demo..

**Provide an example via Codesandbox! (required)**
From the doc page [here ](https://github.com/tannerlinsley/react-table/blob/master/docs/examples/simple.md)there is a sorting demo.

**Repro:**

Visit:
https://codesandbox.io/embed/github/tannerlinsley/react-table/tree/master/examples/sorting

Click a column to sort it, then shift click another column, it will show the multi sort actions taking place but the second column doesn't actually get sorted. It just shows an arrow showing what direction it should be sorting.

**Expected behavior (Recommended)**
Both columns should be sorted together.

If this functionality isn't available in this demo, the multi sort buttons shouldn't show up. It should be stated with a reason and how you could add multi sort capability. Or point to a multi sort demo.

**Screenshots**

https://i.imgur.com/KkTW7T0.png

**Desktop (please complete the following information):**

Windows 10, Firefox 76.0.1

**Comment by MaximBG** [comment]
I believe you do not understand the concept of multi sorting.
It first sorts on the first column you chose and then if there are equal entries they are sorted according to the second column entries order. Try to sort by age and visits and you'll see how it works.

**Comment by awarmfastbear** [comment]
Aaaaahh, thank you!
