### ISSUE TITLE
MobX observable array and useSortBy hook do not work together

### ISSUE THREAD

**Issue by MaximBG** [tannerlinsley/react-table#2397]
I am using react-table together wit MobX and till now it worked perfectly. Now I want to implement sorting and something does not work as expected.

I modified your sorting example to use MobX observable array as the data source: https://codesandbox.io/s/affectionate-pike-mp1os
and it does not work - an exception pops up. If to remove useSortBy hook no error occurs.

This issue might be related to [#2369](https://github.com/tannerlinsley/react-table/issues/2369) - the error message is the same.

Following the recommendation in this topic: https://github.com/tannerlinsley/react-table/issues/1657#issuecomment-602028927
I downgraded to v7.0.0-rc.1 and the issue is gone. I confirm, that it started from v7.0.0-rc.2
However if to add useResizeColumns the issue appears even there if to resize a column.

1. Click on "Load" button
2. "Maximum update depth exceeded" error appears after couple of seconds.

Expected behavior: no errors of course.

- OS: Windows 10
- Browser: Chrome
- Version: 81.0.4044.138 (Official Build) (64-bit)

**Comment by tannerlinsley** [comment]
You must pass a stable data reference to useTable. If the reference changes on every render (like it does if you `arr.slice()` it on every render), it will trigger a rerender over and over until your machine dies. Please, use `useMemo`.
