### ISSUE TITLE
Warning in console when using row selection

### ISSUE THREAD

**Issue by sujatha97714** [tannerlinsley/react-table#2398]
I have used react-table along with getToggleAllRowsSelectedProps for row selection.

This is part of my code

```
const tableInstance = useTable(
   {
      columns: defaultColumns,
      data: sessionData,
      autoResetPage: !skipPageReset,
      autoResetSelectedRows: !skipPageReset,
      autoResetSortBy: !skipPageReset,
      autoResetFilters: !skipPageReset,
      autoResetRowState: !skipPageReset,
      getRowId(row) {
        return row.idSession;
      },
      updateSessionName(index, idSession, sessionName) {
        props.updateSessionName(idSession, sessionName);
        let updatedSessionData = JSON.parse(JSON.stringify(sessionData));
        updatedSessionData[index].sessionName = sessionName;
        setSessionData(updatedSessionData);
      }
    },
    useFilters,
    useSortBy,
    usePagination,
    useRowSelect,
    hooks => {
      hooks.visibleColumns.push(cols => [
        // Make a column for selection
        {
          id: 'selection',
          // The header can use the table's getToggleAllRowsSelectedProps method
          // to render a checkbox
          Header: ({ getToggleAllRowsSelectedProps }) => (
            <div className="custom-control custom-checkbox">
              <input
                type="checkbox"
                className="custom-control-input"
                id="select-all-session"
                name="example1"
                {...getToggleAllRowsSelectedProps()}
              />
              <label
                className="custom-control-label"
                htmlFor="select-all-session"
              />
            </div>
          ),
          // The cell can use the individual row's getToggleRowSelectedProps method
          // to the render a checkbox
          Cell: ({ row }) => (
            <div className="custom-control custom-checkbox">
              <input
                type="checkbox"
                className="custom-control-input"
                id={`select-session-${row.values.idSession}`}
                name="example1"
                {...row.getToggleRowSelectedProps()}
              />
              <label
                className="custom-control-label"
                htmlFor={`select-session-${row.values.idSession}`}
              />
            </div>
          )
        },
        ...cols
      ]);
    }
  );

```
I am getting a warning in console as shown in the image. 

![image](https://user-images.githubusercontent.com/66296410/83487750-39017500-a4c9-11ea-8a3c-79562fd20f7e.png)

I found that the cause of this issue is the default value for indeterminate from getToggleAllRowsSelectedProps() is set to 'false' ( a string) but it is actually expected to be a boolean.

I have temporarily managed this in my code with the following patch.

```
Header: ({ getToggleAllRowsSelectedProps }) => {
            let headerProps = getToggleAllRowsSelectedProps();
            headerProps.indeterminate = 'false';
            return (
              <div className="custom-control custom-checkbox">
                <input
                  type="checkbox"
                  className="custom-control-input"
                  id="select-all-session"
                  name="example1"
                  {...headerProps}
                />
                <label
                  className="custom-control-label"
                  htmlFor="select-all-session"
                />
              </div>
             );
})
```
With this patch, I don't see the warning in the console.

**Comment by Mikoz93** [comment]
Have you tried following [this example](https://codesandbox.io/embed/github/tannerlinsley/react-table/tree/master/examples/row-selection) that's listed in the docs?

**Comment by sujatha97714** [comment]
> Have you tried following [this example](https://codesandbox.io/embed/github/tannerlinsley/react-table/tree/master/examples/row-selection) that's listed in the docs?

As you can see in the sample code I have attached, I don't have (or need) an indeterminate state in my code. So I would have replaced <IndeterminateCheckbox /> in the sample code with a classic input checkbox. Everything else is pretty much the same.

**Comment by tannerlinsley** [comment]
If you don't want the `indeterminate` prop, then destructure it out of your props and pass the rest on. It's provided as a convenience, not a requirement.

**Comment by Domiii** [comment]
@tannerlinsley The warning should not be there regardless, wouldn't you agree?

The example listed [here](https://codesandbox.io/embed/github/tannerlinsley/react-table/tree/master/examples/row-selection) requires a big hack-around just to dance around that warning. Can you fix this without having to workaround it, every time you want to use `getToggleAllRowsSelectedProps` or any of its friends?

Changing it to `0` and `1` instead of `false` and `true` would suffice. :)

I agree, it's actually React being stupid. They should fix this on their level, but as long as they don't.... can we fix it at the `react-table` level?
