### ISSUE TITLE
Property paginationClassName not passed to the Pagination component

### ISSUE THREAD

**Issue by jorispz** [tannerlinsley/react-table#24]
While the ReactTable component supports a `paginationClassName` prop (as mentioned in the docs), it doesn't seem to get passed down to the actual Pagination component. (Which, looking at the source, does actually honor that prop - it just isn't passed down.)

Thanks for creating this component, it works great for our use case!

**Comment by tannerlinsley** [comment]
Good find! This should be fixed in the release I just cut 👍 

Thanks for the support!

**Comment by jorispz** [comment]
Awesome, I was just about to commit in my fork and create a pull request, but this is even better!

Thanks for the fix!

**Comment by tannerlinsley** [comment]
:) My pleasure
