### ISSUE TITLE
links not working in IE10

### ISSUE THREAD

**Issue by orhan-swe** [tannerlinsley/react-table#240]
## Problem Description
link elements within cells not accessible when trying to click on them on IE10

## Steps to Reproduce
when i try to inspect the table on IE10, the inspector only sees one element (the whole table) and it is highlighting \<div class="-loading"\> 
NOTE: this is working on other browsers and I am also able to inspect each cell individually. 
I am using react-table stylesheet

![react_table_ie10](https://cloud.githubusercontent.com/assets/10519489/25618474/5f822eb8-2f47-11e7-8bc6-241a170cb884.jpg)

## System Information
* **Browser & Browser Version:**
Internet Explorer 10.0

**Comment by tannerlinsley** [comment]
Not sure why this is happening. Though we don't ensure support

**Comment by tannerlinsley** [comment]
For IE 10, we will look into this issue
