### ISSUE TITLE
Filter is case-sensitive, how to change to not case sensitive??

### ISSUE THREAD

**Issue by yolohello12** [tannerlinsley/react-table#241]
Hi,

The filters in the table is case sensitive. I've gone through the documentation but couldn't find anything on how to change it to not being case sensitive. Any suggestions??

Thanks in advance.

**Comment by aaronschwartz** [comment]
Have you taken a look at the [Filtering](https://github.com/tannerlinsley/react-table#filtering) section of the Readme?

If you want to set the filters on the whole table you can use the `defaultFilterMethod` or you can set each column individually with the `filterMethod`. The Custom Filtering example is a good reference as well.

**Comment by a-x-** [comment]
https://github.com/tannerlinsley/react-table/blob/bc7005db9993df2a38c3c04024c9c49638dc5125/src/defaultProps.js#L25:
```es6
  defaultFilterMethod: (filter, row, column) => {
    const id = filter.pivotId || filter.id
    return row[id] !== undefined ? String(row[id]).startsWith(filter.value) : true
  },
```
```es6
  filterMethod: (filter, row, column) => {
    const id = filter.pivotId || filter.id
    return row[id] !== undefined ? String(row[id].toLowerCase()).startsWith(filter.value.toLowerCase()) : true
  },
```

```jsx
    <Table
        defaultFilterMethod={this.filterMethod}
    />
```

**Comment by yolohello12** [comment]
@a-x- That did the trick, thanks a lot.

**Comment by abdulrahman-khankan** [comment]
> ```js
> filterMethod = (filter, row, column) => {
>     const id = filter.pivotId || filter.id
>     return row[id] !== undefined ? String(row[id].toLowerCase()).startsWith(filter.value.toLowerCase()) : true
>   }
> ```

I suggest applying .toLowerCase() after String(row[id])
as in `String(row[id]).toLowerCase().startsWith`, to make sure data in row[id] is actually a string, and that toLowerCase() exists as well.

Becomes:
```js
filterMethod = (filter, row, column) => {
    const id = filter.pivotId || filter.id
    return row[id] !== undefined ? String(row[id].toLowerCase()).startsWith(filter.value.toLowerCase()) : true
  }
```
