### ISSUE TITLE
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

### ISSUE THREAD

**Issue by kkr600** [tannerlinsley/react-table#2412]
Hi, I'm new here. When I use react-table i have issue like in topic.

The most simple code doens't works:

`import React from "react";`
`import ReactTable from "react-table";`

`const Details = props => {
    const columns = [{  
        Header: 'Name',  
        accessor: 'name'  
       },{  
       Header: 'Age',  
       accessor: 'age'  
       }]  `
    `const data = [{  
        name: 'Ayaan',  
        age: 26  
        }]`
    `return (
        <ReactTable
            data={data}  
            columns={columns}
        />
    )
}`
`export default Details;`

Instead of simple lovely table, I have this:

`index.js:1 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

Thanks for help.

**Comment by IAteYourKitten** [comment]
Same issue.

**Comment by akerckhofs-mycsn** [comment]
Exact same issue.

**Comment by santhoshmohanr** [comment]
Same issue. Still no response.

**Comment by gargroh** [comment]
any codesandbox reproduction of same ?

**Comment by tannerlinsley** [comment]
No reproduction found. Please reopen with a repro.

**Comment by mizusu** [comment]
Greetings.

Is this issue has not been addressed? It occurs in a class-based component and the ReactTable object is `undefined` when added in an import.

`import ReactTable from 'react-table';`

I am using yarn by the way (`yarn add react-table`). Could this be a local issue?

**Comment by gargroh** [comment]
Try to check version of react-table being used here, you may require v6 for this.

**Comment by akerckhofs-mycsn** [comment]
@mizusu I ended up using the useTable hook instead.
