### ISSUE TITLE
Pivot and filter

### ISSUE THREAD

**Issue by cristianocca** [tannerlinsley/react-table#242]
What would be, if possible, the way to use pivotBy while keeping a default filter working for the grouped data?

**Comment by tannerlinsley** [comment]
That will be possible in the next release

**Comment by smoleniuch** [comment]
Hi @tannerlinsley 

Is this feature supported? i can not find the solution for this?

I know you can access `_subRows` on aggregated cell but this property is private.How it can be done properly?

**Comment by tannerlinsley** [comment]
This looks to be a question of implemention. Please repost this question on our support community:

<a href="https://spectrum.chat/react-table">
  <img alt="Join the community on Spectrum" src="https://withspectrum.github.io/badge/badge.svg" />
</a>
