### ISSUE TITLE
Sorting behavior

### ISSUE THREAD

**Issue by snirlugassy** [tannerlinsley/react-table#243]
## Sorting is behaving weird.
When clicking on a column's header to sort, the field is not sorted properly.

Also when clicking several times for sorting, the functionality seems to act weird and kind of randomly or without any pattern.

Update: it seems to happen on columns that handle *null* values, is there any sorting related functionality for null values? should I check if null on render? 

I saw previous issues related to this topic but I didn't understand the problem itself.

BTW I love this project I really think it's amazing!

## System Information
* **Browser & Browser Version:*Google chrome 57.0.2987.133*
* **Node Version:*6.9.5*
* **OS Version:*Windows 10*
* **NPM Version:*3.10.10*

**Comment by tannerlinsley** [comment]
This falls into a previously filed issue for custom sorting.

**Comment by tannerlinsley** [comment]
Glad you like it!
