### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by ValeZhang** [tannerlinsley/react-table#245]
Hi,Thank you for the components you provided.

Sorry if this exists already, I want the form to be an optional configuration that offers radio and multiple options, e.g:

`
<ReactTable data={data} columns={columns} rowSelection={{ type: 'checkbox/radio' }}/>
`

And add a row click event, e.g:

`
<ReactTable data={data} columns={columns} onRowClick={(item, index) => {}}/>
`

Thanks again.

**Comment by ValeZhang** [comment]
Sorry, did not see the documentation. I found the way to handle row click events, which is getTrProps.

**Comment by tannerlinsley** [comment]
Awesome
