### ISSUE TITLE
Financing

### ISSUE THREAD

**Issue by brillout** [tannerlinsley/react-table#2455]
Hi :wave:,

I couldn't connect to your Discord server (#2454); I'm opening a ticket on GitHub, I hope it's ok.

Anyways, I'm Romuald from the [Lsos](https://lsos.org/), an organization that develops financial solutions for open source projects, and we are currently doing outreach to projects we like.

One of our solutions is the [Lsos Commons](https://lsos.org/#lsos-commons), which I believe could fit; is that something React Table would be interested in?

If not I'm sorry for having opened this ticket and I'll close it :).

**Comment by tannerlinsley** [comment]
You can now join the discord server with that link : https://discord.gg/WrRKjPJ

We can chat privately there.

**Comment by brillout** [comment]
We developed a new solution: the [Lsos Donation Fund](https://lsos.org/fund). Unlike the Lsos Commons, the Lsos Donation Fund doesn't alter your license and everything stays free; the donation fund collects donations on your behalf and uses a "donation-reminder".

We estimate the donation-reminder to substantially increase donations. Sublime Text, for example, achieves impressive results using a similar technique.

We are just starting (we are finishing up the implementation of the donation-reminder) and we are looking for a handful of early adopters to try out the donation-reminder.

Would that be something you'd be up to? The only thing you have to do is to add our `@lsos/donation-fund` npm module to your dependencies which implements the donation-reminder. We take care of everything but we'll let you know exactly about our plans and what the npm module does. You'll be more than welcome to object to anything and give feedback.

For example, we plan to show the donation-reminder only to large companies and make it removable. But if you want to further increase donations we can change things.

While in the long term the goal is to distribute company donations among all open source projects used by the company, at the beginning we expect that most donations will go to our early adopters.

We care a lot about transparency; each company will see to what open source projects its donations goes to, and each open source project will see from what companies its donations came from.

Let me know if you are interested, we are eager to give this experiment a shot!

**Comment by tannerlinsley** [comment]
I’ll need full technical details of what the module does, how it works and confirmation from NPM that it is allowed before I can consider it. We just went through a difficult process removing scarf-js for similar privacy reasons.

**Comment by brillout** [comment]
The module should be fine. It basically does the following:

1. Reads the installed packages in `node_modules/` in a postinstall script in order to look after packages that accept funding.
2. Reads the git log to check commit frequency and how many developers are working on the project (that's how we determine whether the project is being developed by a company or if it's a hobby thing).
3. Saves a `~/.lsos.json` to record whether the user removed the donation-reminder.
4. Prints the following to the browser dev console:

<img width="700" src="https://user-images.githubusercontent.com/1005638/86499876-b7358d80-bd8d-11ea-9462-3861c0813dd3.png">

It doesn't do anything beyond that and in particular it doesn't send out data and doesn't use the network.

> full technical details 

We'll thoroughly comment the source code and give an overview of what the module does including what file does what.

> confirmation from NPM

Makes sense, we'll let you know once we are there.

**Comment by nickmccurdy** [comment]
Out of curiosity, how does this differ from the Parity licenses? Is just just a donation script without any changes to the licenses, or does it implement license restrictions that have to be paid to be removed like with Parity?

**Comment by brillout** [comment]
> Is just a donation script without any changes to the licenses [...]?

Yes exactly, the [Lsos Donation Fund](https://lsos.org/fund) doesn't touch the license. Only the [Lsos Commons](https://lsos.org/commons) and the [Lsos Growth](https://lsos.org/growth) require a license clause.

The donation fund revolves around two ideas:
- Reminding companies to donate with a "donation-reminder", which is nothing more than a `console.log` to the browser dev console.
- A simple subscription model: companies donate $10 per developer/month and we take care of fairly distributing the money among open source projects used by the company.

Creating a long-term relationship between open source developers and companies is the name of the game for donations. That's for example why we are currently redesigning the donation-reminder to make it more friendly and more transparent. (If you look at the donation-reminder I posted in my previous reply: it's a cold anonymous message, and users don't know where it's coming from which is a big no-go.) The goal here is to build a relationship and, yes, a donation-reminder is annoying but it is removable simply by entering `npx lsos remove`/`yarn lsos remove`.

> like Parity

License Zero (which Parity is part of) is basically dual licensing: the code is available as a "community version" with a free but restrictive copyleft license, and as an "enterprise version" with a permissive but paid commercial license. For example, MongoDB's community version is AGPL-like licensed and prohibits running a SaaS, while the enterprise version allows running a SaaS but is expensive.

MongoDB has the resources to build all the infrastructure around dual licensing, but individual open source developers don't. The idea of License Zero is to make dual licensing available to anyone &mdash; a dual licensing SaaS, so to speak.

I really like License Zero but I wish they'd focus more on simplicty. Like I understand that Kyle (creator of License Zero) developed several custom licenses for it (such as Parity) to fine-tune copyleft triggering but I'm doubtful this is really necessary, especially prior to having had any traction. AGPL would be so much simpler to get started.

A problem with dual licensing is that it's not particularly open: if MongoDB shuts down then the code is stuck with the restrictive license and nobody can take over.

As you can see this field is a bit tricky.

We try to simplify as much as possible, but it will take time until we get there.

> Out of curiosity

:)

I've created a [discussions repo](https://github.com/Lsos/discussions) in case you want to start further discussions &mdash; I'm always happy to talk about OSS financing.

**Comment by brillout** [comment]
Hi Tanner,

Sorry for the late reply, I have been quite busy the last couple of weeks.

The implementation of the donation-reminder is done: [github.com/lsos/donation-reminder](https://github.com/Lsos/donation-reminder). You can find an explanation of what the source code does [here](https://github.com/Lsos/donation-reminder/tree/master/src).

I doubled checked: npm's terms of service confirms what npm has been doing so far which is to ban commercial advertisements but allow call for donations. For example, if you install [core-js](https://github.com/zloirock/core-js) today you we'll see a postinstall note that asks for donations. So we should be good here.

Since you are looking for sponsors, I'd suggest a copy that mentions this, for example "Hi :slightly_smiling_face:, I'm Alice, I'm looking for a gold sponsor, thanks! :heart:".

Note that there is a `minNumberOfAuthors` parameter that enables you to target companies only. I'd suggest to start with a conservative number such as `7` to see how your community responds to the donation-reminder and then reduce it to `3` or `2`.

The donation-reminder includes a link to `https://lsos.org/npm/react-table` which I'd set up to redirect to [github.com/sponsors/tannerlinsley/](https://github.com/sponsors/tannerlinsley/). (Normally the page looks like this [lsos.org/npm/@wildcard-api](https://lsos.org/npm/@wildcard-api) but I guess you'd prefer to use your GitHub sponsors page instead.) The redirect is important so that I can see how many people visited the `https://lsos.org/npm/react-table` page and how well the donation-reminder is performing with React Table.

Let me know if you are interested and I'll set up the `https://lsos.org/npm/react-table` page.

All in all, I'd suggest to first try to increase donations to meet your financial needs and, if we cannot get there, we can go to the next level and leverage a license clause.

In general, are you interested in:
- Increasing donations only?
- Starting/increasing consulting work for your users?
- Being able to earn a living from your open source work?
- Hiring and remunerating a small engineering team?

If your current donations are too far stretched from your financial goals, then we may want to consider leveraging a license clause. In any circumstance, what's paramount to me is that code stays:
1. Accessible: large companies pay only a small fee, and everything stays free for individuals and small companies.
2. Open: anyone can fork the code with a pure MIT license (or another permissive license). This has been a long-standing problem with financial models so far (such as the dual-licensing model I mentioned earlier). The Lsos Commons is a design that solves this problem. (Btw. I've redesigned the license clause I showed you a while ago and it's much simpler now.)

Also, you mentioned that you are interested in reaching out to companies to convert them to sponsors, and that it has been working out for you. We can further explore this area together, if you are interested. There are ways to automatically track and cold email companies who use React Table but I'm reluctant regarding the ethicality of it. But there are ethical and transparent ways to do it. We can further explore this.

I'm confident we can bring together your financial needs and open source values. Although it may take some time until we get there.

Feel free to hit me up on Discord :)
