### ISSUE TITLE
manualRowSelectedKey leads to incorrect tableInstance

### ISSUE THREAD

**Issue by strass** [tannerlinsley/react-table#2459]
I have a situation where I want my row selection to be controlled via interaction with plotted data. I am using isSelected as my manualRowSelectedKey to send selection details to useTable.  The display works correctly but the tableInstance seems off.

Is this a bug and if not would I be better off using something like row state?

**Provide an example via Codesandbox!**
https://codesandbox.io/s/vibrant-napier-r7zmw?file=/src/App.js

**Steps To Reproduce (required)**
Open the codesandbox, notice that debug display is empty
![Screen Shot 2020-06-17 at 11 52 25 AM](https://user-images.githubusercontent.com/134242/84920345-05117c80-b091-11ea-8cd1-ee6298370935.png)

**Expected behavior**
I expect selectedFlat rows to include rows where isSelected is true. Additionally I'm noticing that using this method, isAllRowsSelected is false even when all rows have been selected manually.

**Screenshots**
![Screen Shot 2020-06-17 at 11 47 15 AM](https://user-images.githubusercontent.com/134242/84919758-59682c80-b090-11ea-8e73-86e8ea5eaffc.png)
![Screen Shot 2020-06-17 at 11 47 25 AM](https://user-images.githubusercontent.com/134242/84919795-671db200-b090-11ea-800e-4eb98e11c0aa.png)
![Screen Shot 2020-06-17 at 11 47 27 AM](https://user-images.githubusercontent.com/134242/84919760-5a00c300-b090-11ea-8bd8-724c6eef8ef3.png)

**Desktop:**

- OS: os x
- Browser chrome
- Version latest

**Comment by tannerlinsley** [comment]
This is a bug that will be addressed in the next major version, since the fix would require breaking changes to the api as a whole. I would implement with rowstate for now. Stay tuned

**Comment by strass** [comment]
Did this get addressed in 7.6.0?

**Comment by Krakof** [comment]
@strass did you find any workaround for preselected rows?

**Comment by strass** [comment]
> @strass did you find any workaround for preselected rows?

yeah, we used a piece of state and a useEffect for syncing

**Comment by Zertz** [comment]
If anyone else runs into this issue, here's what I came up with to get around it:

```js
const { rows, toggleRowSelected } = useTable({
  columns,
  data,
}, useRowSelect);

useEffect(() => {
    rows.forEach(({ id, original }) => {
        if ("isSelected" in original) {
            toggleRowSelected(id, original.isSelected);
        }
    });
}, [rows, toggleRowSelected]);
```

**Comment by AmrStar25** [comment]
this issue still exist at v7.7
