### ISSUE TITLE
Pass row data to custom TrGroupComponent?

### ISSUE THREAD

**Issue by sangnuce** [tannerlinsley/react-table#246]
How can I get the row data in my custom TrGroupComponent or TrComponent component?
I think it should be present in the props.

**Comment by sahil6111** [comment]
@sangnuce  Were you able to get row data in TrComponent props ?

**Comment by sangnuce** [comment]
@sahil6111 Yes, I was.
I used [Custom Props](https://github.com/tannerlinsley/react-table/blob/ad7d31cd3978eb45da7c6194dbab93c1e9a8594d/README.md#custom-props) and returned `RowInfo` as the props passed to my custom Components.
