### ISSUE TITLE
Manual Pagination is true still clearing  page index

### ISSUE THREAD

**Issue by ubheamar** [tannerlinsley/react-table#2483]
**Describe the bug (required)**
Hey first of all thanks for awesome react table library.
I am using react v7 with Hooks i am using usePagination & with graphql 
for server side pagination i set manualPagination true
but its reseting my page index  when i use gotoPage(pageNumber) method
I gone through API there is property called autoResetPage i made it false now its working

But As per documentation when manualPagination is true it should not reset page index

 
 
 `type TableProps = {
    columns;
    data?;
    fetchData?;
    pageInfo?: PaginatorInfo | undefined | any;
    loading: boolean;
};

const Table: FC<TableProps> = ({
    columns,
    data ,
    fetchData,
    loading,
    pageInfo
}) => {
    console.log("Render Table Component");
    const count = useMemo(
        () => Math.ceil(pageInfo?.total / pageInfo?.perPage),
        [pageInfo?.total,pageInfo?.perPage]
    );
    const {
        getTableProps,
        getTableBodyProps,
        headerGroups,
        rows,
        prepareRow,
        page,
        canPreviousPage,
        canNextPage,
        pageOptions,
        pageCount,
        gotoPage,
        nextPage,
        previousPage,
        setPageSize,
        state: { pageIndex, pageSize }
    } = useTable(
        {
            columns,
            data,
            autoResetPage:false,
            initialState: { pageIndex: 1},
            manualPagination: true,
            pageCount:count
        },
        useSortBy,
        usePagination
    );

    useEffect(() => {
        debugger;
        console.log("Page index:"+pageIndex);
        fetchData({ pageIndex, pageSize});
    }, [ pageIndex, pageSize]);
    /*const onPageChange = useCallback((pageNumber)=> {
        debugger;
        gotoPage(pageNumber);
    },[]);*/
    const onPageChange = (pageNumber)=>{
        gotoPage(pageNumber);
    };
    return (
        <Fragment>
            <table className="w-full border border-border" {...getTableProps()}>
                <thead>
                    {headerGroups.map(headerGroup => (
                        <tr
                            className="bg-list_header text-list_header-on border-b border-border"
                            {...headerGroup.getHeaderGroupProps()}
                        >
                            {headerGroup.headers.map(column => (
                                <th
                                    {...column.getHeaderProps(
                                        column.canSort
                                            ? column.getSortByToggleProps()
                                            : []
                                    )}
                                >
                                    <div
                                        className={`${column.isSorted &&
                                            "text-background-on"} flex flex-row items-center justify-between`}
                                    >
                                        <span>{column.render("Header")}</span>
                                        {column.canSort && (
                                            <span>
                                                {column.isSorted ? (
                                                    column.isSortedDesc ? (
                                                        <FiChevronDown />
                                                    ) : (
                                                        <FiChevronUp />
                                                    )
                                                ) : (
                                                    ""
                                                )}
                                            </span>
                                        )}
                                    </div>
                                </th>
                            ))}
                        </tr>
                    ))}
                </thead>
                <tbody {...getTableBodyProps()}>
                    {page.map((row, i) => {
                        prepareRow(row);
                        return (
                            <tr {...row.getRowProps()}>
                                {row.cells.map(cell => {
                                    return (
                                        <td
                                            className=""
                                            {...cell.getCellProps()}
                                        >
                                            {cell.render("Cell")}
                                        </td>
                                    );
                                })}
                            </tr>
                        );
                    })}
                </tbody>
            </table>
            {pageInfo && (
                <div className="px-1 py-4 bg-background">
                    <Pagination
                        pageCount={count}
                        total={pageInfo.total}
                        perPage={pageInfo.perPage}
                        current={pageInfo.currentPage}
                        ariaCurrentLabel="Current page"
                        ariaNextLabel="Next page"
                        ariaPageLabel="Page"
                        ariaPreviousLabel="Previous page"
                        iconNext={<FiChevronRight />}
                        iconPrev={<FiChevronLeft />}
                        rangeBefore={3}
                        rangeAfter={1}
                        onPageChange={onPageChange}
                    />
                </div>
            )}
        </Fragment>
    );
};

export default Table;`

**Comment by bulby97** [comment]
Having the same issue, did you find a solution ?
