### ISSUE TITLE
 gotoPage method not working for last page number

### ISSUE THREAD

**Issue by ubheamar** [tannerlinsley/react-table#2484]
I am using gotoPage method for last page as code written 
PageCount  = 11
newPageIndex = 11

`  canNavigate = pageCount === -1 ? page.length >= state.pageSize : newPageIndex < pageCount;`

it should be

`  canNavigate = pageCount === -1 ? page.length >= state.pageSize : newPageIndex <= pageCount;`
this make canNavigate to false thats why my state is not changing

![image](https://user-images.githubusercontent.com/10156281/86140533-94497600-bb0e-11ea-8594-9b70a2379b85.png)

**Comment by mattnischan** [comment]
@pavanjadhaw 
The page index and count work like an array. The index is zero based, so a page count of 11 would have page indexes of 0 through 10.
