### ISSUE TITLE
[ERROR] Maximum update depth exceeded. This can happen when a component repeatedly ...

### ISSUE THREAD

**Issue by lamualfa** [tannerlinsley/react-table#2487]
**Describe the bug:**

Error when click `th` (that initilized with `getSortByToggleProps`) component in [react-table](https://github.com/tannerlinsley/react-table) and [semantic-ui-react](https://github.com/Semantic-Org/Semantic-UI-React). I use default `useSortBy` plugin. I have tried to wrap `columns` & `data` using `useMemo` and replace [semantic-ui-react](https://github.com/Semantic-Org/Semantic-UI-React) component with native *HTML* component (like `table`, `th`, `td`, etc), but the result is still an error. And the following error that always appears:

```
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

**Codesandbox:**

Codesandbox link: https://codesandbox.io/s/react-table-722-semantic-ui-error-ton9w?file=/src/App.js

**Steps To Reproduce:**

Just click one of the header table to see the error.

**Expected behavior:**

I want the `useSortBy` feature to work well.

**Dependencies:**

- `react-table@^7.2.2`
- `semantic-ui-react@^0.88.2`

**Comment by lamualfa** [comment]
You may not manipulate the `columns` or `data` props inside the component that use `useTable` hook itself.

**Comment by dargaCode** [comment]
@lamualfa thanks for coming back to post your solution! I thought I just had to have the columns and data memoized before it went into `useTable`, but moving the memoization up to the parent component fixed this error for me as well.
