### ISSUE TITLE
React table status true and false in react switch component

### ISSUE THREAD

**Issue by softwaresolution357** [tannerlinsley/react-table#2488]
In my project,Data is showing in react table,I am showing status data(true or false) in switch component, My Status column aren't short and filter corresponding row,Please help me, If any one know.

**Comment by pavanjadhaw** [comment]
@softwaresolution357 it would be great if you provide reproducible code sample :)

**Comment by softwaresolution357** [comment]
this is my project url, you can check
http://dashboard.mylitekart.com/category

**Comment by tannerlinsley** [comment]
Please submit a codesandbox reproduction where we can see the source, output and use-case in an isolated environment.
