### ISSUE TITLE
Parent component state effects child's pagination state

### ISSUE THREAD

**Issue by jdmcd** [tannerlinsley/react-table#2492]
**Describe the bug (required)**
When the table is abstracted into a child component and using pagination, changes in the parent's state resets the pagination for the child. 

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/determined-colden-zlnrp

**Steps To Reproduce (required)**

1. Go to the code sandbox
2. Click on the "next" button to observe that pagination works correctly 
3. While on the second page of the table, click "Click Me"
4. Observe that the table's pagination state resets

**Expected behavior (Recommended)**
The state of the parent component should not affect the view of the child (table) component

**Desktop (please complete the following information):**

- OS: macOS
- Browser Brave (Chromium)
- Version 1.10.90

**Comment by mjchang** [comment]
The [documentation](https://github.com/tannerlinsley/react-table/blob/master/docs/api/useTable.md#table-options) states that columns and data must be memoized. In your case, you're redefining both every render.

**Comment by jdmcd** [comment]
@mjchang gotcha - thanks. Is there a way to do the memo in the GenericTable component? Or do I need to pass it in memo’d?

**Comment by mjchang** [comment]
Pass the in memo'd columns and data. Memo'ing GenericTable doesn't do anything since the state change occurs inside GenericTable.

**Comment by jdmcd** [comment]
@mjchang how would you go about wrapping the props in memo? Doesn't React.memo need a functional component?

**Comment by mjchang** [comment]
https://codesandbox.io/s/interesting-kowalevski-337kk

Or you can convert to a functional component and use useMemo on data and columns like the documentation examples.

**Comment by jdmcd** [comment]
@mjchang thanks!!
