### ISSUE TITLE
Core PaginationComponent can not be overriden

### ISSUE THREAD

**Issue by jorispz** [tannerlinsley/react-table#25]
In contrast to the documentation, ReactTable doesn't seem to actually support a prop named `paginationComponent`. The mentioned `previousComponent` and `nextComponent` do exist and work correctly, it's just the `paginationComponent` that isn't implemented.

**Comment by tannerlinsley** [comment]
This should be fixed in the release I just cut 👍

**Comment by awahlfischle** [comment]
to everybody else stumpling upon this: 
the readme should be updated with the lowercase version

`<ReactTable
   paginationComponent={Component}
/>
`

**Comment by tannerlinsley** [comment]
With the latest version I pushed yesterday, all component props are now
uppercase.
