### ISSUE TITLE
Simplification the usage to make tree tables

### ISSUE THREAD

**Issue by aight8** [tannerlinsley/react-table#250]
## Problem Description
React table is so powerful, that it neglect the usage for some simple use case scenarios.
I used ```react-table``` several times as tree table - and it's wonderfully supports that - however it's not so easy. It requires some tweaking and internal know-how. I think this should be as easy as any other tables.

A good tree table currently requires following steps:
- Set the ```subRowsKey``` property of the ```Table``` component to ```children``` *(or other)*
- Add a hidden column to the ```columns``` definition ```{ accessor: 'children', show: false }``` - otherwise it fails silently because it's not enough that ```children``` is defined in the passed ```data``` it must be effectively a ```column```
- The ```column``` defined as the ```expander``` must implement the ```render``` function.
   - This one must check if ```rowInfo.subRows``` has any items.
      - If not, just render the a row value. **1)**
      - If yes you must reimplement the expander arrow (+ optional rows summary) **2)**
   - Because any good tree table should intend by level this logic must be implemented too **1)** + **2)**

**1)**
```JSX
<span
   style={{
      marginLeft: ((rowInfo.level + 1) * 10 + 5) + 'px',
   }}
>
   {rowInfo.value}
</span>
```

**2)**
```JSX
<div>
   <div
      className={classNames('rt-expander', rowInfo.isExpanded && '-open')}
      style={{
         marginLeft: ((rowInfo.level + 1) * 10) + 'px',
         userSelect: 'none',
      }}
   >
      &bull;
   </div>
   <div>
      // Any summary of the sub rows
   </div>
</div>
```

**Problems:**
- The ```column``` which has the ```expander``` enabled - don't accept ```accessor```, ```header```, ```id``` property. So don't try to access the ```rowInfo.value``` in the ```render``` function of an ```expander``` cell.
- Currently there is no example in the docs for this use case - however it should be improved anyway

**How to make it easier (many ideas):**
- It should be possible that a full row acts as an expander (just attach the expanding event trigger on the whole table row) - possible configuration key on ```Table```: ```fullRowExpander: boolean```
- The ```cell``` which acts as the ```expander``` should one of:
   - Validate ```column``` definition. ```expander``` column cannot contain several props.
   - The ```expander``` ```column``` should exactly acts like any other column (with working accessor).
- Expose a basic expander component (the current expander component) which takes the whole rowInfo. Then it used ```isExpanded``` (open/closed) and ```subRows``` (visible/hidden).
- A table level configuration key ```tree: boolean```. If enabled, the table is optimised as a tree table which means:
   - If ```expander``` ```column``` shows the value gathered by ```accessor``` after the expander arrow.
   - The ```expander``` ```column``` has indent by level or/and has css classes by level (level-1, level-2) etc.

More:
- If sorting by a row value which is an array (for example the subRows property) then sort rows by amount array length + then no array rows

**Comment by tannerlinsley** [comment]
We will take this into consideration for our next round of large changes. Thanks for using react table and thanks for the input! :)
