### ISSUE TITLE
defaultCanFilter not used when accessor is present

### ISSUE THREAD

**Issue by simplecommerce** [tannerlinsley/react-table#2506]
**Describe the bug (required)**

`defaultCanFilter ` does not work as suggested, in the source, it only seems to be checked when an `accessor` is not passed for a column, I am not sure I understand this logic, why would you not consider these options when the `accessor` is valid?

This results is `canFilter` always being `true` for every column regardless if `defaultCanFilter` is set to `false` or even `canFilter` in the column is set to `false`.

Is there a certain logic or reasoning for this? 

Thanks!

**Steps To Reproduce (required)**

1. Go to https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/filtering
2. Set `defaultCanFilter` to `false` in the table options.
4. Nothing happens, columns are still filterable.

**Expected behavior (Recommended)**
Based on the documentation here, https://github.com/tannerlinsley/react-table/blob/master/docs/api/useFilters.md#table-options

I was expecting `defaultCanFilter` to be set to `false` for all my columns and to be able to specify which ones I want to allow filtering by using `canFilter` as suggested.

Thanks for your help!

**Comment by simplecommerce** [comment]
In the end, I decided to pass my own prop per column in order to determine if it was filterable or not.
I used `disableFilters` in order to toggle filters globally.

The default options didn't seem to work with the accessor, so I had to bypass them.

**Comment by chetanism** [comment]
This had me confusing as well, perhaps the documentation is not very clear. Just leaving my understanding here in case it helps others.

1. Applying `useFilters` plugins enables filters for all columns that have an `accessor`
2. If you set `defaultCanFilter` to true, even columns without an accessor will have filter enabled
3. You specifically need to disable filtering for each column that doesn't need a filter using `disableFilters` option.
4. If you use `disableFilters` at table level, the option can not be enabled at column level.

HTH.
