### ISSUE TITLE
Multi Sort Issue (Clicking the last sorted by column toggles the sort instead of replacing it)

### ISSUE THREAD

**Issue by sullyslegacy** [tannerlinsley/react-table#2507]
If the initialState.sortBy is set to 2 columns [Name, Cost], and then you click the last column 'Cost' you'd expect the table to be sorted by just 'Cost' (Since shift was not held down), however clicking the last column only toggles whether it is ASC or DESC sorted.

https://codesandbox.io/s/thirsty-pine-gtzl1  
1. Go to https://codesandbox.io/s/thirsty-pine-gtzl1  
2. Click on Cost (This will only toggle the sort)
3. Click on Cost (This will remove the sort by Cost)
4. Click on Cost (This will only sort by Cost, which is what's expected)

**Comment by tannerlinsley** [comment]
This is fixed now (with your PR! 🎉 )
