### ISSUE TITLE
Array as a setFilter value

### ISSUE THREAD

**Issue by SquareShooter** [tannerlinsley/react-table#2509]
Hi! I need to put an array as the value for setFilter. I have an object like this:
`id: '1',
name: "Name",
values: [
0: 'string1',
1: 'string2',
2: 'string3'
]`

And I want to send changed array **values** to filter my table. What is the best way to do this?

**Comment by luisfavila** [comment]
Have you found a way to do this? 
It seems to take the first array element as the filter when you use `setFilter([...])`
