### ISSUE TITLE
initialState.sortBy doesn't work in v7.1.0

### ISSUE THREAD

**Issue by DarthVitalus** [tannerlinsley/react-table#2518]
**Describe the bug (required)**
Passing an `initialState.sortBy` prop doesn't have effect

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/young-cherry-ey6jb?file=/src/App.js  only change from Sorting example from docs is added `initialState` prop

**Steps To Reproduce (required)**

1. Go to provided codesandbox
2. See rows neither sorted by `firstName`, nor by `lastName`

**Expected behavior (Recommended)**
rows sorted by `firstName` column values, then by `lastName`

**Screenshots**
<img width="1310" alt="Снимок экрана 2020-07-10 в 12 04 33" src="https://user-images.githubusercontent.com/20593651/87137428-8978a900-c2a5-11ea-9dba-c2baf6bf5976.png">

**Desktop (please complete the following information):**

- OS: iOS
- Browser chrome

**Comment by rstrand** [comment]
Your example doesn't pass the `initialState` into `useTable`.
Here is a fixed version of your sandbox with working `initialState`: https://codesandbox.io/s/practical-water-pfhze?file=/src/App.js

**Comment by DarthVitalus** [comment]
@rstrand so sorry for wasting your time! this was a very stupid mistake of mine 😭
thank you!!!
