### ISSUE TITLE
How to freeze the  header when we scroll with overflow: scroll ?

### ISSUE THREAD

**Issue by ashishdhyani** [tannerlinsley/react-table#252]
## Problem Description
How to freeze the  header when we scroll with overflow: scroll ?

Below code used.

                  `<ReactTable 
                            className='-striped -highlight'
                            data={this.props.pivotData}
                            columns={this.props.pivotColumns}
                            showPagination={false}
                            showFilters={true}
                            freezeWhenExpanded={true}
                            pageSize={1000}
                        >
                            {(state, makeTable, instance) => {
                                return (
                                <div style={{overflow: 'scroll',height: '800px', marginLeft:"5px"}}>
                                    {makeTable()}
                                </div>
                                );
                            }}
                        </ReactTable>`

**Comment by tannerlinsley** [comment]
https://github.com/tannerlinsley/react-table/wiki/Fixed-headers-with-scrollable-table-body

**Comment by ashishdhyani** [comment]
Thanks tannerlinsley.
This works properly if there is no pivot on the grid.

But when there is pivoting in the table, everything in the table messes up. Doesnt render the data properly.

Can you please help ?
