### ISSUE TITLE
Toggle all row selected not working for subRow

### ISSUE THREAD

**Issue by pjshu** [tannerlinsley/react-table#2528]
**Describe the bug (required)**
Toggle all row selected not working for subRow

**Provide an example via Codesandbox! (required)**
codesandbox: https://codesandbox.io/s/crimson-river-ymw1p?file=/src/App.js

**Expected behavior (Recommended)**
I'm not sure if this is a bug,
when i click toggle all row checkbox,it is not working for subrow

**Screenshots**
![2020-07-11 14-47-49](https://user-images.githubusercontent.com/47631325/87218545-7093f480-c386-11ea-9b3b-2fee9ad4ce6e.png)

**Desktop (please complete the following information):**

- OS:ubuntu20.04
- chrome
- latest

**Comment by 07harish** [comment]
Hi @pjshu,

I think you should place useExpanded hook before useRowSelect. [here is a working demo](https://codesandbox.io/s/modern-framework-119cg?file=/src/App.js)

I just checked the souce code: `useRowSelect` hook must be placed after these hooks: ['useFilters', 'useGroupBy', 'useSortBy']. But there is no `useExpanded` included in the array. So mostly this should be handled from the library, But the above change will solve this issue for you.

**Comment by pjshu** [comment]
> Hi @pjshu,
> 
> I think you should place useExpanded hook before useRowSelect. [here is a working demo](https://codesandbox.io/s/modern-framework-119cg?file=/src/App.js)
> 
> I just checked the souce code: `useRowSelect` hook must be placed after these hooks: ['useFilters', 'useGroupBy', 'useSortBy']. But there is no `useExpanded` included in the array. So mostly this should be handled from the library, But the above change I mentioned will solve this issue.

thanks!!!slove my problem
