### ISSUE TITLE
Not a bug, but the link to examples is broken 😱

### ISSUE THREAD

**Issue by aditya2337** [tannerlinsley/react-table#2532]
**Describe the bug (required)**
If I click on the examples link on npm, it redirects me to a 404 not found.

**Steps To Reproduce (required)**
Steps to reproduce the behaviour:

1. Go to [react table npm page](https://www.npmjs.com/package/react-table)
3. Scroll down to Documentation
3. Click on examples

**Expected behaviour (Recommended)**
The examples of documentation should be available.

**Screenshots**
![image](https://user-images.githubusercontent.com/18441725/87429714-cf18d700-c601-11ea-9997-dbeb089bb295.png)

**Comment by tannerlinsley** [comment]
We're now using the new documentation website.
