### ISSUE TITLE
Cell is not updated when manually changing data

### ISSUE THREAD

**Issue by nirsky** [tannerlinsley/react-table#254]
On my table I have a custom render function for one of the cells.
The cell is editable and has a submit button.
Once submit is pressed I post the change to my server and also **update the local data** that was previously pulled from the server (this is done to reduce refetching the data from the server).

The data is updated properly but the change is not visible on the table.
the change only becomes visible when I "force" re-render (e.g. go to the next page and then go back, filter out the row and then remove filter).

Any way to force re-render without taking extra actions?

**Comment by aaronschwartz** [comment]
It is most likely because you are mutating the data object instead of providing a new copy of it when your data changes.

When you modify your data make sure you're creating a new object reference for your data.

E.g. 
```
data = [...data];
data[2] = {
  ...data[2],
  changedKey: changedValue
}
```

**Comment by nirsky** [comment]
Yap, this worked, thanks a lot!
