### ISSUE TITLE
useResize not working in production

### ISSUE THREAD

**Issue by rogerdribeiro** [tannerlinsley/react-table#2555]
**Describe the bug**
UseResize works normally in the development environment, but does not work in production.
I am using version 7.2.2.

**Steps To Reproduce**
After deploying the application (create-react-app), go to the table and try to resize the width of any column. get the following error:

![WhatsApp Image 2020-07-17 at 13 31 27](https://user-images.githubusercontent.com/41801242/87963420-10403980-ca8f-11ea-9014-75f0e9d33e88.jpeg)

**code of table** -> https://codesandbox.io/s/damp-browser-ww2p5?file=/src/Table.js

**Comment by maxime4000** [comment]
I think your code sandbox is missing some file.

**Comment by tannerlinsley** [comment]
Needs a better repro.
