### ISSUE TITLE
UseRowSelect doesn't work properly in a "default" React environment. React.StrictMode cause problem.

### ISSUE THREAD

**Issue by maxime4000** [tannerlinsley/react-table#2566]
**Describe the bug (required)**
So I try to make a react table using most of the feature and I use the CodeSandbox to experiment and I was getting different result between the CodeSandbox version and the App I'm developping. So I made a testing environment to understand that it's a real problem that I'm not sure why it's happening. 
So I did find out why the select was broken and it's because at the root of the app, I have <React.StrictMode><App/></React.StrictMode> 

# Codesandbox example :
## React.StrictMode Disable: 
-   [Javascript version](https://codesandbox.io/s/laughing-benz-qxo1z)
-   [Typescript version](https://codesandbox.io/s/bold-lehmann-nfpdm?file=/src/App.tsx)
## React.StrictMode Enable:
-   [Typescript version](https://codesandbox.io/s/unruffled-lamarr-kcg7x?file=/src/App.tsx) - [base on this repo](https://github.com/maxime4000/TestPerfReactTableTypescript)

Use a react-table v7.3.2 aka Latest to reproduce the issue.

1. yarn create react-app my-app --template typescript
2. Add same file that are working in the example solution from the docs (codesandbox)
3. Make App use the grid
4. Select data and only 1 select is keep between refresh of the react-table, other select are lost.

**Expected behavior (Recommended)**
I expect the behavior from the example codesandbox, but the select work completely differently. It is cause by the React.StrictMode which isn't enable in prod but because this tools has the purpose to help finding potential problem, react-table should be working fine with React.StrictMode activated.
See : https://reactjs.org/docs/strict-mode.html

**Comment by sudhakarnam4work** [comment]
Yes , Am also facing problem in **StrictMode** ,  Multiple row selection is not working as Expected :(

**Comment by mickgr** [comment]
I have the same problem.
Only works if I remove React.StrictMode

**Comment by tannerlinsley** [comment]
React Table v7 isn't 100% ready for concurrent mode, so this will be the case until v8 comes out with all of the CM-safe stuff.

**Comment by tannerlinsley** [comment]
I'll accept any PR's to make v7 better with Strict Mode for now, but I'm focusing all my efforts on the new suspense/CM compatibility in v8.

**Comment by mickgr** [comment]
Hi,
Will be happy to contribute and try to fix this.
can you please help me understand how can I run the useRowSelect example to
take the output in the dist folder?

Michael
