### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by atkawa7** [tannerlinsley/react-table#257]
Just wondering how the filter works. For example I have a table like this
| Name    |value|
|----------|------|
| Apple    | 10    |
| Banana  | 8      |
| Apple    | 11    |
| Apple    | 12    |

I am trying to filter at the server. However when my data comes from the server it is in the following form

```
[
"results": [{
"name": A,
"value": 10
},
{
"name": B,
"value": 8
},
{
"name": A,
"value": 11
},
{
"name": A,
"value": 12
}],
"pageSize": 10,
"count" : 10,
"page": 1
]
```
If I filter using A and B's. However I want the user to filter using full words not abbreviations

**Comment by aaronschwartz** [comment]
What is the question?

Are you having a problem using the `filterMethod` option with a controlled table?

Posting your current table and column options to see what you have so far might be helpful.

**Comment by atkawa7** [comment]
@aaronschwartz I want to filter using using full words and not abbreviations ie filter by "Apple", "Banana" and not by "A" or "B". How do I go about that when the server is expecting abbreviations i.e "A" or "B"?

**Comment by aaronschwartz** [comment]
So your data from the server is "A" and "B" but you render it as "Apple" "Banana"?

The filter is set to whatever the user types in. There's not much you can do except something like:
```
if("Apple") {
 filter("A")
}
if("Banana") {
 filter("B")
}
```

**Comment by atkawa7** [comment]
>>> So your data from the server is "A" and "B" but you render it as "Apple" "Banana"?

@aaronschwartz  yes that is correct.

So lets say you have more fruits like carrots,orange etc and  the user types "Apple and Bananas" , "Apple,Bananas"  or "Apple|Bananas". How would you do such filter?

**Comment by tannerlinsley** [comment]
Seeing how the filter interface is fully customizable, this is now considered an implementation question. Going to close this issue, but you want, you can continue the discussion on our [slack channel](https://react-chat-signup.herokuapp.com/) for more information on implementation.
