### ISSUE TITLE
Using Filterable + filterMethod lead to infinite calls of filterMethod

### ISSUE THREAD

**Issue by VRymarovich** [tannerlinsley/react-table#2582]
**Describe the bug (required)**
When I use filterable and custom filterMethod in filtered columns it leads to infinite calls of filterMethod when I change filteable. See example below

**Provide an example via Codesandbox! (required)**
[react-table codesandbox](https://codesandbox.io/s/react-table-custom-filtering-multiple-values-filter-v1y13?file=/index.js)

**Steps To Reproduce (required)**
1. Choose age in select and press filterable button. 
2. Open console, it will write multiple 'filter records'.

**Expected behavior (Recommended)**
I want to filter data separately in external filters (select) and using internal filters

**Screenshots**
![image](https://user-images.githubusercontent.com/5712547/88818790-c5799c80-d1c7-11ea-9102-9bfc08c35d61.png)

**Comment by tannerlinsley** [comment]
Well, you're not memoizing your columns, so regardless of what you pass as the filter method, an infinite render will occur. You need to `useMemo` your columns and data.
