### ISSUE TITLE
Can title value for sortable column be a option instead?

### ISSUE THREAD

**Issue by harshithjv** [tannerlinsley/react-table#2583]
https://github.com/tannerlinsley/react-table/blob/9676c8f0c285c365eab5ee18efc6aec24f406330/src/plugin-hooks/useSortBy.js#L50

In above code `Toggle SortBy` is hard-coded. Better to make it available as option variable so that it can even be a locale string.

**Comment by gargroh** [comment]
you can overwrite the same by passing required title...pass empty to show
no title

**Comment by harshithjv** [comment]
@gargroh 

I tried adding `title` via column data and it does not work. From the link I shared above its conspicuous that `column.title` isn't used anywhere in `defaultGetSortByToggleProps` function.

**Comment by gargroh** [comment]
pass {title:'xyz'} in getSortProps methods

**Comment by harshithjv** [comment]
@gargroh 

I don't see mention of `getSortProps` in the docs. Can you give full example as in where to use it? in column options?

I feel its better to place it as user configurable option as `tooltipText` in *column* data options.

**Comment by harshithjv** [comment]
@tannerlinsley I wonder why this was closed without giving explanation?

There is no mention of `getSortProps` in docs. I don't find it while searching on your repo while searching here on github too.
