### ISSUE TITLE
How to remove {flex, width, max-width} styles in every cell?

### ISSUE THREAD

**Issue by a-x-** [tannerlinsley/react-table#259]
I want to specify custom styles (no styles).

I want to remove this: https://github.com/tannerlinsley/react-table/blob/master/src/index.js#L561
https://github.com/tannerlinsley/react-table/blob/master/src/index.js#L726
etc.

Maybe you can rewrite this like:
```js
          style={{
            flex: width ? `${width} 0 auto` : '',
            width: width,
            maxWidth: maxWidth,
            ...styles,
          }}
```

p.s. you should not add px, react do it itself better (think about null, 'auto',  etc. cases)

**Comment by tannerlinsley** [comment]
Currently you would need to override these styles to their initial values using either `getItemProps` for each element, or via a stylesheet.

**Comment by a-x-** [comment]
I tried `getTdProps` w/o any effect.

**Comment by tannerlinsley** [comment]
Other than overriding these styles in a stylesheet, there currently isn't any way in JS to accomplish this. We'll keep this in mind going forward for future releases.
