### ISSUE TITLE
canSort is always true when manualSortBy is true

### ISSUE THREAD

**Issue by Billy-** [tannerlinsley/react-table#2599]
**Describe the bug**
`column.canSort` is always true when `manualSortBy` is `true`. I'd expect it to default to false for each column (the docs show `defaultCanSort` should default to `false` on both the table and column level). Even if I set these explicitly to false on both the table level options and/or the column level options, `column.canSort` is always true.

[codesandbox](https://codesandbox.io/s/eloquent-monad-j22fj?file=/src/App.js)

**Steps To Reproduce**

1. Go to the codesandbox above
2. Observe the `defaultCanSort` is false on both the table options and one of the column options
3. Observe that all columns can still be sorted

**Expected behavior**
`column.canSort` respects the `defaultCanSort` options.

**Additional context**

I have noticed that `disableSorting` _does_ work in disabling it. I'm confused as to why there is  `defaultCanSort` and `disableSorting` - as opposed to `defaultCanSort` and `canSort`? Is there a difference I'm not understanding? And if `defaultCanSort` is `false`, why is that not respected?

And why is it "default" canSort - this makes me think it's the default for an uncontrolled prop/state and that `canSort` could change.. is that possible?

**Comment by EvgenyCrow** [comment]
@Billy- Column properties should be: disableFilters, disableSorting.

**Comment by Billy-** [comment]
> @Billy- Column properties should be: `disableFilters`, `disableSortBy`.

The docs also show table and column level props for `defaultCanSort` - this is what my issue is about - they don't seem to work.

I don't want to repeat `disableSortBy` on every column - I want to default `canSort` to false and then only set it to true on a column where I want to support it.

**Comment by Dandry** [comment]
> > @Billy- Column properties should be: `disableFilters`, `disableSortBy`.
> 
> The docs also show table and column level props for `defaultCanSort` - this is what my issue is about - they don't seem to work.
> 
> I don't want to repeat `disableSortBy` on every column - I want to default `canSort` to false and then only set it to true on a column where I want to support it.

+1. It looks like one cannot globally disable sorting (table-level) and have that enabled on column level only for the ones which actually should support sorting.

**Comment by tannerlinsley** [comment]
Thanks for noting this issue. To fix it, a breaking change is required and thus we will slate the fix for v8 and, for sake of triage, close this issue.

Thanks for your patience!

**Comment by shuheitachikawa** [comment]
is this problem fixed? I am facing same problem...
