### ISSUE TITLE
How to call default filter method from child element

### ISSUE THREAD

**Issue by missmellyg85** [tannerlinsley/react-table#260]
I would like to have a single filter input that filters on all columns with filtering enabled.
I am having trouble firing an event that triggers filtering in the table. Ideally, I'd like to be able to add an onChange call to my input that sends the right data to the table's default onFilterChange method.

So far, I've tried a few things, but this is the closest to what I'd want, though it doesn't work:
```
<ReactTable
      data={this.state.savedSearches}
      columns={columns}
      showFilters={true}
      defaultFilterMethod={(filter, row) => 
            (row[filter.id].toUpperCase().includes(filter.value.toUpperCase()))}
>
      {(state, makeTable, instance) => {
            return (
                  <div>
                        <div>
                              <label>Search:</label>
                              <input type="text" onChange={(e) => {
					state.onFilteringChange(state.columns[3], e.target.value)
				}}/>
                        </div>
                        {makeTable()}
                  </div>
            )
      }}
</ReactTable>
```
I can't seem to find a way to do this.

**Comment by tannerlinsley** [comment]
In the next major version, `filters` will be a fully controllable prop.
Would this help?

**Comment by missmellyg85** [comment]
It will definitely help if I can hook into the filtering of the main component.

**Comment by tannerlinsley** [comment]
This is now possible in the latest version. Simply build your own filter model using the `filtered` prop like so: 
```javascript
filtered={[
  {id: 'columnID', value: 'myFilterValue'},
  {id: 'otherColumnID', value: 'myOtherFilterValue'}
]}
```
