### ISSUE TITLE
incorrect link in the example

### ISSUE THREAD

**Issue by toczeksiedlce** [tannerlinsley/react-table#2611]
**Describe the bug** and **Steps To Reproduce**

when go to https://react-table.tanstack.com/docs/examples/material-ui-components

and click on the "View Source" I got 404 error

**Expected behavior**

the correct link is: 
https://github.com/tannerlinsley/react-table/tree/master/examples/material-UI-components (look at the `UI')

thanks

**Comment by semopz** [comment]
Same here. The example doesn't even load up.

Also, the next link down (Material-UI Kitchen Sink) link goes to a 404

**Comment by giubatt** [comment]
Same problem here, both examples are broken

**Comment by giubatt** [comment]
Correct link for the sandbox is also https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/material-UI-components

**Comment by tannerlinsley** [comment]
Fixed.
