### ISSUE TITLE
Cannot sort by Date

### ISSUE THREAD

**Issue by 89erik** [tannerlinsley/react-table#2613]
**Describe the bug (required)**
A column with Date objects cannot be sorted. Note that it is possible to do this by using the accessor function to convert the Date to a sortable string. This is not always practical, though, for example if the column's filter expects the value to be a Date.

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/eager-bouman-95uot?file=/src/App.js

**Steps To Reproduce (required)**

1. Go to https://codesandbox.io/s/eager-bouman-95uot?file=/src/App.js
2. Click on the Date column, switching back and forth between asc and desc
3. The column is never sorted right

**Expected behavior (Recommended)**
Expected both the column in the sandbox example to sort exactly the same way

**Comment by sgratzl** [comment]
according to the docs there is the `sortType` property. https://react-table-omega.vercel.app/docs/api/useSortBy. When I set it to `sortType: 'datetime'` it works for me as expected

see also https://codesandbox.io/s/great-payne-3t5jb?file=/src/App.js

**Comment by 89erik** [comment]
Thanks!
