### ISSUE TITLE
Non-resizable columns

### ISSUE THREAD

**Issue by achingbrain** [tannerlinsley/react-table#262]
Is there a way to have some columns be resizable and others not?  I've got a table with columns of checkboxes, icons and text - it makes sense for the text columns to be resizable but the checkboxes & icons should remain fixed width.

Awesome module, btw.

**Comment by aaronschwartz** [comment]
Currently no.

The next major version in the works will have this functionality.

**Comment by achingbrain** [comment]
Great, I'll look out for it, thanks.
