### ISSUE TITLE
useResizeColumns does not clean up eventlistener for touch events properly.

### ISSUE THREAD

**Issue by jyang14** [tannerlinsley/react-table#2622]
In the following code, shouldn't line 92 be `handlersAndEvents.touch.upHandler` instead?

https://github.com/tannerlinsley/react-table/blob/efaaa71baadff44d1109f4cdbff1014fa1a0a5ab/src/plugin-hooks/useResizeColumns.js#L85-L95

**Comment by tannerlinsley** [comment]
Indeed. Please submit a PR with a fix if this is urgent, otherwise we will slate the fix for v8.
