### ISSUE TITLE
Getting the number of expandable rows

### ISSUE THREAD

**Issue by Marfa93** [tannerlinsley/react-table#263]
Hi there !
First of all, I apologize for my bad english.

I want to know if there is a way to know the number of expandable rows created with the pivoting.
When row count is lower than the page size, the component leaves blank rows and I want to void that.

Thank you !

**Comment by aaronschwartz** [comment]
Rows that are under a pivot should not count towards the row count.

If you really want to know the number of expanded rows you can fully control the `expanded` prop and then you will be able to count the items inside of it.

See https://github.com/tannerlinsley/react-table#fully-controlled-component for more information.

**Comment by Marfa93** [comment]
Thanks for answer !

I misspoke myself.

> Rows that are under a pivot should not count towards the row count.
I do not want to count the rows under the pivots, just the displayed rows ^^

**Comment by Marfa93** [comment]
Hi !

Sorry for the long absence. I found a solution for my problem, here's a link to a CodePen : http://codepen.io/marfa93/pen/wdxLbo

Feel free to ask !
