### ISSUE TITLE
the ID passed to the filter function is not an string

### ISSUE THREAD

**Issue by danielo515** [tannerlinsley/react-table#2644]
**Describe the bug (required)**
The ID that is provided to the filterFunctions is not a string. Looking at the examples (the only source where you can see what the filter functions get) it is used to access an object property like if it was an string, but in reality it is an array, so the lookup will always fail.
The only reason why individual fields works is because the ID is a single element string, and due to the nature of javascript it is coerced to string that results in just a string, but it will fail for global filters for example.

**Provide an example via Codesandbox! (required)**
[react-table codesandbox](https://codesandbox.io/s/trusting-ride-y8tm9) to reproduce the issue.

**Steps To Reproduce (required)**

1. Go to the sandbox
2. Change the profile progress
3. Check the console
4. See the logged ID as an array

**Expected behavior (Recommended)**
I actually expect the examples and docs to be updated

**Comment by tannerlinsley** [comment]
Thanks for noting this issue. To fix it, a breaking change is required and thus we will slate the fix for v8 and, for sake of triage, close this issue.

Thanks for your patience!
