### ISSUE TITLE
how do i update react table after i added or removed rows?

### ISSUE THREAD

**Issue by johnsonreyliu** [tannerlinsley/react-table#266]
## Problem Description
I am trying to update react table programatically to refresh itself when i add or remove new data to the table. Is there a way to refresh the table without refreshing the whole page?

I bind data using {this.state.myData}

## Steps to Reproduce
1. list the steps
2. to reproduce the issue

## System Information
* **Browser & Browser Version:** Chrome, latest version
* **Node Version:** 6.10.3
* **OS Version:**
* **NPM Version:**
* **Yarn Version:**

**Comment by aaronschwartz** [comment]
Data should be automatically refreshed when you change the reference to `data`. Make sure you're not mutating the original reference but creating a new copy (e.g data = [...data])

If you need more help with implementation please join the slack channel.

Slack Signup: https://react-chat-signup.herokuapp.com/
