### ISSUE TITLE
Documentation web site (react-table.tanstack.com) nav-bar links only work on home page

### ISSUE THREAD

**Issue by rjray** [tannerlinsley/react-table#2667]
**Describe the bug (required)**
On the docs website (https://react-table.tanstack.com/), once you click on any of "Docs", "Examples" or "API", those three nav-bar elements are no longer linked.

**Provide an example via Codesandbox! (required)**
https://react-table.tanstack.com/

**Steps To Reproduce (required)**

1. From home page
2. Click on any of "Docs", "Examples" or "API"
3. Attempt to click on any of those again
4. See propblem

**Desktop (please complete the following information):**

- OS: all
- Browser: Firefox
- Version: 79

**Additional context**
Sorry for using this method of reporting this, but there is literally no contact information for you other than the Discord, Twitter handle, etc. on this page or tanstack.com.

**Comment by tannerlinsley** [comment]
Works fine for me and my coworkers!
