### ISSUE TITLE
manualPagination causes useEffect loop Cycle

### ISSUE THREAD

**Issue by chrismpalmer** [tannerlinsley/react-table#2671]
useEffect seems to be stuck in a loop even with the most basic samples provided.

https://codesandbox.io/s/vigorous-sky-beu8n?file=/src/App.js

**Steps To Reproduce (required)**

1. Go to link above and un comment line 93
2. save sanbox
3. infinite loop occurs

**Expected behavior (Recommended)**
The code provided as reference to support fetching external data should not cause infinite loop.

**Desktop (please complete the following information):**

- OS: [iOS]
- Browser [Brave]
- Version [1.12]

**Additional context**
I am getting a better understanding of react hooks and I could be doing something very incorrect. But I can't see how I am causing the infinite loop. Unless the dependencies pageIndex and pageSize are actually changing.

**Comment by Vezarino** [comment]
What's happening is you're re-creating the Table component on every render, so React runs cleanup on the old hook, and runs the hook again, since it's now rendering a new instance. Either move it outside of your render function, or memoize it.
For example: https://codesandbox.io/s/focused-ride-zpdo2?file=/src/App.js

**Comment by chrismpalmer** [comment]
> What's happening is you're re-creating the Table component on every render, so React runs cleanup on the old hook, and runs the hook again, since it's now rendering a new instance. Either move it outside of your render function, or memoize it.
> For example: https://codesandbox.io/s/focused-ride-zpdo2?file=/src/App.js
@Vezarino 
Thank you very much. I understand what you are saying now. I need to go back and review the examples. I believe they are in this form and can cause the problem for a new person.
