### ISSUE TITLE
useResize not working in production

### ISSUE THREAD

**Issue by rogerdribeiro** [tannerlinsley/react-table#2688]
**Describe the bug (required)**
I am using version 7.3.2.

UseResize works normally in the development environment using the Chrome browser.
Using Firefox in development, I get an error when trying to perform the resize for the first time (you can see this error below), but when I reloaded the page again this error no longer appears, and it works normally.

In production, it does not work in any browser, and the screen goes white when resizing the column and the console shows the error according to the image below.

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/fancy-rain-4lmqs?file=/src/Table.js

**Steps To Reproduce (required)**
After deploying the application (create-react-app), go to the table and try to resize the width of any column. get the following error:
![87963420-10403980-ca8f-11ea-9014-75f0e9d33e88](https://user-images.githubusercontent.com/41801242/91637500-5f0eb680-e9df-11ea-9f36-6eed9def823a.jpeg)

**Error getting using firefox (development)**

`TypeError: _headerIdWidths is undefined
reducer$b
node_modules/react-table/dist/react-table.development.js:4179

  4176 | var percentageDeltaX = deltaX / _columnWidth;
  4177 | var newColumnWidths = {};
  4178 | 
> 4179 | _headerIdWidths.forEach(function (_ref2) {
       | ^  4180 |   var headerId = _ref2[0],
  4181 |       headerWidth = _ref2[1];
  4182 |   newColumnWidths[headerId] = Math.max(headerWidth + headerWidth * percentageDeltaX, 0);

useTable/reducer</<
node_modules/react-table/dist/react-table.development.js:1064

  1061 | 
  1062 | 
  1063 |   return [].concat(getHooks().stateReducers, Array.isArray(getStateReducer()) ? getStateReducer() : [getStateReducer()]).reduce(function (s, handler) {
> 1064 |     return handler(s, action, state, getInstance()) || s;
       | ^  1065 |   }, state);
  1066 | }, [getHooks, getStateReducer, getInstance]); // Start the reducer
  1067 | 

useTable/reducer<
node_modules/react-table/dist/react-table.development.js:1063

  1060 |   } // Reduce the state from all plugin reducers
  1061 | 
  1062 | 
> 1063 |   return [].concat(getHooks().stateReducers, Array.isArray(getStateReducer()) ? getStateReducer() : [getStateReducer()]).reduce(function (s, handler) {
       | ^  1064 |     return handler(s, action, state, getInstance()) || s;
  1065 |   }, state);
  1066 | }, [getHooks, getStateReducer, getInstance]); // Start the reducer

updateReducer
node_modules/react-dom/cjs/react-dom.development.js:15120

  15117 |     newState = update.eagerState;
  15118 |   } else {
  15119 |     var action = update.action;
> 15120 |     newState = reducer(newState, action);
        | ^  15121 |   }
  15122 | }
  15123 | 

useReducer
node_modules/react-dom/cjs/react-dom.development.js:15904

  15901 | ReactCurrentDispatcher.current = InvalidNestedHooksDispatcherOnUpdateInDEV;
  15902 | 
  15903 | try {
> 15904 |   return updateReducer(reducer, initialArg, init);
        | ^  15905 | } finally {
  15906 |   ReactCurrentDispatcher.current = prevDispatcher;
  15907 | }

useReducer
node_modules/react/cjs/react.development.js:1467

  1464 | 
  1465 | function useReducer(reducer, initialArg, init) {
  1466 |   var dispatcher = resolveDispatcher();
> 1467 |   return dispatcher.useReducer(reducer, initialArg, init);
       | ^  1468 | }
  1469 | 
  1470 | function useRef(initialValue) {

useTable
node_modules/react-table/dist/react-table.development.js:1068

  1065 |   }, state);
  1066 | }, [getHooks, getStateReducer, getInstance]); // Start the reducer
  1067 | 
> 1068 | var _React$useReducer = React.useReducer(reducer, undefined, function () {
       | ^  1069 |   return reducer(initialState, {
  1070 |     type: actions.init
  1071 |   });

Table
src/pages/NewMonitorTable/Table.js:34

  31 |   () => ({width:132}), []
  32 | );
  33 | 
> 34 | const {
     | ^  35 |   getTableProps,
  36 |   getTableBodyProps,
  37 |   headerGroups,`

**Comment by tannerlinsley** [comment]
This should be fixed in the latest version.
