### ISSUE TITLE
Wrapping <App /> with <React.StrictMode> in index.js breaks combination of rows and pagination

### ISSUE THREAD

**Issue by MislavPeric** [tannerlinsley/react-table#2689]
**Describe the bug (required)**
I was attempting to use rows and pagination with React 16.13.1 and you can't select more than one row (the selectedRowId doesn't update past that one selected row). If you attempt to select other checkboxes you can select one at the time, but the selectedRowId won't update. The issue comes from <App /> being wrapped by default with <React.StrictMode> when starting a new project with CRA

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/m5lxzzpz69

**Steps To Reproduce (required)**
Create a new CRA project, attempt to copy-paste everything from the example sandbox except the index.js,

**Expected behavior (Recommended)**
selectedRowIds should update on each select, you should be able to select more than one box and have the value change.

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser: Chrome
- Version: 84.0.4147.135

**Additional context**
The workaround to this is removing the <React.StrictMode> that's wrapping <App /> from index.js. I'm not sure if this is intended behavior, but I lean on it being a bug.

**Comment by tannerlinsley** [comment]
This should be fixed now.
