### ISSUE TITLE
Use OnfilterChange to change page index.

### ISSUE THREAD

**Issue by kirank3836** [tannerlinsley/react-table#269]
Hi,

I'm want to change pageIndex on calling onFilteredChange, but I'm not to access the pageIndex to change. How can I access pageIndex from that call?

Thank you,

**Comment by tannerlinsley** [comment]
You will need to use the component instance like so:
```javascript
<ReactTable
  ref={el => this.tableInstance = el}
  onFilteredChange={() => {
    const { page } = this.tableInstance.getResolvedState()
    // page is the current pageIndex
  }}
/>


```
