### ISSUE TITLE
Hard coded column header tooltip interferes with a user provided one 

### ISSUE THREAD

**Issue by vladifel** [tannerlinsley/react-table#2693]
**Describe the bug (required)**
When using the Material-UI Table, with the ```useSortBy``` hook and adding a ```Tooltip``` to the column header, one of two things happen:
* In case the ```Tooltip``` is added inside the ```TableColumn``` component, a hard-coded tooltip appears next to the user provided one. try this [codesandbox](https://codesandbox.io/s/funny-easley-s8kbn)
![image](https://user-images.githubusercontent.com/41642429/91664203-5230b680-eaf6-11ea-90f1-767326c5c4e1.png)
* In case the ```Tooltip``` is added above the ```TableColumn``` component, the following error appears in the console:
. try this [codesandbox](https://codesandbox.io/s/shy-pine-7umv9?file=/src/App.js)
![image](https://user-images.githubusercontent.com/41642429/91664269-b94e6b00-eaf6-11ea-926d-43017c9d60ce.png)

**Desktop:**

- OS: [Win10]
- Browser [chrome]
- Version [7.5.0]

**Comment by gargroh** [comment]
Pls search in discussion, related question is there.

**Comment by vladifel** [comment]
> Pls search in discussion, related question is there.

Only thing I found in the discussion is the question I posted (no answers).
With the error in the console and no exposed prop to remove the tooltip or to provide user defined one, it looks like a bug.

**Comment by ivaskevych** [comment]
@vladifel you can remove the default title with:
`{...column.getHeaderProps(column.getSortByToggleProps({ title: undefined }))}`

**Comment by vladifel** [comment]
> @vladifel you can remove the default title with:
> `{...column.getHeaderProps(column.getSortByToggleProps({ title: undefined }))}`

Worked perfectly. Thanks!
