### ISSUE TITLE
autoResetSelectedRows Typescript problem

### ISSUE THREAD

**Issue by tahv0** [tannerlinsley/react-table#2697]
Getting error when giving autoResetSelectedRows option.

```
Argument of type '{ columns: any; data: any; autoResetSelectedRows: boolean; }' is not assignable to parameter of type 'TableOptions<object>'.
  Object literal may only specify known properties, and 'autoResetSelectedRows' does not exist in type 'TableOptions<object>'.ts(2345)
```

This is documented feature https://react-table.tanstack.com/docs/api/useRowSelect
Why I'm getting this error? 

Code sample:

```
  const {
    getTableProps,
    getTableBodyProps,
    headerGroups,
    rows,
    prepareRow,
    state: { pageIndex, pageSize, selectedRowIds },
  } = useTable(
    {
      columns,
      data,
      autoResetSelectedRows: false,
    },
    useFlexLayout,
    useRowSelect
  );
```

**Comment by Vezarino** [comment]
Have you included a react-table type configuration file in your project, as described by https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table ?
Specifically, this property is provided by UsePaginationOptions<D> in interface TableOptions.
Additionally I suggest removing Record<string, any> from that interface, as it would allow you to input unknown keys without warning.

**Comment by tahv0** [comment]
@Vezarino  ok so the `"@types/react-table": "^7.0.22"` is not enough?

**Comment by Vezarino** [comment]
Indeed. The @types/react-table package assumes no plugins are loaded without a config, the linked example config assumes every plugin is loaded. The only way to accurately represent your specific plugin setup is to manually adjust the provided example - though you can use it as-is if you don't mind typescript accepting code that relies on plugins that are not enabled.

**Comment by showduhtung** [comment]
@Vezarino does that also cover the typescript issue with adding customized, non-specified functions into useTable?:

```
 const updateMyData = (rowIndex, columnId, value) => {
    setData((old) =>
       old.map((row, index) =>
         index === rowIndex ? { ...old[rowIndex], [columnId]: value } : row,
       ),
     );
  };
  const { getTableProps, headerGroups, rows, prepareRow } = useTable(
    {
      columns,
      data,
      defaultColumn,
      updateMyData,
    },
    usePagination,
  );
```

This code comes directly from https://react-table.tanstack.com/docs/examples/editable-data

**Comment by Vezarino** [comment]
While we do not use that functionality ourselves, a quick check would seem to confirm that to type check the custom function, you need to add it to the "TableOptions" interface in the configuration file, i.e.:
```
export interface TableOptions<D extends object>
      extends UseFiltersOptions<D>,
        UsePaginationOptions<D>
        {
          updateMyData: (rowIndex: number, columnId: string, value: unknown) => void
        }
```

**Comment by showduhtung** [comment]
> While we do not use that functionality ourselves, a quick check would seem to confirm that to type check the custom function, you need to add it to the "TableOptions" interface in the configuration file, i.e.:
> 
> ```
> export interface TableOptions<D extends object>
>       extends UseFiltersOptions<D>,
>         UsePaginationOptions<D>
>         {
>           updateMyData: (rowIndex: number, columnId: string, value: unknown) => void
>         }
> ```

wow thanks. This was exactly what I was looking for!!

**Comment by tannerlinsley** [comment]
Again, this library does not ship with native types (yet). So use any community types at your own risk.
