### ISSUE TITLE
Fixed header makes the pivot grid unstable.

### ISSUE THREAD

**Issue by ashishdhyani** [tannerlinsley/react-table#271]
## Problem Description
Fixed header makes the pivot grid unstable.

I have make the changes the same way as described at below wiki

[https://github.com/tannerlinsley/react-table/wiki/Fixed-headers-with-scrollable-table-body](url)

It works perfectly well if there is no pivoting on the grid.

But if there is pivoting on the grid, it makes the pivot grid unstable and it messes up the table and it doesnt render properly.

Thanks
Ashish

**Comment by tannerlinsley** [comment]
I'm not sure how to fix it without more info. Can you post a screenshot?

**Comment by ashishdhyani** [comment]
Hi @tannerlinsley,

See attached snapshot. I have done some editing to the snapshot to hide business critical data.

but you can see area highlighted in red.

![image](https://cloud.githubusercontent.com/assets/21311351/26045152/56314586-397b-11e7-88ae-39eda296e456.png)

Thanks
Ashish

**Comment by tannerlinsley** [comment]
I'll look at this asap

**Comment by tannerlinsley** [comment]
This appears to be fixed in the new versions of `6.x.x`
