### ISSUE TITLE
Hosted compiled version?

### ISSUE THREAD

**Issue by aft-luke** [tannerlinsley/react-table#272]
## Problem Description
Currently this library can only (easily) be consumed from npm/yarn + some webpack-type packaging tool. Can we have a compiled version of this lib hosted somewhere, or perhaps simply inside this project? As a clojurescript user, it's a hurdle to incorporate a third party library. It's a much higher hurdle, however,  to consume a library that's both not closure compiler enabled and not build into a javascript artifact, or offered as a prod-ready minified artifact.

**Comment by tannerlinsley** [comment]
You can easily use the vanilla js version that is bundled with each release.  https://github.com/tannerlinsley/react-table#cdn

**Comment by aft-luke** [comment]
My apologies, I overlooked that section of the README. Thanks!
