### ISSUE TITLE
no typescript support for state with plugins

### ISSUE THREAD

**Issue by r3wt** [tannerlinsley/react-table#2743]
**Describe the bug (required)**
the typings for the library are unaware of plugins it would seem, as state type is not augmented with the additional properties provided by the plugins. for example, i am using the `useRowSelect` plugin, but trying to use `selectedRowIds` on state is throwing type error. my temporary work around is to stop destructuring state as shown in the material example, and just then cast state before accessing property, like so:
```ts
const {selectedRowIds} = state as TableInstance<any> & {selectedRowIds:any[]};
```

**Provide an example via Codesandbox! (required)**
i cannot provide codesandbox as the corporate firewall is blocking such websites.

**Steps To Reproduce (required)**

try to use any plugin with `useTable` in a typescript project, and you will see problem

**Expected behavior (Recommended)**
typescript support should actually work. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6] 2017 macbook pro

**Additional context**

**Comment by marwan38** [comment]
https://github.com/tannerlinsley/react-table/issues/2697#issuecomment-685440212

> Have you included a react-table type configuration file in your project, as described by https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table ?
> Specifically, this property is provided by UseRowSelectOptions in interface TableOptions.
> Additionally I suggest removing Record<string, any> from that interface, as it would allow you to input unknown keys without warning.

Basically, read the `README` for the TS declaration.

**Comment by r3wt** [comment]
No i haven't. because there is no mention of that anywhere in your documentation and i'm not a mind reader. but thanks for the help, nonetheless.

**Comment by marwan38** [comment]
Me neither, I had to look through the issues You have a point though, might be handy to be part of the docs. Let's wait for one of the collaborators to see what they think. If not then perhaps I can make a PR to update this repositorys README

The type repo README is usually totally ignored, at least for myself.

**Comment by tannerlinsley** [comment]
To sum up:

- Be kind to one another and follow the code of conduct.
- React Table does not ship with native types. Any use of community types are at your own risk.
