### ISSUE TITLE
JSX element type 'ReactTable' does not have any construct or call signatures

### ISSUE THREAD

**Issue by deepak-terse** [tannerlinsley/react-table#2749]
**Describe the bug (required)**
Not able to use this component in .tsx files. Facing this error - "JSX element type 'ReactTable' does not have any construct or call signatures"

**Provide an example via Codesandbox! (required)**
See the error here - https://codesandbox.io/s/wonderful-feather-t3vjf?file=/src/App.tsx

**Steps To Reproduce (required)**

1. Go to 'https://codesandbox.io/s/wonderful-feather-t3vjf?file=/src/App.tsx'
2. Check ReactTable component under render() function

**Expected behavior (Recommended)**
Expecting the code without errors

**Desktop (please complete the following information):**

- OS: Windows
- Browser chrome
- Version 22

**Comment by tearingItUp786** [comment]
So not a moderator but I will try to answer this. It appears that you're attempting to use the old API of this library in your code sandbox but the project has moved from export a component that you can render to being hooks based. 

For example, your import should look like this:

`import { useTable } from "react-table";`

**Comment by tannerlinsley** [comment]
Correct ☝️
