### ISSUE TITLE
All examples in the documentation fail to render.

### ISSUE THREAD

**Issue by MendelBak** [tannerlinsley/react-table#2763]
**Describe the bug**
If you navigate to the example section in the documentation ([for example](https://react-table.tanstack.com/docs/examples/basic)), all the examples fail to render. Attempting to view the example on CodeSandbox external site also fails with a 404 error. 

**Provide an example via Codesandbox! (required)**
Use a new [react-table codesandbox](https://codesandbox.io/s/m5lxzzpz69) to reproduce the issue.

**Steps To Reproduce**

1. Go to https://react-table.tanstack.com/docs/examples/basic'

**Screenshots**
![image](https://user-images.githubusercontent.com/17897003/95010489-740be480-0632-11eb-9e17-a84b3f440b52.png)

- OS: Ubuntu 20.04
- Browser Brave Browser (built on Chromium)
- Version 1.14.81 Chromium: 85.0.4183.102 (Official Build) (64-bit)

**Comment by tannerlinsley** [comment]
This was an upstream issue with codesandbox.
