### ISSUE TITLE
7.6.0: Weird display when there are a lot of columns

### ISSUE THREAD

**Issue by cedricfarinazzo** [tannerlinsley/react-table#2771]
**Describe the bug (required)**
When there are a lot of columns, when you scroll horizontally, the style of columns on the right is broken: white text on white background color 

**Provide an example via Codesandbox! (required)**
Use a new [react-table codesandbox](https://codesandbox.io/s/m5lxzzpz69) to reproduce the issue.
Soon ... If I have time.

**Steps To Reproduce (required)**

Create a table with more than 15 columns.

**Expected behavior (Recommended)**
Good css.

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Firefox and Chrome

**Comment by Yaroslaww-1** [comment]
Not sure I understand the issue correctly (link to the Codesandbox not working), but adding
```
const { ...other-table-props, totalColumnsWidth } = useTable(...)
```
and
```
style={{ minWidth: totalColumnsWidth }}
```
to both body and header elements (or just to a table root element) solved the issue for me.
Link to the working example: https://codesandbox.io/s/agitated-sunset-sswm0?file=/src/App.js
Before:
<img src="https://user-images.githubusercontent.com/40521835/105709842-f0e30700-5f1e-11eb-9c6e-1690567c8d24.png" width="300" height="300">
After:
<img src="https://user-images.githubusercontent.com/40521835/105709874-fccec900-5f1e-11eb-804d-4c43c797b2ad.png" width="300" height="300">

**Comment by homax** [comment]
Probably I had the same issue or at least similar after one of updates. This helped, thanks.
