### ISSUE TITLE
Is there a way to force column text to break to new line instead of ellipsis(...)

### ISSUE THREAD

**Issue by cbll** [tannerlinsley/react-table#278]
Currently if the content of a cell is larger than the cell itself, the way to see the content is by dragging the cell and increasing its size(which is fine)

However I have some cells with a lot of information in them; I'd rather have it break the line and expand the entire table horizontally to accommodate for it.

Is there a way to do that currently? Reading through the API and examples, I haven't come across it unfortunately.

Thanks!

**Comment by tannerlinsley** [comment]
Disable overflow hidden on '.rt-td' styles

**Comment by cbll** [comment]
Thanks. So I just overwrite that property in a my .css file that I load?

**Comment by tannerlinsley** [comment]
Yep

**Comment by cbll** [comment]
I just tried adding this to the top level css, it didn't change it though:

```
.rt-td{
    overflow: visible;
}
```

**Comment by cbll** [comment]
Ah - I added it to the individual columns I want it to happen to, like this:

```
{
            header: 'Details',
            accessor: 'details',
            minWidth: 150,
            style: {overflow: "visible"},
        }
```

However, it just pushes the bar horizontally and adds scrolling. Is there any way to push the text downwards, vertically, and increasing the height of the column? that would be prettier :)

**Comment by tannerlinsley** [comment]
You would need to put a max Width on the column

**Comment by cbll** [comment]
On the individual columns?

I attempted that; It looks very weird(it will have a horizontal scroll bar per default, and some columns overlap?

```
        const columns = [{
            header: 'Details',
            accessor: 'details',
            style: {overflow: "visible"},
            maxWidth: 200
        },{
            header: 'Severity Level',
            accessor: 'severitylvl',
        },{
            header: 'Time',
            accessor: 'time',
        }, {
            header: 'Source Type',
            accessor: 'srctype',
        }, {
            header: 'Description',
            accessor: 'description',
            style: {overflow: "visible"},
            maxWidth: 350
        }];
```

**Comment by tannerlinsley** [comment]
Oh. You may only need to change the white-space CSS property. That should do the trick

**Comment by tannerlinsley** [comment]
To be more specific, this is the only thing you should need to change (the `!important` is probably not needed, but was in the codepen:
```css
.rt-td {
  white-space: normal !important
}
```
Codepen Example: http://codepen.io/tannerlinsley/pen/PmBKGp?editors=0110
