### ISSUE TITLE
Issue with setAllFilters

### ISSUE THREAD

**Issue by dmitrij-v** [tannerlinsley/react-table#2788]
The situation for reproducing:
1. We have preset columns. Some of the columns can be hidden.
2. We have preset filters. Some of the columns can have filter value as default.

In some cases, we use setAllFilters as a function to set new filters configuration. At that moment we can get the error: "Cannot read property 'filter' of undefined". It connected with https://github.com/tannerlinsley/react-table/blob/master/src/plugin-hooks/useFilters.js#L106

The situation happens when we try to set a filter for a hidden column. If we show the column, it works correctly.

**Comment by fseitun** [comment]
Closing stale issues. Should this be a mistake please open a new issue.
We are triaging issues and getting things up to date.

**Comment by ioannisth** [comment]
I am using react-table 7.7.0 and I am facing the same issue. Sadly, you decided to close this one which essentially renders a fundamental table functionality such as filtering very problematic.
