### ISSUE TITLE
Custom TableComponent is not loading the other components, just TableComponent

### ISSUE THREAD

**Issue by kieronsutton00** [tannerlinsley/react-table#279]
Custom TableComponent does not load all the other components. I understand this is not a bug, or an issue with react-table (I'm new to React - started today). I have tried overriding the TableComponent, so the HTML is of a valid table rather than div's (for compatibility with Bootstrap's tables). However, when I override the TableComponent, none of the other components load apart from a "loading" div, and the TableComponent - which obviously suggests that I've missed something in my custom component, I also tried looking at the [source](https://github.com/tannerlinsley/react-table/blob/master/src/index.js#L782) but i do not have a sufficient understanding of React yet to fully understand what's going on here to make my custom compoment load the other components like in the source.

https://codepen.io/anon/pen/QvBgJg

**Comment by tannerlinsley** [comment]
The default component originates from here:
https://github.com/tannerlinsley/react-table/blob/master/src/defaultProps.js#L168
Which builds a standard through-put component with a class here:
https://github.com/tannerlinsley/react-table/blob/master/src/utils.js#L122
Which results in this component:
 ```javascript
TableComponent: ({children, className, ...rest}) => (
    <div
      className={classnames('rt-table', className)}
      {...rest}
    >
      {children}
    </div>
  )
```
This is a pretty standard pattern.  Its basically a `div` component that takes the props given to it, changes a few small things (in this case, the `className` is decorated with `rt-table`), then applies any other props (via ...rest). So you will probably want to do something like simply change the `div` to `table`:
 ```javascript
TableComponent: ({children, className, ...rest}) => (
    <table
      className={classnames('rt-table', className)}
      {...rest}
    >
      {children}
    </div>
  )
```

**Comment by tannerlinsley** [comment]
You will also need to do the same for any other components you need to override (particularly rows and cells).  Bear in mind though, I don't recommend changing the underlying html components as things will be prone to break (like column flex and column sizing). I'm not familiar enough with bootstrap table styling to know exactly what needs to be done, but give it a try!

**Comment by kieronsutton00** [comment]
@tannerlinsley Cheers, so if I just override every component, they'll automatically be loaded in with each other?

**Comment by tannerlinsley** [comment]
Correct! As long as you render the component with right`className` and `children`, the layout will be handled automagically :)

**Comment by kieronsutton00** [comment]
@tannerlinsley Thank you for the example above, but they're still not working for me. Can you take a quick look and my updated codepen to see if you can spot an amateur mistake I've made?
https://codepen.io/anon/pen/Omwjzx

Thanks!

**Comment by tannerlinsley** [comment]
Oh you were so close!  Just needed to use `this.props` for class syntax. Also, `classnames` is a module that you'd have to import, so I changed it to use a more simple approach.  This still doesn't work fully, since you still need to replace all of the other html elements.  You'll see an error in the console where React enforces that you don't mix non-table elements inside of table elements. Good job and good luck!  Join the slack org if you have more questions :)
