### ISSUE TITLE
Global filter on the formatted cell value

### ISSUE THREAD

**Issue by venkatesh22** [tannerlinsley/react-table#2790]
I'm unable to get the records filtered on the formatted cell values using GlobalFilter
1) format the date column value using Cell 
2) search with the formatted value which is displayed on the column

ex: format the date value while showing it on the table and trying to search with the value that is displaying in the table

<img width="778" alt="Screen Shot 2020-10-21 at 10 40 01 PM" src="https://user-images.githubusercontent.com/3272750/96754735-58a12780-13ef-11eb-9119-193a6383d2ef.png">

an example implementation can be found here
https://codesandbox.io/s/react-table-7-resizing-forked-jxizb

**Comment by freestyle09** [comment]
It's not an issue, you are just wrong. Cell key is only for formatting values that becomes to the table, but accessor is function that you run before your data is moved to the table. 
Run your codesanbox and before remove Cell on Birthday object and add this:
`accessor: (value) => dateFormatter(value.birthday),`

**Comment by venkatesh22** [comment]
> It's not an issue, you are just wrong. Cell key is only for formatting values that becomes to the table, but accessor is function that you run before your data is moved to the table.
> Run your codesanbox and first remove Cell on Birthday object and add this:
> `accessor: (value) => dateFormatter(value.birthday),`

it's working
