### ISSUE TITLE
Unable to extend Column in typescript;

### ISSUE THREAD

**Issue by tar-aldev** [tannerlinsley/react-table#2809]
**Describe the bug (required)**
I see that there is a Column interface exported from react-table types; it has all possible properties the Column has. 
However, I am following [this example ](https://react-table.tanstack.com/docs/examples/data-driven-classes-and-styles)
where I see that styles are added directly to some columns;

However, I am unable to extend the Column definition anyhow, to add styles property;
It looks logical to me to just be able to do this:
```
(Column<UserInfo> & { style: any })[]
```
However after adding this I get typescript errors for all defined columns
>Types of property 'accessor' are incompatible

Trying to extend from Column<D> like this:
```
interface ColumnWithStyles extends Column<UserInfo> {
  style: any;
}

```
 gives
> An interface can only extend an object type or intersection of object types with statically known members.

Columns look like this
```
const columns: (Column<UserInfo> & { style: any })[] = [ // Column comes from @types/react-table
    {
        Header: 'Name',
        accessor: data => {
          return `${data.firstName} ${data.lastName}`;
        }
      },
      {
        Header: 'Email',
        accessor: 'email',
        filter: 'text'
      },
      {
        Header: 'Roles',
        accessor: 'roles',
        Cell: ({ row }: Cell<UserInfo>) => {
          return row.values.roles.length > 0 ? row.values.roles.join(', ') : '-';
        }
      },
      {
        Header: 'Date Joined',
        accessor: data => {
          return data.createdAt ? formatStringToMonthDayYearDate(data.createdAt) : '';
        },
        disableFilters: true,
        style: { verticalAlign: "top" }
      }
    ];
```

**Provide an example via Codesandbox! (required)**
Use a new [react-table codesandbox](https://codesandbox.io/s/m5lxzzpz69) to reproduce the issue.

**Steps To Reproduce (required)**

1. Create react-table component with typescript
2. try to add styles to header or column
3. See error

**Expected behavior (Recommended)**
Would be good to have a guide somewhere or just be able to intuitively extend the Column or intersect it.
**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOS
- Browser [e.g. chrome, safari] chrome
- Version [e.g. 22] latest

**Smartphone (please complete the following information):**

**Additional context**
"@types/react-table": "^7.0.24",
"react-table": "^7.6.0",

**Comment by tar-aldev** [comment]
I am extremely sorry, I just made a mistake in type declaration;

It should be 
```
type EnhancedColumn = Column<UserInfo> & { style?: ..., headerStyle?: .... } // non required
```
instead of 
```
type EnhancedColumn = Column<UserInfo> & { style: ..., headerStyle: .... } // this will error
```
although the error is quite misleading

**Comment by wegry** [comment]
@tar-aldev You might consider using `Partial` if everything in the additional properties is optional. It helps me avoid errors like this.

https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype
