### ISSUE TITLE
Problem with aggregate function

### ISSUE THREAD

**Issue by Marfa93** [tannerlinsley/react-table#282]
Hello !
I am using the pivot feature and I have a problem when I want to access to the value of an hidden column in the aggregated function.
It seems the hidden column is not considered as a part of the table.

Here is a codepen : https://codepen.io/marfa93/pen/wdEKVo

## System Information
* **Browser & Browser Version:** Vivaldi 1.9.818.49
* **Node Version:** 6.10.3
* **OS Version:** Ubuntu 16.04 LTS
* **NPM Version:** 3.10.10

**Comment by tannerlinsley** [comment]
Yeah, this seems like a bug of sorts.  I'm not sure how to handle it though.  If a column is hidden, it would be nice to not have to perform calculations on it, but at the same time I can see your use case.  @aaronschwartz thoughts on this?

**Comment by mikedevita** [comment]
maybe add a prop to include it in the calculations if its hidden?

**Comment by aaronschwartz** [comment]
I was trying to play around with it until CodePen went down... it looked like technically the data still existed in the _subRows key. You would have to do the aggregation yourself though instead of relying on the column aggregation function.

**Comment by aaronschwartz** [comment]
Maybe something like this as a workaround for now:
https://codepen.io/aaronschwartz/pen/ybwRrp?editors=0010

**Comment by Marfa93** [comment]
Hi !

Thanks a lot for the solution, it works !
In some case I have more than two pivot columns, so I made this : https://codepen.io/marfa93/pen/WjWRQO?editors=0010

The self-made aggregation function is recursive.

PS : Where/How can I pay you a beer ? ;)

**Comment by tannerlinsley** [comment]
There is a donate button on the readme that would facilitate that ;)

**Comment by tannerlinsley** [comment]
@Marfa93 no worries :) Go buy yourself a Coke and celebrate!
