### ISSUE TITLE
Don't throw an error when render doesn't exist

### ISSUE THREAD

**Issue by velocityzen** [tannerlinsley/react-table#2829]
Throwing error is limiting usage of custom renderers here:
https://github.com/tannerlinsley/react-table/blob/3d76ffe38dc2de6148d6ae6fb2816dd02ae980b4/src/publicUtils.js#L205

Would it be better to return `null` instead? It will make it more flexible.

**Comment by datner** [comment]
There is no context given at all. But I do agree with the current implementation. It is very odd for a `Render` method to not return or return `undefined`. Even logical component that don't render at all return null or empty fragments for brevity-sake. I'd consider it an anti-pattern to write a component like this:

```tsx
function GooglePixelLikeComponent(props) {
  useEffect(() => {
    fancyUserTracking(props.something)
  }, [props.something])
}


function App() {
  return (
    <div>
      <GooglePixleLikeComponent something={"user"} />
      <SiteContent />
    <div>
  )
}
```

besides, a nullish rendered table cell is really exotic, __maybe__ once-in-a-career occurrence, so a void rendered table cell? Can you please elaborate your use case?
Or is this just academic deliberations?

**Comment by velocityzen** [comment]
I added custom `Placeholder` renderer to **some** of the columns and then in my Body Cell component:

```js
  if (isPlaceholder) {
    const hasPlaceholderRenderer = !!cell.column.Placeholder;
    return <>{hasPlaceholderRenderer ? cell.render("Placeholder") : null}</>;
  }
```

But if `render` method would just return null if there is no renderer, it would be so much simplier:

```js
  if (isPlaceholder) {
    return cell.render("Placeholder");
  }
```

**Comment by datner** [comment]
oh, now I understand what you're talking about.

The solution is to add a `Placeholder` renderer to the `defaultColumns` object. Theres no reason why `cell.render` should be extended like that

**Comment by velocityzen** [comment]
Hmm, but I don't need `Placeholder` renderer available for every column. Only to specific column, that's why I put in the columns definition in a first place. If you think returning `null` from `render` is not safe I'm okay to live with the check. Maybe you can add nice renderer check method :)

**Comment by datner** [comment]
returning null is safe, I mean add a default Placeholder renderer that returns null, and override it for columns that actually want to render a placeholder

**Comment by velocityzen** [comment]
ah. that will work. thank you!
