### ISSUE TITLE
Render Index Column

### ISSUE THREAD

**Issue by helsont** [tannerlinsley/react-table#284]
I'd like to have a column display the nth row that the current row is on. 

The docs for the section "Custom Cell, Header and Footer Rendering" seem to have the relevant information. But when I specify a `Cell` key in a column, it doesn't use the custom renderer. 

I even copied and pasted the code straight for the example and it didn't render the custom function. (I overwrote `row.value` with a hardcoded value.)

**Comment by aaronschwartz** [comment]
What version are you using? `Cell` replaced the `render` method as of version 6.x.x.

**Comment by helsont** [comment]
5.6.0

**Comment by aaronschwartz** [comment]
Take a look at the readme for 5.x.x and see if that helps: 
https://github.com/tannerlinsley/react-table/blob/ad7d31cd3978eb45da7c6194dbab93c1e9a8594d/README.md

**Comment by helsont** [comment]
Thanks @aaronschwartz 

Here's what I ended up doing:

```
{
  header: '#',
  columns: [{
    accessor: 'progress',
    render: row => {
      return <div>{row.index}</div>;
    },
    width: 40,
    hideFilter: true
  }]
},
```

However, the problem with this is that it's not aware of the pagination. So when I click next page, it starts from 0 again. 

If there's a better solution, would love to know... I guess keep track of the onPageChange and store in the state if nothing else.

**Comment by aaronschwartz** [comment]
Hmm. I don't remember if that info is available in that version. In the newest version I believe `index` gives you what you're wanting.
If you don't want to upgrade I think the easiest way is to map over your data and add the index to the data object before passing it to the table.
