### ISSUE TITLE
peerDependency warning when used with react@17

### ISSUE THREAD

**Issue by AviVahl** [tannerlinsley/react-table#2846]
**Describe the bug (required)**
`react-table`'s peerDependency range does not cover newly released `react@17`.

**Provide an example via Codesandbox! (required)**
Irrelevant for this issue.

**Steps To Reproduce (required)**

```
mkdir react-table-r17
cd react-table-r17
npm init -y
npm i react react-dom react-table
```
See warning: `npm WARN react-table@7.6.1 requires a peer of react@^16.8.3 but none is installed. You must install peer dependencies yourself.`

**Expected behavior (Recommended)**
Allow react@17 in peerDep range.

**Additional context**
- Node 14.15.0 (LTS) and npm 6.14.8

**Comment by scleikas** [comment]
Hi, thanks for all the work on this great library. I was wondering if there's a chance of updating this peer dependency to React 17 on the (admittedly obsolete) react-table 6.x version. There's a project that would require a lot of rework to upgrade from 6, and if the 6.x branch is compatible with React 17, just bumping the peer dependency requirement would solve this issue.

I guess the question is, are you aware of something in the 6.x version that would prevent updating the peer dependency?
