### ISSUE TITLE
Design Issues since 6.0.3

### ISSUE THREAD

**Issue by IDragonfire** [tannerlinsley/react-table#285]
## Problem Description
With `6.0.2` all worked as expected:
![image](https://cloud.githubusercontent.com/assets/1217999/26265231/8f8794c6-3ce0-11e7-83fa-096b2699461f.png)

With `6.0.3` the table header and body is collaped:
![image](https://cloud.githubusercontent.com/assets/1217999/26265298/e4437e3a-3ce0-11e7-9718-2e200e79d4bf.png)
(This is the whole table)

I added this to my style to fix this:
```css
.ReactTable {
  display: inherit;
}
```

Now with `6.0.4`  and the hotfix from above scrollbars are visible:
![image](https://cloud.githubusercontent.com/assets/1217999/26265349/1dd03c56-3ce1-11e7-9458-bdaa486d8d38.png)

I imported your `css` over
`import 'react-table/react-table.css';`

What did I make wrong?
Or is the `6.x.x` branch not stable?

## Hotfix
Currently I fix my `react-table` version  to `6.0.2`

**Comment by tannerlinsley** [comment]
It should be stable, but it looks like you're finding some bugs.  We're still working this out. The first find you made is actually intended. We'll let you know when these issues are fixed.

**Comment by IDragonfire** [comment]
Maybe you should mention this in the documentation ;)

**Comment by tannerlinsley** [comment]
The fix for the scrollbars is out as of 5 minutes ago.

**Comment by IDragonfire** [comment]
Looks good with `6.0.5` and the manual style entry
```css
.ReactTable {
  display: inherit;
}
```

**Comment by cdtinney** [comment]
I'm seeing the collapsed header since `6.0.0` and unable to fix it via setting `display: inherit`.

**Comment by tannerlinsley** [comment]
.ReactTable's display needs to be 'flex' (or just left alone).  You can alter any styles other than these without affecting the table's core display:
```css
    position: relative;
    display: flex;
    flex-direction: column;
```
