### ISSUE TITLE
Accessibility: Redundant ARIA attribute - role

### ISSUE THREAD

**Issue by 1ak31sha** [tannerlinsley/react-table#2862]
**Describe the bug (required)**
The ARIA roles used in the react table are redundant and not needed as the native HTML tags for tables are already well supported across all user agents.

**Provide an example via Codesandbox! (required)**
Use a new [react-table codesandbox](https://codesandbox.io/s/m5lxzzpz69) to reproduce the issue.
https://hewc9.csb.app/

**Steps To Reproduce (required)**

1. inspect the DOM, check the table and tr elements created by react-table
2. notice that they have redundant 'role' attributes.

**Expected behavior (Recommended)**
Reccomend to remove the redundant attribute, unless there is some other reason its there that we are not aware of.

**Screenshots**
<img width="321" alt="Screen Shot 2020-11-18 at 11 16 46 AM" src="https://user-images.githubusercontent.com/15619911/99557330-906ca200-2990-11eb-8523-a18cddaba008.png">

**Desktop (please complete the following information):**

- OS: macOS
- Browser :all browsers
- Version: latest

**Additional context**

@bly1978

**Comment by Bly1978** [comment]
Thanks for helping me get this written up @1ak31sha

**Comment by tannerlinsley** [comment]
What if the cells are rendered with divs?

**Comment by 1ak31sha** [comment]
@tannerlinsley do you mean render divs as children of the td? That is fine AFAIK. @Bly1978 do you have any comment? I would think we can render whatever we want inside a cell, as long as its a td, its taken care of accessibility-wise.

**Comment by tannerlinsley** [comment]
No no, I’m talking about tables that are not made out of table elements like the flex box or grid structure table layouts. This would then require the aria attributes.

**Comment by 1ak31sha** [comment]
i guess you are right then. i didn't realize people used react-table that way. thanks!

**Comment by borm** [comment]
@1ak31sha 
so, how to remove all `role` attribute from each tag inside table and from table also?

**Comment by 1ak31sha** [comment]
> @1ak31sha
> so, how to remove all `role` attribute from each tag inside table and from table also?

you could use a document.querySelector to get the elements and then override the value

**Comment by ben8jam** [comment]
Feel like we skirted the issue here. Redundant Aria roles on HTML elements fails accessibility testing. The answer isn't "well, it could be a div". An accessibility testing department will not allow the table to pass. Is there a flag that can be added to exclude role being added to tables by choice?

**Comment by 1ak31sha** [comment]
> Feel like we skirted the issue here. Redundant Aria roles on HTML elements fails accessibility testing. The answer isn't "well, it could be a div". An accessibility testing department will not allow the table to pass. Is there a flag that can be added to exclude role being added to tables by choice?
> 
> Well to get around this - I simply removed all the references to {...getXYZ props} from each of the table elements. The only one in there for me was row="xxx"

perhaps you'd like to reopen the issue

**Comment by simzikov** [comment]
This is still an issue in 2021. Pages built with react-table fail to pass the HTML validation test. Instead of completely removing the { ...getXYZ props} from each of the table elements, I solved this by setting their role attribute to false, e.g.:

```
<tbody {...getTableBodyProps({ role: false })}> ... </tbody>
``
