### ISSUE TITLE
[QUESTION] Suggestions for rendering Popup from Semantic UI React

### ISSUE THREAD

**Issue by vaidsu** [tannerlinsley/react-table#287]
## Problem Description

* Consider I wish to color a cell as red/green/yellow depending on the threat level. On plain React Semantic UI [table](https://react.semantic-ui.com/collections/table) it will be done as shown:

```jsx
<Popup
       trigger={
            <Table.Cell style={highlight_threat}>
                {utils.getThreatIcon(i.threat)}
            </Table.Cell>
      }
       inverted={true}
       position="left center"
       size="mini"
>
     <ThreatPopup threat={i.threat}/>
</Popup>
```

* Semantic UI React binding requires to pass the rendering cell as a trigger 

* Now in the case of React Table we have handle to render the Cell and override, so I used the following:

```jsx
const columns = [
            {
                header: '',
                accessor: 'threat',
                render: props => {
                    const highlight_threat = utils.getThreatStyle(props.value);
                    return (
                        <Popup
                            {/* This needs to contain the Table Cell or TdComponent if I am right */}
                            trigger={
                                <span style={highlight_threat}>
                                    {utils.getThreatIcon(props.value)}
                                </span>
                            }
                            inverted={true}
                            position="left center"
                            size="mini"
                            style={highlight_threat}
                        >
                            <ThreatPopup threat={props.value}/>
                        </Popup>
                    )
                }
            },
]
```
Now this one obviously will not work, since I am passing the span and not the cell itself, that colors the checkmark icon but not the actual cel.. 

* Now how do I do this? Is there a way I can pass the "this" component somehow. I tried that but the this is only bound to my parent component. 

I am trying to play with the source code, any help is greatly appreciated. 

VERSION: react-table@5.3.2

**Comment by tannerlinsley** [comment]
I'm not sure what Popup is, but this seems like it should work based on your description.  Anything returned in `render` (in versions less than 6) will render inside of the table cell (you do not need to create the table cell yourself.

**Comment by vaidsu** [comment]
Thanks for your response @tannerlinsley 
Sorry to continue the conversation in a closed issue.

> I'm not sure what Popup is

```<Popup />``` is an UI component in [Sementic UI](https://semantic-ui.com/) and I am using the [React binding](https://github.com/Semantic-Org/Semantic-UI-React) for it. Essentially it expects to send the actual component within its prop. Now, I need to send the actual cell as a component into the Popup. 

Avoiding any specific discussion about Popup, and to make it more generic:

**Here is the doubt:**
I can understand that we can override ``render`` method or ``Cell`` in the latest version to override the Cell render, but it doesn't let me to push a background color for that cell itself right? 

Since a render, is only providing me access for the <div> within the cell, I am not able to set a background color for that cell. 

Hope I am clear now. **So the question is, is there a way to reference the Cell itself within the render/Cell function?** 

Thanks again.

**Comment by tannerlinsley** [comment]
I think what may solve your problem is using the `getProps` callback in
your column definition.  In that callback, you are provided all available
information about the cell, row, data, and column, and you can return an
*object* of props to be placed on the cell container. In your case you
could easily do: `getProps: () => ({ style: { backgroundColor: ‘red’ } })`

**Comment by vaidsu** [comment]
This is excellent.

Thanks a lot for your quick response, let me try it out and keep you posted.

**Comment by vaidsu** [comment]
@tannerlinsley  Thanks for your suggestion, using TdProps helped. 

Thanks again
