### ISSUE TITLE
Fix displayName for template components

### ISSUE THREAD

**Issue by atkawa7** [tannerlinsley/react-table#289]
This is not a problem but a question. How do you get the component names to show in devtools?

![image](https://cloud.githubusercontent.com/assets/5673828/26367828/cb93fbbe-3fa4-11e7-8ad8-6abf822f8198.png)

**Comment by mikedevita** [comment]
You know this is a good question, I was experiencing the same thing @tannerlinsley any thoughts?

**Comment by tannerlinsley** [comment]
Yeah, this just need to be updated in the [`makeTemplateComponent`](https://github.com/tannerlinsley/react-table/blob/master/src/utils.js#L123) function that is used to create the generic default components.  It would need to be passed a display name which would either need to be used as the component's `displayName` static property.
