### ISSUE TITLE
No styling out of the box

### ISSUE THREAD

**Issue by hect1c** [tannerlinsley/react-table#29]
Hey,

Thanks for this component btw.

I'm sure it's something I'm missing, but when I attempt to use this component out of the box with sample data within my app, there doesn't seem to be any sort of initial styling taking place. Should I be referencing the react-table.css file in my app ? I would assume I wouldn't need to and this would be handled accordingly and I could just override any and all existing element styling.

**Comment by tannerlinsley** [comment]
You do need to include the CSS file. The styles in it have been designed to
be overridden easily but give the table a decent look out of the box.

**Comment by hect1c** [comment]
Ah I see, got it thanks a lot.
