### ISSUE TITLE
PageSize issue when changing from not manual to manual

### ISSUE THREAD

**Issue by alebrozzoSP** [tannerlinsley/react-table#292]
## Problem Description
I am using the component with the ability to change from full client side to server side by setting the manual property to false/true, depending on some conditions. In this case it's when the data has to be retrieved from a manual date-range picker (I want server side paging and sorting because data can be too much to bring to the client) vs retrieved from a drop down to indicate a specific short date range (I want client side sorting and paging here because I know data volume won't be much)

It works kind of ok, except that I have a problem with the page size. When using client side then I switch to server side, I think there is no way to get the currently selected page size, hence the code uses the original size (which is in my parent control's state)

Also, as I set the ```pages``` property because I have the manual option, even if the table is on client side option it still uses the property, and does not handle paging properly (it is not automatically set to the correct number when changing the page size from the drop down)

## Code Snippet
this is how I use the table, wrapped on a custom control I made
```
        <ReactTable
            manual={!fullClientSide}
            columns={columns}
            data={reportData}
            pages={totalPageCount}
            defaultPageSize={defaultPageSize}
            onChange={fullClientSide ? () => { } : onDataRequest}
        />
```
Sorry, I don't think I can create a snippet that goes server side to fetch data

## Steps to Reproduce
_Invalid page size when gong to manual_
1. Page start with a client side managed table
2. User changes the page size (say, from 20 to 5)
3. User selects a manual date range -> table enters server side (manual) mode
at this point the data is fetched but using a page size of 20 in stead of 5, however the page size selector says that the page size is 5. If I don't have a default

_Invalid pages value_
1. Page start with a client side managed table
2. User changes the page size (say, from 20 to 5)
at this point the pages count does not change, hence you cannot properly paginate
This second issue I solved by modifying the snippet above to render different instances of the table depending on ```fullClientSide```, using the ternary operator, but it would be great if the ```manual``` option caused the logic to ignore all server side code, like ```pages``` property or ```onChange```, which I was able to hack as seen on the snippet.

## System Information
* **Browser & Browser Version: Chrome**
* **OS Version: Windows 10**
* react-table v5.4.1

**Comment by tannerlinsley** [comment]
- Please first upgrade to the latest version of `6.x.x`.
- Read through the Changelog for this version and adjust any parts of your implementation that are affected by the changes.
- Attempt to reproduce again and update this issue with your findings.

**Comment by tannerlinsley** [comment]
Closing for triage. Please reopen if you are still experiencing the issue after upgrading.

**Comment by alebrozzoSP** [comment]
Thanks, I'll try what you said when I find the time!
