### ISSUE TITLE
Checkbox not correctly selected 

### ISSUE THREAD

**Issue by nitishnivedan** [tannerlinsley/react-table#2921]
Hello,

in react table , I have 4 rows and i have checked the first row checkbox.

 now if i add a new row to top of 4 rows which were already present. Then the result is new row (which is at top now) checkbox is selected.

It should be 2nd row that is selected (instead of the first).

react table version: 7.6.2

some piece of code I am giving below:-
---------
index.js
.......
hooks.visibleColumns.push((columns) => [
        {
          id: "selection",
          Header: ({ getToggleAllPageRowsSelectedProps }) => (
            <div>
              <Check {...getToggleAllPageRowsSelectedProps()} />
            </div>
          ),
          Cell: ({ row }) => {
           // console.log(row,'RA');
            return(

            <div>
              <Check {...row.getToggleRowSelectedProps()} disabled={row.original.DisableCheckbox === "1"}/>
            </div>
          )},
.......

-------------------
Check.js 

import React from "react";

 export const Check = React.forwardRef(({ indeterminate, ...rest }, ref) => {
  const defaultRef = React.useRef();
  const resolvedRef = ref || defaultRef;

  React.useEffect(() => {
    resolvedRef.current.indeterminate = indeterminate;
  }, [resolvedRef, indeterminate]);

  return (
    <>
      <input type="checkbox" ref={resolvedRef} {...rest} />
    </>
  )
})

@tannerlinsley  -please help. would really appreciate. thanks in advance.

**Comment by gargroh** [comment]
use getRowById method on instance

**Comment by nitishnivedan** [comment]
@gargroh - can u write some pseudo code or refer me some documentation if this is feasible. thanks in advance

**Comment by gargroh** [comment]
`getRowId` at https://react-table-omega.vercel.app/docs/api/useTable#table-options can help you assigning ids to each row, which internally react-table use for maintaining selectable row. 

In your case, if you are not providing this method then react-table uses row index, so on addition of row on top, changes selected row to the newly added one.

**Comment by nitishnivedan** [comment]
thank you @gargroh, was able to achieve it with your suggestion.

**Comment by nitishnivedan** [comment]
@gargroh - is there any way to reset all the checkbox selected by clicking on a button somewhere outside the table.
