### ISSUE TITLE
Make column widths dependent on entry widths

### ISSUE THREAD

**Issue by blacktemplar** [tannerlinsley/react-table#297]
## Feature Request
I used before other table components which had a feature like this and I was wondering if it is possible to adjust the column widths depending on the maximal width of all its rows.

So at the moment the column widths are evenly distributed, except if minimum or maximum width are used. What I would like is something as follows.

Lets say we have n columns and the total table has a width of W and lets say the cells of each column i have a maximum width of w_i and let W_real be the sum of all w_i. Then the displayed with of a column i should be something like w_i + (W - W_real) * w_i / W_real. So each column should get his needes space + the rest of the space is distributed relative to the needed space (if W_real larger than W the formula above would result in that each column gets reduced from its needed space by the same relative amount).

I hope you understand what I mean.

**Comment by tannerlinsley** [comment]
Technically you would be able to implement this on your own, but it would require some very intricate measuring. Any table that can dynamically size its columns to the content inside them uses a cell content measurer of sorts.  React Table does not come with this, so out of the box you will need to implement some way of measuring each columns content for each row. You would need to do this immediately before render (by rendering it invisibly) or immediately after the first render (you may get some FOUC). Then you would be able to pipe your ratio'd measurements into the width properties of their respective columns.

This kind of functionality is very advanced, and I would heavily consider finding a different way to solve this problem. BUT, if you absolutely want to use this method, the way I have described above should *theoretically* work.

Closing this issue as it is a very advanced use case that falls under an opinionated implementation. If you would like to continue discussing the topic, please use our [Slack Organization](https://react-chat-signup.herokuapp.com/).
