### ISSUE TITLE
Extra table rows

### ISSUE THREAD

**Issue by hect1c** [tannerlinsley/react-table#30]
Hey,

When I create the table extra rows seem to be created, yet I only have 4 records in my global variable. 

` handleAssignedBookings() {
        //get bookings
        let data,
            columns,
            options = {};

        data = DATA.bookings.map( function(items) {
            if( items.status != 'pending' ) {
                return items;
            }
        });

        //get columns
        columns = [
            {
                header: 'Name',
                accessor: 'driver.firstName',
            },
            {
                header: 'Pick-up Date/Time',
                accessor: 'pickUp.dateTime',
            },
            {
                header: 'From',
                accessor: 'from.location',
            },
            {
                header: 'To',
                accessor: 'to.location',
            },
            {
                header: 'Status',
                accessor: 'status'
            }
        ];

        //set table config options
        //https://github.com/tannerlinsley/react-table#props
        options = {
            showPageSizeOptions: false,
            showPageJump: false,
            showPagination: false
        }

        return {
            data: data,
            columns: columns,
            options: options
        }
    }`

This is one of me methods that I pass to create the table. I've also attached an image ![localhost](https://cloud.githubusercontent.com/assets/1482519/22076397/c6488b02-dda7-11e6-9034-2690c05dae49.png)

Thanks

**Comment by hect1c** [comment]
It seems I need to explicitly set minRows in my options. Thought there would be a default ?

**Comment by tannerlinsley** [comment]
It uses minRows or pageSize. Whichever is set
