### ISSUE TITLE
Responsive columns and bootstrap hidden-* class

### ISSUE THREAD

**Issue by pinkynrg** [tannerlinsley/react-table#300]
what is the rationale of react-table for responsiveness? I will need show tables on phones as well so I was wondering if it is meant to be heavily customized in order to look good on phones or there are known ways to make it look good with little effort? 

I see there is a hide property for columns. I could use that in order to show hide certain columns at a certain size of the screen but maybe there was a more forward way to do it?

**Comment by vaidsu** [comment]
@pinkynrg This was asked in #98  and the response is https://github.com/tannerlinsley/react-table/issues/98#issuecomment-300896281 

I am using plain strict widths to make it overflow scrollable. It could be naive, but works for all screens without shrinking the font sizes. 

Hope this answers.

**Comment by pinkynrg** [comment]
I ended up using "hidden-[xs/sm/md/...]" bootstrap classes. If I find a better solution i will let you know.

**Comment by pinkynrg** [comment]
The above method is the same one I used in the past too. Would it be useful though to have beside the className and the headerClassName some sort of commonClass name for both the header and the column itself? It would be easier to avoid boilerplates of css when you need to write css for both head and column.

**Comment by vaidsu** [comment]
@pinkynrg 
> It would nice to avoid duplicated css

Not sure I understand the duplication problem, all I did is to wrap the table around a responsive wrapper with a bunch of media queries. 
I am not an expert, but it worked on 5 devices with the users feedback, it looks good. 

The requirement for me is to not stack the table in most cases, to avoid users to scroll a lot and loose context. So, making scrollable left-right looks okay for the requirement.

**Comment by tannerlinsley** [comment]
This falls heavily into various strategies for implementation, so we're going to close this issue and continue this discussion on the [slack channel](https://react-chat-signup.herokuapp.com/).
