### ISSUE TITLE
Support for nested header groups

### ISSUE THREAD

**Issue by theCmaker** [tannerlinsley/react-table#302]
## Problem Description
It seems nested header groups are not supported. When I try to make a header group from two others, these groups are used as normal columns and their `columns` property is ignored so the table is blank.

Is there a way to make it work?

## Codepen
https://codepen.io/anon/pen/OmYYyB?editors=0010

## Steps to Reproduce
No step, just have a look at the `columns` declaration in the codepen sample.

**Comment by tannerlinsley** [comment]
Nested Header Groups are not currently supported.  We will keep this in mind for future major releases. Thanks!

**Comment by theCmaker** [comment]
Thank you for your reply and for sharing this awesome react-table.
