### ISSUE TITLE
Exhaustive dependency warning when using useControlledState

### ISSUE THREAD

**Issue by WaqqarSuleman** [tannerlinsley/react-table#3025]
Hi,

The following is a portion of my code:

```
const {sort}=props;
.....
useControlledState: state => useMemo(() => ({ ...state, sortBy: sort }), [state, sort]),

```
I get the following es-lint warning:
`React Hook useMemo has an unnecessary dependency: 'sort'. Either exclude it or remove the dependency array. Outer scope values like 'sort' aren't valid dependencies because mutating them doesn't re-render the component react-hooks/exhaustive-deps`

If I remove the **sort** as a dependency of useMemo() then the table state does not update when the **sort** coming from the **parent** component changes as expected. How do I get rid of this warning and achieve my goal?
Thanks.

**Comment by cention-sany** [comment]
```
// eslint-disable-next-line react-hooks/exhaustive-deps
useControlledState: state => useMemo(() => ({ ...state, sortBy: sort }), [state, sort]),
```
Guess it should be fine to avoid the warning since doc mentioned `This hook function is run on every render and allows you an opportunity to override or change the final table state in a safe way.`, thus useControlledState will be affected by the props pass in.
