### ISSUE TITLE
[Question] How to highlight selected row?

### ISSUE THREAD

**Issue by sportity** [tannerlinsley/react-table#303]
Hey, first of all, thanks for an awesome lib - it's probably one of the well designed components I've seen so far.
I'm trying to make a simple task now - highlight the row when it's selected (simple table, no expandables, no multiselection, etc). Similar to how '-highlight' class highlights row on hover, but for the click (I'm handling the state of selected rows in parent component).

In docs I've found a way to track the click event:
```
  getTdProps={(state, rowInfo, column, instance) => {
                                return {
                                    onClick: e => {
                                        console.log(rowInfo);
                                    }
                                }
                            }}
```
but seems that rowInfo is immutable and there should be another way to access the row and modify some prop or set className explicitly.

Anyway, it should be very common feature, and probably very obvious solution, but I can't find any.
Can anyone post and example how to properly do this?

Thanks in advance for help.

**Comment by vaidsu** [comment]
@sportity I am not an expert, I was trying experiment between getTrProps and getTrGroupProps.

> If you are okay to use jQuery in React

I tried to get the current target onClick which gave me the Td, finding the closest Tr and applying the background helped. 

Unless there is a direct method, which I am looking forward to find, this method works.

Let me know what you find and please share a better way if you find.

**Comment by aaronschwartz** [comment]
You are on the right track. You need to track the highlighted row somewhere in your state and then you can add the style to the row if it matches the row you have saved.
Here is an example:
https://codepen.io/aaronschwartz/pen/VbJerK?editors=0010

**Comment by sportity** [comment]
@vaidsu @aaronschwartz thank you! That works.

**Comment by dmr** [comment]
Thank you for documenting this.

This could be in the documentation, what do you think?
Maybe in a "best practice" section.
