### ISSUE TITLE
React table is getting sorted on filter

### ISSUE THREAD

**Issue by souviiik** [tannerlinsley/react-table#3030]
**Describe the bug (required)**
I am creating a grid for my project where I need to implement column filtering. I have done it mostly, but facing an issue, that is whenever I click on the filter input box for ID column that column gets sorted. I have tried using e.stopPropagation() but that is not working.

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/qc8in

**Steps To Reproduce (required)**

1. Go to 'https://qc8in.csb.app/'
2. Click on 'Textbox under Sl# column to enter a filter value'
3. See that the column sorting icon changes and the column is sorted.

**Expected behavior (Recommended)**
Column should not sort on click inside text box or, interacting with any other filter type.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win
- Browser Chrome
- Version Version 79.0.3945.79 (Official Build) (32-bit)

**Additional context**

**Comment by souviiik** [comment]
I implemented something wrong.

**Comment by NLeRoy917** [comment]
I have this issue too, what did you incorrectly implement?

**Comment by souviiik** [comment]
> I have this issue too, what did you incorrectly implement?

Please get the solution here - https://stackoverflow.com/questions/65937241/react-table-is-getting-sorted-on-filter

**Comment by NLeRoy917** [comment]
Awesome. That helped a lot - I had to tweak my solution a bit, but that was what I needed to point me in the right direction. I moved `column.getSortByToggleProps()` into it's own div that only surrounds the column header render.

**From this:**

```jsx
              <thead>
                {headerGroups.map(headerGroup => (
                  <tr {...headerGroup.getHeaderGroupProps()}>
                    {headerGroup.headers.map(column => (
                      <th
                        {...column.getHeaderProps(column.getSortByToggleProps())} // <---- this is what I changed
                      >
                        {column.render('Header')}
                        /* .... custom stuff here */
                      </th>
                    ))}
                  </tr>
                ))}
              </thead>
```

**To this:**
```jsx
              <thead>
                {headerGroups.map(headerGroup => (
                  <tr {...headerGroup.getHeaderGroupProps()}>
                    {headerGroup.headers.map(column => (
                      <th
                        {...column.getHeaderProps()} // <---- remove column.getSortByToggleProps()
                      >
                     <div {...column.getSortByToggleProps()}> // <---- Add column.getSortByToggleProps()
                        {column.render('Header')}
                     </div>
                        /* .... custom stuff here */
                      </th>
                    ))}
                  </tr>
                ))}
              </thead>
```
