### ISSUE TITLE
filters don't work properly if autoResetPage is false

### ISSUE THREAD

**Issue by violabg** [tannerlinsley/react-table#3035]
**Describe the bug (required)**
filters don't work properly if autoResetPage is false

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/kitchen-sink

**change** autoResetPage to false _(line 308)_

**Steps To Reproduce (required)**

1. type language on firstName
2. see the results
3. reset filter
4. go to second page
5. type language on firstName again
6. no results found

**Expected behavior (Recommended)**
filters should work in all pages, with autoResetPage set to false only works correctly on the first page

 "react": "^17.0.1",
 "react-dom": "^17.0.1",
 "react-table": "^7.6.3",

**Comment by bsubba** [comment]
I see, the problem is, there are no data to show in page 2. If you navigate back to page 1, it will show data. So I would suggest to do `autoResetPage=true` if a page has no data.

**Comment by violabg** [comment]
Thanks, got it.
I solved by using this approach 
https://react-table.tanstack.com/docs/faq#how-do-i-stop-my-table-state-from-automatically-resetting-when-my-data-changes

**Comment by junagao** [comment]
Hi, I'm having the same issue. But in my case, I need the autoResetPage=false because when I update the data I need it to stay on the same page. Is there a way to set page to the first one only when using the filters?

**Comment by adityaayare** [comment]
Hi, thanks for the great library. I am facing the same issue as @junagao. Is there any workaround to this?

**Comment by KonstantinaD** [comment]
Hi,
I also have autoResetPage=false and am doing this to go to page 1 when the filtered results change and their number (rows.length) goes below the current page size.

**Table component**
```
useEffect(() => {
    if (rows.length < pageSize) {
      gotoPage(0)
    }
  }, [rows.length, pageSize, gotoPage])
```

**Comment by prakashnaikwadiSP** [comment]
This might help you @adityaayare https://github.com/TanStack/table/blob/main/docs/faq.md
