### ISSUE TITLE
Better support for flex-box-impaired browsers

### ISSUE THREAD

**Issue by Lilmortal** [tannerlinsley/react-table#304]
## Problem Description
This is not supported in IE11.

Can we add support for this? Thanks.

**Comment by hermith** [comment]
It seems one of the more recent versions broke the table in IE11 (we had issues in mobile Safari on iOS as well). There are some issues with `display` flex on .ReactTable. Overriding it to `display: block` will make it work, but not sure if this causes any issues with other functionality (like the loading element).

**Comment by tannerlinsley** [comment]
Maybe we could try and get a browserstack example of this so we can reproduce the errors that need to be fixed? https://www.browserstack.com/

**Comment by mikedevita** [comment]
>It seems one of the more recent versions broke the table in IE11 (we had issues in mobile Safari on iOS as well). There are some issues with display flex on .ReactTable. Overriding it to display: block will make it work, but not sure if this causes any issues with other functionality (like the loading element).

@hermith that is because flexbox isn't 100% supported in IE11. see [here](https://caniuse.com/#feat=flexbox)

**Comment by aaronschwartz** [comment]
@Lilmortal Can you provide more information on what isn't working. Is it a purely CSS issue? There may be some ES6 functions used that may need to be polyfilled in IE11. Are you getting any console errors?

**Comment by Lilmortal** [comment]
Hi @aaronschwartz, it is purely a CSS issue. The table is not displaying at all, but the "Previous" and "Next" button shows up. There are no console errors. 

Here is what it looked like on IE11, ignore that "Refine my search" button. I reduced my browser width that's why the components looked jumbled up; but the main point is the actual table is not there.

![image](https://cloud.githubusercontent.com/assets/10085070/26606309/8ced50bc-45e5-11e7-96f4-ae41aad0bc43.png)

**Comment by Lilmortal** [comment]
But @hermith you are right! 

.ReactTable {
  display: block;
}

This fixed it.

**Comment by tannerlinsley** [comment]
Going to track this in #316, as I think they are very closely related.
