### ISSUE TITLE
Column Resize not working

### ISSUE THREAD

**Issue by aikidoshi** [tannerlinsley/react-table#307]
Table is working perfectly (data, paging, headers etc.) but I simply can't resize the columns, don't even get a handle when I hover over them. I have 3 pages with tables and all have the same problem.

import ReactTable from 'react-table'
import 'react-table/react-table.css'
...
            const columns = [
                {
                    header: 'Rec #',
                    accessor: 'RecordNo',
                },
...
                    <ReactTable 
                        data={this.props.audits}
                        columns={columns}
                        defaultPageSize={10}
                        resizable={true}
                    />

Using a vanilla create-react-app codebase on Chrome. With or without  resizable={true} on the table or the individual columns, neither make any difference.

**Comment by aaronschwartz** [comment]
What version are you using?

**Comment by aikidoshi** [comment]
^5.4.1 in packkage.json

**Comment by aaronschwartz** [comment]
Make sure it is using at least version 5.5.0 which is when it was first added. Ideally you could migrate your project to version 6.x.x but it has a few breaking changes.

**Comment by aikidoshi** [comment]
Many thanks Aaron, I'll give it a shot shortly

**Comment by aikidoshi** [comment]
That worked like a charm at 5.5.0, many thanks for the assist Aaron!
