### ISSUE TITLE
react-table v7. Сalling toggleRowSelected ()  TypeError: Cannot read property 'isGrouped' of undefined 

### ISSUE THREAD

**Issue by didoshakra** [tannerlinsley/react-table#3076]
I took the example of Row Selection as a basis. https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/row-selection?from-embed
And I want the line to be marked when I click anywhere. To do this, I add onClick = {() => toggleRowSelected () to the code <tbody ...
   <tr {... row.getRowProps ()} onClick={() => toggleRowSelected()}>...
And in function Table ({columns, data}) {added ...
toggleRowSelected,

As a result, when you start the table and click on the line anywhere gives an error: TypeError: Cannot read property 'isGrouped' of undefined

When I use toggleAllRowsSelected instead of toggleRowSelected, everything works and all lines are marked. Day 2 I'm looking for an answer to this and I can't find it. I understand that you can do without it, but I really want to implement it. Please help.

![image](https://user-images.githubusercontent.com/20404838/108193524-35c51c80-711e-11eb-8be7-fcc81cdcefbd.png)

**Comment by anjunatl** [comment]
@didoshakra Add the rowId & a boolean representing the selection as parameters and it will work, IE `toggleRowSelected(row.id, true)` 

https://user-images.githubusercontent.com/157208/108242538-05c84a00-711b-11eb-9d3c-9027683ca14f.mp4

**Comment by didoshakra** [comment]
Everything works. Thank you very much!!

**Comment by didoshakra** [comment]
Everything works thanks to Kevin

**Comment by mivchal333** [comment]
In `toggleRowSelected: Function(rowPath: String, ?set: Bool) => void` function use row id as `rowPath`.
Row id is row index by default. You can customize row id by passing `getRowId: Function(row, relativeIndex, ?parent) => string` function as [table option](https://react-table.tanstack.com/docs/api/useTable#table-options).

Regards,
MK
