### ISSUE TITLE
column not aligned

### ISSUE THREAD

**Issue by maxmoeschinger** [tannerlinsley/react-table#309]
## Problem Description
When creating a table with scroll the column header and content is not aligned.

## Steps to Reproduce
1. Go to example at https://react-table.js.org/#/story/fixed-header-w-vertical-scroll

## System Information
* **Browser:** Chrome 58.0.3029.110

**Comment by tannerlinsley** [comment]
This is a known issue we are tracking internally.  There is a quick fix right now you can use by applying `overflow-y: scroll` to the `.rt-thead` class. This should add a scrollbar to the header and align things temporarily.

**Comment by karankumar89** [comment]
Is there a permanent fix for this?

**Comment by noam3127** [comment]
In case this helps anyone, here's how I manually adjust the column headers to be aligned:

````
adjustHeaders() {
        const tableBody = document.querySelector('.rt-tbody');
        const tBodyWidth = tableBody.clientWidth;
        const tBodyStyle = window.getComputedStyle(tableBody);
        const tBodyOuterWidth = parseInt(tBodyStyle.width.slice(0, -2));
        const tr = document.querySelectorAll('.rt-thead > .rt-tr');

        const margin = tBodyWidth < tBodyOuterWidth ?
             tBodyOuterWidth - tBodyWidth :
             0;

        tr.forEach(h => {
            h.style.marginRight = margin + 'px';
        });
}
````
I call this method from `componentWillMount()` and `componentWillReceiveProps()` (which is necessary for my use case, but may not be necessary for everyone), as well as set it to be a debounced listener for a window resize event.

**Comment by zemagnifique** [comment]
Here is how I solve this problem using css only without showing the extra scroll bars on the headers:
``` .ReactTable .rt-thead {
    overflow-y: scroll;
}

.ReactTable .rt-thead::-webkit-scrollbar {
   background: transparent; 
} ```

**Comment by gary-menzel** [comment]
My recommendation is to avoid using the `height` to set a scroll bar for the following reasons:

- react-table is a page-based table (not a scrollable table)
- the scrolling (while possible with the `height` setting) has not be properly integrated into the package and only works reliably for a very specific set of use-cases

NOTE: react-table needs to an arcihtecture design to stay "true" to React and the original design to properly incorporate a vertical scroll bar - and may then not even be what it was originally intended to be

**Comment by Ryanwiz** [comment]
I ended up with something slightly different, but build upon, noam3217's answer.

`componentDidUpdate() {
        this.adjustHeaders();
    }

adjustHeaders = () => {
        const tableBody = document.querySelector('.rt-tbody');
        if (tableBody) {
            const tBodyWidth = tableBody.clientWidth;
            const tBodyStyle = window.getComputedStyle(tableBody);
            if (tBodyStyle && tBodyStyle.width) {
                const tBodyOuterWidth = parseInt(tBodyStyle.width.slice(0, -2), 0);
                const headerRows = document.querySelectorAll('.rt-thead > .rt-tr');

                if (headerRows) {
                    const margin = tBodyWidth < tBodyOuterWidth ?
                        tBodyOuterWidth - tBodyWidth :
                        0;

                    headerRows.forEach(r => {
                        r.style.marginRight = margin+1 + 'px';
                    });
                }
            }
        }
    }`

**Comment by mbkupfer** [comment]
I have an alternative hack to fixing this, and that is simply removing all scroll bars (or more technically speaking, the appearance of there being one). My issue with both of the code solutions above is that they didn't work in IE, which I unfortunately have to always ensure is compatible with my apps. 

That said, below is the css solution I'm using (I can confirm that it works in FF, IE and Chrome):

```
.ReactTable .rt-thead {
   overflow-y: scroll;
   scrollbar-width: none;

   /* IE properties */
   scrollbar-track-color:  #FFF;
   scrollbar-3dlight-color:  #FFF;
   scrollbar-darkshadow-color:  #FFF;
   scrollbar-arrow-color:  #FFF;
}

.ReactTable .rt-tbody {
   scrollbar-width: none;
}

.ReactTable .rt-thead::-webkit-scrollbar { 
  background: transparent; 
}
```

**Comment by er-parag91** [comment]
for me only this adding this class worked like charm

.ReactTable .rt-tbody .rt-td{
    margin-left: 0;
}

**Comment by willbee28** [comment]
@zemagnifique Your css rules worked until I realized clicking the headers for filtering multiple times in a row causes the top black line above the header to flicker. Pretty strange side effect. Do you have any idea how to fix this/why it is happening?

**Comment by zemagnifique** [comment]
@willbee28 it's been working for me for a year plus with that CSS. I'm not able to reproduce the issue. Can you provide steps to reproduce or a jsfiddle?

**Comment by willbee28** [comment]
@zemagnifique   Turns out it was a problem with one of my css rules. Using a different font causes you the need to add more padding than the default for the headers. Thanks anyway!

**Comment by IanVS** [comment]
To hide the scrollbar in the header in firefox, you can use `scrollbar-width: none;`.

**Comment by IanVS** [comment]
To hide the header scrollbar in firefox, you can use `scrollbar-color: transparent transparent;`
