### ISSUE TITLE
useFlexLayout broken when table is in overflow on the width

### ISSUE THREAD

**Issue by Frumba** [tannerlinsley/react-table#3095]
**Describe the bug (required)**
Since React-Table 7.6.0 when using flexLayout, when columns are overflowing on width react-table strop drawing borders and backgrounds for an unknown reason.

**Provide an example via Codesandbox! (required)**
On the existing example on [react-table doc](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/full-width-resizable-table?file=/src/App.js)

**Steps To Reproduce (required)**

1. Resize the window width on the example to a certain point
2. Check that the right columns are not being rendered into the table
3. If you apply react-table 7.5 it works perfectly

**Expected behavior (Recommended)**
Display content in width overflow contained into the table

**Screenshots**
Render in 7.6 : 
![Capture d’écran 2021-02-24 à 17 23 43](https://user-images.githubusercontent.com/3282055/109031620-2cf7bc00-76c5-11eb-93a8-7eabb5a9816a.png)

Render in 7.5 : 
![Capture d’écran 2021-02-24 à 17 23 59](https://user-images.githubusercontent.com/3282055/109031669-38e37e00-76c5-11eb-859a-f26f2a82cbde.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 88

**Comment by dkumar431** [comment]
@tannerlinsley , Any solution for this?

Recently for a very important table implementation, I decided to go with react-table. 
But this exact issue blocking us. For us, column widths are very important as we save them in the server and reapply it.

**Comment by Frumba** [comment]
I could fix this issue by following this [advice](https://github.com/tannerlinsley/react-table/pull/2639#issuecomment-730723478).

Thansk @Abdallatif !
