### ISSUE TITLE
Style odd Rows through options

### ISSUE THREAD

**Issue by hect1c** [tannerlinsley/react-table#31]
Hey,

Is it possible to change the background of a Odd row through the config options ? Looking at the docs I'm thinking I would need to use either `trStyleCallback: row => {}` or `trClassCallback: row => null`.  Is this correct? If so how would that look exactly ?

I could just override the css rules but looking to make sure there isn't an option available for this already. Thanks.

**Comment by tannerlinsley** [comment]
Its all in the CSS for now. And probably much easier to work with than the
row callback
