### ISSUE TITLE
Access filtered result data.

### ISSUE THREAD

**Issue by kirank3836** [tannerlinsley/react-table#310]
Hi,

I want to access the data returned from the filtered result. I'm trying with onfileredChange and defaultfilterMethod, but I'm only able to get all the data present in the table instead of just the search result.

Any suggestions are appreciated!!
Thanks.

**Comment by kirank3836** [comment]
Thanks for the response. But that's returning the filter input value right. I want to access the updated results in table after filter.

**Comment by aaronschwartz** [comment]
Ah. In that case you'll probably need to save a `ref` to the table. And then in `onFilteredChange` you'll want to grab the `sortedData` state from the table.

**Comment by kirank3836** [comment]
I'm using the ref, but not sure how to grab the sortedData. Can you please gimme an example of what exactly you mean?

 ref={el=> this.tableInstance  = el}

Thank you,

**Comment by tannerlinsley** [comment]
This.tableInstance.getResolvedState().sotedData

**Comment by kirank3836** [comment]
Thanks a lot @tannerlinsley @aaronschwartz
