### ISSUE TITLE
styling of rows with getTrProps() and 'className' not working as expected

### ISSUE THREAD

**Issue by eschreiner** [tannerlinsley/react-table#312]
## Problem Description
I'm trying to style table rows using getTrProps() and returning conditionally a field 'classname' as described in the Docs / Examples.

When doing so I get an error 'invalid property'

When changing the field to 'className', the styling has no effect at all. The desired class is not applied to the appropriate 'rt-tr' elements.

I can get the desired styling by returning a 'style' field with individual, conditional fields e.g. 'color'. But of course I would prefer to use CSS classes here...

## System Information
* react-table 6.0.5

**Comment by tannerlinsley** [comment]
className should be working. Can you post your code or a link to a code pen
example?

**Comment by eschreiner** [comment]
Here you are:

```
getTrProps={(state,rowInfo) => {
  return {
    className: (rowInfo && rowInfo.row && rowInfo.row.status == 'D') ? "status-refused" : "", // no effect
    style : { // works as expected
      color: (rowInfo && rowInfo.row && rowInfo.row.status == 'D') ? "#a00" : "#000",
      opacity: (rowInfo && rowInfo.row && rowInfo.row.status == 'D') ? 0.5 : 1.0,
    },
  }
}}
```

The class is defined w/o any further selectors. Inspection of the rendered rows shows that the class was not applied.

Regards, Erich

**Comment by tannerlinsley** [comment]
Should be working: https://github.com/tannerlinsley/react-table/blob/master/src/index.js#L456.  Are you using a custom `TrComponent` perhaps?

**Comment by eschreiner** [comment]
Hi @tannerlinsley, it works in another project of mine, my bad.

Sorry for stealing your time & best regards, Erich

**Comment by eschreiner** [comment]
Hi again,

'className' now works in my main project as well.

### Problem:

- the class is determined based on a 'hidden' property of the model data, i.e. there is no column mapping for the field 'status'

```
className: (rowInfo && rowInfo.row && rowInfo.row.status == 'D') ? "status-refused" : ""
```

### Solution:

Since version 6.0, react-table creates a copy of the model data containing only the fields / properties that are actually required for rendering, i.e. that are mentioned in a column's 'accessor'.

- you need to use 'rowInfo.**original**' instead of 'rowInfo.**row**'

```
className: (rowInfo && rowInfo.original && rowInfo.original.status == 'D') ? "status-refused" : ""
```

Best regards, Erich

**Comment by darioenginius** [comment]
Hi,
I use version 5 of react-table. Is there a way to apply className if the column isn't in "accessor"?
If I add an unwanted column with "accessor" it works fine, otherwise both .row and .original don't work.

**Comment by AbhaysinghBhosale** [comment]
Hi,
How we can add !important to background colour using getTrProps
