### ISSUE TITLE
How can I define an initial sorting?

### ISSUE THREAD

**Issue by eschreiner** [tannerlinsley/react-table#313]
## Problem Description
I would like to define an initial sorting based on data retrieved (unsorted) from the server.

I have tried to use the 'sorted' property on the ReactTable component, but that seems to break changing the sorting by clicking on the column headers.

I have tried to use the 'defaultSorting' property, but that does not seem to have any effect.

Please provide a snippet showing how to set this up. Thank you!

## System Information
* react-table 6.0.5

**Comment by tannerlinsley** [comment]
Default sorting should work. Can you please post your code?

**Comment by eschreiner** [comment]
Here you go:

```
defaultSorting={[{
  id   : 'start',
  desc : true,
}]}
```

and the related column definition:
```
{
  Header  : 'from',
  accessor: 'start',
  width: 100,
}
```
The objects in the data array contain an ISO date as field 'start' e.g. '2017-06-01'. The data are displayed unsorted initially. No 'sort' indicator is displayed in the header column.

Thank you for the lightning fast response & best regards,
Erich

**Comment by aaronschwartz** [comment]
If you're using version > 6.0.0 then the key is `defaultSorted` I believe.

**Comment by eschreiner** [comment]
@aaronschwartz you're a hero :-)

**Comment by SujathaRamanMindera** [comment]
Hi - I have the same requirement now. Thanks for this answer. But where do we add this code snippet?
-------------------------------------
defaultSorting={[{
  id   : 'start',
  desc : true,
}]}
-------------------------------------
