### ISSUE TITLE
Sorting numbers that include a currency symbol

### ISSUE THREAD

**Issue by kieronsutton00** [tannerlinsley/react-table#315]
Hello,
When sorting my table, the sorting does not work correctly for numbers that contain a currency symbol. Is it possible to add this support?

I tried to make use of the defaultSortingMethod but it appears that the function wasn't even being used.

Thanks

**Comment by aaronschwartz** [comment]
The key is `defaultSortMethod` and it should be working in the latest releases.

If you're still having trouble you can join the slack channel for quicker answers: https://react-chat-signup.herokuapp.com/

**Comment by tannerlinsley** [comment]
It *is* possible to sort numbers with a dollar sign in them, but you would need to parsing out just the number, at which point I would highly suggest doing so before you render the table.  That way you can easily point the column `accessor` to use the number, then in your `Cell` renderer, add in a `$`.

**Comment by denishaskin** [comment]
> It _is_ possible to sort numbers with a dollar sign in them, but you would need to parsing out just the number, at which point I would highly suggest doing so before you render the table. That way you can easily point the column `accessor` to use the number, then in your `Cell` renderer, add in a `$`.

Except the OP asked about sorting currency, not dollar values.  So now the table has to know what currency is being used, to prepend (or append) the correct currency symbol.

**Comment by tannerlinsley** [comment]
You could ultimately use a custom `column.sortMethod` if you are unable to normalize the column data. In that custom sort method you would need to handle the removal of any currency symbols, casting to a float and sorting appropriately.

And yes, if you are handling multiple currencies, then you would need to be aware of those options regardless.
