### ISSUE TITLE
design issue in the last version 6.0.5 on Chrome only

### ISSUE THREAD

**Issue by Saidvic** [tannerlinsley/react-table#316]
after upgraded the module to 6.0.5, i encountered a design problem in Chrome.
the table header and body are collapsed, and the pagination options are tall, this is how it looks on Chrome:
![capture](https://cloud.githubusercontent.com/assets/28808786/26728118/a59bb1ee-4798-11e7-954b-0e1755d54ee7.PNG)

on Firefox everything is fine

as i temporarily fix, i downgraded the module to 6.0.2 and applied height : 50px on pagination section

**Comment by tannerlinsley** [comment]
Is this in the storybook or your own implementation?  We use Chrome, Firefox and Safari to test our releases. If it is your own implementation, could you please replicate the issue in a our codepen example and post the link here?

**Comment by orweis** [comment]
Got a similar (collapsed table (which reappears if you remove display:flex) issue (on 6.0.2 from NPM) ...
I'm guessing it might be a conflict with Material-UI. Wasn't able to recreate the issue in codepen (no CDN for material-UI currently)

**Comment by shivekkhurana** [comment]
This is similar to #351 and #304. I have added `display: block` on `.ReactTable` and it seems to (hack) fix the issue (but the pagination height is still a problem).

**Comment by gillisd** [comment]
I am also having this issue

**Comment by tannerlinsley** [comment]
Could someone please provide a codepen example for this issue? I will test on all major browsers as soon as I can reproduce it on my end.

**Comment by coreyleelarson** [comment]
I'm having this same issue.

**Comment by jmtoung** [comment]
I'm having the same *frustrating* issue. (Chrome Version 58.0.3029.110 (64-bit))

**Comment by tannerlinsley** [comment]
Using only the stylesheet that comes with react-table, everything appears to be fine on all of my devices. MacOS, chrome, safari, iPhone 6s, and emulations across many other devices. Use this codepen example for reference or testing. https://codepen.io/tannerlinsley/full/QpeZBa/
