### ISSUE TITLE
Update custom Cell when datas are updating

### ISSUE THREAD

**Issue by qmorel** [tannerlinsley/react-table#317]
First, thanks for your amazing job on this, and sorry for my english ^^'

## Problem Description
I read some issue on the (maybe?) same problem that I have, but didn't find what I'm doing wrong, I didn't find the way the correct it in my case. I'm a react-beginner, don't blame me :D

So, I have a table, with custom Cell component for several columns. The first data is initialized on the componentWillMount function, and send from a server, by an ajax request:

`fechtApi(route)
      .then(response => {
        this.setState({ datas: response, loading: false })
      })`

As simple as that.
Then, I update my data in an other function (when a event coming that update the datas on the sever), like that:

`eventComing = () => {
      fechtApi(route)
        .then(response => {
          this.setState({ datas: response })
        })
  }`

The data prop in my React Table is obviously data={this.state.datas}.

The result: simple rendered data (no custom cells) are well rendered, but in my custom Cell (that load a component) don't update.

(Also, something strange appended when a reach the last page that show just on row, then go back to a page that show two rows, my custom component is re-render, because it was unmount, then re-mount? And, on a other page that show two row too, the component on the second row is showing like is datas changing, but the datas for this cell hasn't changing. I think I have to make a GIF for this, this is not clear :thinking: ).

So I read about this problem here: https://github.com/tannerlinsley/react-table/issues/254 but… didn't find what I did wrong 😞 

Edit: I thought about something,did the custom Cell component is unmount and re-mount when datas change? Or just updating ?

Thanks a lot for any help !

**Comment by qmorel** [comment]
Ok, I investigate.

My custom cell component have logic rende, so I made this logic into the render() function and not into willReceiveProps. It's working now. Soz4This.

**Comment by tannerlinsley** [comment]
Sounds good.  Just to clarify, React-Table does not rerender your Cell components whenever possible, but updates them instead.  This keeps the table fast.  If you need to know when a cell is rendered and then subsequently updated, you should use `componentDidMount` + `componentDid/WillUpdate`
