### ISSUE TITLE
Show Loading Indicator While Rendering Happens?

### ISSUE THREAD

**Issue by Iteria** [tannerlinsley/react-table#318]
I'm currently working with a table with a lot of data and I allow my users to change the column grouping on the fly. The problem is that some of these table have a lot of data and the rerendering takes a few secs, which makes the table look like its frozen. I can set the loading indicator when I change the grouping, but I can't see anything that will let me remove it when the data is ready to be viewed.

Am I missing something or is this not possible?

**Comment by aaronschwartz** [comment]
How are you showing the loading indicator?
If you're using `loading` option, then you can just set it to true, false appropriately.
See https://react-table.js.org/#/story/sub-components for an example where you can click to toggle the `loading` indicator.

**Comment by Iteria** [comment]
I'm setting the loading props, but playing with it after I posted and diving into the source code, I realized my true problem. Even if I set the loading props when I adjust the pivoting on the grid, the loading indicator won't appear instantly. It will appear finishes resolving the new state, which takes it 2 or 3 seconds with some of the very large tables I'm working with.

I'm not sure there's a fix for that, except to somehow figure out how to set the loading prop by itself, and let the table render itself, then set the pivotBy prop with the loading prop off and let the table render once more when a user changes the table pivot.

**Comment by tannerlinsley** [comment]
Loading is a controlled prop. You should be able to set it on your own even
when not using the manual prop

**Comment by Iteria** [comment]
I'm going to make a pen showing what I mean. I think the problem will become apparent when you see it in action

**Comment by Iteria** [comment]
[Here is an example pen](https://codepen.io/iteria/pen/weaBQa) of what I mean. When you're dealing with a lot of rows (in this case 100K), the grid locks up and setting a loading indicator before the new form of the data is impossible. I've got both ways I've attempted it.

When the button is clicked to fill the grid with data, the loading indicator is set first, while getting the data, then again when all the data has been fetched. You don't see the loading screen.

After the data fills the grid and the button is clicked that pivots the table by age, you'll notice that the loading indicator only appears _after_ the data appears pivoted.

Either way, I don't have a way to deal with the long delay in the grid update when dealing with this much data. That's beyond the instability of the page which working with this much data, which is also a problem. Half the chrome my chrome tab will just crash, sometimes if I click the dialog to wait for the process to finish, it actually will.

**Comment by aaronschwartz** [comment]
Here is a hacky workaround. The problems is that it is hard to tell React exactly when to perform updates since it is constantly trying to batch together changes for optimization.

https://codepen.io/anon/pen/yXNORq?editors=0010

**Comment by Iteria** [comment]
It does seem to work. I guess I'll use this until a better solution appears, if it ever does.

**Comment by tannerlinsley** [comment]
That does seem like the best option right now.  The delay you experience is because of the synchronous processing happening on the UI thread. The only way around this is to first render your own loading indicator, then render the table underneath it. My guess is that everything on the page, including animated SVG will pause while you are rendering your table, so there isn't much more you can do to avoid this (maybe react fiber will help this situation a little bit, we'll see). For now, @aaronschwartz 's suggestion is the best route I think.
