### ISSUE TITLE
404 on GitHub 

### ISSUE THREAD

**Issue by isaaczafuta** [tannerlinsley/react-table#32]
Thanks for this project!

I noticed that the GitHub page links to http://react-table.js.org/ but I'm getting 404s when I visit that page.

**Comment by tannerlinsley** [comment]
Just waiting on the DNS to propagate. I've switched the link back until it
resolves

**Comment by reintroducing** [comment]
hmm, i'm still seeing a 404 when trying to access that URL.

**Comment by tannerlinsley** [comment]
Haha, turns out that react-storybook was recreating the `docs` directory on build, so the `CNAME` file was disappearing all the time.  Should be fixed for good in 3d325dad8da12c9e0934bf0357e6b916f999d319 :)

**Comment by reintroducing** [comment]
Yep, works now :)
