### ISSUE TITLE
expandedRows prop from example does not open SubComponent

### ISSUE THREAD

**Issue by nicotroia** [tannerlinsley/react-table#320]
## Problem Description
Implementing the `expandedRows` prop does not automatically open the SubComponent defined in the top-level props.

## Code Snippet
```
    constructor(props: Object) {
      super(props)
  
      this.state = {
        numPages: 1,
        page: 0,
        pageSize: 10,
        fakeData: [{
          id: "11",
          first_name: 'hey',
          last_name: 'ho'
        }, {
          id: "12",
          first_name: 'lets',
          last_name: 'go'
        }]
      }
    }

    render() {
      return (
        <ReactTable
          className='-striped -highlight'
          data={this.state.fakeData}
          columns={gridColumns}
          SubComponent={(row) => {
            return (
              <div>sub content</div>
            )
          }}
          expandedRows={{
            0: true,
            1: true
          }}
          onExpandedChange={(newExpanded, index, event) => {
            console.log('expanded', newExpanded, index)
          }}
        />
      )
    }
```

The `onExpandedChange` will fire after a manual click to expand the row but it doesn't look like the `expandedRows` is being honored when explicitly set. 

Any info here? Thank you!

## System Information
react-table 6.0.5
react 15.5.4
node v7.10.0
npm 4.2.0

**Comment by aaronschwartz** [comment]
In react-table > 6.x.x `expandedRows` got changed to `expanded`. It appears that Controlled Component section of the readme didn't get updated.

**Comment by Arjav97** [comment]
Hi @aaronschwartz where can i find the readme file of fully controlled component props section of the react-table.....
