### ISSUE TITLE
Deep accessor doesn't work

### ISSUE THREAD

**Issue by qmorel** [tannerlinsley/react-table#321]
## Problem Description
Hello, I'm back with an other issue :D

This concern deep accessor like: 
`"accessor": "orderItems[0].productOptions[0].location.label"`
This don't work, but `"accessor": "orderItems[0].product.label` work.

When I put it in a a custom accessor like this: `accessor: d => d.orderItems[0].productOptions[0].location.label` it works too. But, my conf of columns is given by a server, in a JSON, so I can't put fonction on it :/

## Step to reproduce
Put a deep accessor path like `array[1].object.array[0].object.key`

It should work no? React Table just do a _.get (like in lodash) with the accessor string? I have tested and lodash _.get return the good value for "orderItems[0].productOptions[0].location.label".

Or I have to find a way to recreate the custom accessor fonction with the path of data in a string… Don't know how.

Thanks !

Edit: there is a problem in your makePathArray function:
`makePathArray("orderItems[0].productOptions[0].name")`
`> ["orderItems", "0", "productOptions[0]", "name"]`

Correct function must be like:
```
function makePathArray (obj) {
  return flattenDeep(obj)
      .join('.')
      .replace(/\[/g, '.')
      .replace(/\]/g, '')
      .split('.')
}
```

**Comment by tannerlinsley** [comment]
I've left some feedback on your PR.  Let's get that merged asap
