### ISSUE TITLE
Row sorting after resizing column

### ISSUE THREAD

**Issue by ThiBsc** [tannerlinsley/react-table#3217]
**Describe the bug (required)**
I use the column sorting and resizing but I have a conflict between those two features. If I click on a column, the column is sorting, everything goes well. But If a resize a column, after release the resize handle, the table apply an unwanted sort. Is it a way to avoid this ?

**Provide an example via Codesandbox! (required)**
Here the [react-table codesandbox](https://codesandbox.io/s/sharp-ives-fzjzu?file=/src/App.js) to reproduce the issue.

**Steps To Reproduce (required)**

1. Resize a column

**Expected behavior (Recommended)**
The column should resize without sorting in this case

**Desktop (please complete the following information):**

- OS: [XUbuntu 20.04 LTS]
- Browser: Mozilla Firefox 87.0 (64 bits)

**Comment by ThiBsc** [comment]
Found a solution by preventing the propagation of the click event on the resize handle div

```js
function Table({ columns, data }) {
  // ...
  const preventPropagationOnResize = (evt) => {
    evt.preventDefault();
    evt.stopPropagation();
  }
  // ...

  return (
    {/* ... */}
       {/* Use column.getResizerProps to hook up the events correctly */}
        <div
          {...column.getResizerProps()}
          className={`resizer ${
            column.isResizing ? 'isResizing' : ''
          }`}
          onClick={preventPropagationOnResize}
        />
    {/* ... */}
  )
}
```

**Comment by fabricioffv** [comment]
Guys, how do I fix this for V8?
