### ISSUE TITLE
Is there a way that I can make the single column clickable to a href?

### ISSUE THREAD

**Issue by shaikjohnsaida** [tannerlinsley/react-table#322]
Is there a way that I can make the single column clickable to a href?

Right now I m using for row
<ReactTable
getTrProps={(state, rowInfo, column, instance) => ({
onClick: e => console.log('A row was clicked!')
})}
/>

**Comment by tannerlinsley** [comment]
This is a great way to do it.  You could also add a style to show a cursor when hovering: `{ style: { cursor: 'pointer' } }`. The only other way would be to use an actual `<a href='' />` in the `Cell` renderer of the column.,
