### ISSUE TITLE
getThProps?

### ISSUE THREAD

**Issue by dentuzhik** [tannerlinsley/react-table#325]
## Problem Description
According to docs there should be `getThProps` hook, but looking into the code I can't find one:
https://github.com/tannerlinsley/react-table/blob/master/src/index.js#L66

Was it removed at some point, and is there any other way to specify props for the table header cells?

The problem what I am eventually trying to solve is to check if the column is sortable, and attach a className or icon to display a sorting indicator. I could do it per-column of course (through `getHeaderProps`), but solution through `getThProps` seems better to me.

**Comment by dentuzhik** [comment]
I was able to achieve what I wanted through `getTheadThProps`, so I guess the old reference was renamed at some point.

**Comment by tnrich** [comment]
Oh, just ran into this also.. this should be fixed in the docs: 
![image](https://user-images.githubusercontent.com/2730609/38579439-da4733a0-3cbb-11e8-880a-0688df83a977.png)

**Comment by gary-menzel** [comment]
Maybe you could submit a PR to fix it? Not a lot of time for people to be fixing docs on this package.
