### ISSUE TITLE
publish master to npm please

### ISSUE THREAD

**Issue by mayank23** [tannerlinsley/react-table#327]
Hi, would you be able to publish master to npm. Sorry for the rush, in a bit of a time crunch.

Thanks a lot!

**Comment by mikedevita** [comment]
I'm mobile but you can clone the repo and npm link it to get what you need.

**Comment by tannerlinsley** [comment]
Released as 6.2.0

**Comment by mikedevita** [comment]
@tannerlinsley do you have automated builds on push to master?

**Comment by tannerlinsley** [comment]
Right now all of the CI consists of TravisCI for testing (which basically just linting right now), and Netlify which will automatically build the website for all braches and PR's.
