### ISSUE TITLE
How to create a Filter component detached from the ReactTable?

### ISSUE THREAD

**Issue by lefnire** [tannerlinsley/react-table#328]
Design spec I'm working with has a "filter by department" select outside the table. Working with the existing `column.Filter` prop and moving it with CSS is messy (since it needs to be positioned relative to neighbor components). My initial thought was to give the `ReactTable` a `ref` and call a method directly, here's what I tried:

```javascript
class MyComponent extends Component {
  defaultFilterMethod = (filter, row, column) => {
    debugger; // This line never reached
    const id = filter.pivotId || filter.id;
    return row[id] !== undefined ? row[id].department === filter.value : true;
  };

  render() {
    const data = [{
      name: 'Tanner Linsley',
      department: 1,
    },{
      name: 'Jason Maurer',
      department: 2,
    }];

    const columns = [{
      Header: 'Name',
      accessor: 'name'
    }, {
      Header: 'Department',
      accessor: 'department'
    }];

    return (
      <div>
        <select onChange={e => this.reactTable.filterColumn('department', e.target.value)}>
          <option value="all">All</option>
          <option value="1">Department One</option>
          <option value="2">Department Two</option>
        </select>

        <ReactTable
          ref="reactTable"
          columns={columns}
          defaultFilterMethod={this.defaultFilterMethod}
          data={data}
          filterable={true}
        />
      </div>
    );
  }
}
```

However, the `debugger;` statement above is never reached. Is there a smarter way about this?

**Comment by tannerlinsley** [comment]
This seems like a good candidate for the functional rendering feature.

**Comment by lefnire** [comment]
Here's an update that I did get working. My bad, I needed to pass the column object directly, not just the accessor/id. 

```javascript
class MyComponent extends Component {
  data = [{name: 'Tanner Linsley', department: 1}, {name: 'Jason Maurer', department: 2}];
  columns = [{Header: 'Name', accessor: 'name'},{Header: 'Department', id: 'department', accessor: 'department'}];
  
  defaultFilterMethod = (filter, row, column) => {
    const id = filter.pivotId || filter.id;
    return row[id] !== undefined ? row[id].department === filter.value : true;
  };

  onChange = e => this.reactTable.filterColumn(this.columns[1], e.target.value);

  render() {
    return (
      <div>
        <select onChange={this.onChange}>
          <option value="">All</option>
          <option value="1">Department One</option>
          <option value="2">Department Two</option>
        </select>

        <ReactTable
          ref="reactTable"
          columns={this.columns}
          defaultFilterMethod={this.defaultFilterMethod}
          data={this.data}
          filterable={true}
        />
      </div>
    );
  }
}
```

Functional rendering does indeed look like the proper approach; cleaner and more idiomatic. I'll update this ticket with that sample code if I get that working.

**Comment by alexrborton** [comment]
Did anyone have an example of the above using Functional Rendering?

**Comment by dmk255** [comment]
I would also be happy to put a PR with the above in the docs if we don't have a good example of functional rendering. 

This is a fairly common use case. Prior reading this thread I was just manipulating the input data prop (via state) - this is much better & faster.

**Comment by Khangeldy** [comment]
@lefnire  Which is more preferable? Delete filterable flag from ReactTable or hiding it in css?

**Comment by zachsa** [comment]
@dan-kez - is there documentation on this? I'm attempting to do a filter that is a component distinct from the ReactTable - as shown in the example by @lefnire. But calling `this.refs.reactTable.filterColumn(this.columns[0], val)` doesn't result in the filter being fired.

I can't find any documentation on reactTable.filterColumn either - The table pivoted, I don't know how that would effect filtering, except that when I use the in-table filters a filter function is definitely fired.

**Comment by evbo** [comment]
I'm new to javascript and I am also really confused on where the code is for `reactTable.filterColumn`?

Is there at least a link someone can give showing where that function is defined?

Thanks for your patience and support for newbies like me trying to wrap their head around this!

**Comment by jerrybuks** [comment]
> @dan-kez - is there documentation on this? I'm attempting to do a filter that is a component distinct from the ReactTable - as shown in the example by @lefnire. But calling `this.refs.reactTable.filterColumn(this.columns[0], val)` doesn't result in the filter being fired.
> 
> I can't find any documentation on reactTable.filterColumn either. Is there any?

@zachsa please did you find a way around this, I'm stuck on the same issue?

**Comment by zachsa** [comment]
> > @dan-kez - is there documentation on this? I'm attempting to do a filter that is a component distinct from the ReactTable - as shown in the example by @lefnire. But calling `this.refs.reactTable.filterColumn(this.columns[0], val)` doesn't result in the filter being fired.
> > I can't find any documentation on reactTable.filterColumn either. Is there any?
> 
> @zachsa please did you find a way around this, I'm stuck on the same issue?

If I remember correctly I changed track and implemented a filter myself with the table component that came with the library I was using (react-md).

**Comment by aruprakshit** [comment]
@lefnire On that `debugger` did you find any reason why it never called. I have similar problem inside the custom filter. I wanted to inspection function arguments data structure to use them to do some logic implementation in my app, but `console.log` never comes out to the browser console. It is so strange I got stuck. That now made me think how even the search is working if not called the function. Here I asked it in [so](https://stackoverflow.com/questions/65804012/how-to-inspect-what-data-react-table-sends-to-filter-function-as-argument) , but didn't get any correct answer yetl

**Comment by lefnire** [comment]
Alas, 4h ago - I don't remember shit about shit
