### ISSUE TITLE
Page refresh not working by default 

### ISSUE THREAD

**Issue by ArunPandianB** [tannerlinsley/react-table#329]
## Problem Description
After navigating to page no 2. When I render a new set of data ,its showing only page no 2.. By defaults its not showing page no 1.

## Steps to Reproduce
1. Render a data set 1 and navigate to page 2
2. Render a data set 2 or apply filter, now page no 1 is not showing only page 2 documents are showing
3. In order to acheive this, Suppose if I set page={0} as props pagination is not working.

## System Information
* **Browser & Browser Version:**
* **Node Version:**
* **OS Version:**
* **NPM Version:**
* **Yarn Version:**

**Comment by tannerlinsley** [comment]
Please provide an example (using the codepen above) that reproduces this issue.
