### ISSUE TITLE
CodeSandbox Iframes are broken

### ISSUE THREAD

**Issue by GuilhermeLLS** [tannerlinsley/react-table#3291]
**Describe the bug (required)**
None of the examples in CodeSandbox are working. It shows an `Not Found` error in the iframe where the code preview should be. The links to the sandboxes themselves are also broken.

**Steps To Reproduce (required)**

1. Go to any page in the website where there is a codesandbox(example: https://react-table.tanstack.com/docs/examples/sorting)

**Expected behavior (Recommended)**
The CodeSandbox should display the code preview.

**Screenshots**
![image](https://user-images.githubusercontent.com/40529676/119850429-ed1ebb80-bee3-11eb-9839-eb644b1638c7.png)
![image](https://user-images.githubusercontent.com/40529676/119850866-4d156200-bee4-11eb-9a6b-ae476c58bb5f.png)

**Desktop (please complete the following information):**

- OS:  Ubuntu 20.04
- Browser:  Brave
- Version: 1.24.86 - Chromium: 90.0.4430.212 - 64 bits

**Smartphone (please complete the following information):**

- Device: Xiaomi Mi 8 Pro
- OS: Android 10
- Browser: Google Chrome
- Version: 91.0.4472.77

**Additional Context**
I tried to use it in other browsers and devices, but the problem remains.

**Comment by GuilhermeLLS** [comment]
Closing issue because the Sandboxes are back. Something wrong probably happened on CodeSandbox part.

**Comment by dikshantpatodia** [comment]
This issue still exists, not showing any of it.
