### ISSUE TITLE
Pivot demo not working

### ISSUE THREAD

**Issue by peterbe** [tannerlinsley/react-table#33]
<img width="1966" alt="screen shot 2017-01-19 at 8 18 39 pm" src="https://cloud.githubusercontent.com/assets/26739/22131889/844258ae-de84-11e6-80ed-1ad71020f614.png">
Screenshot says it all.

**Comment by tannerlinsley** [comment]
Looks like a firefox issue.  Debugging it now...

**Comment by tannerlinsley** [comment]
Very interesting!  The `namor` word generator I'm using happened to create a word called `watch`, which was then applied to an object like so `ob['watch'] = obj['watch'] || []`, which, in firefox is an actual method on the object prototype, hence the error.  I'll have a fix out for this asap.

**Comment by tannerlinsley** [comment]
Fixed in 66f1b04ba6ba4534edfddf5dea8cdf97983d65bd

**Comment by tannerlinsley** [comment]
@peterbe Thanks for finding this!
