### ISSUE TITLE
Can we call the Prev and Next in pagination dynamically ? I want to control the Next and Prev by left an right arrow in keyboard???

### ISSUE THREAD

**Issue by shaikjohnsaida** [tannerlinsley/react-table#331]
## Problem Description
include a detailed explanation of the problem here...

## Steps to Reproduce
1. list the steps
2. to reproduce the issue

## System Information
* **Browser & Browser Version:**
* **Node Version:**
* **OS Version:**
* **NPM Version:**
* **Yarn Version:**

**Comment by tannerlinsley** [comment]
You can easily use a `ref` on the table and call `instance.setState({page: 5})` and the page would update to page 6 (it is zero-indexed)
