### ISSUE TITLE
Hide expander for rows without children.

### ISSUE THREAD

**Issue by janbuerling** [tannerlinsley/react-table#332]
## Problem Description
Is there a way to display an expander for only such rows, which also have children or rather, stop the click event for those rows which don´t have children? 

I can hide the expander, but the click event on the expander column still exists.

I have tried the following:

### (1) getTdProps:
     In the methode getTdProps if (column.expander && !row.original.children.length > 0)
     I have set the onClick fn as follows:  
             
    onClick: (p, e) => {
        e.preventDefault();
        e.stopImmediatePropagation();
    };

### (2) Expander:
    I have overwritten the expander component and if there are no children there is 
    a fake button set with the same onClick (see: (1)). 
    It is totally unclean, but my last idea.

Do I make something wrong or is there another solution?

In this picture you can see that 'Bags' should not have an expander:

![bildschirmfoto 2017-06-07 um 13 10 17](https://user-images.githubusercontent.com/18394509/26875581-ddd580ce-4b82-11e7-8d48-5f286152ae8b.png)

This is how it should look if children exist:

![bildschirmfoto 2017-06-07 um 13 31 29](https://user-images.githubusercontent.com/18394509/26876294-c979b796-4b85-11e7-8127-fa63fe31eaf8.png)

I can hide the expander by return null in expander component if children === 0 but the click event still exists:

![bildschirmfoto 2017-06-07 um 13 52 25](https://user-images.githubusercontent.com/18394509/26876970-b95acd70-4b88-11e7-8011-f2f4bf5fda85.png)

**Comment by leejeannes** [comment]
Related issue that was closed as a feature request: https://github.com/tannerlinsley/react-table/issues/62

**Comment by tannerlinsley** [comment]
For pivoted rows, the expander will not be shown. See https://codepen.io/tannerlinsley/pen/NvRWzM?editors=0010 for an example.

For sub-components, #62 covers the conversation which basically entails a massive performance hit to render all of the sub components even when not displaying them.

If you have more questions, feel free to joint the slack organization and post a question.
