### ISSUE TITLE
Accessing filter object from renderers

### ISSUE THREAD

**Issue by dentuzhik** [tannerlinsley/react-table#333]
## Problem Description
I want to be able to highlight the search result inside the table cells when filtering happens.
By inspecting the argument of `Cell` renderer, I haven't found anything what could help me get this data, so I'm relying on setting the ref and accessing the state of the table in cell renderer, which is not ideal.

```javascript
Cell: row => {
    const filteredColumns = this.tableInstance ?
        get(this.tableInstance.getResolvedState(), 'filtered', []) :
        [];
    const filteredDevicesColumn = find(filteredColumns, { id: 'devices' });
    const filterValue = get(filteredDevicesColumn, 'value');

    return (<UserDevicesPopover
        devices={row.value}
        higlightText={filterValue}
    />);
}
```

This is rather a feature request, but is it even possible to add this data to a cell and/or any other renderers?

**Comment by tannerlinsley** [comment]
You should have access to the entire table state with the other props that are passed to the Cell Renderer. If not, I would accept a PR for this functionality
