### ISSUE TITLE
Left column pinning 

### ISSUE THREAD

**Issue by gnain** [tannerlinsley/react-table#334]
Is there any way to pin the leftmost column of the table, so that when there is a large number of columns, and you have to scroll left and right, the column still displays ?

**Comment by ankuronweb** [comment]
+1
It will be awesome to have this feature soon implemented. Thanks

**Comment by tannerlinsley** [comment]
We are aware of this feature. Working on it conceptually, but don't expect anything in this area very soon at all :(

**Comment by cwiese** [comment]
yes pin one or more columns from horizontal scroll
