### ISSUE TITLE
Case Insensitive Filtering on client side

### ISSUE THREAD

**Issue by Keshavdulal** [tannerlinsley/react-table#335]
## Problem Description
Currently the built in filter-system works great but can we configure react-table to support additional facilities like: Case Insensitive Filtering and Substring Matching While Filtering.
caseInsensitiveFiltering = {true}
subStringFiltering = {true}

P.S. I am a fan of react-table :)

**Comment by aaronschwartz** [comment]
Glad it is working for you.

You have full control over how the filter is rendered as well as how the filtering works for each column.

See the Filtering section of the readme for more information:
https://github.com/tannerlinsley/react-table#filtering

Also take a look at the Custom Filtering demo: 
https://react-table.js.org/#/story/custom-filtering

If you have more implementation questions the Slack channel is a great place to get answers:
https://react-chat-signup.herokuapp.com/

**Comment by ashtarcommunications** [comment]
For case insensitive filtering - with help from a previous issue:

```
function filterCaseInsensitive(filter, row) {
	const id = filter.pivotId || filter.id;
	return (
		row[id] !== undefined ?
			String(row[id].toLowerCase()).startsWith(filter.value.toLowerCase())
		:
			true
	);
}

<ReactTable
	data={data}
	columns={columns}
	filterable
	defaultFilterMethod={filterCaseInsensitive}
/>
```

**Comment by cbll** [comment]
@ashtarcommunications I can't seem to get that function working that way. Where do you put the filterCaseInsensitive in the scope? In render? I've tried both in render, as well as the outside scope(main React class), but to no avast. Thanks :)

**Comment by cbll** [comment]
Arh, I rewrote it ES6-style and has some better luck. It even worked for a nested table. Here's what I wrote in `render()`:

`
        const filterCaseInsensitive = (filter, row) => {
            const id = filter.pivotId || filter.id;
            return (
                row[id] !== undefined ?
                    String(row[id].toLowerCase()).startsWith(filter.value.toLowerCase())
                    :
                    true
            );
        };
```

And called as such:

```
return(
            <div>
                    <ReactTable
                        showFilters={true}
                        className='-striped -highlight'
                        defaultPageSize={10}
                        defaultFilterMethod={filterCaseInsensitive}
                        pageSizeOptions={[5, 10, 15]}
                        data={tableArr}
                        columns={columns}
                        noDataText="No assets detected on network"
                        SubComponent={(row) => {
                            return (
                                <div style={{padding: '20px'}}>
                                    <ReactTable
                                        showFilters={true}
                                        data={Object.values(row.row.Details)}
                                        defaultFilterMethod={filterCaseInsensitive}
                                        columns={swColumn}
                                        defaultPageSize={Object.keys(row.row.Details).length}
                                        showPagination={false}
                                    />
                                </div>
                            )
                        }}
                    />
            </div>
return(
            <div>
                    <ReactTable
                        showFilters={true}
                        className='-striped -highlight'
                        defaultPageSize={10}
                        defaultFilterMethod={filterCaseInsensitive}
                        pageSizeOptions={[5, 10, 15]}
                        data={tableArr}
                        columns={columns}
                        noDataText="No assets detected on network"
                        SubComponent={(row) => {
                            return (
                                <div style={{padding: '20px'}}>
                                    <ReactTable
                                        showFilters={true}
                                        data={Object.values(row.row.Details)}
                                        defaultFilterMethod={filterCaseInsensitive}
                                        columns={swColumn}
                                        defaultPageSize={Object.keys(row.row.Details).length}
                                        showPagination={false}
                                    />
                                </div>
                            )
                        }}
                    />
            </div>
```

Not sure what I did wrong the first time, but works for me like this!

**Comment by cbll** [comment]
Here's a fix to handle case insensitive filtering of rows that include empty cells:

```
        const filterCaseInsensitive = (filter, row) => {
            const id = filter.pivotId || filter.id;
            if (row[id] !== null){
                return (
                    row[id] !== undefined ?
                        String(row[id].toLowerCase()).startsWith(filter.value.toLowerCase())
                        :
                        true
                );
            }
        };
```

**Comment by ashtarcommunications** [comment]
In my case, I have the filter in a separate module and am just importing it at the top of the file, e.g.:
import { filterCaseInsensitive } from './filters';

The files where I'm using the filter are all stateless functional components though, not ES6 classes, so there's no render function.

Good call on the null values. Also worth keeping an eye out for how the custom filtering interacts with custom accessor functions, Cell render functions, or higher order components that wrap ReactTable and accidentally mutate the table state - I've run into a couple weird but easily worked around edge cases.

**Comment by gary-menzel** [comment]
Use the `endsWith` String function. If you need to support IE then you will need to also add a polyfill for the `endsWith` function.

**Comment by juniarsofyan** [comment]
thankyou @gary-menzel , in my case i tried to make a case insensitive filtering, and can be filtered from the start or the end of the string. and also can be filtered if the field contains the word i typed. here is my code:

const defaultFiltering = (filter, rows) =>
      matchSorter(rows, filter.value, {
        keys: [filter.id]
      });

return (
        <LayoutContentWrapper style={{ height: "100vh" }}>
            <LayoutContent>
                <Col md={24} sm={24} xs={24}>
                    <ReactTable 
                        data={result} 
                        filterable
                        defaultFilterMethod={defaultFiltering}
                        columns={columns}
                        loading = {this.state.loadingState}
                        style={{
                          height: "600px"
                        }}
                        className = "-striped -highlight"
                        />
                </Col>
            </LayoutContent>
        </LayoutContentWrapper>
    );

sorry if my english is bad

**Comment by PavelAlexDev** [comment]
Hi, everyone.
Please let me know kindly about my issue.
I am using custom dropdown for reacttable filtering.(every colum has own filter method.)
All are working correctly, but not working to show original column list with setting "all" item in select.
I was set as like following.
   - colume setting
       {
        Header: translations['cocom'],
        accessor: 'cocom',
        Filter: ({ filter, onChange }) =>
                    <FilterDropdown dropdownData={(value)=> 
                  {onChange({filterValue:value}); console.log(value);}} value={this.state.filterValue}/>
      },
    - FilterDorpdown
       renderItems() {
        return this.state.dropdownItems.map(function(data, key){  
            if(data.label == "All"){
                return ( <option key={key} value="">{data.label}</option>) ;
            } else {
                return (<option key={key} value={data.label}>{data.label}</option> );
            }
        })
    }

    handleChange = (e) => {
        const { name, value } = e.target;
        const { selectedDropDownValue } = this.state;
        this.setState({
            selectedDropDownValue: value
        }, () =>{
            this.props.dropdownData(this.state.selectedDropDownValue);
        });
    }

    render() {
        let key = this.props.id || 0;
        return (
            <div>
                <select name={key} onChange={this.handleChange}>
                    {this.renderItems()}
                </select>
            </div>
        );
    }
But in this https://react-table.js.org/#/story/custom-filtering, I was setting as like following attached image
http://prntscr.com/jk03y4
Mean's to set filter value with "", then working to show original list.
What is my fault using this?
Hope to get kindly teaching.
Regards.

**Comment by brianhankins** [comment]
Just in case anyone has columns with numbers, this will filter both string types and numbers without throwing an error.

```
const filterCaseInsensitive = (filter, row) => {
            const id = filter.pivotId || filter.id;
            if (row[id] !== null && typeof row[id] === 'string'){
                return (
                    row[id] !== undefined ?
                        String(row[id].toLowerCase()).startsWith(filter.value.toLowerCase()) : true
                )
            }
        }
```

**Comment by nabeelnazirvf** [comment]
How can we achieve case insensitive string, case insensitive substring, and number (Integer) filter?

**Comment by ashtarcommunications** [comment]
Use your favorite method to check for a substring instead of startsWith. Depending on your environment and your particular use case, you can use string.includes, string.contains, string.indexOf, etc.

```javascript
function filterCaseInsensitive(filter, row) {
    const id = filter.pivotId || filter.id;
    if (row[id] !== null) {
        return (
            row[id] !== undefined ?
                String(row[id].toString().toLowerCase())
                    .includes(filter.value.toString().toLowerCase())
            :
                true
        );
    }
}
```

**Comment by kutyel** [comment]
Here’s ours 😉 

```js
const filterCaseInsensitive = ({ id, value }, row) =>
  row[id] ? row[id].toLowerCase().includes(value.toLowerCase()) : true
```

**Comment by okothomondi** [comment]
this does not work for number. what if I have number in my table too!!

**Comment by Memogcia** [comment]
@okothomondi please read all comments. @brianhankins wrote the solution for that case

**Comment by fastwayweb** [comment]
Solutions above didn't solve my needs, as i have number and null values as well. However great starting point, kudos to all who provide the answers. Below my 5 cents ;)
`
const filterCaseInsensitive = (filter, row) => {
  const id = filter.pivotId || filter.id;
  if(row[id] !== null && typeof row[id] === 'string') {
    return (
      row[id] !== undefined ?
          String(row[id].toLowerCase()).startsWith(filter.value.toLowerCase()) : true
    )
  }else if(row[id] !== null) {
    let re = new RegExp("^" + filter.value, "i");
    let match = (String(row[id]).match(re) === null) ? false : true;
    return match;
  }else{
    return false;
  }
}
`

**Comment by laureanopiotti** [comment]
> Solutions above didn't solve my needs, as i have number and null values as well. However great starting point, kudos to all who provided the answers. Below my 5 cents ;)
> 
> ```
> const filterCaseInsensitive = (filter, row) => {
>   const id = filter.pivotId || filter.id;
>   if(row[id] !== null && typeof row[id] === 'string') {
>     return (
>       row[id] !== undefined ?
>           String(row[id].toLowerCase()).startsWith(filter.value.toLowerCase()) : true
>     )
>   }else if(row[id] !== null) {
>     let re = new RegExp("^" + filter.value, "i");
>     let match = (String(row[id]).match(re) === null) ? false : true;
>     return match;
>   }else{
>     return false;
>   }
> }
> ```

Thanks ! That helped me with my boolean field columns
