### ISSUE TITLE
Not able to disable filter for one column.

### ISSUE THREAD

**Issue by hbulgarini** [tannerlinsley/react-table#336]
Hello ! 

I'm trying to disable the filter by adding the property "filterable:false" on one specific column , but i'm afraid that this is not working and the filter is shown anyway for that column.
Here is my setup for the specific column:

```
        const columns = [
            {
                header: '',
                accessor:'contract_id',
                filterable:false,
                render: ({value}) => (<button className="btn " onClick={(e) => this.ShowContract(e, value)}>Ver</button>)
}
```

Any ideas why it is not working? Do i'm settting in the incorrect way or the option for disable filters is not working?

Thanks!

**Comment by antoniwan** [comment]
Hi,

I was able to disable filtering by adding it like this:

```
    const columns = [
      {
        Header: 'Name',
        accessor: 'name',
      },
      {
        Header: 'E-mail',
        accessor: 'email',
        sortable: false,
        filterable: false,
      },
      {
        Header: 'Country',
        accessor: 'country',
      }
    ];
```

**Comment by tannerlinsley** [comment]
This should work just fine. https://codepen.io/tannerlinsley/pen/XgZgeg?editors=0010

**Comment by hbulgarini** [comment]
Hello Guys, thanks for your reply but i'm still not able to disable the filter after adding the filterable:false property on the column definition:
Please check my code:
```
        const columns = [
            {
                header: 'Nombre',
                accessor:'name',
                filterable:false
            },
            {
                header: 'Tipo',
                accessor: 'type',
            },
            {
                header: 'Teléfono',
                accessor: 'tel',
            },
            {
               header: 'Email',
                accessor: 'email',
            }
        ]
```
And here is how i define my react-table
```
    <ReactTable className="-striped -highlight"
                            columns={columns}
                            defaultPageSize={10}
                            data={data} // should default to []

                            loading={this.state.loading}
                            showFilters={true}
                            previousText={'Anterior'}
                            nextText={'Siguiente'}
                            loadingText={'Cargando...'}
                            noDataText={'No existen registros'}
                            pageText={'Siguiente'}
                            ofText={'de'}
                            rowsText={'lineas'}
                            getTdProps={(state, rowInfo, column, instance) => {

                                var ret = {

                                    onClick: e => {
                                        if (this.state.CurrentID ==rowInfo.row.person_id ){
                                            this.setState({CurrentID: null,CurrentName: null});
                                            this.setState({message_class: "animated fadeOut",alertmessage:""})
                                            this.setState({Visible: "hidden"})
                                        }
                                        else{
                                            this.setState({CurrentID: rowInfo.row.person_id,CurrentName: rowInfo.row.name});
                                            this.setState({message_class: "animated fadeOut",alertmessage:""})
                                            this.setState({Visible: "visible"})
                                        }


                                    }
                                }
                                if(rowInfo && (this.state.CurrentID == rowInfo.row.person_id)){
                                    ret.style = { background: '#B0C4DE'}

                                }
                                return ret;
                            }}
                    />
```
Any comments?

**Comment by paigeflourin** [comment]
still can't disable mine as well.

**Comment by sbimochan** [comment]
> columns:[{
>   sortable:false
> }]

This will disable sorting for all columns.

**Comment by sbimochan** [comment]
> This should work just fine. https://codepen.io/tannerlinsley/pen/XgZgeg?editors=0010

Only works if it is parent column.

**Comment by lyhd** [comment]
> still can't disable mine as well.

https://github.com/tannerlinsley/react-table/issues/336#issuecomment-309575199

**Comment by mmaya** [comment]
On version 7:

`
        {
            Header: 'First Name',
            accessor: 'firstName',
            disableFilters: true,
          }
`

**Comment by amir3code** [comment]
On Version 7:

```
{
    Header: 'Some Thing',
    accessor: 'something',
    disableSortBy: true
}
```

In this case you disable sorting features on a column.

**Comment by hybmg57** [comment]
This doesn't work on 7.0.4 was someone able to get it working?

**Comment by sbimochan** [comment]
> This doesn't work on 7.0.4 was someone able to get it working?

Everything works on 7 but is tricky.

**Comment by AndrewAi** [comment]
Why is it tricky? It's just a simple thing. I'm also having difficulty hiding columns by default whose value are empty, which also should be very simple but having difficulty getting it done. Any help here would be appreciated

**Comment by Matar91** [comment]
> disableSortBy: true

Thanks this worked for me `disableSortBy: true  `

**Comment by Horroon** [comment]
disableSortBy: true
Thanks worked for me but one thing still remain two caret signs after text remains there

**Comment by ankojh** [comment]
`disableSortBy: true` makes it unselectable. I am trying to make a multi-select checkbox header.

**Comment by DavidRNogueiraResi** [comment]
Is it possible to make the table to disable sorting for all columns by default, but then enable some columns selectively?

Right now, I am disabling in the Table options but enabling for the columns and it is not working. The column remains unsortable.

```
  const { getTableProps, headerGroups, getTableBodyProps, rows, prepareRow, visibleColumns } = useTable(
    { columns, data, disableSortBy: true },
    useSortBy,
    useExpanded
  );
  
    const columns: Header<SocialMediaAccount>[] = [
    {
      Header: 'header;
      accessor: 'name',
      disableSortBy: false,
      Cell: 'Cell'
      }
  ```

**Comment by sabbiu** [comment]
@Horroon 
You could use `column.canSort` to hide or show caret signs

**Comment by hrithiknaha** [comment]
`disableFilters: true` not working in v7.7

**Comment by dahalprastut** [comment]
Hi, 
i solved my issue by:
```
{
        Header: 'Category',
        accessor: 'category',
        cellClass: 'text-muted w-20',
        disableSortBy: true,
 }
```

**Comment by roman-la** [comment]
I dont understand why we mix disable filtering and disable sorting in this issue, topic was clearly about filtering...

I can confirm `disableFilters: true` works on 7.7.0

**Comment by shinstargie** [comment]
```
 {
    Header: "First Name",
    accessor: "first_name",
    disableSortBy: true, // disable sorting for this specific column
    disableGlobalFilter: true, // disable global filter for this specific column
  }
```

My react-table version is **7.7.0**

**Comment by xeiaaa** [comment]
> `disableFilters: true` not working in v7.7

@hrithiknaha you have to add an `accessor` property

**Comment by WSINTRA** [comment]
columns =  [{
      accessor: 'actions',
      Header: 'Actions',
      width: 250,
      disableSortBy: true,
      disableFilters: true,
    },..]
disableFilters: true is not working for React Table 7.7.0
disableSortBy: true is working as expected.

**Comment by jmaciaa** [comment]
On v8:
```    
const columns = [
    {
      header: 'E-mail',
      accessorKey: 'email',
      enableColumnFilter: false,
    }
]
```

**Comment by andreasbalevik** [comment]
> In the columns object, include the **disableGlobalFilter** property with a boolean value like...
> 
> ```
>  {
>     Header: "First Name",
>     accessor: "first_name",
>     disableGlobalFilter: true, // disable global filter for this specific column
>   }
> ```
> 
> My react-table version is **7.7.0**
> 
> See the section **Column Options** at the link below
> 
> https://react-table.tanstack.com/docs/api/useGlobalFilter#table-options
> 
> ![image](https://user-images.githubusercontent.com/42705232/144542580-41cfca4b-3194-4c88-8892-1c95fc076cdb.png)

`disableGlobalFilter: true` works for me.
