### ISSUE TITLE
Typescript problem with useTable hook

### ISSUE THREAD

**Issue by pilzandreas** [tannerlinsley/react-table#3388]
Please see: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54630

Versions:
@types/react-table 7.7.2
react-table 7.7.0

Here is the sandbox I set up: https://codesandbox.io/s/react-table-simple-typescript-forked-t7mtf

it works - but the code wont compile locally.

```
// Be sure to pass our updateMyData and the skipPageReset option
function Table({ columns, data, updateMyData, skipPageReset }) {
  // For this example, we're using pagination to illustrate how to stop
  // the current page from resetting when our data changes
  // Otherwise, nothing is different here.
  const {
    getTableProps,
    getTableBodyProps,
    headerGroups,
    prepareRow,
    page,
    canPreviousPage,
    canNextPage,
    pageOptions,
    pageCount,
    gotoPage,
    nextPage,
    previousPage,
    setPageSize,
    state: { pageIndex, pageSize }
  } = useTable(
    {
      columns,
      data,
      defaultColumn,
      // use the skipPageReset option to disable page resetting temporarily
      autoResetPage: !skipPageReset,
      // updateMyData isn't part of the API, but
      // anything we put into these options will
      // automatically be available on the instance.
      // That way we can call this function from our
      // cell renderer!
      updateMyData
    },
    usePagination
  );
```

The error: 

Property 'xxxxxxxxxx' does not exist on type 'TableInstance<object>'.ts(2339)

xxxxxxxxxx:
    page,
    canPreviousPage,
    canNextPage,
    pageOptions,
    pageCount,
    gotoPage,
    nextPage,
    previousPage,
    setPageSize,
    state: { pageIndex, pageSize }

seems to be a problem with @tyoes/react-table - any idea how to hotfix it?

**Comment by SQReder** [comment]
bump for this

**Comment by SQReder** [comment]
Duplicate of #3064

**Comment by pilzandreas** [comment]
> Duplicate of #3064

Thank You - was not aware of #3064
