### ISSUE TITLE
Using with create-react-app

### ISSUE THREAD

**Issue by dmaslov** [tannerlinsley/react-table#34]
Hi! I started to use `react-table` with [create-react-app](https://github.com/facebookincubator/create-react-app) tool. And i get a warnings in console. There are several of them, but every about the same issue (You should write display: flex by final spec instead of display: box)

```
./~/react-scripts/~/css-loader?importLoaders=1!./~/react-scripts/~/postcss-loader!./~/react-table/react-table.css
autoprefixer: /node_modules/react-table/react-table.css:1:7441: You should write display: flex by final spec instead of display: box
```
Am i doing something wrong? I would be a very appreciated for advice or fix!))

**Comment by tannerlinsley** [comment]
This is just a CSS warning. I'll try and take care of it.
