### ISSUE TITLE
Case insensitive filtering to check if string is in entire cell(and not just start?)

### ISSUE THREAD

**Issue by cbll** [tannerlinsley/react-table#341]
Right now the current filter methods I've seen on here check the start of the string in the cell, but not if the word is within the cell. F.e. "Windows Server 2012" wouldn't return anything if you filtered "Server 2012" with this method:

```
        const filterCaseInsensitive = (filter, row) => {
            const id = filter.pivotId || filter.id;
            if (row[id] !== null){
                return (
                    row[id] !== undefined ?
                        String(row[id].toLowerCase()).startsWith(filter.value.toLowerCase())
                        : true
                );
            }
        };
```

Which is called on the returned ReactTable by:

`defaultFilterMethod={filterCaseInsensitive}`

Is there a way to modify this custom filtermethod to include any sequence of characters in the search cell itself? 

Experimenting a bit with it myself now; i'll update if i figure it out :)

**Comment by cbll** [comment]
I read up on ES6 string methods at [Mozilla CDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String), we can use the ES6 method `includes`. It's the only thing we have to change, and it works - this is case insensitive filtering, matching any word in the cell content:

```
        const filterCaseInsensitive = (filter, row) => {
            const id = filter.pivotId || filter.id;
            if (row[id] !== null){
                return (
                    row[id] !== undefined ?
                        String(row[id].toLowerCase()).includes(filter.value.toLowerCase())
                        : true
                );
            }
        };
```

**Comment by antoniwan** [comment]
Hey,

I'm implementing a custom filter in a project. It was fairly straight-forward using this section of the docs: https://github.com/tannerlinsley/react-table#filtering

**Comment by tannerlinsley** [comment]
In the https://react-table.js.org/#/story/custom-filtering example, it's shown how to use just about any filter method you want that uses equality checking. eg.
javascript```
filterMethod: (filter, row) => (row[filter.id].includes(filter.value))
```
