### ISSUE TITLE
Documentation for the built-in filter types

### ISSUE THREAD

**Issue by pedrovrima** [tannerlinsley/react-table#3464]
I just faced the same issue and found this unanswered discussion. If it is from the project's interest, I could contribute with a filter type section on the documentation.

### Discussed in https://github.com/tannerlinsley/react-table/discussions/2859

<div type='discussions-op-text'>

<sup>Originally posted by **bendykstra94** November 16, 2020</sup>
As I understand from the [docs](https://react-table.tanstack.com/docs/api/useFilters#table-options)

filterTypes: Object<filterKey: filterType>
- Must be memoized
- Allows overriding or adding additional filter types for columns to use. If a column's filter type isn't found on this object, the column will default to using the **built-in filter types**.

there is no documentation for the built ins such as 'between'. When viewing the code-sandbox for filtering I was confused because I had not specified a 'between' filter in the filterTypes object.

Can we add a small section in the useFilter documentation under the column `filter` options: 
`Defaults to 'text'. Other built in options include 'exactText', 'exactTextCase', 'includes', 'includesAll', 'includesSome', 'includesValue', 'exact', 'equals',  and 'between'. See [here](https://github.com/tannerlinsley/react-table/blob/master/src/filterTypes.js) for implementation details`
</div>

**Comment by fseitun** [comment]
@pedrovrima please go ahead and make a PR with your proposal.
