### ISSUE TITLE
Empty table row size 

### ISSUE THREAD

**Issue by coldfish** [tannerlinsley/react-table#347]
After upgrading from 6.0.5 to 6.3.0, size of the table rows which has no value aren't the same as the others.

In the old version, cells have the `&nbsp;` value to make them equal size with other ones.

Is there any option that I can pass to library in order to get the same experience?

**Comment by tannerlinsley** [comment]
This is a bug/regression. I will add it back in asap.

**Comment by tannerlinsley** [comment]
This is fixed in version 6.4.0

**Comment by tannerlinsley** [comment]
You can also now customize what is in a pad row via the `PadRowComponent` prop :) It currently defaults to `() => <span>&nbsp;</span>`

**Comment by coldfish** [comment]
Thanks for your support @tannerlinsley
