### ISSUE TITLE
Column width auto increase/decrease

### ISSUE THREAD

**Issue by kieronsutton00** [tannerlinsley/react-table#348]
Hello,
I have quite a big table where the columns could have different widths of values. For example, a 4 digit number will have a smaller width than a full datetime.

How do I go about automatically increasing/decreasing the widths of the columns to fit all the data in? I tried manually changing the width for each column (messy, I know) but the columns quickly became out of line with data all over the place.

Thanks

**Comment by tannerlinsley** [comment]
If you are referring to an `auto` width option, we currently do not support one out of the box.  Though it is possible to build your own: https://github.com/tannerlinsley/react-table/issues/94.

Closing for triage.
