### ISSUE TITLE
API to access row order?

### ISSUE THREAD

**Issue by alexanderwhatley** [tannerlinsley/react-table#350]
After sorting by clicking a column, is there a way to access the new sorted table, or in particular the order of the items in a particular row?

**Comment by cbll** [comment]
Isn't the array itself manipulated? In such case, wouldn't you be able to access the new array in the render method? Or do you mean inside the component itself?

**Comment by alexanderwhatley** [comment]
I tried printing out the values in the table in the render method. It
doesn't appear that the reorganization of the table by clicking on the
column triggers the render method....
ᐧ

**Comment by tannerlinsley** [comment]
You need to use a `ref` like so:
```javascript
<ReactTable ref={instance => this.tableInstance = instance} />

// ... somewhere in your parent component
console.log(this.tableInstance.getResolvedState().sortedData) // log the sorted+filtered row model
```
I believe that is the array you are looking for. :)

Closing for triage.
