### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by rootux** [tannerlinsley/react-table#3502]
It's been 4 months since last commit - is this repo still alive?
If it is dead - is someone continue this project?
Does anyone know of an alternative? (In React or Vue or Vanilla)?

**Comment by fnn** [comment]
v8 is in development. Currently in alpha state and only available for GitHub sponsors (as far as I know).

https://twitter.com/tannerlinsley/status/1446903719430266888

**Comment by fseitun** [comment]
No. It isn't dead an as stated V8 is near!
