### ISSUE TITLE
div.ReactTable has no height on Chrome or Safari iOS

### ISSUE THREAD

**Issue by antoniwan** [tannerlinsley/react-table#351]
## Problem Description
div.ReactTable has no height on mobile Chrome and Safari iOS.

This causes the tables to not be visible.

If you add something similar to  `div.ReactTable { height: 1000px }` to provide the .ReactTable div with some fixed height, the table will show.

## System Information
* **react-table Version: `"react-table": "^6.3.0",`**
* **Browser & Browser Version: Latest Safari version from an iPhone 7 Plus - iOS 10.3**
* **Node Version: `v6.9.5`**
* **OS Version: macOS Sierra v10.12.5**
* **NPM Version: `4.6.1`**
* **Yarn Version: `yarn install v0.24.5`**

**Comment by antoniwan** [comment]
The table is there, but not showing.

## Safari on an iPhone 7 Plus - iOS 10.3 screenshots
![screen shot 2017-06-19 at 5 03 06 pm](https://user-images.githubusercontent.com/588388/27305879-7bad0046-5511-11e7-960a-90f073ded49a.jpg)
![screen shot 2017-06-19 at 5 03 24 pm](https://user-images.githubusercontent.com/588388/27305880-7cea8208-5511-11e7-90fd-dc798b3e3b43.jpg)


### package.json dev and normal dependencies

```
"dependencies": {
    "axios": "^0.16.2",
    "firebase": "^4.1.2",
    "moment": "^2.18.1",
    "prop-types": "^15.5.10",
    "react": "^15.5.4",
    "react-bootstrap": "^0.31.0",
    "react-dom": "^15.5.4",
    "react-router-bootstrap": "^0.24.2",
    "react-router-dom": "^4.1.1",
    "react-table": "^6.3.0",
    "victory": "^0.21.0"
  },
  "devDependencies": {
    "react-scripts": "1.0.7"
  },
```

**Comment by coldfish** [comment]
+1.

**Comment by shivekkhurana** [comment]
Setting `display: block` on .ReactTable fixes some part of the issue. See #304.

**Comment by jmtoung** [comment]
+1

**Comment by joelrorseth** [comment]
I also ran into this issue on both Safari and Chrome mobile iOS apps. Would like to confirm that manually overriding `display: block` fixed it. It seems that **react-table/react-table.css** sets `display: flex`, which must be causing these issues.

**Comment by tannerlinsley** [comment]
Please make sure you are running the latest version of React-Table. As far as we know, we have tested on all major browsers and devices with all other styles disabled and everything looks great. Use https://codepen.io/tannerlinsley/pen/QpeZBa?editors=0110 for reference.

**Comment by WebAppUI-dev** [comment]
I suspect that those having problems may mostly be using create-react-app, as I know that an upgrade of react-scripts caused the same result in safari for my project.  display: block on .ReactTable seems to fix it for me, but the real cause may have to do with autoprefixer config changes that are modifying the react-table styles.

https://github.com/facebookincubator/create-react-app/commit/044e57b726afa18d6fc009efe93f64429853208a#diff-d2bddbd3bfb7051f9381474c844674fa

**Comment by joeferraro** [comment]
I'm experiencing this issue on iOS as well. `display: block` resolves the height issue but impacts the layout of the table.
