### ISSUE TITLE
Calling onExpandedChange in getTdProps -> onClick

### ISSUE THREAD

**Issue by kieronsutton00** [tannerlinsley/react-table#353]
When updating the expanded rows for the onClick event inside getTdProps, the onExpandedChant event is not called and the expanded state does not update.

This is my code:
`var expands = {};

getTdProps: function getTdProps(state, rowInfo, column, instance) {
                return {
                    onClick: function onClick(e) {
                        expands[rowInfo.index] = true;
                        console.log(expands)
                    }
                }
            },
            expanded: expands,
            onExpandedChange: function(newExpanded, index, event) {
                console.log(newExpanded)
            }`

ReactTable version: 6.4.0

**Comment by kieronsutton00** [comment]
any ideas?

**Comment by kolbeypruitt** [comment]
I also need this. There seems to be no way to access the `row` data from the onExpandChange function.

**Comment by tannerlinsley** [comment]
Here is a demo of manually handling the expanded prop: https://codepen.io/tannerlinsley/pen/NgygGZ?editors=0010
Closing for triage.
@kolbeypruitt what is your use case? You should join the slack group for more discussion :)
<a href="https://react-chat-signup.herokuapp.com/" target="\_parent">
  <img alt="" src="https://img.shields.io/badge/slack-react--chat-blue.svg" />
</a>
