### ISSUE TITLE
Does the react-table take height as %?

### ISSUE THREAD

**Issue by frankp3836** [tannerlinsley/react-table#354]
Hi,

I'm trying to set height to react-table. I'm passing the style through style attribute and through className as well, it's taking numeric value as px but I'm unable to set a % as height. It's taking width as % but not height. Any suggestions??

Thanks,

**Comment by tannerlinsley** [comment]
You can set the height on the ReactTable component using the `style` prop as you would with any other component. It is important to note though, ReactTable's height is largely based on the number of rows being displayed and less on the style. For more questions, join slack :)
<a href="https://react-chat-signup.herokuapp.com/" target="\_parent">
  <img alt="" src="https://img.shields.io/badge/slack-react--chat-blue.svg" />
</a>
