### ISSUE TITLE
on state update the expanded row is getting closed.

### ISSUE THREAD

**Issue by AjayShivanagol** [tannerlinsley/react-table#3540]
please find the code link here https://codesandbox.io/s/agitated-dubinsky-t0hcn?file=/src/nestead-table/index.js:8254-8263
on state updates like selecting the checkbox, the expanded row is getting closed.

**Comment by AjayShivanagol** [comment]
any updates please?

**Comment by fseitun** [comment]
I'm checking your sandbox and the row isn't closing on selected row. Did you solve it? Closing for the time being.

**Comment by AjayShivanagol** [comment]
@fseitun I did a kind of hack like changing checkbox value using jquery.......the issue is still persisted if I update the state it's closing.
