### ISSUE TITLE
Initial Filtering

### ISSUE THREAD

**Issue by andreoliveirawinny** [tannerlinsley/react-table#355]
## Problem Description
Hi. I would like to filter the table on the first render using, for example, an ID.
is that possible? I am passing an array to the 'defaultFiltered' props, but nothing happens.

Thank you.

**Comment by cbll** [comment]
That would likely be done outside of your render function, f.e. a callback function in `componentWillMount`

**Comment by tannerlinsley** [comment]
Please see here: https://codepen.io/tannerlinsley/pen/OgQmKa?editors=0010 for how to use `defaultFiltered` Or join us on slack for more discussion!
<a href="https://react-chat-signup.herokuapp.com/" target="\_parent">
  <img alt="" src="https://img.shields.io/badge/slack-react--chat-blue.svg" />
</a>

**Comment by vivek7890** [comment]
@tannerlinsley Here you have mentioned a single value for the filter. Can we use an array of key and values for filter and if how can it be done? thanks

**Comment by arun-qfor** [comment]
> Please see here: https://codepen.io/tannerlinsley/pen/OgQmKa?editors=0010 for how to use `defaultFiltered` Or join us on slack for more discussion!
> [ ![](https://camo.githubusercontent.com/4a927a3b216b428cdfb3aaa63ade71504b6b7f2c/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f736c61636b2d72656163742d2d636861742d626c75652e737667) ](https://react-chat-signup.herokuapp.com/)

Thanks a lot. It is working for me :)
