### ISSUE TITLE
Is there possible for without case sensitive  in column search?????

### ISSUE THREAD

**Issue by shaikjohnsaida** [tannerlinsley/react-table#356]
Is there possible for case sensitive search in column search?????

**Comment by cbll** [comment]
I do believe the standard filter method is case sensitive?

**Comment by shaikjohnsaida** [comment]
Thanks for giving reply.then is there any way to get without case
sensitive????

**Comment by cbll** [comment]
Ease on the questionmarks man :)

Yes, just search the issues, it's been brought up a lot of times.

**Comment by kieckhafer** [comment]
This is what we are using for a custom filter... it is not case sensitive, and also searches full text instead of just the start of the word:

```
customFilter = (filter, row) => {
    const id = filter.pivotId || filter.id;
    if (row[id] !== null && typeof row[id] === "string") {
      return (row[id] !== undefined
        ? String(row[id].toLowerCase()).includes(filter.value.toLowerCase())
        : true);
    }
  }
```

and then when calling `<ReactTable />`:
```
defaultFilterMethod={this.customFilter}
```

Hope that helps.

**Comment by HartmanAnalytics** [comment]
This breaks other filters with integer data types
