### ISSUE TITLE
getHeaderProps() warns of unknown/illegal React prop

### ISSUE THREAD

**Issue by karbica** [tannerlinsley/react-table#357]
## Problem Description
The `getHeaderProps` callback throws an unknown prop warning but the other prop getter methods do not and work fine. It only occurs when a property is returned that does not pass as a DOM element attribute observed by React. To simplify, `onClick`, `onMouseOver`, `style`, work fine but custom properties like `sortOrder` trigger the warning.

As mentioned before, the other two similar methods, `getProps` and `getFooterProps` work fine.

## Code Snippet(s) or Codepen
https://codepen.io/anon/pen/OggxYb?editors=0010
You can see the error in the console. `getProps` and `getFooterProps` are in there to show the difference.

## Steps to Reproduce
1. create a columns array and add a columns object.
2. implement `getHeaderProps` and have it return an arbitrary key/value pair.
3. console will indicate that the prop is unknown/illegal to DOM elements with a link to the React page discussing it further.

## System Information
* **Browser & Browser Version:** Google Chrome Version 59.0.3071.109 (Official Build) (64-bit)
* **Node Version:** v7.10.0
* **OS Version:** macOS Sierra 10.12.5
* **NPM Version:** v5.0.3
* **Yarn Version:** v0.24.6

**Comment by aaronschwartz** [comment]
Just curious, whats the use case for passing an invalid prop to the component being rendered?

**Comment by karbica** [comment]
I'm using `getHeaderProps` to get the `state.sorted` array which I then access in the component I gave to `Header` in the column definition. The custom header component handles presenting the custom sort indicators.

The props in `Header` when providing a function do not expose the sorted state of the column or any state for that matter.

Basically, I want to provide the sorted array as a prop to a custom header component.

**Comment by tannerlinsley** [comment]
You are correct. `ThComponent` would be much better suited for this.  Closing for triage :) For more discussion, join us on slack!
<a href="https://react-chat-signup.herokuapp.com/" target="\_parent">
  <img alt="" src="https://img.shields.io/badge/slack-react--chat-blue.svg" />
</a>
