### ISSUE TITLE
[Question] Sorting involving numbers 

### ISSUE THREAD

**Issue by KenLeeKH** [tannerlinsley/react-table#358]
## Problem Description
Hi
I have just download this to try and when there are numbers involved, it seems that the sorting is weird. Example, if I have 2, 500 and 80, sorting by desc order, I will assume it will be:
500
80
2

But instead, I got the below (with no custom sorting)
80
500
2

Sorting in ascending order will get me:
2
500
80

It seems to be sorting according to the first character. I am passing in the data as a string, is there anything I should note on how to make the sorting be aware that it is an integer? Thanks!

**Comment by aaronschwartz** [comment]
This is the default sorting method: 
```
  defaultSortMethod: (a, b) => {
    // force null and undefined to the bottom
    a = a === null || a === undefined ? '' : a
    b = b === null || b === undefined ? '' : b
    // force any string values to lowercase
    a = typeof a === 'string' ? a.toLowerCase() : a
    b = typeof b === 'string' ? b.toLowerCase() : b
    // Return either 1 or -1 to indicate a sort priority
    if (a > b) {
      return 1
    }
    if (a < b) {
      return -1
    }
    // returning 0, undefined or any falsey value will use subsequent sorts or the index as a tiebreaker
    return 0
  },
```
If you pass it a string it will sort it as a string. You have a few options:
* You can modify your data before passing it to react-table and make them integers
* I believe you can cast it to an integer using the `accessor` e.g. `accessor=(row)=>parseInt(row.stringColumn)`
* You can implement a custom `sortMethod` for that column.

Closing for now. You can join the react-chat slack channel if you need more implementation help.

https://react-chat-signup.herokuapp.com/

**Comment by KenLeeKH** [comment]
Thank you very much, I managed to get it working based on what you have posted
