### ISSUE TITLE
Problems to call props in a redux app or how to cascade props on callback functions?

### ISSUE THREAD

**Issue by emanuelgomez** [tannerlinsley/react-table#359]
## Problem Description
Im following this example https://react-table.js.org/#/story/server-side-data in order to adapt it to my app needs.  Thanks in advance for any help

i have the function to fetch data on my props 
```
const mapDispatchToProps = {
  loadShops
}
```

In my component, this works well
```
  componentDidMount() {
    this.props.loadShops()
  }
```

In the same component im using react table like this
```
fetchData(state,instance) {
     this.props.loadShops() //  **im not able to get the component's original Props, how do i cascade the props?**
}

render() {
store=//.....
columns=//.......
return(
<ReactTable
 data={store}
 columns={columns}
 pages={10} // Display the total number of pages
 onFetchData={this.fetchData}
  />
)
}
```

When onFetchData callback is made i have no way to access this.props.loadShops it seems out of context on callback. 

## System Information
* **"react-table": "^6.3.0",**

**Comment by emanuelgomez** [comment]
I've found a way to solve this. 


```
fetchData(state,instance) {
     instance.props.customProps.loadShops() 
}

render() {
store=//.....
columns=//.......
return(
<ReactTable
 data={store}
 columns={columns}
 pages={10} // Display the total number of pages
 onFetchData={this.fetchData}
 customProps={this.props}
  />
)
}

```

**Comment by aaronschwartz** [comment]
I don't think that's the best way to do it.

I think you're running into a common issue people run into when they're writing react classes.

You need to bind your `fetchData` function to your class.

See: http://blog.andrewray.me/react-es6-autobinding-and-createclass/

**Comment by emanuelgomez** [comment]
thanks aaron!
