### ISSUE TITLE
Add a full text search filter

### ISSUE THREAD

**Issue by twheys** [tannerlinsley/react-table#36]
Please add a full text search filter akin to datatables.js.  This should include some UI such as a text box above the table and should search all columns/rows and filter the rows that do not match.  Please also expose a javascript function for setting a full text search filter.

**Comment by tannerlinsley** [comment]
Similar to #37, react-table doesn't package this functionality in the core.  We may provide extensions in the future, but for now, you can implement this functionality on your own fairly easily.

1. Add the necessary UI above your react-table (probably just a text box will do)
1. When the state of the text box changes, filter your data accordingly using something like https://github.com/kentcdodds/match-sorter or https://lodash.com/docs/4.17.4#filter
2. Pass the newly filtered data to `react-table`

As react-table matures, we may discuss including functionality like this, but for now, we're opting for a leaner extension-like api to achieve such functionality.

**Comment by scottfr** [comment]
This feature would be very useful. Is it considered in the roadmap?
