### ISSUE TITLE
Trying filterable

### ISSUE THREAD

**Issue by Ishneetkaur** [tannerlinsley/react-table#361]
## Problem Description
I tried "filterable" and can't seem to see any filters

## Code Snippet(s)

const rawData = _.map(_.range(3424), d => {
    return {
        firstName: namor.generate({ words: 1, numbers: 0 }),
        lastName: namor.generate({ words: 1, numbers: 0 }),
        age: Math.floor(Math.random() * 30)
    }
})

<ReactTable
      className='-striped -highlight'
      columns={[{
              header: 'First Name',
              accessor: 'firstName'
            }, {
              header: 'Last Name',
              id: 'lastName',
              accessor: d => d.lastName
            }, {
              header: 'Age',
              accessor: 'age'
            }]}
     filterable
     data={rawData} // Set the rows to be displayed
/>

Please tell if I am missing something?
![screen shot 2017-06-22 at 10 47 02 am](https://user-images.githubusercontent.com/8664494/27448053-27aa46ec-5738-11e7-99e6-a6f7b7b1da9d.png)

**Comment by Ishneetkaur** [comment]
was missing showFilters as true!

**Comment by aaronschwartz** [comment]
Note: `showFilters` is for version < 6.0.0. `filterable` is for version > 6.0.0
