### ISSUE TITLE
vertical-scroll example

### ISSUE THREAD

**Issue by yemingshi** [tannerlinsley/react-table#362]
I'm looking at this story for vertical-scroll support: https://react-table.js.org/#/story/fixed-header-w-vertical-scroll

It appears to me that the code is no different than the the basic example. How do I enable vertical scrolling? I'm using version 6.4.0.

**Comment by junbinku** [comment]
How did u get to solve this?

**Comment by Jefski14** [comment]
Just give the table a fixed height.
It's written in the example:

```
style={{
  height: "400px" // This will force the table body to overflow and scroll, since there is not enough room
}}
```

**Comment by Raaseem** [comment]
style={{ maxHeight: '350px',  overflowY: 'auto' }}
