### ISSUE TITLE
Question: range select on table

### ISSUE THREAD

**Issue by dgildeh** [tannerlinsley/react-table#3636]
I’m trying to implement range select on my table where a user can hold down shift, select one row, then another, and both rows with any in between are selected. 

I can’t find any good examples of the best way to do this using react-table and was wondering how I would approach implementing that feature using the library?

I tried this callback function to select rows using the index buts it’s extremely unreliable and non performant for table with only 150 rows.

**Comment by dgildeh** [comment]
Apologies - I only noticed the discussions tab for this repo after I raised this issue, but hopefully can keep this as a reference for other users searching for a solution to this. 

I figured out a solution after a few hours playing around. In the end I couldn't use the out of the box useRowSelect plugin because it's missing the ability to update all the selected rows in one function call (probably need to add a toggleRowsSelect callback function that accepts an array of selected row IDs cc @tannerlinsley), so used local component state to keep track of selected fields. 

In addition because the onClick callback function had to be updated with every selection update, it was forcing the entire table to re-render every row, which in my 150 row table was slow and led to a lot of lag between clicking and highlighting the selected row(s). I decided to move all onClick event callbacks to the tbody element and added a data-row-index attribute to every row so I could lookup which row was being clicked. I also built a Row component that used the useMemo hook to return on render so only rows that were selected needed to be re-rendered when the selection changed and significantly improved the performance of the table after the initial render.

I also think a new plugin to add table wide onclick/ondoubleclick/oncontextmenu event listeners to tables at the tbody level would be cool, and significantly improve performance for larger/slower tables. I'll look into creating one in future if I have time (cc @tannerlinsley )

One issue I noticed is the row.index doesn't match the index of the row in the rows array when using the useSortBy plugin - so in my code below you'll see I need to do an additional indexOf to find the row's index position in the sorted array. I'm not sure what the row.index field is for tbh, its confusing, and updating if the sort is changed will cause every row to re-render, so wondering if this field could be depreciated in future versions (cc @tannerlinsley )

Anyway, I can't share the full code as its in a private repo, but here are the key parts for anyone looking to do range selection on React-Table (TypeScript):

**1. Helper Function to lookup row from tbody onClick handler using data-row-index attribute on each row**
```
/**
 * Gets the current row being clicked from the 'data-row-index' attribute on the parent <tr>
 * element for any click event. Using this approach to avoid row re-renders whenever click handler
 * callbacks are updated
 * 
 * @param target  The Target HTMLElement (event.target) that raised the event
 * @param rows    The list of sorted rows
 */
function getRowFromEvent(target: HTMLElement, rows: Row<any>[]) {
  const rowIndex = parseInt(target.closest('tr').getAttribute('data-row-index'))
  const filteredRows = rows.filter((row) => row.index == rowIndex)
  if (filteredRows.length) {
    // Should only be one result
    return filteredRows[0]
  }
  return null
}
```

**2. Example of tbody onClick handler using helper function - provides double click checking too**

```
  // Local variables to help differentiate between
  // single click and double click
  const [timer, setTimer] = React.useState<NodeJS.Timeout>(undefined)
  const [prevent, setPrevent] = React.useState<boolean>(false)

.....

<TableBody
              {...getTableBodyProps()}
              onClick={(event) => {
                const row = getRowFromEvent(event.target as HTMLElement, rows)
                setTimer(setTimeout(function () {
                  if (!prevent) {
                    handleRowSelection(event, row)
                  }
                  setPrevent(false)
                }, 200))
              }}
              onDoubleClick={(event) => {
                const row = getRowFromEvent(event.target as HTMLElement, rows)
                clearTimeout(timer)
                setPrevent(true)
                row.toggleRowExpanded()
              }}
              onContextMenu={(event) => {
                console.log('context', event)
                const row = getRowFromEvent(event.target as HTMLElement, rows)
                handleContextMenu(event, row)
              }}
            >
```

**3. The actual function that does all the selection logic**

```
  const [selectedRowIds, setSelectedRowIds] = useState<string[]>([])
  const [selectedRows, setSelectedRows] = useState<Row<any>[]>([])

/**
   * Handle Row Selection:
   * 
   * 1. Click + CMD/CTRL - Select multiple rows
   * 2. Click + SHIFT - Range Select multiple rows
   * 3. Single Click - Select only one row
   */
  const handleRowSelection = React.useCallback((
    event: React.MouseEvent<HTMLTableSectionElement>,
    row: Row<TransactionRow>,
  ) => {

    // See if row is already selected
    const selectIndex = selectedRowIds.indexOf(row.id)
    const isSelected = selectIndex > -1

    let updatedSelectedRowIds = [...selectedRowIds]
    let updatedSelectedRows = [...selectedRows]

    if (event.ctrlKey || event.metaKey) {
      // 1. Click + CMD/CTRL - select multiple rows

      if (isSelected) {
        updatedSelectedRowIds.splice(selectIndex, 1)
        updatedSelectedRows.splice(selectIndex, 1)
      } else {
        updatedSelectedRowIds.push(row.id)
        updatedSelectedRows.push(row)
      }

    } else if (event.shiftKey) {
      // 2. Click + SHIFT - Range Select multiple rows

      if (selectedRows.length) {
        const lastSelectedRow = selectedRows[0]
        // Calculate array indexes and reset selected rows
        const lastIndex = rows.indexOf(lastSelectedRow)
        const currentIndex = rows.indexOf(row)
        updatedSelectedRowIds = []
        updatedSelectedRows = []
        if (lastIndex < currentIndex) {
          for (let i = lastIndex; i <= currentIndex; i++) {
            const selectedRow = rows[i]
            updatedSelectedRowIds.push(selectedRow.id)
            updatedSelectedRows.push(selectedRow)
          }
        } else {
          for (let i = currentIndex; i <= lastIndex; i++) {
            const selectedRow = rows[i]
            updatedSelectedRowIds.push(selectedRow.id)
            updatedSelectedRows.push(selectedRow)
          }
        }

      } else {
        // No rows previously selected, select only current row
        updatedSelectedRowIds = [row.id]
        updatedSelectedRows = [row]
      }

    } else {
      // 3. Single Click - Select only one row

      updatedSelectedRowIds = [row.id]
      updatedSelectedRows = [row]
    }

    setSelectedRowIds(updatedSelectedRowIds)
    setSelectedRows(updatedSelectedRows)

  }, [selectedRowIds, selectedRows, rows])
```

**4. And finally the part to render your rows in tsx**

```
rows.map((row) => {
                  prepareRow(row)
                  return (
                    <TableRow
                      key={row.getRowProps()["key"]}
                      row={row}
                      isSelected={selectedRowIds.indexOf(row.id) > -1}
                    />
                  )
```

Hope this helps. Summary of asks for future development (cc @tannerlinsley ):

1. toggleRowsSelection - can pass in array of all selected rows for useRowSelect plugin, would have saved me having to do my own separate code to store selection state
2. Depreciation of row.index field as its confusing and doesn't appear to match the row's array index when using sorting
3. Potential addition of plugin to add click handlers to tbody and find row using data attribute on each row instead of adding onClick callbacks to each row, which forces the entire table to re-render each time the callback function is changed

**Comment by volodymyrdn** [comment]
I have made it like this: 
rows have an onClick event:
```
<tr key={row.id}
    onClick={(evt) => handleRowSelect(evt, row)}
    style={{ backgroundColor: row.getIsSelected() ? "red" : undefined }}
>

```
And the event handler looks like this: 

```
    const handleRowSelect = (evt: React.MouseEvent, row: Row<Person>) => {
        if (evt.ctrlKey) {
            row.toggleSelected()
        } else if (evt.shiftKey) {
            const lrIndex = lastRowSelected?.current?.index ?? row.index
            const fromIndex = Math.min(lrIndex, row.index)
            const toIndex = Math.max(lrIndex, row.index)
            const rowselection: any = {}
            for (let i = fromIndex; i <= toIndex; i++) {
                rowselection[i] = true
            }
            setRowSelection(rowselection)
        }
        else {
            table.resetRowSelection(false)
            row.toggleSelected(true)
        }

        lastRowSelected.current = row   // lastRowSelected is a ref
    }
```

Tested in a virtualized table with 300K rows, and it takes nothing to select all rows

**Comment by dgildeh** [comment]
This looks much cleaner - I've virtualised the table now so adding click listeners to each row works now, before I had to do one at the tbody and use a data-index property to work out which row was clicked as it was to large to add 1000's of onclick event listeners. 

I'll try this when I'm next working on the table. Thanks!

**Comment by jonathanhudak** [comment]
```tsx

cell: ({ row, table }) => (
      <Checkbox
        checked={row.getIsSelected()}
        onClick={(e): void => {
          if (e.shiftKey) {
            const { rows, rowsById } = table.getRowModel();
            const { rowSelection } = table.getState();
            const lastSelectedRowIndex =
              Math.max(...Object.keys(rowSelection).map(Number)) ?? 0;
            const rowsToToggle = getRowRange(
              rows,
              row.index,
              lastSelectedRowIndex
            );
            const isCellSelected = rowsById[row.id].getIsSelected();
            rowsToToggle.forEach((_row) =>
              _row.toggleSelected(!isCellSelected)
            );
          } else {
            row.toggleSelected();
          }
        }}
```

**Comment by Innders** [comment]
> I have made it like this:

Thanks for the great snippet. I have taken it and added support for **subRows**, id for selection keys and ctrl + shift selection combinations!

```tsx
  const lastRowSelected = useRef<Row<Folder> | null>(null)

  const handleRowSelect = useCallback(
    (event: MouseEvent, row: Row<Folder>) => {
      const handleMultiSelect = () => {
        row.toggleSelected()
        lastRowSelected.current = row
      }

      const handleShiftSelect = () => {
        if (!row) return

        const lastIndex = lastRowSelected?.current?.index ?? row.index
        const [fromIndex, toIndex] = [
          Math.min(lastIndex, row.index),
          Math.max(lastIndex, row.index),
        ]

        const siblingRows = row.getParentRow()?.subRows ?? rows
        const newRowSelection = { ...rowSelection }

        siblingRows.slice(fromIndex, toIndex + 1).forEach((row) => {
          if (row?.id && !newRowSelection[row.id]) {
            newRowSelection[row.id] = true
          }
        })

        setRowSelection(newRowSelection)
      }

      const handleSingleSelect = () => {
        table.resetRowSelection(false)
        row.toggleSelected(true)
        lastRowSelected.current = row
      }

      if (event.ctrlKey || event.metaKey) handleMultiSelect()
      else if (event.shiftKey) handleShiftSelect()
      else handleSingleSelect()
    },
    [rows, rowSelection, table],
  )
```
