### ISSUE TITLE
Fixed columns

### ISSUE THREAD

**Issue by Alex-Ferreli** [tannerlinsley/react-table#364]
## Feature Description
How can i fix some columns to the table? When i scroll horizontally, i would have the first 2 columns of 20 (for example) fixed to the start of table.

Awesome plugin, thanks for the hard work!

**Comment by gnain** [comment]
More generic feature request, but similar to #334

**Comment by tannerlinsley** [comment]
Thanks!  This is currently not supported, but we are well aware of the feature request. Thanks for your input! Closing for triage. Join us in slack for more discussion :)
<a href="https://react-chat-signup.herokuapp.com/" target="\_parent">
  <img alt="" src="https://img.shields.io/badge/slack-react--chat-blue.svg" />
</a>
