### ISSUE TITLE
Using two JSON files

### ISSUE THREAD

**Issue by zlatianiliev** [tannerlinsley/react-table#365]
Can someone help me a problem I am having.
I want to use two json files (known and unknown words) for the data. 

The problem is that in the json I have [{word: "cat", wordId: "123123"},{word: "dog", wordId: "234234"},...]. I want to display two columns: 1. the word 2. a tick if the word is known and an empty string if the word is unknown. My problem is that there is I don't know how to say (knownwords) ? `✓` : ``, because I need to concat the two arrays before passing the data. 

Or if someone knows how to make the table with 2 data sources. 

<ReactTable
            data={data1, data2}
            columns={this.state.columns}/>

**Comment by karbica** [comment]
This is not the concern of react-table.

You need to get your two JSON files into a single JSON file which then becomes the array you feed into react-table. Your array you provide will contain both known words and unknown words. From there, you can modify the `Cell` property in the column to use a functional component that you made which will render an icon based on the value.

Make your two JSON files become one. Then react-table provides everything else to do what you need.

```javascript
const data = [
  { word: 'cat', wordId: '123123' },
  { word: 'dog', wordId: '234234' },
  { word: 'snake', wordId: '' },
  { word: 'snail', wordId: '' }
];
```

**Comment by zlatianiliev** [comment]
I am concatenating them, but the problem there is that I have no unique prop like isDone: 'yes', because that is what the server is giving me. So when they become 1 array, I no longer have a way to determine if they keyword is known or unknown.

**Comment by karbica** [comment]
When the data comes from the server, can you map over the arrays in each file. One file gets a property added called `isDone: true` and the other file gets a property `isDone: false` added. So now all the words in the array have the `isDone` property.

As long as you know which array is known and unknown, you can add properties to your data to know which one is which.

Then when the array is concatenated, you'll have word objects that indicate which one is which.

**Comment by tannerlinsley** [comment]
Closing this for triaging as it is not related to a bug or feature of react-table. Please join us in slack if you have more questions!
<a href="https://react-chat-signup.herokuapp.com/" target="\_parent">
  <img alt="" src="https://img.shields.io/badge/slack-react--chat-blue.svg" />
</a>
