### ISSUE TITLE
update data with setState, ReactTable not update UI

### ISSUE THREAD

**Issue by navono** [tannerlinsley/react-table#367]
## Problem Description
I have a  custom ReactTable, it receive the data from caller, and the caller change the data when ReactTbale row trigger a click event.
Code sample:
class customRTable extends Component {
...
 handleRowClick (rowInfo) {
    this.props.onRowSelected(rowInfo.index);
  }
render() {
    return (
      <div className="table-wrap">
        <ReactTable
          data={this.props.items}
          columns={this.state.columnTitle}
          className='-striped -highlight'
          defaultPageSize={10}
          style={{
              height: '300px' // This will force the table body to overflow and scroll, since there is not enough room
            }}
          filterable={true}
          getTrProps={(state, rowInfo, column, instance) => {
            return {
              onClick: e => {
                return this.handleRowClick(rowInfo);
              }
            }
          }}
          />
      </div>
    )
  }
}

class CallerComponent extends Component {
  constructor () {
   super();
  this.state = {
    currentShowItems: [
    {name: 'Jim', age: 12 },
    {name: 'Li', age: 13} 
    ]
  }
}

hanleRowSelected (rowIndex) {
  let newItems= this.state.currentShowItems;
    newAlarmItems[row].age= newAlarmItems[row].age++;
    this.setState({
      currentShowItems: newAlarmItems
    });
}

 render () {
   return (
    <div>
        <customRTable items={this.state.currentShowItems} onRowSelected={this.hanleRowSelected} />
   <div>
  )
}
}

## System Information
Browser: Chrome 59
Node Version: 8.0.0
OS Version: win10
NPM Version: 5.0.0

I follow the source code, and find the reason. In lifecycle.js, componentWillReceiveProps,
the oldState and newState is the same when I click the table row to change the data. So it will not execute the this.setStateWithData(this.getDataModel(newState)). cause the resolvedData not update.

 // Props that trigger a data update
  if (
        oldState.data !== newState.data ||
        oldState.columns !== newState.columns ||
        oldState.pivotBy !== newState.pivotBy ||
        oldState.sorted !== newState.sorted ||
        oldState.filtered !== newState.filtered
      ) {
        this.setStateWithData(this.getDataModel(newState))
  }

**Comment by aaronschwartz** [comment]
In the future please format your code using the editors code formatting.

Also your example seems to be have a lot of function/variable names that don't match up to anything else. But I think I get what you're trying to do.

The most common cause of what you're seeing is that you're mutating state directly instead of creating a new copy.

For example, your handleRow function should look something like this:

```
handleRowSelected (rowIndex) {
  const newItems= {...this.state.currentShowItems};
  newItems[row] = {
    ...newItems[row],
    age: newItems[row].age + 1
  };
  this.setState({
    currentShowItems: newItems
  });
}
```

See
https://medium.com/pro-react/a-brief-talk-about-immutability-and-react-s-helpers-70919ab8ae7c 
for more information.

**Comment by navono** [comment]
Yes, keep state immutable is fine, and I modify the code. But the key here is in lifecycle.js, when the data changes, it not trigger a data update, because the trigger condition is true. oldState and newState is the same.

**Comment by tannerlinsley** [comment]
Aaron is correct. Create a new array instead of reusing the existing array.
React table checks using referential integrity. So if you do not create a
new array, the change detection will not trigger

**Comment by navono** [comment]
Sorry guys. It's my mistake. When I change the code with this:
```js
handleRowSelected (rowIndex) {
  let newItems= [...this.state.currentShowItems];
  newItems[row] = {
    ...newItems[row],
    age: newItems[row].age + 1
  };
  this.setState({
    currentShowItems: newItems
  });
}
```
It's work.
I learn React in recently, lack some practice knowledge.
Thank you for the detailed explanation, and React-Table is great!
