### ISSUE TITLE
Problem with custom checkbox column on paging

### ISSUE THREAD

**Issue by yjfoo** [tannerlinsley/react-table#368]
## Problem Description
I've made a column with checkbox. So if the user checks this row's checkbox, I'll add this row data to state and on uncheck will remove this row data from state.
I've also set the defaultPageSize to 5 and have 10 rows of test data. The issue is when I checked the 1st row checkbox and when I go to "Next Page" somehow the 6th row checkbox also appears checked. However only 1st row data is saved in state this is correct. Is there some additional settings I need to do for "Cell"?

## Code Snippet(s) or Codepen (http://codepen.io/tannerlinsley/pen/QpeZBa?editors=0010)
Checkbox column
`{
	  	Header: 'Add',
	  	accessor: 'add',
	  	Cell: row => (
			<input type="checkbox"
			disabled={row.value === 'NOK' ? 'disabled' : ''}
			onChange={()=>this.handleCheckboxChange(row)}
			/>
	  	)
}`
## Steps to Reproduce
1. list the steps
2. to reproduce the issue

## System Information
* **Browser & Browser Version:**
* **Node Version:**
* **OS Version:**
* **NPM Version:**
* **Yarn Version:**

**Comment by aaronschwartz** [comment]
You didn't provide enough information to accurately diagnose your particular example.

Please see here for a working checkbox example:
https://codepen.io/aaronschwartz/pen/WOOPRw?editors=0010

If you need further implementation help we would be glad to give you suggestions in the slack channel:
https://react-chat-signup.herokuapp.com/
