### ISSUE TITLE
Add select box filters for filtering columns

### ISSUE THREAD

**Issue by twheys** [tannerlinsley/react-table#37]
Please add an option for enabling a (multi) select box filter which lists distinct values in the column.  This should be configurable on a per column basis.  When one or more options are selected, the table should be filtered to only display rows which match the selection.

**Comment by tannerlinsley** [comment]
React-Table, in it's current form, gives you the api to achieve this on your own, but you will need to implement your own UI and filtering methods. Try the following:

1. Pass your own react component to the `header` field for your column. In that component you can implement any type of UI that you want for filtering: select, string input, multi-select, or even [react-select](https://github.com/JedWatson/react-select)
1. You will need to create and populate any options for the column UI from the original dataset (before filtering it)
1. When your column's filter state changes, apply that filter state the original dataset using something like https://github.com/kentcdodds/match-sorter or https://lodash.com/docs/4.17.4#filter
1. Pass the new filtered array to `react-table`

**Comment by twheys** [comment]
Ok, I will consider creating an extension then. Thanks for the suggestions.
