### ISSUE TITLE
Looking to render API data in the table. 

### ISSUE THREAD

**Issue by Sm00g15** [tannerlinsley/react-table#370]
## Problem Description
How can I render JSON data from an API endpoint from coincap.io/front in the react-table? Super noob at all this and very confused. 

## Steps to Reproduce
1. list the steps
2. to reproduce the issue

## System Information
* **Browser & Browser Version:**
* **Node Version:**
* **OS Version:**
* **NPM Version:**
* **Yarn Version:**

**Comment by cbll** [comment]
That's not related to the react-table component itself, but rather you need to make a fetch to the API... Using something like jQuery(not worth it for only making Ajax calls), or axios.

**Comment by Sm00g15** [comment]
alright, thanks. Do you have any good axios tutorials for reference?

**Comment by cbll** [comment]
Official docs are sufficient I think, but depends on your skill level?

https://github.com/mzabriskie/axios

For example, this is a GET request that you'd put in componentDidMount usually:

```
axios.get('/user?ID=12345') // The URL for wherever you wanna get data from goes here
  .then(function (response) {
    const data = response.data // This is the data you wanna pass to the react-table down the line
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  });
```

**Comment by Sm00g15** [comment]
LOL uber noob here. Any good references for looking into componentDidMount mixed with axios api calls? hehe

**Comment by cbll** [comment]
I'd say go through the official React docs if you're at that level, and learn the different lifecycles(componentDidMount amongst them), and build some small apps from them first. Otherwise you're in for a mess, if you go head first into complex stuff, without knowing the basics.

**Comment by Sm00g15** [comment]
fair enough, I'll heed your advice.
