### ISSUE TITLE
How to style filter input?

### ISSUE THREAD

**Issue by cbll** [tannerlinsley/react-table#371]
## Problem Description

See stackoverflow post here : https://stackoverflow.com/questions/44774468/how-do-i-style-react-table-filter-input-field

## Code Snippet(s) or Codepen

https://codepen.io/anon/pen/QgOdOp?editors=0010

Codepen with standard filter input. I can't seem to figure out how to access the filter column and style it myself?

**Comment by cbll** [comment]
Update: So I managed to style the filter input in the codepen above... But somehow in my project, even with very simple columns(just header and accessor plus type property), it just doesn't apply anything?

**Comment by tannerlinsley** [comment]
Closing this for triaging (your codepen is correct), but if you'd like to post your personal code we can take a look at why it's not working for you.  Or join the slack chat and get help from the community! :) 
<a href="https://react-chat-signup.herokuapp.com/" target="\_parent">
  <img alt="" src="https://img.shields.io/badge/slack-react--chat-blue.svg" />
</a>
