### ISSUE TITLE
defaultExpanded

### ISSUE THREAD

**Issue by haialaluf** [tannerlinsley/react-table#372]
## Problem Description
I have tried to create a table with raw expanded as default i have tried expandedRows and defaultExpanded but none of them worked (no console error)
Codepen (https://codepen.io/anon/pen/eReewL?editors=0010)
<ReactTable
	data={makeData()}
	columns={columns}
	defaultExpanded={ {0: true, 2: true}  }
	expandedRows={ {0: true, 2: true}  }
	SubComponent={ ()=><div>Hello!</div> }
/>

**Comment by aaronschwartz** [comment]
It does appear that `defaultExpanded` is not working correctly.

But if you're willing to completely take over the expanded rows, if you change `expandedRows` to `expanded` it does work. The API changed in 6.0.0 but I do see a reference in the readme still to the old `expandedRows` api.

**Comment by cbazza** [comment]
I just tried the same and it works with 'expanded' instead of 'expandedRows'.

**Comment by tannerlinsley** [comment]
Indeed, this looks broken.

**Comment by ChenYu020** [comment]
Hi,It seems that the defaultExpanded  is still not working ,but I have updated my version to 6.5.1

**Comment by jozefcuryllo** [comment]
It still seems it's not working.

**Comment by elhamsarikhani** [comment]
I am facing the same issue. I need a few lines to be expanded by default. when I use `defaultExpanded` , it's not working at all and when I use 'expanded' property, the rows will be expanded but they won't be collapsed anymore as the user clicks on the row.

**Comment by stahlmanDesign** [comment]
What appears to be happening is that the rows start by respecting `defaultExpanded`, but immediately close on initial render.
![screenflow](https://user-images.githubusercontent.com/972804/37551875-bc755d10-297f-11e8-96a1-7549209b3a5b.gif)

**Comment by dazlious** [comment]
This is still happening to me.

using defaultExpanded and pivotBy

expanded does work, but the row cannot be collapsed
