### ISSUE TITLE
Dynamic amount of columns

### ISSUE THREAD

**Issue by kieronsutton00** [tannerlinsley/react-table#374]
Hello,
I'm curious as to how I would go about having a dynamic amount of columns on a table that can randomly change depending on a filter value.

Thanks

**Comment by cbll** [comment]
There's a `show` boolean value you can attach to each column, and filter that with whatever logic you have for showing/not showing them

**Comment by tannerlinsley** [comment]
@cbll correct! You can dynamically rebuild the columns value if you'd like, and `show` is always available.
