### ISSUE TITLE
Expandable SubComponent subtracts once component receives props

### ISSUE THREAD

**Issue by cbll** [tannerlinsley/react-table#375]
I have a React-Table inside another React-Table, it works fine except when my component receives props from the parent. If I have expanded the SubComponent, it will unexpand once new data is updated; even if nothing new is added.

I thought about managing this in `componentWillReceiveProps` and checking `nextProps.data` vs `this.props.data`, but I'm unsure of how to pass a value to tell the React-Table to just .. not do anything in case they haven't changed.

Something like this:

```
    componentWillReceiveProps (nextProps) {
        if(this.props){
            if (nextProps.data === this.props.data) {
                /// What to do to make the component not reset?
            }
        }
    };
```

**Comment by aaronschwartz** [comment]
If the data reference is not changed, then react-table should not try and update the table.

If you want it to stay expanded even after a data change, consider the table setting:
`collapseOnDataChange: false`

**Comment by cbll** [comment]
I had not noticed `collapseOnDataChange`! I applied it to the parent component, and it works: Thanks a lot!
