### ISSUE TITLE
Is possible to hide empty lines at the end of the DataTable?

### ISSUE THREAD

**Issue by lhas** [tannerlinsley/react-table#377]
Hi!

@tannerlinsley very thanks for `react-table`. You're doing a great job here!

## Problem Description

I want to hide these empty lines at the end of last page. Is it possible? I tried to search at the docs but i don't found nothing.

![image](https://user-images.githubusercontent.com/1396448/27696327-be960e62-5cc7-11e7-802f-bfd0c444c21d.png)

**Comment by tannerlinsley** [comment]
Use this prop: `minRows={0}`

**Comment by lhas** [comment]
Thanks for the reply @tannerlinsley ! :+1:
