### ISSUE TITLE
Expander with checkbox in the same column

### ISSUE THREAD

**Issue by robinprashanth** [tannerlinsley/react-table#378]
I am working on data representation which should have expander and checkbox in the same column.Can someone help me on how to implement. Screenshot Attached
![untitled](https://user-images.githubusercontent.com/3203423/27731404-6f345ebc-5daa-11e7-9cd0-656902053ea4.png)

**Comment by tannerlinsley** [comment]
See this example: https://codepen.io/aaronschwartz/pen/WOOPRw?editors=0010

**Comment by robinprashanth** [comment]
I see only checkbox in the first column. In my case i need expander and checkbox in the same column.

**Comment by tannerlinsley** [comment]
There are several points where you can customize the expander component to be whatever you'd like it to be, including overriding it completely:
- The `ExpanderComponent` prop will globally override the expander component for the entire table.
- The `PivotComponent` prop will override the expander component just for pivoted rows
- The `column.Expander` property will override the expander component for a specific column
- The `column.Pivot` property will override the expander component (for pivoted rows) for a specific column.

I would suggest adapting the codepen example above to use one of these component/renderer overrides to accomplish what you need.

**Comment by robinprashanth** [comment]
Ok. Let me try using said options.
