### ISSUE TITLE
Missing onResizeComplete in version 6

### ISSUE THREAD

**Issue by woutervh-** [tannerlinsley/react-table#379]
## Problem Description
I'm missing the onResizeComplete callback in new version (6+).
I need it, as callbacks on every mouse move trigger way too often.

## Code Snippet(s) or Codepen (http://codepen.io/tannerlinsley/pen/QpeZBa?editors=0010)
With version 5 I used to be able to get a callback when resizing was complete:

```js
<Table ... onResizeComplete={(resizing) => this.setState({resizing})}/>
```

This callback is no longer provided in version 6.

**Comment by aaronschwartz** [comment]
I don't believe there was ever an onResizeComplete on react-table.

You can always debounce `onResizedComplete` so that it doesn't get called as often.

```
// Returns a function, that, as long as it continues to be invoked, will not
// be triggered. The function will be called after it stops being called for
// N milliseconds. If `immediate` is passed, trigger the function on the
// leading edge, instead of the trailing.
function debounce(func, wait, immediate) {
    var timeout;
    return function() {
        var context = this, args = arguments;
        clearTimeout(timeout);
        timeout = setTimeout(function() {
            timeout = null;
            if (!immediate) func.apply(context, args);
        }, wait);
        if (immediate && !timeout) func.apply(context, args);
    };
};
```

If you PR a change to add an `onResizedComplete` I'm sure we would consider it for inclusion.

**Comment by woutervh-** [comment]
Ah thanks, for some reason I had it in my mind we were using such a function from react-table, but we had written our own wrapper around the ResizerComponent to handle this. However, I will give it a try to implement a new PR for you, since that would be a neater solution.
