### ISSUE TITLE
Async Table Mockup link at Server-side Data is broken

### ISSUE THREAD

**Issue by JHRms** [tannerlinsley/react-table#385]
Async Table Mockup link at Server-side Data is broken. Is there another link to this?

Broken link:
https://github.com/tannerlinsley/react-table/blob/master/stories/ServerSide.js

**Comment by aaronschwartz** [comment]
https://github.com/tannerlinsley/react-table/blob/master/docs/src/stories/ServerSide.js

**Comment by JHRms** [comment]
Thanks!

**Comment by miguelmota** [comment]
link is broken in readme

**Comment by soncco** [comment]
Still broken

**Comment by gary-menzel** [comment]
Please see the following FAQ (it was answered in a different issue):

https://github.com/react-tools/react-table/wiki/FAQ#some-samples-on-codesandboxio-are-breaking

**Comment by quaspar** [comment]
> Please see the following FAQ (it was answered in a different issue):
> 
> https://github.com/react-tools/react-table/wiki/FAQ#some-samples-on-codesandboxio-are-breaking

Now this is also broken :)

**Comment by flymans** [comment]
Still broken
