### ISSUE TITLE
Getting the current Page Size and Page Number

### ISSUE THREAD

**Issue by JHRms** [tannerlinsley/react-table#386]
How would you determine the current Page Size and Page Number to pass in when doing Server-Side Data?

**Comment by tannerlinsley** [comment]
It is provided in the `onFetchData` callback.

**Comment by JHRms** [comment]
So is it possible for me to do something like this?

```
onFetchData={(pageSize, pageIndex) => {
        ...
      }
```

**Comment by tannerlinsley** [comment]
Yep!
