### ISSUE TITLE
Resized state - Handling columns with auto widths?

### ISSUE THREAD

**Issue by ldstein** [tannerlinsley/react-table#387]
## Problem Description

Hi all,

Assume a table with three fixed width columns and one column of variable width which uses up any remaining available width:

```
[
	{Header: 'First Name',   accessor: 'firstName' , width:100},
	{Header: 'Last Name' ,   accessor: 'lastName'             },
	{Header: 'Age'       ,   accessor: 'age'       , width:50 },
	{Header: 'Registered',   accessor: 'registered', width:50 }	
]
```
(I'm going to use the phrase 'auto-width' throughout this message. What I mean by that is a column with no `width` property defined.)

I'd like to persist the column width state so that it is restored across sessions. This is easily achieved via `onResizedChanged`  and `resized` properties:

```
function handleResized(resizedState){
	localStorage.setItem('resizedState', JSON.stringify(resizedState));
}

function getPersistedResizedState(){
	return JSON.parse(localStorage.getItem('resizedState'));
}
```

Now we come to where I'm stuck - I'd like to add an option to reset columns modified by the user back to their default state. One approach I considered was to iterate through the columns and generate a default `resized` state:

```
function getDefaultResizedState(){
	var state = [];
	columns.forEach(function(column){
		if (column.width) state.push({id:column.accessor, value:column.width});
	});	
	return state;	
}
```

Which actually works quite well... except for the column with no defined width. If the user has resized a column with no width defined, I'm unable to see a way to set the column's width back to 'auto-width'. 

I've tried setting the width to values such as 0, -1, false, null, undefined, as this would make the effect achievable, but it appears only numbers are accepted.

I should confirm my current approach actually works, but requires a reload of the browser window. I'm looking at ways of achieving this result without the reload.

Any thoughts or other methods I could consider to programmatically set the width back to 'auto-width' mode?

## Code Snippet(s) or Codepen
See https://codepen.io/anon/pen/XgOjLw?editors=0011

## Steps to Reproduce
1. Load https://codepen.io/anon/pen/XgOjLw?editors=0011
2. Resize column 1 and make it bigger.
3. Resize column 2 and make it smaller.
4. Click 'Clear Persisted State'
5. Column 2 is unable to be reset back to a auto-width mode.

## System Information
* **Browser & Browser Version:** Chrome, 64bit
* **Node Version:**na
* **OS Version:**Windows 10 x64
* **NPM Version:**na
* **Yarn Version:**na

**Comment by tannerlinsley** [comment]
Simply omit the columns respective object from the `resized` prop
https://codepen.io/tannerlinsley/pen/GvZjEe?editors=0011

**Comment by ldstein** [comment]
Your example https://codepen.io/tannerlinsley/pen/GvZjEe?editors=0011 unfortunately doesn't resolve the issue.

1. Resize the 'Last Name' column
2. Click the 'Clear Persisted State' button
3. The 'Last Name' column width does not revert back to an undefined width.

**Comment by ldstein** [comment]
I had a chance to get better acquainted with how the cell widths are calculated.

First thing I noticed is a mismatch between the column Id and resized column Id if no `id` field is set:

Assume the following column definition:
`const columns = [{Header:'My name', accessor:firstName}] `

Internally, the `column.id` will be set to `myName`

But the resized object returned by `onResizeChanged` has a different ID:
`[{id:'My name', value:600}]`

The result being during render, the resized[n].id will fail to columns[n].id.

Solution - Always define an id for each column.

Second Step - for a column to go back to a state where it's width completely fills the available space, a simple case of handling null values.

Assume this resized state:
`[{id:'firstName', value:null}]`

When calculating the width of a cell, some extra checks need to be performed:

```
// if resizedCol.value is null, fallback to column.minWidth
const width = _.getFirstDefined(resizedCol.value, column.width, column.minWidth) || column.minWidth
...
style={{
   ...styles,
   // If maxWidth is null, do not include it
   maxWidth:  maxWidth: maxWidth ? `${maxWidth}px` : null
}}
```

With those changes, the `resized` controlled state  can make a column behave as though it has an undefined width.

**Comment by ldstein** [comment]
See https://github.com/ldstein/react-table/tree/resized-handle-null for a demo.

I changed the width calculation only in `ThComponent`. Should allow for easy comparison of the existing width calculation found in `TdComponent`
