### ISSUE TITLE
Rendering custom Row. More a question than a problem.

### ISSUE THREAD

**Issue by pc-lsepulveda** [tannerlinsley/react-table#389]
## Problem Description
I have to code an `edit` mode. That means, whenever I click on a row, that row should be replaced by a custom component which contains a form.

## Code Snippet(s) or Codepen (https://codepen.io/anon/pen/KqJEez?editors=0010)
For now I'm using `getTrProps` for:
* Save the `viewIndex` of the editing column to the state `onClick`

On `getTrProps` I have `if (rowInfo && rowInfo.viewIndex === this.state.editing)` then I should render my custom row component but I haven't find a way to do it.

Thanks you in advance for any help and thanks to the contributors for making this an excellent component

**Comment by mmiller42** [comment]
@pc-lsepulveda Did you solve this problem? I'm looking to accomplish the same thing. I don't know if it's possible to override how a row is rendered.

**Comment by pc-lsepulveda** [comment]
@mmiller42 nope, I decided to drop it and create my own custom component based on the official facebook react table.

**Comment by gary-menzel** [comment]
@mmiller42 It is possible to override how a row appears (but it takes a bit of thinking as would need to replicate the existing row rendering as well - not easy to just switch out and switch in - although still feasible it would get complicated).  What I do is use `SubComponent` to render the `form` or other data that I need for a row. That is very simple to do.

You might also want to join the #react-table Slack channel (badge on the README in the doco) as a wider group of users participate there compared to the github issues. Thanks.

**Comment by mmiller42** [comment]
Ah, I see you can override the Row component ([here](https://github.com/react-tools/react-table#component-overrides)). So I should be able to import the original row component, wrap it in a custom component that renders a form, and pass that into the `RowComponent` prop.

**Comment by gary-menzel** [comment]
CAUTION: the `TrComponent` is used for every "row" (including headers and such) - that is why it gets "difficult".

**Comment by gary-menzel** [comment]
in 6.7.5 there are some HOCs in the source which I wrote - there is a treeTableHOC that overrides the TrComponent to handle rendering the Pivot information so it looks more like a tree - if you are keen, that's a good place to start.

**Comment by cmdd80** [comment]
@mmiller42 Did you manage to find a solution? I'm struggling with HOC but I am not able to wrap each row in a component able to fire a context menu...

**Comment by mmiller42** [comment]
I haven't tried yet. I wanted to explore the functionality, but currently the UI engineer who was working on this particular task ended up just rolling their own table component since we didn't really need to leverage most of the features of react-table. I'm still interested in doing this though. This seems like a fairly common use case of this component, so if I have any success with it, I'll be sure to post a Gist or Codepen or something.
