### ISSUE TITLE
Support for sorting columns

### ISSUE THREAD

**Issue by Siaver** [tannerlinsley/react-table#391]
Is it possible to sort columns?

**Comment by tannerlinsley** [comment]
https://github.com/tannerlinsley/react-table#sorting

**Comment by Siaver** [comment]
@tannerlinsley Can I change the order of columns like a drag and drop functionality?

**Comment by tannerlinsley** [comment]
You can do that by changing the order of the columns in the `columns` prop array. If you want drag and drop functionality for that, you'll have to implement that on your own. React Table doesn't ship with drag and drop support. But it has been done by users on their own.

**Comment by Siaver** [comment]
Cool! Thanks.

**Comment by Siaver** [comment]
@tannerlinsley I am updating the columns array order but the headers doesn't update. Can I get a simple example how would you implement that?
