### ISSUE TITLE
Multi-Sort without holding shiftkey

### ISSUE THREAD

**Issue by Ixl123** [tannerlinsley/react-table#392]
## Problem Description

Is there an easy way of enable multi-sorting without holding the shiftKey? I was searching for a solution and didn't find one. 

Is there somehow an easy way to just pass down a true prop for holding the shiftkey as default?

**Comment by Ixl123** [comment]
as mentioned in the Slack channel you can just overwrite the sorted property of react-table as you like after onSortedChange events fires.

**Comment by daniloprates** [comment]
@Ixl123 I couldn't find how to use this function. 
Is it possible to change the table sorting with that?
