### ISSUE TITLE
Passing column props to table results in an error

### ISSUE THREAD

**Issue by thirashima** [tannerlinsley/react-table#394]
Trying to pass the prop 'column' to the Table element results in a "TypeError: column.getHeaderProps is not a function" error.

The following code will trigger it:
`<ReactTable 
    data={[{name: 'Bob' }]} 
    columns={[{Header: 'Name', accessor: 'name'}]} 
    column={{className: 'table__cell'}}  />`

Using version 6.5.1 with react 15.6.1.

**Comment by aaronschwartz** [comment]
You're losing all of the other column defaults when you completely override it like that. Since `column` is an object, you need to merge your desired settings into the existing object.

```
column={ 
{
  ...ReactTableDefaults.column,
  className: 'table__cell'
}
```

From the documentation:
```
import { ReactTableDefaults } from 'react-table'

Object.assign(ReactTableDefaults, {
  defaultPageSize: 10,
  minRows: 3,
  // etc...
})
```

**Comment by thirashima** [comment]
I see, thank you.
