### ISSUE TITLE
Thank you for this library

### ISSUE THREAD

**Issue by iamakulov** [tannerlinsley/react-table#395]
Hey,

Just started using `react-table` and wanted to say thanks for such a great job. Customization is so well through-out that I’m just enjoying working with it: I can change almost every detail to adapt the table for design requirements; and, at the same time, I need to change only a small number of things because defaults also work very well. And the number of features just blows my mind.

Thank you. Such an amazing job.

**Comment by tannerlinsley** [comment]
You are very kind! This issue will remain open until further notice to keep me motivated :)

**Comment by lord-xeon** [comment]
Agreed, I found this library earlier this week and it's solving issues for me and its very extensible.  Thanks for the hard work!

**Comment by dcworldwide** [comment]
I'm also a react table fan boy. Awesome job!

**Comment by Lube** [comment]
This reminded me to Star the repo, thanks for the great job @tannerlinsley

**Comment by amitripshtos** [comment]
@tannerlinsley You are awesome! really good piece of software

**Comment by browne0** [comment]
@tannerlinsley this repo is awesome, thanks for all of the continued support :raised_hands:

**Comment by kesuskim** [comment]
OMG this is freaking good! :hugs: I must do double :+1: , but sorry for not having 2 github acc, :laughing:

**Comment by SteveGBanton** [comment]
I agree this is awesome! 👍

**Comment by shift-keshav-pudaruth** [comment]
I've been looking for a replacement to fixed-data-table 2 and this one fits my needs perfectly.

**Comment by shanky101** [comment]
@tannerlinsley Coming from an iOS development, environment jumping into React for Web was daunting enough and I was confused by the zillion set of ways tables could be implemented in React. Your library is like a complete implementation of Table component and is akin to UITableView set of controllers used in iOS development. I hope one day this gets integrated into the core React library since this library saves tremendous amount of time and has tons of ways for customisation.

PS: It would be nice if one of the community members can add the "react-table" tag on stackoverflow so that all questions related when implementing this can easily be found or answered to.

**Comment by maooricio** [comment]
Hey, I want to join to this post because this library is highly excellent. Great job, and thank you sooooo much.

**Comment by NickyYo** [comment]
I was about to say thank you as an issue then noticed this :), that has to be best datable i've ever used! so much customisability! Thank you!

**Comment by codeorelse** [comment]
Awesome work!

**Comment by cemremengu** [comment]
Simply amazing.  Not only this is the best table/data-grid component for react but also such a gem in every aspect. I am literally drooling 🤤 💯  

Thank for your work, I am buying you a beer now 🍻

**Comment by sandalaphon** [comment]
Loving this!! Thank you 👍

**Comment by maxdarque** [comment]
Amazing react table! I've spent a week researching and using different react-based tables and I feel like this has to be the best one. It is both simple to make work and highly customisable. Kudos

**Comment by dclark27** [comment]
Love this component! You saved me a ton of work. It's extremely well done.

**Comment by revolunet** [comment]
Yesss ! thank you ❤️

**Comment by alejandroMA** [comment]
Recently i found this component and it's freaking awesome.
i need to build some sorting features for a table, and i'm done. 
And there's so many features.
Just Thank you!

**Comment by bnjmn-jns** [comment]
Excellent component and so refreshing to see such thorough documentation.

**Comment by alebrozzoSP** [comment]
I love the library, even had a PR approved on v5, but why... oh why did you change column `header` to `Header`?? that is my most breaking point :(

**Comment by tannerlinsley** [comment]
We capped the property names for anything that accepts a react
component/class/renderfunction

**Comment by blunatic** [comment]
Refactoring several tables in my company's app to react-table from another table library, and must say, this library is stellar and the support is great. Thanks for the excellent examples and documentation.

**Comment by johnthomas00** [comment]
Great library, thank you kind people!!

**Comment by jsjain007** [comment]
Amazing library with complete customization options. Thanks a lot for your efforts.

**Comment by khanhtrannnn** [comment]
I'd like to thank you too~~~ Such an amazing table ^^

**Comment by pedrof** [comment]
Thanks you for this library!! is super customizable and make sense! :)

**Comment by JasonRitchie** [comment]
I really love this library. After trying all the major competitors simultaneously, I am moving forward with production implementations of react-table. It's so extensible and well-structured!

**Comment by mmmikeal** [comment]
I love this repo, but I wish there were more examples for adding custom styling or for finding out what specific classes are

 (example: .ReactTable .rt-tbody .rt-td,
.ReactTable .rt-tbody .rt-td:last-child,
.ReactTable .rt-thead .rt-th,
.ReactTable .rt-thead.-filters .rt-th)

**Comment by tannerlinsley** [comment]
In the future version we may move to css-in-js, but for now, the best way
is just to inspect what you want to change and go for it.

**Comment by baoduy** [comment]
I’m also using this library for a internal application of my company and successful went live yesterday as global application. Cheers and thanks for a great react table.

**Comment by Punith13** [comment]
I too was looking forward for a React Table library after working on the jQuery Slick Grid. Had thoughts about building one, but was putting off due to lack of necessary skills :P. This library looks uber cool, I will just use it anyways. Thanks a lot!

**Comment by mondayCoding** [comment]
Excellent library 💜 so far it has had just about everything we needed without needless bloat. Also allowed me to drop a ton of boilerplate.  Currently finding a transition-lib to pair with this. 

Thanks for good work

**Comment by sanchitbansal10** [comment]
Used it with firebase....Made filters that work conditionally on server-side and client-side....It was easy and interesting to work with react-table....The library is so greatly thought out

**Comment by netmajor** [comment]
I am using this library in financial react app. It works great! Thank you!

**Comment by edoroshenko** [comment]
Special thanks for header groups.

**Comment by luisrodge** [comment]
This library is the reason I believe the React community is the be the best development community there is today.

**Comment by acidjunk** [comment]
Thanks for this amazing library. +1000 Kudo's :)

**Comment by bjs250** [comment]
Just dropping in to heap praise on everyone for this library. Huge lifesaver, useful documentation.

**Comment by ArtDev616** [comment]
@tannerlinsley  You would not imagine how many companies and people you have been helping.
I am one of them who enjoy your open source lib, and well-versed documentation.

**Comment by tannerlinsley** [comment]
Thanks @ArtDev616! Tell your company to become a patreon sponsor and get they're logo on the repo!

**Comment by mideridder** [comment]
First of all thanks for this great library. I really like the react table and can't wait to update to version 7 with the hooks. I was wondering is there maybe some sort of roadmap to get a rough idea about when version 7 will go from alpha to beta and so on. Thanks!

**Comment by Fabitosoft** [comment]
Really the nicest library to show my data. I used almost in my whole app. Thanks, you have helped me so much.

**Comment by adepatie** [comment]
Ditto what the nice people said! I'll be using this in my current search refactor. I'd like to help the development of this any way I can!

**Comment by tannerlinsley** [comment]
Hello everyone! Thanks for supporting React Table. If you use it, love it, or want to help make it better, I would like to invite you to become a Patron!

I have Patreon tiers starting at just $1, but all of the higher plans get your name or logo into this project's readme with a link to wherever you want! The repo receives about 35k unique Github visitors and 1+ Million downloads on NPM every month.

All of your help makes this project possible, so thanks for all the ❤️!

<a href="https://patreon.com/tannerlinsley" target="_blank"><img width="178" alt="Screen Shot 2019-08-05 at 6 09 23 AM" src="https://user-images.githubusercontent.com/5580297/62463596-a593d200-b747-11e9-8c70-b13c5b56b58d.png"></a>

**Comment by tannerlinsley** [comment]
Thank you all for loving this library. It means a lot to me. Now that patreon and github sponsors (soon hopefully) are available, I'll be closing this issue.

I appreciate all the love and support you've given me here and will remember this issue forever.
