### ISSUE TITLE
unable to to join https://react-table-slack.herokuapp.com/

### ISSUE THREAD

**Issue by davchang** [tannerlinsley/react-table#397]
Is the slack account active? 
I got "Failed! account_inactive" error message when I tried to join.

**Comment by tannerlinsley** [comment]
The new slack organization signup is located here: https://react-chat-signup.herokuapp.com/ :)

**Comment by gardezii** [comment]
is this still working ?

**Comment by tannerlinsley** [comment]
We now use https://spectrum.chat/react-table

Tanner Linsley
