### ISSUE TITLE
defaultExpanded is still not working 

### ISSUE THREAD

**Issue by ChenYu020** [tannerlinsley/react-table#399]
It seems that the defaultExpanded is still not working ,but I have updated my version to 6.5.1

 `<div className="table-flow" style={{height: '100%'}}>
                <ReactTable
                    loading = {this.state.loading}
                    className='-striped -highlight'
                    columns={this.state.columns}
                    data={this.state.data}
                    pivotBy={this.state.pivotBy}
                    defaultExpanded={{
                        1: true,
                        4: true,
                        5: {
                          2: true,
                          3: true
                        }
                    }}
                    previousText = '上一页'
                    nextText = '下一页'
                    loadingText = '加载中...'
                    noDataText = '没有数据'
                    pageText = '页'
                    ofText = '共'
                    rowsText = '行'
                />
            </div>`
* **chrome**
* **Mac OS**

**Comment by tannerlinsley** [comment]
Looking into this right now

**Comment by tannerlinsley** [comment]
Looks like its working here: https://codepen.io/tannerlinsley/pen/PKNGBY?editors=0010

**Comment by Firanolfind** [comment]
Hi,
I just faced the same issue. It does not work with sub rows. There is your updated demo: https://codepen.io/anon/pen/eLzqzE?editors=0010

**Comment by Firanolfind** [comment]
It is probably something wrong with this condition on line [81](https://github.com/react-tools/react-table/blob/master/src/lifecycle.js#L81)
When I comment line [90](https://github.com/react-tools/react-table/blob/master/src/lifecycle.js#L90) it works fine
