### ISSUE TITLE
Sorting help

### ISSUE THREAD

**Issue by SamSimmons** [tannerlinsley/react-table#40]
Hey, I'm having some trouble implementing custom sorting. Say I have a component
```
const BigTable = (props) => {
  let { data } = props
  return (
    <ReactTable
      data={data}
      columns={columns}
    />
  )
}
```

If I had an age column, that was a string, and I wanted to use a function like `(a, b) => parseInt(a) - parseInt(b)` to sort the data. From the docs I've been trying to set the table to manual use `onSortingChange`, but I can't figure out how to use it properly. Any chance you could point me in the right direction?

**Comment by tannerlinsley** [comment]
If you want to fully control the sorting algorithm, you will need to treat
the table as a server side setup. See
https://react-table.js.org/?selectedKind=2.%20Demos&selectedStory=Server-side%20Data&full=0&down=0&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel

I may possibly make the sorting customizable more easily

**Comment by atlanteh** [comment]
Any update regarding customizing the search? I have a getter that shows some date as a formatted string, but I want the sorting to be done by the actual date value..
