### ISSUE TITLE
how to use expanded subComponent on clicking particular accesor 

### ISSUE THREAD

**Issue by shaikjohnsaida** [tannerlinsley/react-table#404]
Hi 
I m facing some issues in react table 
I need to expand sub-component on clicking row accessor

**Comment by tannerlinsley** [comment]
You can use the "controlled" props `expanded` and/or `onExpandedChanged` to manually control when to expand a sub component. In your case, you may want to utilize an `onClick` handler in your `Cell` renderer that updates the local state for the `expanded` prop. For more questions, please just us on Slack (https://react-chat-signup.herokuapp.com/)
