### ISSUE TITLE
Locked Columns?

### ISSUE THREAD

**Issue by lord-xeon** [tannerlinsley/react-table#405]
## Problem Description
Is there the ability to lock columns in the layout?

## System Information
* **Browser & Browser Version:**
Chrome v59
* **Node Version:**
6.10.0
* **OS Version:**
OSX 10.11.6
* **NPM Version:**
4.2.0

**Comment by tannerlinsley** [comment]
If you are referring to column "pinning", no there is not a way to do that in React-Table; the reasons for now being that React-Table does not do virtualized scrolling. There are no immediate plans to support this.

**Comment by lord-xeon** [comment]
That's a shame, thanks for the reply though.

**Comment by tannerlinsley** [comment]
In the very distant future, there is talk of possibly moving to a synced
column layout (this would be a total rewrite). It would effectively squash
the auto-flex capability of the table in exchange for some more tricky
pinning features. It’s been hard to strike a balance between the two, so
we’re just covering the majority use case right now which is simply having
a reliable and consistent table navigation experience.
