### ISSUE TITLE
Iam using react subcomponent ,  i want to render another table inside main table by clicking values in the parent table .

### ISSUE THREAD

**Issue by vigneshranganathan26** [tannerlinsley/react-table#407]
## Problem Description
include a detailed explanation of the problem here...

## Steps to Reproduce
1. list the steps
2. to reproduce the issue

## System Information
* **Browser & Browser Version:**
* **Node Version:**
* **OS Version:**
* **NPM Version:**
* **Yarn Version:**

**Comment by tannerlinsley** [comment]
This is more of a question of implementation, not an issue.  Please join us on Slack and ask your question to the community! https://react-chat-signup.herokuapp.com/
