### ISSUE TITLE
Filter issue (no result at all, or weird behaviour)

### ISSUE THREAD

**Issue by Drillan767** [tannerlinsley/react-table#408]
## Problem Description
I implemented the filter function, letting the normal filter method by default. However, on one column, the filter doesn't seem to work, and on another, the filter gives no result back.

My table is composed as the following:
- One column is used as a checkbox, the value passed in it is a file's full path. This is the value contained in my database.
- The one next to also uses the path, but filters it to only keep the filename.
- The last one is the date when the file was added.

(there are two more columns, but I have the same problem with each of them, so it's useless to detail them)

If I do a console.log of this.state.filtered, I do obtain what I write in my filters. However, if I disable the "filterable' on the checkbox column, nothing happens if I type something in the "filename" column.

## Code Snippet

``` javascript
const columns = [{
    Header: ' ',
    accessor: 'path',
    // filterable: false,
    Cell: row => (
        <input
            type="checkbox"
            name="file_selected[]"
            value={row.value}
        />
    )
}, {

    Header: 'File',
    accessor: 'path',

    sortMethod: (a, b) => { // functional
        let reA = /[^a-zA-Z]/g;
        let reN = /[^0-9]/g;
        let afile = a.split('/').pop();
        let bfile = b.split('/').pop();
        let aA = afile.replace(reA, "");
        let bA = bfile.replace(reA, "");

        if(aA === bA) {
            let aN = parseInt(afile.replace(reN, ""), 10);
            let bN = parseInt(bfile.replace(reN, ""), 10);

            return aN === bN ? 0 : aN > bN ? 1 : -1;
        } else {
            return aA > bA ? 1 : -1;
        }
    },

    Cell: row => {
        let filename = row.value.split('/').pop();

        return <p>{filename}</p>
    }

}, {
    Header: 'Tags',
    accessor: 'tags',
    Cell: row => {
        /* @Todo: Mettre en place ce système de tag par array */
        let tags = row.value.replace(/[^a-zA-Z0-9]/g, "");

        return <p>{tags}</p>

        /*{ tags.split(' ').map(function(tag, i) { // For now, renders a string
            return (
                <span key={ i } className="chip">{ tag }</span>
            )
        })}*/
    }
}, {
    Header: "Date d'ajout",
    accessor: 'created_at',
    sortMethod: (a, b) => {
        return a > b ? 1 : -1;
    },

    Cell: row => {
        let date = new Date(row.value);
        return (
            <div
                style={{
                    width: '100%',
                    height: '100%',
                    textAlign: 'center',
                }}
            >
                <p>{ date.getDate() + '/' + (date.getMonth()+1) + '/' + date.getFullYear() }</p>
            </div>
        )
    }
}];

// ...

render() {

        console.log(this.state.filtered);

        return (
            <form action="/download/zip">
                <ReactTable
                    data={this.state.data}
                    noDataText='Pas encore de fichier'
                    columns={columns}
                    filterable
                    filtered={this.state.filtered}
                    onFilteredChange={filtered => this.setState({filtered})}
                    defaultFilterMethod={(filter, row) =>
                        String(row[filter.id]) === filter.value}
                />
                <input type="submit" value="Télécharger" />
            </form>
        )
    }
```

## System Information
* **Browser & Browser Version: Chrome - 59.0.3071.115**
* **Node Version: 8.1.2**
* **OS Version: Ubuntu 16.04**
* **NPM Version: 5.3**
* **Yarn Version: 0.27.5**

**Comment by tannerlinsley** [comment]
@aaronschwartz Can you see anything obvious in this code example?

**Comment by aaronschwartz** [comment]
You may be having issues because columns have the same `accessor` without defining an `id` field. Try and set a unique `id` on your columns with matching `accessors`. Otherwise it would be helpful to re-create it in Codepen if possible.

**Comment by tannerlinsley** [comment]
Good find @aaronschwartz, we should add a check for that.

**Comment by tannerlinsley** [comment]
As far as I can tell, this should work (and has worked when I try it locally).  @Drillan767, could you please create a [codepen](https://codepen.io/tannerlinsley/pen/QpeZBa?editors=0010) replicating this functionality? Closing this for now for triaging. Please open when you have the pen. :)

**Comment by Drillan767** [comment]
Hello, I'm sorry I couldn't answer earlier, I was abroad and without computer, so I couldn't do much myself.
So I [created a pen](https://codepen.io/Drillan767/pen/yoaaEN) but failed to make it work like you did in your example (even though I added React-Table.

 I also added some actual datas that I get from my own database, and tried for my part to add this 'id' you guys were talking about, but in vain, even though I check your documentation to have an idea about how to do it. 
So far, even with a few ids, my issue move slightly : now if I try to write anything in any searchbox, the result is always empty (before this, nothing happened when stuff was written in the "file" column searchbox). Here is my [github file](https://github.com/Drillan767/saint_gufre/blob/master/app/javascript/gufremagicbox/GufreList.js) so you have a better idea of what I'm talking about.

thank you guys for your help so far!

**Comment by tannerlinsley** [comment]
**Fork** [this codepen](https://codepen.io/tannerlinsley/pen/QpeZBa?editors=0010) and modify it. It is already preloaded with React-Table (including styles) and the simple example. That might get us closer to the problem.

**Comment by Drillan767** [comment]
Ok here is the the [new codepen](https://codepen.io/Drillan767/pen/xLEgGe?editors=0010) with id added at each column, no change so far

**Comment by aaronschwartz** [comment]
The filter is based on the original 'value' of the row. So if you start typing `/uploads/` you'll see the filter working since the default filter is `.startsWith(...)`. You can override the filter method for that column to change it if desired. Or you could make the accessor a function that does the split and then the value will be just the filename.

**Comment by tannerlinsley** [comment]
@aaronschwartz Bingo!

**Comment by Drillan767** [comment]
Wow you're right! So if I follow you, I need to override the "startsWith()" function with my own filters for every columns? Since it looks like the problem is the same for each of my columns?

**Comment by aaronschwartz** [comment]
You can set the global `defaultFilterMethod` for the entire table to `.includes()` if you want.

**Comment by Drillan767** [comment]
Ok I must admit I have some trouble finding out the correct way to replace the `.startWith()` method: I've been trying a few things but I don't really know what to replace the default filter with : I can't manage to find a way to say that the filter is equal to what is rendered in the column. For example, I'd like to be able to filter among the `row.value.split('/').pop()`, but I can't manage to do correctly the following

Thank you in advance

**Comment by aaronschwartz** [comment]
Is this what you're trying to do? I used both methods I outlined. The filename uses a custom `filterMethod` and the tags uses a custom `accessor` function.

https://codepen.io/aaronschwartz/pen/KvgXpz?editors=0010

**Comment by Drillan767** [comment]
Ok, thank you a lot, I could put this in my own code and it woked like a charm, the creation date won't work for now but I think i'll make it work through a `filterMethod`. Thank you both a lot!
