### ISSUE TITLE
Overriding column's default sort direction does not work.

### ISSUE THREAD

**Issue by brendonsoto** [tannerlinsley/react-table#413]
I've tried switching a column's default sorting direction from the global direction, but the override is ignored.

I've noticed in the props section of the documentation defaultSortDirection is listed for footers only, however the sorting section doesn't mention footers for overriding sort direction.

Any input would be much appreciated.

**Comment by brendonsoto** [comment]
I just noticed removing defaultSortDirection on the table and setting the property on the individual columns works fine so I'm not sure if just the documentation needs updating or if the override not working is unintentional.

**Comment by tannerlinsley** [comment]
This is a bug. Working on it now.

**Comment by tannerlinsley** [comment]
Actually, appears to not be a bug! https://codepen.io/tannerlinsley/pen/eEddmO?editors=0010
Be sure to double check you are using `defaultSortDesc` and not `defautSortDirection`

**Comment by brendonsoto** [comment]
Interesting. Thanks again for your time and help!
