### ISSUE TITLE
Option to move the ExpanderComponent to the right

### ISSUE THREAD

**Issue by deepakkj** [tannerlinsley/react-table#45]
I would like to move the Expander Component to right side of the table. By default it renders to the left.
How can I achieve this?

**Comment by tannerlinsley** [comment]
Great question. I'll noodle on this on my way to work

**Comment by tannerlinsley** [comment]
Working on this feature as we speak. Expect it to launch in the next few
hours!

**Comment by deepakkj** [comment]
Thanks and appreciate it.

**Comment by tannerlinsley** [comment]
Available in `react-table@4.4.0`. See [Custom Expander Position](https://react-table.js.org/?selectedKind=2.%20Demos&selectedStory=Custom%20Expander%20Position&full=0&down=0&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel) example :)
