### ISSUE TITLE
pageSize not updating

### ISSUE THREAD

**Issue by DimitryDushkin** [tannerlinsley/react-table#46]
I believe it's happening because of https://github.com/tannerlinsley/react-table/blob/master/src/index.js#L146-L150

We have new `pageSize` in `state` variable, but it's overwritten by `this.props` with old `pageSize` value. Because of that following `shouldComponentUpdate` returns `false`, so despite new `pageSize` in state component is not re-rendered.

**Comment by tannerlinsley** [comment]
How are you setting/changing pageSize exactly? Can you post your component here?

**Comment by DimitryDushkin** [comment]
I've developed custom pagination and this behaviour appeared after update from 3.2.1 to 4.4.1.
This is how I'm updating pageSize — https://gist.github.com/DimitryDushkin/ff76572d5f1efe2b642206171a5290fb#file-reacttablepagination-jsx-L78

I'm sure that correct number is passed to this function.

**Comment by tannerlinsley** [comment]
That's strange. This should work from what I saw in your gist. What props are you sending the table when you render it?

**Comment by DimitryDushkin** [comment]
@tannerlinsley sorry for worry.

I've set `pageSize` prop by myself instead of `defaultPageSize` that's why changing it via pagination component didn't have effect.
