### ISSUE TITLE
onTrHover callback

### ISSUE THREAD

**Issue by stropitek** [tannerlinsley/react-table#50]
Would it be possible to add a `onTrHover` callback prop, to complement the `onTrClick` prop?

**Comment by tannerlinsley** [comment]
I will look into this. I plan on implementing a general props interface for
every component for easy customization.

**Comment by tannerlinsley** [comment]
This is now possible via version 5.0.0.  Please take a look at the new docs for [Custom Props](https://github.com/tannerlinsley/react-table#custom-props)
