### ISSUE TITLE
I'm trying to style td tags conditionally 

### ISSUE THREAD

**Issue by sshaginyan** [tannerlinsley/react-table#52]
Is is possible to style td tags conditionally? Can I see some sample code. The `Function Rendering` section in the docs should suffice, but don't know how to change a td's background color based on the data I give to react-table.

**Comment by tannerlinsley** [comment]
Help is on the way in v 5.0.0 :)  You'll be able decorate or override the props of any core component with a callback.  You'll have all the power you want :)

**Comment by sshaginyan** [comment]
Is there a branch for v 5.0.0?

**Comment by tannerlinsley** [comment]
Nope, It's live and release.  `yarn install react-table` or `yarn upgrade react-table`.  Be sure to skim the docs again.  I'll work on a changelog here soon.

**Comment by tannerlinsley** [comment]
https://github.com/tannerlinsley/react-table#custom-props should be exactly what you need :)
