### ISSUE TITLE
How to rerender entire single row in react-table?

### ISSUE THREAD

**Issue by olegzhermal** [tannerlinsley/react-table#54]
I have a react-table component in my app and pass there next props:

```
<ReactTable
  data={this.props.words}
  columns={columns}
  getTrProps={changing_state_func}
/>
```

changing_state_func is a function that changes state of the component that wraps react-table. Specifically, this function fills an array that contains ids of the data objects for rows. So I'd like to highlight the rows with the data for those ids... Cannot figure it out how to do it.

**Comment by tannerlinsley** [comment]
Could you perhaps post your `changing_state_func`?

**Comment by olegzhermal** [comment]
```
changing_state_func = (state, rowInfo) => {
  if (!rowInfo) return {}
  return {
    onClick: () => {
      this.setState({rowsIdsArray: this.state.rowsIdsArray.concat([rowInfo.row.id])})
    }
  }
}
```

**Comment by olegzhermal** [comment]
Think this illustrates my problem even better:
```
changing_state_func = (state, rowInfo) => {
  if (!rowInfo) return {}
  return {
    style: {
      background: (this.state.rowsIdsArray.includes(rowInfo.row.id)) ? 'green' : null
    },
    onClick: () => {
      this.setState({rowsIdsArray: this.state.rowsIdsArray.concat([rowInfo.row.id])})
    }
  }
}
```
So, when you click on some row it suppose to change background to green (and it does so after, for example, column sorting). How to do it without additional actions (like data changing, sorting etc), that the table rerenders after onClick event happens (style doesn't necessarily inline..) ?

**Comment by tannerlinsley** [comment]
Interesting.  This is because of the "pure" nature of the component. So in that case, it looks like you would need a way to tell the table to rerender.  Since you're not technically changing any props that are sent to the table, it would need to be programmatically.

**Comment by tannerlinsley** [comment]
I just published version 5.0.2 that gives you access to the table's instance.

Try this:
```changing_state_func = (state, rowInfo, column, instance) => {
  if (!rowInfo) return {}
  return {
    style: {
      background: (this.state.rowsIdsArray.includes(rowInfo.row.id)) ? 'green' : null
    },
    onClick: () => {
      this.setState({rowsIdsArray: this.state.rowsIdsArray.concat([rowInfo.row.id])});
      instance.forceUpdate()
    }
  }
}```

**Comment by olegzhermal** [comment]
That works! Thanks for the quick fix.

**Comment by tannerlinsley** [comment]
You bet. 😊
