### ISSUE TITLE
Demos not working

### ISSUE THREAD

**Issue by arindambarman1** [tannerlinsley/react-table#55]
Can someone please update the storybook. Currently is it full of errors

**Comment by rpalermodrums** [comment]
It's not just the storybook. The 5.0.0 update seems to be broken. Getting this error when trying to render the table: `column.getHeaderProps is not a function`.

**Comment by tannerlinsley** [comment]
Just issued a fix.  `react-table@5.0.1` Sorry!

**Comment by arindambarman1** [comment]
Thanks a lot

**Comment by arindambarman1** [comment]
Before starting to use this can someone confirm if it supports fixed header and fixed set of columns on the left for horizontal scrolling? Can't see it in the documentation

**Comment by tannerlinsley** [comment]
It does not support fixed headers yet.

**Comment by dnlsandiego** [comment]
I'm getting the same error using `v5.0.2` when trying to override the `column` defaults like so:

```JSX
<ReactTable
  data={data}
  columns={columns}
  styleName="table"
  column={{headerClassName: 'header'}}
/>
```

I was under the impression this kind of props override is possible after reading the docs. Or is it not possible to override for object type props like the one for `column`?

**Comment by tannerlinsley** [comment]
Should be possible for sure. I'll look into it

**Comment by brantchoate** [comment]
also have the same exact problem (trying to override the headerClassName)

**Comment by a-x-** [comment]
i researched how to use it:

```jsx
import tableDefaultProps from 'react-table/lib/defaultProps';
      <Table
        {...{data, columns}}
        column={{...tableDefaultProps.column, filterRender}}
      />
```

**Comment by a-x-** [comment]
reopen pls

**Comment by asokolova88** [comment]
How to solve this problem?
