### ISSUE TITLE
Support for fixed header

### ISSUE THREAD

**Issue by bruth** [tannerlinsley/react-table#57]
Are there any plans to support a fixed header like [fixed-data-table](http://facebook.github.io/fixed-data-table/example-object-data.html) does?

**Comment by mlukaszczyk** [comment]
I just did this with a custom CSS (actually sass). Works great!

```
$headerHeight: 40px;
$rowHeight: 60px;

.ReactTable {
  position: absolute; // This is not really necesarry. I do this to span the table to the width and heigth of the parent component
  left: 0px;
  top: 0px;
  width: 100%;
  height: 100%;
  border: none;

  .rt-table {
    height: 100%;
    display: block;

    .rt-thead {
      height: $headerHeight;
    }

    .rt-tbody { // I setup the body of the table to behave as a scroll container
      height: calc(100% - $headerHeight);
      overflow: scroll; 
      display: block;

      .rt-tr-group {
        background: white;
        height: $rowHeight;
      }
    }
  }
}

```

**Comment by bruth** [comment]
Look at that! Thank you thank you. My CSS skills are severely lacking these days.. I remember doing this with JavaScript years ago and it was never good.

**Comment by mlukaszczyk** [comment]
You´re welcome! 

It´s amazing what you can do with css today. Definetly check [this flexbox guide](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) for your secret css super weapons.

**Comment by micahsteinberg** [comment]
This works, but it would be really nice if you could have the table use the same scroll as the rest of the page so you can't get stuck only partially scrolled to it and then switch over to the table's separate scroll.

I tried getting this behavior with this css:
```
.ReactTable .rt-thead {
  position: sticky;
  top: 0;
  z-index: 1;
}
```
but it didn't work.

Any suggestions for how to do this?

**Comment by Koriit** [comment]
You can do this with pure CSS: https://css-tricks.com/position-sticky-and-table-headers/

**Comment by markobilanovic** [comment]
> You can do this with pure CSS: https://css-tricks.com/position-sticky-and-table-headers/

this but with fixed columns would be nice to see with pure CSS
