### ISSUE TITLE
Support for resizable columns

### ISSUE THREAD

**Issue by bruth** [tannerlinsley/react-table#58]
Are there any plans for supporting resizable columns? [example](http://facebook.github.io/fixed-data-table/example-resize.html)

**Comment by tannerlinsley** [comment]
Its definitely been brought to my attention but I haven't moved on the idea yet. Other than deciding where and how to manage the column state to support it, it would be or straight forward.

**Comment by NicolaFenix** [comment]
+1

**Comment by spacedarcy** [comment]
+1

**Comment by tannerlinsley** [comment]
@NicolaFenix @spacedarcy, please use the thumbs up on the original comment, then remove your +1 comment :)  Just keeping things clean.

**Comment by TacticalCoding** [comment]
I'm working on an implementation that will hopefully be available soon.

https://github.com/TacticalCoding/react-table/tree/Resize-Columns

**Comment by RajuTicvic** [comment]
Hey Hi
I'm using react table with material UI Enhanced table
I don't want a resizable column for checkbox column  

Can I have help Please
