### ISSUE TITLE
Position of pagination component

### ISSUE THREAD

**Issue by bruth** [tannerlinsley/react-table#59]
I would like to move the pagination component above the table. I am reading the section on functional rendering and I suspect I can do this here (maybe). Could you provide any insight on how this can be achieved?

**Comment by mlukaszczyk** [comment]
This is a quick hack that works:

Just add 
```
display: flex;
flex-direction: column-reverse;
```

To the .ReactTable css class

**Comment by bruth** [comment]
That is a nice hack 👍 Thanks!

**Comment by tannerlinsley** [comment]
For now, this works.  In the future I plan on making the functional render more robust so you can easily move things around.
