### ISSUE TITLE
Fetching server-side data shouldn't require a default

### ISSUE THREAD

**Issue by alexandersimoes** [tannerlinsley/react-table#6]
I'm trying to use the server-side data example which will work until I add a setTimeout and then I get a few console errors. Here's the sample code:

Works --

``` js
const data  = [{name:'test', id:1234}];
return (
  <div>
    <ReactTable
      pageSize={10}
      columns={columns}
      data={(params, callback) => {
        callback({ rows:data })
      }}
    />
  </div>
)
```

Doesn't work --

``` js
const data  = [{name:'test', id:1234}];
return (
  <div>
    <ReactTable
      pageSize={10}
      columns={columns}
      data={(params, callback) => {
        setTimeout(() => {
          callback({ rows:data })
        })
      }}
    />
  </div>
)
```

The second test will work if initialized with the callback like so:

``` js
const data  = [{name:'test', id:1234}];
return (
  <div>
    <ReactTable
      pageSize={10}
      columns={columns}
      data={(params, callback) => {
        columns={columns}
        setTimeout(() => {
          callback({ rows:data })
        })
      }}
    />
  </div>
)
```

**Comment by tannerlinsley** [comment]
I'm not sure I understand the columns={columns} jsx you have in the
callback?

**Comment by alexandersimoes** [comment]
Woops, sorry that was a copy/paste error, the last, working example should've been this:

```js
const data  = [{name:'test', id:1234}];
return (
  <div>
    <ReactTable
      pageSize={10}
      columns={columns}
      data={(params, callback) => {
        callback({ rows:[] })
        setTimeout(() => {
          callback({ rows:data })
        })
      }}
    />
  </div>
)
```

**Comment by tannerlinsley** [comment]
I'll look into this tomorrow. Very interesting

**Comment by casperOne** [comment]
I can confirm, I'm running into the same issue as well.

**Comment by tannerlinsley** [comment]
Just released 3.0.0. Did you have a look at the new server side section?

**Comment by tannerlinsley** [comment]
The way data is fetched in the latest version should fix this issue. You can now listen for table changes and handle the data updates yourself via component state or redux or any other dynamic react state.

**Comment by casperOne** [comment]
> The way data is fetched in the latest version should fix this issue. You can now listen for table changes and handle the data updates yourself via component state or redux or any other dynamic react state.

Do you have an example of this?

When using a callback, I'm getting `this.props.data.map` is not a function:

![image](https://cloud.githubusercontent.com/assets/561862/19848138/cf43d398-9f21-11e6-9b4e-147545454371.png)

In this case, `this.props.data` is the callback function.

Here's the code that I have for react-table:

```
<ReactTable
  data={ (params, callback) => {
      // If no URL, then just get out.
      if (!challongeUrl) return Promise.resolve({ rows: [] });

      return fetchUtilities.fetchApi({
        url: `/api/challonge/tournaments?url=${ encodeURIComponent(challongeUrl) }&page=${ params.page }`
      }).then(data => {
        return {
          pages: data.pages,
          rows: data.tournaments
        }
      })
    }
  }
  columns={[
    {
      accessor: 'name',
      name: 'Name'
    },
    {
      accessor: 'game',
      name: 'Game'
    },
    {
      accessor: 'type',
      name: 'Bracket Type'
    },
    {
      accessor: 'progress',
      name: '% Complete',
      render: ({ value, rowValues, row, index, viewIndex}) => <LinearProgress mode='determinate' value={ value }/>
    }
  ]}
/>
```

I've validated that my service is returning the data correctly.

**Comment by tannerlinsley** [comment]
Update to the latest version and follow these steps
https://github.com/tannerlinsley/react-table/#server-side-data

**Comment by casperOne** [comment]
That seems to do it, thanks!

I'm having an issue where all the data is being rendered as `&nbsp` but that's for me to figure out another day.

**Comment by tannerlinsley** [comment]
@casperOne If `minRows` is set to anything > 0, placeholder rows are inserted into the table that contain `&nbsp;`.  My guess is your `data` is empty or something similar.  If you still have that problem, create a new issue and we'll handle it there :)
