### ISSUE TITLE
remove arrow in sub components

### ISSUE THREAD

**Issue by Gi972** [tannerlinsley/react-table#62]
Hello,
Have you plan to remove the arrow when a row has not sub component? thanks

**Comment by tannerlinsley** [comment]
If you set the `SubComponent` prop, there will be an arrow on every row. 

If you are asking about having some rows with a sub component and some without, we can talk about it here :)

**Comment by Gi972** [comment]
Yes it is exactly this.
It will normal if some rows have not subcomponent do not show arrow, the arrow it's just a indication :-) than the row have  extra-contents.

maybe if return false or null?

**Comment by tannerlinsley** [comment]
I'll look into this

**Comment by Gi972** [comment]
thanks :-)

**Comment by tannerlinsley** [comment]
So far this cannot be achieved easily without incurring some big performance hits.  Basically, we would have to render every sub component in place and check if it returns truthy, then show the arrow based on that.  You can imagine though how bad this would be for performance if the sub component contained any heavy rendering processes.  I think we'll need to rethink the approach to this.  Possibly a `enableRowSubComponent={rowInfo => true}` callback for the row?

**Comment by Gi972** [comment]
I agree with you for performance. 
I don't know if a callback for the row it's the good way :-/
A other way will to add a propertie  in data, but it not élégant and not intuitive ...

**Comment by tannerlinsley** [comment]
This doesn't seem to be possible right now without the massive performance hit of running each sub component function and analyzing the output.  The alternative callback idea is also a bit funky.  Closing this for now as we see how the library matures.

**Comment by aight8** [comment]
:/ have someone solved this one elegantly? For small data sets I think this wouldn't be remarkable but can improve the usability a lot.

**Comment by TacticalCoding** [comment]
I believe this is now possible in 5.6.0. You are now able to control the rendering of the expander column by modifying the `render` option on an expander column. You will have to manually check whether or not that row has sub data during render and you can choose to not show the arrow. The empty column might still have a click trigger on it though. Maybe you can find a way around that (Possibly by taking manual control of the `expanding` option).

**Comment by nicotroia** [comment]
@aaronschwartz can you show a quick example of what you mean? Or even simply to remove the arrow col altogether. 

I'm trying to manually open/close each SubComponent (if this is possible?) based on some other action. 
Thanks for the input

**Comment by aaronschwartz** [comment]
See https://react-table.js.org/#/story/custom-expander-position.

Also if you set set the `show: false` on the custom expander column it should hide it.
```
{
  expander: true,
  show: false
}
```

**Comment by trb727** [comment]
@aight8
Going off what @aaronschwartz said, I ended up creating a custom expander component modeled off of the [ExpanderComponent](https://github.com/tannerlinsley/react-table/blob/master/src/defaultProps.js) and conditionally rendering it based on the accessor value.

`        
const columns = [  
  {  
     accessor: 'exception',  
     expander: true,  
     render: (row) => return row.value ? <CustomExpanderComponent /> : null;  
   },
   ...  
]  
`

The custom expander component uses local state and an onClick event to add and remove the `rt-expander -open` class. I also updated the css so that the entire cell being clicked triggers the rotation of the icon and expands the sub column.  

`
.ReactTable .rt-expander {
    margin: 0;
    width: 100%;
}
`

I am using the v5.6 of the library btw. I'm not sure if this was the best way to do this, but hopefully it helps!

**Comment by aifoS1** [comment]
@trb727 could you share your custom expander component? Need to do something similar for a project. Thanks in advance.

**Comment by Ahershel** [comment]
hi, anyone could tell me how to remove the arrow for all rows? sorry if it's a very easy thing to do.. i'm still new to react and react-table.. thanks

**Comment by gary-menzel** [comment]
@Ahershel This is an implementation question that is best asked on the #react-table Slack channel.  You'll probably need to explain your use case in more detail. The first question that comes to mind is "How will the use expand the content if there is no arrow?". But as I said, these github issues are for bugs and feature request and the #react-table Slack channel is for discussion around ways to implement things. There is a badge at the top of the readme in the doco. Thanks.

**Comment by bupy7** [comment]
In ReactTable:

```js
getTrProps={(state, rowInfo, column) => {
    if (rowInfo === undefined) {
        return {}
    }
    return {
        'data-qnt': rowInfo.original.qnt,
        className: 'container-row'
    }
}}
```

In CSS:

```css
.rt-tr[data-qnt="0"] > .rt-expandable {
        visibility: hidden;
}
```

Profit.

**Comment by lrojas94** [comment]
@bupy7 quite an elegant solution! Thank you!

**Comment by rtman** [comment]
In case anyone is still wondering about this..

Here's how I did it.

This part handles the rendering of the expander component
```
const columns = [
      {
        expander: true,
        Header: () => <strong>More</strong>,
        width: 65,
        Expander: ({ isExpanded, ...rest }) => {
          if(rest.original.data.variants) {
            return(
              <div>
                {isExpanded
                  ? <div><MinusIcon/></div>
                  : <div><PlusIcon/></div>
                }
              </div>
            )
          } else {
            return null
          }
        },
      },
      ...
    ]
````

This part handles the onclick

```
         <ReactTable
            data={this.state.data}
            defaultPageSize={40}
            filterable
            style={styles.Table.reactTableContainer}
            columns={columns}
            getTdProps={(state, rowInfo, column, instance) => {
              return {
                onClick: (e, handleOriginal) => {
                  // rowInfo.original is the data you pass in, check if there is any subTableData (whatever data you are putting in the subTable) and check if you are clicking the expander column (only if you want the user to have to click on the expander button)
                  if (handleOriginal && !rowInfo.original.subTableData && column.expander) {
                    //console.log('No SubTable Data, do not handle Click')
                    null
                  } else {
                    handleOriginal();
                  }
                }
              };
            }}

``

**Comment by bpeter97** [comment]
> In ReactTable:
> 
> ```js
> getTrProps={(state, rowInfo, column) => {
>     if (rowInfo === undefined) {
>         return {}
>     }
>     return {
>         'data-qnt': rowInfo.original.SOME_VALUE_WITH_QUANTITY_OF_CHILDREN_ROWS
>     }
> }}
> ```
> 
> In CSS:
> 
> ```css
> .rt-tr[data-qnt="0"] > .rt-expandable {
>         visibility: hidden;
> }
> ```
> 
> Profit.

Fabulous! Thanks for the solution!

**Comment by bayon-adder** [comment]
Hi. Awesome work. I just have a question. The sub components arrow is missing when I transfer the 'exact same code', that works fine in an independent react project,... into a 'material-ui' based framework called xtreme by Wrappixel. Do you have any idea why that might be happening?
