### ISSUE TITLE
how to use onTrClick

### ISSUE THREAD

**Issue by ruls** [tannerlinsley/react-table#63]
I'd like to use onTrClick to achieve two things:

1. Set an 'active' class to the row
2. Retrieve that row's info and send it to another component.

Sorry for the noob question. I'm just started picking up React.

**Comment by tannerlinsley** [comment]
There is no `onTrClick` anymore.

Please use `getTrProps` like so:

```javascript
getTrProps={(state, rowInfo, column, instance) => {
  return {
    onClick: e => {
      // Do something when a tr element is clicked!
    }
  }
}}
```

As you can see, it's very easy to add other props as well :)
