### ISSUE TITLE
Sample columns don't show proper data

### ISSUE THREAD

**Issue by debuggeek** [tannerlinsley/react-table#67]
New to using project and noticed I couldn't get your simple sample to show age correctly unless I enclosed props.value in braces.
`{
    header: 'Age',
    accessor: 'age',
     render: props => <span className='number'>props.value</span> // Custom cell components!
  }`
displays age value as `props.value` vs
`{
    header: 'Age',
    accessor: 'age',
     render: props => <span className='number'>{props.value}</span> // Custom cell components!
  }`
actually displays `26` as expected.

New to React but thought I'd point out as something noticed and can help other newcomers

**Comment by tannerlinsley** [comment]
Good find
