### ISSUE TITLE
Support for "scrollable pagination/content"

### ISSUE THREAD

**Issue by jchenjc** [tannerlinsley/react-table#68]
Hi, 

Is there a plan to support "scrollable pagination", instead of pressing the "Next" button?

Also, I'm trying to customise the table (with CSS only) to have its height fixed so that I can scroll within the table (instead of scrolling the whole web page) if I render 10K rows in each page. However, I couldn't get it working, all the cells reduced their sizes and became unreadable. Is what I try to achieve possible with CSS only?

Thanks!

**Comment by tannerlinsley** [comment]
We don't plan to support any vertical scrolling in the table any time soon.  If you wanted to "mock" this with css, you would need to give each row/cell a minimum height (via `min-height`, `height`, or `flex-basis`.  Then they would not be squished when you give the table a static height.  Then set the table body to `overflow:auto`.

**Comment by jchenjc** [comment]
Thanks @tannerlinsley! I will give a try.
