### ISSUE TITLE
Rerendering table when component's state changes. How?

### ISSUE THREAD

**Issue by olegzhermal** [tannerlinsley/react-table#71]
Continuing Issue #54...
You gave access to the instance inside the component decorator callback function.

The table instance:
```
<ReactTable
  data={this.props.words}
  columns={columns}
  getTrProps={changing_state_func}
/>
```

The changing_state_func callback function:
```
changing_state_func = (state, rowInfo, column, instance) => {
  if (!rowInfo) return {}
  return {
    style: {
      background: (this.state.rowsIdsArray.includes(rowInfo.row.id)) ? 'green' : null
    },
    onClick: () => {
      this.setState({rowsIdsArray: this.state.rowsIdsArray.concat([rowInfo.row.id])});
      instance.forceUpdate()
    }
  }
}
```
Now I'd like to update the instance (as instance.forceUpdate() for example) outside the callback.
For example, I do `this.setState({rowsIdsArray: []})` inside a class method and, considering the code above, all the selections should be removed from rows. BUT the table is not rerendered when I change the state... What is the proper way to do it? Am I missing something?

**Comment by tannerlinsley** [comment]
I'm still looking at some good ways to solve this problem (stateful components within the pure table component).

Maybe putting the `forceUpdate` inside of the `setState` callback will help?  `setState` should pretty much always be treated as an asynchronous function:

```javascript
this.setState({rowsIdsArray: this.state.rowsIdsArray.concat([rowInfo.row.id])}, () => {
  instance.forceUpdate()
});
```

Let me know if that works

**Comment by olegzhermal** [comment]
Probably, you don't understand the question or I'm missing what you mean =)
How can I get access to the instance?
This part of code works fine:
```
onClick: () => {
      this.setState({rowsIdsArray: this.state.rowsIdsArray.concat([rowInfo.row.id])});
      instance.forceUpdate()
    }
```
I need to update table inside of wrapper class method:

```
export default class SomeClass extends Component {
  state = {
    rowsIdsArray:[]
  }

  changingStateFunc = (state, rowInfo, column, instance) => {
    //...
    //This works fine!
    onClick: () => {
      this.setState({rowsIdsArray: this.state.rowsIdsArray.concat([rowInfo.row.id])});
      instance.forceUpdate()
    }
  }

  clearTableSelection = () => {
    this.setState({rowsIdsArray: []})
    // here should be written smth in order table be updated
    // I don't have the instance variable here
    // So probable you can add some prop to table besides data, which trigger table update if it changes...
    // Or some other more clever solution...
  }

  render() {
    return (
      <div>
        <ReactTable
          data={this.props.words}
          columns={columns}
          getTrProps={changing_state_func}
        />
        <button onClick={this.clearTableSelection}>Update the table</button>
      </div>
      
    )
  }

}

```

**Comment by tannerlinsley** [comment]
Got it.  Yeah we were on the same page.  I have been leaning towards that,
but could you first try using a ref like this: `ref={el =>
this.tableInstance = el}`. This will let you reference the tableInstance
anywhere in your class after it has rendered.

**Comment by olegzhermal** [comment]
Oh, yeah, that was so obvious... Sorry for disturbing. This worked for me. Although I think it's not the most effective way. I would create a prop which somehow triggers rerendering of specific rows or columns, don't know how to do it though (have not time to research 'underhood' so to say =). Thanks anyway. Issue can be closed =) Have a nice day.
