### ISSUE TITLE
Table row order is messed up

### ISSUE THREAD

**Issue by wgoto** [tannerlinsley/react-table#73]
It seems the row order for data is messed up. If you have `n` number of rows for `n > 10`, the row at index `n / 2` will be the first row and row at index `1` will be in row `n / 2`.

I'm trying to use the table with control over the `onSortingChange` handler, but the order of the elements in my array provided to the `data` prop is not being preserved.

Example:

```javascript
import ReactTable from 'react-table';
import _ from 'lodash';

<ReactTable
  columns={[{ header: 'n', accessor: 'n' }]}
  data={_.times(30, n => ({ n }))}
/>
```

<img width="488" alt="screen shot 2017-02-09 at 6 17 09 pm" src="https://cloud.githubusercontent.com/assets/12705454/22811503/0c15b95e-eef4-11e6-8008-5e6419a54e9b.png">

**Comment by wgoto** [comment]
I'm trying to use the table with control over the `onSortingChange` handler, but the order of the elements in my array provided to the `data` prop is not being preserved.

**Comment by wgoto** [comment]
Example:

```javascript
<ReactTable
  columns={[{ header: 'n', accessor: 'n' }]}
  data={_.times(30, n => ({ n }))}
/>
```

**Comment by tannerlinsley** [comment]
What happens if you click the header to sort?

**Comment by wgoto** [comment]
It correctly sorts.

**Comment by tannerlinsley** [comment]
After generating your data, what does the stay look like before it goes
into the table?

**Comment by tannerlinsley** [comment]
Array *

**Comment by wgoto** [comment]
The generated data is sorted correctly before going into the table.

**Comment by tannerlinsley** [comment]
Okay. I'll try and reproduce this. Screen shot would be helpful as well

**Comment by wgoto** [comment]
Added to the original comment with the example provided. Thanks.

**Comment by tannerlinsley** [comment]
Fixed in beaa748187106bd6dd80883a6135450bf8a5541f

**Comment by wgoto** [comment]
Thank you @tannerlinsley

**Comment by tannerlinsley** [comment]
You bet :)
