### ISSUE TITLE
Override Next and Previous button

### ISSUE THREAD

**Issue by windgaucho** [tannerlinsley/react-table#76]
Hello, thanks for your great work !!

Is possible to override the className attribute of the next and previous button? (I need to use ui-semantic style buttons).

Thanks in advance.

**Comment by tannerlinsley** [comment]
Yes, what you are looking for is a component override.  There is more information in the documentation but the gist of it is passing a custom react component to either the NextComponent or PreviousComponent. Any component you pass will be decorated here: https://github.com/tannerlinsley/react-table/blob/master/src/index.js#L128 with the proper on click and disabled props.

**Comment by windgaucho** [comment]
Thank you @tannerlinsley I already saw that. I tried to override the component for Previous and Next button, copy the code for Next and Previous button (from pagination.js) but I can't get the properties (canNext, canPrevious, page, etc) in my custom component. Can you please show me an example of a custom component?

**Comment by tannerlinsley** [comment]
This is the standard button component used for both `NextComponent` and `PreviousComponent`:
```javascript
(props) => (
  <button {...props} className='-btn'>{props.children}</button>
)
```

So you could create your own `PreviousComponent` like this:
```javascript
<ReactTable
  PreviousComponent={(props) => (
    <button {...props} className='myButtonClass'>{props.children}</button>
  )}
/>
```

Just make sure to inherit and use all of the props pass to it, and to render the children from props.

**Comment by tannerlinsley** [comment]
@windgaucho Did the above example get you on the right track?

**Comment by windgaucho** [comment]
Thank you very much @tannerlinsley and I am sorry about the delay in mi response.
Yes, the example is exactly what I was looking for !! I will let you know how if it work.
