### ISSUE TITLE
Change column render function behavior

### ISSUE THREAD

**Issue by wgoto** [tannerlinsley/react-table#77]
The underlying assumption for the `render` function for columns is that it is either a `React.Component` class or a pure function. However, React Table shouldn't make this assumption, it should just be a pure function that returns any React node. The following is a use case:

```javascript
const columns = [{
  header: 'Name',
  accessor: 'name' // String-based value accessors !
}, {
  header: 'Date of Birth',
  accessor: 'dob',
  render: props => formatDate(props.value) // Separate presentation from sorted values!
}, {
  header: 'Age',
  accessor: 'age',
  render: props => <span className='number'>{props.value}</span> // Custom cell components!
}, {
  header: 'Friend Name',
  accessor: d => d.friend.name // Custom value accessors!
}, {
  header: props => <span>Friend Age</span>, // Custom header components!
  accessor: 'friend.age'
}]
```

I am currently sorting on dates, but they need to be in a localized format. I shouldn't have to wrap the dates in `span` elements to decorate them. If you want to render a `React.Component` class you can pass the function `props => <MyComponent {...props} />`.

The code at https://github.com/tannerlinsley/react-table/blob/1fec9b882fbc2074146d0457a74f9bd4dc8fb576/src/index.js#L749 should be:

```javascript
{typeof customRender === 'function' ? customRender({
  ...rowInfo,
  value: rowInfo.rowValues[column.id]
}) : typeof customRender !== 'undefined' ? customRender
: rowInfo.rowValues[column.id]}
```

**Comment by tannerlinsley** [comment]
Should be fixed in version `5.1.1` 3852227bddeba81b15a51b410cde5b49b2116b73
