### ISSUE TITLE
[Proposal] Add a noRowsComponent prop

### ISSUE THREAD

**Issue by ingro** [tannerlinsley/react-table#78]
Hello and thanks for your work on this library!

One thing I'm missing is the option to display a message for the users when the table they are looking at is empty (which could be because the server returns no data or the filters the user choose were too strict, or for whatever reason).

I would like to mantain all the standard table's layout (or at least the headers) but show a single table row with the message, something that could be accomplished on a standard html table by setting a high *colspan*  on a single `td`.

For what I'm seeing there is no way to accomplish it right now, do you think it could be a useful feature to add in the future?

Thanks for your time and sorry for my bad english!

**Comment by tannerlinsley** [comment]
I'll see if I can get this added in the next day or two.

**Comment by tannerlinsley** [comment]
You'll want to use the `noDataText` prop that was just added. It can be either string, function, or react component.  If you want even more control, you can override the `NoDataComponent`, but that probably won't be necessary.

**Comment by ingro** [comment]
Whoa thanks @tannerlinsley , I will look into it tomorrow! :)
