### ISSUE TITLE
Adding custom components to column headers in global column defaults

### ISSUE THREAD

**Issue by AchinthaReemal** [tannerlinsley/react-table#79]
Is it possible to customize all the headers (apply a global component ) through the 'column' prop (like adding an image to all headers or up and down arrows when sorting), as it seems to get overridden by the 'header' attribute in 'columns' props set.

**Comment by tannerlinsley** [comment]
You can override the core components pretty easily. https://github.com/tannerlinsley/react-table/blob/master/README.md#component-overrides. Just make sure that the custom components you use implement the necessary interfaces that the built in ones do (on click, class name merging, styles, etc)

**Comment by tannerlinsley** [comment]
If you still have issues, reopen

**Comment by safweb89** [comment]
can you please give me a usage example for overriding ThComponent ! thanks
