### ISSUE TITLE
Some broken links in docs (on React Storybook)

### ISSUE THREAD

**Issue by greyvugrin** [tannerlinsley/react-table#80]
Under the Table of Contents section, the following links do not jump.

- Custom Cell & Header Rendering
- Pivoting & Aggregation
- Sub Tables & Sub Components

Seems to be related to the ampersand (links refer to --, when ids are just -).

Hope this helps.

**Comment by tannerlinsley** [comment]
Would you like to create a pull request to fix those issues?

**Comment by tannerlinsley** [comment]
Fixed for now by avoiding `&`'s in headers. It looks like the `markdown-loader` isn't importing the ID's the same as github does for headers with `&`'s in them.  Filed an issue here: https://github.com/peerigon/markdown-loader/issues/17
