### ISSUE TITLE
Previous & Next buttons changes number of rows displayed

### ISSUE THREAD

**Issue by spacedarcy** [tannerlinsley/react-table#81]
First off, thanks for making this awesome table. Having gone through many React tables and found them wanting, this is by _far_ the best one I've used.

Anyway, my issue is: clicking the Previous and Next buttons causes the number of visible rows to decrease and increase, respectively. The row count never goes below one. This only happens when I have the 'defaultPageSize' prop set. (I tried 1, 5 and 10).

Again, thanks for making a super awesome and useful table.

**Comment by tannerlinsley** [comment]
Let's take a look shall we? Could you post your react-table setup?

**Comment by tannerlinsley** [comment]
I can't reproduce this right now.  If you want to post your setup so we can take a look, please reopen.

**Comment by spacedarcy** [comment]
Sorry, I'm waiting on word from Compliance as to whether I can post my code here.

**Comment by tannerlinsley** [comment]
Okay, sounds good.  Just reopen if and when you can :)

**Comment by friedpine** [comment]
I've meet the same problem while using 
defaultPageSize="10" which is the wrong way,  after changing to:
defaultPageSize={10}, the problem solved!
