### ISSUE TITLE
Table Footer / Column Footer Support

### ISSUE THREAD

**Issue by yanv1991** [tannerlinsley/react-table#83]
I'm adding a last row/item to put the total value of a column, but I want to avoid that last row to be sorted, how can I do that?

**Comment by tannerlinsley** [comment]
Right now that would be extremely difficult to accomplish with the existing API.  Makes me wonder if column definitions should support an optional `footer` renderer.  Thoughts?

**Comment by yanv1991** [comment]
yes that would be useful

**Comment by tannerlinsley** [comment]
This would, at the very least, introduce the need for:
- footer renderers
- optional footer accessors
- intelligent placement for calculating said footer accessors

I really like this idea actually.  It fits in well with the architecture of the table, and wouldn't take too much to make a reality.

**Comment by tannerlinsley** [comment]
Column footers are now available in version `5.3.0` 🎉

**Comment by yanv1991** [comment]
great!!! Thanks and excelent component BTW

**Comment by tannerlinsley** [comment]
Thanks! Much appreciated :)
