### ISSUE TITLE
No rows found error

### ISSUE THREAD

**Issue by theotran** [tannerlinsley/react-table#84]
I'm getting this message showing "No rows found" on the Table.
The data i'm getting is being passed as props from an Apollo(GraphQL) Provider

![screen shot 2017-02-16 at 10 53 55 am](https://cloud.githubusercontent.com/assets/13879848/23040672/435ded72-f436-11e6-97bb-beb68f303f78.png)

![screen shot 2017-02-16 at 10 57 49 am](https://cloud.githubusercontent.com/assets/13879848/23040813/cdae3676-f436-11e6-80a6-5245a5e4619c.png)

**Comment by tannerlinsley** [comment]
Fixed with 6b384f2a9002b773b37f98f340a058aa81787452

**Comment by tannerlinsley** [comment]
Upgrade to `react-table@5.3.2` :)

**Comment by theotran** [comment]
Awesome, thanks!

**Comment by tannerlinsley** [comment]
You bet!
