### ISSUE TITLE
Issue with column widths.

### ISSUE THREAD

**Issue by octalmage** [tannerlinsley/react-table#85]
Demonstration of issue: 

![](https://cloudup.com/csMjKzZNNUP+?.png)

I'm running into this issue where if I have the maxWidth set for 2 columns, after removing a column, then adding it back, the first column shrinks. 

I'm using the latest version (react-table@5.3.2), but I had the issue with 4.4.1. The column logic looks like this: 

```JavaScript
let columns = [{
  header: this.props.dimension,
  accessor: 'label',
  sortable: false,
}];

if (isPost(this.props.dimension)) {
  columns.push({
    header: 'Published Date',
    accessor: 'post_date',
    sortable: false,
    maxWidth: 250,
  });
}

columns.push({
  header: this.props.metric,
  accessor: 'value',
  sortable: true,
  maxWidth: 250,
});
```

I'll see what I can find my looking at the source, but I wanted to open an issue!

**Comment by octalmage** [comment]
Removing maxWidth resolves the issue, but then all columns are the same width.

**Comment by tannerlinsley** [comment]
Interesting. If you can, please fork this bin so we can replicate it
together. http://www.webpackbin.com/NyZ6NJktz

**Comment by octalmage** [comment]
Sure thing! It looks like the max-width is being added to the first column which shouldn't have it, but only after removing a column then adding it back. Working on stripping down an example now.

**Comment by tannerlinsley** [comment]
Okay.  Can't wait to get to the bottom of it!

**Comment by tannerlinsley** [comment]
@octalmage Were you able to get a bin of this working?

**Comment by octalmage** [comment]
I haven't had any luck getting it to work, I decided to just not use the maxWidth options for now. If I can figure out what the issue is I'll come back and reopen this. 

Thanks!
