### ISSUE TITLE
Custom cell render produces TypeError

### ISSUE THREAD

**Issue by spacedarcy** [tannerlinsley/react-table#87]
Error message: `Uncaught TypeError: Cannot read property 'isReactComponent' of undefined`

I upgraded from 4.4.1 to 5.3.2 because I was getting that unique key error when using Subcomponent, and my code now throws this error. I isolated the issue to the custom render in my columns, and was able to reproduce the problem with the following code.

`import React, {Component} from 'react';
import ReactTable from 'react-table';

class DevPage extends Component {

    constructor (props) {
        super(props);
    }

    render () {

        const data = [{
          name: 'Tanner Linsley',
          age: 26,
          friend: {
            name: 'Jason Maurer',
            age: 23,
          },
          name: 'Spacedarcy',
          age: 100,
          friend: {
            name: 'Fookimoose',
            age: 99,
          }
        }];

        let columns = [{header: 'Name',
                        accessor: 'name',
                        render: props => <span>{props.value}</span>
                     }];

        return (<ReactTable className="-striped -highlight"
                            columns={columns}
                            data={data}/>
        );
    }
}

module.exports = DevPage;
`

Here's the full error message:

`Uncaught TypeError: Cannot read property 'isReactComponent' of undefined
    at Object.normalizeComponent (http://localhost/static/js/build.js:114734:53)
    at http://localhost/static/js/build.js:113571:31
    at Array.map (native)
    at makePageRow (http://localhost/static/js/build.js:113467:29)
    at http://localhost/static/js/build.js:113742:22
    at Array.map (native)
    at makeTable (http://localhost/static/js/build.js:113741:22)
    at Object.render (http://localhost/static/js/build.js:113770:63)
    at http://localhost/static/js/build.js:95782:21
    at measureLifeCyclePerf (http://localhost/static/js/build.js:95061:12)`

**Comment by tannerlinsley** [comment]
Could you replicate it in a fork of this web pack bin? http://www.webpackbin.com/NyZ6NJktz Then we can try to get to the bottom of it.

**Comment by spacedarcy** [comment]
It works in the webpack bin, but not in my dev environment. Probably worth mentioning at this point that we're not using webpack.

**Comment by tannerlinsley** [comment]
But you're using Babel right? Jsx transpiler?

**Comment by spacedarcy** [comment]
Yes

**Comment by tannerlinsley** [comment]
Interesting. I would love to see the compiled code or even what the
function/object looks like where that error is being thrown

**Comment by spacedarcy** [comment]
`'use strict';

var _react = require('react');

var _react2 = _interopRequireDefault(_react);

var _reactTable = require('react-table');

var _reactTable2 = _interopRequireDefault(_reactTable);

function _interopRequireDefault(obj) {
    return obj && obj.__esModule ? obj : { default: obj };
}

class DevPage extends _react.Component {

    constructor(props) {
        super(props);
    }

    render() {

        const data = [{
            name: 'Tanner Linsley',
            age: 26,
            friend: {
                name: 'Jason Maurer',
                age: 23 }
        }, {
            name: 'Spacedarcy',
            age: 100,
            friend: {
                name: 'Fookimoose',
                age: 99
            } }];

        let columns = [{ header: 'Name',
            accessor: 'name',
            render: props => {
                return _react2.default.createElement('span', null, props.value);
            }
        }];

        return _react2.default.createElement(_reactTable2.default, { className: '-striped -highlight',
            columns: columns,
            data: data });
    }
}

module.exports = DevPage;`

**Comment by tannerlinsley** [comment]
Does it work if you use react component instead of a stateless component?

**Comment by spacedarcy** [comment]
You mean use React.createComponent?

**Comment by spacedarcy** [comment]
Update: custom renderer is working!

Here's my code, for posterity. (I build my columns in a loop, for reasons):

`    getCellRenderer (option) {
        const {customRender, type} = this.props;

        return(
            React.createClass({
                render: function () {
                    let {row} = this.props;
                    return <div>{StringUtils.formatSingleMetadata(row, option)}</div>;
                }
            })
        );
    }
`
...
 `let column = (customRender) ?
                         customRender(option, pretty, type, width) :

                        //default render
                        [{header: pretty,
                         accessor: option,
                         width: width,
                         render: cellRenderer}];`
...

**Comment by tannerlinsley** [comment]
I’m still curious as to why stateless components don’t work for you.
Thoughts?

**Comment by spacedarcy** [comment]
No idea. Could be our build system, which is really sketchy.

**Comment by tannerlinsley** [comment]
Interesting. Well, if you get to the bottom of it, please post back here
for posterity :)

**Comment by spacedarcy** [comment]
Possibly worth noting for more context: SubComponents *do* let me use anonymous functions.
 ¯\_(ツ)_/¯

`SubComponent={(row) => { return subcomponent(row)}}/> :`

**Comment by spacedarcy** [comment]
As of the latest version of react-table I no longer receive this error!
