### ISSUE TITLE
Custom sort function

### ISSUE THREAD

**Issue by RalphSleigh** [tannerlinsley/react-table#88]
Hi

Sorry if this exists already, but I think it would be nice to be able to pass a custom sort function for a column, probably as part of the columns configuration object e.g:

```
const  columns =[{
    accessor:"foo",
    header:"Foo",
    sortable:true,
    sortFunction: (a, b) => a > b ? 1 : -1},
...]

```

**Comment by tannerlinsley** [comment]
This would, in fact, be very nice. I'll look at implementing it in the next few days :)

**Comment by tannerlinsley** [comment]
I will probably also lump into that release, a hook for overwriting the entire sorting algorithm for the table. Thoughts?

**Comment by cesalberca** [comment]
Hi! I'm loving the plugin, great work! I don't know if this is the appropriate space to ask questions but it has to do with this issue. While you implement custom sortFunctions how could I go about implementing something of my own? I need to sort not alphabetically but in other way. Cheers!

**Comment by eladbs** [comment]
@tannerlinsley Any updated on the issue?
Thanks in advance for implementing it!

**Comment by jacobmischka** [comment]
Sorry, is there any update on this? I've got some dates that I would like to display in the table and sorting alphabetically by month name isn't very useful. Thanks!

**Comment by tannerlinsley** [comment]
Hey there.  Still working on this at the moment.  It’s a bit more
complicated that I previously thought. Should have it out soon, but I can’t
make any promises on timeline :(  If you want to take a stab at it, feel
free and we can work through it together.

**Comment by jacobmischka** [comment]
Thanks for the quick response, I'll take a look.

**Comment by jacobmischka** [comment]
I threw [something](https://github.com/jacobmischka/react-table/tree/sort-accessor) together. It's not exactly the ability to add a custom sort function, instead it allows you to set a `sortAccessor` on a column declaration, which is then to used to get the value that it sorts by. The sorting itself is still done in the same place as it was before, but this allows people to specify a value to use instead of just the text string.

So this isn't really a complete "custom sort function" solution, but it's all that I need and should probably be able to satisfy most use-cases.

Example:

```jsx
<ReactTable className="requests-table"
	data={row.requests}
	columns={[
		{
			header: 'Location',
			id: 'location',
			accessor: request =>
				request.requestedLocation.name
		},
		{
			header: 'Dates',
			id: 'dates',
			accessor: request =>
				displayDateRange(request.requestedDate),
			sortAccessor: request => {
				console.log(request);
				return moment(request.requestedDate[0]).valueOf();
			}
		},
		{
			header: 'Requested',
			id: 'requestTime',
			accessor: request =>
				displayDate(request.requestTime),
			sortAccessor: request =>
				moment(request.requestTime).valueOf()
		},
		{
			header: 'Reason',
			accessor: 'requestedReason'
		},
		{
			header: 'Status',
			id: 'status',
			accessor: request =>
				ucfirst(request.status)
		}
	]}
	pageSize={row.requests.length}
	showPagination={false} />
```

![peek 2017-03-22 16-46](https://cloud.githubusercontent.com/assets/3939997/24222194/4225d5b0-0f1f-11e7-8136-65a6a627586a.gif)

What do you think?

**Comment by tannerlinsley** [comment]
I think that’s cool, but one thing you might want to try is this:

- for the column `accessor`, just pass regular date object
- for the column `render`, pass the formatted date

This doesn’t solve the customSorting function, but it will solve your
specific problem I think. Javascript can sort normal date objects, which is
exactly what `accessor` is for (to pass the data that sorting and pivoting
should use), you can then just format the date in the renderer.

**Comment by jacobmischka** [comment]
Oh, you're right that is better. Thanks!

**Comment by tannerlinsley** [comment]
👍😉

**Comment by epitaphmike** [comment]
I have added a component into the render of a column and passed props.row to the component to render the correct component. Unfortunately if I sort on a different column the component column doesn't sort.

Any ideas?

![sort](https://cloud.githubusercontent.com/assets/677832/24430936/236a3b3a-13e7-11e7-98b8-e3945d565815.gif)

**Comment by tannerlinsley** [comment]
@epitaphmike Let's chat in the slack channel :)

**Comment by epitaphmike** [comment]
Join our Slack team with your @29degre.es email:
https://29degrees.slack.com/signup

**Comment by epitaphmike** [comment]
Where's the invite to that team?

**Comment by tannerlinsley** [comment]
Click the slack badge on the readme

**Comment by epitaphmike** [comment]
Just found it. https://react-chat-signup.herokuapp.com/

**Comment by epitaphmike** [comment]
Just signed in.

**Comment by jeffklassen** [comment]
@tannerlinsley I like the idea of having accessor control the sorting/pivoting while render controls how the row is displayed. However, the following configuration seems to use the accessor function to control rendering:

```
const sortedDays = day => {
    switch (day) {
        case '6-Week Groups':
            return 1;
        case 'Sunday':
            return 2;
        case 'Monday':
            return 3;
        case 'Tuesday':
            return 4;
        case 'Wednesday':
            return 5;
        case 'Thursday':
            return 6;
        case 'Friday':
            return 7;
        case 'Saturday':
            return 8;
    }
};

const columns = [
    {
        id: 'dayOTW',
        header: 'Day',
        accessor: (row) => {
            return sortedDays(row.dayOfTheWeek);
        },
        render: (row) => {
            return <span>{row}</span>;
        }
    },
//...
 ```

<img width="193" alt="screen shot 2017-04-11 at 8 14 58 am" src="https://cloud.githubusercontent.com/assets/7376576/24895117/02ab3c7a-1e8f-11e7-9516-022e02166cd6.png">

**Comment by tannerlinsley** [comment]
So to clarify your question, the accessor is what provides the `value` property to the renderer.  But, this doesn't mean that the renderer doesn't have access to the entire row still. This way of doing things essentially allows your renderer to quickly and easily reference the data your accessor has provided you without having to rewrite or reuse the logic in the accessor. Right out of the docs: 
```
render: JSX eg. (rowInfo: {value, rowValues, row, index, viewIndex}) => <span>{value}</span>, // Provide a JSX element or stateless function to render whatever you want as the column's cell with access to the entire row
    // value == the accessed value of the column
    // rowValues == an object of all of the accessed values for the row
    // row == the original row of data supplied to the table
    // index == the original index of the data supplied to the table
    // viewIndex == the index of the row in the current page
```

 If you truly wanted to sort by something completely different than what you were displaying, you could easily do that doing something like this: 

```javascript
id: 'fullNameSortableByLastName',
accessor: d => d.lastName,
render: rowInfo => <span>{rowInfo.row.firstName} {rowInfo.row.lastName}</span>
```

Even thought you are using the `lastName` value as the accessor doesn't mean that you can't display other data.  This simply means that `lastName` will be used to sort, filter, and pivot the column, while the render function pulls from the original row to show the full name.

**Comment by jeffklassen** [comment]
So then this should 
- spit out a bunch of messages to the console, and
- render correctly
right?

``` const sortedDays = row => {
    switch (row.dayOfTheWeek) {
        case '6-Week Groups':
            return 1;
        case 'Sunday':
            return 2;
        case 'Monday':
            return 3;
        case 'Tuesday':
            return 4;
        case 'Wednesday':
            return 5;
        case 'Thursday':
            return 6;
        case 'Friday':
            return 7;
        case 'Saturday':
            return 8;
        default:
            return 9;    
    }
};

const columns = [
    {
        id: 'dayOTW',
        header: 'Day',
        accessor: sortedDays,
        render: ({ row }) => {
            console.log('TEST Row', row)
            return <span>{row.value}</span>;
        }
    }, ```

**Comment by madeinspace** [comment]
I have an issue with sorting that pretty much would be a show stoper for me:

I have a series of ranges ie:

0 to 4
5 to 9
10 to 14
...
45 to 49

when I sort this column the "5 to 9" row goes after the "45 to 49" row: 

0 to 4
10 to 14
...
45 to 49
5 to 9


 I kind of understand what's going on but can't explain why it's been implemented that way. 

Is there a fix? thanks!

**Comment by madeinspace** [comment]
I think this has to do with natural sort order (https://en.wikipedia.org/wiki/Natural_sort_order) is there a way to implement natural sort order?

**Comment by tannerlinsley** [comment]
There will be very soon. Hang tight.

**Comment by madeinspace** [comment]
that's great news thanks! :)

**Comment by snirlugassy** [comment]
Is there some way to do it meanwhile? one accessor but custom values for the sort?
I have a column with status of the row based on strings, such as "done" / "new", 
and I want to prioritize the statuses (for example "new" first with defaultSorting).
Thanks!

**Comment by aaronschwartz** [comment]
@snirlugassy You can try transforming your accessor into a value that will sort how you want it to. 

Column definition for Status column:
```
{
  id: 'status',
  accessor: x => x.status == "new" ? 1 : 2,
  render: ({row}) => <span>{row.status}</span>
}
```

**Comment by snirlugassy** [comment]
still, doesn't work, it seems the accessor receives only strings

**Comment by snirlugassy** [comment]
OK I used a different method, and maybe some of you will find it handy:

Basically, i used 'Axios' to fetch the data from the node server.

Later, in the promise '.then()' I checked if values are null and manipulated the data so each pointer (accessor in this case) will point to one type of variable (the sorting is going 'crazy' when there are 2 types involved - AFAIK).

```
response.data.map(order => {
  if(typeof(order.is_order_shipped) == 'undefined' || order.is_order_shipped === null){
    order.is_order_shipped = "false";
  }
  if(order.is_order_shipped === true){
    order.is_order_shipped = "true";
  }
}
```

**Comment by tannerlinsley** [comment]
In the next major release, you will be able to control the default `sortMethod` for the entire table instance, and also individual `column.sortMethod`s.  Stay tuned.

**Comment by tannerlinsley** [comment]
Now available in version 6.0

**Comment by jacobmischka** [comment]
Great work!

**Comment by PranavBhatia** [comment]
Hi, I have a question. If some values of the column we want to sort are null (undefined), sorting gives the result with the empty rows first.
Is there a way to put the empty ones in the end and sort the rows that have values first?
I am sorry if this is not the right place to ask questions and thanks in advance

**Comment by iKrushYou** [comment]
> In the next major release, you will be able to control the default `sortMethod` for the entire table instance, and also individual `column.sortMethod`s. Stay tuned.

Sorry to revive this ooold issue but has this functionality been removed?

**Comment by ongelo** [comment]
@iKrushYou seems like it is now called `sortType`: https://react-table.tanstack.com/docs/api/useSortBy#column-options
