### ISSUE TITLE
How to add Link to a cell?

### ISSUE THREAD

**Issue by friedpine** [tannerlinsley/react-table#89]
Is it possible to add link(in react-router) to the cells of a column?

**Comment by nikhilag** [comment]
How did you manage to solve it? 
I am trying to use react-router with react-table.

**Comment by tannerlinsley** [comment]
In the Cell renderer just use the react router Link component

**Comment by mikedevita** [comment]
```jsx
import { Link } from 'react-router';

const columns = [
  {
    header: '',
    id: 'links',
    render: ({ row }) => (<Link to={{ pathname: `/foo/${row.id}` }}>{row.name}</Link>)
  }
];
```

**Comment by nikhilag** [comment]
Thanks @tannerlinsley and @mikedevita .
Is it possible to use <Link> when clicking on a row instead of just a cell?

**Comment by Skylsmoi** [comment]
@nikhilag 

I've managed to do it by overriding TrGroupComponent prop
Here's my code :  
```
<ReactTable
  data={searchResult}
  columns={[{
    Header: 'Libellé matière',
    accessor: 'materialDescription'
  }, {
    Header: 'Code thème',
    accessor: 'themeCode'
  }, {
    Header: 'Libellé thème',
    accessor: 'themeDescription'
  }, {
    Header: 'Marque',
    accessor: 'brand'
  }, {
    Header: 'Nature',
    accessor: 'nature'
  }, {
    Header: 'Typologie',
    accessor: 'type'
  }, {
    Header: 'Code Bdd',
    accessor: 'codeBdd'
  }, {
    Header: 'Code Sap',
    accessor: 'codeSap'
  }, {
    Header: 'VariationId',
    accessor: 'variationId',
    headerStyle: {display: 'none'},
    style: {display: 'none'}
  }]}
  TrGroupComponent={((compClass, displayName) => {
    if (!displayName) {
      throw new Error('No displayName found for template component:', compClass)
    }
    const cmp = ({ children, className, ...rest }) =>
      Array.isArray(children) // if the array is empty, children isn't an array, use standard react-table display fallback
       ? <Link
         to={`${PAGE_LIST.VIEW_MATERIAL}/${children[0].props.children[6].props.children + '/' + children[0].props.children[8].props.children}`}
         className={classnames('searchresult__item', compClass, className)} {...rest}>
         {children}
       </Link>
      : <div className={classnames(compClass, className)} {...rest}>
        {children}
      </div>
    cmp.displayName = displayName
    return cmp
  })('rt-tr-group', 'TrGroup')}
/>
```

The overriding function is a copy of makeTemplateComponent (utils.js) as an IIFE, I only rewrited `cmd`


As you can see, I generate the href (prop 'to') with the data from the children (which are the cells). Here, I use the column `accessor: 'codeBdd'` but I also required an info that shouldn't be in the table (`accessor: 'variationId',`), so I added it with `display: 'none'`.  

It feels a bit hacky but it works.

I'm looking forward for a better solution

**Comment by aaronschwartz** [comment]
@Skylsmoi Why does it have to be a `<Link/>` component? 
I think it would be cleaner to just do something like this:
```
getTrProps: (state, rowInfo)=> {
  return {
    onClick: ()=> this.props.history.push(`${PAGE_LIST.VIEW_MATERIAL}/${rowInfo.row.[columnName]}}`)
  }
}
```
You may need to wrap your entire component with the `withRouter` HOC from react-router.

**Comment by Skylsmoi** [comment]
@aaronschwartz I dont, your solution work and is way cleaner !
Thx !

**Comment by TreborOB** [comment]
Cell: ({ row }) => (<Link to={{ pathname: `/foo/${row.name}` }}>{row.name}</Link>)

I simply changed 'render' to 'cell' in the code snippet from mikedevita's answer and it worked for me.

**Comment by bocodigital** [comment]
None of these solutions work. I have tried them all. I think there is an issue with React Table and the router.

**Comment by arkn98** [comment]
> `Cell: ({ row }) => (<Link to={{ pathname: `/foo/${row.name}` }}>{row.name}</Link>)`
> 
> I simply changed 'render' to 'cell' in the code snippet from mikedevita's answer and it worked for me.

I'm doing exactly the same thing. But for some reason, links are not clickable. I can hover over them & I can go to the link using right click menu and the enter keys. But primary click is not taking me anywhere. Can anyone help? It's a simple table that loads data from props (redux).

**Comment by arkn98** [comment]
Okay. I sorted things out. I was using `react-onclickoutside` from [here](https://github.com/Pomax/react-onclickoutside) on some components. It had an onClick listener on the entire page which was not propagating clicks to the DOM elements. But it is weird that only the links inside `react-table` were un-clickable; all other things were normal.

**Comment by anilsingh581** [comment]
I have tried the above solutions but need a bit modification i.e.
```
const columns = [
  ...,
  {
    Header: 'Name',
    accessor: 'name',
    Cell: ({ row }) => (<Link to={{pathname:'/editpage/'+`${row.id}`, state :{data : row} } }>{row.name}</Link>),
    filterable : true
  },
  ...
]
```

**Comment by skyrbs** [comment]
Hello Everyone,
 
i am not able to pass e.id or my dataset id.. Can you please let me know what i am missing ?
Note:  Proper Link is ready but not able to pass product id at end or url..


const columns =[
        {
            Header: "Name",
            accessor: "name",
            filterable: true
        },
        { 
            Header: "Action",
            Cell: e =><Link to={`/admin/product/update/${e.id}`}>
                  <span className="badge badge-warning badge-pill">  Update </span>
                    </Link>,            
            filterable: false,
            sortable:false
        }
    ]


<ReactTable 
         columns={columns}
         data = {products}
         filterable
         sortable
         defaultPageSize={5}
         noDataText={"Please wait ...loading"}
      >

**Comment by ankitparsana** [comment]
@TreborOB Thanks for your solution works for me.
a slight change for the display cell and get a cell id name here.
`Cell: ({ row }) => (
          <Link to={{ pathname: `/brand/edit-brand/${row.values.id}` }}
{row.values.name}
</Link>
),`

**Comment by sibiyan** [comment]
> @TreborOB Thanks for your solution works for me.
> a slight change for the display cell and get a cell id name here.
> Cell: ({ row }) => (
> <Link to={{ pathname: `/brand/edit-brand/${row.values.id}` }}
> {row.values.name}
> 
> ),

this helped me too

**Comment by Vishakh-vcc** [comment]
> Okay. I sorted things out. I was using `react-onclickoutside` from [here](https://github.com/Pomax/react-onclickoutside) on some components. It had an onClick listener on the entire page which was not propagating clicks to the DOM elements. But it is weird that only the links inside `react-table` were un-clickable; all other things were normal.

how did you solve this issue... can you suggest your solution...even i am unable to get the click event and navigation to next page

**Comment by tzpranto** [comment]
> `Cell: ({ row }) => (<Link to={{ pathname: `/foo/${row.name}` }}>{row.name}</Link>)`
> 
> I simply changed 'render' to 'cell' in the code snippet from mikedevita's answer and it worked for me.

I just had to change row.name to row.original.name and it worked for me.

**Comment by dlsso** [comment]
Note: most of these suggestions do not turn the **cell** into a link, only the **cell content**. If you have cell padding and want the link to work when you click anywhere this does not work.

Looks @aaronschwartz suggestion may address that issue, but in the app I'm working on they are feeding in an array of column objects with [these options](https://react-table.tanstack.com/docs/api/useTable#column-options), and it doesn't look like it works in that situation.

**Comment by nis6** [comment]
@bocodigital were you able to find the solution for react-router and table? 
 I am trying smthg similar, nothing worked so far, here's the code
```css 
const MenuLink = styled(Link)`
  text-decoration: none;
  text-transform: capitalize;
  color: #a4a3a4;
  font-size: 1rem;
  &:hover {
    color: ${colors.ivory100};
    transition: all 0.5s ease;
    cursor: pointer;
  }
  @media (min-width: 700px) {
    font-size: 2rem;
  }
`;
```

```js
<Table>
        <tbody>
          <tr>
            <td
              style={{
                padding: "2rem",
                borderRight: `1px solid ${colors.indianred}`,
                textAlign: "right",
              }}
            >
              <Link to="/">Home</Link>
            </td>

            <td
              style={{
                padding: "2rem",
                borderBottom: `1px solid ${colors.marigold}`,
              }}
            >
              <MenuLink to="/">Library</MenuLink>
            </td>
          </tr>
        </tbody>
        <tbody>
          <tr>
            <td
              style={{
                padding: "2rem",
                borderTop: `1px solid ${colors.pine}`,
                textAlign: "right",
              }}
            >
              <MenuLink to="/">Register</MenuLink>
            </td>
            <td
              style={{
                padding: "2rem",
                borderLeft: `1px solid ${colors.oliverhaze}`,
              }}
            >
              <MenuLink to="/">Log in</MenuLink>
            </td>
          </tr>
        </tbody>
      </Table>
```
will appreciate any suggestions.

**Comment by NinjaAniket** [comment]
> > `Cell: ({ row }) => (<Link to={{ pathname: `/foo/${row.name}` }}>{row.name}</Link>)`
> > I simply changed 'render' to 'cell' in the code snippet from mikedevita's answer and it worked for me.
> 
> I just had to change row.name to row.original.name and it worked for me.

strange but 
row.original.name worked for me thanks!

**Comment by qqpann** [comment]
It's now small lettered cell as of v8.9

```ts
cell: ({ row }) => {
        return (
          <Link
            href={
              // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
              routes.page(row.original.page_id).home
            }
          >
            <span className="hover:underline">{row.original.title}</span>
          </Link>
        )
      },
```
