### ISSUE TITLE
Consider passing full props to sub components

### ISSUE THREAD

**Issue by manuxio** [tannerlinsley/react-table#90]
In order to achieve a "fixed height" table body, I had to override TbodyComponent as per your documentation.

Unfortunately, I had also to wrap the whole component in a class, because react-table props are not passed to the generating function.

My solution:

```
const createComp = function createComp(compClass, fullprops) {
  return ({ children, className, ...rest }) => { // eslint-disable-line
    const {
      bodyHeight
    } = fullprops;
    if (typeof bodyHeight !== 'undefined') {
      return (
        <div
          style={{
            height: `${bodyHeight}px`
          }}
        >
          <Scrollbar>
            <div
              className={classnames(compClass, className)}
              {...rest}
            > {children} </div>
          </Scrollbar>
        </div>
      );
    }
    return (
      <div
        className={classnames(compClass, className)}
        {...rest}
      >
        {children}
      </div>
    );
  };
};

export default class UniversalTable extends Component {
  render() {
    const { props } = this;
    return (
      <ReactTable
        {...props}
        TbodyComponent={
          createComp('rt-tbody', props)
        }
      />
    );
  }
}
```

Reason behind:

```
<TbodyComponent
            className={classnames(tBodyProps.className)}
            style={{
              ...tBodyProps.style,
              minWidth: `${rowMinWidth}px`
            }}
            {...tBodyProps.rest}
          >
            {pageRows.map((d, i) => makePageRow(d, i))}
            {padRows.map(makePadRow)}
</TbodyComponent>
```

This could be avoided by passing full props to sub component, like this:

```
<TbodyComponent
            rootProps={rootProps}
            className={classnames(tBodyProps.className)}
            style={{
              ...tBodyProps.style,
              minWidth: `${rowMinWidth}px`
            }}
            {...tBodyProps.rest}
          >
            {pageRows.map((d, i) => makePageRow(d, i))}
            {padRows.map(makePadRow)}
</TbodyComponent>
```

Would you accept a PR for that?
If that would be implemented, I could have just avoided one wrapping...

Thanks,
M.

**Comment by tannerlinsley** [comment]
So let me make sure I understand what you're saying. You want every single internal component to gain a `rootProps={this.props}` prop, so those components can respond to different scenarios produced from the props sent to the ReactTable component.

Correct?

**Comment by manuxio** [comment]
That's the idea, yes. 
I think that would boost the ability to fully use component customization...

M.

**Comment by tannerlinsley** [comment]
Go for it! 👍

**Comment by manuxio** [comment]
Will PR as soon as possible...

**Comment by tannerlinsley** [comment]
This is still a valid issue, but hasn't been brought up much in the past few weeks. I will still consider the implementation after it gets updated, but this is not a pressing issue for the majority use case.  Reopen if appropriate :)
