### ISSUE TITLE
ReactTableDefaults export undefined

### ISSUE THREAD

**Issue by d-winter** [tannerlinsley/react-table#92]
Hi,
I saw you removed the named export `ReactTableDefaults` from the index.js file.
I have imported the the ReactTableDefaults like this before:
`import ReactTable, { ReactTableDefaults } from 'react-table';`
In the example within the readme it is still imported this way. Could you tell me what's the right way to import the defaults?
Best
Daniel

**Comment by tannerlinsley** [comment]
That's a bug. 🐛 we need to get that fixed asap. Could you send a PR ?

**Comment by d-winter** [comment]
Should I just insert the old export again?

**Comment by tannerlinsley** [comment]
The file location changed. So you just need to change the import in
index.js. See it?

**Comment by d-winter** [comment]
Yepp, here it is

**Comment by terencechow** [comment]
FYI, installing from npm today did not fix this issue.
