### ISSUE TITLE
Possible to set a column width based on the longest cell width?

### ISSUE THREAD

**Issue by sshaginyan** [tannerlinsley/react-table#94]
How can I make the columns automatically adjust the the longest text a corresponding cell?

**Comment by tannerlinsley** [comment]
You would probably need to do that dynamically by measuring the text
beforehand and adjusting the column width accordingly. Since the text and
table style cannot be consistently measured for every single scenario, this
is likely something that would turn into a plugin instead of a core feature

**Comment by spacedarcy** [comment]
I did something like this. Not great, but it works.

` getColumnWidth (accessor, headerText) {
        let {data} = this.state;
        let max = 0;

        const maxWidth = 400;
        const magicSpacing = 18;

        for (var i = 0; i < data.length; i++) {
            if (data[i] !== undefined && data[i][accessor] !== null) {
                if (stringify(data[i][accessor] || 'null').length > max) {
                    max = stringify(data[i][accessor] || 'null').length;
                }
            }
        }

        return Math.min(maxWidth, Math.max(max, headerText.length) * magicSpacing);
    }`

The last bit ensures the width doesn't go over a universal maximum, and is never smaller than the header text (because that's annoying AF).

**Comment by tannerlinsley** [comment]
That's exactly what I would have done.

**Comment by sshaginyan** [comment]
Thanks guys

**Comment by eric-burel** [comment]
Hi @spacedarcy, I might ask the stupid question here, but how/where do you use this function ? In ReactTable props or did you build a wrapper around it ?

**Comment by izaleu** [comment]
A wrapper.

**Comment by tayan-serna** [comment]
@spacedarcy Could you please give a little example? I think i'm kind of miss :S

**Comment by dbertella** [comment]
Based on @spacedarcy answer I rewrote the function to something like this:
```
const getColumnWidth = (rows, accessor, headerText) => {
  const maxWidth = 400
  const magicSpacing = 10
  const cellLength = Math.max(
    ...rows.map(row => (`${row[accessor]}` || '').length),
    headerText.length,
  )
  return Math.min(maxWidth, cellLength * magicSpacing)
}
```
Not sure about the `magicSpacing` 10 seems to work for me, I guess it's about your font size, and I also have to handle pivoting. To use this I just call the function in the columns definitions something like:
```
{
  Header: 'My header',
  accessor: 'accessor',
  width: getColumnWidth(rows, 'accessor', 'My header'),
},
```
Hope this helps

**Comment by surajba** [comment]
@dbertella how you passing rows to getColumnWidth method. 

I get ReferenceError: rows is not defined, would really appreciate your help

**Comment by dbertella** [comment]
rows is whatever you pass as data to your table, so a complete example is this:
```js
<ReactTable
          data={data}
          columns={[
            {
                Header: 'My header',
                 accessor: 'accessor',
                 width: getColumnWidth(data, 'accessor', 'My header'),
             },
          ]}
          defaultPageSize={10}
          className="-striped -highlight"
        />
```

**Comment by surajba** [comment]
@dbertella Thanks!

**Comment by dbertella** [comment]
well your accessor is the whole function I guess, did you with `moment(d.partner_created_date)` I guess you have an object with `2018-01-01` as a key, not sure but basically you have to pass wathever is the key because it needs to work inside the map as: `row[accessor]` so in your case possibly should be `row['2018-01-01']` (I'm guessing). If it doesn't work I'm afraid you should come up with something more custom sorry

**Comment by parwat08** [comment]
Yes I guess more custom, Not a problem with date

`accessor: d => moment(d.partner_status),`

`width:(d) => getColumnWidth(this.state.partners, (d.partner_status), "Status")`

even nothing gets logged inside getColumnWidth function

Any Idea where break and start

**Comment by dbertella** [comment]
oh I see sorry, yeah no that will not work because width is not expecting a function there, just a value so `d` will be undefined I don't know how you can work around this. You will have to find somehow how to provide the name of the property you want to check inside your object.

**Comment by natakina** [comment]
Thanks guys, it works. But what about general table with. I have a lot of tables on the different pages and when there are few colums on wide screens the last column of the table takes all free space and becomes too wide, maxWidth for this column visually doesn't works

**Comment by HamsterHuey** [comment]
Thanks @dbertella. I made another slight tweak to make the accessor accept both strings and functions. The latter adds some more flexibility to the use of this function.

```javascript
const getColumnWidth = (data, accessor, headerText) => {
  if (typeof accessor === 'string' || accessor instanceof String) {
    accessor = d => d[accessor]; // eslint-disable-line no-param-reassign
  }
  const maxWidth = 600;
  const magicSpacing = 10;
  const cellLength = Math.max(
    ...data.map(row => (`${accessor(row)}` || '').length),
    headerText.length,
  );
  return Math.min(maxWidth, cellLength * magicSpacing);
};
```

**Comment by dbertella** [comment]
Good one thank you!

**Comment by oldo** [comment]
And one finally improvement, to allow string accessors of type `'objectA.objectB'` you can use `lodash.get()` and also a check if value is a number along with conversion to string:

```javascript
export const getColumnWidth = (data, accessor, headerText) => {
  const cellLength = Math.max(
    ...data.map(row => {
      let value = '';

      if (typeof accessor === 'string') {
        value = _.get(row, accessor);
      } else {
        value = accessor(row);
      }

      if (typeof value === 'number') return value.toString().length;
      return (value || '').length;
    }),
    headerText.length
  );

  const magicSpacing = 12;
  return cellLength * magicSpacing;
};
```

**Comment by septe01** [comment]
> rows is whatever you pass as data to your table, so a complete example is this:
> 
> ```js
> <ReactTable
>           data={data}
>           columns={[
>             {
>                 Header: 'My header',
>                  accessor: 'accessor',
>                  width: getColumnWidth(data, 'accessor', 'My header'),
>              },
>           ]}
>           defaultPageSize={10}
>           className="-striped -highlight"
>         />
> ```
> 
> Edit the above will work just if data in this case is an array, for an object you will need to modify the helper, since I'm using `...row.map`

how to implementation in v.7

**Comment by devniel** [comment]
Just in case someone is looking for this feature, right now it's easily done with `useGridLayout` , it's not in the docs nor `@types/react-table`.

**Comment by ikiw** [comment]
@devniel : Do you have a sample code snippet using useGridLayout ?

**Comment by lukesmurray** [comment]
before anyone else spends time trying it `useGridLayout` with `display: contents` does not seem to work with `react-window`.
