### ISSUE TITLE
Backward compatibility for Object.entries in safari browser

### ISSUE THREAD

**Issue by vaidsu** [tannerlinsley/react-table#96]
I found that Object.entries was not defined in safari. It worked fine in Chrome and Firefox. 

Found https://github.com/es-shims/Object.entries and incorporated that. Then it worked. 

Attaching the diff, please check. If you suggest a different way (I even tried babel-polyfill) please let me know. Else, I can provide a PR. 

```javascript
// In methods.js
// npm install --save object.entries
import { entries } from 'object.entries'

if (!Object.entries) {
  entries.shim();
}
```

**Comment by tannerlinsley** [comment]
So react table doesn't work in safari for you?

**Comment by vaidsu** [comment]
Yes I am getting Object.entries is undefined error. I use Version 10.0.3 (11602.4.8.0.1). I have a private copy that works with the above diff. If you wish to see the console debugger I can send. 

Thanks again.

**Comment by tannerlinsley** [comment]
Interesting.  It works in my safari, v10.0.2.  Are you on a mac or windows?

**Comment by vaidsu** [comment]
I tried to clean the cache, and cleared my modules, then tried again. 

Like you said, **it started working**. I still don't understand why I got the Object.entries issue or if babel-polyfill is somehow helping. 

In any case I would like to close this for now until I see that issue again. 

Thanks for your help and wrong alarm.

**Comment by tannerlinsley** [comment]
No worries! 😊
