### ISSUE TITLE
Not an issue but Question: How to make cell editable?

### ISSUE THREAD

**Issue by westerhofffl** [tannerlinsley/react-table#97]
Hi! This table is great!  Is there a  columns default so the cell data is editable?

**Comment by tannerlinsley** [comment]
This isn't built in, as you've discovered, but it is possible. Just keep some state externally if a cell should be editable or not. Then, if the cell should be editable, update that state. There are many ways to do this. Its the same as plain old react state. 

To update the data in the cell, use set state to update the data before its sent into the table. 

Hope this makes sense. Its rather conceptual. I'm on my cell phone right now. ;)

**Comment by westerhofffl** [comment]
Got it!

Thanks  will follow up if I get lost:)
